### ISSUE TITLE
No stand alone zip file in latest 2.4.1 release

### ISSUE THREAD

**Issue by nacho4d** [jasmine/jasmine#1001]
Unlike other releases, 2.4.1 does not have a jasmin-standalone-2.4.1.zip file.
Newbies like me might have some problems to start :( 

https://github.com/jasmine/jasmine/releases

Are there any instructions on how to make a standalone from the source?

**Comment by slackersoft** [comment]
Sorry about that, I totally forgot to upload it. It should be there now.

Thanks for the find!

**Comment by nacho4d** [comment]
Awesome! .Thank you very much
