### ISSUE TITLE
TypeError: 'undefined' is not a constructor

### ISSUE THREAD

**Issue by drewbarontini** [jasmine/jasmine#1002]
_Running the jasmine-gem with Jasmine 2.4.0_

With a setup similar to the following (in CoffeeScript):

```coffee
class @Base
  constructor : ( @options ) ->
    @_settings = $.extend( {}, @constructor._defaults, @options )

class @SubClass extends Base
  @_defaults :
    test : true

  constructor : ->
    super
    
    # ...
```

And when instantiating the child class in any test (e.g. `new SubClass`), I get the following error:

```
TypeError: 'undefined' is not a constructor (evaluating 'new SubClass')
```

The tests _were_ working fine before with this setup:

```coffee
class @Base
  _settings : {}

  constructor : ( @options ) -> @init?()

  _setDefaults : ( defaults ) ->
    @_settings = $.extend( defaults, @options )

class @SubClass extends Base
  init : ->
    @_setDefaults
      test : true
```

Functionally the code works anywhere else. However, for some reason, with the new setup of `Base`, the tests will always fail with that error, no matter how much I change it around. I've isolated it, updated to the latest Jasmine, and tried as much as I can absolutely think of. I've exhausted all the options I can think of, so I thought I'd drop an issue here and see.

_Any_ help at all would be greatly appreciated! :smile:

**Comment by drewbarontini** [comment]
As an update to this, I was able to create tests in a completely different testing library and it worked fine, so I'm still assuming there's something Jasmine doesn't like.

**Comment by slackersoft** [comment]
I don't really know much CoffeeScript, but one thing I'm seeing different between your two examples is that the `SubClass` in the second example doesn't actually define its own `constructor`, while the first example defines a `constructor` that looks like it simply defers to `super`. I don't know if this is what is actually causing your issues or not, but Jasmine doesn't concern itself with how you generate the javascript that it is testing.

Hope this helps. Thanks for using Jasmine!

**Comment by drewbarontini** [comment]
They are both valid CoffeeScript examples. The second example worked fine in Jasmine. The first throws an error.

As I said, though, I've tested this in Mocha and it works completely fine. Jasmine throws the error for the first example. I tested it in another testing framework to confirm that it wasn't the code.

**Comment by slackersoft** [comment]
Hmmm, I'm not seeing any errors when I run this spec:

````coffeescript
class @WorkingBase
  constructor : ( @options ) ->
    @_settings = $.extend( {}, @constructor._defaults, @options )

class @WorkingSubClass extends WorkingBase
  @_defaults :
    test : true

  constructor : ->
    super

class @BrokenBase
  _settings : {}

  constructor : ( @options ) -> @init?()

  _setDefaults : ( defaults ) ->
    @_settings = $.extend( defaults, @options )

class @BrokenSubClass extends BrokenBase
  init : ->
    @_setDefaults
      test : true

it "working", () ->
  expect(new WorkingSubClass()).not.toBeUndefined()

it "broken", () ->
  expect(new BrokenSubClass()).not.toBeUndefined()
````

I'm running it through coffee script before loading the page, so maybe since I'm only loading a single javascript file it works fine, but that would seem like it isn't necessarily Jasmine's fault other than maybe not waiting for something to load before executing the suite. Are you using the Rails asset pipeline or some other mechanism to generate the javascript on the fly?

**Comment by drewbarontini** [comment]
I'm just using Gulp to build the JS files and then the Jasmine gem to glob and look for the JS files.

**Comment by slackersoft** [comment]
Hmm. Does the example I pasted in work in your setup? It seems to be working for me with current Jasmine versions. If it isn't working for you, it might be something else in your setup. If it does work, but your real code doesn't, we may need a more accurate example of a spec that isn't working to try to diagnose what is going on.

**Comment by drewbarontini** [comment]
@slackersoft Sorry for the delayed response. I'm having trouble getting everything in my setup completely cleared out so that I can test things with your isolated example. I'll report back once I get this tested out.

**Comment by drewbarontini** [comment]
@slackersoft Apologies for the delays here. Running your spec does indeed work within the setup, so I'm assuming it's something within the code, but I'm not sure what or how to diagnose it. Any help would be greatly appreciated. Here is the `Base` class implementation and an example class that extends it, followed by an example spec that isn't working when run in isolation:

```coffee
class @Base
  constructor : ( @options ) ->
    @_settings = $.extend( {}, @constructor._defaults, @options )
```

```coffee
class @AutoDuplicateInput extends Base
  @_defaults         :
    $container       : $( '.js-autoDuplicateInput-container' )
    $element         : $( '.js-autoDuplicateInput' )
    classInvalid     : 'is-invalid'
    classValid       : 'is-valid'
    dataAttrCloned   : 'cloned'
    dataAttrValidate : 'validate'
    onDuplicate      : null
    onInvalid        : null
    onValid          : null

  constructor : ->
    super

    # ...

# ...
```

```coffee
describe 'AutoDuplicateInput', ->
  beforeEach ->
    loadFixtures( 'auto_duplicate_input.html' )

    @selector              = '.js-autoDuplicateInput'
    @element               = $( @selector )
    @container             = $( '.js-autoDuplicateInput-container' )
    @clonedDataAttribute   = 'cloned'
    @validateDataAttribute = 'validate'
    @invalidClass          = 'is-invalid'
    @validClass            = 'is-valid'

    @adi = new AutoDuplicateInput

  # ...
```

It's erroring out on the `new AutoDuplicateInput` instantiation, which clearly has something to do with `extend`ing `Base` into the class. The CoffeeScript converts to valid JavaScript, so I'm not sure what the issue is. And, interestingly enough, the spec for the `Base` class passes fine:

```coffee
describe 'Base', ->

  beforeEach ->
    class ExtendsBase extends Base

    @extendsBase = new ExtendsBase

  it 'should cause extended classes to be an instance of itself', ->
    expect( @extendsBase instanceof Base ).toBeTruthy()
```

Any help would be greatly appreciated. Thanks for your time.

**Comment by slackersoft** [comment]
Unfortunately, I don't really know much about coffeescript to help diagnose your error. As you've said it appears to be somewhere in your code and not Jasmine itself, I'm going to close this issue.

Please update here or open a new issue if you find something that Jasmine seems to be doing incorrectly.

Thanks for using Jasmine!
