### ISSUE TITLE
Test results not reported when teardown is undefined

### ISSUE THREAD

**Issue by palortoff** [jasmine/jasmine#1004]
When the teardown function is undefined, the test result is not reported.

Failed tests are missed.

``` javascript
describe('not reported suite', function(){
  afterEach(undefined);
  it('failing test case', function(){
    expect(false).toBe(true);
  });
});
```

In this case it there might be an obvious error, but jasmine should still treat it as an error.

The following example is not that obvious:

``` javascript
describe('not reported suite', function(){
  var tearDown;
  beforeEach(function(){
    tearDown = function(){}
  });

  afterEach(tearDown);

  it('failing test case', function(){
    expect(false).toBe(true);
  })
});
```

The tests itself run and report their failure, however the teardown execution throws an exception that is caught and not handled, while discarding the test results.

See [plnkr](http://plnkr.co/edit/VL84Nu?p=preview).

**Comment by slackersoft** [comment]
We would be happy to review a pull request that made the functions that receive functions from the user (`beforeEach`, `afterEach`, `beforeAll`, `afterAll`, `it`, and `describe`) throw an error during suite construction that tells the user that something is wrong.
