### ISSUE TITLE
Mocking 2nd-level modules

### ISSUE THREAD

**Issue by IngwiePhoenix** [jasmine/jasmine#1005]
I want to test a CDN helper function. It is super basic and does only one thing that makes it tricky to test - at least I think so.

```javascript
var CDN = require("./GlobalConfig").config.CDN;
var url = require("url");
module.exports = function MakeCDNLink(path) {
    path = path || "/";
    if(CDN.enable) {
        return url.format({
            protocol: "http",
            host:     CDN.domain,
            pathname: path
        });
    } else {
        return CDN.baseUrl+path;
    }
}
```

This `GlobalConfig` module parses a YAML file and puts it's values into a `.config` property. This property is used to see if we should use a local endpoint (`/cdn/...`) or remote (`http://cdn.example.com/...`).

How can I mock this config? I want to test specific behaviors, but not needing to change my current config just to get that thing right.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using jasmine!
