### ISSUE TITLE
How do i spy on javascript DOM methods like getBoundingClientRect

### ISSUE THREAD

**Issue by amit1911** [jasmine/jasmine#1012]

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.


Thanks for using Jasmine! Closing
