### ISSUE TITLE
GreaterThanOrEqual and LessThanOrEqual matchers

### ISSUE THREAD

**Issue by rullopat** [jasmine/jasmine#1013]
I found myself in the situation many times to check that a number is greater than or equal than another number, or less than or equal to it, so I had to write 2 custom matchers for this.
I've noticed searching on Google, that writing "Jasmine greater", it suggests as first option "Jasmine greater or equal to", so it seems I'm not the only one to need something like that.
I would propose to add those 2 default matchers in the core. I can also offer my contribution to the project for it.

**Comment by slackersoft** [comment]
We would be happy to review a pull request to implement these matchers

**Comment by rullopat** [comment]
I just did a pull request with the new matchers and the the related spec tests.
