### ISSUE TITLE
In console.log, add the current test

### ISSUE THREAD

**Issue by jehon** [jasmine/jasmine#1014]
It is sometimes difficult to know what console.log relate to.

Would it be possible to add the current test into each console.log?

**Comment by slackersoft** [comment]
`console.log` is provided by the outer environment being used to execute jasmine (e.g. the browser or nodejs), and not by jasmine itself. You might be able to write your own wrapper for use in your own tests, but this isn't something we're looking to have in jasmine right now.

Closing this. Thanks for using jasmine!

**Comment by jehon** [comment]
I use something to replace console.log by my own function, that something I can do. Could you show me how to get (in that global function) some informations about the running test?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
