### ISSUE TITLE
There could be a better error message if non-funtion is passed to spy.and.callFake()

### ISSUE THREAD

**Issue by jrencz** [jasmine/jasmine#1016]
I often change from
```
spy.and.returnValue(someExistingVariable);
```

to 

```
spy.and.callFake(() => someVariableThatCanBeAssignedLater);
```

and I sometimes forget to pass a function:

```
// Triggers error
spy.and.callFake(someVariableThatCanBeAssignedLater);
```

The error that is returned does not tell me immediately what have I done wrong:

```
TypeError: 'undefined' is not a function (evaluating 'plan.apply(this, arguments)')
```

There could be a better error message that would hint the user that what has been passed to `callFake` is not a function.

**Comment by slackersoft** [comment]
We would be happy to review a pull request that throws an error if `callFake` is called with a non-function argument.

Thanks for using Jasmine!
