### ISSUE TITLE
toHaveBeenCalledTimes doesn't work with 0

### ISSUE THREAD

**Issue by logankd** [jasmine/jasmine#1018]
florimon mentioned this problem in #994.
"It is not possible to call toHaveBeenCalledTimes() with the value 0 (zero). This is because the implementation uses "if (!expected)" to test whether a value was supplied for the 'expected' argument.

(I know the same can be accomplished with the stanza "expect(...).not.toHaveBeenCalled()" but I feel like toHaveBeenCalledTimes() should support this too)."

**Comment by logankd** [comment]
I have fixed the 0 issue with a test in Pull request #1015.

**Comment by slackersoft** [comment]
Fixed with 342f0eb9a38194ecb8559e7df872c72afc0fe52e
