### ISSUE TITLE
Set up auto-update for jsdelivr

### ISSUE THREAD

**Issue by erquhart** [jasmine/jasmine#1020]
cdnjs doesn't offer the files necessary for the standalone runner  (trying to file an issue and need this to demonstrate on jsbin), but jsdelivr does. Their latest version of Jasmine is 2.0.0. They have an auto-update feature, instructions here:

https://github.com/jsdelivr/jsdelivr

Thanks for the awesome lib!

**Comment by slackersoft** [comment]
Based on the files listed on the [cdnjs page for jasmine](https://cdnjs.com/libraries/jasmine), it looks to me like all of the necessary files are hosted there, and it should be doing auto-updating with new releases. What files do you think are missing?

I've also created a PR for jsdelivr (jsdelivr/jsdelivr#9829) to configure the auto-update for jasmine.

Closing. Thanks for using Jasmine!

**Comment by erquhart** [comment]
Awesome. I did eventually get it going. Jsdelivr should make it even easier. Thanks!
