### ISSUE TITLE
expect("1").toEqual(1) fails

### ISSUE THREAD

**Issue by fjanon** [jasmine/jasmine#1022]
In Javascript:
1 == '1'
true

**Comment by Gerg** [comment]
The jasmine equality check is based off the of [underscore.js isEqual method](http://underscorejs.org/#isEqual). If you want to define your own notion of equality, you can make a [custom matcher](http://jasmine.github.io/2.4/custom_matcher.html).

Also worth noting:
```js
1 === '1'
false
```

Thanks for using Jasmine.
