### ISSUE TITLE
testing custom matcher failure case

### ISSUE THREAD

**Issue by atomanyih** [jasmine/jasmine#1024]
Say I want to test the failure case of a custom matcher called `toDoCustomMatchy`

After a bunch of fiddling I end up with this:

```js
it('fails and stuff', () => {
  let expectationPassed, expectationMessage;

  const expectation = expect(guy);

  expectation.addExpectationResult = (pass,result) => {
    expectationPassed = pass;
    expectationMessage = result.message;
  };

  expectation.toDoCustomMatchy();

  expect(expectationPassed).toEqual(false);
  expect(expectationMessage).toMatch(/Expected guy to custom matchy/);
});
```

Is there a better way?

**Comment by Gerg** [comment]
Take a look at how we test the core matchers: https://github.com/jasmine/jasmine/tree/master/spec/core/matchers

**Comment by atomanyih** [comment]
Do you mean unit test the compare method?

more like this?

```js
it('fails and stuff', () => {
  const matcher = toDoCustomMatchy(jasmine.matcherUtils);

  const {pass, message} = matcher.compare(guy);

  expect(pass).toEqual(false);
  expect(message).toMatch(/Expected guy to custom matchy/);
});
```

**Comment by slackersoft** [comment]
Yes, part of the reason for the syntax change for matchers with 2.0 is to better allow this type of testing.

In the future, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing.
