### ISSUE TITLE
would be nice if the reporter can be passed as CLI arg

### ISSUE THREAD

**Issue by timaschew** [jasmine/jasmine#1027]
For instance `jasmine --reporter junit`.
Of course you need to define some convention for the npm module name of a supported reporter.

**Comment by aMarCruz** [comment]
absolutely +1

**Comment by floverdevel** [comment]
+1

**Comment by rochejul** [comment]
+1

**Comment by agirorn** [comment]
+1

**Comment by mister-what** [comment]
+1

**Comment by slackersoft** [comment]
The `--reporter=` arg has been added to jasmine-npm in the 3.0-features branch and will be released as part of the 3.0 release of Jasmine. The string provided will be passed directly to `require()` and the file is expected to export a constructor that can be `new`ed up and passed in as a reporter to Jasmine.

Hope this helps. Thanks for using Jasmine!
