### ISSUE TITLE
Does fail function exist?

### ISSUE THREAD

**Issue by hajiz** [jasmine/jasmine#1028]
Hi,

I know there has been a lot of discussions over fail, this.fail and similar calls. What surprises me is that there is definitely a fail function (I can call 'fail("Fail the test")' from inside "it" tests) and I can see it in the source code:

    fail: function() {
      return env.fail.apply(env, arguments);
    },

but it is not documented and in some cases its existence is denied. What is the status for it? Is it an undocumented/unsupported feature? Is using it a good idea or it may be dropped at some future versions? So far I have seen it in Jasmine 2.2 and 2.4.1

Thanks,
Hajix

**Comment by Gerg** [comment]
Fail does exist in modern Jasmine.

It is currently undocumented because our docs are executed and will fail if
we call the fail method.

This is not ideal, and we are working to restructure our docs.

Thanks for using Jasmine!

**Comment by hajiz** [comment]
Thank you Gerg :)
