### ISSUE TITLE
Ability to load tests dynamically and rerun jasmin/reporter

### ISSUE THREAD

**Issue by HansHammel** [jasmine/jasmine#1030]
I am currently trying to run jasmine tests from partials/ components, which are dynamically loaded via ajax. The idea is to have the corresponding reports appended to the Body (html-reporter) for each “view”, while avoiding the page-reload. I am able to run jasmine exactly once. Is there a way to load test suites via ajax and/or clear jasmines html reports/ unload jasmine or reload/reinitialize it when I load dynamic content?

Thanks.

**Comment by slackersoft** [comment]
A Jasmine suite doesn't currently expect to be run more than once. If I'm understanding your situation correctly, you might be able to [write your own boot.js](http://jasmine.github.io/edge/custom_boot.html) that waits for all of your specs to load before telling Jasmine to start execution of the suite.

In the future, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
