### ISSUE TITLE
Notify reporters on errors when using catchExceptions/throwOnExpectationFailure

### ISSUE THREAD

**Issue by adamziel** [jasmine/jasmine#1031]
If you set any of the below:
```js
  env.catchExceptions(false);
  env.throwOnExpectationFailure(true);
```

No reporter is notified in case of failure. I would expect `jasmineDone` to be executed

**Comment by slackersoft** [comment]
When you tell Jasmine `catchExceptions(false)` it doesn't handle any exceptions thrown during the run. The intention here is to get the exception to bubble all the way out to the browser for easier debugging of issues that jasmine might be inadvertently covering up, it isn't something you would want to permanently leave on in your suite for this exact reason.

This isn't something we're looking to change at this point in time, so I'm going to close this. Thanks for using Jasmine!
