### ISSUE TITLE
Jasmine, TypeScript and spyOn

### ISSUE THREAD

**Issue by blackat** [jasmine/jasmine#1032]
Hi,
I am migrating some tests from JavaScript to TypeScript and I have some issue with `spyOn`. I have tried
```javascript
spyOn(fooService, 'fooMethod').and.returnValue();
```
but it does not work, in the `d.ts` file the function is `declare` so I have tried to 
```javascript
jasmine.Spec.spyOn(fooService, 'fooMethod').and.returnValue();
```
and it does not work as well, the transpiler says `Property 'Spec' does not exist on type 'typeof jasmine'.`

How can I use the `spyOn` method?

Thanks a lot for the attention.

**Comment by JoseRoman** [comment]
If Javascript will eventually be the code in production, why would you test Typescript directly?

**Comment by blackat** [comment]
I am not tested TypeScript directly, I transpile ts to js and the run the test, but I would like to write test in ts.

**Comment by JoseRoman** [comment]
Oh OK. I have been writing the test in TS and then running them after transpiling too. Could you provide more details as of what TS Definition you are using? Is it the one from the DefinitelyTyped repo?

**Comment by blackat** [comment]
Hi,
thanks a lot for your help, may be I have found the problem: in pure `JavaScript` I have written something like:
```javascript
spyOn(myService, 'remove').and.returnValue()
```
and I was working, no problems!
Moving to `TypeScript` and transpiling I got the following error
```
error TS2346: Supplied parameters do not match any signature of call target.
```
and I have thought was an issue with the `spyOn` and how it has been called, but actually it is an issue with the `.returnValue()` that, because of the type checking, requires now an argument as you can see from

```javascript
returnValue(val: any): void;
```

Unfortunately the transpiler does not point out at which column there is error (just the line and the column where the statement starts) and the IDE, at least in this case, does not highlight the error.

Thanks a lot anyway for your offer to help me, much appreciated :wink:
