### ISSUE TITLE
Jasmine spec dependency

### ISSUE THREAD

**Issue by vivekbrahmadandi** [jasmine/jasmine#1034]
In jasmine suite , if we have 10 specs , how can we arrange dependeny specs such that if any dependency specs are failed the jasmine should not execute other specs which has to be executed.

In testNG library which is used for java unit testing where we are using dependency groups or methods attribute on an @test annotation

**Comment by floverdevel** [comment]
are you looking for something like this ?
`jasmine --stop-on-failure=true`

http://jasmine.github.io/2.4/node.html#section-13

**Comment by slackersoft** [comment]
Ideally, your tests shouldn't depend on other tests. If you have some common setup that you need to run, Jasmine has `beforeEach` to set up each test the same, or `beforeAll` in case the setup is expensive enough that you're willing to deal with the shared state between tests.

If you have all of that set up and you want Jasmine to not execute any further specs after encountering the first failing spec, you can configure Jasmine that way. If you're using Jasmine in a node context, you can use the command line flag as @floverdevel mentioned, or configure it in your `jasmine.json`, other runners have their own configuration for this, and the built-in Jasmine HTML page includes an option (in the top right) to turn this on as well.

In the future you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
