### ISSUE TITLE
How to test for session variables?

### ISSUE THREAD

**Issue by bwobst** [jasmine/jasmine#1038]
I'd like to test for the value of a session variable.

Right now, this happens:
1. I have a default session variable: `Session.setDefault('alert', null);`
2. I have the test suite click a button which makes the session variable value = true: `Session.set('alert', true);`
3. I test for the value of `Session.get('alert');` and it comes back with `null`.

How can I get the correct session variable value after an event takes place?

FYI, I'm using the [`sanjo:jasmine`](https://github.com/xolvio/jasmine) implementation for Meteor.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
