### ISSUE TITLE
with this and without this

### ISSUE THREAD

**Issue by brutalcrozt** [jasmine/jasmine#1039]
may i ask? sorry to open new issue.
**i just confuse why i have to use `this` to share variable on a suite.**
i just new on unit test, and i work with example on the internet (`which not use this`).
i stuck then read the intro documentation, realize using this to share variable.
now it work fine, but why i got undefined when not using `this`.

**Comment by Gerg** [comment]
Check out this for an explanation: https://gist.github.com/traviskaufman/11131303

You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using jasmine!

**Comment by brutalcrozt** [comment]
@Gerg Thanks for your fast response.
I suggest update introduction on jasmine website, since i don't know much about it.

**Comment by brutalcrozt** [comment]
I use chai with jasmine
and i got htis
```
assert.throw(funtion() {
  this.service.someMethod(dummyParameter); // yell cannot read service on undefined
},'some error');
```
when i change to use injector it works
```
assert.throw(funtion() {
  injector.get('service').someMethod(dummyParameter); // works fine
},'some error');
```

**Comment by brutalcrozt** [comment]
even use jasmine it'self
```
expect(function () {
  this.service.dataContext({}); // yell cant read service of undefined
}).toThrowError(threwMsg);
```
details:
````
"name": "karma-jasmine",
"version": "0.2.2"

"name": "jasmine-core",
  "license": "MIT",
  "version": "2.4.1",
```

**Comment by amavisca** [comment]
@brutalcrozt This isn't a problem with Jasmine - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

`this`is a reserved word that is scoped within a function, so each function declaration would need to pass the `this` from the it/beforeEach/etc. block that Jasmine sets up into the inner functions. There are a few ways to accomplish this:

Manually bind your function using Function.prototype.bind:
```
it('uses Function.prototype.bind', function() {
 // this = the this that Jasmine bound to the it function
  expect(function() { 
    // this = the this that was bound to the outer function (the one Jasmine supplied)
  }.bind(this)).toThrow(...)
});
```

Use the ES6 Arrow function (fat arrow) syntax, which accomplishes the same behavior of function(){}.bind(this) with a shorthand syntax (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
```
it('uses ES6 Arrow functions', function() {
  // this = the this that Jasmine bound to the it function
  expect(function() => {
    // this = the this that was bound to the outer function (the one Jasmine supplied)
  }).toThrow(...);
});
```

Refer to the Jasmine-supplied this in the it function:
```
it('uses closures', function() {
  var self = this;
  expect(function() {
  // self is captured in the closure, so you can refer to self.whatever inside the inner function
  }).toThrow(...);
});
```

Depending on what JS standard was available to me, I'd choose ES6 Arrow func > Function.prototype.bind > var self = this.

If you have other questions about usage, please send them to the mailing list as github issues are intended to be used for feature requests and issues.

**Comment by floverdevel** [comment]
javascript 101 : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

> A function's this keyword behaves a little differently in JavaScript compared to other languages. It also has some differences between strict mode and non-strict mode.

> In most cases, the value of this is determined by how a function is called.

**Comment by brutalcrozt** [comment]
@amavisca @floverdevel my apologize , thank for your help

**Comment by floverdevel** [comment]
no problem @brutalcrozt :)
