### ISSUE TITLE
Using toThrowError testing directive in Jasmine 2.4.1

### ISSUE THREAD

**Issue by odancik** [jasmine/jasmine#1045]
I am testing a directive input parameters and throwing new Error() if they are invalid. I am using Jasmine 2.4.1 and Angular 1.4.9

If my directive has templateUrl defined, the exception is recognized by Jasmine because the exception object is instanceof Error.

However, if my directive doesn't have templateUrl defined (because I am creating directive without template), the exception is not recognized by Jasmine, because the exception object is not instanceof Error.

More details here:
http://stackoverflow.com/questions/35010158/using-tothrowerror-testing-directive-in-jasmine-2-4-1

**Comment by slackersoft** [comment]
`toThrowError` checks explicitly for an `Error` object to be thrown. If you want to throw something more generic you'll want to use `toThrow` instead.

Next time, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing.

**Comment by odancik** [comment]
I think it is probably a bug, because in both of my examples I throw new Error. 

However when Jasmine checks the the type (if (thrown instanceof Error) { ... }), in case when the directive throwing error HAS templateUrl the "thrown" variable IS INSTANCE of Error, but in case when the directive throwing error DOESN'T HAVE templateUrl the "thrown" variable IS  NOT INSTANCE of Error. 

That seems very strange. What do you think?

**Comment by slackersoft** [comment]
Are you sure Angular is executing the code in your directive? I don't see anything about what errors you're actually seeing.

**Comment by odancik** [comment]
After a day of testing and searching I found the problem. It is actually a ngMock bug/issue as described here:

https://github.com/angular/angular.js/issues/13821

And example: https://codepen.io/anon/pen/NxQKBp

Anyways, thanks for replying to my question.

**Comment by slackersoft** [comment]
Glad you found the issue
