### ISSUE TITLE
HTML Reporter Spec Link Goes Wrong When Base URI Was Set

### ISSUE THREAD

**Issue by FuweiChin** [jasmine/jasmine#1051]
In SpecRunner.html, when adding an `<base href="../">` to document, the reporter-generated spec link may looks like this:

``` html
<a href="?spec=prologue%20InstallFunctions()">InstallFunctions()</a>
```

when I clicked the link.  browser window jumped to the base URL page

So I think, the `specHref` function in jasmine-html.js shoud be updated from 

``` js
    function specHref(result) {
      return addToExistingQueryString('spec', result.fullName);
    }
```

to

``` js
    function specHref(result) {
      var search=addToExistingQueryString('spec', result.fullName);
      var href=search;
      if(document.URL!=document.baseURI){
        href=location.pathname+search;
        if(document.baseURI.indexOf(location.origin+"/")==-1){
          href=location.origin+location.pathname+search;
        }
      }
      return href;
    }
```

So that spec link in test result works fine test result under such a circumstance.

P.S.
I didn't considered about browser compatibility of code `document.baseURI` and `location.origin`.

Here are two fallback functions to resolve the concerns:

``` js
function getBaseURI(){
    var a=this.createElement("a");
    a.href="";
    return a.href;
}
function getOrigin(){
    return this.protocol+"//"+this.host;
}
```

To make it compatible with old browsers:
- use `getBaseURI.call(document)` instead of `document.baseURI`
- use `getOrigin.call(location)` instead of `location.origin`.

**Comment by FuweiChin** [comment]
P.S.
I didn't considered about browser compatibility of code `document.baseURI` and `location.origin`.

Here are two fallback functions to resolve the concerns:
```js
function getBaseURI(){
	var a=this.createElement("a");
	a.href="";
	return a.href;
}
function getOrigin(){
	return this.protocol+"//"+this.host;
}
```
To make it compatible with old browsers:
+ use `getBaseURI.call(document)` instead of `document.baseURI`
+ use `getOrigin.call(location)` instead of `location.origin`.

**Comment by slackersoft** [comment]
The HtmlReporter really kind of expects to be in control of most of the page, so I'm not sure how much sense it makes to try to support a document with a custom `baseUri` set.

If the code being tested needs to handle a page with a custom `baseUri` it probably makes sense to provide some kind fake or stub to the specs that need it, similar to what you might do if you have code that deals with `window.location`.

Closing, I don't think this is something we're looking for in Jasmine at this time. Thanks for using Jasmine!

**Comment by FuweiChin** [comment]
I mean Jasmine HTML Reporter always assuming the baseURI of the SpecRunner page is document URI,  regardless of page author's custom baseURI setting.

Any SpecRunner page  WITH CUSTOM BASE URI (which is not the same as documentURI) will result in wrong page navigation when spec link clicked as long as this issue not resolved.
