### ISSUE TITLE
jasmine repository contains zero-padded file modes

### ISSUE THREAD

**Issue by nfk** [jasmine/jasmine#1052]
The jasmine repository is not clean.
"git fsck" returns the following errors:

`Checking object directories: 100% (256/256), done.
warning in tree 30e85099c116ada0d0588915567e6ed438d52ed7: contains zero-padded file modes
warning in tree a0a1663600be9b6d099bffd067e4452c5a1a37ef: contains zero-padded file modes
warning in tree 34b50ab9f16aecca8263830bfe59f5b4333e4501: contains zero-padded file modes
warning in tree 90e54d021c732fb81af9989a019c87c4aee3e621: contains zero-padded file modes
warning in tree d589297f4654e4a685eac61cce7481437e612b8b: contains zero-padded file modes
warning in tree 0cc331339a0f1e685055bbdf1b38a2f647467a44: contains zero-padded file modes
warning in tree 0c932084c1f9f2b2dc86a4dc98dcee126b76b644: contains zero-padded file modes
Checking objects: 100% (12993/12993), done.`

Someone has a clean repository somewhere?
I am not able to clone the project with a recent version of git like 2.7.

**Comment by nfk** [comment]
This topic can help to clone the project: https://groups.google.com/forum/#!topic/binary-transparency/f-BI4o8HZW0

But it don't solve the issue.

**Comment by slackersoft** [comment]
It looks like those issues have been in the repo for some time now (at least 2 years). I haven't been able to figure out when they occurred, and it looks like fixing this issue would require force pushing a full new repo. Since this would break all forks of jasmine, I'm not sure this is something we want to attempt at this point.

**Comment by slackersoft** [comment]
Given the difficulty in fixing this issue and how long it has been around, I'm inclined to just leave it alone for now so we don't break pull requests and forks.

Closing. Thanks for using Jasmine!
