### ISSUE TITLE
'and' assertion chainer

### ISSUE THREAD

**Issue by Jameskmonger** [jasmine/jasmine#1054]
It would be good to have an `and` chainer which allows for multiple assertions/expectations to be chained into a single statement.

When testing that something has been correctly instantiated, it is common to test that it is neither null nor undefined.

Currently, this must be done like so:

    it("should set someProperty", () => {
        let someInstance = new SomeClass();

        expect(someInstance.someProperty).not.toBe(null);
        expect(someInstance.someProperty).not.toBe(undefined);
    });

There would then be further tests added to ensure that it has the correct value, but this test would usually come first when TDDing.

It would be good to chain the two `expect` statements into a single statement, like this:

    it("should set someProperty", () => {
        let someInstance = new SomeClass();

        expect(someInstance.someProperty)
            .not.toBe(null)
            .and.not.toBe(undefined);
    });

**Comment by sinaru** [comment]
Each test example should make only one **assertion**. This helps you on find errors faster and makes your code easier to read and maintain.
An exception to this would be when testing a state of a resourceful object. But then again your suggestion reduce the readability and maintainability of test code.

**Comment by slackersoft** [comment]
As @sinaru said, using `and` in this way would make it harder to diagnose failing tests. I would also argue that instead of checking both not null and not undefined, you probably want to check for a single positive assertion that is more descriptive of what should be happening. This could even be something like `expect(someProperty).toEqual(Jasmine.any(String));` to assert that it is of the type you expect. 

This isn't something we're looking at changing any time soon, so I'm going to close this. Thanks for using Jasmine!

**Comment by AntonioRedondo** [comment]
@sinaru, @slackersoft there are plenty cases where it's absolutely legit to chain assertions. For example:

```
expect(button.addEventListener).toHaveBeenCalledTimes(1)
      .and.toHaveBeenCalledWith('click');
```
Without an `.and` chaining property the expect block becomes considerably longer:
```
expect(button.addEventListener).toHaveBeenCalledTimes(1);
expect(button.addEventListener).and.toHaveBeenCalledWith('click');
```

It's also more prone to bugs: you have to write twice `expect(button.addEventListener)`.

This feature is implemented in [Chai](http://chaijs.com/api/bdd) and there is no real reason why it shouldn't be implemented on Jasmine taking into account is a basic one. Your answer looks to me a bit opinionated and definitively lessens the number of testing choices. I think it would be nicer to let the user decide which is the best approach for different use cases. I don't think this feature would be a dangerous one.

**Comment by liuxh0** [comment]
I think this feature should be taken into consideration again.

**Comment by AntonWille** [comment]
Maybe I am mistaken but there seems to be no real 'in range' expectation, being able to chain with and would enable that, too.

**Comment by spyro2000** [comment]
It's a common feature in pretty much all other assertion frameworks I know. So yes, it should be just like that.

```typescript
expect(button.addEventListener)
  .toBeDefined()
  .toHaveBeenCalledTimes(1)
  .toHaveBeenCalledWith('click', jasmine.any(Function))
````
