### ISSUE TITLE
Jasmine Runs Test Three Times

### ISSUE THREAD

**Issue by oliver-spryn** [jasmine/jasmine#1063]
I am running Karma/Jasmine/Angular 2.0 tests on my development box. Just recently, Jasmine on my development box decided to start running my tests three times. Yes, exactly three times, every time.

On the first run, everything passes as expected. However, on the second and third pass, all of the same things fail. It always acknowledges that there are 7 tests, but runs 21, and 10 fail (first-grade math out the window)????

This also [fails on Travis](https://travis-ci.org/oliver-spryn/portfolio/builds/112652221) with SauceLabs. (**Note:** That links to an older build with 3 tests, but ran 9, and 5 fail???)

I have a screenshot, karma.conf.js file, and one suite which started this whole thing. Any help with be greatly appreciated.
---
## Culprit [TypeScript] (Remove this and problem solved on my dev box):

[Full source](https://github.com/oliver-spryn/portfolio/blob/51fc57a6ec4f0261400571ac8b7d1d6d24ff1a78/test/unit/app/layout/typescript/services/Conductor.Spec.ts)

```
describe('From the Conductor Service', () => {
    let arr: Array<ComponentStatusModel> = null;
    let svc: ConductorService = null;

    beforeEach(() => {  
        arr = [/* Inits the array*/];
        svc = new ConductorService();
    });

    describe('when it is handed a container to hold objects which need loaded', () => {
        // More passing tests...

        /// vvvvv The culprit !!!!!
        describe('then when you need to access the container', () => {
            beforeEach(() => {
                svc.loadedContainer = arr;
            });

            it('it should always be available', () => {
                assertIsLocalDataInTheService(arr, svc.loadedContainer);
            });
        });
        /// ^^^^^ End of culprit !!!!!
    });

    // More passing tests...
});
```
## Failing Tests:

[![Tests are ran three times](http://i.stack.imgur.com/ehtry.png)](http://i.stack.imgur.com/ehtry.png)
## Browser Screenshots:

Not sure if this is related, but before all of the errors happen, the Jasmine call stack is smaller (left, observe scrollbar). After the errors start, the stack just gets bigger with repeating calls to the same functions (right, observe scrollbar).

[![Jasmine Call Stack](http://i.stack.imgur.com/6Hqzi.png)](http://i.stack.imgur.com/6Hqzi.png)
## Suite Stack is Wrong:

In my test, the Nanobar and Conductor spec files are totally separate. However, you can see the suites array includes stuff from the Nanobar ans Conductor specs. Somehow Jasmine mashed these two spec files together (after everything started failing), and resulted in my describe() statements not making any sense when published to the console.

[![Jasmine Suite Stack](http://i.stack.imgur.com/l1Oel.png)](http://i.stack.imgur.com/l1Oel.png)
## Simplified karma.conf.js:

[Full source](https://github.com/oliver-spryn/portfolio/blob/51fc57a6ec4f0261400571ac8b7d1d6d24ff1a78/karma.conf.js)

```
module.exports = function (config) {
    config.set({
        autoWatch: false,
        basePath: '.',
        browsers: ['Chrome'],
        colors: true,
        frameworks: ['jasmine'],
        logLevel: config.LOG_INFO,
        port: 9876,
        reporters: ['coverage', 'progress'],
        singleRun: true,

        coverageReporter: {
            // Code coverage config
        },

        files: [
            // Loads everything I need to work
        ],

        plugins: [
            'karma-chrome-launcher',
            'karma-coverage',
            'karma-jasmine'
        ],

        preprocessors: {
            'app/**/*.js': ['coverage']
        },

        proxies: {
            // Adjust the paths
        }
    })
}
```

**Comment by tcpip4000** [comment]
Same here angular 2  beta 15 tests runs 3 times, dependencies I use:
...
  "dependencies": {
    "angular2": "2.0.0-beta.15",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.10",
    "jquery": "1.12.1",
    "bootstrap": "^3.0.0"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "jasmine-core": "2.4.1",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^0.7.12"
  }
...

**Comment by slackersoft** [comment]
It sounds like somehow your specs are getting registered with Jasmine more than once.

Is the TypeScript being compiled in the browser and maybe it ends up executing oddly? I don't know much about TypeScript or how things like `let` work in it, but I could see these things potentially causing problems.

If you pre-compile to JS and use those tests can you still reproduce the issue? If so, this would indicate an issue with TypeScript and probably not Jasmine itself.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't seen any more information on this issue, and it sounds like it is probably an issue with TypeScript configuration and not necessarily Jasmine itself.

Closing. We'd be happy to review a pull request or further discussion about particular things that Jasmine is doing that can cause errors with TypeScript.
