### ISSUE TITLE
Can't chain 'and.callThrough' with 'and.returnValue' to spy

### ISSUE THREAD

**Issue by sinaru** [jasmine/jasmine#1064]
Code fails when chaining 'and.callThrough' with 'and.returnValue' to spy.
See below codes. Notice the chaining order causes same test to fail and pass different occasions.

```js
describe('Spy', function () {
    var bar = null;

    beforeEach(function () {
        this.foo = {
            setBar: function (value) {
                bar = value;
                return bar;
            }
        };
        spyOn(this.foo, 'setBar').and.returnValue(52).and.callThrough();
        this.foo.setBar(42);
    });

    // passes
    it("expect bar to be 42", function () {
        return expect(bar).toBe(42);
    });

    // fails. return value is 42.
    it("expect 52 as return value", function () {
        return expect(this.foo.setBar(42)).toEqual(52);
    });
});
```

```js
describe('Spy', function () {
    var bar = null;

    beforeEach(function () {
        this.foo = {
            setBar: function (value) {
                bar = value;
                return bar;
            }
        };
        spyOn(this.foo, 'setBar').and.callThrough().and.returnValue(52);
        this.foo.setBar(42);
    });

    // fails. bar is null.
    it("expect bar to be 42", function () {
        return expect(bar).toBe(42);
    });

    // passes
    it("expect 52 as return value", function () {
        return expect(this.foo.setBar(42)).toEqual(52);
    });
});
```

**Comment by slackersoft** [comment]
A spy can only have a single execution strategy at a time. When you chain the second `and` you are changing the execution strategy, this is why it only executes the way you are seeing. 

If you want to define some behavior and also change the return value of a spy, you probably want to use `callFake` instead. This will let you pass a function that defines the implementation of the spy. 

Closing this issue, since is the currently defined/expected functionality. Thanks for using Jasmine!

**Comment by sinaru** [comment]
Oh I see. I didn't find any note about a single execution strategy mentioned in the docs. So I thought it is possible to chain like this and expect both behavior. For example, if I want to have the actual execution of the spied function but also have a specified return value, it is not possible it seems. :cry:

**Comment by tam-borine** [comment]
Yeah I also assumed what sinaru did, I would love to be able to chain spy execution strategies

**Comment by jasonwr** [comment]
@slackersoft I to fell into this pitfall and hence I'm here. I agree with @tam-borine in that chaining spy executions would be stellar.

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.
