### ISSUE TITLE
Website hard to read on high-dpi non-retina displays

### ISSUE THREAD

**Issue by khm** [jasmine/jasmine#1068]
For some reason, you specify font sizes in px, instead of using a method that allows scaling.  As a result, unless you're using a Mac, the website is fairly useless, since the code samples are almost unreadable.   Like so:  http://i.imgur.com/veCLXmm.png

You don't see this effect on your Mac because OS X browsers play games with how many pixels per px are rendered.  The rest of us with nice monitors do not get this special treatment.  Text-zoom settings in Chrome do not affect px-specified font sizes, so low-vision people who rely on these settings are unable to use your site.  

You may find luck multiplying by .75 and switching to pt, which should allow scaling, or you may consider switching to em/rem, with which most accessibility packages work very well.

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

I'm going to close this in favor of an issue or pull request on the documentation itself. Thank for using Jasmine!
