### ISSUE TITLE
Enumerate Jasmine Suites and related Spec names

### ISSUE THREAD

**Issue by aggarwalricha** [jasmine/jasmine#1069]
Hi , I am developing a UI for displaying all the jasmine tests specified in a spec file.
I am looking for some handle in jasmine API which can enumerate all the spec and suite names for me without making any change in the API.

Please let me know if anything available of such sort. For now , I am tweaking in the code by appending a suiteDetails array in to the " jasmine env" variable from boot.js and populating it inside the "getSpecName" API method which has control to both spec and related suite name.

**Comment by slackersoft** [comment]
A loaded Jasmine Env has a `topSuite()` function that you can call to the the root of the spec/suite tree. From there you should be able to enumerate down to all child suites and specs that are loaded.

In the future, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
