### ISSUE TITLE
Jasmine doesn't seem to like Number.MAX_SAFE_INTEGER for timeouts

### ISSUE THREAD

**Issue by keirlawson** [jasmine/jasmine#1070]
This fails:

```js
beforeEach(function(done) {
  setTimeout(function () {
    done();
  });
}, Number.MAX_SAFE_INTEGER);

describe("Some thing", function() {
  it("should do something", function() {
    console.log('did something');
  });
});
```

With `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL`

**Comment by slackersoft** [comment]
The timeout you pass to Jasmine, is then passed as the delay to a `setTimeout` call under the hood that may [suffer from overflow](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout#Notes).

Alternatively, you might just have Jasmine's mock clock turned on which would cause your `setTimeout` call to never be invoked.

Does it seem to fail immediately, or after `MAX_SAFE_INTEGER` number of milliseconds?

Hope this helps. Thanks for using Jasmine!
