### ISSUE TITLE
Proposal: Mock requestAnimationFrame

### ISSUE THREAD

**Issue by traviskaufman** [jasmine/jasmine#1071]
It would be great to have either the `MockClock` or some other utility have a means of mocking requestAnimationFrame (or **rAF** as I like to call it). 

## Motivation

A lot of UI components rely on rAF to avoid synchronous layout and render in sync with the browser's native render cycle. Animation libraries that provide fine-grained control over such animations also lean heavily on the method. Given that jasmine has facilities for mocking dates, timers, and Ajax, I feel functionality to mock rAF is appropriate.

## Proposed Implementation

The rAF should act similarly to the way that `set{Timeout,Interval}` behave when mocked. Specifically it would be nice if it:

* Provided the ability to `tick()` all queued callbacks at once
* Provided the ability to tick a certain number of callbacks, e.g. `tick(n)` where `n` is the first `n` callbacks
* Supported `cancelAnimationFrame`
* Perhaps as a nice to have, provided a way to retrieve a copy of the array of scheduled callbacks, e.g. if you wanted to validate that there are not pending callbacks.

```javascript
describe("Manually Ticking Jasmine's requestAnimationFrame", function() {
  var rafCallback1, rafCallback2;

  beforeEach(function() {
    jasmine.raf().install();
    rafCallback1 = jasmine.createSpy('rafCallback1');
    rafCallback2 = jasmine.createSpy('rafCallback2');
  });

  afterEach(function() {
    jasmine.raf().uninstall();
  });

  it("causes all callbacks given within an rAF cycle to be called", function() {
    requestAnimationFrame(rafCallback1);
    requestAnimationFrame(rafCallback2);
    jasmine.raf().tick();
    expect(rafCallback1).toHaveBeenCalled();
    expect(rafCallback2).toHaveBeenCalled();
  });

  it("allows for only a certain number of callbacks to be called", function() {
    requestAnimationFrame(rafCallback1);
    requestAnimationFrame(rafCallback2);
    jasmine.raf().tick(1);
    expect(rafCallback1).toHaveBeenCalled();
    expect(rafCallback2).not.toHaveBeenCalled();
  });

  it("supports cancelAnimationFrame", function() {
    var frameId = requestAnimationFrame(rafCallback1);
    requestAnimationFrame(rafCallback2);
    cancelAnimationFrame(frameId);
    jasmine.raf().tick();
    expect(rafCallback1).not.toHaveBeenCalled();
    expect(rafCallback2).toHaveBeenCalled();
  });

  // Nice to have
  it("can provide a read-only queue of pending callbacks?", function() {
    requestAnimationFrame(rafCallback1);
    requestAnimationFrame(rafCallback2);
    expect(jasmine.raf().pendingQueue().length).toEqual(2);
    jasmine.tick(1);
    expect(jasmine.raf().pendingQueue().length).toEqual(1);
    jasmine.raf().pendingQueue().shift();
    expect(jasmine.raf().pendingQueue().length).toEqual(1);
    expect(jasmine.raf().pendingQueue()).toEqual([rafCallback2]);
  });
});
```

I feel like most of the code used behind the clock functionality could be repurposed for this, and either way I am happy to take point on this and would love to discuss this with the team further. Thanks!

**Comment by traviskaufman** [comment]
Friendly ping :smiley: would be great to get some feedback on this

**Comment by Ryuno-Ki** [comment]
Here's a reference implementation as Jasmine plugin:

https://gist.github.com/ischenkodv/43934774f4509fcb5791

I'm looking forward to see it in Jasmine Core (I could upgrade from setTimeout-implementation in my code then).

**Comment by Gerg** [comment]
Since Jasmine is build to test Javascript in many different environments, many of which are not browsers, I don't think this is a good feature for Jasmine core. 

That said, this does seem like a useful extension of Jasmine (much like Jasmine Ajax).

**Comment by traviskaufman** [comment]
@Gerg that's fair. 

If there's enough interest, I can investigate building an extension. We built a [really cheap version](https://github.com/google/material-design-lite/blob/master/test/unit/helpers/raf.js#L32) for testing MDLv2 code, which I could use as a best. There's also one in [react-motion](https://github.com/chenglou/react-motion/blob/master/test/createMockRaf.js) which looks good.
