### ISSUE TITLE
Feature Request: call real function from callfake

### ISSUE THREAD

**Issue by vgrevendo** [jasmine/jasmine#1073]
Hi,

I might have missed some documentation, but there seems to be no easy way to call the original function from a spy's callFake. Example of how this could work:

```
spyOn(bar, 'foo').and.callFake(function() {
  // Some testing stuff here
  bar.foo.original();
  // Some more testing stuff here
});
```

I found this could come in handy in some cases. Thoughts?

Thanks,
Vincent

**Comment by sgravrock** [comment]
I usually just stash the real method in a variable:

```javascript
var realFoo = bar.foo;
spyOn(bar, 'foo').and.callFake(function() {
  // Some testing stuff here
  realFoo.original();     // or maybe realFoo.call(bar), if needed
  // Some more testing stuff here
});
```

It's slightly awkward, but I'm kind of ok with that. I think that adding fake behavior and then calling the real method is both a useful pattern and a design smell. When I find myself doing it often enough to be bothered by the extra friction, it usually means that the design of the code under test could be improved in some way.

**Comment by vgrevendo** [comment]
There are cases where it's hard to think of an alternative. For example I find this pattern particularly useful when you need to test in which order API calls are made.

**Comment by sgravrock** [comment]
Agreed. I haven't come up with a better way to write that kind of test.

**Comment by Gerg** [comment]
I agree with @sgravrock that if you find yourself doing this, it is probably a design smell. It means that your code is dependent on side effects from another function. 

I think that the strategy of saving off the original function definition is sufficient for the few cases where you need to do this.

That said, I would be happy to hear feedback from the Jasmine community if anyone has strong feelings otherwise.

**Comment by drtimwright** [comment]
the Mockito library (for Java) has functions to verify that calls to spy methods occurred in a particular order. 

http://site.mockito.org/mockito/docs/current/org/mockito/InOrder.html

If there's interest, I could have a go implementing that?

Tim

**Comment by slackersoft** [comment]
We would be happy to review a pull request that allowed a user to verify that spies were called in a specified order. That has been on our radar for a while, but never quite bubbled up to the top of the list.

However, it doesn't seem like it is significantly hard enough to call the original method from your fake to balance the trade-off of demonstrating to a user a potential design smell in their code.

I'm going to close this issue. Thanks for using Jasmine!
