### ISSUE TITLE
Piping a readable to a writable stream yields unexpected results

### ISSUE THREAD

**Issue by tdecaluwe** [jasmine/jasmine#1074]
When running the following program with node, the contents of the input file are shown in the terminal output:

```javascript
require('fs').createReadStream('input.txt').pipe(process.stdout);
```

However when executing the same program with jasmine, nothing is shown. Listening to the `data` event emitted by the readable stream with `on('data', ...)` yields no events.

Checking the docs for the node `Readable` streams:
> You can switch to flowing mode by doing any of the following:
> * Adding a `data` event handler to listen for data.
> * Calling the `stream.resume()` method to explicitly open the flow.
> * Calling the `stream.pipe()` method to send the data to a `Writable`.

So why doesn't this happen when running with jasmine?

**Note:** Replacing the file stream with any other readable stream, or `process.stdout` with any other writable stream shows the same behavior.

**Note:** When wrapping the code in a specification, as follows, the problem persists as well:

```javascript
it('should output the file', function () {
  require('fs').createReadStream('input.txt').pipe(process.stdout);
});
```

**Comment by amavisca** [comment]
The stream pipe interface is asynchronous, so you need to pass the `done` callback into the `it` function and call it when you are done with the test.

http://jasmine.github.io/2.4/introduction.html#section-Asynchronous_Support

Something like:
```
it('should output the file', function (done) {
  require('fs').createReadStream('input.txt')
   .on('end', done)
   .pipe(process.stdout);
});
```
