### ISSUE TITLE
Pretty print sparse arrays

### ISSUE THREAD

**Issue by deckar01** [jasmine/jasmine#1075]
Jasmine's pretty printer handles the string indexes of arrays nicely, but I am getting less than desirable results when a number index is used and the array is very sparse.

I ran into this issue due to the the javascript quirk that causes numerical string indexes to be treated the same as number indexes which increases the reported length.

```js
var array = [];
array['200'] = 1;
array['key'] = 2;
console.log(jasmine.pp(array));
```

`[ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, ..., key: 2 ]`

The expected output for this example would be `[ 200: 1, key: 2 ]`.

Dense arrays should almost certainly output the way they do now. Outputting an array's number indexes is usually less readable. As far as I know there is no standard threshold density qualifies a sparse array.

One reason this is an issue is that I am getting too much unneeded output, so the qualification could be a reduction in output size. A percentage of undefined values would be the easiest. Estimating the difference in output length is possible to do in [constant time](www.cplusplus.com/forum/general/59883/#msg325866), but is probably overkill.

Another reason this is an issue is that the actual value I am interested in gets folded into the `...` and obscured by a wall of 100 `undefined` values. That may indicate that this is only an issue with arrays whose length exceeds that output limit (100).

===

I am aware that there are helpers specifically built for jasmine that aid in cleaning up the output of matchers in odd use cases like this. I am using [jasmine-collection-matchers](https://github.com/just-boris/jasmine-collection-matchers).

This issue arises when a test like `expect(foo).toHaveBeenCalledWith('arg1', 'arg2')` fails and one of the spy's other (potentially unrelated) calls was passed a large, sparse array. When jasmine outputs the set of all arguments for the calls to that spy, the useful calls are obscured by the wall of `undefined` values.

===

> Note: I understand abusing arrays as objects is a weird code pattern, but I have to test some code as is before I can shift any of its paradigms.

**Comment by deckar01** [comment]
I looks like @pivotalops, @xian, and @maxbrunsfeld made most of the major changes to the pretty printer in the past. I looks like @Gerg and @slackersoft added the [array properties functionality](https://github.com/jasmine/jasmine/commits/master/src/core/PrettyPrinter.js) relatively recently.

**Comment by slackersoft** [comment]
Unfortunately, I'm not sure of a great way to determine when an array is in this situation. The Jasmine pretty printer would need to be able to detect the difference between

````javascript
var arrayWithUndefined = [undefined, undefined, 1]
````

and

````javascript
var arrayWithNumberKey = [];
arrayWithNumberKey[2] = 1;
````

Since they both report a `length` of 3 and `[0] === undefined`, this gets tricky because we don't want Jasmine to just ignore/hide array values that are `undefined`. The other option would be to print out arrays more similar to how objects are printed which would mean:

````javascript
jasmine.pp(['a', 'b', 'c'])
=>
[ 0: 'a', 1: 'b', 2: 'c' ]
````

instead of (currently):

````javascript
[ 'a', 'b', 'c' ]
````

The full key-based output for a simple array doesn't seem like an obvious way to view it. This seems like enough of an edge case and tricky enough to implement that it doesn't sound like something Jasmine needs itself. You should be able to provide a custom `toString` or `jasmineToString` on `Array.prototype` for your tests if you want to configure the output while you're moving away from this pattern.

Hope this helps. I'm going to close this issue. Thanks for using Jasmine!

**Comment by deckar01** [comment]
Oh, I can define `Array.prototype.jasmineToString()` to customize he formatting. Thanks for the help!
