### ISSUE TITLE
FeatureRequest: flags to filter specs to run

### ISSUE THREAD

**Issue by damianobarbati** [jasmine/jasmine#1078]
First: amazing job guys.

I think it would be great to allow developer to run specific specs by matching their name directly from command line.
When a fail raises after a mod, it's actually a pain to search and edit the spec file to apply the "f" before the interested "it" or "describe" block.
Could a flag like "-g pattern" to run just blocks matching the given pattern be implemented in the future?

**Comment by csymeonides** [comment]
[Jasmine on node](http://jasmine.github.io/2.4/node.html) supports `--filter`, that might do the trick for you. But I prefer the idea of labelling/tagging tests, as described [here](https://github.com/mhevery/jasmine-node/issues/343#issuecomment-214003468), what do you think?

**Comment by damianobarbati** [comment]
Wow, I don't know how could I possibly miss that. 
I was trying the standard syntax "jasmine --filter pattern" and "jasmine -g pattern".

Well, the simple describe/it name is already a label for the block, the second option you posted looks great.

Othre ideas:
jasmine --d upload <== run describe blocks matching upload
jasmine --i success <== run it blocks matching success
Better ideas:
jasmine --b upload:success <== run it blocks matching success in describe blocks matching upload
jasmine --b upload <== run describe blocks matching upload
jasmine --b :success <== run it blocks matching success
Even better (for nested):
jasmine --b d:form:d:upload:i:success <== run it blocks matching success in describe blocks matching upload nested in describe blocks matching form

Better tokens can be found instead of ":", like "@" or "#", I don't know
The goal of having a command line flag is isolating a block as fast as possible without touching the code . A single powerful flag like -b could solve every case.

Otherwise just let the developer add an array of tags as you mentioned. And the -t 'tag' will run everything matching that tag. Stop. :)
