### ISSUE TITLE
Jasmine seeing parsing error

### ISSUE THREAD

**Issue by danemery** [jasmine/jasmine#1080]
When feeding Jasmine this dummy data:

```
const testShowInfo = '{"id": "11655593", "artist": "Odesza", "date": "Thursday, March 24, 2016 at 10:00PM", "venue": "Pacific Coliseum", "location": "Vancouver, Canada", "tickets": "available"}';

const test_csrf = 'KGSa3p5f-eJDLDjksk6FQmRqx2aouBU9zY-w';
```
...and running this test (I'm returning and expecting an arbitrary number while I troubleshoot), I get **SyntaxError: Unexpected token u**:

```
describe('The Save Show Form', function() {

  beforeEach(function() {

    saveShow = {
      saveShowToDashboard: function(info, csrf) {
        const parsedShowInfo = JSON.parse(info);
        const _csrf = csrf;
        const data = {
          tourInfo: parsedShowInfo,
          token: _csrf
        };
        return 2;
      }
    };

    spyOn(saveShow, 'saveShowToDashboard').and.callThrough();

    saveShow.saveShowToDashboard(testShowInfo, test_csrf);

  });

  it('Should return a value of 2 for this test.', function() {
    expect(saveShow.saveShowToDashboard()).toEqual(2);
  });
});
```

According to my browser console, everything is being parsed just fine. Could this be a bug?

**Comment by cwmoo740** [comment]
`expect(saveShow.saveShowToDashboard()).toEqual(2)`

is calling JSON.parse(undefined) because it has no info argument. That's the "unexpected token u" error you're seeing. Either pass an argument that is parseable or add a check such as

`const parsedShowInfo = info ? JSON.parse(info) : null;`

**Comment by danemery** [comment]
I incorrectly assumed I only needed the arguments when calling it inside the beforeEach function. Thanks a ton.
