### ISSUE TITLE
Cannot find  spec\support\jasmine.json'

### ISSUE THREAD

**Issue by winnemucca** [jasmine/jasmine#1081]
Today I did npm installed jasmine.  I read about configuring it, and am having issues with jasmine on istanbul. I keep gettign back 

```
'c:\HA\VSTS\Applications\HA.Web.Main\spec\support\jasmine.json'
```

Does this file exist?  I see a reference to it on your docs.  All I see is the file path below.

````
node_modules >> jasmine >> lib >> examples >> jasmine.json
````

**Comment by Gerg** [comment]
The jasmine library on npm is here: https://github.com/jasmine/jasmine-npm. You can find information about the `jasmine.json` file in the readme.

I believe you will need to run `jasmine init` to create the file.

Thanks for using jasmine!
