### ISSUE TITLE
Where can I find automatic unit test generator for JavaScript?

### ISSUE THREAD

**Issue by wizardnet972** [jasmine/jasmine#1082]
Hi Guys,

Where can I find automatic unit test generator for JavaScript/Angular2/TypeScript?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
