### ISSUE TITLE
Spying on a function referenced from object doesn't work when this function was called indirectly

### ISSUE THREAD

**Issue by shamansir** [jasmine/jasmine#1083]
```javascript
var foo = (function() {

    function bar(a) {
        console.log(a);
    }

    function callBarWith(a) {
        bar(a);
    }

    return {
        bar: bar,
        callBarWith: callBarWith
    }
})();

var barSpy = spyOn(foo, 'bar').and.callThrough();
//var barSpy = jasmine.createSpy('bar', foo.bar).and.callThrough();
foo.callBarWith(42);
expect(barSpy).toHaveBeenCalled();
expect(barSpy).toHaveBeenCalledWith(42);
```

both variants of creating a spy doesn't work for jasmine v2.4.1

both result in:

* _Expected spy bar to have been called._
* _Expected spy bar to have been called with [ 42 ] but it was never called._

Though following the console report, `bar` reference was actually called with '42' and logged the call.

If I replace `foo.callBarWith(42)` with `foo.bar(42)`, everything works.

**Comment by shamansir** [comment]
Changing it to this variant obviously helps:

```javascript
var foo = (function() {

    var obj = {};

    obj.bar = function(a) {
        console.log(a);
    }

    obj.callBarWith = function(a) {
        obj.bar(a);
    }

    return obj;

})();
```

**Comment by Gerg** [comment]
Jasmine spies will only replace the function on the returned object. The `callBarWith` function will still have a handle on the original function. It should work if you call `this.bar` in `callBarWith` (even without modifying the prototype).

Thanks for using Jasmine!

**Comment by jackson-sandland** [comment]
What is the rationale behind having to need this workaround to get spies to work as the community believes they should? When we are testing, and we create a spy, and we indicate a desire to spy on a given method, the spy should be able to listen for the same method that we called when we console.log in that method to test whether or not the spy is being called...which it is, except jasmine can't figure that out.

**Comment by slackersoft** [comment]
Unfortunately Javascript just doesn't work this way. If you've saved off a reference to the original function, Jasmine can do whatever it wants to the object you grabbed the function from, but it won't change your local variable reference to the original function. You probably don't want that anyways, as that would imply that any Javascript code running in the same process as your Javascript code can modify any of your local variables it wants to without your consent.

An example:

```javascript
var foo = {
  bar: function() {
    console.log('original');
  }
};

var doThings = (function() {
  // save off a reference to the current function stored at foo.bar
  var myBar = foo.bar;

  return function() {
    myBar();
  }
})();

// replace the function stored at foo.bar
foo.bar = function() {
  console.log('replacement');
};

doThings();
> original

foo.bar();
> replacement
```

The Jasmine spy is installed similar to the replacement part of this example, so it is similarly unable to modify the saved off local variable reference.
