### ISSUE TITLE
Potential issue on asynchronous test using `done();`

### ISSUE THREAD

**Issue by motizuki** [jasmine/jasmine#1084]
Hello everyone,
By running the test below, the beforeEach in the inner describe block doesn't wait the `done()` be called before executing the inners `it` blocks.
Setting the inner it blocks a setTimeout of 1ms seems to solve the problem, however it doesn't seem to be ideal.
Does anyone have any thoughts about this? Is this really an issue?

```
describe('some test case..', function () {
    var User;
    beforeEach(function(){
        module(function($provide) {
            $provide.value('User', {
                performSignup: function(callback){
                    callback('123');
                }
            });
        });
    });

    beforeEach(inject(function (_User_) {
        User = _User_;
    }));

    describe('setting local variable this.uid inside the callback', function () {
        beforeEach(function (done) {
            User.performSignup(function(_uid){
                this.uid = _uid;
                done();
            });
        });

        it('should match value returned by callback - FAIL', function() {
            expect(this.uid).toBe('123');
        });

        it('nasty workaround adding a 1 ms timeout - PASS', function(done) {
            setTimeout(function(){
                expect(this.uid).toBe('123');
                done();
            },1);
        });
    });
});

```

Thanks in advance!

**Comment by slackersoft** [comment]
The other thing that is happening when you add the `setTimeout` like that is that the `this` object is different between the two calls of `expect(this.uid).toBe('123');`.

In the first `it`, the `this` is the object Jasmine provides for saving things (like your `uid`) for use across `beforeEach`, `it`, `afterEach` for a given spec. In the second `it`, the `this` will be the global object (`window` in a browser), which is probably the same object that it is being saved onto in the `beforeEach`. You should be able to check this by testing `expect(window.uid).toBe('123');` or saving off the `uid` value in a different way.

Additionally, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
