### ISSUE TITLE
Documentation for `this`

### ISSUE THREAD

**Issue by tpflueger** [jasmine/jasmine#1085]
I started having memory issue and was able to run into one of the issues on github that discussed using `this` to clean up. I think if the documentation discussed the use of `this` for cleanup it would be helpful.

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing this here. Thanks for using Jasmine!
