### ISSUE TITLE
Serialize objects passed to `done.fail` for readability

### ISSUE THREAD

**Issue by mmmichl** [jasmine/jasmine#1090]
When testing a promise based API the `done` and `done.fail` methods are a great help to write very efficient test code. Usually I end up with something like the following:

``` javascript
it('tests some async behaviour', function (done) {
  service.method()
    .then(function(result) {
      expect(result).toBe('something');
      done();
    })
    .catch(done.fail);
});
```

Now if the promise is rejected with an object as error description, the error message in jasmine is only `Failed: [object Object]`. This does not help in finding the issue at all. Thus in general I would change the `.catch` method to following:

``` javascript
.catch(function(err) {
  done.fail(JSON.stringify(err));
});
```

Although this is not a lot of code, it bloats up the test code with repetitive "housekeeping" code. In worst/extreme case it might take up most of the test method.

I would love to see a feature, where the `done.fail` method could print the content of a passed in object in a readable way.

During my research if someone raised this issue already, I stumbled upon the functionality of "Pretty-printing". I don't know enough on this feature, but could this maybe be applied to the error parameter?

**Comment by mmmichl** [comment]
If someone might be interested, I wrote a monkey patch:

```javascript
/**
 * Monkey patch fail method to serialize objects
 */
var origFail = jasmine.getEnv().fail;
jasmine.getEnv().fail = function (error) {
  if (typeof error !== 'string' && typeof error === 'object' && !error.message) {
    if (error.toString !== Object.prototype.toString) {
      error = error.toString();
    } else {
      error = JSON.stringify(error);
    }
  }

  return origFail.call(this, error);
};
```

**Comment by slackersoft** [comment]
I'm not sure if we want to do straight JSON serialization of the object, but we would be happy to review a pull request that makes `fail` in `Env.js` use Jasmine's pretty printer to format the object for human consumption.
