### ISSUE TITLE
Spy failed in image onload event

### ISSUE THREAD

**Issue by holmescn** [jasmine/jasmine#1093]
I am using karma-jasmine and browserify to test Vue component. One method listen on image on load event. But the spy that called in the event handler didn't get the right result. Following snippets shows the error:

    let spy = jasmine.createSpy('spy')
    spy.and.returnValues({
      name: 'name'
    })

    describe('example tests', () => {
      it('should pass', (done) => {
        var img = new Image()
        img.onload = function() {
          console.log('2', spy())
          done()
        }
        img.src = "http://dummyimage.com/100x100"
        console.log('1', spy())
      })
    })

here we are, at position 1, the log shows 1, but at position 2, the log shows undefined.

Versions:

1. jasmine-core 2.4.1
2. karma 0.13.22
3. karma-jasmine 0.3.8
4. karam-browserify 5.0.3

**Comment by Gerg** [comment]
`returnValues` will return undefined after it runs out of arguments: http://jasmine.github.io/2.4/introduction.html#section-Spies:_<code>and.returnValues</code>

If you want to return the same thing multiple times, use `returnValue`.
