### ISSUE TITLE
Angular2 (typescript) + Jasmine: require is not defined

### ISSUE THREAD

**Issue by junjunruan** [jasmine/jasmine#1094]
I have code `var fs = require("fs");` in app.component.ts inside my angular2 project, my app works. But when doing unit test with Jasmine, it comes with an error: `require is not defined` 

Does anyone know how to do with it?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
