### ISSUE TITLE
Allow reproducing of test order

### ISSUE THREAD

**Issue by janpaul123** [jasmine/jasmine#1095]
Recently I was debugging an intermittently failing test, which only happened when the tests were executed in a particular order (we have random test order enabled to prevent accidental dependencies between tests). However, this was hard to reproduce because Jasmine doesn't have functionality like in RSpec, where they print a seed that you can use to reproduce the same order. See https://relishapp.com/rspec/rspec-core/docs/command-line/randomization-can-be-reproduced-across-test-runs

It would be great to have something like that in Jasmine too!

**Comment by Gerg** [comment]
How are you running jasmine? Jasmine supports a `seed` query parameter for manually specifying seeds. It should be supported in the latest versions of the binding libraries.

**Comment by janpaul123** [comment]
Ah, I'm running it with `karma-jasmine` and `karma-jasmine-html-reporter` and don't see it in the interface, nor does the query parameter work there. But I'll look into those projects then, possibly they use an old version. Thanks for your help!
