### ISSUE TITLE
Unable to Handle model dialog in two different it().

### ISSUE THREAD

**Issue by Kothajagadeesh** [jasmine/jasmine#1097]
Hi, 

I've a scenario where clicking on a button will cause alert pop-up. I need to read the text inside the alert (alert.getText() is working) and then accept it(alert.accpet() working also). However, when i split alert.getText() and alert.accept() to two different its() the script is failing with Model dialog present

i Need to alert.getText() and alert.accept() in two different its(). Could some one please let me know if that is possible?

ENV:
Protractor 3.0.0.
IE 9.0
jasmine 2.x

Regards,
Jagadeesh

![alert](https://cloud.githubusercontent.com/assets/10230839/14643713/1265f834-066d-11e6-84a5-840c1ad45d4f.JPG)
![alerterror](https://cloud.githubusercontent.com/assets/10230839/14643712/12649f98-066d-11e6-9db3-b85761c075da.JPG)

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
