### ISSUE TITLE
Severe memory leak in core

### ISSUE THREAD

**Issue by bcherny** [jasmine/jasmine#1108]
While tracking down a memory leak in my Angular + Jasmine + Karma + Chrome test suite (the leak is bad enough that Chrome disconnects by the end of every test run, causing the suite to fail), I tried to write the simplest possible test setup to see if the leak exists there.

What I noticed is when running the same test in a loop (eg. 100,000x), memory usage as measured by `top` keeps climbing. The Chrome Browser process starts at around 240MB of memory, and climbs linearly to ~450MB until the suite is completed.

It seems like Jasmine is allocating a bunch of objects, and preventing GC from happening.

Repro code is below:

```js
// spec.js:

function test() {
  it('should pass', function() {
    expect(true).toBe(true)
  })
}

describe('test', function() {
  for (var n = 0; n < 100000; n++) {
    test()
  }
})
```

```js
// karma.conf.js:

module.exports = function (config) {
  config.set({
    frameworks: ['jasmine'],
    files: [
      './spec.js'
    ],
    browsers: ['Chrome']
  })
}
```

Full repro code is in this repo: https://github.com/bcherny/jasmine-leak-test.

And here is a memory timeline of the original leak, while running ~1500 tests for our production codebase:

![timeline](https://cloud.githubusercontent.com/assets/1761758/15030788/3b796c40-1209-11e6-8304-1c814bfd4ba0.png)

**Comment by timaschew** [comment]
Don't think it's jasmine, the same happens with mocha: https://github.com/timaschew/jasmine-leak-test

**Comment by bcherny** [comment]
@timaschew Pretty interesting stuff. I ran a timeline on your mocha suite, and the leak there feels a bit different - less frequent GC, more memory reclaimed at each GC-

Mocha:
<img width="1440" alt="screen shot 2016-05-24 at 11 12 06 am" src="https://cloud.githubusercontent.com/assets/1761758/15515036/e59ebc38-21a0-11e6-9890-5017bc803453.png">

Jasmine:
<img width="1440" alt="screen shot 2016-05-24 at 11 22 30 am" src="https://cloud.githubusercontent.com/assets/1761758/15515217/ec4b174c-21a1-11e6-9f86-c74c32ea305c.png">

What do you think this is, if not the test framework? Karma? Chrome?

**Comment by timaschew** [comment]
Oh, indeed. I just compared the total memory in my activity monitor and there was just a difference of 70MB (490 vs. 420).
My impression is that it's karma, but you could try it with Firefox and also just on Node.js without any karma and use node-inspector for profiling.

**Comment by Gerg** [comment]
Hey @bcherny 

Looks like this leak was not caused by Jasmine. Feel free to re-open if you find evidence to the contrary.

**Comment by bcherny** [comment]
To put some closure on this, it looks like this is just the way V8's GC works. Unless we are hitting some critical threshold of memory usage, V8 will avoid doing a GC until there is a pause in computation; with a bunch of synchronous operations (like in our test), it avoids pausing for GC.

To confirm this, I ran a synchronous and asynchronous loop in Chrome, without Jasmine or Karma. The respective timelines make it pretty clear:

**Synchronous:**

```html
<!doctype html>
<html>
	<body>
		<script>
			function test() {
	      var a = [1, 2, 3]
			}

			for (var n = 0; n < 10000000; n++) {
				test()
      }
		</script>
	</body>
</html>
```

<img width="1210" alt="screen shot 2016-07-13 at 11 17 31 am" src="https://cloud.githubusercontent.com/assets/1761758/16814604/75374150-48eb-11e6-9784-6fa2362112e8.png">

**Asynchronous:**

```html
<!doctype html>
<html>
	<body>
		<script>
			function test() {
	      var a = [1, 2, 3]
			}

			var n = 10000000
			function loop() {
				test()
        if (n-- > 0) {
          setTimeout(loop, 0)
        }
      }
      loop()
		</script>
	</body>
</html>
```

<img width="1208" alt="screen shot 2016-07-13 at 11 14 06 am" src="https://cloud.githubusercontent.com/assets/1761758/16814613/7c206244-48eb-11e6-992e-ebf64601f880.png">

**Comment by brandonros** [comment]
Is there any way to pause execution? I have a ton of unit tests dying becuase of this.

**Comment by slackersoft** [comment]
Newer versions of Jasmine should be going asynchronous in their execution much more often than previous versions. Currently, we should ensure a call to `setTimeout` approximately every 10 specs (specs aren't the only thing that causes the stack to clear) even if we're using `MessageChannel` or `setImmediate` for other stack clearing. The intent was to fix exactly this kind of issue where Jasmine wasn't fully giving up the stack, while still making use of the lower overhead functionality when available.

@brandonros what version of Jasmine are you using? Do you have a sample Jasmine suite so we can reproduce and try to fix the error you're seeing?

**Comment by brandonros** [comment]
@slackersoft A super old version. I will update. However... do you think it makes any difference that Chrome dies while executing the tests, but Firefox does not?

**Comment by slackersoft** [comment]
Based on @bcherny's [comment](#issuecomment-232442273), it is probably just a v8 optimization gone awry with the suite, and not cleaning up ever which causes a crash. I would love to hear whether a newer version of Jasmine fixes your issue.

**Comment by brandonros** [comment]
Confirmed this still happens in the latest jasmine version.

Not sure what else to provide. I can't provide my code base with 4,000+ unit tests... but... Chrome Helper crawls from 200mb memory to 2gb of memory then dies at about the 1,000th unit test.

Firefox, no problems.

**Comment by slackersoft** [comment]
I can't seem to get a reproduction case that does anything other than just cause Chrome or Firefox to slow way down. When you say that the suite "dies" in Chrome, what particular error message are you seeing? Are you using any javascript frameworks (Angular, React, etc.)? Something like that might help narrow down what is allocating the memory and possibly not letting it be freed.

The only way I can really get anything that feels like a memory leak is by having my specs specifically save things off outside of the specs.

```javascript
let stuff = [];

for(var j=0; j<1000; j++) {
  describe('The Thing ' + j, function() {
    let things;

    beforeEach(function() {
      things = makeStuff();
      stuff[0] = things;
      // stuff.push(things);
      // if (stuff.length > 100) { stuff[stuff.length-100] = null; }
    });

    it('does things', function() {
      return new Promise(function(resolve) {
        expect(stuff[stuff.length-1]).toEqual(things);
        resolve();
      });
    });
  });
}
```

If I change the commented lines to use the `push` and save all of the data off for the duration of the suite, it slows way down, but this doesn't seem like the use case you mention.
