### ISSUE TITLE
Jasmine doesn't seems to recognize Jquery parameter

### ISSUE THREAD

**Issue by wellingtonamaralleitao** [jasmine/jasmine#1109]
I'm trying to make jasmine work with node. I haven't found any useful information about my problem. Maybe the documentation was not clear enough for me. So I decided to ask you guys.

I've configured my jasmine.json like this:
``` json
{
  "spec_dir": "assets",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "assets/vendors/jquery.min.js",
    "js/src/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

**Working tree:**
```
codedummies
  assets
    js
      src
        script.js
      spec
        scriptSpec.js
    vendors
      jquery.min.js
  spec
    suport
      jasmine.json
```
And I got this error: 

`jQuery is not defined`

jQuery is passed as a parameter for my IIF javascript file like this:

`...})(jQuery);`

**Comment by slackersoft** [comment]
The paths passed to `helpers` should be relative to the specified `spec_dir`, so you probably want to remove the `assets/` from the jquery path.

Additionally, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
