### ISSUE TITLE
jsApiReporter Documentation

### ISSUE THREAD

**Issue by Whitebeard86** [jasmine/jasmine#1110]
Hello,

I'm trying to get the test results within Javascript, I've seen that Jasmine provides a jsApiReporter interface but how is it used? I can't find any documentation of a real scenario which handles the test results.

@note
I was able to handle the results using a custom reporter, but I'm a little confused about the jsApiReporter support. 

Thanks.

**Comment by Gerg** [comment]
The jsApiReporter is not technically considered part of Jasmine's public interface (and is therefore subject to breaking changes). It is used by Jasmine binding libraries like [jasmine-py](https://github.com/jasmine/jasmine-py).

That said, it has been relatively stable and would be a useful tool for developers like yourself. In the future I could see us committing to keep it stable and document it.
