### ISSUE TITLE
Unable to fail test if expect fails

### ISSUE THREAD

**Issue by bharathp** [jasmine/jasmine#1111]
Hi,

While using Jasmine 1.3, I was able to stop execution using "**fail()**" function long back but unable to do the same nowadays(since I'm getting error- 

> Referecne error: fail()

). So, upgraded to Jasmine 2.4 only to overcome this but I'm unable to abort test ('it' block) if any expect fails even in jasmine 2.4. 
Can anyone please guide me in aborting a test if any expect fails in jasmine 2.4

Thanks in advance.

**Comment by Gerg** [comment]
As of Jasmine 2.3, you can stop specs on execution failure. This is configurable in your browser using the menu in the top right, with the query parameter `throwFailures`, or by using certain jasmine runners' config files.
