### ISSUE TITLE
Testing set/get

### ISSUE THREAD

**Issue by ankit-m** [jasmine/jasmine#1115]
Testing the following snippet

```javascript
save(data, successMessage) {
    chrome.storage.local.set(data, (error) => {
      if (error) {
        this.status('Error Occurred. Please refresh.', 1000, 100, 'danger');
      } else {
        this.status(successMessage, 1000, 100, 'success');
      }
    });
  }
}
```

On calling `save(data, message)`, it should call `chrome.storage.local.set(...)`. The `spyOn` function returns the following error:

`Error: set is not declared writable or has no setter in /path/to/jasmine (line 2008)`

**Comment by jaapz** [comment]
Well, I think the error is quite clear. You are trying to overwrite (patch/spy on) a function that is not allowed to be overwritten. You're going to have to find a different way to mock out the chrome.storage part.

**Comment by ankit-m** [comment]
@jaapz Thank you!

**Comment by herodrigues** [comment]
@ankit-m have you found a good solution for this situation?

**Comment by ankit-m** [comment]
@herodrigues this is how I solved it

```javascript
// in the start of the file where test cases are written
// NOTE: this overrides chrome.storage.local.set/get everywhere while testing
global.chrome =  {
  storage: {
    local: {
      get: jasmine.createSpy('get'),
      set: jasmine.createSpy('set')
    }
  }
}

// in the test cases
describe('test something', () => {
  var chrome;
  beforeEach(() => {
    chrome = global.chrome;
  });
...
```

**Comment by herodrigues** [comment]
@ankit-m this will override everything under chrome?

For example, if I print chrome global variable with ```console.log(chrome)``` without overriding it, I get the whole chrome API object. However, if I do something similar like what you did, I just get a simple object:

Without overriding it:
```
LOG: Object{alarms: Object{}, bookmarks: Object{}, browserAction: Object{}, browsingData: Object{}, certificateProvider: Object{}, commands: Object{}, contentSettings: ...
```

Overriding browserAction.setIcon:
```
LOG: Object{browserAction: Object{setIcon: Object{get: ..., set: ...}}}
```

What I want to do is simulating a user clicking and browsing with my extension.
