### ISSUE TITLE
API Document PLEASE!

### ISSUE THREAD

**Issue by qx** [jasmine/jasmine#1116]
I really hate tools without api doc, It's too hard to use!
if I must look out method from source code??

**Comment by glebec** [comment]
http://jasmine.github.io/2.4/introduction.html

**Comment by Gerg** [comment]
@qx is that what you were looking for? If not, what documentation would you expect? How could we better surface the documentation?

**Comment by qx** [comment]
Sorry for late reply, introduction is good for learn ,but not for search. @Gerg

**Comment by stijnherreman** [comment]
A TOC would be handy on that introduction page.

**Comment by alewang** [comment]
I would like a page that cleanly lists what sorts of objects and methods are available. A wall of text is definitely not helpful.

Something like Protractor's API page would be neat: http://www.protractortest.org/#/api

**Comment by Gerg** [comment]
I'm going to close this as a duplicate of #596 

Please continue any discussion there. Thanks!
