### ISSUE TITLE
works via CLI but not through HTML, 404 not found

### ISSUE THREAD

**Issue by Mr-Binary** [jasmine/jasmine#1118]
This is a project written by Typescript, I use jasmine to do some unit testing. Now it can work via the command line, but doesn't work with the fancy html page. It said 404, how to solve it?

This is my UnitTest.html, it is in the root of the project.

```
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>My App Unit Tests</title>
    <link rel="stylesheet" href="node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
</head>

<body>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/typescript/lib/typescript.js"></script>
    <script>
        System.config({
            transpiler: 'typescript'     
        });
        System.import('./spec/UnitTest.spec.ts')
            .then(window.onload)
            .catch(console.error.bind(console));
    </script>
</body>

</html>
```

This is the jasmine.json

```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

This is the actural test file, in the "spec" folder, the folder is the just under the root.

```
import { FindViewModel } from '../Application/TS/ViewModels/FindViewModel';
import { ISpeechService } from '../Emulator/TS/Services/ISpeechService';


describe('Tests for the FindViewModel', () => {
  it('getKeyword() should return a string', () => {
    let returnValue: string = (new FindViewModel()).getKeyword();
    expect(returnValue).toEqual(jasmine.any(String));
  });

  it('getKeywordByVoice() should return a string', () => {
    let checkThisValue:string;
    class mockSpeech implements ISpeechService{
        recognize():string{
            return checkThisValue;
        }
    }

    let testFindViewModel = new FindViewModel();
    let findKeywordByVoice = testFindViewModel.getKeywordByVoice(new mockSpeech());
    expect(findKeywordByVoice).toEqual(checkThisValue);
  });
});
```

After compile the Typescript, It can run smoothly via cli, I can comfirm, because when I try to screw the test, it throws exception.
[![enter image description here](http://i.stack.imgur.com/zMMyB.png)](http://i.stack.imgur.com/zMMyB.png)

But it won't run via browser, The error from the browser is just as following, seems can't find the File that imports from the unittest.spec.ts?

[![enter image description here](http://i.stack.imgur.com/Zih1V.png)](http://i.stack.imgur.com/Zih1V.png)
[![enter image description here](http://i.stack.imgur.com/26LOR.png)](http://i.stack.imgur.com/26LOR.png)

This is my structure of the project.
[![enter image description here](http://i.stack.imgur.com/lCaPO.png)](http://i.stack.imgur.com/lCaPO.png)

How to solve it?

**Comment by slackersoft** [comment]
Since you're letting the TypeScript library load all of your code and tests, you'll need to stop Jasmine from `execute`ing your suite when `window.onload` is triggered and wait to start that until TypeScript has loaded everything down from the server. Jasmine can only execute specs it knows about.

Closing, since this doesn't sound like it is a problem with Jasmine itself. Thanks for using Jasmine!
