### ISSUE TITLE
Passing undefined/null to beforeEach() causes tests to be silently skipped.

### ISSUE THREAD

**Issue by voithos** [jasmine/jasmine#1119]
Passing `undefined` or `null` to `beforeEach()` causes the tests in the given spec file to be silently skipped, without any error. Here's an example showcasing the problem in Jasmine 2.4.1: http://codepen.io/anon/pen/EKzqVe

The issue seems to occur [on this line](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/QueueRunner.js#L37) - `queueableFn.fn` ends up being `undefined`, so the attempt at accessing `.length` throws an error which is somehow swallowed (you can see the issue using the "Pause On Caught Exceptions" feature of Chrome's Devtools).

**Comment by slackersoft** [comment]
This sounds like a duplicate of #1004. Closing in favor of the more comprehensive issue there.

Thanks for using Jasmine!
