### ISSUE TITLE
Allow custom matchers to customize the error message

### ISSUE THREAD

**Issue by deckar01** [jasmine/jasmine#1123]
**Issue**:

Large output messages returned by custom matchers are difficult to read.

**Behavior**:

[`Expectation.prototype.wrapCompare()`](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/Expectation.js#L63) only passes along the custom matcher's `message`, so [`buildExpectationResult`](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/ExpectationResult.js#L26) has to construct a new error, which [duplicates the message](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/ExpectationResult.js#L40).

![screenshot from 2016-05-26 12-25-39](https://cloud.githubusercontent.com/assets/3108007/15583814/06f369e0-233d-11e6-84b7-33c0268fa379.png)

Having a really long line in the message breaks the [`HTMLReporter` layout](https://github.com/jasmine/jasmine/blob/master/src/html/_HTMLReporter.scss#L322).

![screenshot from 2016-05-26 12-36-33](https://cloud.githubusercontent.com/assets/3108007/15584075/883af8d2-233e-11e6-9997-a7c6557f00e4.png)

**Expected behavior**:

[`Expectation.prototype.wrapCompare()`](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/Expectation.js#L63) allows custom matchers to return an `error` object in its results and passes it to [`buildExpectationResult`](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/ExpectationResult.js#L26) which will specify a custom error message.

``` js
jasmine.addMatchers({
  exampleMatcher: function() {
    return {
      compare: function(actual, expected) {
        ...
        return {
          pass: pass,
          message: message,
          error: new Error (message + '\n\n' + details)
        };
      }
    };
  }
});
```

![screenshot from 2016-05-26 12-20-52](https://cloud.githubusercontent.com/assets/3108007/15583670/661b3db8-233c-11e6-83eb-e271b76bcb3d.png)

The [`HTMLReporter` layout](https://github.com/jasmine/jasmine/blob/master/src/html/_HTMLReporter.scss#L322) should specify `.jasmine-result-message { overflow-x: scroll; }` to prevent horizontal overflow out of the document body (although it is less of an issue when the extended details are moved to the error).

**Comment by deckar01** [comment]
I'm not sure if/when this would ever land, so I made a helper to override `Expectation.wrapCompare()`.

```js
eval(
  'jasmine.Expectation.prototype.wrapCompare = ' +
  jasmine.Expectation.prototype.wrapCompare.toString()
  .replace(/message:\s*(\w+),\n/, 'message: $1, error: result.error,\n')
);
```

**Comment by deckar01** [comment]
... and published it as a helper:

https://github.com/deckar01/jasmine-matcher-errors

**Comment by deckar01** [comment]
... and now it supports jasmine v1.

https://github.com/deckar01/jasmine-matcher-errors

**Comment by slackersoft** [comment]
I would be happy to review a pull request that allows a matcher to optionally specify an `Error` for the purpose of printing a more detailed message.
