### ISSUE TITLE
Possibility to run external script before/after

### ISSUE THREAD

**Issue by johnBim** [jasmine/jasmine#1124]
Hello,
I would like to know if there is there the possibility to run an external script file before/after jasmine runs all tests written?
e.g run a bat file to execute some task automatically when in Visual studio jasmine starts and just before it starts to run effectively the tests.

    It is possible to capture the moment it start/end to run all tests?

Thanks for help

**Comment by adityaparab** [comment]
Hi, This is a `question` not an `issue` as such. This would have been answered very quickly had it been posted on `StackOverflow` :)

But in any case, you can take advantage of jasmine's custom reporters.

```
var JohnsReporter = {
    jasmineStarted: function(suiteInfo) {
        //This is where you call your batch file or external javascript file 
        //(make sure you `require` it above :) ) or whatever
    },

    jasmineDone: function() {
        // This is where you call your post jasmine stuff.
    }

}
```

And in your jasmine config you write:

`jasmine.getEnv().addReporter(JohnsReporter );`

**Comment by johnBim** [comment]
Hi,
Thank you, I will try this.
Regards
