### ISSUE TITLE
Help with testing javascript Closure in jasmine

### ISSUE THREAD

**Issue by ramavaxa** [jasmine/jasmine#1126]
I am completely novice at using jasmine. I couldn't figure out how can I write a test case for a java script closure like below.

My code in Typescript is as follows

```
module FIRST.Mobile.Controllers{
"use strict";
class sampletest
{
public  subtract(a: number, b: number): number {
    return a - b;
}
}
}
```

And when converted to JavaScript it becomes

```
var FIRST;
(function (FIRST) {
    var Mobile;
    (function (Mobile) {
        var Controllers;
        (function (Controllers) {
            "use strict";
			var sampletest = (function () {
                function sampletest() {
                }
                sampletest.prototype.subtract = function (a, b) {
                    return a - b;
                };
                return sampletest;
            })();
        })(Controllers = Mobile.Controllers || (Mobile.Controllers = {}));
    })(Mobile = FIRST.Mobile || (FIRST.Mobile = {}));
})(FIRST || (FIRST = {}));
```

I do not understand if I could test code in a typescript module? 
If yes can some one explain me how could I test the subtract method using jasmine. 

Thank you

**Comment by Gerg** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js) or sites like stackoverflow. We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
