### ISSUE TITLE
Dynamically Loading Javascript files in test file.

### ISSUE THREAD

**Issue by thomasbuckle-uk** [jasmine/jasmine#1130]
Hi 

Currently working on getting our testing setup for a jQuery plugin. 
In our test cases we need to be able to load different javascript files on the same test. 
We're using fixtures to load html files but gotten stuck on how to include an external javascript file into a test.
Is there any built in way to do this in Jasmine, if not could anyone suggest how I could go about it?

Thanks for your help.

**Comment by jaapz** [comment]
Either add them manually to your TestRunner.html file (just add a `<script>` tag), or use something like [karma](http://karma-runner.github.io/0.13/index.html).

This kind of question would better be asked on stackoverflow, though. This issue tracker is meant for bugs :smile:
