### ISSUE TITLE
Help with "extending" the BDD interface

### ISSUE THREAD

**Issue by tarciosaraiva** [jasmine/jasmine#1133]
Hi there
I need some help to extend the default Jasmine interface (describe, before, etc) to add my own methods to it.

Instead of doing something like

```
describe('Module', function() {
  it('should assert true', function() {
  ))
})
```

I would like to do something like

```
NewInterface('Module', function () {
  check('title', function, function() {
  })
})
```

I'm having a hard time trying to put the pieces together. I know about the jasmine-npm project and understand (ish) the boot file but it feels excessive to have to write a new boot file to expose more methods in the interface.

I've also read about the guidelines to "not change the interface" which is fine, but wondering, in this case I would like to have people using the new interface with Jasmine under the hood.

Is there any other way? Like using a configuration file like the matchers or something?

Thanks for your help

**Comment by Gerg** [comment]
Creating a custom boot file is the official way to do this. You could also do something like `NewInterface = describe;` in your test setup.

Thanks for using Jasmine!
