### ISSUE TITLE
Inherit parent context in beforeAll

### ISSUE THREAD

**Issue by chaoran** [jasmine/jasmine#1135]
I have a test suite organized like this:
```
describe('Something', function() {
  beforeEach(function() {
    this.something = new Something();
  });
  describe('Suite 1', function() {
    beforeAll(function() {
      this.something.setSomething();
    });
    ... // a series of tests
  });
  describe('Suite 2', function() {
     beforeAll(function() {
      this.something.setSomethingElse();
     });
     ... // a series of tests
  });
});
```

I assume the `something` I created in `beforeEach` can be seen in the `beforeAll` child scope. However, this is not the behavior currently jasmine implemented (2.4.1).

I don't understand why this behavior is not supported. If not passing the parent context setup by beforeEach to beforeAll is the intended behavior, it would be nice to know why.

**Comment by Gerg** [comment]
I believe the issue is that all `beforeAll` functions are run before `beforeEach` functions. See this issue for details: https://github.com/jasmine/jasmine/issues/873
