### ISSUE TITLE
TypeScript source and testing

### ISSUE THREAD

**Issue by heruan** [jasmine/jasmine#1136]
I have a JS app with Jasmine tests, but now I'm in the process of rewriting the entire app in TypeScript. I'd also like to rewrite the tests in TypeScript. Any suggestion on how to test with Jasmine then? Currently I'm transpiling all to JS and testing in a temporary build, but I hope to find a more straightforward way.

**Comment by ValeriiVasin** [comment]
I solved this problem with [ts-node require hook](https://github.com/TypeStrong/ts-node#programmatic-usage). Just by adding helper first.

ts-node.helper.js:
```javascript
require('ts-node/register');
```

jasmine config:
```json
"helpers": [
  "ts-node.helper.js"
]
```

That works pretty fine.

BTW, same goes for babel :)

**Comment by heruan** [comment]
That's perfect. Thank you @ValeriiVasin!
