### ISSUE TITLE
No Nested It?

### ISSUE THREAD

**Issue by kariasbolster** [jasmine/jasmine#1140]
Hi, I am doing a front-end automation using protractor and jasmine. My test scenarios heavily reliant with the front end as such my specs are dynamic and loop dependent. Example of what I am doing: in the page there is this called template ( template for a survey ). It is divided into groups and each groups contains questionnaires ( can be multiple-choice, rubric type, or open-ended ). My test involves creating a template, which includes creating the groups and the questionnaires to create a whole template. Then I need to check if the front-end actually displays what I created. I have no problem with creating but my problem is the checking. I am not allowed to do the checking the same time as creating, they must be separate as after creating I need to save it first before I can do the checking. Since, I need to check the questionnaires and groups, I need to loop a lot. So first I need to loop the groups and then loop the questionnaires in each group and then check its question text and question options. So my first it block is to loop the groups it looks like this: 

```
it( 'Should loop groups', function () {
groupPage.getGroups().map( function ( groupEl, groupIndex ) {
		if ( groupIndex > 0 ) {
			groupPage.clickGroup( groupIndex );
		}
                it( 'Should verify group title for group: ' + groupIndex, function () {
                        expect( groupPage.getGroupName() ).toEqual( 'Group Name' );
                }  );
	} );
} );
```

However the questionnaires are within the groups, so within the loop group it block, I need to write it blocks for the questionnaires and assert the question texts and option texts. In order to do that, I need to nest the questionnaires it inside the group it. It should look like this.

```
it( 'Should verify group titles', function () {
	groupPage.getGroups().map( function ( group, groupIndex ) {
		if ( groupIndex > 0 ) {
			groupPage.clickGroup( groupIndex );
		}
                it( 'Should verify group title for group: ' + groupIndex, function () {
                        expect( groupPage.getGroupName() ).toEqual( 'Group Name' );
                }  );
                questionPage.getQuestions().map( function ( question, questionIndex ) {
                        verifyQuestionText( questionIndex );
                } );
	} );
} );


function verifyQuestionText( questionIndex ) {
       it( 'Should verify question text: '  + questionIndex, function () {
              expect( questionPage.getQuestionText() ).toEqual( 'Question Text' );
       } );
}
```

But this doesn't work. It won't execute the nested it blocks. Any advice?

**Comment by Gerg** [comment]
Jasmine does not support nesting `it` functions inside each other. If you remove the nested `it` calls, then it appears that you spec will work. 

Why are you interested in nesting `it`s? It appears that you only need to to do that because your test is not aware of what groups/questions are created until runtime. If you programmatically did test setup, then you would know exactly what groups and questions you needed to check.

**Comment by vance** [comment]
the problem is it is sometimes hard to persist class instances across it statements, leading to redundant setup code. This really happens often when testing angular2 services, for instance.

**Comment by slackersoft** [comment]
In general you _shouldn't_ have shared state between two specs. If this is something you really want, take a look at the [setup options](https://jasmine.github.io/2.5/introduction.html#section-Setup_and_Teardown) that Jasmine has.
