### ISSUE TITLE
Can you update npm?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [jasmine/jasmine#1144]
jasmine-core v2.4.1 on npm is not the same with github, it's painful.
/lib/jasmine-core/jasmine.js/ on npm:
```
line 26:    if (typeof module !== 'undefined' && module.exports) {
```
/lib/jasmine-core/jasmine.js/ on github:
```
line 26:  if (typeof module !== 'undefined' && module.exports && typeof exports !== 'undefined') {
```

**Comment by amavisca** [comment]
I'm blocked on bumping jasmine-npm until we get a core release.
We do weird things in jasmine-npm: https://github.com/jasmine/jasmine-npm/issues/81 that I can stop doing once we get a core release out.

@Gerg @slackersoft What do we need to do to get a core npm release out?

**Comment by Gerg** [comment]
2.5 was released
