### ISSUE TITLE
Please update Glob dependency (minimatch@0.3.0 deprecated)

### ISSUE THREAD

**Issue by aszegedi** [jasmine/jasmine#1148]
Hi,

I get the following warning during my test environment install:
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
as far as I see this comes from `jasmine@2.4.1` dependency for `glob@3.2.11` (here `"minimatch": "0.3"` is defined as dependency). So the install shows:
```
+-- jasmine-reporters@2.2.0 
| +-- jasmine@2.4.1 
| | +-- exit@0.1.2 
| | +-- glob@3.2.11 
| | | `-- minimatch@0.3.0 
| | |   +-- lru-cache@2.7.3 
| | |   `-- sigmund@1.0.1 
| | `-- jasmine-core@2.4.1 
| +-- mkdirp@0.5.1 
| | `-- minimist@0.0.8 
| `-- xmldom@0.1.22 
```
Could you help me out to resolve this issue. Maybe just a Glob update is needed for Jasmine.

**Comment by amavisca** [comment]
@aszegedi This is an issue in the node runner here: https://github.com/jasmine/jasmine-npm/issues/78

I'm working on finding out what we need to do to get a release out.

Thanks for the report!

**Comment by amavisca** [comment]
Well actually this happens when I `npm install` this module too since the jasmine-npm module is a `devDependency`. I'll leave this open for now.

**Comment by satidurga** [comment]
couls u plz help me in solving this issue

![image](https://user-images.githubusercontent.com/22154176/29238637-5c31e694-7f57-11e7-80a6-66afe50e3f01.png)

**Comment by slackersoft** [comment]
This repository is published to npm as `jasmine`. The jasmine-node package is not maintained by the jasmine team, and I'm not totally sure how maintained it is at all now. [jasmine-node](https://github.com/mhevery/jasmine-node)
