### ISSUE TITLE
NodeJS: Promise.then() doesn't get called during test?

### ISSUE THREAD

**Issue by ShashankaNataraj** [jasmine/jasmine#1153]
Im returning a promise from a module for an async file read function. The `.then` method in the promise doesnt get executed. Is this a known bug?

[Source code is here](https://github.com/ShashankaNataraj/Dexter/blob/master/spec/HarReader.spec.js#L8)

**Comment by amavisca** [comment]
It's not a bug, you're doing an async operation so Jasmine doesn't have a way to know when your test is done.
There's some documentation of async tests here: http://jasmine.github.io/edge/introduction.html#section-Asynchronous_Support

You need to ask for the done callback in the `it's` function, something like this:
```
it('does something async', function(done) {
  doSomethingAsync().then(function() {
    expect('foo').toEqual('foo');
    done();
  }, function(e) {
    done.fail('The promise rejected because of ' + e.message);
  });
});
```

Going to mark this issue as closed! For usage questions: https://groups.google.com/forum/#!forum/jasmine-js

You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the jasmine-js group. We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
