### ISSUE TITLE
Test failures on feature branches should not make the Travis badge red

### ISSUE THREAD

**Issue by benchristel** [jasmine/jasmine#1164]
I'd expect the badge to reflect only the state of `master`. If I push failing tests to a feature branch that has a PR open, the badge currently turns red.

**Comment by benchristel** [comment]
Never mind, it seems that `master` actually has failing tests 😲

**Comment by Gerg** [comment]
Yea, the issue is that sauce doesn't run against PRs. Your last PR broke
ie8.
