### ISSUE TITLE
Permanent "Cancelled" result if using Asynchronous XMLHttpRequest in Google Chrome

### ISSUE THREAD

**Issue by alexander-ossur** [jasmine/jasmine#1167]
Hi there,

I am having both Karma and Jasmine installed. The case described below is tested without Jasmine-Ajax. 
For some reason asynchronous ajax requests to remote servers failed with "cancelled" state in the Google Chrome console.

```
describe ("Test:", function () {
	it ("test XMLHttpRequest", function (done) {
		var xhr = new XMLHttpRequest ();

		xhr.addEventListener ("load", function (event) {
			done ();
		}, false);

		xhr.open ("GET", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js", true);
		xhr.send ();
	});
});
```

### Expected behavior
1. Ajax requests should work as expected

### Actual behavior
Ajax ends with "abort" event and exists.
Also the code below works fine in the Google Chrome console:
```
var xhr = new XMLHttpRequest ();

xhr.addEventListener ("load", function (event) {
	console.log ("ALL OK");
}, false);

xhr.open ("GET", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js", true);
xhr.send ();
```

### Enviroment Details

- windows 8.1
- gulp CLI version 3.9.1
- gulp Local version 3.9.1
- Karma version: 1.1.0
- jasmine-core: 2.4.1

### Workaround

Currently it seems stable if working with synchronous requests:
```
describe ("Test:", function () {
	it ("test XMLHttpRequest", function (done) {
		var xhr = new XMLHttpRequest ();

		xhr.addEventListener ("load", function (event) {
			done ();
		}, false);

		// TADAAA: synchronous!
		xhr.open ("GET", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js", false);
		xhr.send ();
	});
});
```

**Comment by Gerg** [comment]
I'm not able to reproduce this running just Jasmine. My guess would be that this is either Karma or one of your other libraries.

Here is a codepen where I tried to reproduce: https://codepen.io/Gerg/pen/bZKavz

**Comment by veloxinsurance** [comment]
fuk
