### ISSUE TITLE
Unresolved function or method configureDefaultReporter()

### ISSUE THREAD

**Issue by Mercieral** [jasmine/jasmine#1173]
Hello,

I am very new to using Jasmine and I am trying to set it up to use jasmine-spec-reporter instead of the default reporter. However I cannot remove the default reporter because configureDefaultReporter() is undefined. I am using version 2.3.2

Here is my code 
```javascript
var Jasmine = require('jasmine');
var jasmine = new Jasmine();
var SpecReporter = require('jasmine-spec-reporter');

jasmine.loadConfig({
    "spec_dir" : "test/electron",
    "spec_files" : [
        "electron_spec.js"
    ],
    "helpers" : []
});

jasmine.configureDefaultReporter({
    print: () => {}
});

jasmine.getEnv().addReporter(new SpecReporter());
```

This should be pretty close to exactly the same as the docs
http://jasmine.github.io/2.4/node.html#section-25
http://jasmine.github.io/2.4/node.html#section-Reporters

I have tried using jasmine.getEnv().configureDefaultReporter() as well.

Any thoughts/suggestions?

I apologize in advance if this is something incredibly simple that is going over my head.

**Comment by amavisca** [comment]
The last line should be:
`jasmine.addReporter(new SpecReporter());`

the `jasmine.addReporter` interface is provided by the node runner and is what will cause the default to not be added.

**Comment by Mercieral** [comment]
That worked, thanks! Is this documented anywhere because all of my searching and examples showed that I had to use configureDefaultReporter() to remove the original?

**Comment by amavisca** [comment]
http://jasmine.github.io/2.4/node.html#section-Reporters
