### ISSUE TITLE
noTryCatch option to make debugging easier

### ISSUE THREAD

**Issue by craigcomstocks** [jasmine/jasmine#1174]
When a spec throws an exception and a developer has dev tools open it would be better if the exception is thrown all the way out and causes test execution to stop and the browser to open the source of the exception and begin debugging.

Our current implementation simply avoids the try/catch in QueueRunner attemptSync and attemptAsync functions.

**Comment by craigcomstocks** [comment]
I am investigating whether Env.catchExceptions(false) is suitable for this purpose or can be modified for this purpose.

**Comment by craigcomstocks** [comment]
With catchExceptions, the exception is thrown from a different location than it's source and so with Chrome or IE11 the debugger position lands on QueueRunner.handleException() instead of at the source as it would if there was no try/catch.

**Comment by slackersoft** [comment]
My inclination here would be to solve the problems of correct stack traces and making sure break on errors works correctly, by using a global error handler like `window.onerror` to handle all errors to associate them with the currently running spec. This would also solve #529 for async specs as well. I don't think we want yet another option to configure exception handling in Jasmine.

I'm going to close this in favor of a more general change to handle all errors the same way at a global level that also solves the async case. Thanks for using Jasmine!

**Comment by craigcomstocks** [comment]
Sounds good. Thanks for looking at the bug and PR.
