### ISSUE TITLE
jasmine.anything() doesn't match undefined

### ISSUE THREAD

**Issue by w3apps** [jasmine/jasmine#1176]
When using
`spyOn(myFn, 'myMethod');`
`myFn.myMethod(undefined);`
`expect(myFn.myMethod).toHaveBeenCalledWith(jasmine.anything());`

I get
`Expected spy call to have been called with [ <jasmine.anything> ] but actual calls were [ undefined ]`

If I use anything other than 'undefined' everything is fine.

**Comment by Gerg** [comment]
This is the expected behavior. See the [docs](http://jasmine.github.io/2.4/introduction.html#section-Matching_existence_with_<code>jasmine.anything</code>) for more info on jasmine.anything.

**Comment by w3apps** [comment]
You are correct, not sure how I missed that. However is there a way to match even `null` and `undifined`?

**Comment by slackersoft** [comment]
You can also supply your own [custom asymmetric matcher](http://jasmine.github.io/2.4/introduction.html#section-Custom_asymmetric_equality_tester) that behaves however you want.

**Comment by vanta** [comment]
Is there a way to do it in easy way?

**Comment by filmaj** [comment]
Or perhaps `jasmine.nothing()`, to match to null or undefined?

**Comment by slackersoft** [comment]
I think an asymmetric matcher like `jasmine.ignored()` or something that basically, just returns `true` for anything that's passed to it would solve this. You might even just be able to implement that in your own suite without Jasmine doing anything.

**Comment by timrayers** [comment]
Would `jasmine.anything() || undefined` not work?

```
expect(myFunctionSpy).toHaveBeenCalledWith(
    jasmine.anything() || undefined
);
```

**Comment by sebinsuresh** [comment]
You can create and use this [asymmetric equality tester](https://jasmine.github.io/tutorials/custom_asymmetric_equality_testers):
```ts
const reallyAnything = () => ({
  asymmetricMatch: (_) => true,
});
```

and use it like so:

```ts
expect(someClass.method).toHaveBeenCalledOnceWith(
  reallyAnything(),
  jasmine.any(String),
  "specific value"
);
```
