### ISSUE TITLE
Jasmine and JavaScript for Automation (JXA) on the Mac

### ISSUE THREAD

**Issue by dagware** [jasmine/jasmine#1179]
Any chance that Jasmine works with JavaScript for Automation (JXA) on the Mac? JXA can't be run in the context of a browser - it has access to OS APIs and things like that, so as I said, it can't run in a browser.

Any ideas?

Thanks

**Comment by joeldbirch** [comment]
Just yesterday, I had a crack at getting Jasmine testing working (via [Testem](https://github.com/testem/testem)) for my JXA scripts reached this stumbling block. I began doing silly stuff, like:

1. stubbing objects non-browser objects, eg. `if (!Application) Application = function(){};`, and
2. adding conditionals to check for features before using them in my JXA scripts, eg. `const finder = Application('Finder'); if (finder) finder.includeStandardAdditions = true;`

This allowed the tests to run in the browser, but (obviously) you can only test the most basic functions that don't rely on OS APIs, which I'm finding isn't really worth the effort.

I'm rewriting an eight year old AppleScript with JXA using cool ES6 stuff (via Browserify/Babelify, NPM, etc) and it is so much better. We just need a testing solution to make it all feel reliable.

**Comment by dagware** [comment]
Yeah, I thought about mocking all that stuff, and it's not an undoable thing. I could build up a library of mocks, I suppose. I was just hoping for the real thing.

Still, good ideas. Having testing in place just feels good. :)

**Comment by Gerg** [comment]
Jasmine should work fine without a browser (for example: [Jasmine in node](https://github.com/jasmine/jasmine-npm)). You will have to run your specs in JXA rather than in a browser.

If JXA supports NPM packages, you should check out [jasmine core](https://www.npmjs.com/package/jasmine-core). It contains all the guts of Jasmine, so you will just have to hook it up yourself.

**Comment by dagware** [comment]
Thanks. I have no idea how to do any of this, but that won't stop me from diving in and trying. Thanks again.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
