### ISSUE TITLE
Improve default error messages for typed arrays

### ISSUE THREAD

**Issue by reiner-dolp** [jasmine/jasmine#1180]
For typed arrays, only a comma-separated list of array elements is output, which can cause confusion.

**For example:**

``` js
expect(new Uint32Array([1,3,2,5,4,8,])).toEqual(new Uint8Array([1,3,2,5,4,8,]));
```

outputs

```
Error: Expected 1,3,2,5,4,8 to equal 1,3,2,5,4,8.
```

**Comment by Gerg** [comment]
How would you suggest we pretty print typed arrays? Ideally we could find a solution that doesn't affect regular arrays (since they are far more common).

**Comment by reiner-dolp** [comment]
How about one of these: 
```
if(is_typed_array()) {
msg = "Error: Expected array 1,3,2,5,4,8 of type uint32 to equal array 1,3,2,5,4,8 of type uint8"
msg = "Error: Expected array type uint32 to equal uint8" // <-- hides values until type matches
msg = "Error: Expected Uint32Array 1,3,2,5,4,8 to equal Uint8Array 1,3,2,5,4,8" // <-- my fav
}
```

**Comment by Gerg** [comment]
I also like "Error: Expected Uint32Array 1,3,2,5,4,8 to equal Uint8Array 1,3,2,5,4,8" as long as it doesn't show the type for regular arrays. For example, we **don't** want "Error: Expected Array 1,3,2,5,4,8 to equal Array 11,13,12".

We'd be happy to review a pull request to accomplish this.

**Comment by mezoistvan** [comment]
Hi! I'm using Jasmine as my daily driver, and I'd like to start working on this issue if that's ok!

**Comment by reiner-dolp** [comment]
I am not working on it. Would appreciate!
