### ISSUE TITLE
Allow reporters to be cleared

### ISSUE THREAD

**Issue by hakunin** [jasmine/jasmine#1183]
Hey guys,
I wanted to swap the default Jest reporter, but since they do their own config somewhere and Jasmine only supports *adding* reporters and not removing old ones, I can't use any reporters unless the guys at Jest make that configurable somehow.

Seems like being able to clear or remove reporters would solve this nicely.

**Comment by slackersoft** [comment]
Sounds reasonable. We'd be happy to review a pull request to accomplish this.

**Comment by slackersoft** [comment]
This should be fixed as of 04bb56a5b553e005dd615f12a6892e5395c9dfb5. We were looking to solve some other problems, namely jasmine/jasmine-npm#88
