### ISSUE TITLE
Stop single test on first expectation failed

### ISSUE THREAD

**Issue by poliveira89** [jasmine/jasmine#1184]
Using jasmine 2.4, and I was wondering if it's possible to **stop a single test** on first expect failed. I mean the test (`it` block code) not the entire suite/set of tests (`describe` block code).

I have acknowledged the existence of `stopSpecOnExpectationFailure` but this stop all the Spec.

Example

```javascript
describe('demo suite', function () {
  it('older test', function (done) { /* some code */});
  it('old test', function (done) { /* some code */});
  
  it('new test', function (done) {
    
    //should be an object, but let's assume that for some Exception/Error on function returns a null
    var person = getPerson(); 

    expect(person).not.toBeNull();
    expect(person.name).not.toBeNull(); // if person == null will not stop here and throw an exception later
    expect(person.name).toBe('john');
    
    done();
    
  });

  it('newer test', function (done) { /* some code */});

});
```

So, regardless of the other tests being marked as success or failed, it would be great If I could "stop" `new test` on first failed expectation and not by a thrown exception. It's possible to do that?

Appreciate any help you can give! 👍

**Comment by henrahmagix** [comment]
The second `expect` never fails because it never runs: `person.name` throws a `TypeError` as soon as it's run, and it's not possible to continue after that because of the javascript engine.

You could wrap the second and third `expect` in `try/catch`, one for both or one each, and manually deal with the caught errors, then fail with Jasmine's `fail()`.
```js
var erred = false;
var thing = getObjectOrNull();

expect(thing).not.toBeNull();

try {
    expect(thing.a).toBe('a');
} catch (error) {
    erred = true;
    console.error(error);
}

try {
    expect(thing.b).toBe('b');
} catch (error) {
    erred = true;
    console.error(error);
}

if (erred) {
    fail('Errors thrown');
} else {
    done();
}
```

Or, more succinctly:
```js
var erred = false;
var thing = getObjectOrNull();

expect(thing).not.toBeNull();

if (typeof thing === 'object') {
    expect(thing.a).toBe('a');
    expect(thing.b).toBe('b');
} else {
    fail('thing is not object');
}
```

As a side note, you don't need `done` for synchronous tests, so you can remove it from the spec's function arguments and the spec will end when the function ends.

**Comment by henrahmagix** [comment]
After a second read of your question, my second example would fit better: fail the assertion instead of throwing an exception if `thing` is null. Otherwise, this is related to #414.

**Comment by poliveira89** [comment]
@henrahmagix as I made my question I was expecting something more aligned with `expect`, but your solution seems to deliver the job as well.

So, thank you very much for your time (and help)! 👍

**Comment by henrahmagix** [comment]
You're welcome, glad I could help :)

**Comment by slackersoft** [comment]
@poliveira89 Unless I'm misunderstanding your question, I think you just want `stopSpecOnExpectationFailure`. The setting will affect each of the specs, but not the entire run of the suite. So: each spec that has a failed expectation will stop, but the next spec will be run.

Hope this helps. Thanks for using Jasmine!

**Comment by poliveira89** [comment]
@slackersoft Hello, for my understanding a `spec` is a single `.js` with one/several `describe`.
And when I found that property, I interpreted as it can ignore failed `spec` when several are executed at same time.

My need it's in a lower level, it's focused on the "test/assertion" (in this case `expect` function), as I said earlier, I want to have a list of `expect` but I would like to "break" the `it` on first failed `expect` occurrence.

**Comment by slackersoft** [comment]
In Jasmine terminology a spec is a single `it`, not the whole file that includes it. `stopSpecOnExpectationFailure` is definitely what you want from your description.

**Comment by alex-svyatenko** [comment]
@slackersoft
Hello! Could you please explain how to do it?
I added in protractor config file the next thing :  
exports.config = {  
  framework: 'jasmine2',
  jasmineNodeOpts: {
    stopSpecOnExpectationFailure: true
  },
  specs: [
    '../spec/test1.spec.js',
    '../spec/test2.spec.js'   
  ]
};
It doesn't work. 
If I have 3 'it' blocks in one spec file and the 2d 'it' was failed, the next one (the 3d) will be executed.
I'm searching an approach how to fail describe with many 'it' blocks, when first expectation is failed and the rest 'it' blocks will NOT be executed.
In the meantime, the rest spec file in config file should be executed.
Could you please give your recommendations? Is it possible to implement this solution using Protractor + Jasmine ? 

Many thanks in advance.
Alex.

**Comment by slackersoft** [comment]
@alex-svyatenko I think you're talking about something more like #414 not this issue. As for how to set the current setting in Protractor, you'd have to talk to the Protractor team, I don't know how those options are set or passed through to the underlying jasmine instance.

Hope this helps. Thanks for using Jasmine!

**Comment by zhong-edward** [comment]
as I know element.click() can stop case if the element not present.
but if a file flag not exist, how can stop case flow?

**Comment by nils-hoyer** [comment]
please have a look at [protractor-stop-describe-on-failure](https://www.npmjs.com/package/protractor-stop-describe-on-failure) custom reporter. It might fit your protractor setup as well. cheers
