### ISSUE TITLE
htmlReporter for node projects

### ISSUE THREAD

**Issue by nashwaan** [jasmine/jasmine#1185]
I can use jasmine-standalone to run spec in the browser and get the nice html output of the specs (only if the specs are not accessing node specific features like `process.argv` and `require('fs')`).
However, i am unable to find a way to get same nice html output if i am writing specs for a node project.
when i type this command in the console `jasmine`, i get the following output:
```
...............................................................
63 specs, 0 failures
Finished in 1.229 seconds
```
But I wonder if there is a way like writing this command `jasmine --useHtmlReporter` so that i get nice html output.
Note that I am using node specific features which means i cannot use tools like browserify to bundle the project and load in the `jasmine.html`.
It seems that `env.addReporter(htmlReporter)` requires a DOM and thus should be run in a browser like chrome or PhantomJS, right?

**Comment by Gerg** [comment]
I don't know of any existing solutions for this.

You could probably set up a HtmlReporter without a browser-side Jasmine that communicates with a web server running jasmine in node. You would also need to provide the HtmlReporter with a fake jasmine env, but thankfully the reporter doesn't use it for much.
