### ISSUE TITLE
Parent's beforeEach/afterEach apply to specs inside nested describe -- bug or by design?

### ISSUE THREAD

**Issue by 3n-mb** [jasmine/jasmine#1186]
Let's consider a nested specs structure:
```
describe {
  beforeEach {}
  afterEach {}
  it { #1 }
  describe {
    it { #2 }
    it { #3 }
  }
}
```
Right now (or, as of version 2.4.1) `beforeEach` and `afterEach` will be called three times, as if specs 2 and 3 where not nested, and at the same level as spec 1.
Nesting logic would suggest calling `beforeEach` and `afterEach` only two times, once for spec 1, and once for nested describe, as a whole.

Is current behavior accidental (bug?), or was it created intentionally.
If it is not a bug, then what is the reasoning behind such decision (it will help to find structural work-around).

**Comment by Gerg** [comment]
This behavior is correct and consistent with other BDD frameworks (RSpec, Ginkgo, Mocha). 

Whenever possible, your tests should be isolated from each other. If your `beforeEach` only ran once for the nested `it`s then changes to the test setup from spec 2 could leak into spec 3. If you intentionally want to leak state between tests, then you should use `beforeAll`.

See this thread for more info about test ordering: https://github.com/jasmine/jasmine/issues/873

Thanks for using Jasmine.
