### ISSUE TITLE
toHaveBeenCalledTimes(0) fails silently in async

### ISSUE THREAD

**Issue by jerroydmoore** [jasmine/jasmine#1187]
In Jasmine v2.4.1 (jasmine-core v2.4.1), calling `expect(obj.Save).toHaveBeenCalledTimes(0)` asynchronously hangs until jasmine.DEFAULT_TIMEOUT_INTERVAL limit is reached.

Calling the function synchronously returns the following error
> Expected times failed is required as an argument.

Either the behavior of `toHaveBeenCalledTimes(0)` should be changed to match `not.toHaveBeenCalled()` or providing 0 to `toHaveBeenCalledTimes` will have to find a way to emit an error in an asynchronous execution flow.

To reproduce:
```
describe("Multiple spies, when created manually", function () {
  var tape;

  beforeEach(function() {
    tape = jasmine.createSpyObj('tape', ['play', 'pause', 'stop', 'rewind']);

    tape.play();
    tape.pause();
    tape.rewind(0);
  });

  it("tracks that the spies were called", function(done) {
    Promise.resolve().then(function () {
        expect(tape.play).toHaveBeenCalled();
        expect(tape.pause).toHaveBeenCalled();
        expect(tape.rewind).toHaveBeenCalled();
        expect(tape.stop).toHaveBeenCalledTimes(0);
        done()
    })
  });
});
```
Output:
> Failures:
> 1) Multiple spies, when created manually tracks that the spies were called
>   Message:
>     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
>   Stack:
>     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
>         at tryOnTimeout (timers.js:228:11)
>         at Timer.listOnTimeout (timers.js:202:5)

**Comment by chrisdeely** [comment]
This issue appears to have been corrected in 2.5.0 via [commit e5c744f](https://github.com/jasmine/jasmine/commit/e5c744f3dc35a0f62e13aa66724370265c1d82ae)

**Comment by slackersoft** [comment]
Closing this, as it sounds like it has been fixed in the current release. Please let us know if you feel this is incorrect.

Thanks for using Jasmine!

**Comment by azanebrain** [comment]
You can also use `expect(...).not.toHaveBeenCalled()`
