### ISSUE TITLE
callFake() fails when passing a "special" function

### ISSUE THREAD

**Issue by IgorAufricht** [jasmine/jasmine#1191]
To reproduce:
`jasmine.createSpy('spy').and.callFake(console.log);`

This fails with the following error:
```
Error: Argument passed to callFake should be a function, got function () {
          self.log(method, arguments)
          return Function.prototype.apply.call(orig, localConsole, arguments);
        }
```

This is caused by the change in #1059. The check for a function in the change is `fn instanceof Function`. And since `console.log instanceof Function` returns `false`, this will fail.

This is quite confusing, since it indeed is a function. I would say the check should be updated. (For example [`_.isFunction()`](https://lodash.com/docs/4.15.0#isFunction) returns `true` for `console.log`.)

**Comment by chrisdeely** [comment]
Are you overwriting ```console.log``` within your code by any chance?

What browsers have you tested this in? In Chrome 52 ```console.log instanceof Function === true```

**Comment by IgorAufricht** [comment]
My apologies - this is happening in PhantomJS (1.9.8). No overwriting of `console.log()` as far as I can tell.
