### ISSUE TITLE
When mixing Angular's $q and ES6's Promise, some of the promises don't get resolved.

### ISSUE THREAD

**Issue by yukw777** [jasmine/jasmine#1200]
I was trying to test my code that uses Restangular (which uses $q) and Sweetalert2 (which uses Promise). Basically, I open an alert box; this in turn returns a Promise, which gets resolved when the user clicks the confirm button; then I make a Restangular call which produces a $q promise. While it worked just fine on my browser, the promise produced by $q never got resolved in Jasmine. 

So I googled around and found this issue: http://stackoverflow.com/questions/33965435/testing-angular-when-mixing-q-and-es6-promises

It has simple code to reproduce the issue I described above. I'm currently using the workaround suggested by the OP to get around this issue, but I believe there should be a fix for this issue.

**Comment by Gerg** [comment]
Jasmine does not know anything about the content of the code you are testing and will not affect promise resolution. My guess is this issue is being caused by angular-mocks (or similar).
