### ISSUE TITLE
Array containing an object broken after update.

### ISSUE THREAD

**Issue by hakunin** [jasmine/jasmine#1201]
This check used to pass:

    expect(array).toContain(value)

Array:

    [
      {"_t":"user","id":1073970419,"email":"email3@example.org","name":"Spectator"},
      {"_t":"user","id":4464992042,"email":"email4@example.org","name":"Collaborator"},
      {"_t":"user","id":1978569710,"email":"email5@example.org","name":"Manage"}
    ]

Value:

    {"_t":"user","id":1978569710,"email":"email5@example.org","name":"Manage"}

But no longer passes. Whats the new way to write the same test?

StackOverflow question:
http://stackoverflow.com/questions/39411424/jasmine-how-to-check-that-array-contains-an-object

**Comment by Gerg** [comment]
Can you try upgrading to 2.5.1? This test passes for me: 

```js
describe("A suite", function() {
    it("contains spec with an expectation", function() {
        var array = [
          {"_t":"user","id":1073970419,"email":"email3@example.org","name":"Spectator"},
          {"_t":"user","id":4464992042,"email":"email4@example.org","name":"Collaborator"},
          {"_t":"user","id":1978569710,"email":"email5@example.org","name":"Manage"}
        ]
        expect(array).toContain({"_t":"user","id":1978569710,"email":"email5@example.org","name":"Manage"});
    });
});
```

**Comment by Gerg** [comment]
Closing for now, please re-open if you are still having issues.

Thanks for using Jasmine!

**Comment by hakunin** [comment]
You're right Gerg, somehow Jest is using a different version of Jasmine that I have installed manually.
