### ISSUE TITLE
Missing documentation for .toThrow('foo')

### ISSUE THREAD

**Issue by Xantix** [jasmine/jasmine#1207]
The [jasmine documentation](http://jasmine.github.io/2.5/introduction.html) for 'toThrow()' fails to mention the following useful feature.

```
  it("The 'toThrow' matcher can also test for specific strings being thrown", function() {
    var foo = function() {
      throw 'foo';
    };

    expect(foo).toThrow('foo');
    expect(foo).not.toThrow('bar');
  });
```

This is different than ".toThrowError" (which expects a "new Error" object to be thrown).

(Only by stepping through the source code did I discover this undocumented feature).

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.
