### ISSUE TITLE
configureDefaultReporter to noop will no longer remove the default reporter

### ISSUE THREAD

**Issue by freed00m** [jasmine/jasmine#1216]
I noticed when I upgrade from version 2.5.1 -> 2.5.2 I am no longer able to supres the console logger with 

```
    let Jasmine = require('jasmine')
    let myReporter = require('./spec/helpers/customReporter')
    let noop = function() {}
    let jrunner = new Jasmine()

    jrunner.configureDefaultReporter({
        print: noop
    }) // remove default reporter logs
```

running jasmine via node $ node launcher.js

It's OS independent, on both windows and linux

**Comment by Gerg** [comment]
This appears to be the same issue as #1228. Please continue any discussion there.

Thanks for using Jasmine!
