### ISSUE TITLE
Show difference in equality failure of objects

### ISSUE THREAD

**Issue by aaronbeall** [jasmine/jasmine#1217]
If two objects are compared using `expect.toEqual` and there is a difference, we only get a dump of the entire object, which makes it nearly impossible to tell what the difference actually is.

Many other libraries print the actual difference. Can jasmine do the same?

**Comment by Gerg** [comment]
There is currently an open PR for this feature: https://github.com/jasmine/jasmine/pull/1163. Please continue any discussion there.

Thanks for using Jasmine!
