### ISSUE TITLE
Testing a style properties on element hover

### ISSUE THREAD

**Issue by gasperthegracner** [jasmine/jasmine#1218]
we have a problem with testing styles when element is hovered.  Event for "mousover" is executed but change of background color is not detected, but it works in browser. 

We are using Jasmine version 2.5.2, Karma version 1.2.0 and Angular 2.

Example of a test:
``` 
it('Primary Button shoud have proper css color on hover', fakeAsync(() => {
    let testComponent = fixture.debugElement;
    de = fixture.debugElement.query(By.css('button.a-button.u-is-large'));
    el = de.nativeElement;
    let styles = window.getComputedStyle(el);


    el.addEventListener('mouseover', (a) => {
      tick();
      fixture.detectChanges();

      console.log(styles.backgroundColor);
      expect(de).not.toBeNull();
      expect(styles.backgroundColor).toBe('rgb(0, 138, 203)');

    });

    console.log(styles.backgroundColor);
    let event = new Event('mouseover');
    el.dispatchEvent(event);
  }));
``` 

HTML:
`
<button type="button" class="a-button u-is-large u-is-primary">Primary Button</button>
`

If anyone has idea how to solve this, we would really appreciate it.
Thanks

**Comment by Gerg** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using Jasmine!

**Comment by Sumanth447** [comment]
Do you have a solution for that yet?
I encountered the same thing in one of my test case. 
It would be really helpful if you can update the solution.

**Comment by szymexpawlowski** [comment]
this could help https://codecraft.tv/courses/angular/unit-testing/directives/
