### ISSUE TITLE
deepEqual module outdated

### ISSUE THREAD

**Issue by crazyhuggins** [jasmine/jasmine#1219]
I noticed that current deepEqual implementation lacks a lot of features? It is a "copy" of underscore.
Lodash supports more features now, but I also found this one: https://github.com/zubuzon/kewlr. Seems to support both browser and node.

Is this going to be fixed?

**Comment by Gerg** [comment]
What features are you looking for that are missing? You can also define [custom equality testers](http://jasmine.github.io/2.5/custom_equality.html) in the mean time to support your use cases.

**Comment by slackersoft** [comment]
We haven't heard any more specific feedback on this, so I'm going to close this issue. If there are particular features that you would like to see in Jasmine's equality functionality, we would be happy to review any specific issues or pull requests. Simply saying that it is old doesn't allow us to fix this.

Thanks for using Jasmine!
