### ISSUE TITLE
HI  i am using jasmin 0.9.b3  version  but unfortunately  new version 0.9.b11 is updated  in repository due to new version  we are unable to update dlr reports to particular  messageId.  so, plz help us ,Thanks in Advance .     

### ISSUE THREAD

**Issue by anushakl** [jasmine/jasmine#1223]
### Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine (Jasmine npm, karma, etc),
  consider filing an issue with that library if appropriate

### When submitting an issue, please answer the following:

 - What version are you using?
 - What environment are you running Jasmine in (node, browser, etc)?
 - How are you running Jasmine (standalone, npm, karma, etc)?
 - If possible, include an example spec that demonstrates your issue.

 Thanks for using Jasmine!

**Comment by slackersoft** [comment]
The version numbers you mention are not version numbers for any of the Jasmine libraries that I know of. Are you sure this is the correct Jasmine project? `dlr` and `messageid` are also not concepts in Jasmine. 

Closing. Hope you find the correct library!
