### ISSUE TITLE
Share `this` on beforeAll/afterAll

### ISSUE THREAD

**Issue by aug-riedinger** [jasmine/jasmine#1226]
- Version: 2.4
- Environment: browser
- Runner: karma

I like that the `this` object gets shared between each `beforeEach` run.

But how come this isn't shared with `beforeAll`/`afterAll` calls?

There may be an obvious reason to this (apologies for this then), unfortunately I can't see it. Searching around hasn't given me any result either.

Thanks

**Comment by amavisca** [comment]
The this object is about sharing a clean object between a single it and all of the beforeEach and afterEachs that are run for it. The all functions aren't run directly connected to an it.

**Comment by amavisca** [comment]
In general I find the entire "this" pattern to be a wonderful deterrent against test pollution.

**Comment by aug-riedinger** [comment]
What's the best practice in my case: in need to initialize a player before starting my test series.

I find the hoisting strategy ugly: 

```
describe('test player', function(){
  var player;
  beforeAll(function(done){
    player = new Player(params, done);
  });

  it('should be accessible', function(done) {
    expect(!!player).toBe(true);
  });
});
```

**Comment by amavisca** [comment]
Hoisting would be my personal recommendation if you feel you must use a beforeAll. Without knowing more about your test suite - if I put on my strongly opinionated hat I'd recommend avoiding sharing state between "it"s as much as possible to avoid test pollution.

Others may have recommendations on the jasmine mailing list (we try to keep discussions on usage out of the github issue tracker).

https://groups.google.com/forum/m/#!forum/jasmine-js
