### ISSUE TITLE
Wrapping jasmine in node-fiber

### ISSUE THREAD

**Issue by JoeyAndres** [jasmine/jasmine#1227]
So I have the following to bootstrap my jasmine:

```javascript
import Jasmine from 'jasmine';
import Fiber from 'fibers';
import log from 'loglevel';

// Set log level to "error" so anything lower won't be printed.
log.setDefaultLevel("error");

function main() {
    var jasmine = new Jasmine();
    jasmine.loadConfigFile('spec/support/jasmine.json');
    jasmine.execute();
}

// Here we run the main executable.
// This makes javascript synchronous instead of the asynchronous.
Fiber(main).run();
```

As you can see, I wrapped it in `Fiber`.

For a short while, no problem. It was testing my "Fiberized" modules well. This is until I added a trivial unit test, just accessor test. The accessor test is not failing, but those "Fiberized" modules (passing before) are now failing.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.


Closing. Thanks for using Jasmine!
