### ISSUE TITLE
Can't use numeric assertions passing through protractor

### ISSUE THREAD

**Issue by martinsson** [jasmine/jasmine#1229]
I'm trying to use toBeGreaterThan and co in my protractor assertions. 

```
        initialWidth = $(selectedPanel.width).getAttribute('value')
        .... resize the panel ....
        resizedWidth = $(selectedPanel.width).getAttribute('value')
        expect(resizedWidth).toBeGreaterThan(initialWidth)
```

To my understanding this makes a string comparison, not a number comparison. In fact protractor will resolve the promises (resolving with text) before calling the jasmine matcher. 

I guess this could be solved either in the protractor call, but it could also be solved by casting to a number in jasmine. ie

```
  compare: function(actual, expected) {
    return {
      pass: **+**actual > **+**expected
    };
  }
```

This seems like the most sensible of the two solutions, but what do you think?

using jasmine 2.4, protractor 3.3.0

**Comment by Gerg** [comment]
I think it makes more sense for the test writer to cast the values themselves. We would like to limit how much Jasmine matchers manipulate their arguments so things are less surprising.

Thanks for using Jasmine!
