### ISSUE TITLE
executing Jasmine twice creates exception via undefined spies property on undefined 

### ISSUE THREAD

**Issue by mgwhitfield** [jasmine/jasmine#1237]
I'm using Jasmine to generate a boolean of pass/fail.  This is on **2.5.2**

To do this, I'm running jasmine.execute([files]) and relying on jasmine.completionReporter.onComplete.

Running jasmine.execute a second time produces an exception on line 803 of jasmine.js in jasmine-core.  Seems the currentRunable().id is undefined in runnableResources.

```
    var spyRegistry = new j$.SpyRegistry({currentSpies: function() {
      if(!currentRunnable()) {
        throw new Error('Spies must be created in a before function or a spec');
      }
      return runnableResources[currentRunnable().id].spies; // exception,runnableResources = [];
    }});
```

**Comment by mgwhitfield** [comment]
This is helped by initializing a new Jasmine object.   This fixes the bug, however it's unclear that execute  is a one-time operation for a Jasmine object and it's worth considering cleaning up the suite or clarifying that  the Jasmine object is a one-time object or adding an additional function to run multiple times.

**Comment by slackersoft** [comment]
We have generally tried not to do anything to _explicitly_ break potentially running the specs in an `Env` more than once, but it isn't really supported functionality. That said, it might be time to have the `Env` track whether it has executed already and throw an error if `execute` is called more than once on the same object.

Hope this helps. Thanks for using Jasmine!

**Comment by mgwhitfield** [comment]
Please notify  if there is intent to shift any objects over to singleton objects, as this  would  break my code(!) and this use case I've stated is helpful for testing before continuous integration.

Thanks in advance :)
