### ISSUE TITLE
Feature request: done() in describe

### ISSUE THREAD

**Issue by aijanai** [jasmine/jasmine#1243]
Using:

-Jasmine 2.5
-Node 6.6
-with Protractor

Background:
I'm generating a list of string URIs from a page, through a promise running in beforeEach.
I'd like to loop through that list and on each URI, which I'd like to place each in its own describe with the URI string as title, execute a number of tests, which preferably should live each in its own it().

My code looks like this:

`describe('Pages', () => {

    var pages

    beforeAll((done) => {

      // open page
      browser.get(someurl)

      // get links
      element.all(by.css(someselector)).then(rows => {
        get_list_of_url_objects_from_elements(rows).then( resolved_links=> {
          pages = resolved_links
          done()
        })
      })
    })

       pages.forEach( page => {
      describe(page.name+' should have no 404',() => {
        beforeAll(() => {
          browser.get(page.href)
        })

        it('on images', () => {
          common.check404_images()
        })

        it('on stylesheets', () => {
          common.check404_stylesheets()
        })
          
        it('on scripts', () => {
          common.check404_scripts()
        })
      })
    })

})
`

Problem:
pages is always in undefined, because that part of the code is executed while the first beforeAll runs.

Possible solution:
I could just wrap the forEach loop within a describe(done), so that it waits for pages to have a value.

Requested feature:
I'd need describe to allow done() function, so that I can do async tests with better separation of sub-specs.

In the meantime, I managed to stash the each loop in a single big it() and execute all tests on all URIs together, but it's not pleasant and I really would like to display separate sections for each sub-spec.

Thanks for the attention

**Comment by slackersoft** [comment]
Adding specs after the suite has started execution is not something we're looking to add to Jasmine. If you want to generate specs in your javascript, I would recommend writing a [custom boot](https://jasmine.github.io/2.5/custom_boot.html) that waits until you have defined all of your specs before calling `execute` on the Jasmine `Env`.

Closing this. Thanks for using Jasmine!
