### ISSUE TITLE
EADDRINUSE connect EADDRINUSE 127.0.0.1:<port number> error seen when executing protractor scripts

### ISSUE THREAD

**Issue by eymemathew** [jasmine/jasmine#1251]
Node version - 4.4.2
Jasmine version - 2.4.1
Protractor version - 3.1.1
OS - Windows Server 2012 R2, 64-bit

When we try to run our protractor tests that use Jasmine, we see an error - EADDRINUSE being thrown after a couple of it blocks are executed. This same test works fine on our laptops (Win7 64bit). Can you advise on why this error is thrown?

The error thrown: EADDRINUSE connect EADDRINUSE 127.0.0.1:

It throws a random port number each time and we have verified that this port is not being used by any other processes at that time.

**Comment by slackersoft** [comment]
This sounds like it is probably an issue with protractor and not Jasmine itself. The only part I. Jasmine that would try to listen on a port wouldn't be in the core repo (something like Jasmine-gem or Jasmine-py). To my knowledge, protractor depends directly on the Jasmine-Core package which has no concept of ports. 

Closing. Hope this helps. Thanks for using Jasmine!
