### ISSUE TITLE
toThrowError with <iframe> reports incorrectly

### ISSUE THREAD

**Issue by anseki** [jasmine/jasmine#1252]
- jasmine-standalone-2.5.2 in browser

Hi, thank you for the great framework.

When an app that runs in `<iframe>` is tested, `toThrowError` reports incorrectly. It says "Expected function to throw an Error, but it threw...".
Jasmine uses `Error` constructor in current window, but it was made by `Error` constructor in child window.

In this code:
https://github.com/jasmine/jasmine/blob/8624a52ee0b6f13b3b608ea6417ccc02257c5412/src/core/matchers/toThrowError.js#L31

```js
if (!(thrown instanceof Error)) {
```

It checks with the `Error` in current window always. But the `thrown` was made in different `global` (namespace).

For example:

- `app.html`

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  <script>

    function methodA() {
      return 'foo';
    }

    function methodB() {
      throw new Error('bar');
    }

  </script>

</head>

<body>
  app.html
</body>
</html>
```

- Spec

```js
describe('App running in <iframe>', function() {

  function methodC() {
    throw new Error('baz');
  }

  var childWindow;

  beforeAll(function(done) {
    // Prepare <iframe>
    var iframe = document.body.insertBefore(document.createElement('iframe'), document.body.firstChild)
    iframe.addEventListener('load', function() {
      childWindow = iframe.contentWindow;
      // self.Error = childWindow.Error;
      done();
    });
    iframe.src = 'app.html';
  });

  it('should return foo', function() {
    expect(childWindow.methodA()).toBe('foo');
  });

  it('should throw an error', function() {
    expect(function() {
      childWindow.methodB();
    }).toThrowError('bar');
  });

  it('(test in current window)', function() {
    expect(function() {
      methodC();
    }).toThrowError('baz');
  });
});
```

The second spec fails.

I think, this line:

```js
if (!(thrown instanceof Error)) {
```

should be:

```js
if (!(thrown instanceof (thrown.constructor.constructor('return this')()).Error)) {
```

This gets `Error` from the same `global` as `thrown`.

**Comment by slackersoft** [comment]
We would be happy to review a pull request that allows `toThrowError` to correctly detect `Error`s that come from different frames correctly.

**Comment by anseki** [comment]
@slackersoft,
Ok, I will send a PR later.
