### ISSUE TITLE
expect(null).toEqual(jasmine.any(Object)) passes

### ISSUE THREAD

**Issue by lmj0011** [jasmine/jasmine#1255]
**version**
jasmine v2.5.3
jasmine-core v2.5.2

**environment**
node v6.9.4
npm v3.10.10

**running Jasmine**
from cli using the `jasmine` command to run my tests

I'm expecting this to fail, but it doesn't.
How does `null` equal an Object?

`expect(null).toEqual(jasmine.any(Object));`

**Comment by JamieMason** [comment]
I think these lines in [/src/core/asymmetric_equality/Any.js:26-28](https://github.com/jasmine/jasmine/blob/8624a52ee0b6f13b3b608ea6417ccc02257c5412/src/core/asymmetric_equality/Any.js#L26-L28) could be the problem and the following snippet should be enough to fix it AFAICT.

```javascript
    if (this.expectedObject == Object) {
      return Object.prototype.toString.call({}) == '[object Object]';
    }
```

**Comment by lmj0011** [comment]
@JamieMason 

I suppose in this context using `==` or `===` doesn't matter.
other than that, it looks legit.

you wanted to make the PR for this?

**Comment by JamieMason** [comment]
> I suppose in this context using == or === doesn't matter.

Yeah I'd normally use `===` but I notice the rest of that file is using `==`.

> you wanted to make the PR for this?

I don't mind yeah, I'll try and fit it in today 👍

**Comment by slackersoft** [comment]
I'm not sure if we can change this behavior for `any` right now, since that has a potential to break existing suites. That said, I think for 3.0 (when we can break things :), we'll want to look at the provided asymmetric matchers to ensure we are providing the right options out of the box.
