### ISSUE TITLE
Maps comparison always passes

### ISSUE THREAD

**Issue by downace** [jasmine/jasmine#1257]
This code passes successfully:
```javascript
const a = new Map();
const b = new Map();
a.set('name', 10);
b.set('id', 9);

expect(a).toEqual(b);
```

`URLSearchParams` objects comparison also always passes because of using `Map` internally

Tested on Jasmine 2.4.1 and 2.5.2. Using Karma test runner (version 1.3.0), Chrome 55.0.2883.

**Comment by derekdowling** [comment]
Hey guys! Would love for this to get fixed. Using Maps is much more prevalent in TypeScript and this is causing silent failures for us.

**Comment by slackersoft** [comment]
We would be happy to review a pull request that compares maps correctly in all browsers that support them.

**Comment by mjeanroy** [comment]
@slackersoft If maps are supported in `toEqual` matcher, it could be great to also support `Set`.

I had the same problem, and until it is included in jasmine, you can solve this with a custom equality tester. Here is a simple example:

```javascript
beforeEach(() => {
  jasmine.addCustomEqualityTester((first, second) => {
    if (supportMap() && isMap(first) && isMap(second)) {
      if (first.size !== second.size) {
        return false;
      }

      let areEquals = true;
      first.forEach((value, key) => {
        if (!second.has(key) || jasmine.matchersUtil.equals(value, second.get(key)) {
          areEquals = false;
        }
      });

      return equals;
    }
  });
});
```

It's not perfect, and methods `supportMap` and `isMap` needs to be implemented but you got the main idea.

There's one downside: the map equality tester does not works if the map contains values that need to be tested against an other custom equality testers. I don't see an easy way to access all the equality testers when calling `jasmine.matchersUtil.equals`, but maybe I'm missing something.

**Comment by slackersoft** [comment]
I believe `Set` should be supported for equality in Jasmine from #1067. This functionality just hasn't been released yet.

**Comment by rmehlinger** [comment]
Because ES6 Maps and Sets preserve order, it would seem that a simple array comparison would be sufficient. As a workaround until such a thing can be included:
```expect(Array.from(new Map([[1, 'a'], [2, 'b']]).toEqual([[1, 'a'], [2, 'b']])```

**Comment by rmehlinger** [comment]
Pull request implementing Map support: https://github.com/jasmine/jasmine/pull/1340
