### ISSUE TITLE
TypeError: null is not an object

### ISSUE THREAD

**Issue by dinee4321** [jasmine/jasmine#1258]
Below is the error log that I have received with running the gulp test

bower_components/angular/angular.js:4631:53
18-Jan-2017 16:45:09	forEach@bower_components/angular/angular.js:322:24
18-Jan-2017 16:45:09	loadModules@bower_components/angular/angular.js:4591:12
18-Jan-2017 16:45:09	createInjector@bower_components/angular/angular.js:4513:30
18-Jan-2017 16:45:09	workFn@bower_components/angular-mocks/angular-mocks.js:3060:60
18-Jan-2017 16:45:09	     TypeError: null is not an object (evaluating 'obj[methodName]') in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 1991)

### When submitting an issue, please answer the following:

 - What version are you using?  "jasmine-core": "2.4.1"
 - What environment are you running Jasmine in (node, browser, etc)?  node
 - How are you running Jasmine (standalone, npm, karma, etc)?  karma
 - If possible, include an example spec that demonstrates your issue.
   
       it 'should go() to `login` state', ->
        spyOn $state, 'go'

        $security.notAuthenticated 'bar',
          foo: 'bar'

        expect $state.go
          .toHaveBeenCalledWith 'login',
            data: Base64.encode '{"to":"bar","toParams":{"foo":"bar"}}'

 Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Based on the Jasmine code at that point, it looks like the objecting you are attempting to add a spy to is `null`. Probably `$state` for you. We have code to check for `undefined` but apparently not `null` for both params.

I think Jasmine can provide a better message in this case, but it sounds like you'll need to look into how to get the right `$state` object from angular and/or angular-mocks to truly fix this.
