### ISSUE TITLE
jasmine_tags extension

### ISSUE THREAD

**Issue by tf** [jasmine/jasmine#126]
Hello,

just wanted to let you know that I wrote a little extension which lets you annotate jasmine spec with tags. You can then choose to run only specs with certain tags or exclude (for example slow) specs from run.

If you are interested, take a look at [tf/jasmine_tags](https://github.com/tf/jasmine_tags).

Best,
Tim

**Comment by danielsiwiec** [comment]
@ragaskar Hi, is there still any desire to bring this kind of functionality into jasmine? Would love to see cucumber style tags. I'd be happy to work on a PR if there's agreement on it.

**Comment by ragaskar** [comment]
@slackersoft is probably the person to ask about this; I haven't been doing much maintenance of Jasmine lately. 

FWIW, we've been trying to keep the core simple as it makes it easier to maintain, and in service of this have done a lot of work to allow people to extend jasmine without having to get changes/new features in core. I expect if this is possible to achieve *without* modifying core, we'd be unlikely to pull it in.
