### ISSUE TITLE
Firefox load spec two times

### ISSUE THREAD

**Issue by jcubic** [jasmine/jasmine#1261]
I'm running jasmine from browser it work fine from Chromium but in FireFox it load my spec twice I have only one `<script>` tag in html file and if I remove it, it don't load my tests at all. To fix it I needed to add code that check for global variable if it set to true it don't load tests.

If can check it here http://terminal.jcubic.pl/SpecRunner.html look at firefox console (there are two requests for spec/terminalSpec.js

**Comment by slackersoft** [comment]
Based on what I see in the console, it looks like you have some sort of AJAX request that is loading various things in multiple times. In Firefox, it's getting your spec file, but Chrome looks like it's getting the favicon multiple times.

Jasmine itself doesn't even really know about the browser so it won't be making any additional requests or writing `<script>` tags into the page, so it looks like it is probably something outside of Jasmine. Possibly in your specs, or the code under test, or even a dependency that is loaded.

Closing this. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
You are also more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
