### ISSUE TITLE
TypeError: jasmine.configureDefaultReporter is not a function

### ISSUE THREAD

**Issue by agirorn** [jasmine/jasmine#1266]
When trying to configure the default reporter as described in the [documentation](https://jasmine.github.io/2.5/node.html#section-Reporters). Then I get the following error.

```shell
npm test

> trying-to-configure-jasmine-default-reporter@0.0.0 test /home/agirorn/tmp/trying-to-configure-jasmine-default-reporter
> jasmine first.spec.js

/home/agirorn/tmp/trying-to-configure-jasmine-default-reporter/first.spec.js:1
(function (exports, require, module, __filename, __dirname) { jasmine.configureDefaultReporter({
                                                                      ^

TypeError: jasmine.configureDefaultReporter is not a function
    at Object.<anonymous> (/home/agirorn/tmp/trying-to-configure-jasmine-default-reporter/first.spec.js:1:71)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/agirorn/tmp/trying-to-configure-jasmine-default-reporter/node_modules/jasmine/lib/jasmine.js:87:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/home/agirorn/tmp/trying-to-configure-jasmine-default-reporter/node_modules/jasmine/lib/jasmine.js:86:18)
npm ERR! Test failed.  See above for more details.
```

This can be reproduced from this gist: https://gist.github.com/agirorn/2d58eb1c08cbd4837830c3e3cbfa9503

I guess this is either a bug in the documentation of jasmine.

**Comment by slackersoft** [comment]
What is `jasmine` in the line where the error occurs?

The `configureDefaultReporter` option isn't intended to be called inside a spec file, since that's possibly too late, and you don't have any hooks to the `jasmine` object created by the executable. In normal use, I wouldn't expect you to need to configure the default reporter when just using the `jasmine` executable, it is really there so you can do some more configuration.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything back on this issue, so I'm going to close it. If you're still having issues, we'd be happy to look into them further with a bit more information.

Thanks for using Jasmine!
