### ISSUE TITLE
Jasmine .spec.js files outside the spec directory

### ISSUE THREAD

**Issue by sgen** [jasmine/jasmine#1267]
Is it possible to have my .spec.js files outside of the spec directory?

I.E.

```
/src/thing.model.js
/src/thing.model.spec.js
```
instead of
````
/src/thing.model.js
/spec/thing.model.spec.js
```

**Comment by piniu** [comment]
of course.  provide jasmine the correct path and it will work. i have it in different location. you can also set 
"spec_dir": "/tests/jasmine" so 
"spec_files": ["test1", "test2"]

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!

**Comment by RogertG** [comment]
Tested some JS on [Jasmine Directory](https://www.jasminedirectory.com/). It worked for me. 

@sgen if you need any help drop me a line.
