### ISSUE TITLE
trigger jasmine from controller

### ISSUE THREAD

**Issue by piniu** [jasmine/jasmine#1271]
I'm trying to trigger jasmine tests from my controller using jasmine-reporter.
the issue is when it finish (btw it finish correctly) the node process exit.
How can i prevent *jasmine.execute()*  to take the node server down?
i think this repository is more relevant then **jasmine-reporters** simply because i'm loading the _reporter_ into jasmine - but maybe I'm wrong.

```
var Jasmine = require('jasmine'),
    reporters = require('jasmine-reporters');
runQaTests: function (req, res, next) {
        var jasmine = new Jasmine();
        var junitReporter = new reporters.JUnitXmlReporter({
            savePath: __dirname+'/../tests/jasmine',
            consolidateAll: true
        });

        jasmine.loadConfigFile("./spec/support/jasmine.json");
        jasmine.addReporter(junitReporter);
        jasmine.execute();
        return res.json('trigger qa tests');
    } 
```

**Comment by piniu** [comment]
OK after debugging found the way to do it. simply override onComplete
```
jasmine.onComplete(function (passed) {
                if (passed) {
                    console.log('All specs have passed');
                }
                else {
                    console.log('At least one spec has failed');
                }
            });
```

**Comment by slackersoft** [comment]
This is the supported way to specify your own behavior when the suite completes.

Closing this. Thanks for using Jasmine!
