### ISSUE TITLE
How to pass parameters to beforeEach / afterEach?

### ISSUE THREAD

**Issue by tomkur** [jasmine/jasmine#1274]
Is there a way to parameterize beforeEach / afterEach calls?
It is a common scenario for me to have multiple tests share same initialization code with some minor difference, e.g.:
```js
it('test default', () => {
  this.myObj = createObj('default');
  // perform some test on myObj
});
it('other test for default', () => {
  this.myObj = createObj('default');
  // perform some other test on myObj
});
it('test foo', () => {
  this.myObj = createObj('foo');
  // perform some test on myObj
});
```
Is there a way to extract common logic to beforeEach and express parameters in test declaration? Something like that can be achieved in at least one framework I'm aware of (Java+TestNG). Here it could be something like:
```js
beforeEach((name = 'default') => {
  this.myObj = createObj(name);
});
it('test default', () => {
  // perform some test on myObj
});
it('other test for default', () => {
  // perform some other test on myObj
});
it('test foo', 'foo', () => {
  // perform some test on myObj
});
```

**Comment by slackersoft** [comment]
The function passed to `beforeEach` won't be passed any parameters from Jasmine when it is invoked, and we don't have any plans to add that ability. If you have test setup that is mostly the same, I would suggest making a function that you can call with your arguments, like it looks like you have with `createObj`.

I'm going to close this since this isn't really a feature we're looking to have in Jasmine. Thanks for using Jasmine!

**Comment by tomkur** [comment]
I see, thanks for answering.
What I was trying to achieve is not to have to explicitly call initialization code everywhere just because there's this single test which is initialized differently.

**Comment by codyherzog** [comment]
I've used something like this:

```
describe('outer', () => {
  function init (options) {
    // Common init behavior here...

    if (options.opt1) {
      // Different behavior depending on options.
    } else {
      // Different behavior depending on options.
    }

    if (options.opt2) {
      // Different behavior depending on options.
    } else {
      // Different behavior depending on options.
    }
  };
  describe('inner 1', () => {
    beforeEach(() => {
      init({ opt1: true, opt2: false });
    });
    it('test 1', () => {
      // Test content here.
    });
    it('test 2', () => {
      // Test content here.
    });
  });
  describe('inner 2', () => {
    beforeEach(() => {
      init({ opt1: false, opt2: true });
    });
    it('test 1', () => {
      // Test content here.
    });
    it('test 2', () => {
      // Test content here.
    });
  });
});
```

**Comment by robbiemu** [comment]
this is a lackluster answer and should be revised. Not wanting to change something because _opinion_ is totally fine! But then not sharing the architectural insight that lead to that opinion is obfuscation.

**Comment by sanyooh** [comment]
I found a way to parameterize it inside one testing scope. Just create a variable and set it to a default value. The only ugly thing is that you need to change it to the new value before the test case starts.

```
describe('test case 1', () => {

  let name = 'default';

  beforeEach(() => {
    this.myObj = createObj(name);
    console.log(name);
  });
  it('test default', () => {
    // perform some test on myObj
  });
  it('other test for default', () => {
    // perform some other test on myObj
    name = 'foo';
  });
  it('test foo', () => {
    // perform some test on myObj
  });
});
```
