### ISSUE TITLE
i18n of Jasmine API

### ISSUE THREAD

**Issue by RomkeVdMeulen** [jasmine/jasmine#1276]
We're writing Dutch descriptions in our specs, and using Dutch names in our code. This makes it feel it bit 'off' that the functions `describe` and `it` are in English. To work around this, we've added some aliases to our test config:

```
var beschrijf = describe;
var het = it;
```

Now our specs read like a story in Dutch:

```
// ...

beschrijf("Mijn Component", () => {

	het("opent een modal", () => {
		comp.klikOpModalLink();
		expect(comp.isModalOpen()).toBe(true);
	});

	het("valideert de invoer", () => {
		comp.vulIn("");
		expect(comp.getFoutmelding()).toBe("Verplicht");
	});

	// etc..
});
```

Notice that we didn't translate `expect` or `toBe`: we would have loved to have done so, but it was simply too much work.

Things got a little more complicated when we put our tests in TypeScript and had to declare our aliases:

```ts
declare function beschrijf(description: string, specDefinitions: () => void): void;
declare function het(expectation: string, assertion?: (done: DoneFn) => void, timeout?: number): void;
```

I was wondering whether it might be an interesting feature for the Jasmine framework itself to support i18n of its API, so that this scenario is supported out of the box.

**Comment by slackersoft** [comment]
The globally scoped functions should be reasonably easy to rename in a [custom boot](https://jasmine.github.io/2.5/custom_boot.html). Unfortunately, matchers, spy mechanics, and things will be a bit trickier.

I don't think full i18n of the public interface for Jasmine is something we're looking for at this time. Hopefully the custom boot and aliasing everything in the jasmineInterface will get you close to where you want to be. Thanks for using Jasmine. Closing.
