### ISSUE TITLE
Expect message 

### ISSUE THREAD

**Issue by roopkt** [jasmine/jasmine#1277]
JASMINE 2.4.1
expect(someValue).toBe(otherValue);
It does not show the detail message.

Currently, it just says expected false to be true and it spits out bunch of file references like below:

buildExpectationResult@file:/// ..., expectationResultFactory@file:... , addExpectationResult@file:///C:/Users/, addExpectationResult@file://... in ..file (line 52)
I think it should just show that test case failed message and why it failed. I am not sure why it is showing other 3 files names and its locaitons ?

**Comment by slackersoft** [comment]
What is "The detail message" that you are expecting to see? You say that it _does_ report `expected false to be true` which sounds like the error message. The stacktrace lines are from Jasmine trying to tell you where in your code the expectation is that is failing. Right now this is a full stacktrace, but we would like to remove the Jasmine specific lines at some point (see #801).

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else about what the issue you are reporting really is, so I'm going to close it. If you're still having issues, we'd be happy to look into them with a bit more information.

Thanks for using Jasmine!
