### ISSUE TITLE
.toThrow() matcher with context argument

### ISSUE THREAD

**Issue by iFarmGolems** [jasmine/jasmine#1278]
Hey, I'd like to know if it is possible to add some context into .toThrow() matcher, just like the second argument in .toBe() or simmilar matcher:  

`
expect(1).toBe(2, 'Reason-why-test-failed')
`

I don't want to specify what kind of error am I getting, just that I got some error.

Thanks.

**Comment by slackersoft** [comment]
The second argument showing up in the failure message for some of the matchers is unintentional functionality, based on how a default failure message is generated if the matcher doesn't specify one. We're not necessarily looking to break this for the matchers it currently works for, but nor are we looking to provide this functionality intentionally.

I'm not totally clear on what information the matcher isn't providing to you that you want. You may also want to look at the `toThrowError` matcher which will check that the thrown thing is actually an `Error`.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue, so I'm going to close it. Thanks for using Jasmine!
