### ISSUE TITLE
Some URLs from the documentation are invalid

### ISSUE THREAD

**Issue by tkrotoff** [jasmine/jasmine#1279]
Example:
https://jasmine.github.io/2.5/introduction#section-Spies:_<code>and.callFake</code>

Characters < and > are not valid and should be escaped.

See [What characters are valid in a URL?](http://stackoverflow.com/questions/7109143/what-characters-are-valid-in-a-url)

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

I would be happy to review a pull request there that either fixes the html/link generation that we're using to make the pages from the annotated source, or updates the headers to no longer include markdown that will generate bad html.

**Comment by slackersoft** [comment]
I think the newer version of the docs has largely fixed this issue and we haven't seen any further discussion here, so I'm going to close this.
