### ISSUE TITLE
  Error: (SystemJS) Can't find variable: jasmineRequire

### ISSUE THREAD

**Issue by ahelord** [jasmine/jasmine#1280]
### Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine (Jasmine npm, karma, etc),
  consider filing an issue with that library if appropriate

### When submitting an issue, please answer the following:

 - What version are you using? 3.10.3
 - What environment are you running Jasmine in (node, browser, etc)? node
 - How are you running Jasmine (standalone, npm, karma, etc)? karma
 - If possible, include an example spec that demonstrates your issue.
`describe('Work Karma Jasmine FrameWork', function () {
    it('true is true', function () {
        expect('Hello World for Karma and Jasmine FrameWork').toBe('Hello World for Karma and Jasmine FrameWork');
    });
});
//# sourceMappingURL=work-karma-jasmine.spec.js.map`

When I try to run the tests with karma get 

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: (SystemJS) Can't find variable: jasmineRequire

  	eval code
  	eval@[native code]
  	F@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:12217
  	H@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:11846
  	when@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:15520
  	run@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:14559
  	_drain@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:3250
  	drain@http://localhost:9878node_modules/systemjs/dist/system-polyfills.js:4:1667
  	Evaluating http://localhost:9878node_modules/karma-jasmine/lib/boot.js
  	Error loading http://localhost:9878node_modules/karma-jasmine/lib/boot.js

i try include directorios of lib in file config karma => `// Karma configuration
// Generated on Fri Feb 17 2017 14:46:21 GMT-0500 (COT)

module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine', 'systemjs'],

        // list of files / patterns to load in the browser
        files: [
            'node_modules/jasmine-core/**/*.js',

            'app/built/!**!/!*spec.js',
             'app/built/!*spec.js',
             'app/built/!**!/!*spec.map.js',
             'app/built/!*spec.map.js'

        ],

        // list of files to exclude
        exclude: [],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {},

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS', 'PhantomJS_custom'],

        customLaunchers: {
            'PhantomJS_custom': {
                base: 'PhantomJS',
                options: {
                    windowName: 'my-window',
                    settings: {
                        webSecurityEnabled: false
                    },
                },
                flags: ['--load-images=true'],
                debug: true
            }
        },

        phantomjsLauncher: {
            // Have phantomjs exit if a ResourceError is encountered (useful if karma exits without killing phantom)
            exitOnResourceError: true
        },
        // plugin
        plugins: ['karma-systemjs', 'karma-jasmine', 'karma-phantomjs-launcher'],

        // systemjs config
        systemjs: {
            // Path to your SystemJS configuration file
            configFile: 'systemjs.config.js',

            // Patterns for files that you want Karma to make available, but not loaded until a module requests them. eg. Third-party libraries.
            serveFiles: [
                'public/**/*.js',
                'node_modules/jasmine-core/lib/jasmine-core.js'

            ],

        },

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false,

        // Concurrency level
        // how many browser should be started simultaneous
        concurrency: Infinity
    })
}
`

but not working please help me.

**Comment by slackersoft** [comment]
This sounds like it is probably an issue with Karma and not Jasmine itself. That error is related to the page not being set up properly for Jasmine to work.

I'm going to close this. Thanks for using Jasmine!
