### ISSUE TITLE
jasmine.clock and setTimeout inside nested promises

### ISSUE THREAD

**Issue by camel-chased** [jasmine/jasmine#1282]
How to use `jasmine.clock` `setTimeout` mock inside nested promises? (result: `Error: jasmine.DEFAULT_TIMEOUT_INTERVAL`)

Order is crucial here.

I need to test nested `promise`s that must have `setTimeout` inside - order matters. I know that `then` is kind of `process.nextTick` (or `setImmediate`) and it goes beyond current event loop (which is the core problem here) but this knowledge does not solve the problem :)

I know that I can put `jasmine.clock().tick()` inside nested promise but this is pointless because I'm testing proper order in some events related lib.

How to test something like this in jasmine? any ideas?

It looks like `jamine.clock().tick(...)` have a `sync` nature but `promises` are async. So we are hitting a wall here?

```javascript
it("should run setTimeout mock inside chained promises",(done)=>{

      jasmine.clock().install();

      let realOrder = [];

      let ok1=new Promise((resolve,reject)=>{
          resolve("ok");
      }).then((ok)=>{
        let p=new Promise((resolve,reject)=>{
          setTimeout(()=>{ // not fired up due to 'then' method
            realOrder.push("1");
            resolve("1");
          },100);
        });
        //jasmine.clock().tick(101); //<- order is crucial here so I can't do that
        return p;
      });

      let ok2=new Promise((resolve,reject)=>{
          resolve("ok");
      }).then((ok)=>{
        let p=new Promise((resolve,reject)=>{
          setTimeout(()=>{ // not fired up due to 'then' method
            realOrder.push("2");
            resolve("2");
          },50);
        });
        //jasmine.clock().tick(51); //<- order is crucial here so I can't do that
        return p;
      });

      jasmine.clock().tick(151);// we must go outside nested promise - we dont need to run tick inplace because order will change
      Promise.all([ok1,ok2]).then((results)=>{
        expect(results).toEqual(["1","2"]);
        expect(realOrder).toEqual(["2","1"]);
        done();
      });
  });
```

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!

**Comment by camel-chased** [comment]
This actually is a bug / feature.
`setTimeout` and `jasmine.clock().tick()` doesn't work inside nested promises.

**Comment by slackersoft** [comment]
The intention behind the Jasmine clock is to make actions that are normally async (possibly with a long wait) to be run in a synchronous manner. The way it does this is by mocking out the normally async methods (`setTimeout` and `setInterval`) so that callbacks passed to them can be triggered synchronously when your test wants them to. This means that if you do something async within an async callback, you may need to tick again to get that secondary async thing to happen. Within a given timeout length, the clock will call the functions in the order that they are added, so order should be preserved.

I hope this helps. Thanks for using Jasmine!
