### ISSUE TITLE
Start and stop the test manually in browser

### ISSUE THREAD

**Issue by skyshore2001** [jasmine/jasmine#1284]
**Expected behavior:**

- Start test manually: When I open the test runner web page in a browser, it shows all the suites and cases. Actually now it executes all of cases immediately on the page load. 
- Stop test manually: There is a "stop" button when I click it stop the test immediately. Actually now I cannot stop test unless I close the browser.

**Environment**

 - What version are you using?
2.5.2

 - What environment are you running Jasmine in (node, browser, etc)?
Browser.

 - How are you running Jasmine (standalone, npm, karma, etc)?
Standalone

**Comment by skyshore2001** [comment]
First I appreciate your great work and I like jasmine very much.

I'd like you to understand that **my test is slow and one full run may cost several minutes or even hours**.  So I have some special requirements described in several issues. Now I summarize them here.

I use jasmine to test the back-end web service interface in browser, as it's easy to view the network log and debug the steps in chrome utilizing chrome's the developer tools. 
Each case contains at least one synchronized ajax call to the back-end which may cost 50ms-500ms. The whole test may contains tens of suites and hundreds of cases.

I expect such features:

## I can see the test progress. 

As I use sync ajax call in the test case,  the browser loses response and I cannot see which case has completed. (see https://github.com/jasmine/jasmine/issues/1285)

I don't want to write the cases in async mode as it makes code complex.

## I can start and stop the test manually.  

(described in this post)

When I open the test runner page, sometimes I just want to choose a case to debug rather than run all cases with waiting several minutes. 

## Critical case support

Developer is able to mark some case as "critical case".  If some critical case fail, skip the other cases in the same suite. And if some critical suite fails, skip all of the others tests. (see https://github.com/jasmine/jasmine/issues/414 and https://github.com/jasmine/jasmine/issues/577)

Usually the first case in a suite is auto marked as "critical case". If such case fails, the other cases ("it" blocks) are skipped to execute and marked as "pending". If the first suite fails, skip all the rest cases.

I expect a flexible mechanism that the core lib expose some more interfaces that allows developers to program the logic.

## Easy debugging

Highlight the spec file in stack trace for failed tests (see https://github.com/jasmine/jasmine/issues/801)

- filter out the stack lines of the jasmine lib.
- Better the filter rule can be configured.
- (nice to have) click the line, and it locates the file and line in the source code panel in the developer tool of chrome browser.

**Comment by slackersoft** [comment]
A [I noted](https://github.com/jasmine/jasmine/issues/1285#issuecomment-286568004) in #1285, Jasmine already displays progress information as the suite is executed. So this part is a duplicate.

If you want to only run a subset of your suite, you should look into [focused specs](https://jasmine.github.io/2.5/focused_specs.html) to solve this. Being able to start and stop a suite in the middle of a run would be a huge undertaking without much upside so this isn't something we're looking to have in Jasmine.

Other people have been asking for the other items you've mentioned (you've even link to the issues), so those seem like duplicates as well.

Closing this. Thanks for using Jasmine!
