### ISSUE TITLE
Message set with "fail()" can leak into following "it()"

### ISSUE THREAD

**Issue by johncvrs** [jasmine/jasmine#1287]
A message set with "fail()" can leak into following "it()" if an async method is mistakenly called by user (e.g., if one is not aware some 3rd party callback is async).
Happens with "fail()" messages only, not with "expect()" messages.

https://plnkr.co/edit/qfZCXMBM8IiA2AsvQwGu

The spec is also included below.

### When submitting an issue, please answer the following:

 - What version are you using?  
  2.5.2
 - What environment are you running Jasmine in (node, browser, etc)?  
 - How are you running Jasmine (standalone, npm, karma, etc)? standalone
   https://plnkr.co/edit/qfZCXMBM8IiA2AsvQwGu demonstrates it in browser environment.
   Plunkr shows same results for FireFox/Chrome/Safari.

       describe('Jasmine message leak demo.', () => {

          // Oops - I am doing async but forgot "done".  My bad.
          it('This will unintentionally pass, and leak its fail.', () => {
              setTimeout(() => {
                  fail('I am in your test!');
              }, 1000);
              expect(true);
          });

          // Should error on
          //     'Async callback was not invoked within timeout
          //      specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.'
          // Instead, it reports the fail message
          //     'I am in your test!'
          it('This will fail, but with wrong message.', (done) => {
              let rememberToCallDone = false;
              if (rememberToCallDone) {
                  done();
              }
          });

          // Same code as previous "it()", but now this one behaves correctly:
          // It errors on
          //     'Async callback was not invoked within timeout
          //      specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.'
          it('This will fail, but with correct message.', (done) => {
              let rememberToCallDone = false;
              if (rememberToCallDone) {
                  done();
              }
          });

          // Nothing leaks into here.  Behaves as expected.
          it('This will pass.', () => {
              expect(true);
          });

          // Nothing leaks into here.  Behaves as expected.
          it('This will pass.', (done) => {
              expect(true);
              done();
          });
        });

Thank you for this great library.

**Comment by slackersoft** [comment]
Unfortunately, there isn't a whole lot that Jasmine can do to stop this. To my knowledge, there isn't a way to detect that some code has called `setTimeout` (or `setInterval`, `setImmediate`, made a promise, etc.) or otherwise caused execution to become async without mocking out all of the possibilities. Expectations inside your `setTimeout` would also get associated with the next spec because as soon as the function for the first `it` returns, Jasmine will move on to the next.

I'm going to close this, since I don't think this is something Jasmine can really solve. Sorry. Thanks for using Jasmine!

**Comment by johncvrs** [comment]
Ah, I had seen Jasmine installing its own `setTimeout()` before.  Now I see that it _only does that within the context of_ `Jasmine.clock().install()`, not for all specs.   Within that context, it also seems to discard any stragglers in the timer queue when `uninstall()` is called, which is what I need.  Problem solved.  Thanks for the support.
