### ISSUE TITLE
Support for .toHaveBeenCalled().exactly(x).times() assertions on spies

### ISSUE THREAD

**Issue by davidwkeith** [jasmine/jasmine#129]
A syntax like:

expect(MySpy.foo).toHaveBeenCalled()exactly(5).times();
expect(MySpy.foo).toHaveBeenCalledWith('bar').exactly(3).times();
expect(MySpy.foo).toHaveBeenCalledWith('bat').exactly(2).times();

// Helpers
expect(MySpy.foo).toHaveBeenCalled().once();
expect(MySpy.foo).toHaveBeenCalled().twice();

would only pass if MySpy.foo was called the specified number of times.

**Comment by Deepakdubey90** [comment]
Hi guys,
 How to test function inside a controller like:
controller :{
var fun = function(val){ 
                                       var aa = "text"
                                    } 
}
I'm not able to access above function in my unit test case fun (jasmine karma) like scope functions in controller.

**Comment by slackersoft** [comment]
@Deepakdubey90 You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

**Comment by dionyziz** [comment]
@slackersoft The link provided to privotaltracker points to a 403. What's the status of this?

**Comment by Gerg** [comment]
@dionyziz http://jasmine.github.io/2.4/introduction.html#section-21

**Comment by dionyziz** [comment]
Thanks!

**Comment by BrightShadow** [comment]
currently we have something like this:

`expect(foo.setBar).toHaveBeenCalledTimes(2);`

we can also use less convenient method:

`expect(foo.setBar.calls.count()).toBe(1);`

The calls object is of type `Calls` and have a little bit more than just count() :-)

```
interface Calls {
        /** By chaining the spy with calls.any(), will return false if the spy has not been called at all, and then true once at least one call happens. **/
        any(): boolean;
        /** By chaining the spy with calls.count(), will return the number of times the spy was called **/
        count(): number;
        /** By chaining the spy with calls.argsFor(), will return the arguments passed to call number index **/
        argsFor(index: number): any[];
        /** By chaining the spy with calls.allArgs(), will return the arguments to all calls **/
        allArgs(): any[];
        /** By chaining the spy with calls.all(), will return the context (the this) and arguments passed all calls **/
        all(): CallInfo[];
        /** By chaining the spy with calls.mostRecent(), will return the context (the this) and arguments for the most recent call **/
        mostRecent(): CallInfo;
        /** By chaining the spy with calls.first(), will return the context (the this) and arguments for the first call **/
        first(): CallInfo;
        /** By chaining the spy with calls.reset(), will clears all tracking for a spy **/
        reset(): void;
    }
```
