### ISSUE TITLE
How to load jasmine into browser with installed by npm?

### ISSUE THREAD

**Issue by rico345100** [jasmine/jasmine#1290]
I just want to load jasmine into browser with installed by npm, no using bundlers like webpack or browserify. I downloaded jasmine from npm, but it fails run from browser with:

```javascript
Uncaught ReferenceError: require is not defined
    at jasmine.js:1
```

Looks like jasmine installed via npm is just working with node.js, not for browser :(
I hate download javascript library from website and put them inside of project, I prefer download module from npm directly, so I can easily install it just run 'npm install', and also I can easily update with 'npm update'.

If I use bundler, it will resolves this problem, but I want to write testing code directly, without bundling. So, is there a way to using jasmine from npm to browser directly? Also do you have a plan to support UMD? Thanks!

**Comment by slackersoft** [comment]
The npm package called "jasmine" includes the wrapping context to run the tests in node itself. If you just want the underlying library check out the "jasmine-core" package. The object returned by `require`ing that should include information on the exact locations of the library code you need to load. 

Hope this helps. Thanks for using Jasmine!

**Comment by rico345100** [comment]
So, you mean load 'jasmine-core' from browser instead? Got it, thanks!
