### ISSUE TITLE
use async7await on the tests 

### ISSUE THREAD

**Issue by thiagohora** [jasmine/jasmine#1293]
Hi, i`m trying to implement a test for my postman library but i need use async/await to do this. The problem is that if I put the done parameter in the test method I got this:

`(node:3253) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error`

But, If I remove the parameter the test passes but don't execute the ajax call. That is the code:

```
it('Basic test', async function (done) {
    let data;
    try {
      data = await this.actionwords.thePostmanTestIsExecuted("Login").catch(error=> {throw new Error(error)});
    } catch(error){
        expect(error.error).toBe(null);
    }
    try {
      data = await this.actionwords.aResponseIsReceived(data).catch(error=> {throw new Error(error)});
      
      expect(data.data).not.toBe(null);
      expect(data.data.length).toBeGreaterThan(0);
      expect(data.error).toBe(null).or.toBe(undefined);        
    } catch(error) {
        expect(error.error).toBe(null);
    }
    try {
      Promise.all(done).catch(error=>{ throw Error(error); }).catch(error=>{ throw Error(error); });
    } catch(error) {
       expect(error.error).toBe(null);
    }
  });
```

How can I do this test execute properly using async/await?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
