### ISSUE TITLE
What about including Infinity methods?

### ISSUE THREAD

**Issue by toubou91** [jasmine/jasmine#1294]
I am thinking about two methods like ```toBeInfinity()```, ```toBeNegativeInfinity()```.
Of course one could argue that we could work around this issue with ```toEqual(Infinity)```, but then I would reply "what is then the purpose of ```toBeNaN()``` method?".

For a visual example, you can refer to https://github.com/mhevery/jasmine-node/pull/415/files.

**Comment by slackersoft** [comment]
This probably has a fairly limited use, but I would be happy to review a pull request to add these matchers.

**Comment by toubou91** [comment]
Cool, I start working on it then
