### ISSUE TITLE
Add `console.time` and `console.timeEnd` support to `jasmine.clock`

### ISSUE THREAD

**Issue by nemoDreamer** [jasmine/jasmine#1299]
I wrote a util that wraps `console`'s `time` and `timeEnd` methods (https://developer.mozilla.org/en-US/docs/Web/API/console#Timers), and is able to calculate averages across multiple calls, etc...
**But** I'm getting brittle test results even when using combinations of `.toBeGreaterThan` and `.toBeLessThan`, because I can't account for large fluctuations of test execution time...

It would be great to be able to "mock" these `console` methods much like we currently can `setTimeout`.

It seems they're standard, and so would not be subject to the same requirements as #866 ?

**Comment by slackersoft** [comment]
It looks like the functions are there on most browsers, but not IE < 11 and phantomjs, so it would still need to be detected and not blindly installed. Additionally, all the docs I'm reading indicate that they just print the timing information directly to the console and not necessarily return the information, so I'm not totally sure how you would programmatically get the information.

Alternatively, for your tests, you should probably just be able to `spyOn` the functions and specify behavior that way.

**Comment by nemoDreamer** [comment]
Aha, yes, I'm storing the timestamps myself in my wrapper.
I'll se if there's a way I should be using `new Date().getTime();` that works w/ Jasmine's `clock`.

**Comment by nemoDreamer** [comment]
Hey @slackersoft finally used `mockDate`, and was able to get rid of all my fuzze less/greaterThan assertions, thanks!

Can I suggest you add something about `mockDate` and `withMock` to the `introduction.js` docs? Should I create a new issue to track that suggestion?

**Comment by slackersoft** [comment]
Here's the current mention for this: https://jasmine.github.io/edge/introduction#section-Mocking_the_Date  I agree this isn't super easy to find, and we've launched some new API docs that should be better at surfacing what exists on Jasmine's API. The clock page for that is here: https://jasmine.github.io/api/edge/Clock.html

Hope this helps. Thanks for using Jasmine!

**Comment by nemoDreamer** [comment]
Oh wow, I _must_ have seen that at some point, and then forgotten about it...
Sorry!!

Jasmine **rocks**, @slackersoft . I keep getting nearly lured away to mocha/sinon/chai blends, but always end up thinking "wait a minute, Jasmine already does all this for me in one package..."
(I _do_ use the `karma-mocha-reporter` though, 'cause it's purdy 😜 )
