### ISSUE TITLE
createSpyObj() with a return value for each spy method

### ISSUE THREAD

**Issue by jongunter** [jasmine/jasmine#1306]
I use Jasmine to mock a lot of AngularJS services that return promises. For this purpose, I'd like to use the `createSpyObj` method and have a certain return value for each. For example:

```
var UserService  = jasmine.createSpyObj('UserService', ['query', 'get', 'post', 'remove', 'put'])
.and.returnValue(new Promise())
```

However, Jasmine does not allow me to tack on `.and.returnValue` at the end of this function call. It throws an error. As a result, I'm stuck writing this significantly more verbose syntax:
```
var UserService = {
   query: jasmine.createSpy('query').and.returnValue(new Promise()),
   get: jasmine.createSpy('get').and.returnValue(new Promise()),
   post: jasmine.createSpy('post').and.returnValue(new Promise()),
   delete: jasmine.createSpy('delete').and.returnValue(new Promise()),
   put: jasmine.createSpy('put').and.returnValue(new Promise()),
}
```

Is there any way I can, by default, return a specific value for every method created by a `createSpyObj` factory?

Additional info:
 - What version are you using? **Jasmine 2.4**
 - What environment are you running Jasmine in (node, browser, etc)? **Browser**
 - How are you running Jasmine (standalone, npm, karma, etc)? **Chutzpah for Visual Studio**

**Comment by slackersoft** [comment]
You should be able to pass an object for the methods instead of an array. (https://jasmine.github.io/api/edge/jasmine.html#.createSpyObj). `createSpyObj` returns the object that was created, which just happens to have each of its properties be a `Spy`. So this should work:

```javascript
var UserService = jasmine.createSpyObj('UserService', {
    'query': new Promise(),
    'get': new Promise(),
    .
    .
    .
});
```

Hope this helps. Thanks for using Jasmine!

**Comment by jongunter** [comment]
@slackersoft Thanks! Is that syntax only available in the latest version, or do 2.4 and 2.5 have it?

**Comment by slackersoft** [comment]
It looks like it is only in edge right now.

**Comment by ericis** [comment]
Yep. this isn't available. I get an array of strings as the only option for 2nd arg

**Comment by slackersoft** [comment]
@ericis this functionality should be out in the 2.6.2 release. What version of Jasmine are you using?

**Comment by boris-ilijic** [comment]
Does createSpyObj support mocking getter / setters in the same fashion as it supports methods in the example above?

**Comment by slackersoft** [comment]
@boris-ilijic Jasmine does not currently have a way to bulk create spies on properties

**Comment by X-51** [comment]
Thank you it helped a lot.
I would like to add that you can return another function and then spyOn it again.

`
tape = jasmine.createSpyObj('tape', 
    {
        'controls': {
            rewind: function() {
                return true;
            },
            forward: function() { 
                return true;
            }
        }
    }
);

spyOn(tape.controls(), 'rewind');
`
