### ISSUE TITLE
Does beforeAll and afterAll support 'done' callback ?

### ISSUE THREAD

**Issue by kunalshokeen** [jasmine/jasmine#1310]
Hi All,

I have read that beforeEach and afterEach in Jasmine supports done callbacks for asynchronous code the same way as it.Is done callback supported in beforeAll and afterAll too ?

Regards,
Kunal

**Comment by slackersoft** [comment]
Yep. Heres the link to the docs: https://jasmine.github.io/edge/introduction#section-Asynchronous_Support we haven't quite added all of this stuff to the API docs just yet.

Closing. Thanks for using Jasmine!
