### ISSUE TITLE
After hooks fire in an inconsistent order.

### ISSUE THREAD

**Issue by gdborton** [jasmine/jasmine#1311]
### Are you creating an issue in the correct repository?

I think so 🤔 .

### When submitting an issue, please answer the following:

 - What version are you using? 2.5.3
 - What environment are you running Jasmine in (node, browser, etc)? node v4.6.2
 - How are you running Jasmine (standalone, npm, karma, etc)? `jasmine ./path/to/spec.js`
 - If possible, include an example spec that demonstrates your issue. See below.

Given the following test file

```javascript
describe('stuff', function() {
  beforeAll(console.log.bind(null, 'beforeAll1'));
  beforeAll(console.log.bind(null, 'beforeAll1'));

  beforeEach(console.log.bind(null, 'beforeEach1'));
  beforeEach(console.log.bind(null, 'beforeEach2'));

  afterEach(console.log.bind(null, 'afterEach1'));
  afterEach(console.log.bind(null, 'afterEach2'));

  afterAll(console.log.bind(null, 'afterAll1'));
  afterAll(console.log.bind(null, 'afterAll2'));

  it('should pass', console.log.bind(null, 'test'));
});
```

I get the following output:

```
❯ jasmine ./test/what_spec.js --silent
Started
beforeAll1
beforeAll1
beforeEach1
beforeEach2
test
afterEach2
afterEach1
.afterAll1
afterAll2
```

Note that `afterEach` gets its order reversed while `afterAll` does not.

Personally I'd like to see neither of them reversed, but that doesn't matter as much as consistency.  I found this while working on a tool that helps automate some setup/teardown, and noticed that the teardown was happening in the wrong order.

**Comment by slackersoft** [comment]
See the discussion in #908 about what is the correct order for `afterEach` in a BDD framework. Long story short the current behavior is the right behavior and we're probably not going to change it. 

Hope this helps. Closing this. Thanks for using Jasmine!

**Comment by gdborton** [comment]
@slackersoft The issue here isn't that `afterEach` is run in reverse order, but that `afterAll` isn't. Shouldn't these behave consistently with each other?

**Comment by slackersoft** [comment]
Ahh! `afterEach` and `afterAll` should both be run in the opposite order they are declared. If this isn't happening for `afterAll`, we would be happy to review a pull request to correct this. 

Sorry for the confusion.
