### ISSUE TITLE
Really Important Question.

### ISSUE THREAD

**Issue by muhammad-haroon** [jasmine/jasmine#1315]
Hi I am new to jasmine and javascript in general,
 i know i should have asked this question on stackoverflow, but i think this is the right place , as i have tried stackoverflow.
the question is . 
in a spec , e.g in the it function , if i have a promise that gets rejected.
can i return a pending on this. e.g
describe ('blah' ,() => {
 it('blah blah', ()=>{
   checkBlah().
  then((result) => {
   if(result != ok){
    **return pending();**
   }
  return doBlahBah() .....
  });
});
});

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
