### ISSUE TITLE
Very slow tests after update from 2.5.3 to 2.6.0 

### ISSUE THREAD

**Issue by rryter** [jasmine/jasmine#1322]
After upgrading Jasmine and Jasmine **only**, suddenly the tests were running dramatically slower than usual. The test duration increased from approximately 15 minutes to more than 30 minutes.

The tests run in chrome via karma.

**Comment by olivierbelzile** [comment]
Same here with 2.6.1. Running in karma and PhantomJS. Reverting to 2.5.2 fixes everything.

**Comment by slackersoft** [comment]
There is a bunch more conversation about what seems like this same issue over in #1327, so I'm going to close this issue as a duplicate. As [I mentioned there](https://github.com/jasmine/jasmine/issues/1327#issuecomment-298428235), this is my current highest priority in my limited Jasmine time.
