### ISSUE TITLE
2.6.0 causes regression of 1188

### ISSUE THREAD

**Issue by davidje13** [jasmine/jasmine#1324]
Since updating to Jasmine 2.6.0, we have noticed the same issue described here: https://github.com/jasmine/jasmine/issues/1188

This appears to be a regression; downgrading to 2.5.2 resolved it for us.

Seems to have been caused by the fix (https://github.com/jasmine/jasmine/pull/1192/commits/c0a9d20a028b930faf5a49bbcc5d97609a1b45b4) either not being applied to the 2.6 branch, or being reverted.

**Comment by Darkein** [comment]
same problem for me.

**Comment by dougludlow** [comment]
Seeing the same thing. My CI build suddenly started failing on several tests with the following error:

``` 
TypeError: allKeys[i].match is not a function
```

Downgrading to 2.5.2 resolves the issue for us as well.
