### ISSUE TITLE
Expected $[0] not to have properties     invocationOrder:

### ISSUE THREAD

**Issue by UziTech** [jasmine/jasmine#1331]
same error that is on the bottom of your documentation

https://jasmine.github.io/2.6/introduction.html

**Comment by slackersoft** [comment]
I've fixed the docs. What are you doing that you are also encountering this error?

**Comment by UziTech** [comment]
https://github.com/UziTech/atom-jasmine2-test-runner

I basically run all the same tests to make sure everything is working for jasmine 2.x on Atom

**Comment by slackersoft** [comment]
Just to confirm then, fixing Jasmine's docs solves this issue for you correct? Or is something else needed?

**Comment by UziTech** [comment]
yes that fixed it, thank you.
