### ISSUE TITLE
2.6 upgrade from 2.5.2 generates errors

### ISSUE THREAD

**Issue by samudurand** [jasmine/jasmine#1334]
Jasmine 2.5.2 -> 2.6.0

I am running my tests using Karma and PhantomJS and until yesterday everything was running smoothly but since then my Jenkins tests have been failing. After downgrading to jasmine 2.5.2 explicitly everything went back to normal.

```bash
> karma start ./config/karma.conf.js

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'global.process.listeners('uncaughtException')')
  at node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2180
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'global.process.listeners('uncaughtException')')
  at node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2180

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 44 ERROR (0.002 secs / 0 secs)

npm ERR! Test failed.  See above for more details.
```
I am fine with 2.5.2, but I am just putting it here in case someone else really needs 2.6 and needs this fixed

**Comment by maksimluzik** [comment]
Having same issues as well with the new 2.6.0 Jasmine version. constructor errors as well as Jasmine promise/ajax timeouts happening. Was working before the update.

`Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

and

`TypeError: undefined is not a constructor (evaluating 'allKeys[i].match(/^[0-9]+$/)') in /Users/maksim/Workspace/midaxo-frontend/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2576)`

**Comment by arshtepe** [comment]
@maksimluzik  I have same issue, when i use  toEqual  for array.
`expect([1]).toEqual([1]);`

**Comment by master-elodin** [comment]
I am also getting errors after upgrading 2.5.2 -> 2.6.0:

```
Error: <spyOn> : success has already been spied upon
Usage: spyOn(<object>, <methodName>) in file:///projectdir/.grunt/grunt-contrib-jasmine/jasmine.js (line 4321) (1)
```

**Comment by pierremanceaux** [comment]
+1, same here.

**Comment by BrianLenzo** [comment]
+1 same error.  2.5.2 and 2.5.3 work fine.

**Comment by gap777** [comment]
I am also getting errors after upgrading 2.5.2 -> 2.6.0 when comparing arrays:

```
Message:
    TypeError: allKeys[i].match is not a function
  Stack:
    TypeError: allKeys[i].match is not a function
        at Object.<anonymous> (/MySpecFile.js:104:21)
```

**Comment by slackersoft** [comment]
The `process.listeners` errors should be fixed as of 1d62504534aa05aeee2f0bdf095c588dcf63bc96

The `allKeys` errors should be fixed from #1326

**Comment by slackersoft** [comment]
@maksimluzik what type of constructor errors are you seeing? I'm not sure what to look for based on that description.

Thanks.

**Comment by slackersoft** [comment]
@master-elodin `spyOn` doesn't allow overriding of an existing spy by default. The option to allow overriding at all was only added in 2.5 with `jasmine.getEnv().allowRespy()`.

Hope this helps. Thanks for using Jasmine!

**Comment by maksimluzik** [comment]
@slackersoft my bad, with the constructor errors I mean the `allKeys[i].match(/^[0-9]+$/)')` issue

**Comment by gap777** [comment]
Kudos for 2.6.1 release, but npm repos don't see it yet?

**Comment by slackersoft** [comment]
@gap777 This repo is the [jasmine-core](https://www.npmjs.com/package/jasmine-core) package on npm. As these fixes don't require changes to the node.js bindings the [jasmine](https://www.npmjs.com/package/jasmine) package did not get bumped.

**Comment by Itschrismorgan** [comment]
Just to chime in.

We are still seeing the asyc callback error with 2.6.1.  I've had to peg our package.json to version 2.5.2 to keep our unit test passing.

```
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by steel** [comment]
We're seeing these errors as well after upgrading to 2.6.1. We've downgraded back to 2.5.2 for the time being.

**Comment by slackersoft** [comment]
I'm working on getting 2.6.2 out tonight with some fixes for various async related issues. Assuming you're seeing the async callback issue incorrectly, this should hopefully fix the problem.

**Comment by Sebl29** [comment]
+1

**Comment by tkmcmaster** [comment]
We're still seeing the async/await issues with jasmine-core 2.6.2. We've also had to revert to 2.5.2 as well.

**Comment by slackersoft** [comment]
@tkmcmaster what kind of `async`/`await` errors are you seeing? The issues reported so far in this issue haven't necessarily been about using the actual keyword async functionality, but just specs that are asynchronous by nature.

**Comment by tkmcmaster** [comment]
We have both an async setup and teardown functions as part of our tests in a plugin we pull in for our tests. Our tests in our spec then use methods set up by the plugin.

The effect we see is that the browser is getting shut down before our setup is even complete.

**Comment by slackersoft** [comment]
@tkmcmaster Jasmine doesn't support `async` functions being passed to `it`, `beforeEach`, etc. and won't actually wait for them to finish before moving on. It sounds like you might have an issue with Jasmine not knowing that your setup is asynchronous. Are you receiving a `done` param?

Can you provide a simplified example of a suite that exhibits the issue so we can help resolve it?

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Jasmine 2.7.0 is now out with support for Promises and `async` functions for the various portions of the interface that can be async (i.e. with the `done` argument). Hopefully this will help with some of the async setup issues people are having.

**Comment by asednev** [comment]
@slackersoft interestingly enough after upgrading from 2.6.4 to 2.7.0 we started getting following error in number of projects:

`Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

**Comment by slackersoft** [comment]
@asednev do you have specs that return Promises or are `async function`s? These should be detected as async by Jasmine in 2.7 and can cause that timeout error if they take too long.

**Comment by asednev** [comment]
> do you have specs that return Promises or are async functions? 

@slackersoft your question provided much needed insight. We use coffeescript and all functions return last statement. So far it looks like all of the tests that are failing with timeout error in Jasmine 2.7 return Promises. Thank you for the tip.

**Comment by slackersoft** [comment]
I think we've solved all of the concerns from this issue, so I'm going close it. If we missed something, please open a new issue so we can track it more easily.

Thanks for using Jasmine!

**Comment by vishal9458425389** [comment]
> Having same issues as well with the new 2.6.0 Jasmine version. constructor errors as well as Jasmine promise/ajax timeouts happening. Was working before the update.
> 
> `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`
> 
> and
> 
> `TypeError: undefined is not a constructor (evaluating 'allKeys[i].match(/^[0-9]+$/)') in /node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2576)`

@maksimluzik  How did you fix this ?

**Comment by maksimluzik** [comment]
If I recall correctly, just downgraded jasmine to version 2.5.2. But you should try the latest one, maybe they fixed it.

**Comment by vishal9458425389** [comment]
> If I recall correctly, just downgraded jasmine to version 2.5.2. But you should try the latest one, maybe they fixed it.

@maksimluzik  how to upgrade the karma?
please help
