### ISSUE TITLE
beforeAll is not defined

### ISSUE THREAD

**Issue by qblslion** [jasmine/jasmine#1337]
recently I use jasmine to run my api testing,and I also install karma,the karma is configed by other people.
When I write scripts,
beforeEach can be used,but beforeAll is not defined and always report an error.
I have searched and tried to upgrade my jasmine-node and karma-jasmine to @v0.3.5 and the problem still exist.I think it is due to  the version relative to jasmine 
 
the package.json is as follows:
"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular2-in-memory-web-api": "0.0.20",
    "body-parser": "~1.16.0",
    "bootstrap": "^3.3.6",
    "cookie-parser": "~1.4.3",
    "core-js": "^2.4.1",
    "debug": "~2.6.0",
    "express": "~4.14.1",
    "express-session": "*",
    "frisby": "^0.8.5",
    "jasmine-core": "^2.5.2",
    "jasmine-node": "^1.14.5",
    "jasmine-node-karma": "^1.6.1",
    "jasmine-xml-reporter": "^1.0.6",
    "kerberos": "~0.0.23",
    "mongodb": "~2.2.25",
    "morgan": "~1.7.0",
    "passport": "*",
    "passport-cas2": "*",
    "reflect-metadata": "^0.1.3",
    "requirejs": "^2.3.3",
    "rxjs": "5.0.0-beta.12",
    "serve-favicon": "~2.3.2",
    "systemjs": "0.19.27",
    "vertx3-min": "^3.0.0-1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "angular2-cookie": "^1.2.6",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.1.2",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "concurrently": "^2.2.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "expect.js": "^0.3.1",
    "file-loader": "^0.11.1",
    "html-loader": "^0.4.5",
    "inline-source-map": "^0.6.2",
    "istanbul": "^0.4.5",
    "istanbul-instrumenter-loader": "^2.0.0",
    "istanbul-merge": "^1.1.1",
    "jasmine": "^2.5.2",
    "jasmine-core": "^2.5.2",
    "jasmine-supertest": "^1.0.0",
    "jasmine-webpack-plugin": "^0.1.1",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^1.2.0",
    "karma-jasmine": "^0.3.5",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-sonarqube-reporter": "0.0.1",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-requirejs": "^1.1.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.31",
    "karma-webpack": "^2.0.3",
    "less-vars-loader": "^1.1.0",
    "lite-server": "^2.2.2",
    "nodemon": "^1.11.0",
    "npm-run-all": "^4.0.2",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "should": "^11.2.1",
    "style-loader": "^0.16.1",
    "supertest": "^3.0.0",
    "ts-loader": "^0.8.1",
    "tslint": "^5.1.0",
    "typescript": "^2.0.2",
    "typings": "^1.3.2",
    "webpack": "^2.4.1",
    "webpack-node-externals": "^1.5.4",
    "webpack-shell-plugin": "^0.5.0"
  },

So pls tell me the jasmine version or karma-jasmine and others' version
THX

**Comment by askarby** [comment]
I think you'd have much more luck in getting help, if posing this question on [Stackoverflow](stackoverflow.com)

**Comment by slackersoft** [comment]
I don't think that [jasmine-node](https://github.com/mhevery/jasmine-node) supports 2.x versions of Jasmine, which are required for access to `beforeAll`. In your HTML runner page, what version of Jasmine does it say is being run?

Hope this helps. Thanks for using Jasmine!

**Comment by megamindbrian** [comment]
Any progress on this?

**Comment by slackersoft** [comment]
@megamindbrian what version of Jasmine are you using? How are you running Jasmine (Karma, jasmine-node, etc.)? As [I said](https://github.com/jasmine/jasmine/issues/1337#issuecomment-298751698), this feature was only released in Jasmine 2.1, which I don't think is supported by jasmine-node.

It sounds like this is either a configuration issue or using an older version of Jasmine. Closing.
