### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hippikon** [jasmine/jasmine#1338]
If theres a console.log in the JS under test, pl display output on SpecRunner.html

**Comment by slackersoft** [comment]
I don't think this is something we're going to put into Jasmine. `console.log` is a browser built-in that isn't always available in all browsers (older versions of IE only define it when the dev tools are open). This would make it difficult to intercept properly. In addition, this message should already appear in the console for whichever browser you are using.

Closing this. Thanks for using Jasmine!
