### ISSUE TITLE
Confused about MO vs MT

### ISSUE THREAD

**Issue by AndreaAltamirano** [jasmine/jasmine#1341]
Hello!
First of all, Jasmin is awesome in the couple of tests I've run so far, so many thanks to everyone involved.  I'm not sure if I'll get an answer here because this is more of a support/conceptual question than an issue. Apologies in advance.

I'm pretty confused when it comes to receiving messages. Our situation is as follows: we have our own numbers but we're not a mobile service provider. We would like to send messages to our clients (through the actual mobile providers) and be abale to receive answers (Like standardized YES or NO answers or prompts) and act on them through an API. This would be covered by the MO messages you refer to in your architecture:

<img width="195" alt="screen shot 2017-05-02 at 5 59 31 pm" src="https://cloud.githubusercontent.com/assets/28315478/25639175/40820974-2f61-11e7-9d45-e9fe784db0b3.png">

But to interconnect with the actual providers they require an SMPP connection where they are the client, while also getting DLRs and everything. This is obviously covered by the "SMPP Server" part of your architecture.

<img width="222" alt="screen shot 2017-05-02 at 6 11 56 pm" src="https://cloud.githubusercontent.com/assets/28315478/25639604/de9e39b0-2f62-11e7-90ad-35b6da386b8e.png">

The connection works with the one provider we've tried so far, but every message through that channel gets identified as an MT message...and we have nowhere to forward it because our numbers aren't actual devices. (We get this error:
"2017-04-28 19:17:01 ERROR    1 SMPPC [cid:virgin] is not bound: Requeuing ..."

So, to sum it up, is there any way to force messages to be identified as MO (How would they ever be MO and not MT?) to be able to trigger the scripts associated with Receiving SMS-MO as described in your documentation, while at the same time delivering DLRs to the SMPP client. Or if thats impossible, a way to save SMS-MT in a database and respond with DLRs while not actually delivering them to the destination number.

I hope that wasn't too confusing. Thanks in advance for any kind reply.

**Comment by slackersoft** [comment]
I think you might have the wrong project. Jasmine is a javascript testing framework, and has no knowledge of SMPP or any other domain concepts. Additionally, the screenshots you posted, are not from any Jasmine documentation I have ever seen.

I'm going to close this. Hope this helps.

**Comment by jaapz** [comment]
This is the project you're looking for: https://github.com/jookies/jasmin, next time read the readme first ;)
