### ISSUE TITLE
Upgrade from 2.5.2 to 2.6.1 get strange error

### ISSUE THREAD

**Issue by Teamop** [jasmine/jasmine#1342]
today when I upgraded jasmine-core from 2.5.2 to 2.6.1, got a strange error:
1. if one test case failed, caused all the rest of cases failed with same error:
failed case:
![image](https://cloud.githubusercontent.com/assets/8519685/25702687/bd71ae22-3104-11e7-9259-0907707a5615.png)
the rest part cases:
![image](https://cloud.githubusercontent.com/assets/8519685/25702709/d4ce497c-3104-11e7-9de7-c67f33874e8e.png)
also during them, there's some other errors:
![image](https://cloud.githubusercontent.com/assets/8519685/25702781/2af38a6a-3105-11e7-825a-e05b0789dccc.png)

**But** if I add breakpoint to debug, the result is right(one case fail, other passed):
just 3 errors for the failed case
![image](https://cloud.githubusercontent.com/assets/8519685/25702843/704bc28a-3105-11e7-9c4c-6137384bf6ae.png)

Karma version used : 1.6.0
Karma-jasmine : 1.1.0
Karma-chrome-launcher: 2.1.0

thanks for your help

**Comment by slackersoft** [comment]
This should also be fixed by #1352. Closing
