### ISSUE TITLE
No Spec Setting for console output 

### ISSUE THREAD

**Issue by vkuehn** [jasmine/jasmine#1346]
- What version are you using?
"jasmine": "^2.5.2"
 - What environment are you running Jasmine in (node, browser, etc)?
node v6.5.0 (different OS's all same result)
 - How are you running Jasmine (standalone, npm, karma, etc)?
just jasmine at the command line

not sure if that is an issue. I get a tests result just as
-----------------------
Started
......

6 specs, 0 failures
Finished in 0.01 seconds
------------------------
But I don't get anything as in the examples which mentions the describe or it sections. Only if there is a fault. Is there any spec setting which simply shows the same as a SepcRunner.html would ?

**Comment by slackersoft** [comment]
Jasmine's built in console reporter only supports dots. There are other projects, like [jasmine-reporters](https://github.com/larrymyers/jasmine-reporters) that provide more options for output.

Closing this. Hope this helps. Thanks for using Jasmine!

**Comment by vkuehn** [comment]
thanks, didn't know they support also jasmine versions newer than 1.3
