### ISSUE TITLE
What about including toBeNumber method?

### ISSUE THREAD

**Issue by toubou91** [jasmine/jasmine#1351]
The concept and the reason I thought about it is more or less similar to #1294.

**Comment by slackersoft** [comment]
A `toBeNumber` matcher doesn't seem like it provides quite as much value as the `Infinity` matchers do. `Infinity` can be a harder thing to get right, and numberness, should be checkable with something like `toEqual(jasmine.any(Number))`.

I don't think this is something we need in Jasmine at this time. Closing. thanks for using Jasmine!
