### ISSUE TITLE
Jasmine 2.6 fails to pretty print Set on Safari 8

### ISSUE THREAD

**Issue by mjeanroy** [jasmine/jasmine#1355]
Hi,

The pretty print function of Jasmine fails (throw an error) to pretty print `Set` instances on Safari 7.1 and Safari 8. The reason is that the pretty print function use the `Set.values` but the iterators returned by them lack a `next` method.

The fix could be to:
- Not try to pretty-print `Set` on browsers with incomplete `Set` features.
- Use `forEach` functions of `Set` which is correctly implemented in all browsers that support `Set` (even with partial support).

@slackersoft What do you think? I would be happy to submit a PR if you think it's worth it.

**Comment by slackersoft** [comment]
I would be happy to review a pull request to correctly pretty-print `Set`s on all browsers that support them.
