### ISSUE TITLE
How do I run jasmine using node's --trace-warnings?

### ISSUE THREAD

**Issue by SeanHayes** [jasmine/jasmine#1357]
I'm using jasmine 2.5.3

I submitted this question to jasmine-js@googlegroups.com but got a mailer error.

**Comment by slackersoft** [comment]
The [jasmine npm package](https://github.com/jasmine/jasmine-npm) doesn't have a built-in way to pass node options through to the underlying node process, but you should be able to execute it by passing it as an explicit parameter to the `node` executable. Probably something like:

```shell
node --options node_modules/.bin/jasmine
```

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this as it sounds like it has been resolved. Thanks for using Jasmine!
