### ISSUE TITLE
Expecting array of object 'toContain' array of objects fails

### ISSUE THREAD

**Issue by hudson-t** [jasmine/jasmine#1358]
When I try to check if an array of objects contains objects from another array, the test fails.

I have made a [jsFiddle](https://jsfiddle.net/hudson_t/btqy3yb3/8/) which outlines my expectations of the 'toContain' method which may be wrong but they would be nice!

> All version info is shown in the fiddle!

**Comment by slackersoft** [comment]
The `toContain` matcher look inside the actual to detect the occurrence of the single argument passed to it. Thus it is looking for one of the element in the actual array to be equal to the array that you passed. If you want to check an array for a subset of elements, you should try [arrayContaining](https://jasmine.github.io/api/edge/jasmine.html)

```javascript
expect(array).toEqual(jasmine.arrayContaining(["your", "stuff", "here"]);
```

Hope this helps. Thanks for using Jasmine! Closing.

**Comment by hudson-t** [comment]
@slackersoft - Thank you! I should have Googled more before posting here...
