### ISSUE TITLE
Default parameters

### ISSUE THREAD

**Issue by emanuelbuholzer** [jasmine/jasmine#1359]
Given a class like this:

```javascript
class Example {
  constructor(fn = (a, b) => b) {
    this.fn = fn;  
  }
}
```

Is it possible to test whether the function assigned to the property fn of the class is the default parameter or not? One approach would be to test the function itself which gets assigned to the class property fn. But this won't work for all cases - for example:

```javascript
const eg = new Example((a,b,c) => b);
```

The second function applied to the parameter fn isn't the same as the default parameter. This is just a very basic example and the use case for this test is indeed very rare.

**Comment by sgravrock** [comment]
Assuming that the default function doesn't really have to be an arrow function with the right `this`, I'd expose it as a named function and then test its identity:

```
function defaultFn(a, b) { return b; }

class Example {
   constructor(fn = defaultFn) {
      this.fn = fn;
   }
}

// ...

it("does not get the default function", function() {
   const eg = new Example((a,b,c) => b);
   expect(eg.fn).not.toBe(defaultFn);
});
```

**Comment by emanuelbuholzer** [comment]
Thank you! I didn't knew, that default constructors have access to variables from that scope.
