### ISSUE TITLE
How do you pronounce Jasmine

### ISSUE THREAD

**Issue by DavePilks** [jasmine/jasmine#1363]
We are having a bit of a pedantic argument in the office and are wondering about the correct pronunciation of Jasmine. 

Is it jaz-min or yas-meen ?

**Comment by jaapz** [comment]
http://dictionary.cambridge.org/pronunciation/english/jasmine

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

See @infews [blog post](https://content.pivotal.io/blog/jasmine-is-5-and-2-0) on the origins of the name.

Closing.
