### ISSUE TITLE
'npm package' test specs fail on Windows because tar is not a valid Windows command

### ISSUE THREAD

**Issue by kiewic** [jasmine/jasmine#1371]
When running `node_modules\.bin\grunt.cmd execSpecsInNode` in Windows, six test specs consistently fail because `tar` is not a command available on Windows.

Failing specs are:

1. npm package has bootFiles
2. npm package has an imagesDir
3. npm package has a bootDir
4. npm package has a root path
5. npm package has cssFiles
6. npm package has jsFiles

Error message is the same in all of them:

```bash
  Message:
    Expected 1 to be 0.
  Stack:
    Error: Expected 1 to be 0.
      at Object.<anonymous> (c:\repos\jasmine\spec\npmPackage\npmPackageSpec.js:15:24)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

The output of `require('shelljs').exec(...)` reveals the followign error:

```bash
  stderr: '\'tar\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n',
  code: 1,
```

I guess this is expected since I can see from the setup instructions Ubuntu is the recommended dev environment. 

Thanks,
Gilberto

**Comment by slackersoft** [comment]
For now you can probably ignore those errors, the specs should run fine on travis. We've had a couple issues in the past with some files not being included in the npm package correctly, so we want to keep that from happening again.

I'd be happy to review a pull request that either:
1. Marked the tests as pending and not run if the `tar` command is unavailable
2. Platform independently untarred the result of `npm pack` so the specs can run either way.

Thanks for using Jasmine!

**Comment by sgravrock** [comment]
It turns out that Windows has shipped with tar for a few years now. Given that the specs pass on recent-ish Windows installations and people on older builds can download tar binaries from various sources, I'll go ahead and close this.
