### ISSUE TITLE
Calling done.fail() after done() fails the test

### ISSUE THREAD

**Issue by samal84** [jasmine/jasmine#1374]
- What version are you using?
2.6.4
 - What environment are you running Jasmine in (node, browser, etc)?
Chrome 59 on Windows 10
 - How are you running Jasmine (standalone, npm, karma, etc)?
Standalone
 - If possible, include an example spec that demonstrates your issue.
https://jsfiddle.net/w8q0xdsz/1/
https://jsfiddle.net/200nr56k/3/

It seems that an async test will fail if you call done.fail() after calling done():
```
describe('test', function() {
  it('an async test', function(done) {
    done();
    done.fail();
  });
});
```

I would have expected the done.fail() call to be ignored, as we have already said done(). So the test should be over and done. Nothing should be able to come back and fail it.

I ran in to this problem when I had the bright idea that I should make sure that my rxjs subscriptions are cleaned up after each test. So I used takeUntil and make sure that it was triggered in the afterEach method. But I was already making sure that complete wasn't being called, by calling done.fail inside the complete callback, and this now gets triggered when takeUntil triggers.

**Comment by slackersoft** [comment]
Jasmine takes the approach that if `fail()` is called (even via `done.fail()`) or `expect` fails anywhere in a suite, then the suite should report the failure. So as long as the full suite hasn't finished reporting, calling a `fail` will cause something in the suite to have that failure.

Once `done()` has been called in a spec, Jasmine assumes that no more code for that spec will be run and it is free to move on to the next one. There is, however, some bookkeeping time before the next spec/suite is officially started and any failures that happen during that time will be associated with that spec. If they happen later, they may be associated with a completely different spec, as long as the full suite is still running.

For these reasons, we're going to leave this behavior as is for the foreseeable future.

Hope this helps. Thanks for using Jasmine!
