### ISSUE TITLE
Uncaught ReferenceError: jasmineRequire is not defined

### ISSUE THREAD

**Issue by wood1986** [jasmine/jasmine#1377]
I found the example on https://github.com/jasmine/jasmine#installation can be done by the webpack with html-webpack-plugin. Therefore I try to wire them up instead of hardcoding the script

```
// webpack.config.js

const path = require("path"),
      webpack = require("webpack"),
      HtmlWebpackPlugin = require('html-webpack-plugin'),
      ExtractTextPlugin = require("extract-text-webpack-plugin"),
      jasmineCore = require("jasmine-core");

module.exports = {
  "devServer": {
    "compress": true,
    "host": "0.0.0.0",
    "disableHostCheck": true,
    "clientLogLevel": "error"
  },
  "entry": {
    "client": path.resolve(__dirname, "src/pages/Spec/Spec.web.tsx")
  },
  "module": {
    "rules": [
      {
        "test": /\.spec\.tsx?$/,
        "enforce": "pre",
        "loader": "tslint-loader",
        "options": {
          "configuration": require("./tslint.json"),
          "tsConfigFile": "tsconfig.json",
          "fix": true
        }
      },
      {
        "test": /\.tsx?$/,
        "exclude": /node_modules/,
        "loader": "awesome-typescript-loader"
      },
      {
        "test": /jasmine\.css$/,
        "use": ExtractTextPlugin.extract({
          "fallback": "style-loader",
          "use": ["css-loader"]
        })
      },
      {
        "test": /\.scss$/,
        "use": "null-loader"
      }
    ]
  },
  "resolve": {
    "alias": {
      "jasmine": path.resolve(jasmineCore.files.path, "jasmine.js"),
      "jasmine-core": path.resolve(jasmineCore.files.path)
    },
    "extensions": [".ts", ".tsx", ".js", ".json", ".jsx"]
  },
  "output": {
    "filename": "[name].spec.js",
    "libraryTarget": "umd",
    "path": path.resolve(__dirname, `spec`),
  },
  "plugins": [
    new HtmlWebpackPlugin({
      "minify": {
        "removeComments": true,
        "collapseWhitespace": true
      },
      "filename": "index.html",
      "template": path.resolve(__dirname, "src/pages/Spec/Spec.ejs"),
      "favicon": path.resolve(jasmineCore.files.imagesDir, "jasmine_favicon.png")
    }),
    new ExtractTextPlugin("[name]-[contenthash].css"),
  ],
  "target": "web"
};

```

It compiles successfully but it fails in runtime. The error is `Uncaught ReferenceError: jasmineRequire is not defined` Then I compared the execution flow between the example and my webpack version. The issue in `jasmine-core/lib/jasmine-core/jasmine.js`

```
var jasmineRequire;

if (typeof module !== 'undefined' && module.exports && typeof exports !== 'undefined') {
           ^^^^^^
```

`module` and `exports` are `Object`s in my webpack version. But in standalone example, they are `undefined`. How can I move forward?

**Comment by wood1986** [comment]
I have just found. `require("script-loader!jasmine")` works

**Comment by slackersoft** [comment]
It sounds like this was a webpack configuration issue and not Jasmine itself. Glad to hear you fixed it. 

Closing. Thanks for using Jasmine!

**Comment by wood1986** [comment]
Don't close please. I think it is Jasmine issue and I am using webpack to hack it.  I think the implementation to determine whether it is node or web environment is not correct. If the implementation of jasmine.js is correct, I don't need to 'script-loader' to make 'module' and 'exports' undefined

**Comment by wood1986** [comment]
I would say there are one issue and one improvement 
1. node vs web checking
2. the standalone installation cannot be achieved in a proper way without using the alias in webpack situation

**Comment by slackersoft** [comment]
I would be happy to review a pull request that specifically fixed the checks around global detection for web-based CommonJS environments if Jasmine thinks it is finding a node.js environment, when it's really a browser.

We haven't fully re-worked the [documentation site](https://jasmine.github.io), but if there is a better getting started guide for Jasmine standalone when in a browser-based CommonJS environment, I'd be happy to review a [pull request](https://github.com/jasmine/jasmine.github.io/pulls)
