### ISSUE TITLE
Create a version of createSpyObj that accepts a constructor instead of a name.

### ISSUE THREAD

**Issue by rubenlg** [jasmine/jasmine#1379]
This is a feature request. And is useful mainly for typescript users.

The proposal is to have a version of `createSpyObj` that can be called with a constructor rather than a name. Maybe it could be called `createSpyOf(ClassConstructor, ...params)`.

This would make typings in Typescript much easier to write and work with. For an overview of why it's hard to type the current function in an accurate way, see here: https://github.com/Microsoft/TypeScript/issues/10571#issuecomment-310704784

By having a constructor as first argument rather than a string, both the mocked type as well as the list of keys being spied on could be inferred just from the parameters, and typescript developers would not need to specify them as generic parameters, which, as you can see from the comment linked above, is annoying for the list of keys being mocked.

In order to work with other things besides classes (e.g. typescript interfaces), ideally it would just get as first argument an object with a "name" property on it (something _like a constructor_). This way, we can pass a class constructor, but also anything else that has a name and carries a type.

The implementation in the jasmine world is pretty straightforward:
```javascript
function createSpyOf(constructorLike, params) {
   return createSpyObj(constructorLike.name, params);
}
```

My second proposal would be to extend createSpyObj, but I notice from the implementation that it supports a mode of operation in which you only pass one JSON object as first argument and it mocks all its properties. Changing that behavior would break existing clients.

In any case, this increases the API surface of jasmine, and I understand it might be marginally useful to javascript developers, so I wanted to gather your feedback.

**Comment by rubenlg** [comment]
Any thoughts?

**Comment by slackersoft** [comment]
Given the ease of adding a function like what you provided to your own TypeScript project and the potential for confusion about which function does which thing for normal Javascript users, I'm not sure this is something we want in Jasmine itself. While I appreciate the issues with finding types for the current Jasmine `createSpyObj`, maintaining typings within Jasmine is tricky given that we (the Jasmine team) don't really make use of TypeScript to see what we might be breaking.

Hope this helps. Thanks for using Jasmine! Closing.
