### ISSUE TITLE
Please release this.emitMap soon

### ISSUE THREAD

**Issue by michaelcm** [jasmine/jasmine#1380]
Thanks for the great ES6 map fix, exactly what I was looking for. Is it possible to get a new npm release for jasmine-core with the commit please? It was committed almost two months ago.

Thanks!

https://github.com/jasmine/jasmine/commit/5ee03f02edb8f18a857673d7a9b96aeee685415d

**Comment by michaelcm** [comment]
Actually, the last release was 2.6.4 which was 9 days ago... why didn't it include the code from the resolved pull request from a couple of months ago? The code is in master.
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js

Perhaps 2.6.4 was tagged from the 2_6 branch? Is it possible to pull this into the 2_6 branch if that is the case?

Thanks in advance!

**Comment by slackersoft** [comment]
The `emitMap` code didn't make it into the 2.6.x patch releases because we use patch releases for bug-fix updates to the previous minor release. As this is a new feature, it doesn't make sense to be in a bug-fix release. It should be in the next minor version (2.7).

**Comment by michaelcm** [comment]
I'm not picky about where/how it gets released, would just like to be able to use it easily with an npm relase. It was committed a good many months ago now. Hopefully 2.7.0 will arrive soon. Thanks for responding.
