### ISSUE TITLE
Customise Report

### ISSUE THREAD

**Issue by vedant05** [jasmine/jasmine#1384]
https://sqa.stackexchange.com/questions/27936/unable-to-add-attach-screenshot-and-test-steps-in-report

**Comment by sgravrock** [comment]
It looks like you're having trouble with some components that are part of Protractor, not Jasmine. If you aren't able to get the help you need on Stack Exchange, I suggest reaching out to the Protractor folks. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else on this in a while. Closing.
