### ISSUE TITLE
If toEqual() fails, the error message always include all properties compared to jasmine.any()

### ISSUE THREAD

**Issue by kiewic** [jasmine/jasmine#1388]
When `toEqual()` fails, and the expected value uses `jasmine.any()`, all comparisons to `jasmine.any()` are listed as errors. 

For example, the next spec succeeds:

```javascript
it("foo property equal", function() {
    var actual = {
        foo: true,
        bar: 1987
    };
    var expected = {
        foo: true,
        bar: jasmine.any(Number),
    };
    expect(actual).toEqual(expected);
});
```

But changing only `foo` makes the test fail, and the error indicates `foo` and `bar` do not have the expected value.

```javascript
it("foo property different", function() {
    var actual = {
        foo: false,
        bar: 1987
    };
    var expected = {
        foo: true,
        bar: jasmine.any(Number),
    };
    expect(actual).toEqual(expected);
});
```

This is the error message:

```
Expected $.foo = false to equal true.
Expected $.bar = 1987 to equal <jasmine.any(Number)>.
```

I'm using Jasmine 2.6.4 in a browser environment.

Thx

**Comment by slackersoft** [comment]
It looks like the diff builder tracking for asymmetric equality testers doesn't properly report when the check passed or not, and instead always reports a difference. I would be happy to review a pull request to fix this tracking so that the message is more correct.

Thanks for using Jasmine!
