### ISSUE TITLE
Adding metadata to suites and specs

### ISSUE THREAD

**Issue by shikaan** [jasmine/jasmine#1392]
Hi everyone,
thank you for the good job you made and you're making with Jasmine which is by far my favourite testing framework.

Before putting my hands in the code and creating a fork of Jasmine I would like to know if there's a less hacky way to achieve what I want.

Basically I'd like to add some metadata to suites and specs in order to have more detailed reports. 

For example:
```javascript
describe('Suite name', {date: Date.now(), detailedDescription: 'Super detailed description'}, function() {
    it('should work', {detailedDescription: 'Another super detailed description'}, function() {
        expect(true).toBeTruthy()
    });
})
```

I'd like to use the extended object this way:
```javascript
const Reporter = {
    suiteStarted: (suite) => {
        console.log(`Suite started at ${suite.metdata.date}`)
    },
    specDone: (spec) => {
        console.log(`Description ${spec.metadata.detailedDescription}`)
    },
}
```

Is there any way to extend the object returned by `describe` or by `spec`? 

I have of course tried (without any success):

```javascript
let suite = describe('Suite name', function() {
    suite.date = Date.now();
   ...
})
```

Thank you in advance!

**Comment by slackersoft** [comment]
If the primary thing you want to do is have start/stop times in a custom reporter, you should use the existing reporter events to do the timing there. The suite and spec objects are internal details of Jasmine and not meant for storing transient data about the execution of the suite. Additionally, the `Date.now()` call you use would be the time of declaration of the suite or spec and not when execution started.

Hope this helps. Thanks for using Jasmine!
