### ISSUE TITLE
Inconsistent behavior between matcher on Promise 

### ISSUE THREAD

**Issue by jonatanskogsfors** [jasmine/jasmine#1395]
I noticed a strange behavior when I was testing an Angular/TypeScript application with Jasmine matchers. Matchers that I believed should function similarly was not equally happy about promises.

I simplified the behavior to this:
```typescript
// Won't compile
expect(Promise.resolve(42)).toBe(42);
expect(Promise.resolve(42)).toEqual(42);

// Will compile and asserts without problem
expect(Promise.resolve(42)).not.toBeGreaterThan(42);
expect(Promise.resolve(42)).toBeCloseTo(42);
expect(Promise.resolve(42)).toBeLessThan(43);
```
The compiler tells me that:
```Argument of type '42' is not assignable to parameter of type 'Expected<Promise<number>>'```.

Is this by design or a bug?

### Versions
```
"jasmine-core": "2.6.4",
"typescript": "2.3.4", // (with 'es5' as target)
"angular/core": "4.2.3",
"karma": "1.7.0",
"protractor": "5.1.2"
```
### Test runners
Same behavior in both karma and protractor.

**Comment by slackersoft** [comment]
Jasmine doesn't know anything about Typescript or the typings you may be using, so if you're getting a compiler error it almost certainly isn't Jasmine causing it.

Hope this helps. Thanks for using Jasmine!
