### ISSUE TITLE
Sets & Maps should be compared irrespective of order

### ISSUE THREAD

**Issue by theefer** [jasmine/jasmine#1402]
## Expected Behavior

ES6 Sets and Maps are most often used as unordered sets and maps, and I would expect the following tests to pass:

``` javascript
var setA = new Set([3, 6]);
var setB = new Set([6, 3]);
expect(setA).toEqual(setB); // pass

var mapA = new Map([['a', 3], [6, 1]]);
var mapB = new Map([[6, 1], ['a', 3]]);
expect(mapA).toEqual(mapB); // pass
```

## Current Behavior

Jasmine matchers would fail the tests above, since the insertion order is considered for equality.

I would consider this behaviour a bug, since it's surprising to require the same order. As an analogy, Objects also retain insertion order, but Jasmine matches ignore the insertion order when comparing Objects.

## Possible Solution

Can we change the tests and implementation to ignore insertion order for Sets and Maps, and thus match the expected behaviour?

If not, why not? Is there an alternative approach to providing order-agnostic matchers?

## Suite that reproduces the behavior (for bugs)

The behaviour described above is enforced by [the tests](https://github.com/jasmine/jasmine/blob/master/spec/core/matchers/matchersUtilSpec.js#L410).

**Comment by slackersoft** [comment]
I believe the insertion order was left in the equality comparison simply because it was easier to implement at the time. I would be happy to review a pull request to change the equality comparison to ignore insertion order for Maps and Sets.

Thanks for using Jasmine!

**Comment by theefer** [comment]
Great thanks, I've started working on a PR to make the comparison order-agnostic!
