### ISSUE TITLE
saveArgumentsByValue() saves primitive arguments as Object({ })

### ISSUE THREAD

**Issue by kapil-ms** [jasmine/jasmine#1403]
## Expected Behavior
saveArgumentsByValue() should save arguments of primitive types (passed by value) as it is.

## Current Behavior
saveArgumentsByValue() saves arguments of primitive types (passed by value) as Object({ })

## Suite that reproduces the behavior (for bugs)
```javascript
it('test', () => {
            let service = { test: (x, y)=> { x.key = y; } };
            let testSpy = spyOn(service, 'test').and.callThrough();
            testSpy.calls.saveArgumentsByValue();
            let a = { key: 1 };
            let b = 2;
            service.test(a, b);
            expect(testSpy).toHaveBeenCalledWith(jasmine.objectContaining({ key: 1 }), 2);
        });
```
```
Message:
    Expected spy test to have been called with [ <jasmine.objectContaining(Object({ key: 1 }))>, 2 ] but actual calls were [ Object({ key: 1 }), Object({  }) ].
```

I went ahead and tried to run the condition check at https://github.com/jasmine/jasmine/blob/9cb2f06aa665870dbd5df5fd58a35863738961b3/src/core/CallTracker.js#L14. I got the following results, so this check would always be true, which is incorrect.
```
λ node                                          
> Object.prototype.toString.apply(1)            
'[object Number]'                               
> Object.prototype.toString.apply('adad')       
'[object String]'                                
> Object.prototype.toString.apply({a:1})        
'[object Object]'                              
> Object.prototype.toString.apply(new Date())   
'[object Date]'                                 
```

## Your Environment
* Version used: 2.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 8.2.1
* Operating System and version (desktop or mobile): Windows 10

**Comment by slackersoft** [comment]
This definitely sounds like a bug. Because `Date`s are mutable, I think it make sense to find some way to clone them properly, but numbers and strings are probably find to copy the reference. I'd be happy to review a pull request to fix this.
