### ISSUE TITLE
spyOn removes angular implict injector signiture

### ISSUE THREAD

**Issue by dspattison-google** [jasmine/jasmine#1405]
Using Jasmine 2.6.4; Angular 1.5.12

```
class Foo {
  static bar($rootScope) {
    return true;
  }
}
describe('SpyOn', () => {
  it('static method foo should be called', inject(($injector) => {
       spyOn(Foo, 'bar');
       expect($injector.invoke(Foo.bar)).toBe(true);
     }));
});
```
Fails with this error:
`Error: [$injector:unpr] Unknown provider: aProvider <- a`
https://docs.angularjs.org/error/$injector/unpr?p0=aProvider%20%3C-%20a

For implicit injection, angular calls toString() on the method to get the argument names.   Here is what i see:
`Foo.bar.toString()` -> `function (a) { return fn.apply(this, arguments); }`

I believe the behavior changed with this change: 
https://github.com/jasmine/jasmine/commit/686d8157e57ca306f36ce91b63d38e253d368a2a

I have a workaround, where the test sets `Foo.bar.$inject =[..]` to make injection work.

**Comment by slackersoft** [comment]
I'm afraid I don't have a great solution for this. Before the 2.6 release, Jasmine just replaced the function with one without any explicit arguments. In the 2.6.0 release, we wanted to try to preserve function arity with spies. At first we tried using `eval` but had at least one (#1325) issue with that. After that, we decided to fall back to just declaring the function with explicit param as you see in 686d8157e57ca306f36ce91b63d38e253d368a2a.

This likely never really worked well for spies you expect to get things injected into. This also seems a bit like testing the Angular framework and not necessarily your applications code to have a test like that, so I think that writing a wrapper to `spyOn` you can use to set the `$inject` property on the spy after it is created it probably the way to go.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this since we haven't heard anything back from the community in a while and doesn't sound like an issue with Jasmine itself.

Thanks for using Jasmine!
