### ISSUE TITLE
toThrowError(Error) does not fail the test correctly

### ISSUE THREAD

**Issue by devrafalko** [jasmine/jasmine#1417]
## Suite that reproduces the behavior (for bugs)
This suit checks if the function throws `TypeError`:
```javascript
describe('The function',function(){
  it('should throw TypeError',function(){
    function fun(){
      throw Error('message');
    }
    expect(fun).toThrowError(TypeError,'message');
  });
});
```

This sample works fine, it fails the test and return the message:
`Expected function to throw TypeError with message 'message', but it threw Error with message 'message'.`

This suit  checks if the function throws `Error`:

```javascript
describe('The function',function(){
  it('should throw Error',function(){
    function fun(){
      throw TypeError('message');
    }
    expect(fun).toThrowError(Error,'message');
  });
});
```
And this sample **does not work fine**.

## Expected Behavior
For me, it should fail the test and return the message:
`Expected function to throw Error with message 'message', but it threw TypeError with message 'message'.`

## Current Behavior
It passed the test.

## Your Environment

* Version used: `2.8.0`
* Environment name and version (e.g. Chrome 39, node.js 5.4): `8.3.0`
* Operating System and version (desktop or mobile): `Windows 10`

**Comment by slackersoft** [comment]
Unfortunately, `Error` is the base constructor for most other errors that can be thrown, and thus checking for `Error` as the type will pass for anything that extends that prototype (like `TypeError`). This is advantageous if you have a hierarchy of Error types and you just want to check that one of your `AppError` objects was thrown to make sure you're wrapping everything up, and not letting any native `Error`s through.

This is actually the currently designed behavior and I don't think we're looking to change it. Hope this helps. Thanks for using Jasmine!
