### ISSUE TITLE
[Improvement] Spy on all functions in a class/object

### ISSUE THREAD

**Issue by yxliang01** [jasmine/jasmine#1421]
This is similar to issue #909. But, instead of just being able to have an object with spies on multiple functions with one function call, I would like to have a method like `spyOnAllMethods(Instance of some class/object)` which returns a spy object with all the functions of the provided instance are spies of the original functions.

Thanks!

**Comment by slackersoft** [comment]
I think it might make sense to have an easier way to create a test double for an object. We would be happy to review a pull request that creates something like a `createDouble` that takes a constructor function and returns a new Jasmine spy object for all of the functions on an instance of that.

**Comment by mjeanroy** [comment]
Hi,

It's certainly not perfect, but I already implemented this kind of utility function in a small library: take a look at the description [here](https://github.com/mjeanroy/jasmine-utils#utils-functions).

Not sure to have the time soon, but I would be happy to share it to jasmine core.

**Comment by yxliang01** [comment]
@mjeanroy Nice one! This library looks fantastic. :)

**Comment by bdirito** [comment]
I doesnt *spy* on them but 
``
proxy = new Proxy(
  () => {
    return proxy;
  },
  {
    get: function() {
      return proxy;
    }
  }
)
```
allows the mocking of anything. ie you can `mock.call().it.all.the().way.down()`

**Comment by mohanrao** [comment]
Any plans to improve jasmine like the methods in jasmine-utils developed by @mjeanroy ?

**Comment by aeisenberg** [comment]
I had some free time and added this functionality in the PR above. Is anyone available to take a look at the PR and provide feedback?
