### ISSUE TITLE
Add command line option like --disallow-focused for jasmine which cause fail if there is any focused suites or specs

### ISSUE THREAD

**Issue by profiprog** [jasmine/jasmine#1425]
It would be nice to have option like this, which can be used in pre-commit hook preventing not to commit focused suites or specs.

**Comment by sgravrock** [comment]
I agree. [Actually, the plan is to make that the default behavior rather than an option.](https://www.pivotaltracker.com/story/show/78679648) We're planning to release that along with a number of other breaking changes in Jasmine 3.0.

**Comment by slackersoft** [comment]
Jasmine 3.0 will now treat suites with specs excluded (with `fit`/`fdescribe` or otherwise) to report an overall status of `incomplete` to solve this problem.

Closing. Thanks for using Jasmine!
