### ISSUE TITLE
fake clock does not allow one timer to clear another when they are scheduled for the same time

### ISSUE THREAD

**Issue by voltrevo** [jasmine/jasmine#1426]
The following test should pass, but it fails:

```js
it('one timer can clear another even if they expire concurrently', () => {
  jasmine.clock().install();

  let timerId2;

  setTimeout(() => {
    console.log('timer1');
    expect(timerId2).not.toBeUndefined();
    clearTimeout(timerId2);
  }, 100);

  timerId2 = setTimeout(() => {
    console.log('timer2');
    fail();
  }, 100);

  jasmine.clock().tick(1000);

  jasmine.clock().uninstall();
});
```

I can see an argument that the order of these two might not be guaranteed, or shouldn't be relied upon, so maybe timer2 could fire first so timer1 can't clear it. However, the log output shows that timer1 does in fact fire first, so timer2 was cleared, and should not fire.

Tested using 2.8.0.

**Comment by leahciMic** [comment]
I have confirmed that this is an issue.

I have submitted a PR that adds tests and a fix for this issue.
