### ISSUE TITLE
jasmine.any(Symbol) does not match Symbol instances

### ISSUE THREAD

**Issue by voithos** [jasmine/jasmine#1431]
## Expected Behavior
`symbolObj instanceof Symbol` actually returns `false`, so perhaps this is working as intended (even if a bit non-intuitive). But I'd expect a symbol instance to be treated as equal to `jasmine.any(Symbol)`.

## Current Behavior
Symbol instances are not equal to `jasmine.any(Symbol)`.

## Possible Solution
We could special-case Symbols in the equality checker to work with `.any(Symbol)`.

## Suite that reproduces the behavior (for bugs)
https://codepen.io/anon/pen/rGoXMz

## Your Environment

* Version used: 2.8.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 61
* Operating System and version (desktop or mobile): Linux

**Comment by sgravrock** [comment]
Your proposed solution makes sense to me. I'd be happy to review a pull request that added this feature while preserving compatibility with older IE versions that don't have `Symbol`.
