### ISSUE TITLE
[2.8.0] jasmine.anything() does not match Symbols as keys in Maps

### ISSUE THREAD

**Issue by voithos** [jasmine/jasmine#1432]
## Expected Behavior
A `Map` object with a `Symbol` key is neither null nor undefined, so per the [documentation](https://jasmine.github.io/api/2.8/jasmine.html) for `.anything()`, it should be considered equal to a `Map` object with `jasmine.anything()` as the key.

## Current Behavior
`expect(symbol).toEqual(jasmine.anything())` works fine, but comparing 2 `Map` objects with `Symbol` and `jasmine.anything()` as keys, respectively, fails.

This used to be working in an earlier version of Jasmine, so is likely a regression?

## Suite that reproduces the behavior (for bugs)
https://codepen.io/anon/pen/rGoXMz

## Your Environment

* Version used: 2.8.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 61
* Operating System and version (desktop or mobile): Linux

**Comment by sgravrock** [comment]
I think it's likely that fixing #1431 would take care of this one too. If not, I'd be happy to review a pull request that fixes it.

By the way, I noticed that you've included small run-able demos in this and other issues you'e logged. Thank you for that. It really makes things easier.

**Comment by voithos** [comment]
Thanks for mentioning that - I'm glad that the demos help.

I did a bit of investigation, and it seems like fixing #1431 doesn't actually help here, unfortunately. Even more surprisingly, it seems that it's not just Symbols that are having this issue: as far as I can tell, nothing seems to be matching properly with `jasmine.anything()` as a `Map` key: https://codepen.io/anon/pen/MEdZvN
