### ISSUE TITLE
PhantomJs unable to process jasmine spyOnProperty

### ISSUE THREAD

**Issue by aniruddhadas9** [jasmine/jasmine#1433]
## Are you creating an issue in the correct repository? 
Yes

I am spying on 2 of my properties using `spyOnProperty` and they are working good in `intellij` console for karma testing and debug mode in browser but when I run them using phantomjs they give me error mentioned below.

Code I am using to test 

    const div = fixture.debugElement.query(By.css('.xxxx'));
    div.triggerEventHandler('mouseover', null);
    fixture.detectChanges();
    expect(component.tooltip.isOpen()).toBeFalsy();

    // now spying on to see if its behavior changes
    spyOnProperty(div.nativeElement, 'clientWidth', 'get').and.returnValue(1400);
    spyOnProperty(div.nativeElement, 'scrollWidth', 'get').and.returnValue(2400);

###Error

    PhantomJS 2.1.1 (Mac OS X 0.0.0) EllipsisOverflowComponent should show tooltip on mouse over of the element FAILED
    	Error: clientWidth is not declared configurable in http://localhost:9877node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 4410)
    	http://localhost:9877/_karma_webpack_/main.bundle.js:8593:22
    	invoke@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12949:31
    	onInvoke@http://localhost:9877/_karma_webpack_/vendor.bundle.js:136846:45
    	invoke@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12948:40
    	run@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12699:49
    	http://localhost:9877/_karma_webpack_/vendor.bundle.js:136543:37
    	http://localhost:9877/_karma_webpack_/vendor.bundle.js:183754:31
    	invoke@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12949:31
    	onInvoke@http://localhost:9877/_karma_webpack_/vendor.bundle.js:136080:45
    	onInvoke@http://localhost:9877/_karma_webpack_/vendor.bundle.js:136843:47
    	invoke@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12948:40
    	run@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12699:49
    	http://localhost:9877/_karma_webpack_/vendor.bundle.js:183749:28
    	http://localhost:9877/_karma_webpack_/vendor.bundle.js:136069:46
    	invokeTask@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12982:36
    	runTask@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:12749:57
    	invoke@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:13044:45
    	timer@http://localhost:9877/_karma_webpack_/polyfills.bundle.js:14070:34

   When debugged deep it looks like the error is in these lines and throwing this

      if (!descriptor.configurable) {
        throw new Error(propertyName + ' is not declared configurable');
      }

https://github.com/jasmine/jasmine/blob/master/src/core/SpyRegistry.js#L82-L95
https://github.com/jasmine/jasmine/blob/master/src/core/util.js#L62-L76

## Expected Behavior

Should spy on properties

## Current Behavior

Throwing `Error: clientWidth is not declared configurable in http://localhost:9877node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 4410)`

## Possible Solution

Should work in all condition
## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Context

Unable to run the test

## Your Environment

* Version used: 2
* Environment name and version (e.g. Chrome 39, node.js 5.4): angular cli phantomjs
* Operating System and version (desktop or mobile): mac
* Link to your project: internal

**Comment by sgravrock** [comment]
Unfortunately, I don't see a way to fix this. PhantomJS doesn't allow changing `clientWidth`, which is exactly what `spyOnProperty` needs to do. There are a number of possible workarounds discussed in [the thread about a related Karma issue](https://github.com/karma-runner/karma/issues/438). Hopefully one or more of them will work in your situation.

I'm closing this as there's nothing that Jasmine can do about it.
