### ISSUE TITLE
angular.mock.module causing a break in testing

### ISSUE THREAD

**Issue by bschmitz9** [jasmine/jasmine#1434]
I am attempting to run some tests but keep getting a break in the build, here is my error: 

` C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:443181
        forEach@C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:172615
        loadModules@C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:440391
        createInjector@C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:301303
        WorkFn@C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:164286
        inject@C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:162795
        C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:3371
        TypeError: undefined is not a constructor (evaluating '$compile('<bss></bss>')') in C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js (line 9)
        C:/Users/schmitzb/Projects/RCO/rco-project/test/index.js:9:4189
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 4 of 4 (1 FAILED) (0.109 secs / 0.084 secs)`

Here is the test I am trying to run:

    `import * as angular from 'angular';
     import 'angular-mocks';
     import 'modules/bss/bss.component';

    describe('bssGrid', function () {
	beforeEach(angular.mock.module('app.modules.bss'));

	var $compile: angular.ICompileService;
	var $rootScope: angular.IRootScopeService;
	var $q: angular.IQService;

	beforeEach(function () {
		inject(function (_$compile_, _$rootScope_, _$q_) {
			console.log('hey there');
			$compile = _$compile_;
			$rootScope = _$rootScope_;
			$q = _$q_;
		});
	});

	it('should display the component', function () {
		// Compile a piece of HTML containing the directive
		var element = $compile('<bss></bss>')($rootScope);

		// fire all the watches
		$rootScope.$digest();

		// Check
		var html = element.html();
		expect(html).toBe(true);
	 });
    });`

I am trying to test this component:

     `angular.module('app.modules.bss', [
	   'app.services.bss',
	   'ui.grid',
	  'ui.grid.edit',
	  'ui.grid.treeView',
	  'ui.grid.resizeColumns',
	  'ui.grid.cellNav',
	  'ui.grid.selection',
	  'ui.grid.autoResize',
	  'ui.grid.exporter',
	  'ui.grid.pinning',
	  'app.modules.newVolumeTarget',
	  // 'app.modules.targetDefType',
	  'app.modules.newVolumeType',
	  'app.modules.uigridtemplates.bss-cell',
	  'app.modules.targetDefType.select-formula'
       ]).component('bss', {
		bindings: {},
		controller: BssComponent,
		template: require('./bss.html')
	})`

       `export class BssComponent {
	     public static $inject = ['bssService', 'uiGridTreeBaseService', '$timeout', '$scope', 'ersModalService', '$location', '$window', '$q', '$interval', 'uiGridConstants', '$uibModal'];

               // variables defined here

         constructor(bssService: BssService, uiGridTreeBaseService, $timeout, $scope, ersModalService, $location, $window, $q, $interval, uiGridConstants, $uibModal) {
             // rest of controller code sits here
       }
     }
`

This line of code seems to be breaking my test:

`beforeEach(angular.mock.module('app.modules.bss'));`

When I run this test, it works fine:

     `import * as angular from 'angular';
      import 'angular-mocks';
      import 'components/layout/header-bar/header-bar.component';

    describe('heaaderBar', function() {

	beforeEach(angular.mock.module('app.components.layout.header-bar'));

	var $compile: angular.ICompileService;
	var $rootScope: angular.IRootScopeService;
	var $q: angular.IQService;	

	var mockFilter = function(value) {
		return value;
	};

	beforeEach(function() {
		angular.mock.module(function($provide) {
			$provide.value('translateFilter', mockFilter);
		});
	});

	beforeEach(angular.mock.inject(function(_$compile_, _$rootScope_, _$q_) {
		// The injector unwraps the underscores (_) from around the parameter names when matching
		$compile = _$compile_;
		$rootScope = _$rootScope_;
		$q = _$q_;
	}));

	it('should display the component', function() {
		// Compile a piece of HTML containing the directive
		var element = $compile('<header-bar></header-bar>')($rootScope);

		// fire all the watches
		$rootScope.$digest();

		// Check
		var html = element.html();
		expect(html).toBeTruthy();
	 });	
     });
`

Is there something that has changed that I need to update in regards to using a specific test?

I am using Angular 1.5.5 and Angular Mocks 1.5.5. Thanks!

**Comment by sgravrock** [comment]
This is just an educated guess, but it might work if you do this:

```
beforeEach(function() {
   angular.mock.module('app.modules.bss')
});
```

instead of this:

```
beforeEach(angular.mock.module('app.modules.bss'));
```

I'm guessing that the problem has to do with Angular Mocks rather than Jasmine, so if the above fix doesn't get things working, you might be better off asking for help in an Angular forum.

**Comment by sgravrock** [comment]
Closing as this doesn't appear to be an issue with Jasmine and we haven't heard anything about it in a while.
