### ISSUE TITLE
Expected undefined to equal 'G'. at UserContext.<anonymous> (...\rna-transcription.spec.js:6:39)

### ISSUE THREAD

**Issue by jfmojicas** [jasmine/jasmine#1439]
**# This is my rna-transcription.js**

var DnaTranscriber = function (input) {
this.Dna = input;
};

DnaTranscriber.prototype.toRna = function () {

var DNA = this.Dna;

    if(DNA == 'G'){
          return 'C';
    } else if(DNA == 'C'){
        return 'G';
    } else if(DNA == 'T'){
        return 'A';
    } else if(DNA == 'A'){
        return 'U';
    }
//
};

module.exports = DnaTranscriber;

**# This is rna-transcription.spec.js**

var DnaTranscriber = require('./rna-transcription');
var dnaTranscriber = new DnaTranscriber();

describe('toRna()', function () {
  it('transcribes cytosine to guanine', function () {
    expect(dnaTranscriber.toRna('C')).toEqual('G');
  });

  xit('transcribes guanine to cytosine', function () {
    expect(dnaTranscriber.toRna('G')).toEqual('C');
  });

  xit('transcribes adenine to uracil', function () {
    expect(dnaTranscriber.toRna('A')).toEqual('U');
  });

  xit('transcribes thymine to adenine', function () {
    expect(dnaTranscriber.toRna('T')).toEqual('A');
  });

  xit('transcribes all dna nucleotides to their rna complements', function () {
    expect(dnaTranscriber.toRna('ACGTGGTCTTAA'))
      .toEqual('UGCACCAGAAUU');
  });

  xit('correctly handles completely invalid input', function () {
    expect(function () { dnaTranscriber.toRna('XXX'); }).toThrow(
      new Error('Invalid input')
    );
  });

  xit('correctly handles partially invalid input', function () {
    expect(function () { dnaTranscriber.toRna('ACGTXXXCTTAA'); }).toThrow(
      new Error('Invalid input')
    );
  });
});

I got this failure:

1) toRna() transcribes cytosine to guanine
     Message:
           Expected undefined to equal 'G'. 
     Stack:
        Error: Expected undefined to equal 'G'. at UserContext.<anonymous> (..\rna-transcription.spec.js:6:39)

**Comment by sgravrock** [comment]
It looks like your tests pass the DNA sequence as an argument to `toRna` but the code under test expects it to be a constructor argument. If you fix that, things should work like you expect them to. 

If you need further help writing or debugging your tests, please ask on [the Jasmine mailing list](https://groups.google.com/forum/#!forum/jasmine-js).
