### ISSUE TITLE
Type definition of custom matchers cannot be merged to Matcher<T> interface

### ISSUE THREAD

**Issue by kota65535** [jasmine/jasmine#1441]
I'm working on Typescript. I created following custom matcher.

- matcher.ts
```
export const customMatchers: any = {
  toBeAt: (util, customEqualityTesters) => {
    return {
      compare: (actual, expected) => {
        return {
          pass: actual.isClose(expected, 0.00001)
        }}}}
};

... and this is the type definition to be merged to jasmine.Matcher<T> interface.
```
- matcher.d.ts
```
declare namespace jasmine {
  interface Matchers<T> {
    toBeAt(expected: any): boolean;
  }
```

But typescript compiler complains `TS2551: Property 'toBeAt' does not exist on type 'Matchers<any>'.` why?

**Comment by sgravrock** [comment]
This is just a guess, but did you forget to reference your `matcher.d.ts` file in the file that TypeScript is complaining about? If that's not it, you'll probably be better off asking for help in a TypeScript forum or from whoever provided the Jasmine typings that you're using.

**Comment by sgravrock** [comment]
I'm closing this as it doesn't appear to be an issue with Jasmine itself.
