### ISSUE TITLE
Failing to add custom matchers. v2.8.0

### ISSUE THREAD

**Issue by EugenAz** [jasmine/jasmine#1452]
This is my `test-runner.js` which i run with `npm test` command.
```javascript
const jasmine = new Jasmine({ projectBaseDir: __dirname });
jasmine.loadConfig({});

jasmine.addMatchers(customMatchers);
jasmine.execute(
  glob.sync('tests/e2e/**/*.spec.js')
      .map(p => path.relative(__dirname, p))
);
```

## What is going wrong
I see an error `TypeError: this.jasmine.Expectation.addMatchers is not a function`

## Environment
* jasmine v2.8.0
* node v7.7.3

**Comment by slackersoft** [comment]
Sorry about that. I'm not sure if that function on the jasmine-npm object ever really worked correctly. I've set it up to correctly register matchers with the running jasmine-core environment so they will be available to the underlying suite.

Hope this helps. Thanks for using Jasmine!
