### ISSUE TITLE
Async test passes in 2.6.2 but fails in 2.8.0

### ISSUE THREAD

**Issue by dereklin** [jasmine/jasmine#1455]
This issue is related to https://github.com/nrwl/nx/issues/127

The following test runs fine with version 2.6.2 but fails with version 2.8.0
```
  describe('someEffect', () => {
    it('should work', async () => {
      actions = hot('-a-|', { a: { type: 'LOAD_DATA' } });
      expect(await readAll(effects.loadData)).toEqual([{ type: 'DATA_LOADED', payload: {} }]);
    });
  });
```
In version 2.8.0, I get this error:
```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
Do I need to change any settings to make the test work?

**Comment by sgravrock** [comment]
Chances are that test never actually worked correctly. Until 2.7, Jasmine only supported callback-style asynchronous tests. So an `async` function like the one in your example would've been run synchronously. My guess is that the promise returned by `readAll` was never resolved even in 2.6.2, but you didn't see the problem because Jasmine wasn't waiting for the `async` function to finish the way you expected it to. I hope this helps.

**Comment by dereklin** [comment]
@sgravrock 
And tried to debug it in this repo: https://github.com/dereklin/nx-demo/tree/feature/figuring-out-jasmine-asyc

It's still using 2.6.2

In the debugging code, I do see readAll being resolved.

![jasmine-async](https://user-images.githubusercontent.com/2231799/33509715-e0a4de14-d6b8-11e7-919d-175fe218d6dc.PNG)

Since you said async not available in 2.6.2.  Then this async must be from typescript then.  And async became available since 2.7?  How is it supposed to be used?  Is there a conflict between typescript's async and jasmine async?

**Comment by slackersoft** [comment]
Before 2.7, `it` wouldn't wait for an `async` function to complete (or a Promise), it only worked with the `done` callback version. It's possible that your `readAll` function just takes longer than Jasmine's default timeout interval and now that Jasmine is waiting for it to complete before moving on to the next spec, you're seeing this timeout. 

As a side note, the [`it` function](https://jasmine.github.io/api/2.8/global.html#it) also accepts a custom timeout if this looks like it might solve your problem.

Hope this helps. Thanks for using Jasmine!

**Comment by dereklin** [comment]
OK. With some digging, it seems like the promise that realAll returns might not resolve.  So it will always cause the timeout error
