### ISSUE TITLE
Testing asnyc (Promise) methods in Angular 2 Services

### ISSUE THREAD

**Issue by dasois** [jasmine/jasmine#1459]
This is an interesting problem: I'm trying to test a Service, that uses the Ionic BarcodeScanner. I have a repo based on the [ionic unit-testing repository](https://github.com/ionic-team/ionic-unit-testing-example) in order to try testing. I'm mocking the BarcodeScanner.scan method via spyOn(..).and.callFake(..)

## Expected Behavior

The following test code should work for both components and services.

## Current Behavior

It just works for components.

## Suite that reproduces the behavior (for bugs)

This works (component).
```javascript
it("should be able to set a spy on the scanner and test the component", done => {
        const testBC = "123456";
        const spy = spyOn(TestBed.get(BarcodeScanner), "scan");
        spy.and.callFake(() => {
            return new Promise((resolve, reject) => {
                resolve(testBC);
            })
        });

            component.testScanner().then(res => {
                expect(res).toBe(testBC);
                done();
            }, reason => {
                expect(true).toBe(false);
                done();
            })
    });
```
This does not work (service):
```javascript
it("should be able to set a spy on the scanner and test the service", done => {
        const testBC = "123456";
        const spy = spyOn(TestBed.get(BarcodeScanner), "scan");
        spy.and.callFake(() => {
            return new Promise((resolve, reject) => {
                resolve(testBC);
            })
        });

        inject([TestService], (service) => {
            service.testScanner().then(res => {
                expect(res).not.toBe(testBC);
                done()
            }, reason => {
                expect(true).toBe(false);
                done();
            })
        })
    });
```

## Context

I'm trying to unit test a service that uses the barcode-scanner and then does some stuff with the result..

## Your Environment

* Version used: 2.5.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 62.0
* Operating System and version (desktop or mobile): Arch Linux (desktop)
* Link to your project: https://github.com/ionic-team/ionic-unit-testing-example

**Comment by sgravrock** [comment]
It's hard to tell what's going on from the code sample you posted. Can you create a minimal, self-contained codepen/plunkr/jsfiddle/etc demo that reproduces the problem?

**Comment by slackersoft** [comment]
What in particular is "not working" when you run the code for the service test? I also notice that you're using `inject` in one of the specs (from angular mocks, I assume) which isn't functionality that Jasmine provides, so the problem might also be there.

Hope this helps. Thanks for using Jasmine!

**Comment by dasois** [comment]
I created a [repository](https://github.com/dasois/unittest_async-service-problem.git) that shows the problem in calling.service.spec.ts.

I also noticed, that it works when i omit the done method, even though it works with promises and thus should be asynchronous...

**Comment by dasois** [comment]
I found the problem. I have forgotten to [call the inject function](https://stackoverflow.com/a/39604104/3085821).

Thank you for helping!
