### ISSUE TITLE
What about adding a toBeOfLength() method?

### ISSUE THREAD

**Issue by toubou91** [jasmine/jasmine#1462]
[There are cases](https://github.com/toubou91/ddday/blob/master/spec/ddday-spec.js#L11) where IMHO it would be handier to have a check (i.e. `toBeOfLength(2)` for the fore-mentioned case) regarding the length of a variable, instead of pure equality.

**Comment by slackersoft** [comment]
This just came up in #1446 and I think for now we're trying to keep Jasmine's built-in matcher list smaller. We want to be considered and careful about how we introduce new matchers so they are all documented well, etc.

Closing this. Thanks for using Jasmine!
