### ISSUE TITLE
Show a warning when a beforeEach, afterEach, beforeAll and afterAll block contains tests

### ISSUE THREAD

**Issue by brainlessdeveloper** [jasmine/jasmine#1465]
This is a **feature suggestion**.

## Expected Behavior

Nesting `describe`s, or `it`s, or any expectations inside of a `beforeEach`, `afterEach`, `beforeAll` or `afterAll` should throw a warning or an error that's easy to notice.

## Current Behavior

Currently, nesting tests inside of the aforementioned hooks will go unnoticed and will not throw a warning or an error.

## Possible Solution

I haven't looked at Jasmine's code too much, but I'd love to jump in and solve this myself if it gets approval. 

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
  beforeEach(() => {
    it('renders', () => { // Jasmine won't complain about this test being here
      expect(true).toBe(false)
    })
  })
});
```
## Context

Using jasmine I've come across the situation where I edit my tests and accidentally move blocks or closing curly brackets and end up with a `describe`, an `it` or expectations inside of a `beforeEach` or any of its counterparts.

This goes unnoticed except for the fact that the tests in particular don't run anymore. In my company's projects we've discovered in many occasions that a couple of our tests hadn't been running for several months.

## Your Environment

* Version used: Jasmine 2.8.0
* Environment name and version: Chrome 59.0.3071, Karma 1.7.1

**Comment by sgravrock** [comment]
Jasmine does allow expectations inside before/after functions, which are useful for making sure that shared setup works correctly or verifying other preconditions:

```
describe("When the frobnicator has two bars", function() {
  beforeEach(() => {
    causeTheFrobnicatorToHaveTwoBars();
    expect(frobnicator.bars().length).toEqual(2);
  });

  it("frobnicates both bars", function() {
    // ...
  });
});
```

I think that  PR #1411, which is already merged into master, should cover the rest of the scenarios that you've described.

**Comment by brainlessdeveloper** [comment]
That's great news! I should have read those checks better. Thanks!
