### ISSUE TITLE
Affix function - Pattern attribute with square brackets?

### ISSUE THREAD

**Issue by sreaney1989** [jasmine/jasmine#1468]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Expected Behavior

Expected some sort of escape behaviour - but it is not building the pattern correctly when rendering the test page.

## Current Behavior

Example, using the affix method I have this; 

[id="testInput"][type="text"][required="true"][pattern="[a-zA-Z0-9-]{1,20}"]

but the above does not work, its having a problem with the square brackets within the pattern.

## Possible Solution

Is there any escape mechanism - note I have already tried \, with no joy.

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {

it('should be invalid', function (){
var testInput = 'input[id="testInput"][type="text"][required="true"][pattern="[a-zA-Z0-9-]{1,20}"][value="#123123"]';

affix(testInput);

//does not need an assert, as the pattern does not render correctly.
})
});
```
## Context

Testing element against some real JS, but need to affix elements as part of the DOM - had this working by manually creating the element but wanted to clean it up by using affix.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

localhost.

**Comment by sreaney1989** [comment]
already tried  \ and \\.

**Comment by sgravrock** [comment]
The `affix` method that you're asking about isn't part of Jasmine. I don't know what it is or how to call it. You're probably better off asking for help wherever you got `affix` from.

**Comment by babielmam** [comment]
@sreaney1989 The problem might have to do to with [jasmin-fixture](https://github.com/searls/jasmine-fixture). However, changing jasmine-core version from 2.9.1 to 2.8.0 fixed it (for the moment)
