### ISSUE TITLE
pretty printer doesn't handle symbols as args in toHaveBeenCalledWith

### ISSUE THREAD

**Issue by jamesona** [jasmine/jasmine#1475]
I'm running some tests where a spy on a method is asserting that the method should be called with a symbol and a callback as parameters like:
 ```javascript
const mySymbol = Symbol('test');
expect(mySpy).toHaveBeenCalledWith(mySymbol, jasmine.any(Function))
```
When the test fails, `result.message()` throws an uncaught `TypeError: Cannot convert a Symbol to a string` when the pretty printer tries to output `expectedArgs`
```javascript
function() { return 'Expected spy ' + actual.and.identity() + ' to have been called with ' + j$.pp(expectedArgs) + ' but it was never called.'; }
```
## Expected Behavior
The test log should output
> Expected spy mySpy to have been called with [ Symbol(test), ...

## Current Behavior
The test log shows

> TypeError: Cannot convert a Symbol value to a string
> ```
>TypeError: Cannot convert a Symbol value to a string
>     at Array.toString (native)
>     at StringPrettyPrinter.PrettyPrinter.format (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3681:42)
>     at Object.pp (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3836:25)
>     at Object.result.message (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3288:124)
>     at Expectation.toHaveBeenCalledWith (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:2087:30)
>     at Object.it (http://localhost:9876/_karma_webpack_/main.bundle.js:1514:22)
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:10585:26)
>     at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:46246:39)
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:10584:32)
>     at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:10335:43)
> ```

## Possible Solution
`JSON.stringify()` the `expectedArgs` array, rather than relying on Array.toString to output the array.

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
    it('fails to show symbols', () => {
        const mySymbol = Symbol('test');
        let mySpy = jasmine.createSpy('mySpy');
        expect(mySpy).toHaveBeenCalledWith(mySymbol, jasmine.any(Function));
    })
});
```
## Context
I'm writing an events subsystem where events are uniquely identified by symbols. This events system has an `EventService.subscribe()` method, that expects a discriminating symbol and a callback.
In writing unit tests for other parts of the app that should be subscribing to events, I check that a particular symbol was the symbol passed into the subscribe method.
It's worth pointing out that if I were calling 
```javascript
expect(mySpy).toHaveBeenCalledWith({
    type: mySymbol,
    callback: jasmine.any(Function)
})
```
it would work (and does, in a different method and tests relating to it). This is only a problem when the symbol is a separate parameter.

## Your Environment
```json
"devDependencies": {
    "@angular/cli": "1.1.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-mocha-reporter": "^2.2.3",
    "karma-phantomjs-launcher": "^1.0.4",
    "ng2-mock-component": "0.0.6",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
```
```bash
$ cat /etc/linuxmint/info
RELEASE=18.1
CODENAME=serena
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.1 Serena"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_serena_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_serena_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.1 Cinnamon 64-bit

```

**Comment by slackersoft** [comment]
What version of Jasmine are you running? If you're using the default HTML reporter, it should be in the top left corner of the results page. I just ran your same spec in Jasmine 2.8.0 and it looks like it's producing the correct output there, so you might try updating your version of Jasmine.

Hope this helps. Thanks for using Jasmine!

**Comment by jamesona** [comment]
Ah, you're correct. Updating to 2.8.0 fixes it. Most of this app is just a default angular-cli build of angular 4.x, so I don't often look at updating my deps. Thanks for looking!
