### ISSUE TITLE
List of specs are no longer shown after upgrading to 2.8 from 2.4

### ISSUE THREAD

**Issue by applecool** [jasmine/jasmine#1481]
## Expected Behavior
In 2.4.1, if one gives an invalid spec name in the url, all the specs were listed in the browser with their appropriate links which would allow the user to click on any specific test spec to run that spec.

## Current Behavior
In 2.8, if one gives an invalid spec name in the url, the specs are not listed in the browser. This is inconvenient as one has to specifically enter the whole spec name in the url ` ?spec="this spec name is longer than i expected"`.  

## Your Environment
* Version used: 2.8
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome: Version 63, Node: Version 7.9.0
* Operating System and version (desktop or mobile): Mac OS Sierra 10.12.6

**Comment by applecool** [comment]
I am not really sure if this is an expected behavior and has been purposefully designed this way. If it is, then I don't have any complaints. But would be nice, if there is a way to make those specs listed the way they used to be.

**Comment by slackersoft** [comment]
This functionality was introduced in [Jasmine 2.6](https://github.com/jasmine/jasmine/blob/master/release_notes/2.6.0.md) (#1046). If you need the full list of specs, you should see that if you run all of your specs.

Additionally, I would be happy to review a pull request that only filtered out specs from the HtmlReporter if any were actually run.

Hope this helps. Thanks for using Jasmine!

**Comment by applecool** [comment]
Right. When the specs are ran, at the end, I can see the list of specs. Will try to look into a fix :)

**Comment by sgravrock** [comment]
I'm closing this due to prolonged inactivity, but anyone who wants the proposed change enough to implement it should still feel free to submit a PR.
