### ISSUE TITLE
beforeAll runs after IT statement in my jasmine test

### ISSUE THREAD

**Issue by bitquality** [jasmine/jasmine#1483]
## Issue
In my node.js integration testing project , i have a config file defined with certain parameters.
I need to read those values in my beforeAll but my describe, it statements are executed first then the beforeAll.

         ` var environment;
   beforeAll( () => {
    console.log(’Step1………..: ');

    browser.getProcessedConfig().then((config) => {
        environment = config.environment ;
        console.log(‘Step2: ' + environment);
    });

})

describe('*************************Executing TestSuite************************', function () {

    console.log(‘Step3: ');
    console.log(environment);

   it('value1 should be not null’, (done) => {
      // code to use environment
     done();
  }

});`

## Expected Behavior
Step1
Step 2
Step 3

I want to use the value of environment before it block and inside it block . But at this moment i only see undefined value being refered by the code in it block.

## Current Behavior
Step 3
undefined
Step 1
Step 2

## Context
Integration Testing

## Your Environment
Mac, Visual Studio Code
    "jasmine-node": "^1.14.5",
    "jasmine-data-provider": "^2.2.0",
    "jasmine-expect": "^3.7.1",
    "jasmine-json-test-reporter": "^1.0.0-beta",
    "jasmine-reporters": "^2.2.0",
    "jasmine-screenshot-reporter": "0.0.6"
    "protractor"

**Comment by slackersoft** [comment]
It looks like your `beforeAll` function is meant to be executed asynchronously (since you're using a Promise), but Jasmine doesn't know to wait. If you `return` the promise from the `beforeAll` Jasmine should correctly detect the asynchronous nature and wait until it is complete to move on. Also, see the [docs for async support](https://jasmine.github.io/edge/introduction#section-Asynchronous_Support) for more info.

Hope this helps. Thanks for using Jasmine!

**Comment by bitquality** [comment]
As per your suggestion i tried to do the below but it still didn't work.

`beforeAll( () => {

    console.log(’Step1………..: ');

    return new Promise(resolve => {
        console.log('browser config 113...........: ');

       browser.getProcessedConfig().then((config) => {
           environment = config.environment ;
           console.log(‘Step2: ' + environment);
           resolve();
       });
     
})`

I tried using done keyword like below inside my describe but still no use. It still executed it block first. 

`beforeEach(function(done) {
      browser.getProcessedConfig().then((config) => {
           environment = config.environment ;
           console.log(‘Step4: ' + environment);
           resolve();
       });
     
    });`


Is it a library issue ? Because i had jasmine-node and jasmine earlier but now i only have jasmine-node lib.

Please note that my it block uses done keyword too.

**Comment by mattcheah** [comment]
@bitquality Did you ever get your code working? I have a similar issue.

**Comment by santimendoza** [comment]
I am having this issue too, using async/await. Any help or update about this?

**Comment by slackersoft** [comment]
As far as I can tell the jasmine-node library isn't being maintained anymore, the last commit is in 2014, and I'm not sure which version of Jasmine it is tied to. Jasmine added the new support for Promises and async/await in 2.7, so you'll need to make sure you're using a new enough version of Jasmine to use that feature. Based on the original comment, I would expect something like the following to work:

```javascript
beforeAll(function() {
  return browser.getProcessedConfig().then((config) => {
    environment = config.environment;
    console.log('Step2: ' + environment);
  });
});
```
