### ISSUE TITLE
Missing custom message with toEqual(..) Failure

### ISSUE THREAD

**Issue by AnmAtAnm** [jasmine/jasmine#1484]
## Expected Behavior

The custom messages appended to `.toEqual(..)` should be included in results / logs upon expectation failure. The below suite should emit both `'GOOD: ...'` and `'BAD: ...'` messages.

## Current Behavior

The 'BAD: ...' custom messages associated with `.toEqual(..)` is not present. The message for that expectation only includes the results from `diffBuilder.getMessage()`.  See this live here: https://codepen.io/AnmAtAnm/pen/PEVPBO

This stopped working around v2.6.0.

## Possible Solution

I don't know whether this is the responsibility of `wrapCompare(..)` or `.toEqual(..)`. `wrapCompare(..)` has a `var message` that is never sliced from the `args` array. Instead, it is assigned the matcher's results, which received the full args array.

## Suite that reproduces the behavior (for bugs)

https://codepen.io/AnmAtAnm/pen/PEVPBO

```javascript
describe("Expect test's custom message", function() {
  it("toEqual example", function() {
    expect(0).toEqual(1,
        'BAD: This message does not appear')
  });
  it("toBeGreater example", function() {
    expect(0).toBeGreaterThan(1,
        'GOOD: This message appears')
  });
});
```

## Context
Unable to annotate my errors with meaningful logs.

## Your Environment

* Version used: 2.9.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 63
* Operating System and version (desktop or mobile): Mac dekstop

**Comment by AnmAtAnm** [comment]
The following addition to `wrapCompare(..)` appears to do it:

```javascript
if (args[2]) {
  message += ((message.indexOf('\n') === -1) ? ' \'' : '\n\'');
  if (Object.prototype.toString.apply(args[2]) === '[object Function]') {
    message += args[2]() + '\'';
  } else {
    message = args[2] + '\'';
  }
}
```

However, the initial assignments to `expected` and `message` don't make sense to me:

```js
var args = Array.prototype.slice.call(arguments, 0),
  expected = args.slice(0),
  message = '';
```

...and fixing them would probably lead to a slightly different solution.

**Comment by AnmAtAnm** [comment]
Dupe of #1457. Can't say I agree with the authors on closing that issue, or the root feature request (#641). Three+ years later, people are still replying in request of it, clear evidence there are numerous (probably hundreds. thousands?) of users who want this behavior with very reasonable use cases.

The recommended alternative of implementing custom matcher is significantly more code, more complexity, and more effort. When one considers that a significant number of use-cases are probably one-off efforts (a particular rationale only needs to be tested once or a small handful of time in its codebase), the short-hand feature makes a world of sense.

Not supporting such a feature for four years, one that is standard in most assert libraries, is incredibly arrogant. The rationale of not expanding the API falls flat when one realizes we are talking about one method (`.because()`, #641) or one parameter (`expectationFailOutput`).

**Comment by sgravrock** [comment]
@AnmAtAnm, please review the project's [Code of Conduct](https://github.com/jasmine/jasmine/blob/master/CODE_OF_CONDUCT.md) before participating further. We welcome and value feedback about the direction of Jasmine, but not personal attacks or other conduct that would be inappropriate in a professional setting.

This is one of those features that seems easy but turns out to be quite a bit more challenging once you dig into it. That said, I'd be happy to review a pull request that solves the problem without also breaking existing custom matchers or making it more difficult to correctly write custom matchers.

**Comment by antonmitsev** [comment]
Hi guys,
This issue still persists in version 3.3.0. Any news/ideas on it?
How can a guy like me contribute to the project?
Thanks,
Anton

**Comment by slackersoft** [comment]
Please see https://jasmine.github.io/api/edge/matchers.html#withContext
