### ISSUE TITLE
Confusing error message with toEqual(array) when array is too long.

### ISSUE THREAD

**Issue by AnmAtAnm** [jasmine/jasmine#1485]
## Expected Behavior

When testing `expect(array).toEqual(shorterArray);`, replace

```
Expected $[n] = 'extra array element' to equal undefined.
```

with

```
Unexpected $[n] = 'extra array element'
```

To remove the confusing (even though technically accurate) reference `undefined`.

## Current Behavior

It outputs 

```
Expected $[n] = ... to equal undefined.
```

which implies some `$[n]` was expected, when most likely the actual array was just longer than the expected.

## Possible Solution

```
Unexpected $[n] = 'extra array element'
```

## Suite that reproduces the behavior (for bugs)

https://codepen.io/AnmAtAnm/pen/ppGgjX

```javascript
describe("Expect a shorter array error message", function() {
  it("example .toEqual(shorterArray)", function() {
    expect(['example']).toEqual([]);
  });
});
```

## Context

Trying to grok the meaning of my errors quickly.

## Your Environment

* Version used: v2.9.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 63
* Operating System and version (desktop or mobile): Mac laptop

**Comment by slackersoft** [comment]
This proposal seems reasonable. We would be happy to review a pull request that changes the message for extra elements at the _end_ of an array without changing the message for one in the middle.

This means that `expect([1, 2, 3]).toEqual([1, undefined, 3])` should still produce the existing failure message.
