### ISSUE TITLE
Executing `beforeEach` outside `describe` block fails since 2.9.0

### ISSUE THREAD

**Issue by mjeanroy** [jasmine/jasmine#1486]
Hi,

## Context

Since version 2.9.0, any `beforeEach` / `afterEach` functions must be put inside a `describe` block. Even if it was not really documented, it has always been possible to define a `beforeEach` function outside any `describe` and it was executed before any tests in the entire test suite.

This was really useful to:
- Execute some initialization code before any test, without declaring it in every `describe` block.
- Declaring additional matcher that would become available in the entire test suite.
- Etc.

For example, I used to mock clock using `jasmine.clock().install()` in a "global" `beforeEach` and uninstalling it in a global `afterEach`.

I think this change comes from: #1411.

Not sure if it was intended. If so: what do you suggest to have initialization code shared across **all** `describe` blocks?

## Expected Behavior
- Do not fail if a `beforeEach` function is defined outside any `describe` block.

## Current Behavior
- Having a `beforeEach` function outside any `describe` block fail with this error: `Error: 'beforeEach' should only be used in 'describe' function`.

## My Environment
* Version used: 2.9.0 / 2.9.1

**Comment by sgravrock** [comment]
Top-level `beforeEach` ought to work, for the reasons that you describe. I'm not immediately able to reproduce the problem. Can you provide example code that demonstrates it?

**Comment by mjeanroy** [comment]
Ok, that was a mistake in my code, that just throw now because of the new check in Jasmine. Really sorry, and thanks for Jasmine!

**Comment by sgravrock** [comment]
No worries. I'd rather see a false alarm than have a bug like the one you thought you saw get missed.

**Comment by tomas-cani** [comment]
I'm having the same error when using reusable describes like [here](https://stackoverflow.com/a/6440097/5384592). Tests using the reusable functions are failing now, any ideas on how to accomplish something similar with the new check?

**Comment by slackersoft** [comment]
@tomas-cani can you provide a small sample suite and what types of failures you're seeing? This will help us diagnose the underlying cause. When I put together a _super_ simple version with a shared context, I'm not seeing any problems.

Hope this helps. Thanks for using Jasmine!

**Comment by BrainforgeUK** [comment]
Got same issue here:
https://github.com/joomla/joomla-cms/pull/20152#issuecomment-412212229

How can I resolve it?
Checks applied to Joomla pull request, cannot see how my changes would be relevant.

**Comment by slackersoft** [comment]
It looks like you got unlucky in the base for your PR to Joomla. That spec file is indeed using invalid Jasmine syntax, having a `beforeAll` nested inside an `it`. These tests likely didn't work correctly for them before, and it looks like things have been moved around in the Joomla repository such that I can't figure out where the current version of that file would be in the branch you're trying to merge into (4.0-dev). If you want to fix the error for your particular PR and let the Joomla folks figure out what the long term strategy is there, you should be able to change the `it` on line 192 to a `describe` and update your PR.

Hope this helps.
