### ISSUE TITLE
Marking a successful test as failed in case of exception

### ISSUE THREAD

**Issue by amitguptagwl** [jasmine/jasmine#1489]
I'm writing a test to check exception scenario

```
it('would not be started when the port is not accessible', function (done) {
        var server = require('.././lib/server');
        server.setup({ "-d" : path.join(__dirname, "spec/test_assets"), "-p" : "8"});
        server.on("start",function(){
            fail("Not expected");
            done();
        });
        server.on("error",function(err){
            expect(err.code).toBe('EACCES');
            done();
        });
        server.on("request",function(err){
            fail("Not expected");
            done();
        });
        server.start();
    });
```

I have confirmed that `expect(err.code).toBe('EACCES');` is passed and `done()` is being called in above test.

## Expected Behavior
So It should mark the test successful.

## Current Behavior
But It is marking it failed and printing the error on console.

```
1) server would not be started when the port is not accessible
  Message:
    Error: EACCES: Permission denied for use of port 8
  Stack:
    Error: EACCES: Permission denied for use of port 8
        at networkErrHandler (/home/amit/git/stubmatic/lib/server.js:100:8)
        at Server.server.on.err (/home/amit/git/stubmatic/lib/server.js:73:3)
        at emitOne (events.js:115:13)
        at Server.emit (events.js:210:7)
        at emitErrorNT (net.js:1325:8)
        at _combinedTickCallback (internal/process/next_tick.js:102:11)
        at process._tickCallback (internal/process/next_tick.js:161:9)
        at Function.Module.runMain (module.js:607:11)
        at startup (bootstrap_node.js:158:16)
        at bootstrap_node.js:575:3

```

Hence I have changed the test in following way.

```
it('would not be started when the port is not accessible', function () {
        var server = require('.././lib/server');
        server.setup({ "-d" : path.join(__dirname, "spec/test_assets"), "-p" : "8"});
        expect(function(){
            server.start();
        }).toThrow("EACCES: Permission denied for use of port 8");
    });
```

But now it fails saying no exception is thrown.

## Your Environment

* Version used: 2.9.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 8.0
* Operating System and version (desktop or mobile): ubuntu 17.10
* Link to your project: https://github.com/NaturalIntelligence/Stubmatic

**Comment by slackersoft** [comment]
More recent versions of Jasmine will trap global unhandled errors that occur during spec execution and report them to the current running spec. My guess is that this is the functionality that is causing you difficulty.

If your code under test actually causes an unhandled error to be thrown (say by trying to open a port it isn't allowed to), then Jasmine will get that in `global.onerror` and route it back through to your spec. If your server does this asynchronously (after the call to `start()`) has returned, then Jasmine's `toThrow` matchers won't work, because `start` is no longer on the call stack when the Error is thrown.

Hope this helps. Thanks for using Jasmine!

**Comment by amitguptagwl** [comment]
Thanks @slackersoft for your kind response. Previously I was throwing error in some certain cases when server doesn't start, to inform the user. However due to the jasmine changes Now I'm just logging it with the reason instead of throwing the error. 

In short, thanks it made my build green.
