### ISSUE TITLE
Unable to query input element in Shadow DOM of Polymer 2 component inside Angular page

### ISSUE THREAD

**Issue by msbasanth** [jasmine/jasmine#1490]
Hi,

I am working with some Polymer 2 components which implement ShadowDOM v1 spec and I need to select elements (e.g. input) inside their shadowRoots to run unit tests and few integration tests using Jasmine.

## Expected Behavior
W should be able to access Shadow DOM elements using Jasmine selectors.
var allInputs =  fixture.debugElement.queryAll(By.css('input'));

![shadowroot](https://user-images.githubusercontent.com/17777813/35608287-74634628-067e-11e8-9ecc-56df34fc2906.png)

## Current Behavior
Unable to access inside of Shadow DOM from unit test. We should have query selectors to query shadow DOM elements.

## Suite that reproduces the behavior (for bugs)
```javascript
describe('AppComponent', () => {
  let component: AppComponent;
  let fixture: ComponentFixture<AppComponent>;
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        FormsModule
      ],
      schemas: [CUSTOM_ELEMENTS_SCHEMA]
    }).compileComponents();
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
  }));
  it('should have default value set for first name and last name', () => {
    fixture.detectChanges();
    var allInputs =  fixture.debugElement.queryAll(By.css('input'));
    var firstNameInput = allInputs[0].nativeElement;
    var lastNameInput = allInputs[1].nativeElement;
    expect(firstNameInput.value).toBe('');
    expect(lastNameInput.value).toBe('');
  });
});
```
What is the best way I can test the Polymer Web Components inside Angular page?
Or whether we have a mechanism to mock web components while unit testing Angular component?

**My environment:**

Angular CLI: 1.6.4
Node: 6.10.0
Angular: 5.2.0

"devDependencies": {
    "karma-jasmine": "^0.3.6",
     "jasmine": "^2.4.1",
    "jasmine-core": "^2.2.0"
}

**Comment by slackersoft** [comment]
Unfortunately, I don't think any of the components you mention having issues with are part of Jasmine. Jasmine doesn't and shouldn't know anything about which javascript framework you're using or how it gets hooked up, it just runs your javascript specs. You might have better luck asking in a Polymer and/or Angular forum for help with test setup.

Hope this helps. Thanks for using Jasmine!

**Comment by msbasanth** [comment]
thanks for the quick reply
