### ISSUE TITLE
Following Error shown When I Execute the test cases parallely with concurrently package Error: timeout - async callback was not invoked within timeout specified by jasmine.default_timeout_interval.

### ISSUE THREAD

**Issue by thirusabari** [jasmine/jasmine#1492]
Hai,

I'm new to TDD. Currently we have 3000 more test cases in our project.  If we run the coverage, these 3000 cases were executed parallell with [npm-concurrently  package](https://www.npmjs.com/package/concurrently). I have configured my test cases folder structure into 10 subFolders.  For Example, Consider, Two Main Folders A and B is here.  Folder A has 5 subFolders and Folder B had  5 Sub Folders. Each SubFolders has minimum 5 count of spec files. I had configured separate karma configuration file for each subFolders and configured the separate gulp tasks for each sub folders too. We are using [Chrome Headless Browser](https://developers.google.com/web/updates/2017/04/headless-chrome) to run the test cases. The Sample **Karma Configuration** file is given below for your reference,

        `module.exports = function (config) {
         config.set({
        browsers: ['Chrome', 'IE', 'Firefox', 'ChromeHeadless'],
        frameworks: ['jquery-1.10.2', 'jasmine-jquery', 'jasmine'],
         files: [   
                'js/src/**/**/*.css',
               'js/src/assets/scripts/jquery-1.10.2.min.js',
               'js/src/assets/scripts/jquery.easing.1.3.min.js',
               'js/src/**/**/*.js',
               {
                 pattern: 'js/**/**/Index.html',
                 watched: true,
                 served: true,
                 included: false
               }
              ],
             concurrency: Infinity,
             browserDisconnectTolerance: 3,
             browserNoActivityTimeout: 1000000,
             browserDisconnectTimeout: 1000000,
             captureTimeout: 1000000,
             retryLimit: 5,
           htmlDetailed: {
                   splitResults: false,
                  dir: 'reoports/nunit/one',
                  fileName: 'TestResult.html',
                  autoReload: false
            },
           coverageReporter: {
               type: "html",
                   check: {
                     each: {
                    statements: 0,
                    branches: 0,
                    functions: 0,
                    lines: 0
                 }
              }
             }
        });
      }; `

## Sample Gulp Configuration file is give below,

         `gulp.task('one', function (done) {
            return new Server({
               configFile: __dirname + '/karma.conf.one.js',
               action: 'run',
               singleRun: true,
               preprocessors: {
            'js/src/**/**/*.js': ['coverage'] 
               },
              reporters: ['progress', 'htmlDetailed', 'coverage'],
              coverageReporter: {
              dir: './reports',
              subdir: "reporters/new",
              reporters: [
                 { type: 'json', file: "one.json" }
              ]
           },
          customLaunchers: {
            MyHeadlessChrome_Desktop: {
                base: 'ChromeHeadless',
                flags: ['--disable-translate', '--disable-extensions', '--remote-debugging-port=9223', "--
                headless", "--disable-gpu", "--window-size=1228,1000"],
              },
            },
           browsers: ['MyHeadlessChrome']
          }, done).start();
       });
       `
### My Package.JSON File is given below for your reference:-

        `{
         "name": "gulp-karma",
         "version": "1.0.0",
          "description": "",
          "scripts": {
          "test": "gulp test",
          "ci": "gulp ci",
          "coverage": "concurrently \"gulp one\" \"gulp two\" \"gulp three\" \"gulp four\" \"gulp five\" 
           \"gulp six\" \"gulp seven\" \"gulp eight\" \"gulp nine\" \"gulp ten\"",
          "lint": "gulp runeslint"
         },
      "devDependencies": {
       "concurrently": "^3.5.1",
        "eslint-html-reporter": "^0.5.2",
        "ghooks": "^2.0.0",
        "gulp": "^3.9.1",
        "gulp-csslint": "^1.0.0",
        "gulp-eslint": "^2.0.0",
        "gulp-jasmine": "^3.0.0",
        "gulp-lesshint": "^4.0.0",
        "gulp-shell": "^0.6.5",
        "istanbul-combine": "^0.3.0",
        "jasmine": "^2.9.0",
        "jasmine-core": "^2.9.1",
        "jasmine-jquery": "^2.1.1",
       "jquery-1x": "^1.12.1",
       "karma": "^2.0.0",
       "karma-chrome-launcher": "^2.2.0",
       "karma-coverage": "^1.1.1",
       "karma-firefox-launcher": "^1.0.1",
      "karma-html-detailed-reporter": "^1.1.21",
       "karma-ie-launcher": "^1.0.0",
       "karma-jasmine": "^1.1.1",
       "karma-jasmine-jquery-2": "^0.1.1",
       "karma-jquery": "^0.2.2",
       "karma-safari-launcher": "^1.0.0",
       "clean-dir": "^1.0.3"
       },
     `

**My Sample Test Case is given below for your reference**

       `describe("Checking AsynC Call", function () {
        var originalTimeout;
         beforeEach(function (done) {
         originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
         jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000;
         });
        it("Ensure element a is visible", function 
        (done) {
                      var num = document.find(".number");
			num.trigger('click');
			setTimeout(function(){
			expect(document.find("a").is(":visible")).toBeTruthy();
			done();
			},1000);
           });
        it("Ensure element b is visible", function 
        (done) {
                      var num = document.find(".num");
			num.trigger('click');
			setTimeout(function(){
			expect(document.find("b").is(":visible")).toBeTruthy();
			done();
			},5000);
           });

           afterEach(function (done) {
            jasmine.DEFAULT_TIMEOUT_INTERVAL = originalTimeout;
            done();
          });
        });`

If i set the **jasmine.DEFAULT_TIMEOUT_INTERVAL value** into **Math.pow(2, 31) - 1** value also, This "Error-Async callback was not invoked within the jasmine.DEFAULT_TIMEOUT_INTERVAL" exception was shown?

Can anybody tell me the solution for above issue?

And Tell me, what is the maximum timeout interval, we can set in **jasmine.DEFAULT_TIMEOUT_INTERVAL" in this settings?

Regards,
Thiru

**Comment by slackersoft** [comment]
It looks like your `beforeEach` function is receiving a `done` callback but never invoking it, which is probably causing the timeout error. Additionally, that `beforeEach` probably doesn't need to be asynchronous and doesn't really need the `done` callback at all.

Jasmine 2.9 should also allow you to pass an override to the default timeout to the individual asynchronous spec, instead of saving and resetting the global value. See: [it](https://jasmine.github.io/api/edge/global.html#it)

**Comment by thirusabari** [comment]
Hai @slackersoft , I will check and update you. And Thanks for the Comment

**Comment by thirusabari** [comment]
Hai @slackersoft , FYI, I had posted my questions with some mistakes, My beforeEach contains, the following block of code,

`beforeEach(function (done) {
            LoadData(done, {
                Data: Request,
                Value: "string"
            });
        });`

**Comment by slackersoft** [comment]
If you're seeing a timeout error in Jasmine, it is probably because you're not completing your asynchronous work before the timeout expires. Make sure your `LoadData` function is actually calling `done` and that it is doing soon before the timeout runs out.

Hope this helps. Thanks for using Jasmine!

**Comment by JESii** [comment]
One more thing that helped me: when you get the timeout error, check your console log to see what's going on. In my experience, there's usually an exception that interrupted the workflow and so you never got to the done() method.

**Comment by slackersoft** [comment]
Closing this since this error is a feature of Jasmine to make sure async specs don't go on forever. Please let us know if you have any other information that looks like Jasmine might be giving the error incorrectly.

**Comment by kmeeraj** [comment]
just don't forget to add done method inside the test case;

 describe("long asynchronous specs", function() {
    var originalTimeout;
    beforeEach(function() {
      originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
      jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
    });

    it("takes a long time", function(done) {
      setTimeout(function() {
        done();
      }, 9000);
    });

    afterEach(function() {
      jasmine.DEFAULT_TIMEOUT_INTERVAL = originalTimeout;
    });
  });
});
