### ISSUE TITLE
You need to include some adapter that implements __karma__.start method

### ISSUE THREAD

**Issue by julmot** [jasmine/jasmine#1495]
I'm coming here since I received a PR to update jasmine: https://github.com/julmot/mark.js/pull/196

Since this update, only in IE9 it throws an error:

```
You need to include some adapter that implements __karma__.start method
```

https://travis-ci.org/julmot/mark.js/builds/338176986#L3394

What's causing the issue? Is it a bug of jasmine when used in combination with Karma or an issue with the environment of mark.js?

![ie9-error](https://user-images.githubusercontent.com/8310677/35907929-96a7c90e-0bef-11e8-8f0e-23d13f59108b.png)

## Your Environment

* Version used: 3.0.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): IE9
* Operating System and version (desktop or mobile): Windows 7
* Link to your project: https://github.com/julmot/mark.js

**Comment by slackersoft** [comment]
Sorry about that. Somehow in all the internal deprecation warnings, I missed the supported browser (and other environment) changes. Jasmine 3.0 will no longer support IE 8 or 9. The market is too small and the workarounds too many.

Hope this helps. Thanks for using Jasmine!

**Comment by julmot** [comment]
Thanks for this information. I won't update to v3 though, as IE9 is still important in some industries.
