### ISSUE TITLE
Jasmine 3.0.0 breaks Angular 5.2 tests

### ISSUE THREAD

**Issue by rnadler** [jasmine/jasmine#1496]
## Expected Behavior
Tests work with Jasmine 2.9.1

## Current Behavior
With Jasmine 3.0.0, **all** tests fail with this error:
```
TypeError: Cannot read property 'run' of null
  at <Jasmine>
  at UserContext.<anonymous> home/bobn/Projects/app/node_modules/zone.js/dist/jasmine-patch.js:106:1)
  at <Jasmine>
  at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:421:1)
  at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:188:1)
  at drainMicroTaskQueue home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:595:1)
  at <Jasmine>
```
Same behavior using Angular 5.2.3 and 5.2.4.
It seems as though **jasmine-patch.js** is no longer compatible with Jasmine 3.0.0.
## Your Environment

Ubuntu 16.04
Chrome 64.0.3282 (Linux)
`ng -v`
> Angular CLI: 1.6.7
> Node: 8.8.1
> OS: linux x64
> Angular: 5.2.4
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> <nowiki>@</nowiki>angular/cli: 1.6.7
> <nowiki>@</nowiki>angular-devkit/build-optimizer: 0.0.42
> <nowiki>@</nowiki>angular-devkit/core: 0.0.29
> <nowiki>@</nowiki>angular-devkit/schematics: 0.0.52
> <nowiki>@</nowiki>ngtools/json-schema: 1.1.0
> <nowiki>@</nowiki>ngtools/webpack: 1.9.7
> <nowiki>@</nowiki>schematics/angular: 0.1.17
> typescript: 2.7.1
> webpack: 3.10.0

**Comment by slackersoft** [comment]
`jasmine-patch.js` is not supplied by Jasmine, it looks like it's probably zone.js based on the stack trace. I don't know what zone.js is trying to patch into Jasmine, but if it is reaching past what Jasmine considers to be its external interface various things could have changed to cause issues like this.

You're probably better off asking this [over there](https://github.com/angular/zone.js).

Hope this helps. Thanks for using Jasmine!

**Comment by JiaLiPassion** [comment]
@rnadler , you can close the issue here, and I will provide a patch from `zone.js`.

**Comment by slackersoft** [comment]
Thanks! Closing this.

**Comment by corvinrok** [comment]
Why is this closed? The issue still exists in the latest revision of stable releases from all components notes (zone.js, rxjs, jasmine).

**Comment by slackersoft** [comment]
The other library(s) were patching the internals of Jasmine, and the patches broke with the new, major version, release of Jasmine. Thus this isn't an issue with Jasmine itself, and this issue was closed.
