### ISSUE TITLE
v2.99 catchExceptions deprecation warning is unavoidable

### ISSUE THREAD

**Issue by bdwain** [jasmine/jasmine#1497]
## Are you creating an issue in the correct repository?
yes

## Expected Behavior
If I am not expliclty using catchExceptions, I should not see the deprecation warning

## Current Behavior
I see the deprecation warning even though I am not using catchExceptions explicitly

## Possible Solution
The [catchExceptions function](https://github.com/jasmine/jasmine/blob/4530f9431fbff52f8e18a984b8b7faffec39cb13/lib/jasmine-core/jasmine.js#L905) is called uncondtionally from [here](https://github.com/jasmine/jasmine/blob/4530f9431fbff52f8e18a984b8b7faffec39cb13/lib/jasmine-core/boot/boot.js#L55), and if the query parameter is not provided, defaults the value to true.

It seems like the value should default to false, and that the warning in the catchExceptions function should only be displayed if the value is truthy. If the catchExceptions function needs to be enabled by default and that a change to that would be breaking, that's fine, but it seems like odd that the deprecation warning would show up if you didn't opt in to the feature. Because you have to explicitly opt out of something you never opted in to to get rid of the warning. 

## Context
I am just running jasmine in a browser and would like to get rid of the deprecation warning.

## Your Environment

* Version used: 2.99
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 64 node 8.9
* Operating System and version (desktop or mobile): OS X High Sierra

**Comment by slackersoft** [comment]
You're totally correct, `catchExceptions` should only be printing the deprecation warning if you turn it off, as that is the part that is deprecated. I'm going to release 2.99.1 shortly to fix this.

**Comment by bdwain** [comment]
thanks for the quick response!
