### ISSUE TITLE
Unable to bundle jasmine-core v2.99.1

### ISSUE THREAD

**Issue by camertron** [jasmine/jasmine#1502]
## Are you creating an issue in the correct repository?
yes?

## Expected Behavior
I should be able to run `bundle install` when Jasmine is in my gemfile.

## Current Behavior
I'm seeing the following error that did _not_ happen with v2.99.0:

```
Installing jasmine-core 2.99.1 (was 2.99.0)
Errno::EEXIST: File exists @ dir_s_mkdir - /Users/cameron/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/jasmine-core-2.99.1/lib/jasmine-core/spec
An error occurred while installing jasmine-core (2.99.1), and Bundler cannot continue.
Make sure that `gem install jasmine-core -v '2.99.1'` succeeds before bundling.
```

## Possible Solution
Is jasmine-core or jasmine-gem trying to create a directory that already exists?

## Suite that reproduces the behavior (for bugs)
This fails for me:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'http://rubygems.org'
  gem 'jasmine', '~> 2.3.0'
end
```

## Your Environment
* Ruby 2.5.0
* Bundler 1.16.1

**Comment by mykhi** [comment]
+1 here, looks like it's broken. works up to 2.99.0

**Comment by rocket-turtle** [comment]
+1 looks like the spec folder is a broken symlink
```
$ cd gems/jasmine-core-2.99.1/lib/jasmine-core/
$ ls -la
...
lrwxr-xr-x   1 jos  staff      29  9 Feb 17:07 spec -> ./lib/jasmine-core/../../spec
```

**Comment by slackersoft** [comment]
I've just released 2.99.2  which should fix this issue. Nothing around the spec folder and bundling has changed in a long while, but we probably don't need to be shipping Jasmine's own specs in the gem anyways.

Thanks for pointing this out!

**Comment by joshrowley** [comment]
@slackersoft Thanks so much for the quick fix!

**Comment by camertron** [comment]
Thank you!
