### ISSUE TITLE
Error when trying to use the 'toHaveClass' matcher

### ISSUE THREAD

**Issue by emaduka-debanke** [jasmine/jasmine#1503]
## Are you creating an issue in the correct repository?
Yes

## Expected Behavior
`expect(el).toHaveClass('bar');` should return true or false.

## Current Behavior
`expect(el).toHaveClass('bar');` returns the following error:
```shell
TypeError: expect(...).toHaveClass is not a function
	    at <Jasmine>
	    at UserContext.<anonymous> (spec/directives/spec.alerts.js:30:20)
	    at <Jasmine>
```

## Suite that reproduces the behavior (for bugs)
```javascript
it('should check the element class', function () {
    var el = document.createElement('div');
    el.className = 'foo bar baz';
    expect(el).toHaveClass('bar');
});
```

## Context

I'm trying to run some tests for a directive and wanted to use the new matcher that has become available in Jasmine 3.0.0.  The first attempt at using the matcher, caused the issue above.

I am using Karma (1.7.1) as a test runner.  

## Your Environment

* Version used: 3.0.0
* Environment name and version: Chrome 62.0.3202, node.js 8.5.0
* Operating System and version (desktop or mobile): Desktop
* App: AngularJS 1.5.11

**Comment by sgravrock** [comment]
We're still working out the best way to package browser-specific matchers. I hope to have something that will work for Karma ready Real Soon Now™. In the meantime, you should be able to get it working by grabbing `jasmine-html.js` from the [standalone distribution](https://github.com/jasmine/jasmine/releases/download/v3.0.0/jasmine-standalone-3.0.0.zip) and including it in your Karma config's `files` array before any of your spec files.

**Comment by emaduka-debanke** [comment]
Many thanks @sgravrock, I'll use ```jasmine-html.js``` in the meantime.
