### ISSUE TITLE
Error in the Version for NPM for jasmine-core

### ISSUE THREAD

**Issue by seanwestfall** [jasmine/jasmine#1504]
I  believe there's been an error in the versioning for jamine-core. As I was checking for updates I an angular app I noticed the version jumped from 2.9.1  →  2.99.1 and that looks like a mistake:

![screen shot 2018-02-09 at 3 41 05 pm](https://user-images.githubusercontent.com/9439906/36055238-d710d53c-0daf-11e8-86b0-3900d1ba7e04.png)

Is this an error?

**Comment by slackersoft** [comment]
This is not an mistake. We also released 3.0 this week. In an effort to help mitigate migration pains, [2.99 was released](https://github.com/jasmine/jasmine/blob/master/release_notes/2.99.md) to let users know about deprecated features.

Hope this helps. Thanks for using Jasmine!
