### ISSUE TITLE
Spies : Calling through doesn't work, but calling fake the same function does. 

### ISSUE THREAD

**Issue by trichetriche** [jasmine/jasmine#1507]
I first should mention I use **Jasmine ~2.8.0** with **Angular 5.1.1 (CLI @ 1.6.1)**.

## Expected Behavior
When I create a spy with this 

      component['createMarker'] = jasmine.createSpy().and.callThrough();

I expect the function to have been called, and I expect the function to run as if there was no spy.

## Current Behavior

The `callThrough` won't work, but using this 

      component['createMarker'] = jasmine.createSpy().and.callFake(component['createMarker']);

Works. I really can't understand the issue there, therefore I am creating an issue into your repo. 

## Suite that reproduces the behavior

I'm not sure I can reproduce the behavior, so instead of making a sandbox, I will post my whole code, hoping for an explanation (at least).

The code is at the end of the issue, so that it doesn't bother your reading ! 

I should also state the error I guess. When I create a marker with the `createMarker` function, using `callThrough` returns `undefined` (and as I stated, fakely calling the same function works well), thus making it impossible to call `getLatLng` on undefined. Here is the error (look for `marker.getLatLng()` in the `setSelected` function)  : 

    × should remove the marker of the select source post
      Chrome 63.0.3239 (Windows 10 0.0.0)
      TypeError: Cannot read property 'getLatLng' of undefined
        at MapComponent.setSelected C:/Users/MT4E45CN/Documents/Projects/ms-front/src/app/components/logged/map/map.component.ts:122:62)

As I said, I have found a workaround, so it's just for information at this point. Although, I would like to use `callThrough`, it's easier ... 

I stay available if you have questions or need additional information !

## Your Environment

I'm on **Windows 10**, using **Chrome 63.0.3239**, with **Jasmine ~2.8.0**.

## Code snippets

**map.component.ts**

````javascript
  setSelected(sp: CustomObject) {
    this.removeMarker(sp);

    if (this.currentPost) {
      this.removeMarker(this.currentPost);

      if (this.session.isCustomObjectInCustomValue(this.currentPost)) {
        this.createMarker(this.currentPost, this.createCoordinates(this.currentPost));
      }
    }
    if (sp.latitude && sp.longitude) {
      const marker = this.createMarker(sp, this.createCoordinates(sp), this.selectedIcon);
      if (
        !this.isMapSelection &&
        !this.leafletMap.getBounds().contains(marker.getLatLng())
      ) { this.zoomOnMarker(marker, 14); }
    } else {
      this.snacker.open('Coordonnées non renseignées', 'OK', { duration: 2500 });
    }
  }
````

**map.component.spec.ts**

````javascript

describe('MapComponent', () => {
  let component: MapComponent;
  let fixture: ComponentFixture<MapComponent>;

  const spMock: any = { id: 1, latitude: 10, longitude: 10 };

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [MapComponent],
      providers: [sessionServiceMock, sourcePostServiceMock],
      imports: [SharedModule, BrowserAnimationsModule]
    })
      .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(MapComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  describe('setSelected', () => {

    let mapContainsSpy: jasmine.Spy;

    beforeEach(() => {
      component.currentPost = spMock;
      component['removeMarker'] = createFakeCallSpy();
      component['createMarker'] = jasmine.createSpy().and.callThrough();
      component['zoomOnMarker'] = createFakeCallSpy();

      mapContainsSpy = spyOn(component.leafletMap.getBounds(), 'contains');
    });

    it('should remove the marker of the select source post', () => {
      component.setSelected(spMock);
      expect(component['removeMarker']).toHaveBeenCalledWith(spMock);
    });
  });
});

````

**Comment by slackersoft** [comment]
The `callThrough` strategy for spies relies on there to be an original function. This gets set up automatically when you use `spyOn`. You should probably be using `spyOn` if you're replacing existing functions on an object because those spies will get cleaned up after each spec is done to help eliminate test pollution.

Hope this helps. Thanks for using Jasmine!

**Comment by trichetriche** [comment]
I used the array notation to bypass the `private` scope of my function and still be tslint compliant. Should I set it to public and use spy on ? I'll try that tomorrow then !

**Comment by slackersoft** [comment]
In general, I would recommend against mocking (or spying on) internals of the object/class/component that you are testing, even if they are public. This can put your tests in a position where they aren't really testing the object how it really works. You could also try injecting a collaborator object that has those functions publicly available. Jasmine does a lot of this in its own specs for just this type of reason.

Hope this helps. Thanks for using Jasmine!

**Comment by guntram** [comment]
You can spy on private methods without the array notation:

`spyOn<any>(component, 'myPrivateMethod');`

**Comment by trichetriche** [comment]
@guntram No you can't (well at least I can't). Furthermore, I think that's besides the point ...

(Here is my proof : )

![image](https://user-images.githubusercontent.com/7789922/36733216-3154bb20-1bd0-11e8-85b5-e03aafc8f927.png)

**Comment by guntram** [comment]
AAANNNYYY ;)

**Comment by guntram** [comment]
`spyOn< A N Y >(component, 'privateMethodName');`

**Comment by trichetriche** [comment]
Oh, my bad ! Anyway, that's still besides the point :P

(but thank you, I will try that tomorrow and see if it suits me !)

**Comment by guntram** [comment]
Yes, I am also confused that sometimes using callTrough() and not using it works...
I tried to avoid callFake() until now, and also createSpy(). I don't like all this manually creating stuff and zones and whatever just to test if some method was called to keep up coverage :)

**Comment by slackersoft** [comment]
I'm going to close this since it seems like there isn't an issue with Jasmine itself, but with test setup and testing angular components. Feel free to discuss more on the [jasmine-js](https://groups.google.com/forum/#!forum/jasmine-js) google group.

Thanks for using Jasmine!
