### ISSUE TITLE
Object equality fails when object contains a function

### ISSUE THREAD

**Issue by antgonzales** [jasmine/jasmine#1508]
## Expected Behavior
I would expect this text assertion to pass:
```
it('passes objects that contain functions', () => {
expect({1: 'hello', 2: function() {}}).toEqual({1: 'hello', 2: function() {}});
expect({1: 'hello', 2: function() {}}).toEqual(jasmine.objectContaining({1: 'hello', 2: function() {}}));
});
```

## Current Behavior
```
Expected Object({ 1: 'hello', 2: Function }) to equal <jasmine.objectContaining(Object({ 1: 'hello', 2: Function }))>.
	    at Object.eval (http://localhost:9876/statictests/
```

## Context
I'm attempting to test a function call that passes callbacks within an object. Here was my initial test idea but it fails.

```
const params = {
  resolve: {
    someData: () => someData
  }
};
myFunc(params);
expect(myFunc).toHaveBeenCalledWith(params);
```

## Your Environment
* Version used: 2.3.4
* Environment name and version: Headless Chrome 64.0.3282.167
* Operating System and version: macOS High Sierra 10.13.3

**Comment by slackersoft** [comment]
Unfortunately, functions are really hard to do equality comparisons on. For example, this spec fails:

```javascript
it("can't compare functions", function()  {
  expect(function() {}).toEqual(function() {});
});
```

Because functions are compared via reference equality

```javascript
it('does reference equality', function()  {
  var fn = function() {};
  expect(fn).toEqual(fn);
});
```

Depending on what you're looking to test about the function, you might also look at [`jasmine.any(Function)`](https://jasmine.github.io/api/edge/jasmine.html#.any), which you can also nest inside your `jasmine.objectContaining`.

Hope this helps. Thanks for using Jasmine!

**Comment by antgonzales** [comment]
Thanks for the reply. It looks like this was previously answered so I'm going to go ahead and close. 

https://github.com/jasmine/jasmine/issues/652

**Comment by alexsalmon** [comment]
If allowed, try using a `JSON.stringify()` on your objects.

**Comment by Gnanarajk** [comment]
you can use toString() to do equality check, so it checks the text exactness rather its functionality.

**Comment by ladytellur** [comment]
Stringlified objects will be equal only in case of the same properties order.
It makes more sense to stringlify only functions inside objects and compare them separately.
