### ISSUE TITLE
Provide an example of async reporter hooks

### ISSUE THREAD

**Issue by tymfear** [jasmine/jasmine#1509]
It is said [here](https://github.com/jasmine/jasmine/issues/842) that async custom reporter hooks are implemented in Jasmine3. But I failed to implement it. Provide some examples to documentation on this, please.

**Comment by slackersoft** [comment]
The [api docs for Reporters](https://jasmine.github.io/api/edge/Reporter.html) and the [custom reporter tutorial](https://jasmine.github.io/tutorials/custom_reporter) have both been update with the new info about async reporters.

The short answer is that they work much like other async functionality in Jasmine. You can accept a trailing param (after the result information) as a `done` callback, return a `Promise`, or use the `async` keyword.

Hope this helps. Thanks for using Jasmine!
