### ISSUE TITLE
Transforming deliver.sm to submit.sm

### ISSUE THREAD

**Issue by JFnine** [jasmine/jasmine#1511]
Good morning,

I’ve been checking the configuration of JasminSMPP to build it. In one of the URL’s – this one: https://github.com/jookies/jasmin/issues/142 - I’ve found that was not posible to comunicate two SMPPclients by transforming deliver.sm to submit.sm because the standard didn’t allow that. 

Then, from Jasmin platform, was wrote a basic scripted example to do this making a PDU and sending it to RabbitMQ, but the webpage  - https://gist.github.com/zoufou/efc604070f34ef699c8b - seems that is not working anymore.

In the latest version of Jasmin, is still not posible to do this? Do I have to prepare some script to make it happen?

Anyway, what I'm trying to do is to connect a SMPP client to a SMPP server to send the SMS to the SMScenter. So, at first, I should be able to receive the petition of the SMPP client via PDU - submit.sm (deliver at my SMPP server) and, by creating a connector, re-send it to SMScenter.

Thanks in advance,

kind regards.

**Comment by sgravrock** [comment]
Did you mean to open this issue on https://github.com/jookies/jasmin rather than here? Jasmine (as opposed to Jasmin) is a Javascript testing framework and has nothing to do with SMPP or SMS.

**Comment by JFnine** [comment]
Wow, you're right. My apologies. 

Kind regards.
