### ISSUE TITLE
Provide a way to run all specs marked as pending

### ISSUE THREAD

**Issue by chris-orchard** [jasmine/jasmine#1517]
It would be helpful to have a way to force all specs marked as `pending` to be run, to easily check if they are now passing without having to go to the corresponding code and take off the `pending` marker.

At a minimum I believe a Pending 'tab' on the html reporter which listed all pending specs in one place would be useful:
`Spec List | Failures | Pending`

Providing an option on this tab to run the listed specs, and another in Jasmine to run a spec even when it is marked as pending.

## Context
Although we try and use the pending argument to say which task numbers in our backlog a spec is blocked by for example `pending('Should be fixed by 123')`, it is still a manual process to comment out the `pending` and re-run the spec to check it has been fixed. This means it invariably gets forgotten on occasion. 

Other times the cause isn't known at the time, or there's no issue in the backlog yet, so the spec gets set to pending without and argument and forgotten about.

Both of these mean we have an ever increasing number of pending specs for our project which I would like an easier way to tackle.

**Comment by henrahmagix** [comment]
I too would like this! Rspec is an example of a test runner that does precisely this, and I love it:
1. write a failing test (unimplemented in code)
2. mark as `pending('unimplemented')`
	- reporter shows test as pending and passes (current usage)
3. write code to implement the test
	- reporter shows test as pending __and fails__ (new change)

On top of that, I think reporting the failure of the pending test is useful to see, even though the runner passes.

**Comment by chris-orchard** [comment]
@henrahmagix That sounds good but how does Rspec cope with tests that have been marked as pending because they fail intermittently? We have some we've marked pending until we can investigate and make them stable. But with Rspec's approach every time they happen to pass the suite would be failed (due to pending tests now passing).

**Comment by slackersoft** [comment]
Currently Jasmine's `pending` is more like RSpecs `skip` than anything else. At some point I'd like to get to the point where Jasmine has both `skip` and `pending` mechanisms, with a possible first step being allowing `pending` to also take a function and only doing the fail on success mechanic when that is used. This would let a user opt-in to this behavior and allow us to make that be the default behavior in a future major release.

**Comment by chris-orchard** [comment]
@slackersoft that sounds like a good starting point to allow running pending specs.

How about my other suggestion of adding a pending tab to the html report to view all of them together?
> At a minimum I believe a Pending 'tab' on the html reporter which listed all pending specs in one place would be useful:
Spec List | Failures | Pending

That sounds like it should be straightforward. If so I'd be happy to have a go at that.

**Comment by henrahmagix** [comment]
@slackersoft Sounds great! What about also including a config option so users don't have to rewrite all their pending to pass functions? It would satisfy @chris-orchard's requirement:
>It would be helpful to have a way to force all specs marked as `pending` to be run, to easily check if they are now passing without having to go to the corresponding code and take off the `pending` marker.

I'm quite keen to give this a go so I'll see what I can come up with over the weekend =)

**Comment by slackersoft** [comment]
I'd be happy to review a pull request that adds a "Pending" tab to the HtmlReporter, including a bit better method to display the message/reason for the pendingness.

I'd also be happy to review a pull request that either added a `skip` function or allowed `pending` to take a function and fail the test when the function doesn't have any failing expectations.

**Comment by elliot-nelson** [comment]
Just noting here the potential interaction between this request and https://github.com/jasmine/jasmine/issues/1579 - this change basically means Jasmine will always be "stealth running" pending tests, whereas the other issue is relying on behavior that does not run code in the unit test if it's pending (with the appropriate flags on).

It sounds to me like maybe there's a breaking change, where today's `pending` implementation should just become `skip` (which always exits the test when called), and then `pending` becomes a marker only -- the test will always run, but failures will be ignored.

**Comment by slackersoft** [comment]
Even the current `pending` implementation isn't a great fit for what we would want a `skip` to do. It currently only stops execution of the current function, but continues to run others unless `oneFailurePerSpec` is set. I would expect a `skip` inside a `beforeEach` to skip out of the rest of the spec, where a current `pending` will run further `beforeEach`, `it`, and `afterEach`. I would definitely like to see such a `skip` function come into Jasmine at some point.

The conversion process might look something like what RSpec for ruby did some time ago where `pending` starts to expect to receive a `function` that will be executed and allow failures, but will first work as normal but show a deprecation message.

**Comment by elliot-nelson** [comment]
I am slicing off https://github.com/jasmine/jasmine/issues/1709 to represent the "add skip to jasmine" work.  In my opinion, we probably want that to exist _before_ we begin changing the behavior of pending, because today I often use pending to mark code that is not safe to run.

**Comment by sgravrock** [comment]
I'm closing this due to prolonged inactivity, but anyone who wants the proposed change enough to implement it should still feel free to submit a PR.
