### ISSUE TITLE
How can I run "done" multiple times?

### ISSUE THREAD

**Issue by LvChengbin** [jasmine/jasmine#1518]
I want to run a test if an async function was executed multiple times, how can I implement the test case?

For example: while emitting the "x" event, I hope the handler function would be executed twice, and then to execute the `done` function.
```js
it( 'should be executed twice', done => {
    const handler = () => done();
    em.on( 'x', handler );
   em.emit( 'x' );
} );
```

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
