### ISSUE TITLE
Async custom reporter hook not working

### ISSUE THREAD

**Issue by brainroma** [jasmine/jasmine#1522]
I'm using the following packages with TypeScript 2.7.2:

"jasmine-core": "^3.1.0",
 "jasmine-reporters": "^2.3.0",
 "jasmine-spec-reporter": "^4.2.0",

This is a chunk of code for testing: 

```typescript
import CustomReporter = jasmine.CustomReporter;

export const TestReporter: CustomReporter = {
    async specDone(result) {
        console.log('Spec Done started');
        await setTimeout(() => console.log('Time out....'), 5000);
        console.log('Spec Done finished');
    }
};

jasmine.getEnv().addReporter(TestReporter);

describe('Test reporter.', () => {
    it(`Successful Test`, async () => {
        expect(true).toBeTruthy();
    });
});
```

This won't asynchronously wait for timeout and won't print 'Time out....'.

Also in the issue #1509 (Closed) you advised to return a Promise, but all functions in TS typing for custom reporter are void:
```typescript
interface CustomReporter {
        jasmineStarted?(suiteInfo: SuiteInfo): void;
        suiteStarted?(result: CustomReporterResult): void;
        specStarted?(result: CustomReporterResult): void;
        specDone?(result: CustomReporterResult): void;
        suiteDone?(result: CustomReporterResult): void;
        jasmineDone?(runDetails: RunDetails): void;
    }
```

Please advise.

**Comment by slackersoft** [comment]
What output _are_ you seeing from your example? This will help diagnose the problems you're seeing.

Additionally, I don't think that `setTimeout` actually returns a Promise that would make it `await`able, so control flow won't actually break.

As for returning a Promise, the Jasmine team doesn't actually maintain any typings for jasmine-core, so it is possible that wherever you're getting these typings from simply hasn't updated the reporter typings for Jasmine 3.0.

Hope this helps. Thanks for using Jasmine!

**Comment by brainroma** [comment]
It won't wait and won't print 'Time out....', the output I see is:

Spec Done started
Spec Done finished

I have updated the code with the following:

```typescript
import CustomReporter = jasmine.CustomReporter;

export function delay(): Promise<void> {
    return new Promise((resolve) => {
        setTimeout(() => resolve(console.log('Time out....')), 5000);
    });
}

export const TestReporter: CustomReporter = {
    async specDone(result) {
        console.log('SPEC DONE started');
        await delay();
        console.log('SPEC DONE finished');
    }
};

jasmine.getEnv().addReporter(TestReporter);

describe('Test reporter.', () => {
    it(`Successful Test`, async () => {
        expect(true).toBeTruthy();
    });
});
```

This won't wait and won't print 'Time out....' and 'SPEC DONE finished'. The output I see is:

SPEC DONE started

**Comment by slackersoft** [comment]
It looks like this is probably an issue with the typings that you're using to work with Jasmine. When I convert to ES5 like this, all three versions of async `specDone` work correctly.

```javascript
(function() {
  var setTimeout = window.setTimeout;

  function delay() {
    return new Promise(function(resolve) {
      setTimeout(function() {
        resolve(console.log('Time out...'));
      }, 3000);
    });
  }

  function MyReporter() {
    this.specDone = async function(result) {
      console.log('SPEC DONE started');
      await delay();
      console.log('SPEC DONE finished');
    };

    // this.specDone = function(result) {
      // console.log('SPEC DONE started');
      // return delay();
    // };

    // this.specDone = function(result, done) {
      // console.log('SPEC DONE started');
      // setTimeout(function() {
        // console.log('Time out...');
        // done();
      // }, 3000);
    // };
  }

  jasmine.getEnv().addReporter(new MyReporter());
})();
```

Hope this helps. Thanks for using Jasmine!

**Comment by JohannesRudolph** [comment]
@slackersoft I tried the reporter code above in my typescript project and all I see logged is: 
```
  Outer describe
    ✓ spec A
SPEC DONE started
    ✓ spec B
SPEC DONE started

    inner describe
      ✓ spec C
SPEC DONE started
      ✓ spec D
SPEC DONE started

Executed 4 of 4 specs SUCCESS in 0.051 sec.
```
but never a `SPEC DONE finished`. Is there a sample test for async reporters in jasmine?

**Comment by JohannesRudolph** [comment]
.... figured it out. I was using [jasmine-ts](https://www.npmjs.com/package/jasmine-ts) which has got its own dependency on jasmine and that was still on v2.8.6. I'm using yarn, so I could use this in my package.json to force use of 3.1: 

```json
  "resolutions": {
    "jasmine": "3.1.0"
  }
```

I assume that trick may also help @brainroma.

**Comment by slackersoft** [comment]
Protractor is still locked to Jasmine 2.8.0, so it isn't going to load Jasmine 3.0.

**Comment by cnishina** [comment]
^^^ you have a Protractor tag! Awesome! 👍

**Comment by sgravrock** [comment]
I'm going to go ahead and close this since it should have been fixed when Protractor updated to Jasmine 3.x, and we haven't heard anything new in over a year. Feel free to open a new issue if async reporters still aren't working for you.

**Comment by Ashraf2513** [comment]
> @slackersoft I tried the reporter code above in my typescript project and all I see logged is:
> 
> ```
>   Outer describe
>     ✓ spec A
> SPEC DONE started
>     ✓ spec B
> SPEC DONE started
> 
>     inner describe
>       ✓ spec C
> SPEC DONE started
>       ✓ spec D
> SPEC DONE started
> 
> Executed 4 of 4 specs SUCCESS in 0.051 sec.
> ```
> 
> but never a `SPEC DONE finished`. Is there a sample test for async reporters in jasmine?



> .... figured it out. I was using [jasmine-ts](https://www.npmjs.com/package/jasmine-ts) which has got its own dependency on jasmine and that was still on v2.8.6. I'm using yarn, so I could use this in my package.json to force use of 3.1:
> 
> ```json
>   "resolutions": {
>     "jasmine": "3.1.0"
>   }
> ```
> 
> I assume that trick may also help @brainroma. Async callbacks work fine for me now.

Hello JohannesRudolph, I am also facing the same issue please help me by providing a sample code to use Async & Await at spect Done in After each. Thanks.

**Comment by lgrignon** [comment]
Warning: using protractor 5.4.2 & jasmine 3.5.0, only [this ugly fix](https://github.com/jasmine/jasmine/issues/842#issuecomment-336077418) worked for me to get async specDone to be waited before next test execution.

**Comment by slackersoft** [comment]
If you're still having trouble with async custom reporters, please make sure that Jasmine 3.x is _actually_ being used, especially if you're running Jasmine through something like Protractor. If you've confirmed Jasmine 3.x and are still seeing this issue, I would appreciate a new issue with some steps and and example so we can get it reproduced and fixed in a future release.

Thanks.
