### ISSUE TITLE
Disable empty tests

### ISSUE THREAD

**Issue by fetis** [jasmine/jasmine#1525]
Hello,

Can we have an option (or maybe make it as default behavior) that empty tests which look like
```
it('should do smth', () => {})
```
will be failed or at least provide some warnings. This's extremely important if you testing some async actions.

**Comment by slackersoft** [comment]
This is a similar problem to detecting a spec which doesn't include any calls to `expect`. There are some situations where a user might feel that an expectation is superfluous (maybe the code under test throws), so we don't want this to cause an the spec to fail. This use case is the reason why reporters are told the number of passed and failed expectations for a spec, so they can tell if none were evaluated. If you're using Jasmine's HTMLReporter, you should see the specs show yellow with a big message and a warning in the console for all specs that don't have any expectations.

I don't think we're likely to be making any changes to this functionality, so I'm going to close this. Thanks for using Jasmine!

**Comment by fetis** [comment]
@slackersoft Are you speaking about [Karma Jasmine reporter](https://www.npmjs.com/package/karma-jasmine-html-reporter)? I don't use it. But so far, I haven't seen any warnings about empty tests from other reporters. Only total number of failed/successful specs.

**Comment by slackersoft** [comment]
If you're using Karma, I'm afraid it covers up some of the built-in functionality of Jasmine including the default HTMLReporter. The reporter and example of no expectations error looks like this:

<img width="883" alt="screen shot 2018-03-12 at 5 23 17 pm" src="https://user-images.githubusercontent.com/512724/37316053-392b49be-261a-11e8-86a9-e0f3cb8e495e.png">

**Comment by fetis** [comment]
My stack is more complex. It's Angular CLI project with 2 testing frameworks: Karma and Angular CLI itself and Jasmine as underlaying unit-testing library. It's standard setup for Angular CLI projects. 

If you provide the number of expectations via API, I could try to pull it on top level and do corresponding checks.

**Comment by slackersoft** [comment]
@fetis take a look at the [spec result](https://jasmine.github.io/api/edge/global.html#SpecResult) object for details on what is sent to a reporter.
