### ISSUE TITLE
StackTrace component truncating error messages from certain stack traces

### ISSUE THREAD

**Issue by rmunch** [jasmine/jasmine#1526]
Since Jasmine 3.0.0, the StackTrace component strips all but the first line of certain error messages that come from the raw browser trace. When running in Chrome, this affects AngularJS exceptions that can be multi-line.

I made a plunker to illustrate the issue with an AngularJS exception - see https://embed.plnkr.co/3qtge9FUP0PCIlu2jB9m/. This plunker boots Jasmine with a custom reporter, and runs a simple Angular app. The output in the gray box comes from the strackTrace object passed into `specDone` reporter method - the gray box is showing the `message` and `stack` properties. You can see the full error is only included in the message, but is stripped from the stack.

I was able to confirm the issue began with this commit: https://github.com/jasmine/jasmine/commit/5906a2c05c5628ca7cf06cf4ca1bada4a7c392b9. The issue is not present in Jasmine 2.99.x.

Thanks!

## Expected Behavior
To be able to view the full multi-line error message, and the stack trace.

## Current Behavior
Can only see the first line of the error message, and the stack trace.

## Possible Solution
Update the StackTrace logic to handle this error format.

## Context
This of course makes it difficult to track debug issues. I'm using karma-jasmine specifically which outputs the stackTrace stack.

## Your Environment
* Version used: Jasmine 3.0.0 +
* Environment name and version: Chrome 64
* Operating System and version: desktop

**Comment by slackersoft** [comment]
I'm not sure I fully understand the differences you're seeing between what you expect and what you're getting. Can you show an example Error with message and stack, then what you're seeing reported for that error in 2.x and 3.x?

Thanks!

**Comment by rmunch** [comment]
Hi @slackersoft - I forked the Plunker with a version that just sets the Jasmine version down to 2.99.0 so that they can be compared directly:

Jasmine 2.99.0 (works, can see additional lines from the Angular error): https://embed.plnkr.co/FPTovSMUsUz8UxCn94vH/

Jasmine 3.1.0 (only has the first line of the error):
https://embed.plnkr.co/3qtge9FUP0PCIlu2jB9m/

In the spec, I'm manually throwing an error in the call to initialize a mock angular module just to get Angular to throw its exception.

Thanks!

**Comment by rmunch** [comment]
Also if helpful, it looks like the logic that is truncating the error message is at https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L5747-L5748 - commenting out this block fixes my particular exception (though I'm sure breaks another format).

**Comment by sgravrock** [comment]
Thanks. That helps. [The code in question](https://github.com/jasmine/jasmine/blob/85b2a8c6c4cf0fbc130a49bf71e5e34bd0ff4027/lib/jasmine-core/jasmine.js#L5747-L5748) is needed to correctly format stack traces across all browsers, some of which include the error message in the stack trace and some of which don't. But it looks like it needs to be a little smarter to correctly handle multi-line messages.

**Comment by jaimemarijke** [comment]
@sgravrock do you have a timeline for when this fix will be published?

**Comment by slackersoft** [comment]
This fix is included in 3.2.0, which has just been released.
