### ISSUE TITLE
Enumerating Specs after loading test file (broken in 3.x, worked in 2.9)

### ISSUE THREAD

**Issue by paulvanbrenk** [jasmine/jasmine#1529]
I work on the [Node Tools for Visual Studio](https://github.com/Microsoft/nodejstools) and after the release of Jasmine 3.0 our ability to enumerate tests has broken. 😞

Before 3.0 we were able to do the following to get a list of specs in a specific file, and communicate that back to VS to show in the test explorer.

```javascript
var testList = [];
var jasmineInstance = // create instance
jasmineInstance.env.specFilter = (spec) => {
   testList.push({
       test: spec.getSpecName(spec),
       // bunch more properties
       });
       return false; 
    };
jasmineInstance.addSpecFiles([testFile]);
jasmineInstance.loadSpecs();
```

But in 3.0 the specFilter function no longer seems to be called when `loadSpecs` is called.

My question is, is there a way to access the enumerated Specs before executing the tests? If there isn't what would be a logical place to make a change to implement this? (I wasn't able to find anything useful, but I only spend a little time spelunking through the code).

**Comment by slackersoft** [comment]
You should be able to get the `topSuite()` from the `env` object and traverse the spec tree from there. This also leaves the `specFilter` available for determining which specs should run programmatically if you want.

The `topSuite()` function is also available in 2.x versions of Jasmine, with the same capabilities.

Hope this helps. Thanks for using Jasmine!

**Comment by paulvanbrenk** [comment]
Thanks!

That's a much cleaner solution.
