### ISSUE TITLE
ES 7 Array.includes issue

### ISSUE THREAD

**Issue by vsharma2266** [jasmine/jasmine#1530]
## Expected Behavior

Should not return error when using Array.includes(element)

## Current Behavior
Returns following error

```TypeError: undefined is not a constructor (evaluating 'exclusions.includes(element) ```

## Possible Solution

Array.includes() can be replaced with Array.indexOf > -1.

## Suite that reproduces the behavior (for bugs)

TS
```javascript
  exclusionTest() {
    return this.exclusions('Event').includes('id');
  }

  exclusions(eventType: string): string[] {
    let defaultExclusions = ['id', 'pendStatus', 'accountId'];
    return eventType === 'REMOVE' ? defaultExclusions : [...defaultExclusions, 'pendDeleteReason'];
  }
```
In angular environment
```javascript
describe ('SomeComponent', () => {
  let fixture: ComponentFixture<SomeComponent>;

  beforeEach(() => {

    TestBed.configureTestingModule({
      providers: [
        SomeComponent,
      ]
    });
  });

  it('should test includes', inject([SomeComponent],
      (component: SomeComponent) => {
        expect(component.exclusionTest()).toBeTruthy();
    }));
  });
});
```
## Context
I am trying to test if an Array has a particular element.
Since there is an option to use `indexOf`, it does not affect as much. But with this issue, testing is dictating how i write my javascript code.

## Your Environment
* Version used: jasmine@2.99.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac OS
* Link to your project: internal company project. Cannot link.

**Comment by vsharma2266** [comment]
Doing more research, looks like none of the ES7 features are supported yet.
Like `Object.values, Object.enteries, padStart, padEnd, etc.`

Is that correct?

**Comment by sgravrock** [comment]
The methods that you're trying to use are provided by Node, not Jasmine. Node 5.4 doesn't provide them, regardless of whether or not you use Jasmine. You'll need to upgrade to a newer version of Node if you want to use things like Array.includes.

Closing as this doesn't appear to be an issue with Jasmine.

**Comment by yanlucas99** [comment]
- You can use a contour solution by setting the parameter before the call on the " it " function, as follows:

// if you want to test an includes function, you should pass an object that contains the function, example:
$scope.testIncludes( { includes: function(){ return true } } );

- And your test will pass at your controller, example:

function testIncludes(text){
if(text.includes("anything")){
// do anything
} else {
// do anything else
}
}

- Note that the else path will only be taken if you test with the opposite of the object we created ( just swap true for false) , example:

$scope.testIncludes( { includes: function(){ return false} } );
