### ISSUE TITLE
List filtered specs without executing them

### ISSUE THREAD

**Issue by Morikko** [jasmine/jasmine#1531]
I am using Jasmine in stand-alone mode in the browser. Every time, I am opening the page, all the tests are executed. I would prefer to have an option to set if tests should be executed or just listed (in gray). More or less an interactive mode (cf Git).

It could take the form of: 
 - URL parameter (my_test.html?**execution=false**)
 - A check box option in the Options menu of Jasmine

Advantages: 
 - You don't have to change your code to choose which specs to do 
    - Avoid to disturb the git
    - You can share the spec param to provide the same filter
 - You can see and prepare which tests are going to be done (Also because each suites/specs give a link to select automatically the sub tests)
 - You can open a page with tests without launching them right now (I have mostly integration tests that use the browser API, they impact the UI directly and are resource consuming)

## Temporary solution but limited
This code makes all and only all the tests to be listed (in grey) without being executed if spec param is empty or not defined. It is like if no spec names match the filter, then all the tests are listed. Am I right ?

Limitation: I didn't find an alternative to keep the list mode while filtering the specs by name.

```javascript
var specFilter = new jasmine.HtmlSpecFilter({
  filterString: function() {
    switch(queryString.getParam("spec")) {
      case "all":
        return "";
      case undefined:
        return "@@@@@@@";
      case "":
        return "@@@@@@@";
      default:
        return queryString.getParam("spec")
    }
  }
});

var env = jasmine.getEnv();

env.specFilter = function(spec) {
  return specFilter.matches(spec.getFullName());
};
```

**Comment by slackersoft** [comment]
Full support for a `dryRun` kind of flag gets a bit more complicated with the command line runners, so I'm not sure this is something we're looking for right now.

However, if you're already customizing your `boot.js` to override the `specFilter` on env, you might also look at how the `filterSpecs` argument is being set in the `HtmlReporter` object. This is the flag that tells the HtmlReporter whether it should hide specs that were excluded from the run.

Hope this helps. Thanks for using Jasmine!

**Comment by Morikko** [comment]
Thank you, I will check `filterSpecs` in the `HtmlReporter`.

**Comment by sgravrock** [comment]
Closing since we haven't heard anything new on this in a while.
