### ISSUE TITLE
Add some way to handle css, scss, html files in node

### ISSUE THREAD

**Issue by kevinlbatchelor** [jasmine/jasmine#1535]
The world seems to be leaving Jasmine behind. recently I was forced to swtich one of my test services to use Jest instead of Jasmine, which was rather painless as I think Jest must respect Jasmine syntax. However I cannot stand how Jest ignores fdescribe and fit.  But the problem is this:

I can find no documentation or examples of how to get Jasmine to handle or mock css, scss or html. This is not a front end app, but I need to process some css and html and when I import or require these files Jasmine goes ballistic.

Is this even possible with out aid from karma? Are there any examples of doing this?  

I would expect to be able to add some type of transform to a config like:

    "transform": {
      "^.+.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+.(css|scss|handlebars)$": "<rootDir>/config/jest/textTransform.js"
    }
}

I don't want to test the results of the css or html, I just want to test the test the code surrounding it. Any thoughts on this?

**Comment by slackersoft** [comment]
The [jasmine](https://www.npmjs.com/package/jasmine) npm package is intended for use in a node.js only context. I'm not totally sure what kinds of errors you're actually seeing or what outcome you're expecting, but you might take a look at:

* [Jasmine npm react tutorial](https://jasmine.github.io/tutorials/react_with_npm)
* [gulp jasmine browser](https://github.com/jasmine/gulp-jasmine-browser)
* [Jasmine ruby gem](https://github.com/jasmine/jasmine-gem)

Jasmine is intended to be able to run in (more or less) any JavaScript context, be it browser, Node.js, or something else. So you need to make sure that the environment in which Jasmine is running supports loading the files you want.

Hope this helps. Thanks for using Jasmine!

**Comment by kevinlbatchelor** [comment]
We are using jasmine in node only. This particular micro service creates html templates and passes them onto be processed by another micro service as apart of a job. We actually package the file using webpack, which obviously handles the handlebars files. I wish I could find some help on this, but it was just easier to switch to Jest, event through I'm not a big fan of the Jest test runner. Thanks for your comments. If you guys are interested in this I could throw up a example of what I'm talking about.

**Comment by slackersoft** [comment]
I'm having a really hard time figuring out what it is that you're trying to do, and what you think Jasmine is doing (or not doing) that is making this hard.

You mentioned loading CSS/HTML/etc. files, and having Jasmine "go ballistic". Unfortunately, we can't really address (or even figure out how to discuss) this feedback. If you can provide an example of what you're trying to do and what _Jasmine_ is doing to make it difficult we'd be happy to discuss solutions within Jasmine.

**Comment by sgravrock** [comment]
Are you importing things like CSS files from your Javascript files, like this:

```
// in somefile.js
import './foo.css';
```

If so, you might be able to solve the problem by using require-hacker as outlined at https://jasmine.github.io/tutorials/react_with_npm.

**Comment by slackersoft** [comment]
Closing this since we haven't heard anything else in a while.
