### ISSUE TITLE
incorrect test execution queue

### ISSUE THREAD

**Issue by vasivas** [jasmine/jasmine#1537]
// file.spec.js
    describe('[test]', () => {
        it('first', () => {
            expect(true).toBeTruthy();
        });
        it('second', () => {
            expect(true).toBeTruthy();
        });
    });

in `file.spec.js` -> `ctrl + S` (first save):

    [test]
       first
       second

in `file.spec.js` -> `ctrl + S` (second save):

    [test]
       second
       first

Is it normal that the test execution queue is broken

part `package.json` with version libraries-

    {
      "devDependencies": {
        "@types/enzyme": "^3.1.9",
        "@types/enzyme-adapter-react-16": "^1.0.2",
        "@types/jasmine": "^2.8.6",
        "@types/react": "^16.1.0",
        "@types/react-redux": "^5.0.15",
        "@types/redux": "^3.6.0",
        "awesome-typescript-loader": "^5.0.0-1",
        "cross-env": "^5.1.4",
        "css-loader": "^0.28.11",
        "enzyme": "^3.3.0",
        "enzyme-adapter-react-16": "^1.1.1",
        "html-webpack-plugin": "^3.1.0",
        "jasmine": "^3.1.0",
        "jasmine-spec-reporter": "^4.2.1",
        "karma": "^2.0.0",
        "karma-chrome-launcher": "^2.2.0",
        "karma-jasmine": "^1.1.1",
        "karma-jasmine-html-reporter": "^1.0.0",
        "karma-sourcemap-loader": "^0.3.7",
        "karma-spec-reporter": "0.0.32",
        "karma-webpack": "^4.0.0-beta.0",
        "node-sass": "^4.8.3",
        "object-assign": "^4.1.1",
        "sass-loader": "^6.0.7",
        "style-loader": "^0.20.3",
        "typescript": "^2.8.1",
        "webpack": "^4.4.1"
      }
    }

Is bug?

**Comment by traxx02** [comment]
Jasmine version 2.3.4

**Comment by sgravrock** [comment]
This is by design. Jasmine 3 runs tests in random order by default, to make it easier to detect accidental state leakage between tests.

**Comment by christian-bromann** [comment]
@sgravrock is there an option to run them sequentially again? It is not the desired behavior when using Jasmine in context of e2e tests.

**Comment by slackersoft** [comment]
Jasmine does have the ability to configure whether your specs run in a random order. Which library you're using to execute your suite will determine the exact mechanism. The `jasmine` packages for ruby, python, and node.js all support a `random` option in their respective config files or some ability to pass `true` or `false` in from the command line. Other libraries like karma or protractor should have their own configuration format as well.

The goal behind this change is that specs should be independent enough from each other that change the execution order shouldn't affect the outcome.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
If the order of execution is important for your testing that order should be encapsulated within a single test. Multiple tests should typically indicate different test cases. I usually build these kinds of things up as a single "happy path" test through the system to make sure all the wizard pages are wired up to each other correctly, and then use unit tests to check all of the edge cases for a given page.

While you convert, or if you don't want to, you should be able to use `jasmine.getEnv().randomizeTests(false)` in your boot.js or a helper before test execution begins.

Hope this helps. Thanks for using Jasmine!

**Comment by rm185033** [comment]
Thanks for the suggestion, it definitely helps. 
I understand what you are saying.  
In the hindsight, I now feel that my intention to split the transaction flow into specs was more to annotate the logical flow (using specs...state a- spec1, state b -spec2...etc), rather than testing any substantial in each spec (which i could have done in a single test spec as you suggested).

I am now changing the suite/spec structure , so randomizing the test runs will not affect their order of execution. This makes so much sense to me now.
Thanks again.
