### ISSUE TITLE
Extend the interface of all Expectations by the `optionally` function/keyword. 

### ISSUE THREAD

**Issue by wzr1337** [jasmine/jasmine#1539]
## Feature request

Extend the interface of all Expectations by the `optionally` function/keyword. 

=> Apply a certain expectation if and *only if* property is existing.

==> It does not matter if it does not exist, but if it does, expect it to be of certain shape..

## technical Solution

In `  function Expectation(options) {` I would love to see code like:
```
    this.isOptional = options.isOptional;
```

In `Expectation.prototype.wrapCompare` I would love to see something like:
```
      function defaultOptionalCompare() {
        if (args[0] != null) {
            return matcher.compare.apply(null, args);
        }
        return { pass: true };
      }
      if (this.isOptional) {
        matcherCompare = defaultOptionalCompare;
      }
```

In `Expectation.Factory` add code like:
```
    options.isOptional = true;
    expect.optionally = new Expectation(options);
```

**Comment by slackersoft** [comment]
Your tests should be deterministic enough that you will always know whether you have an object or not. An optional expectation format makes it easy to have tests that give a false positive. If you `expect` something to be someway, but it's `null` or `undefined`, it is by definition not as you expect. It is therefore better for the test framework to tell you this so you can fix the bug, then allow you an easy way to paper over it to make your suite green.

If you have a spec that can't know what it is getting back, how can you tell it is doing anything correctly. For example, say I have:

```javascript
expect(randomStuff()).optionally.toEqual({ foo: 'bar', baz: 'quux' });
```

And someone changes `randomStuff` to always return `null`. This expectation will continue to pass even though the functionality, we were previously testing has been completely removed.

If you testing a component that relies on `Math.random`, I would suggest injecting a collaborator that wraps it so you can control the randomization in your tests.

This isn't functionality that we want in Jasmine, so I'm going to close this.

Hope this helps. Thanks for using Jasmine!
