### ISSUE TITLE
Option to set random order for a single suite?

### ISSUE THREAD

**Issue by colinjoy** [jasmine/jasmine#1541]
With ^3.0.0, is it possible to set the random option for a single suite (describe) as well?
We'd like to use random: true as a default to encourage properly encapsulated tests, but will need to keep the old non-random behaviour for a number of legacy specs until they can be migrated.

**Comment by sgravrock** [comment]
No, the randomization settings are global.

How frequently does your team write tests that aren't properly encapsulated from each other? If it's frequent enough to be cause for concern, then it might be worth running the legacy specs in a separate invocation of Jasmine that runs with randomization off. That way you could turn it on immediately for the remaining specs. On the other hand, if this is just a "once in a blue moon" problem, it might be better to save the effort and just leave randomization off until all the legacy tests are converted.
