### ISSUE TITLE
.toEqual & .toBe is not a function - Build breaks

### ISSUE THREAD

**Issue by muthucse7** [jasmine/jasmine#1542]
Hi All,

I am new to the angular/Jasmine frameworks. Can anyone advise me for the below issue? I saw other 's post but the anwser is not clear,

Package.JSON
 `{
  "name": "dashboard-kendo-ui",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@progress/kendo-angular-buttons": "^3.0.4",
    "@progress/kendo-angular-charts": "^2.0.3",
    "@progress/kendo-angular-dateinputs": "^2.2.0",
    "@progress/kendo-angular-dialog": "^3.4.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^2.1.2",
    "@progress/kendo-angular-inputs": "^2.2.0",
    "@progress/kendo-angular-intl": "^1.3.2",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-layout": "^2.2.1",
    "@progress/kendo-angular-popup": "^2.1.0",
    "@progress/kendo-angular-upload": "^3.0.3",
    "@progress/kendo-data-query": "^1.2.2",
    "@progress/kendo-drawing": "^1.5.2",
    "@progress/kendo-angular-ripple" : "^0.2.5",
    "@progress/kendo-theme-default": "^2.49.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    **_"jasmine-core": "~2.5.2",_**
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}`

![jasmine_issue](https://user-images.githubusercontent.com/3167071/38788144-35826378-4100-11e8-9039-c858d464ad4a.PNG)

**Comment by slackersoft** [comment]
Jasmine doesn't patch anything onto your existing objects, so you'll need to call `expect` to use Jasmine matchers. Based on your error message it might look something like:

```javascript
expect(coeGridTitle).toEqual('some thing')
```

For a bit more information take a look at the [your first spec tutorial](https://jasmine.github.io/tutorials/your_first_suite).

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this since we haven't seen any more discussion on this topic and it sounds like it might be an issue with the tests and not Jasmine itself.
