### ISSUE TITLE
Support for logging the expectation failure to the console in Jasmine.

### ISSUE THREAD

**Issue by applecool** [jasmine/jasmine#1549]
## Expected Behavior
When an expectation fails in a test spec, it would be great to show the line number of the assertion in the console of the browser. 

## Current Behavior
Currently, when an expectation fails, there is no information to the developer which line it has failed.

## Possible Solution
Adding `console.error()` or `console.log()` to the `expectationFailureFactory` maybe? I am not really sure about it. Sorry about the ignorance.

## Suite that reproduces the behavior (for bugs)
```javascript
describe("sample", () => {
  it('test', () => {
  expect(true).toBe(false); 
 }
});
```
## Context
In the above spec, the expectation fails on line 3. It would be great to see that in the console of the browser with the expectation failure message.

## Your Environment
* Version used: Jasmine 2.9.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 65, node 9.4
* Operating System and version (desktop or mobile): MacOSX High Sierra.

Note: It already logs the range of line numbers (of the spec) to the browser like here:     
`at eval (http://localhost:3000/build/exp/chains/test.spec.js?1524674:24:30)` which indicates the error is from 24 to 30 but not precisely the expectation line.

**Comment by applecool** [comment]
@slackersoft Any advice on workarounds?

**Comment by applecool** [comment]
I found the workaround by adding the customReporter. Closing this.

**Comment by slackersoft** [comment]
If you would like to see the error details in the browser console _as well_ as in the page where Jasmine displays your results, a custom reporter is indeed probably the correct solution. If you're just looking to see the stacktrace and error details in your browser, this should already be visible in the page.

Hope this helps. Thanks for using Jasmine!

**Comment by applecool** [comment]
@slackersoft Yup, that's what I did :) Thank you :)
