### ISSUE TITLE
Mark test suite as ordered/serial

### ISSUE THREAD

**Issue by the-spyke** [jasmine/jasmine#1557]
Is there a way to create a suite that runs specs in order? I don't need to set it globally, just for some special suites. Something like:

```javascript
describe_ordered("sample", function() {
});
```

## Your Environment

Jasmine 3.1.0

**Comment by slackersoft** [comment]
Jasmine does not have a way to specify that a suite (and its children) are to be run with the global randomization options overridden. I don't think this is a feature we're looking to add to Jasmine either. It would be pretty complex to add and maintain for not much added benefit.

If you're in the process of moving your full suite to be able to execute randomly, you could look at having  two suites, one that uses randomization, and one that doesn't, and use those to manage your migration.

Hope this helps. Thanks for using Jasmine!

**Comment by the-spyke** [comment]
That's exactly what I wanted to do, but I don't see any other options except running them separately.

**Comment by slackersoft** [comment]
It should also be possible to spot check your suite periodically to see if it is able to be run with randomization. Depending on how big your suite is and how many specs currently need to be run in order, you could also just bite the bullet and turn randomization on and fix the resulting issues.
