### ISSUE TITLE
How to exclude some spec files in jasmine?

### ISSUE THREAD

**Issue by Chinmoy-globalIds** [jasmine/jasmine#1560]
Is there any way to exclude some spec files with in a directory in jasmine?
For example, I want to exclude all spec in the extended folder from Foo folder.

    ```
    ├── Foo
    │   ├── sub
    |   |    |
    |   |    |--extended
    │   │         ├── a-spec.js
    |   |         ├── e-spec.js
    │   ├── b-spec.js
    │   ├── c-spec.js
    │   ├── d-spec.js
    └── 
    ```

I have tried with folowing jasmin.json.But this is not working.

        {
        "spec_dir": "Foo/",
        "spec_files": [
            "**/*[sS]pec.js",
            "!**/extended/*.js"
        ]
    }

**Comment by jakub-g** [comment]
@Chinmoy-globalIds I have the similar problem, how did you solve it?

**Comment by slackersoft** [comment]
@jakub-g what version of Jasmine are you using? The exclude syntax was introduced in v3.3, so you might just not be using a version that supports it.

**Comment by jakub-g** [comment]
@slackersoft I was checking with jasmine-core 3.3.0 and 3.4.0

**Comment by slackersoft** [comment]
The exclude syntax is part of the wrapping `jasmine` library, not `jasmine-core`. Jasmine-core doesn't really know anything about loading files. Are you using jasmine as a standalone, the `jasmine` package from npm, or something else?
