### ISSUE TITLE
Question: How to use a custom matcher when using toHaveBeenCalledWith

### ISSUE THREAD

**Issue by StefH** [jasmine/jasmine#1564]
The following test-case verifies if the service (which uses Angular HttpClient to do a post request) does indeed use certain headers.

I want to write some custom matching code to check if the headers contains a certain key and value, like:

```js
headers.get('Session') === 'abc'
```

My question is what to write at the **???** in below example?
``` js
spyOn(http, 'post').and.returnValue(new Observable<Response>());

const result = service.Post<string>(data);

assert.isNotNull(result);

expect(http.post).toHaveBeenCalledWith(`http://localhost/odata/Employees`, jasmine.any(String),
    {
        headers: // ???,
        observe: 'response'
    });

```
Is this possible?

**Comment by slackersoft** [comment]
You should be able to use something like the [stringMatching](https://jasmine.github.io/api/edge/jasmine.html#.stringMatching) asymmetric matcher. You can also build your own by passing in an object that has an `asymmetricMatch` function on it, admittedly our documentation for this isn't very good.

Hope this helps. Thanks for using Jasmine!

**Comment by StefH** [comment]
Some documentation on this functionality, especially writing typescript code would indeed be helpfull.

For now I ended up with this matcher class:
``` ts
class HttpHeadersMatcher {

    constructor(private check: { [name: string]: string }) {
    }

    public asymmetricMatch(options: any): boolean {
        const headers: HttpHeaders = options.headers;

        assert.equal(options.observe, 'response');

        Object.keys(this.check)
            .forEach((key: string) => {
                assert.equal(headers.get(key), this.check[key], `The header '${key}' does not have the correct value`);
            });

        return true;
    }

    public jasmineToString(): string {
        return `<HeaderMatching: ${JSON.stringify(this.check)}>`;
    }
}
```

Which is used like:
``` ts
expect(http.post).toHaveBeenCalledWith(`http://localhost/odata/Employees`, jasmine.any(String), new HttpHeadersMatcher({ 'Session': 'abc' }));

```

My project and example code can also be found here: [angular-odata-es5 : angularODataService.spec.ts](https://github.com/StefH/angular-odata-es5/blob/master/test/angularODataService.spec.ts#L13)
