### ISSUE TITLE
Env() properties are sorely lacking JavaDoc

### ISSUE THREAD

**Issue by ajvincent** [jasmine/jasmine#1565]
https://jasmine.github.io/api/3.0/Env.html
"Documentation generated by JSDoc 3.5.5 on ..."

Only one method of the created Env instance has JavaDoc comments on it (addReporter), and that's the only one documented in the generated Env page.

I noticed this because Jasmine 3.0 randomizes the order of tests by default, per release notes.  For my testing, that's bad because I often place simpler tests earlier than more complex ones.  If I call `jasmine.getEnv().randomizeTests(false)`, I _think_ that will solve the problem for me.  But I am not sure because the documentation doesn't say anything about this new method.

**Comment by slackersoft** [comment]
You're right. In the first pass for the API docs, we focused on getting the primary use cases populated. There is a lot of stuff on `Env` that is wrapped up in other interfaces, but things like this are currently used directly from `jasmine.getEnv()`.

We would be happy to review a pull request here to add the appropriate documentation comments to Env.js to document `randomizeTests` and any other things that appear to be missing.

Hope this helps. Thanks for using Jasmine!

**Comment by ajvincent** [comment]
Nice.  So how do we get the documentation page refreshed?

**Comment by slackersoft** [comment]
Sorry about that, it looks like I named them incorrectly for JSDoc and it didn't put them on the right page. The [edge Env page](https://jasmine.github.io/api/edge/Env.html) is updated correctly now.
