### ISSUE TITLE
jitSpy = spyOn(window, 'Function').and.callThrough(); breaks Jasmine

### ISSUE THREAD

**Issue by mhevery** [jasmine/jasmine#1573]
Imagine you would like to spy on `new Function()` calls. This may be accomplished in your tests by something like so:
```
const mySpy = spyOn(window, 'Function').and.callThrough();
```

This works great as expected except if one would like to test with clock. In that case it fails with NullPointerException. The crux of the problem is code which contains `Function.prototype.apply.apply:
- https://github.com/jasmine/jasmine/blob/74287c578cb7a9c5a775fba849f8e7c71f6c8194/src/core/Clock.js#L90-L96
- https://github.com/jasmine/jasmine/blob/8bb0e2d494eff37fa19cf1d50066b8cf225f603a/src/core/QueueRunner.js#L54-L60
- https://github.com/jasmine/jasmine/blob/9ee7b4ee0b60a734f6f4beb7087fc2e766a42d0d/src/core/ClearStack.js#L44-L46

With spy enabled on `Function` `Function.prototype.apply.apply` raises NPE because `Function.prototype.apply` is not defined. 

The issue is that `spyOn` replaces native `Function` with an instance of `Function` which no longer has the `prototype`.

## Suggested Fix.

In all cases where `Function.prototype.apply.apply` is invoked, replace it with.
```
// Place the next line at top of the file in the outer most context so that `Function.prototype`
// can be captured early.
const Function_prototype = Function.prototype;


function someFunction() {
  // Now even if `Function` gets replace in `spyOn` the code works fine 
  // Since we are working with the original Function.prototype
  Function_prototype.apply.apply(...);
}
```

## Simple workaround in tests
For users of `jasmine` which may run into this problem the following line fixes the issues in your test.
```
const mySpy = spyOn(ɵglobal, 'Function').and.callThrough();
// Patch prototype due to spying on the Function
Function.prototype.apply = Function.constructor.prototype.apply;
```

**Comment by nitobuendia** [comment]
Clock.js also uses Array.prototype.

https://github.com/jasmine/jasmine/blob/74287c578cb7a9c5a775fba849f8e7c71f6c8194/src/core/Clock.js#L168-L168

Even if the `const Function_prototype = Function.prototype;` is applied, using `spyOn(window, 'Array');` would make jasmine fail again. Trying to capture all possible window Objects like this would be tedious and not a very good practice to be populating the global space or even namespace.

----

**Approach 1**

One suggestion here is delegating the `prototype` property as to the original object. This is:
`wrapper.prototype = originalFn.prototype;`

This would change:
https://github.com/jasmine/jasmine/blob/12f56fdb7de6680a1d4c6fb0a53ca9bc42b083fc/lib/jasmine-core/jasmine.js#L5649-L5655

Into:
```
    for (var prop in originalFn) {
      if (prop === 'and' || prop === 'calls') {
        throw new Error('Jasmine spies would overwrite the \'and\' and \'calls\' properties on the object being spied upon');
      }

      wrapper[prop] = originalFn[prop];
    }
    if (originalFn && originalFn.prototype) {
      wrapper.prototype = originalFn.prototype;
    }
```

The only drawback I can foresee with this approach is that if we try to prototype something on the spy, we would be actually prototyping it on the original object.

----

**Approach 2**
One idea here to avoid this would be only mapping the methods that are required:
```
    if (!wrapper.prototype) wrapper.prototype = {};
    if (originalFn && originalFn.prototype) {
      wrapper.prototype.apply = originalFn.prototype.apply;
      wrapper.prototype.call = originalFn.prototype.call;
      wrapper.prototype.slice = originalFn.prototype.slice;
      wrapper.prototype.join = originalFn.prototype.join;
    }
```

This has the advantage of just being a "read" of methods. Adding new prototypes would be destroyed with the wrapper. However, now we are back to the point of continuously having to add all the prototype methods which is not ideal.

----

**Approach 3**

The former can also be solved by simply copying the prototype for non-replace methods.
```
    if (!wrapper.prototype) wrapper.prototype = {};
    if (originalFn && originalFn.prototype) {
      wrapper.prototype = Object.assign(
        originalFn.prototype,
        wrapper.prototype,
      );
    }
```

------


I have done a small quick test:

test.js
```
describe('ClockSpyErrorTest', () => {
  beforeEach(() => {
    jasmine.clock().install();
  });

  afterEach(() => {
    jasmine.clock().uninstall();
  });

  it('equals true', () => {
    spyOn(window, 'Array');
    spyOn(window, 'Function');
    expect(true).toBe(true);
  });
});
```

Without any changes, the test breaks with the following console errors:
```
jasmine.js:5044 Uncaught TypeError: Cannot read property 'apply' of undefined
    at QueueRunner.clearTimeout (jasmine.js:5044)
    at cleanup (jasmine.js:5058)
    at jasmine.js:5000
    at QueueRunner.attempt (jasmine.js:5128)
    at QueueRunner.run (jasmine.js:5149)
    at runNext (jasmine.js:5075)
    at next (jasmine.js:5082)
    at QueueRunner.onComplete (jasmine.js:5000)
    at jasmine.js:5165
    at MessagePort.channel.port1.onmessage (jasmine.js:2317)
QueueRunner.clearTimeout @ jasmine.js:5044
cleanup @ jasmine.js:5058
(anonymous) @ jasmine.js:5000
attempt @ jasmine.js:5128
QueueRunner.run @ jasmine.js:5149
runNext @ jasmine.js:5075
next @ jasmine.js:5082
(anonymous) @ jasmine.js:5000
(anonymous) @ jasmine.js:5165
channel.port1.onmessage @ jasmine.js:2317
jasmine.js:3007 Uncaught TypeError: Cannot read property 'call' of undefined
    at onerror (jasmine.js:3007)
```


With the `const Function_prototype = Function.prototype;` solution, the test fails with:
```
TypeError: Cannot read property 'call' of undefined
    at <Jasmine>
    at UserContext.it (file:///Users/nito/Google%20Drive/webapps/jasmine-test/test.js:13:18)
    at <Jasmine>
```

Adding  `const Array_prototype = Array.prototype;` makes the test pass. However, now we need to capture all potential prototype breaks such as:
- Array.prototype
- Function.prototype
- Object.prototype


Adding `wrapper.prototype = originalFn.prototype;` without any other of the previous changes also makes the tests pass. As well as any other of the other approaches suggested here.

Additionally, all the 3 approaches here passes all the tests using grunt.


@slackersoft Would you be willing to approve any of these changes?

**Comment by slackersoft** [comment]
My inclination for this is to add some helper methods to Jasmine's `util` object (`slice` and `join`) that wrap up the `Array` prototype stuff and reduce some of that groping out from the various places in Jasmine's codebase. I think I might actually look for a new thing in Jasmine (`timers`? maybe) that holds onto the originals and does the `apply`/`call` logic there when needed.

We might also want to do something like your option 1 (copying over the `prototype` of the function being spied upon), but that would be more to keep a users code working.

Hope this helps. Thanks for using Jasmine!
