### ISSUE TITLE
[v3.1.x] Potential regression with custom matcher usage

### ISSUE THREAD

**Issue by cexbrayat** [jasmine/jasmine#1574]
When using a custom matcher (like `toBeUseless` below)  inside a `then` method of a Promise, Jasmine will throw:

```
(node:41179) UnhandledPromiseRejectionWarning: TypeError: expect(...).toBeUseless is not a function
    at Promise.resolve.then (/Users/cedric/Code/tests/jasmine-v3-custom-matchers/spec/custom-matcher-in-promise.spec.js:19:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Expected Behavior

Let's consider a dumb custom matcher:

```javascript
const customMatcher = {
  toBeUseless: (util, customEqualityTesters) => ({
    compare: (actual, expected) => ({
      pass: true, message: 'useless'
    })
  })
}
```

Used a in unit test:

```javascript
describe('Custom matcher', () => {

  beforeEach(() => jasmine.addMatchers(customMatcher));
  
  it('should succeed', () => {
    expect(true).toBeUseless(true);
  });

  it('should succeed in promise', () => {
    Promise.resolve()
      .then(() => expect(true).toBeUseless(true));
  });

});
```

This will succeed if using Jasmine v2.99
You can check out a simple reproduction repository here: https://github.com/cexbrayat/jasmine-v3-custom-matchers/blob/master/spec/custom-matcher-in-promise.spec.js

## Current Behavior

The same unit tests using Jasmine v3.1 with the following error:

```
(node:41179) UnhandledPromiseRejectionWarning: TypeError: expect(...).toBeUseless is not a function
    at Promise.resolve.then (/Users/cedric/Code/tests/jasmine-v3-custom-matchers/spec/custom-matcher-in-promise.spec.js:19:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Note that the error for the unknown custom matcher only arises in the `then` case.

See the same reproduction repo, with this PR https://github.com/cexbrayat/jasmine-v3-custom-matchers/pull/1
A simple `npm install`, `npm test` will reproduce the issue.

## Possible Solution

Weirdly, registering the custom matcher again in the `then` makes the test pass:

```javascript
describe('Custom matcher', () => {

  beforeEach(() => jasmine.addMatchers(customMatcher));
  
  it('should succeed', () => {
    expect(true).toBeUseless(true);
  });

  it('should succeed in promise', () => {
    Promise.resolve()
      .then(() => {
        // register again the matcher
        jasmine.addMatchers(customMatcher);
        expect(true).toBeUseless(true);
      });
  });

});
```

## Suite that reproduces the behavior (for bugs)

See above or https://github.com/cexbrayat/jasmine-v3-custom-matchers

## Context

This bugs hits us when bumping an Angular project from Jasmine v2.99 to v3.1, in which we use custom matchers.

## Your Environment

* Version used: v3.1.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v8.11.2
* Operating System and version (desktop or mobile): MacOS 10.13.5
* Link to your project: 

Original issue: https://github.com/Ninja-Squad/globe42/pull/203 
Dumbed down repro: https://github.com/cexbrayat/jasmine-v3-custom-matchers

**Comment by cexbrayat** [comment]
Closing as it looks like:

**Comment by slackersoft** [comment]
Jasmine also supports returning a `Promise` from your specs, so `return Promise.resolve().then(...)` should also work without the `done` callback.
