### ISSUE TITLE
callFake on express route

### ISSUE THREAD

**Issue by tzjoke** [jasmine/jasmine#1577]
I am using Jasmine for test and meet some problems with `callFake`.

I fake `fetchPanelRowData` function in my test, but it still steps into original `fetchPanelRowData`.

express dashboardRouter:

```
exports.fetchPanelRowData = (req, res) => {
    ...
}
```

spec:

```
const request = require('supertest');
const app = require('../../app');
const dshRouter = require('../../routes/dashboardRouter');

describe('test dashboard router: ', () => {

    it('test fetchPanelRowData', async () => {
        spyOn(dshRouter, 'fetchPanelRowData').and.callFake((req, res) => {
            res.status(500).end();
        });

        let response = await request(app).post('/api/fetchPanelRowData');
        expect(response.statusCode).toBe(500);
        expect(dshRouter.fetchPanelRowData).toHaveBeenCalled();
    })
})
```

Any ideas?

**Comment by slackersoft** [comment]
How are you `require`ing your dashboardRouter in the code under test? `spyOn` works by replacing the function on the root object with a new function that is a spy, so if the live code saves a reference to the function itself, replacing it will happen too late.

**Comment by slackersoft** [comment]
Closing this since we haven't heard anything in a number of months.
