### ISSUE TITLE
beforeAll called non non-focused specs

### ISSUE THREAD

**Issue by rlotufo** [jasmine/jasmine#1578]
From my understanding, for the following tests, the `beforeAll` on the "disabled suite" should no be called, but it is.

```
describe.only("enabled suite", () => {
  it("enabled test", () => {
  });
});

describe("disabled suite", () => {
  beforeAll(() => {
    console.log("should not run");
  });

  it("disabled");
});
```
This is on 23.4.0.

## Your Environment

* Version used: This is on 23.4.0.

**Comment by slackersoft** [comment]
The `.only` suffix isn't the Jasmine mechanism to focus a suite or spec, Jasmine uses an `f` prefix, so `describe` becomes `fdescribe` and `it` becomes `fit`. Additionally, Jasmine is only up to version 3.1.0, not 23.4.0. That version number looks like it probably came from Jest and not Jasmine.

Hope this helps.

**Comment by rlotufo** [comment]
Indeed, I'm sorry, I posted this to the wrong project. We can close this.
