### ISSUE TITLE
pending() in beforeEach does not stop execution

### ISSUE THREAD

**Issue by webmaster128** [jasmine/jasmine#1579]
## Expected Behavior

Calling pending() in beforeEach should allow the user to prevent further execution of a spec.

## Current Behavior

Calling pending() in the spec itself stops spec execution while calling it in beforeEach only marks the test as pending but does not stop execution.

## Suite that reproduces the behavior (for bugs)

`./node_modules/.bin/jasmine --random=false dummy.spec.js` of

```js
describe("pending in body", () => {
  it("should not explode", () => {
    pending("Stop execution or things will explode");
    console.log("body: boom!");
  });
});

describe("pending in beforeEach", () => {
  beforeEach(() => pending("Stop execution or things will explode"));

  it("should not explode", () => {
    console.log("beforeEach: boom!");
  });
});
```

prints

```
Started
*beforeEach: boom!
*

Pending:

1) pending in body should not explode
  Stop execution or things will explode


2) pending in beforeEach should not explode
  Stop execution or things will explode

2 specs, 0 failures, 2 pending specs
Finished in 0.009 seconds
```
## Context

In our environment we want to selectively stop test execution for client-server tests when server is not there. Marking the spec as pending is not sufficient since a complex initialization is started that leads to some very hard to debug exceptions in afterAll.

## Your Environment
* node v8.10.0
* jasmine 3.1.0

**Comment by slackersoft** [comment]
The current mechanism for this is the `--stop-on-failure` CLI argument. This is also configurable in your jasmine.json as `stopSpecOnExpectationFailure`. If this isn't working with `pending()` we definitely need to fix that.

I would also be happy to review a pull request that makes `pending()` always behave as if `stopSpecOnExpectationFailure` is set.

Hope this helps. Thanks for using Jasmine!

**Comment by johnjbarton** [comment]
We hit a similar issue, but I am confused by the answer here.  

If we set `stopSpecOnExpectationFailure`, the `pending()` will work when called in `beforeAll()`?

**Comment by slackersoft** [comment]
`stopSpecOnExpectationFailure` should only affect what `pending` does in a `beforeEach` not a `beforeAll`. Jasmine runs a `beforeAll` as part of a suite, where a `beforeEach` is run as part of a spec.

**Comment by johnjbarton** [comment]
Thanks, so what should `pending()` mean in `beforeAll()`?  I believe the intention was for the entire suite to be set pending, but that was not the result.
