### ISSUE TITLE
[Question] Testing WebSockets with Jasmine

### ISSUE THREAD

**Issue by Jakems777** [jasmine/jasmine#1582]
Could some one please provide a working code example, on how to test WebSockets using Jasmine syntax and spies? (Do I need any additional libraries like Rxjs or what not?)

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this.
