### ISSUE TITLE
Error acessing availableMatchers on IE8

### ISSUE THREAD

**Issue by Tanato** [jasmine/jasmine#1584]
I'm running Jasmine with Karma on IE8 and there's a error occurring when Jasmine-core try to run through the array of `availableMatchers`.

The error is caused because IE8 treats arrays declarations syntax different of modern browsers, not allowing the last item to be postfixed with a comma without adding an extra `undefined` item to array like in the image bellow

![image](https://user-images.githubusercontent.com/1019940/43095719-1fd84f6c-8e8d-11e8-9591-71ac914aa733.png) 

## Expected Behavior
Jasmine core should iterate through `availableMatchers `array without issue on any compatible browser, like IE8.

## Current Behavior
Jasmine-core are throwing an exception when try to access the last item of `availableMatchers` (the undefined item that IE8 adds to array)

## Possible Solution
Remove comma after the last item on declaration of `availableMatchers`

## Your Environment

* Version used: Internet Explorer 8.0.7601.17514
* Environment name and version (e.g. Chrome 39, node.js 5.4): IE8
* Operating System and version (desktop or mobile): Windows 7

**Comment by slackersoft** [comment]
Jasmine 3.0 no longer supports IE 8 & 9 as more people move away from them. There are probably other things that also don't work there, and we decided it wasn't worth the effort to continue to maintain code to support these older browsers.

This isn't something we're looking to fix in future versions of Jasmine. Closing this.

Thanks for using Jasmine!
