### ISSUE TITLE
How to reuse code of 'it' block / Is there a way we can call 'it' block in other spec files?

### ISSUE THREAD

**Issue by bharukaRupesh** [jasmine/jasmine#1589]
Hi,

I have multiple spec files in which I want to reuse the code of 'it' block from some other spec file just to avoid code redundancy.

Is there a way to achieve this purpose?

**Comment by slackersoft** [comment]
If you have code that you want to test with something like a shared example, but doesn't make sense to be fully pulled out into a separate component, you should be able to write a function that makes specs.

I've done something like this before:

```javascript
function sharedExamples(args) {
  it('does something arg based', function () {
    // use the args and build your tests.
  });
}
```

In the future you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself. Closing. Thanks for using Jasmine!

**Comment by fetis** [comment]
@bharukaRupesh see this answer for an example https://stackoverflow.com/a/52446198/2145997

@slackersoft approach with args will fail in real life because args normally are defined on `beforeEach` section, whic invoked later than function call
