### ISSUE TITLE
Do not manage to import a module "User.findById is not a function"

### ISSUE THREAD

**Issue by nclsndr** [jasmine/jasmine#1591]
Hello there,

## Expected Behavior
I have 3 files:
```javascript
// user.js

const findById = async id => {
  //...
}

module.exports = {
  findById
}
```

```javascript
// auth.js
const User = require('../models/user')

const validateToken = async token => {
  // ...
  const user = await User.findById(id)
  return user
}

module.exports = { validateToken }
```

```javascript
// auth.spec.js
// ...
const auth = require('../../src/services/auth')
describe('validateToken', () => {
    const userData = {
      firstName: 'Nico',
      lastName: 'Andre',
      email: 'nicolas@any.com',
      password: 'myPassword'
    }
    let user
    beforeEach(async () => {
      user = await User.create(userData)
    })
    it('Should return a user', async () => {
      const token = auth.make(user)
      const { email, _id } = await auth.validateToken(token)
      expect(email).toBe(user.email)
      expect(_id).toBe(user._id)
    })
  })
```

So if not wrong, `auth.spec` imports `auth` that imports `user` yes but

## Current Behavior

I receive an error form the console:

```
Failures:
1) JWT Service validate Should return a user
  Message:
    TypeError: User.findById is not a function
  Stack:
        at <Jasmine>
        at Object.validate ([...]auth.js:38:27)
        at process._tickCallback (internal/process/next_tick.js:68:7)

Ran 1 of 30 specs
1 spec, 1 failure
Finished in 0.163 seconds
```

I already tried to exports a full defined object like: (didn't work)

```javascript
const core = { findById: findById }
module.exports = core
```

when I debug `User` > it's just an empty literal object (`{}`)

Did anyone experienced this type of bug? Or have any idea where to start investigating?

## Context

- Express app designed as an API
- **not** using Babel
- Model is managed by mongoose
- Node 10.8

Thanks a lot for your help

**Comment by slackersoft** [comment]
Do you have any spies installed anywhere or something else that might be changing the default behavior? I'm not able to run your example suite as it is written, so I'm using this example:

User.js
```javascript
module.exports = {
  findById: async id => await Promise.resolve('hi')
}
```
Auth.js
```javascript
const User = require('./user');

const validateToken = async token => {
  const user = await User.findById(token);
  return user;
};

module.exports = { validateToken };
```
Spec.js
```javascript
const auth = require('../lib/auth');

describe('validate', () => {
  it('works?', async () => {
    const result = await auth.validateToken(1);
    expect(result).toEqual('hi');
  });
});
```

And it is running correctly. If you can provide a runnable example suite that reproduces the issue, that would greatly help with diagnosing and fixing the error.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything further to help diagnose this issue, so I'm going to close it. If you have more information please comment here and we can look into it further.

Thanks!
