### ISSUE TITLE
In npm is last 3.2.0 not 3.21

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1592]
From npm is not possible install last version 3.2.1

**Comment by slackersoft** [comment]
Only the jasmine-core package was updated to 3.2.1. The jasmine package depends on jasmine-core with a `~3.2.0` version spec which should allow installation of 3.2.1 of jasmine-core.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
If this versioning strategy is causing issues for installing things in node.js, I would love to have that discussion, but my understanding is that it is possible to update `jasmine-core` as long as `jasmine` works with the later version.
