### ISSUE TITLE
Improve exception formatter

### ISSUE THREAD

**Issue by giniedp** [jasmine/jasmine#1594]
## Expected Behavior
If an expectation fails because of an ErrorEvent it should print at least the message of that ErrorEvent object.

## Current Behavior
The printed message is simply `[object ErrorEvent] thrown`

This is because the ErrorEvent object does not have a `name` property, so it drops into the else case in the ExceptionFormatter here https://github.com/jasmine/jasmine/blob/master/src/core/ExceptionFormatter.js#L8

## Possible Solution
The exception formatter could be changed, so that it can handle the ErrorEvent object which is described here https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent

## Suite that reproduces the behavior (for bugs)
https://stackblitz.com/edit/jasmine-error-event

**Comment by slackersoft** [comment]
This sounds like a nice addition. I would be happy to review a pull request to add support for printing the `message` for a thrown object that doesn't also have a `name` property.

Thanks for using Jasmine!

**Comment by armand2099** [comment]
It will be great if the script line could be printed when an exception fails instead of:
Failure: Expected true to be false.
Currently I'm using:
expect(btn.enabled).toBe(false, "[TS:" + Error().lineNumber + "] Button should be disabled");

**Comment by nitobuendia** [comment]
Sent PR #1601 to cover @giniedp proposal.
