### ISSUE TITLE
Spy a method having multiple arguments and a callback

### ISSUE THREAD

**Issue by swayangjit** [jasmine/jasmine#1603]
When ever a method is having more than 1 argument I cant stub a method. 

### Component
```javascript
service.myMethod(reqBody,true, false, false, (success) => {

    },(failure)=>{

    });
```
### test
```javascript
const service = TestBed.get(Service);
spyOn(service, 'myMethod').and.callFake(function (reqBody, success,error) {
        return success({});
    });
```
It throws error "success is not a function."

```javascript
spyOn(service, 'myMethod').and.callFake(function (reqBody,true,false,false, success,error) {
        return success({});
    });
```
It throws compilation error.
## Your Environment
"jasmine": "^2.99.0"

**Comment by nitobuendia** [comment]
This is not a problem with Jasmine, but with your function definition.

Try with:
```
spyOn(service, 'myMethod').and.callFake(function (reqBody, boolean1, boolean2, boolean3, success, error) {
        return success({});
    });
```

I think you are mixing between defining functions and passing parameters to them.
boolean1, boolean2, boolean3 will receive the values "true, false, false", but you cannot define them on the function level.


I have created a JSFiddle to illustrate it: http://jsfiddle.net/ej5ubzxn/
The test passes and you can see {'it': 'worked'} on the console log too.

**Comment by swayangjit** [comment]
Thanks, @nitobuendia . It's working now.
