### ISSUE TITLE
trigger afterAll on error

### ISSUE THREAD

**Issue by tahayk** [jasmine/jasmine#1609]
I'm trying to write end-2-end tests using the Jasmine framework with `selenium-webdriver`, 
my problem is that the browser doesn't close when an element not found.

PS: the code that closes the brower is in the `afterAll` function, 
PS: I don't want to add `.catch` call at the end of `it` because I'm goint to have many `it`s and I don't want to repeat it multiple times

this is my spec code:

```
const webdriver = require('selenium-webdriver');
const until = webdriver.until;

const capabilities = {
    "browserName": "chrome",
    "platform": "any"
};
describe('my spec', function () {
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 60000;
    waitTimeout = 20000;

    beforeAll(function (done) {
        this.driver = new webdriver
            .Builder()
            .usingServer("http://127.0.0.1:4444/wd/hub")
            .withCapabilities(capabilities)
            .build();
        this.driver.then(done);
    });

// --------- this function is not triggered if an element is not found
    afterAll(function (done) {
        this.driver.quit().then(done);
    });


    it('test name 1 should succeed', function (done) {

        this.driver.get("http://127.0.0.1:8800")

        // wait for element to be present
//--------- the element #packageAddressSearchHome is not present, so it should fail
            .then(_ => this.driver.wait(until.elementLocated(webdriver.By.css("#packageAddressSearchHome")), waitTimeout, "the element #packageAddressSearchHome is not present"))
            .then(_ => this.driver.findElement(webdriver.By.css("#packageAddressSearchHome")))
            .then(element => {
                // wait for element to be displayed
                this.driver.wait(_ => element.isDisplayed(), waitTimeout, "the element #packageAddressSearchHome is not visible");
                // element is enabled
                this.driver.wait(_ => element.isEnabled(), waitTimeout, "the element #packageAddressSearchHome is not enabled");
                return element.sendKeys("Paris");
            })

            .then(done)
    });

});

```

PS: I'm new to jasmine-selenium-webdriver, so maybe the code I wrote is wrong
any idea how to fix it ? and thanks

**Comment by slackersoft** [comment]
Jasmine should always invoke your `afterAll` callbacks unless you're using the failFast option. This seemed like a reasonable decision for other types of specs, but is probably not the right decision for selenium uses, or other things that definitely need to be torn down.

I would be happy to review a pull request to change the way the `TreeProcessor` invokes the `queueRunnerFactory` to pass in `afterAll` callbacks as cleanup functions so they will always be invoked.

Thanks for using Jasmine!

**Comment by tahayk** [comment]
Thank you very much for the hint @slackersoft , it was my mistake, I set `stopSpecOnExpectationFailure` to true in the `jasmine.json` config file, now it works fine as expected.

**Comment by razielron** [comment]
Hi, I have the same issue where I turned failFast flag to True and the afterAll isn't invoked.
Is there a way to bypass this and make the afterAll to run no matter the test status?

**Comment by slackersoft** [comment]
@razielron See [my earlier comment](https://github.com/jasmine/jasmine/issues/1609#issuecomment-426036805). We would still be happy to review a pull request to change this behavior specifically for `afterAll` even if the original issue reporter has solved their immediate issue.
