### ISSUE TITLE
Error: Expected [ 'Array', 'Contents' ] to be [ 'Array', 'Contents' ].

### ISSUE THREAD

**Issue by TheeRFG** [jasmine/jasmine#1614]
When comparing two arrays in my test framework `expect(['Array', 'Contents']).toBe(['Array', 'Contents']);` Jasmine reports an error in that `Expected [ 'Array', 'Contents' ] to be [ 'Array', 'Contents' ]. ` Jasmine is truly mad about the fact that the address pointers for both of these arrays is not the same regardless of their contents. The first `[ 'Array', 'Contents' ]` is *not* the second `[ 'Array', 'Contents' ]`. While it isn't a huge deal, I would maybe expect some sort of error message explaining that.

## Expected Behavior
I would expect some error message or some way of implying that the base address of my arrays is not the same and therefore they are not the same object.

## Current Behavior
Right now jasmine reports `Expected [ 'Array', 'Contents' ] to be [ 'Array', 'Contents' ]. `

## Possible Solution
A new error message that tells me the base addresses of my arrays is not the same and they are not the same object because of that. Ideally, I think there could be something that suggests that I should use toEqual to compare the contents of my arrays instead, maybe if it notices their contents are similar. 

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() { 
    expect(['Array', 'Contents']).toBe(['Array', 'Contents']);
});
```
## Context

Again, this isn't a huge deal. Maybe I shouldn't assume the worst of people, but I feel like had I not been more informed and actually known what the issue was, this could have been a very frustrating error to come across. In every way, it looks like the first array should be the second array as reported by Jasmine, and I think it would be a frustrating experience to see something that looks like it should be working, but is still upset and wrong.

**Comment by slackersoft** [comment]
If you want a deep equality of your objects you should be using `toEqual` instead of `toBe`. As I write this up _again_ though, you're probably correct, that an additional note for `toBe` that mentions deep equality vs object equality would be useful. I'd be happy to review a pull request to update the failure message for `toBe`.

Hope this helps. Thanks for using Jasmine!
