### ISSUE TITLE
bug: PrettyPrinter fails in IE11

### ISSUE THREAD

**Issue by Havunen** [jasmine/jasmine#1618]
IE10 - IE11 
do not support outerHTML or innerHTML property for SVG elements.

error
`Unable to get property 'indexOf' of undefined or null reference`

Code:

https://github.com/jasmine/jasmine/blob/110c092c9ece00cd6c882bd573b911c35ff73478/src/core/PrettyPrinter.js#L230-L240

Work around could be that we create 'div' element and clone that node there and read divs innerHTML.

**Comment by mdomi** [comment]
Seeing the same behavior in PhantomJS 2.

**Comment by slackersoft** [comment]
That sounds like a good plan. I would be happy to review a pull request that detected DOM elements without `innerHTML` or `outerHTML` and uses some other mechanism to print, possibly even falling back to putting the `tagName` inside some `<` and leaving it at that.
