### ISSUE TITLE
afterAll not working with fit

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1619]
if  test contains afterAll() and fit(), then afterAll is ignored.

Probably same problem will have afterEach()

**Comment by slackersoft** [comment]
Can you provide a bit more information or an example suite to show the issue? When I run the following suite, it I see the `console.log` output just fine.

```javascript
describe('foo', function() {
  afterAll(function() {
    console.log('hi there');
  });

  fit('things', function() {
    expect(true).toBe(true);
  });
});
```

Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this since we haven't received any more information to help track down an issue. Please let us know if you have more details.
