### ISSUE TITLE
Jasmine cancels callback execution when unsubscribe is called

### ISSUE THREAD

**Issue by kno** [jasmine/jasmine#1620]
I've created this stackblitz to representate the bug:
 https://stackblitz.com/edit/jasmine-testing-r6bpfh

To execute the code in normal mode you must change the TEST variable to false in main.ts and reload the live preview window. You can click on button and then in 'yes' or 'no'. You can see how the 'dialogIsOpen' variable is being changed from false, to true and then again to false, because the callback function is fully being executed.

In test mode (set TEST variable to true and reload the preview window) the test fails because the callback function execution is being cancelled on unsubscribe call.

## Expected Behavior
Continue the execution of the current callback in test.

## Current Behavior
The callback execution is being cancelled after calling unsubscribe.

## Suite that reproduces the behavior (for bugs)
https://stackblitz.com/edit/jasmine-testing-r6bpfh
## Context
I can't test callbacks with unsubscribe methods.

## Your Environment
* Version used: 3.1.0
* Environment: Chrome  70.0.3538.67 32 bits
* Operating System and version (desktop or mobile): Windows 10

**Comment by slackersoft** [comment]
If you need callback or other asynchronous behavior, make sure you're taking advantage of Jasmine's [async functionality](https://jasmine.github.io/tutorials/async) to ensure that the framework knows when your tests having completed. By default all Jasmine tests are synchronous, and will move on to the next test as soon as the `function` passed in returns.

Hope this helps. Thanks for using Jasmine!

**Comment by kno** [comment]
Thanks @slackersoft , but I think this is not a problem with callback: If you comment the line 23 in app.component.ts in the example (the unsubscribe call) the callback is fully executed and the test pass, but with this line, the callback execution is cancelled and it shoun't be cancelled, only it shouldn't be called again.

**Comment by slackersoft** [comment]
It looks like this that `unsubscribe` call is throwing an error. When I open up the the developer console, I see:

```
Uncaught TypeError: Cannot read property 'unsubscribe' of undefined
    at SafeSubscriber.eval [as _next] (app.component.ts:27)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:270)
    at SafeSubscriber.next (Subscriber.ts:212)
    at Subscriber._next (Subscriber.ts:141)
    at Subscriber.next (Subscriber.ts:101)
    at Observable.eval [as _subscribe] (scalar.ts:5)
    at Observable._trySubscribe (Observable.ts:224)
    at Observable.subscribe (Observable.ts:205)
    at AppComponent.openDialog (app.component.ts:26)
    at UserContext.eval (app.component.spec.ts:37)
```

It looks like a couple of things are happening here.

1. Something in that call chain seems to be actually `catch`ing the error and preventing it from making it all the way up to Jasmine to be reported to you.
1. Something (possibly the same thing) is causing that callback to be invoked inline, in such a way that your reference to `dialogSub` hasn't actually been assigned to yet, causing the error to be thrown.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't seen any more information to help diagnosing an issue with Jasmine itself, so I'm going to close this. If you have some more information, please let us know so we can investigate further.
