### ISSUE TITLE
TypeError when use jasmine^3.0 

### ISSUE THREAD

**Issue by ShengYenPeng** [jasmine/jasmine#1624]
I get error messages when use jasmine^3.0 to run sample code(src/Player.js and src/Song.js), 
but jasmine works well when I use jasmine 2.99.

![image](https://user-images.githubusercontent.com/16522555/48454922-34e10a00-e7f4-11e8-9e6e-43aeeab62292.png)

The browser information (the browser version is older since I use Qt4.8 webkit to implement) :
![image](https://user-images.githubusercontent.com/16522555/48454865-fcd9c700-e7f3-11e8-8478-1a3fe1f8b387.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/16522555/48454747-7a510780-e7f3-11e8-9295-8e96f3f549ac.png)

**Comment by slackersoft** [comment]
What version of Firefox are you running then? One of the major things that happened when we released Jasmine 3.0 is dropping support for older browsers.

**Comment by ShengYenPeng** [comment]
it looks like that the version of browser is Safari/534.34

**Comment by slackersoft** [comment]
Based on [the wikipedia Safari history page](https://en.wikipedia.org/wiki/Safari_version_history) it looks like that UserAgent string maps to Safari version 5, which is no longer supported by Jasmine as of the 3.0 release.

Closing.
