### ISSUE TITLE
Add a `toBeRejectedWithError` async matcher

### ISSUE THREAD

**Issue by sirlantis** [jasmine/jasmine#1625]
## Expected Behavior

I want to test to use the `toThrowError` utility matcher on an asynchronous operation which rejects with a given error.

## Current Behavior

API is not available - but [`eq`](https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js#L111-L117) and `objectContaining` works as interim solutions.

```
await expectAsync(boom()).toBeRejectedWith(new TypeError("BOOM"))
await expectAsync(boom()).toBeRejectedWith(jasmine.objectContaining({ message: "BOOM" }))
```

## Possible Solution

Jasmine already has `toThrowError` besides `toThrow` to make it easier matching against errors with various overloads.

```
expect(foo).toThrowError("foo bar baz");
expect(foo).toThrowError(/bar/);
expect(foo).toThrowError(TypeError);
expect(foo).toThrowError(TypeError, "foo bar baz");
```

Having `toBeRejectedWithError` besides `toBeRejectedWith` with the same overloads would be quite intuitive.

It seems that would require extracting some code from `toThrowError` first.

I wonder whether that extracted code could live in a `jasmine.error` asymmetric matcher instead though (meaning that ultimately `toThrowError` could be deprecated).

**Comment by sirlantis** [comment]
I can take on that issue, just wanted to gather some opinions before doing some refactoring.

**Comment by slackersoft** [comment]
I would be happy to review a pull request to add a `toBeRejectedWithError` matcher. I'm not entirely sold on the usefulness of a `jasmine.error` asymmetric equality tester, but I'm willing to discuss that. I think you're correct that there is probably some common code that would be able to be pulled out between `toThrowError` and `toBeRejectedWithError`, and I think that would make sense as part of a PR for this if you find something that looks good.

**Comment by webmaster128** [comment]
Love and thumbs up for @sirlantis. You are our man!

I did not know about `toBeRejectedWith` (missing in TypeScript types?), but our current workaround looks like:

```ts
await connection
  .getItem(1234)
  .then(() => fail("promise must be rejected"))
  .catch(err => expect(err).toMatch(/Item 1234 doesn't exist yet/));
```
