### ISSUE TITLE
Test fails when NGRX action contains observable

### ISSUE THREAD

**Issue by TKul6** [jasmine/jasmine#1626]
## Expected Behavior
Test based on NGRX should pass when an Action contains observable.

## Current Behavior
When testing effects and the expected observable contains action **That contains another observable** jasmine throws:
`Expected $[2].notification.value.payload.commands[0].active._subscribe = Function to equal Function.`

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
it('should not crash', () => {
  
      const expectedStream$ = cold('--b', {b: new successAction(Observable.of(true))});

        // Act
        actions$ = hot('--a', {a: new MyAction()});

        // Assert
        expect(effects.MyEffect$).toBeObservable(expectedStream$);
});
});
```
## Context
I have an ngrx effect that throws Action containing an observable.
When I'm testing the effect I get: 'Expected $[2].notification.value.payload.commands[0].active._subscribe = Function to equal Function.`

## Your Environment

Node: 9
Chrome: 70 
Jasmine: 3.3.0

**Comment by TKul6** [comment]
Thanks @ohjames  I think it might work, I'll check it and let you know ASAP.

**Comment by sgravrock** [comment]
I'm going to go ahead and close this as it's been quite some time since we've heard anything. Feel free to reopen if you think there's still something here that we can help with.
