### ISSUE TITLE
Unclear deprecation messages

### ISSUE THREAD

**Issue by cliff76** [jasmine/jasmine#1628]
The deprecation messages issued when using the default configuration generated by jasmine init does not explain any remediation. 

## Expected Behavior
When installing Jasmine and generating a config using jasmine init it should use up to date configuration syntax. The error message thrown when deprecated keys could be updated to explain what the newer keys or syntax is. The current message seems to imply one should use a `configuration` object and tuck these new key/values inside. However I've tried various combinations in my jasmine.json file to control test randomization, for eg. and nothing seems to work. Here's one example:
```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "oneFailurePerSpec": true,
  "config": {
    "random": false
  }
}
```
When running with this I still see messages like `Randomized with seed 70099` which, I believe, indication randomization is still happening. When I set `"random": false` directly the Randomized with seed message goes away but I get a deprecation warning. I've checked online docs and briefly looked through the commit which adds the new feature but I can't figure out the recommended syntaxt for configuring these values. Do they now belong under a `configure` subkey? Is there a separate file?

**Comment by slackersoft** [comment]
These deprecation messages are coming from the internals of Jasmine, where the external interface was not fully updated for the 3.3.0 release. At this time, 3.3.1 has been released which _should_ fix the deprecation warnings.

Sorry for the confusion. Thanks for using Jasmine!

**Comment by Adalid07** [comment]
Guys,
I'm new in jasmine, so i trying to run a test using _npm run test_ for example, and i'm getting the below error someone knows hot to fix that ?
DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`
DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`

Thanks in advance!

**Comment by slackersoft** [comment]
I'm going to re-open this to make the messages more clear that deprecated doesn't actually mean removed and that your tests will still run.
