### ISSUE TITLE
spyOn(myService, "gettest1").and.callThrough(); promise is not resolving get status like 0

### ISSUE THREAD

**Issue by Ajaykumarkonda** [jasmine/jasmine#1630]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

Trying to get API data from controller. It works fine in controller. Once i used callThrough(). testcase pases but  Api was not resolving. It shows status 0
## Expected Behavior

Expecting to get data from ApI as response. Below is tried code.
spyOn(myService, "gettest1").and.callThrough();
 it('getDateRangeData return Data obj', function() {
 
   var tee = myService.gettest1();

    var tee1 = myService.gettest1().then(function(response) {
      console.log('Success', response);
    }, function() {
      console.log("error on chart list");
})
}
can any one help me resolve promise? 
Also tried  "scope.$apply();" it gives an error Unexpected request: GET https://jsonplaceholder.typicode.com/todos/1
        No more request expected
## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
