### ISSUE TITLE
Feature Request: Detect duplicate test names

### ISSUE THREAD

**Issue by paulmedynski** [jasmine/jasmine#1633]
## Expected Behaviour
It would be nice if Jasmine could be configured to detect and warn/fail when duplicate fully qualified test names are found.  This is similar to Issue #747, but asking for a config option to enable the behaviour.

Alternatively, the list of fully qualified test names could be returned to the Reporter in JasmineStartedInfo and the Reporter could choose to detect duplicates itself.

## Current Behaviour
Duplicate test aren't detected.

## Possible Solution
See expected behaviour.

**Comment by didaquis** [comment]
It’s an interesting idea. So usefull when you have two thousand test writted for others developers. 

On this conditions, If some test fail detect which test are throwing error can be confusing if you have multiple test with same description.

**Comment by paulmedynski** [comment]
@didaquis summed it up nicely.  The nested structure of Jasmine tests (describe -> describe -> ... it) make it hard to visualize the full test names when you're in the code.  I think the nesting approach is totally fine for writing tests and having common functionality (aka fixtures), but it does obfuscate the full test names.  Boost (C++ test framework) has the same nested test definition approach and duplicate name problem, but detects the duplicates for you at runtime.

I'd be perfectly happy if there were a way to query Jasmine for the list of full test names in the jasmineStarted() Reporter callback.  Then my reporter could implement the detection.  Jasmine knows all of the tests by then (it provides the test count in the callback), so presumably there is a list of tests somewhere that could be queried.

If someone can point me to the place in the Jasmine code where the tests are compiled, I could probably write a patch.

**Comment by elliot-nelson** [comment]
I find this idea interesting as well.

I think a common thread here is detecting potential errors, like:

- Potentially copy/pasted tests (this issue)
- expect() with no matcher (https://github.com/jasmine/jasmine/issues/1696)
- a spec with no expects (_kind of_ supported -- but only the HtmlReporter shows it, never displayed for JUnit or console output)

All of these things and more are detected by linters, using plugins like https://github.com/tlvince/eslint-plugin-jasmine.  It might make sense to have some kind of decision about where the boundary should be between jasmine the linter (if jasmine will do error detection, which kinds, and why?).

**Comment by slackersoft** [comment]
Given the presence and availability of linting plugins as you've noted and the existing complexity of Jasmine already, I'm inclined to keep that type of detection outside of Jasmine itself. I might actually be more inclined to add a link of some kind to [the documentation](https://github.com/jasmine/jasmine.github.io) to the appropriate linter options to allow users to catch the types of errors that are important to them.

**Comment by paulmedynski** [comment]
That sounds good to me.  Even better if there's a TSLint plugin for Jasmine already :)

**Comment by slackersoft** [comment]
I don't know if there is also a plugin for TSLint, but it sounds like Palantir is also deprecating TSLint to focus on ESLint (https://medium.com/palantir/tslint-in-2019-1a144c2317a9).

**Comment by HolgerJeromin** [comment]
I have no idea how others are using that new option, but a bit more granular would be nice.
duplicate suites are not interesting for us, but duplicate specs (aka its "full qualified name") are.

**Comment by sgravrock** [comment]
That sounds pretty niche to me. Probably too niche to make for a good addition to Jasmine. I'd be very surprised if many people want to forbid duplicate spec names while allowing duplicate suite names. My recommendation is to give the top-level suite in each file a name that's both unique and relates to the filename in some way that's obvious to human readers. That will make features like filtering work and also help developers interpret failures more easily.

If you don't want to do that, then your next best bet is probably to write a custom eslint plugin that enforces your team's uniqueness policy.
