### ISSUE TITLE
Feature request: Report all failed expectations, not just first.

### ISSUE THREAD

**Issue by GCHQDeveloper911** [jasmine/jasmine#1635]
If I have a test:

describe('my suite', () => {
  it ('tests something', () => {
      expect(1).toEqual(2); 
      expect(2).toEqual(3);
      console.log('oh dear');
  })
})

Then obviously this fails - but only the "1=2" expectation is reported. It would be good to see all failed expectations. The test IS running through, because I see my log output.

**Comment by GCHQDeveloper911** [comment]
Further investigation shows this to be an issue with the tool I'm using (WebdriverIO) not Jasmine itself. Closing.

**Comment by slackersoft** [comment]
Awesome, glad to hear you've solved the issue. Thanks for using Jasmine!
