### ISSUE TITLE
Support  for custom systemic features ('plugins')

### ISSUE THREAD

**Issue by johnjbarton** [jasmine/jasmine#1640]
Our users love the jasmine testing  API, so they adapt jasmine to cases it may not have been designed for.  They call non-API jasmine functions and these break when we update them. Maybe more of these cases could be fixed with 'plugin' support?

Some of the use cases:

- Require `it()` functions to be `async` (to avoid errors when promises are used in tests).
- Require `it()` functions to be synchronous (because the system ensures synchrony).
- Add an `afterEach` to every suite to ensure environment cleanup (avoid errors from mismatched before/after operations)
- Add an `afterEach` to every suite to record the state of the test env (browser screenshots).

The general flavor of these hacks is to operate on the suite or spec list after user code creates the list but before it is passed into the jasmine queue.  Unlike beforeEach/afterEach, these changes are systemic and not context dependent.  Typically they are implemented by wrapping the globals `describe` or `afterEach` and calling the wrapped functions.

**Comment by slackersoft** [comment]
I definitely want to move towards allowing more customizibility with the use of plugin type things in Jasmine. I'm not sure that your last two examples need a plugin in order to work though, an `afterEach` not inside of a `describe` should apply to _all_ specs across all files in your suite.

The `it` changes can also be a bit tricky within Jasmine due to where the sync/async determination is made. What kind of entry point or interface from Jasmine would make this something you could write a plugin to solve?

**Comment by johnjbarton** [comment]
I was thinking of an onAddSpecsToSuites(suite, specDefinitions) in at the entry to [addSpecsToSuites()](https://github.com/jasmine/jasmine/blob/1b5e0c0c10321fe8b265bff004a39594aea14986/src/core/Env.js#L745)

**Comment by slackersoft** [comment]
I was thinking as well about how the plugin would get registered with Jasmine and what types of errors, etc. it might have available. Right now Jasmine doesn't really have "global" configuration, just configuration that happens to be on the super secret global suite (matchers, custom equality, etc.), so I want to make sure we have a reasonable interface.

**Comment by sgravrock** [comment]
I think it's pretty safe to assume that nobody's interested in this feature any more. It's also worth noting that of the four original use cases, two are commonly handled with ESLint rules these days and the other two can probably be handled with a top-level `afterEach`.

Closing.
