### ISSUE TITLE
Jasmine "Expect spy ... to have called" errors not readable

### ISSUE THREAD

**Issue by ohjames** [jasmine/jasmine#1641]
This message all on one-line is unreadable:

```
Expected spy next to have been called with [ Object({ subject: [ 'serviceu', 'more-serviceu' ], type: [ 'shyan-the-cat', 'lovely', 'beautfiul', 'hero' ], profile: [ 'human', 'annoying', 'notsogood' ] }) ] but actual calls were [ Object({ subject: [ 'serviceu', 'more-serviceu' ], profile: [ 'human', 'annoying', 'notsogood' ], type: [ 'shyan-the-cat', 'lovely', 'beautiful', 'hero' ] }) ]
```

The error here is a small typo in a single string but it takes ages to track down. For the same scenario mocha shows a lovely object diff which makes the issue immediately clear.

**Comment by slackersoft** [comment]
I would be nice to have some better comparison errors for `toHaveBeenCalledWith`, but it gets a bit trickier than for `toEqual` since the spy could have been called multiple times, and the arguments could be different at some deeper level. That said, I would be happy to review a pull request that used the existing difference reporting logic inside of the deep equals comparison to show the differences for each of the calls similar to how `toEqual` does. I _think_ it will have to be all of the calls, not just the one most likely to be the match, because there's no way to know that the one that is least different is the call that mattered.

**Comment by sgravrock** [comment]
c100bb6 puts each actual call on its own line. This matches what I've been doing by hand to diagnose `toHaveBeenCalledWith` failures. I don't think it's a complete solution, but in practice it makes the mismatch easy to spot in most cases and it plays nice with spies that are called multiple times.

**Comment by sgravrock** [comment]
I like the idea of including a diff, but Mocha's output format has some drawbacks that I'd rather not copy. I find it hard to interpret when I haven't been using Mocha a lot lately. It gets harder to interpret if the red and green colors are stripped away e.g. by piping through a plain-text interface, which also suggests that red-green colorblind folks might have trouble with it. And compared to the output of `toHaveBeenCalled`, it's harder to see at a glance what the arguments for a given call are.

Something like this might be a nice middle ground:

```
Expected spy foo to have been called with:
  [ Object({ subject: [ 'serviceu', 'more-serviceu' ], type: [ 'shyan-the-cat', 'lovely', 'beautfiul', 'hero' ], profile: [ 'human', 'annoying', 'notsogood' ] }) ]
but actual calls were:
  [ Object({ subject: [ 'serviceu', 'more-serviceu' ], profile: [ 'human', 'annoying', 'notsogood' ], type: [ 'shyan-the-cat', 'lovely', 'beautiful', 'hero' ] }) ],
  [ Object({ subject: [ 'serviceu', 'more-serviceu' ], profile: [ 'human', 'annoying', 'notsogood' ], type: [ 'shyan-the-dog', 'lovely', 'beautfiul', 'hero' ] }) ].

Call 0: Expected $[0].type[2] = 'beautiful' to equal 'beautfiul'.
Call 1: Expected $[0].type[0] = 'shyan-the-dog' to equal 'shyan-the-cat'.
```

**Comment by ohjames** [comment]
Hm, still find mocha's output far more readable than what was recently implemented. This is enough to keep me from ever choosing jasmine.
