### ISSUE TITLE
Support nodejs experimental-modules

### ISSUE THREAD

**Issue by jehon** [jasmine/jasmine#1651]
## Are you creating an issue in the correct repository?

The "bug" (unwanted feature) is at jasmine.js#89.5

## Expected Behavior
We should be able to use the "ecmascript" experimental modules of nodejs (https://nodejs.org/dist/latest-v11.x/docs/api/esm.html), 

## Current Behavior
we receive an error:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mnt/c/Users/jhn/src/kiosk/tests/server/basic-test.mjs
>     at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:724:11)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at /mnt/c/Users/jhn/src/kiosk/node_modules/jasmine/lib/jasmine.js:89:5
>     at Array.forEach (<anonymous>)
>     at Jasmine.loadSpecs (/mnt/c/Users/jhn/src/kiosk/node_modules/jasmine/lib/jasmine.js:88:18)
>     at Jasmine.execute (/mnt/c/Users/jhn/src/kiosk/node_modules/jasmine/lib/jasmine.js:257:8)

## Possible Solution
Jasmine should use "import" instead of "require" when loading esm modules. But that is not that easy, since "import" is asynchronous, while require is synchronous.

## Suite that reproduces the behavior (for bugs)
- Create a .jsm file (can be any test, even a simple one)
launch nearly as usual:
```
node --experimental-modules node_modules/.bin/jasmine
```

## Context
This is blocking to use jasmine in this new (experimental) context.

## Your Environment

* Version used: 3.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs v10.15.1
* Operating System and version (desktop or mobile): ubuntu
* Link to your project:

**Comment by jehon** [comment]
After looking, I think it is part of the jasmine-npm package?

**Comment by jehon** [comment]
Reopened to include the management of the stacktrace in core

**Comment by frank-dspeed** [comment]
where is the pr?

**Comment by frank-dspeed** [comment]
https://github.com/jasmine/jasmine/pull/1662

**Comment by damianobarbati** [comment]
Is there any workaround actually to use jasmine with node v14.3 and ESM imports?

**Comment by drzraf** [comment]
https://github.com/jasmine/jasmine-npm/issues/150#issuecomment-570684328 :

`jasmine --require=esm`

or

```
  "requires": [
    "esm"
  ],
```

**Comment by slackersoft** [comment]
Closing this issues as the relevant issue on jasmine-npm has been resolved and merged into main there to be included in the next release.
