### ISSUE TITLE
Spec.status does not match with Suite.status

### ISSUE THREAD

**Issue by wood1986** [jasmine/jasmine#1655]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Expected Behavior

`suites[0].status` should be in `failed`.

## Current Behavior

![a](https://user-images.githubusercontent.com/5212215/53151330-ca183b00-3567-11e9-9637-b3b49cf3f0cb.gif)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("index", () => {
  it("index", () => {
    expect(1).toBe(0);
  });
});
```
## Your Environment

* Version used: 3.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): 
* Link to your project:

**Comment by slackersoft** [comment]
The `status` property on a Suite result is intended to represent failures at the suite level and is _not_ a rollup of child failures. Errors and failures in a `beforeEach`, `afterEach`, or `it` will be on the Spec result and errors in `beforeAll`, `afterAll` or outside of anything will be on the suite.

Hope this helps. Thanks for using Jasmine!
