### ISSUE TITLE
suiteStarted and suiteDone not called when filtering

### ISSUE THREAD

**Issue by paulmedynski** [jasmine/jasmine#1661]
## Expected Behavior
When filtering, any tests that will be run should have `specStarted()` and `specDone()` called if those tests live within any number of `describe()` suites.

In my case, I'm doing this:
```javascript
const Jasmine = require('jasmine');
const jasmine = new Jasmine();
jasmine.loadConfig(...);
jasmine.addReporter(new MyReporter());
jasmine.execute(undefined, 'my filter');
```

`MyReporter` defines `suiteStarted()` and `suiteDone()`, and those functions are called as expected when no filter is provided.  However, when I supply a filter (`'my filter'` in the case above), none of the suites in which filtered tests run have `suiteStarted()` or `suiteDone()` called for them.

## Current Behavior
`suiteStarted()` and `suiteDone()` are not called on my custom reporter when I call `execute()` and provide a filter (the second arg to `execute`).  I would expect that the suite the filtered tests belong to would have `suiteStarted()` and `suiteDone()` called for them, but that's not happening.

## Possible Solution
Whenever a test within a suite (or nested suites) actually executes, call `suiteStarted()` and `suiteDone()` for each level of suite that test resides within.

## Context
When running filtered tests, errors in a suite `beforeEach()` or `afterEach()` are not reported, but the overall execution state ends up `failed`.  I have to run without filtering to see the suite errors.

## Your Environment
* Version used:  3.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 11
* Operating System and version (desktop or mobile): Linux

**Comment by slackersoft** [comment]
That sounds concerning, but I'm having some trouble reproducing the issue. When I run Jasmine's own tests with a `beforeAll` that has an expectation failure in it, I see the suite failure message printed out when I have the specs filtered. Only errors in a `beforeAll`, `afterAll`, or during declaration of the suite itself will be reported as part of the `result` on a suite. Any errors in a `beforeEach` or `afterEach` will be reported as part of the individual spec that they failed for.

Can you try to reproduce the issue with the built-in Jasmine reporters? If you're seeing all the errors there, it might be an issue with the custom reporter you're using. Depending on how old the reporter is, it might need to be updated, there were some large status changes for reporters as part of Jasmine 3.0.

Hope this helps. Thanks for using Jasmine!

**Comment by paulmedynski** [comment]
I've confirmed with a minimal custom reporter that Jasmine is behaving correctly:

https://github.com/paulmedynski/jasmine-issue-1661

The custom reporter I have been using had a bug where it was suppressing the spec start/done messages under certain circumstances, and was triggered by the filtering (among other things).

Thanks for indulging me :)
