### ISSUE TITLE
Running Child Process in Jasmine Produces Inconsistent Results Based on the Shell Command

### ISSUE THREAD

**Issue by jcald1** [jasmine/jasmine#1671]
## Summary

When I execute a child process using exec(), some shell commands produce standard out and others do not.  `pwd` works for me but `ps` doesn't.

## Expected Behavior
I should see the same standard out and error as I would if I were to run the commands in teh shell.

## Current Behavior
I have the following code to execute a shell command in Jasmine.  If I change "ps" to something like "pwd", it works.  I see the standard out and the exit code, but I see neither one if I use certain commands like "ps".

## Suite that reproduces the behavior (for bugs)

```javascript
    const uuid = require('uuid');
    const child_process = require('child_process');

    describe('TESTS', () => {
      console.log('TEST***');
      it('mp4', () => {
        console.log('1TEST***');
        const cmd = 'ps';
        child_process
          .exec(cmd, (err, stdout, stderr) => {
            console.log(`stdout is:${stdout}`);
            console.log(`stderr is:${stderr}`);
            console.log(`error is:${err}`);
          })
          .on('exit', code => console.log('final exit code is', code));
      }, 20000);
    });
});
```
## Context
I'm trying to build an integration test suite taht runs some AWS SAM commands.  When I found that the tests weren't working I reverted to trying some basic shell commands.

## Your Environment
Jasmine 3.3.0
Node 10.15
Linux Mint 19

**Comment by slackersoft** [comment]
Remember that command the command line prints both `stderr` and `stdout` to the same place, so just because you see some text when you run the command in a terminal doesn't mean it is necessarily being printed to one or the other. Additionally, it doesn't sound like this is an issue with Jasmine itself, as Jasmine doesn't provide the `child_process` library.

Closing. Thanks for using Jasmine!
