### ISSUE TITLE
Jasmine 'expect(…).withContext is not a function' error

### ISSUE THREAD

**Issue by spleshakov** [jasmine/jasmine#1673]
I was looking for a way to make failure messaging more descriptive in Jasmine and found this new functionality https://jasmine.github.io/api/edge/matchers.html#withContext

So I try it in my Protractor framework like this

`expect(true).withContext("something else").toBe(false);`

Run the test and get error `- Failed: expect(...).withContext is not a function`

This feature was implemented since Jasmine 3.3.0, so I checked my package.json and see `"jasmine": "^3.3.1"`, and package-lock.json has

```
"jasmine-core": {
      "version": "3.3.0",
```
Any ideas what is wrong?

**Comment by tymfear** [comment]
Protractor uses `jasminewd` wrapper which uses jasmine 2.x. If you want to use Jasmine 3.x, you can use Protractor 6.0, that has been released recently. In older versions the newest features of Jasmine, like `withContext` function, async hooks (e.g. onSpecDone) are not available.

**Comment by spleshakov** [comment]
Thanks for the help!
