### ISSUE TITLE
Spec duration is mentioned in docs, but null or 0

### ISSUE THREAD

**Issue by apla** [jasmine/jasmine#1676]
As I see on [docs](https://jasmine.github.io/api/edge/global#SpecResult) `duration` is available and there is a pull request (#1646) to support `duration` property. But it is `null` or `0`. How to make it works?

[Console reporter](https://github.com/jasmine/jasmine-npm/blob/master/lib/reporters/console_reporter.js#L3) and [Third-party console reporter](https://github.com/onury/jasmine-console-reporter/blob/master/lib/TestStats.js#L101) use their own timers. It is possible to use `jasmine.jasmine.Timer` in custom reporter?

**Comment by slackersoft** [comment]
What version of Jasmine are you using? Spec duration was only just released in version Jasmine-Core 3.4.

It should be possible to use `jasmine.Timer` in other contexts, the interface is pretty simple. The goal of #1646 was to make it so reporters didn't have to do that work themselves.
