### ISSUE TITLE
await expect - expectationFailOutput

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1681]
it('test async fail to console log', async() => {
        let components = element.all(by.xpath('//button'));

        await browser.get('http://localhost:3333/testpageforbutton');
        await expect(components.count()).toBe(19, 'some info for fail ' + components.count());
    });

count in expect is correctly counted, but in expectationFailOutput did not show correctly text to console log

this working:
it('test async fail to console log', async() => {
        let components = element.all(by.xpath('//button'));

        await browser.get('http://localhost:3333/testpageforbutton');
        expect(await components.count()).toBe(19, 'some info for fail ' + await components.count());
    });

**Comment by slackersoft** [comment]
Jasmine's built-in `expect` function doesn't handle `async`/`Promise`s natively. You may want to look at [`expectAsync`](https://jasmine.github.io/api/edge/global.html#expectAsync) and the promise related matchers.

Hope this helps. Thanks for using Jasmine!
