### ISSUE TITLE
Getting mismatch execute of test

### ISSUE THREAD

**Issue by brendonco** [jasmine/jasmine#1683]
```
devDependencies: {
  "jasmine-core": "3.4.0",
    "jest": "22.4.2",
    "jsdom": "14.0.0",
    "karma": "3.1.4",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jsdom-launcher": "6.1.2",
    "karma-junit-reporter": "1.2.0",
    "karma-webpack": "^4.0.0-rc.6",
}
```

```
karma.config {
     browserDisconnectTolerance: 2,
    // long load time while webpack blocks on serving the request.
    browserNoActivityTimeout: 60000, // 60 seconds
    browsers: ['jsdom'],
}
```

node version: v8.9.1

The Unit test should be 223 instead of 515.

 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 515 of 223 SUCCESS (0 secs / 2 mins 5.294 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 516 of 223 SUCCESS (0 secs / 2 mins 7.293 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 517 of 223 SUCCESS (0 secs / 2 mins 11.44 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 518 of 223 SUCCESS (0 secs / 2 mins 13.478 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 519 of 223 SUCCESS (0 secs / 2 mins 13.58 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 520 of 223 SUCCESS (0 secs / 2 mins 13.608 secs)
 Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 521 of 223 SUCCESS (0 secs / 2 mins 15.648 secs)
Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/14.0.0: Executed 521 of 223 SUCCESS (0 secs / 2 mins 15.648 secs)

**Comment by slackersoft** [comment]
That message is actually provided by [Karma](https://github.com/karma-runner/karma/blob/c311ac00cef4a957f889ed613238793c0ffa95a2/lib/reporters/base.js#L39) and not Jasmine itself. Unfortunately, I don't know enough about how Karma to figure out what mechanism is being used to compute those two numbers. My best guess would be that there is a mismatch in how Jasmine reports errors for Suites and how Karma expects those errors to be reported.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
I'm going to go ahead and close this since we haven't heard anything in quite some time. Feel free to open a new issue with more information if you're still having problems.
