### ISSUE TITLE
npm install jasmine in eclipse after that it showing error in ci.js file

### ISSUE THREAD

**Issue by kesavamuthuM** [jasmine/jasmine#1684]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by kesavamuthuM** [comment]
I used the eclipse provided git bash in that entered keyword is "npm install jasmine" this is what I saw in docs. After that, it showing error in ci.js file.

**Comment by slackersoft** [comment]
I'm not seeing any errors when I install or run tests on windows or MacOS. I tried in git bash and even in basic windows command prompt. Can you please provide a bit more context on what errors you're seeing and the environment you are working in. Take a look at the issue template if you need an example of what type of information is helpful for us to debug and fix issues.

**Comment by kesavamuthuM** [comment]
Initially, I created a javascript project in eclipse then I used the git bash local terminal in eclipse. Then I used npm init and npm install jasmine. Then in node modules jasmine folder got created. In ci.js follow error it shows 
Multiple markers at this line
	- Semi-colon expected
	- ',' expected
	- primary expression 
	 expected
	- primary expression 
	 expected
	- Semi-colon expected
	- ')' expected
	- ',' expected
	- Semi-colon expected
	- '}' expected
	- Semi-colon expected

Also I am new to javascript and programming. I am using windows 10 and eclipse jee 2018-12.

**Comment by slackersoft** [comment]
You can probably safely ignore those errors. You probably don't want to be editing the code of Jasmine (or any of your other dependencies) directly. The `ci.js` file is used by Jasmine internally to run Jasmine's own specs before being published, and is not actually used when you run your own specs. It looks like we didn't get all of the style checking set up for this new file, and so didn't catch them earlier.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this issue. The `ci.js` file should no longer be included in the jasmine-core package.
