### ISSUE TITLE
Suggestion: a way to default spies to _not_ expect calls

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1692]
## Summary

I would like some way to default spies to behave as if they should not be called -- similar to what you get today if you use `.withArgs()` but then call the spy without defined arguments:

```
Error: Spy 'spy' received a call with arguments [ 'hello' ] but all configured strategies specify other arguments.
```

## Expected Behavior
I'd like to do this:

```
spyOn(myModule, 'myMethod');
myModule.myMethod();  // => throws 'Unexpected call to myMethod()'
```

I'd _especially_ like to do this:
```
const request = require('request-promise');
spyOnAllFunctions(request);
request.post();    // => throws 'Unexpected call to post()'
```

## Current Behavior
Today, the default behavior is that a spy is "not configured" - but that's not really true, it's configured to return `undefined`.  The following are all equivalent, with varying levels of expressiveness:
```
spyOn(foo, 'bar');
spyOn(foo, 'bar').and.stub();
spyOn(foo, 'bar').and.returnValue(undefined);
```

## Possible Solution
I'm fishing here.  Obviously, there are one billion jasmine tests out there that assume an un-configured spy returns `undefined`, so you can't break that.

I think there's a few things I'd like that add up to a workable solution:

1) A new spy strategy (or maybe it's a method on spy itself?) that explicitly says "expect this not to be called".  `spy.and.unexpected()` or something.  You can _already do this!_  But it's unintuitive:

```
// One approach that's already built in...
spy.withArgs('aosdfihasidfhsido').and.returnValue();
spy();  // => throws error

// Obviously, you can also do this...
spy.and.callFake(myCustomUnexpectedCallHandler);
spy();  // => throws some custom error
```

2) Some way (perhaps temporarily?) to "default" what method is used when assigning spies.  Especially for mass-assignment... This might be good enough:

```
// This could mean "apply the unexpected spy strategy to every spy?"
spyOnAllFunctions(request).and.unexpected();

// Or without a new spy strategy
spyOnAllFunctions(request).and.throwError(UnexpectedError);
```

## Context
This is something that I end up implementing on many projects, and so it'd be great if there was a built-in "jasmine" way to accomplish it.

(The use case here is when you are unit testing modules and completely mocking external dependencies.  It's very useful to grab the 3 components this component uses, and mass-assign every function on all of them an error that says "hey, this got called unexpectedly!".  You then allow-list only the expected function calls by assigning `.stub()` or `.callThrough()` as appropriate.)

This could be related to https://github.com/jasmine/jasmine/issues/1641, in that, I'm kind of advocating for a message like this (with no withArgs):

> Unexpected call to 'spy' with arguments [blah]

Whereas the linked issue wants to fix the toBeCalledWith matcher, you could make that argument about the withArgs output, and desire:

> Unexpected call to 'spy' with arguments [blah]. You might have meant:
  - `#1: diff builder comparison of withArgs(0) & blah`
  - `#2: diff builder comparison of withArgs(1) & blah`
  - etc.

So, the behavior I'm looking for is consistent, just the message is more detailed if you've used `withArgs()`.

## Your Environment
* node v6, v8, v10 (varies)

**Comment by elliot-nelson** [comment]
I guess it's worth mentioning that this suggestion is similar  to https://github.com/jasmine/jasmine/issues/1568.

My suggestion is to make it easy to have all methods on a module blow up immediately if they get used.  In the linked issue, the suggestion is to make it easy to stub all methods, but check _afterwards_ that none of them got used.

**Comment by slackersoft** [comment]
The way I typically handle this is to create an object that simply doesn't include the functions I don't expect to be called. This also generates an error (and spec failure) if the function is called when you don't expect it to be. I think using something like TypeScript probably makes this trickier as now you need some way to convince the compiler that this object you're supplying is good enough for your tests.

I think I could see Jasmine providing a way to configure the default spy strategy used when creating a new spy, either on a global or per-spec level. This would let you say in a global `beforeEach` or something that the default strategy should be to throw an exception, possibly even providing one that has a friendly message about what happened.

**Comment by elliot-nelson** [comment]
I wonder if an alternate proposal is not "set a default strategy", but rather, allow you to reason about a bundle of spies at once.

Example syntax:

```
// Set a plan for several spies at once
jasmine.spies(randomObject, ["get", "post", "options"]).and.stub();

// Assert that no spies on an object have been called at all
expect(jasmine.spies(randomObject)).not.toHaveBeenCalled();

// Spy on all functions and then set them to throw errors
jasmine.spies(spyOnAllFunctions(myObject)).and.throwError();

// Assert that several functions were called exactly once
expect(jasmine.spies(randomObject, ["foo", "bar", "baz"])).toHaveBeenCalledTimes(1);
```

I guess what I'm thinking is that `jasmine.spies(object, [optional name list])` returns a new thing called a "SpyCollection", and that it behaves like SpyStrategyDispatcher except loops through all collected spies instead of setting on just one.  All existing `toHaveBeen*` matchers would detect a SpyCollection and loop through each spy in the collection.

You could use this thing not only with existing objects but with `createSpyObj`, which would make https://github.com/jasmine/jasmine/issues/1568 trivial.

**Comment by slackersoft** [comment]
I think the suggested name `spiesOn` might be a bit too close to the existing `spyOn` and cause confusion about whether it is expected to create spies. `spiesFrom` might be more explicit, since I don't think this should create spies since there are already enough ways to do that. Otherwise, this sounds like a useful thing, especially for the `.not.toHaveBeenCalled()` case.

**Comment by elliot-nelson** [comment]
Been noodling on this some more.  I'd hate to introduce ambiguity in any existing matchers, but I'm afraid this does... if you assume any matcher that takes a `Spy` should be able to take a `SpyCollection` (in other words, the result of calling `getSpies()`), then you have some questions:

- Does `expect(getSpies(obj)).toHaveBeenCalled()` mean _any_ spy on obj was called?  Or does it mean _all_ spies on the object were called?  I think the intuitive answer depends on context: if `obj` is a giant S3 instance that you `spyOnAllFunctions`, the intuitive answer is "any spy".  If `obj` is a `createSpyObj` with two methods, the intuitive answer may be "all spies".

- Does `expect(getSpies(obj)).toHaveBeenCalledTimes(7)` mean that at least one spy had 7 calls?  Or that if you add up all the calls on all spies it equals 7?  Similar questions for `toHaveBeenCalledWith`.

I do really like the idea of getting these two syntax sugars:

```
// Mass "not-called" check
spyOnAllFunctions(obj);
expect(getSpies(obj)).not.toHaveBeenCalled();

// Mass "strategy" assignment
spyOnAllFunctions(obj)
getSpies(obj).and.resolveWith();
```

But the expectations in particular seem easy to get wrong.  (A possibility would be to just ignore the expectation side for now, and at least implement the mass-strategy-assignment.)

**Comment by elliot-nelson** [comment]
A possible solution to the above that achieves consistency, but might be of limited usefulness, would be to add a "mode" method to SpyCollection, which is looked at by matchers -- modes are `all()`, `any()`, and `onlyOne()`.

You can then make statements that are relatively explicit:

```
var spies = getSpies(bigObjectSpiedUpon);

// Some spy on the object got called
expect(spies.any()).toHaveBeenCalled();

// Every spy on the object got called exactly twice
expect(spies.all()).toHaveBeenCalledTimes(2);

// No spies can be called
expect(spies.all()).not.toHaveBeenCalled();

// You can call any method, but only one
expect(spies.onlyOne()).toHaveBeenCalled();

// Error: specify a mode
expect(spies).toHaveBeenCalled();
```

**Comment by slackersoft** [comment]
I can't think of a good reason to want to check that _any_ or _any one_ of `n` various functions on an object was called. Honestly, I'm not sure how valuable checking that _all_ of them were simply called. I think that given a transpiler that checks that objects have all of the properties on them that that the type defines, the most directly useful thing for Jasmine to provide is a way to ensure that functions that exist on the type, but shouldn't actually be used in this particular test are not called.

I think the nicest way to do this is with a matcher like `toHaveNoSpyInteractions` (#1568) possibly that also accepts a list of methods that should be skipped in the matcher. This would allow behavior like Mockito's `verifyNoMoreInteractions`.

**Comment by elliot-nelson** [comment]
We could probably close this suggestion once https://github.com/jasmine/jasmine/pull/1716 (or something similar) goes in.

It's not a full implementation, but it allows you to create a user-defined error (`.and.throwError('foo')`) and set it as your default spy strategy, which would be good enough for my original use case.

**Comment by slackersoft** [comment]
Now that #1716 has been merged, I'm going to close this per your suggestion. If folks have additional use cases for something like this feature that aren't covered by #1716, please let us know here and we can re-open discussions.
