### ISSUE TITLE
Suggestion: default async spies to be async

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1693]
## Expected Behavior
Today, everyone expects an un-configured spy to return undefined.  If we _know_ that the function is async, though, we can do better and return a promise for undefined.

```
const Foo = {
    bar: async () => 7
};
spyOn(Foo, 'bar');
Foo.bar().then(console.log);  // => prints undefined
```
    
## Current Behavior
```
const Foo = {
    bar: async () => 7
};
spyOn(Foo, 'bar');
Foo.bar().then(console.log);  // => error: then is not defined on undefined
```

## Possible Solution
In recent versions of node, anyway, you can use:
```
    fn.constructor.name === 'AsyncFunction'
```

## Context
Throwing this out here.  I think the behavior "un-configured spies return undefined" is _consistent_, and there's a lot of history there we don't want to break, but it's also not very useful in my opinion.

Almost all useful nodejs javascript involves promises, and most of _that_ work can now be written using async functions.  Unlike promise-based functions, we can actually tell (generally) when a function is async, which means we know it's totally useless to return a value that's not a promise.

**Comment by slackersoft** [comment]
My main concern with making a change like this is that it (accidentally) creates a distinction between an `async function` and a function that returns a `Promise` that isn't obvious to a user. As a user of Jasmine I would expect `spyOn(Foo, 'bar')` to do the same thing whether the function uses the `async` keyword or returns a `Promise`, and we wouldn't be able to do that here.

This is especially true if we start talking about code running in a browser that might have `Promise` but not necessarily `async` and a transpiler that turns one into the other. Now my tests behave differently depending on where they are run. This seems like it would be a bad thing.

**Comment by elliot-nelson** [comment]
Oh, yeah, the transpilation issue is something I hadn't even thought about.

I guess the thing that is frustrating is the requirement any time you have a promise-based method (which is a _lot_ of them for modern node), spying is always `spyOn(method).and.returnValue(Promise.resolve())`, which is so much longer than `spyOn(method)`.

The PR currently up for `spyOn(method).and.resolveValue()` takes a little sting out, so that's something.

(I'm fine with just closing this suggestion.)

**Comment by slackersoft** [comment]
I'm going to close this in favor of getting better `and.resolveValue` syntax in. I would expect this functionality to mostly lead to people still doing something like that just so they don't need to go look up whether this function is `async` or `return Promise`.
