### ISSUE TITLE
Suggestion: function matcher 'toHaveCallSequence'

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1694]
## Context
On many projects on my team, we encourage people to avoid `toHaveBeenCalled()` and `toHaveBeenCalledWith()`, in favor of this stricter check:

```
    expect(spy.calls.allArgs()).toEqual([
        ["first", "expected", "call"],
        ["second", "expected", "call"]
    ]);
```

This is the last word in spy expects: you'll get notified if you called too many times _or_ too few times, and if any of the calls weren't exactly as expected or were in a different order than expected, you get nice diff-builder output describing the differences.

## Expected Behavior
I'd like to be able to do that check, with a built-in matcher instead:
```
// Just like the .calls.allArgs() approach:
expect(spy).toHaveBeenCalledExactly([
    ["first", "args"],
    ["second", "args"]
]);

// Or maybe the matcher could just use ...args instead of an array:
expect(spy).toHaveBeenCalledExactly(
    ["first", "args"],
    ["second", "args"]
);

// This is equivalent to .not.toHaveBeenCalled()
expect(spy).toHaveBeenCalledExactly();
```

## Current Behavior
Today, you can use a `.toEqual` on `.calls.allArgs()`.  Totally serviceable, just lacks a little syntax sugar.

## Possible Solution
I'd be happy to put up a PR for this one, if it sounds like something that could belong in core.

Possible names?
 - toHaveBeenCalledExactly([], [], [])
 - toHaveBeenCalledWithExactArgs([], [], [])
 - toHaveBeenCalledWithOnly([], [], [])

I think the functionality is pretty simple, it mostly just needs an understandable name and need to decide which calling syntax is least surprising (an array of arrays, or an ...arguments list of arrays, to represent the args for each call).

**Comment by slackersoft** [comment]
I think you can already accomplish _most_ of this with something like the following:

```javascript
expect(spy).toHaveBeenCalledWith("first", "expected", "call");
expect(spy).toHaveBeenCalledWith("second", "expected", "call");
expect(spy).toHaveBeenCalledTimes(2);
```

This admittedly doesn't check for the order of the two calls, and I don't think that `toHaveBeenCalledBefore` will do the right thing for multiple invocations of the same spy. I don't think we want a new matcher with the word `exact` in it for this, because that implies that `toHaveBeenCalledWith` doesn't do an exact comparison. Especially when compared with other mocking libraries like sinon that have a distinction between a call with some args and a call with exact args.

I would be happy to see if we can find a way to extend `toHaveBeenCalledBefore` to work with multiple calls to a single spy. Or just document it correctly if it turns out that that already works.

Hope this helps. Thanks for using Jasmine!

**Comment by elliot-nelson** [comment]
Your example is definitely the same spirit, but the output (just imo) is nowhere near as concise and helpful as `.calls.allArgs()).toEqual()`.  You get the same _assertion_, but nowhere near the level of immediate debugging when the test fails.

Good call on the phrase "exact".  I'll noodle on it.

**Comment by elliot-nelson** [comment]
A possibility, deviating slightly from `toHaveBeenCalled`:

    expect(fn).toHaveCallSequence([args...], [args...], [args...]);

**Comment by slackersoft** [comment]
I'm definitely open to working on the messages for `toHaveBeenCalledWith` so the errors better indicate the specific calls and maybe even what's different in them. I think one of the current problems there is that it prints the calls out raw as the result from `allArgs()`. I would be concerned as well, that a `toHaveCallSequence` would end up encouraging long chains of calls at once, which will be hard to read, instead of just looking at what actually matters for whatever is being tested.

**Comment by elliot-nelson** [comment]
I'll put up a defense of `toHaveCallSequence` here...

The real value (just imo) of your unit tests is when they fail.  As long as your unit tests are always green, they have _potential_ value, but as soon as they fail -- due to an intentional or unintentional code change -- that's when they show their real value.

Here's two ways to write the same unit test:

```
describe('#execute', function () {
    it('writes one file - Option A', function () {
        execute();
        expect(fs.writeFileSync).toHaveBeenCalledWith('result.xml', '<result></result>', 'utf8');
        expect(fs.writeFileSync).toHaveBeenCalledTimes(1);
    });

    it('writes one file - Option B', function () {
        execute();
        expect(fs.writeFileSync.calls.allArgs()).toEqual([
            ['result.xml', '<result></result>', 'utf8']
        ]);
    });
});
```

When your unit test fails, in my opinion, Option A is often worse:

1. If you didn't call `writeFileSync`, now you have two different expectation failures.  "Failure spam" is a big deal and escalates quickly, the fewer unique failures per real problem, the better.

2. If you called `writeFileSync` too many times, you only get the message `2 is not 1`.  Option B gives you immediate information on exactly what the additional calls were, without the need to re-run the test with additional debugging (which might not even be possible if it's an intermittent failure).

3. If you called `writeFileSync` with the wrong arguments, in this case Option A and Option B are similar, except that Option B will print enhanced diff builder output (helpful if the arg list is long or complex).

Because Option B is never worse (and is often better) at providing immediately actionable feedback on failure, I always write every expectation using that pattern.  But, it's just not as friendly to read as Option A -- which is why I'd love to be able to write it this way instead:

```
    expect(fs.writeFileSync).toHaveCallSequence([
        ['result.xml', '<result></result>', 'utf8']
    ]);
    // just syntax sugar for "expect allArgs() to equal this array"
```

Let me know what you think... I think this is a pretty easy matcher to write up, but I do understand your desire not to encourage bad patterns as well.

**Comment by elliot-nelson** [comment]
I feel like it's safe to close this request:

1) Since I opened it, the toHaveBeenCalledWith diff output has really improved (it's great now).
2) PR https://github.com/jasmine/jasmine/pull/1801 will, I think, handle the very common "match these args and only allow 1 call" situation.
3) For remaining, rare circumstances (like verifying the exact number of glob calls from a complicated search method or something), then I think it's appropriate to use the explicit `.calls.allArgs()` equality comparison.
