### ISSUE TITLE
toBeCloseTo fails in edge case (+ fix)

### ISSUE THREAD

**Issue by paulvanbrenk** [jasmine/jasmine#1695]
the `toBeCloseTo` matcher started to fail recently on Chrome 74, i.e. the following cases are failing:

```javascript
describe("sample", function() {
    it("tobecloseto fails", function() {
        expect(4.030904708957288).toBeCloseTo(4.0309, 5);
        expect(4.82665525779431).toBeCloseTo(4.82666, 5);
        expect(-2.82665525779431).toBeCloseTo(-2.82666, 5);
    });
});
```

A possible fix is the following:
[tobecloseto.js#29](https://github.com/jasmine/jasmine/blob/eb30e8179a9073482d07cb7a066183a9fc786a27/src/core/matchers/toBeCloseTo.js#L29) change to:
`pass: Math.round(delta * pow) <= maxDelta * pow`

* Version used: 3.4.0 & 2.99
* Environment name and version: Chrome 74 & NodeJs 12.2.0
* Operating System and version (desktop or mobile): WIndows 10

**Comment by slackersoft** [comment]
Thanks for finding this. I would be happy to review a pull request to fix this that includes some of those examples that fail correctly in Chrome and force the change in implementation.

**Comment by paulvanbrenk** [comment]
I should have some time next week to setup a Jasmine development environment and get a PR ready.
