### ISSUE TITLE
Ability to add custom AsyncMatchers

### ISSUE THREAD

**Issue by r4j4h** [jasmine/jasmine#1703]
While testing using the great new `expectAsync` matchers, I ran into a deficiency where `toBeResolvedTo` does not print what it was rejected with on rejections.

```javascript
await expectAsync(
    promiseReturningThing()
).toBeResolvedTo(jasmine.any(Buffer));
```

becomes

```
Expected a promise to be resolved to <jasmine.any(Buffer)> but it was rejected.
```

I tried to overcome that with a custom async matcher that is a direct copy of `toBeResolvedTo` but that prints out the rejection cause for easier debugging.

```javascript
import {toBeDescriptivelyResolvedTo} from "../../matchers/async/toBeDescriptivelyResolvedTo";
jasmine.addMatchers({
    toBeDescriptivelyResolvedTo: toBeDescriptivelyResolvedTo
})
```

However, I found that custom matchers **do not** count as async matchers.

## Expected Behavior

I expect to be able to define a custom async matcher.

```javascript
await expectAsync(
    promiseReturningThing()
).toBeDescriptivelyResolvedTo(jasmine.any(Buffer));
```

and have it print out the rejected value.

```
Expected a promise to be resolved to <jasmine.any(Buffer)> but it was rejected with "fake rejection".
```

## Current Behavior

I get
`TypeError: expectAsync(...).toBeDescriptivelyResolvedTo is not a function`

I can test it with a normal expect and it works, as far as being called, but then I get a failure from expect itself not working with the promise.

```javascript
await (expect(Promise.resolve('b')) as any).toBeDescriptivelyResolvedTo(2);
```

```
Expected [object Promise] to be descriptively resolved to 2.
```

I can verify it is being called by adding console.log statements and seeing them output in addition to the failure.

## Possible Solution

A possible workaround might exist by manipulating some of the internal globals, but it might be tricky as they are not all exposed. The correct code is probably going to look like something around `src/core/Expectation.js`, specifically `addAsyncCoreMatchers`. The current code is able to add the core async matchers.

`j$.Expectation` or `j$.asyncMatchers` seem useful if one could get a reference.

Also note [this todo](https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js#L2) about `j$.pp`, because [`toBeResolvedTo`](https://github.com/jasmine/jasmine/blob/master/src/core/matchers/async/toBeResolvedTo.js) uses it.

If my problem is a typing issue that would be great and I can open an issue elsewhere.

## Suite that reproduces the behavior (for bugs)

```javascript
export const toBeDescriptivelyResolvedTo  =
    /**
     * Expect a promise to be resolved to a value equal to the expected, using deep equality comparison.
     * @function
     * @async
     * @name async-matchers#toBeResolvedTo
     * @param {Object} expected - Value that the promise is expected to resolve to
     * @example
     * await expectAsync(aPromise).toBeResolvedTo({prop: 'value'});
     * @example
     * return expectAsync(aPromise).toBeResolvedTo({prop: 'value'});
     */
    function toBeResolvedTo(util: any, customEqualityTesters: any) {
        console.log("eggo");
        return {
            compare: function(actualPromise: any, expectedValue: any) {
                console.log("waffle");
                function prefix(passed: any) {
                    return 'Expected a promise ' +
                        (passed ? 'not ' : '') +
                        'to be resolved to ' + JSON.stringify(expectedValue);
                }

                return actualPromise.then(
                    function(actualValue: any) {
                        if (util.equals(actualValue, expectedValue, customEqualityTesters)) {
                            return {
                                pass: true,
                                message: prefix(true) + '.'
                            };
                        } else {
                            return {
                                pass: false,
                                message: prefix(false) + ' but it was resolved to ' + JSON.stringify(actualValue) + '.'
                            };
                        }
                    },
                    function(err: any) {
                        return {
                            pass: false,
                            message: prefix(false) + ' but it was rejected with ' + JSON.stringify(err) + '.'
                        };
                    }
                );
            }
        };
    };

---

      await (expectAsync(Promise.reject('b')) as any).toBeDescriptivelyResolvedTo('a');

```

## Context

Not printing the value makes debugging failed tests harder.

Not being able to extend custom async matchers reduces Jasmine's power.

## Your Environment

* Version used: 3.4.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 10
* Operating System and version (desktop or mobile): Alpine Linux Docker container
* Link to your project: N/A

**Comment by slackersoft** [comment]
The intention is definitely to allow adding custom async matchers at some point. We opted leave the feature out initially in order to get async matchers into Jasmine at all. I believe the architecture for async expectations should be similar enough to the way that synchronous expectations work that the same type of pattern can be followed. I would expect this to manifest as an `addAsyncMatchers` function on `Env.js` and exposed through the interface of Jasmine.

I would be happy to review a pull request for this, or a pull request to update the `toBeRejectedWith` matcher to include the object that was the source of the rejection. Note that it should use `j$.pp` to format the object and not `JSON.stringify` both for more consistent formatting of the object and because Jasmine's pretty printer will handle cycles in objects, where `JSON.stringify` will not.

**Comment by elliot-nelson** [comment]
I'm asking this just as someone curious (since you are finding value in them); what do you typically use an async matcher for?  If you have async/await capability, I guess I would expect this:

    expect(await promiseReturningThing()).toEqual(jasmine.any(Buffer));

To be "more readable" than:

    await expectAsync(promiseReturningThing()).toBeResolvedTo(jasmine.any(Buffer));

(I'm wondering if there use cases I'm just missing.)

**Comment by slackersoft** [comment]
`expectAsync` is also usable in a context with `Promise` support but without `async`/`await` support. So you could say:

```javascript
return expectAsync(promiseReturningThing()).toBeResolvedTo(jasmine.any(Buffer));
```

It can also be helpful for folks who want to think about these kinds of things as Promises that get resolved instead of as asynchronous things that they `await`.

**Comment by r4j4h** [comment]
In addition to the points @slackersoft pointed out, I think handling promise rejection with expectAsync is a bit more readable than having try/catches sprinkled about the tests:

```javascript
try {
  await promise;
} catch (e) {
  expect(e).toEqual(
      jasmine.any(Buffer)
  );
}
```

```javascript
return expectAsync(promise).toBeRejectedWith(jasmine.any(Buffer));
```

They also fail differently:

awaited equals:
```
Expected Error: demo to equal <jasmine.any(Buffer)>.
```

toBeRejectedWith
```
Expected a promise to be rejected with <jasmine.any(Buffer)> but it was rejected with Error: demo.
```

To be fair, that can be ameliorated with withContext somewhat:

```javascript
expect(e).withContext("Expected a promise to be rejected with a different value").toEqual(
  jasmine.any(Buffer)
);
```

```
Expected a promise to be rejected with a different value: Expected Error: demo to equal <jasmine.any(Buffer)>.
```

**Comment by elliot-nelson** [comment]
Ah, that makes sense; the `toBeRejectedWith` syntax does look good.  In fact I think that uncovered a big blind spot I had:

```js
// This won't work! It'll throw inline and break the test.
expect(await promise).toThrowError('demo');

// This won't work either! await promise not allowed in non-async function
expect(() => await promise).toThrowError('demo');

// This won't work either! it doesn't throw, it rejects
expect(async () => await promise).toThrowError('demo');
```

For some reason I thought there was a way to collapse an awaited promise into a `toThrowError` matcher, but I think there isn't.

**Comment by sgravrock** [comment]
Custom async matchers were added in f77ee32c5663c17919604f235fda222ad412fb11 by @UziTech and should be in the next release of Jasmine.

**Comment by UziTech** [comment]
@sgravrock when can we expect a new release?

**Comment by sgravrock** [comment]
@UziTech I'm not sure. Jasmine releases tend to happen when there's enough new stuff queued up and when there's a solid block of maintainer time to actually create the release. I think we've cleared the first one but the second can be hard to predict.

**Comment by slackersoft** [comment]
Jasmine 3.5 is out now. The ruby release is taking a bit longer, but should be done shortly

**Comment by dotnetCarpenter** [comment]
Could someone please write a small example of how to write an async matcher? The current documentation for [`custom matcher`](https://jasmine.github.io/tutorials/custom_matcher) does not really tell me how to implement an async custom matcher.

However, it seems like I can use the approach in [spec/core/integration/CustomAsyncMatchersSpec.js](https://github.com/jasmine/jasmine/commit/f77ee32c5663c17919604f235fda222ad412fb11#diff-77a6e019b84ccc8a834431d61c9c6cd46553c7e690ee45d130fc385ea6cda82c)

**Comment by sgravrock** [comment]
You can also look at [Jasmine's built in async matchers](https://github.com/jasmine/jasmine/tree/main/src/core/matchers/async). Jasmine doesn't differentiate between built-in and user-supplied matchers, so they should be workable examples to follow with a couple of caveats:

* There's some boilerplate around them related to Jasmine's module system.
* Some of the things they use internally (like `j$.isPromiseLike`) are private APIs that you shouldn't rely on.

Async matchers are basically like regular matchers except that Jasmine expects them to return a promise that eventually resolves to a matcher result.

**Comment by sgravrock** [comment]
Custom async matchers are also now covered in the custom matcher tutorial: https://jasmine.github.io/tutorials/custom_matchers#section-Custom_async_matchers
