### ISSUE TITLE
Spec 'x' has no expectations.

### ISSUE THREAD

**Issue by GrosSacASac** [jasmine/jasmine#1704]
Spec 'x' has no expectations.

## Expected Behavior

it should be a warning

## Current Behavior

it is an error (in the console)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("regular use", function() {
		it("basic use should work", function() {
			var x = new X();
			x.run();
		});
	});
```
## Context
I run some simple statement and not throwing an error is enough for the test to make sense

## Your Environment
jasmine-core": "3.4.0
(browser)

**Comment by slackersoft** [comment]
> I run some simple statement and not throwing an error is enough for the test to make sense

This is exactly why it doesn't fail your test. Jasmine logs it as an error in the browser console because the absence of expectations is often a mistake.

**Comment by GrosSacASac** [comment]
I understand, my proposal is to make it a warning

**Comment by slackersoft** [comment]
Can you expand a bit more on what issues you're seeing with it using `console.error` instead of `console.warn`? I'm not necessarily averse to the change, but I don't want to have change just for changes sake.

**Comment by GrosSacASac** [comment]
I think it is more consistent to use console.warn for warnings. Feel free to close the issue.

**Comment by slackersoft** [comment]
You're right, I see what you're talking about. Sorry for the confusion, will be fixed in the next release
