### ISSUE TITLE
Can we get a mention in the docs somewhere for @testdeck/jasmine?

### ISSUE THREAD

**Issue by silkentrance** [jasmine/jasmine#1707]
## Question

We have created a wrapper for existing test frameworks, including also jasmine.
Please see https://github.com/testdeck/testdeck and also https://github.com/testdeck/testdeck-jasmine-seed for a working minimal setup.

Perhaps you can give us a little boost by mentioning the project in your official documentation?

TIA!

**Comment by slackersoft** [comment]
A link from the Jasmine docs seems like it would be an endorsement of your project. I don't really have time to review any of the various projects that wrap Jasmine to change the behavior, so I don't think I would be able to give a sincere endorsement.

**Comment by silkentrance** [comment]
Too bad, but I thank you anyway for taking your time. For back reference: https://github.com/testdeck/testdeck-marketing/issues/2
