### ISSUE TITLE
Implement "skip()" in Jasmine

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1709]
## Summary

Jasmine should support a `skip()` interface.  This issue is being filed so before any work is done, we can agree on what that interface should look like.

### VARIANT 1: Straight up call, no message
```
it("isn't finished yet", function() {
    skip();
    callAMethodThatDoesntExist();
});
```

### VARIANT 2: Straight up call, with explanatory message
```
// it
it("isn't finished yet", function() {
    skip("need to implement this");
    callAMethodThatDoesntExist();
});

// Or before
beforeEach(function() {
    skip("these tests don't work yet");
});

// Or after
afterEach(function() {
    skip("this cleanup phase is broken");
});
```

### VARIANT 3: Skip _partial_ test, no message
```
it("isn't finished yet", function() {
    skip(function() {
        callAMethodThatDoesntExist();
    });
});
```

### VARIANT 4: Skip _partial_ test, with explanatory message
```
it("isn't finished yet", function() {
    skip("need to implement this", function() {
        callAMethodThatDoesntExist();
    });
});
```

### VARIANT 5: Skip full test (wrapper approach)
```
it("isn't finished yet", skip(function() {
    callAMethodThatDoesntExist();
}));
```

### VARIANT 6: Skip full test (wrapper approach w/message)
```
it("isn't finished yet", skip("need to implement this", function() {
    callAMethodThatDoesntExist();
}));
```

### VARIANT 7: Skip block of tests (suite level)
```
describe("My Module", function() {
    it("works", function() { });

    skip("need to implement these", function() {
        it("fails", function() { });
        it("fails again", function() { });
    });
});
```

I am including Variants 5-7 so we can intentionally include or exclude them.  Variants 1-4 all happen "inside" a running spec context; Variants 5-7 would be outside a running spec but in a suite context, so we'd need to detect that and behave differently _if_ we cared to support it.

## Proposed Behavior

My understanding of how `skip()` should work is that it should immediately exit the _current function_, and any follow-up functions _at that level_.  It should still execute any functions at any level _above this level_.

```
Level        Function Containing skip()
-----        --------------------------
0            beforeAll
1              beforeEach
2                beforeEach
3                  it
2                afterEach
1              afterEach
0            afterAll
```

Expressed as requirements:
- If `skip()` is encountered inside `it`, skip the rest of this `it`.  _All_ afterEach's defined must be called in order as usual.
- If `skip()` is encountered inside a `beforeEach`, skip the rest of that `beforeEach`, skip the `it` we were about to execute, and skip the same-level corresponding `afterEach`.  All `afterEach` defined above this level must still execute -- for example, a `skip` encountered in Level 2 will skip Level 2's afterEach but not Level 1's.
- If `skip()` is encountered inside a `afterEach`, skip the rest of that function, but nothing else.
- If `skip()` is encountered inside a `beforeAll`, I'm not sure what should happen.  Either literally no tests at all should run (i.e. report NOTHING), or, we should run everything but every single beforeEach, it, and afterEach is skipped.  The `afterAll` is also skipped in this case.

## Relationship with `pending()`

There are similarities between `pending()` and `skip()`.  I think the skip interface should make it intentional that Jasmine will never for any reason attempt to run the skipped content, and that it is well-suited for:

  - Broken code (potentially unrunnable)
  - Unsafe code (code with side effects that could break other tests)
  - Slow tests (i.e. a large suite with tests that are all timing out due to an error)
  - Intermittent tests (sometimes pass, sometimes fail)

The intention for `pending()`, I believe, is tests that are fundamentally sound but are just not passing yet, which is not the same category as the situations above.

## Changes to Reporting API + Packaged Reporters

TODO: Decide whether we need to and can report "skipped" and "pending" tests separately to reporters, update the reporting API, and update packaged reporters to display this information.  Determine whether we can make this a non-breaking change (ideally, outdated custom reports simply take a new field -- skipped -- that they don't display until they are updated).

## Changes to shortcut (xit/xdescribe) functions

TODO: Is it appropriate to change xit/xdescribe to "skip" instead of "pending"?

Comparisons to other popular projects: Mocha just copies Jasmine, so `xit` translates to `pending`.  RSpec interprets `xit/xdescribe` as _skipped_, NOT _pending_, so we could align with them in Jasmine if desired.

## New helper shortcuts

Speaking of RSpec, note that they provide the `it` "replacements" `skip` and `pending` (so `skip("blah", function() {` instead of `it()`) to easily mark tests as skipped or pending.  "skip()" is identical to "xit()" for RSpec.  These might be alternative, _better_ approaches than supporting Variants 5-7 up above.  However, this would increase the additions to global scope.

## Approach

Sorry for the essay.  I'd like to see this functionality, and want to make sure it's laid out for anyone who might want to tackle it.  I'll plan on updating these requirements based on comments below.

**Comment by slackersoft** [comment]
My inclination is that we really only need Variants 1 & 2 from here. The other options seem to have much lower usefulness. My basic thoughts for `skip` are to have a way to cause _all_ of the specs in  a `describe` (and their `beforeEach`, etc.) to not run and supply a message about why this is being done. I think a fine first pass would be to have `skip` work like having `oneFailurePerSpec` turned on when called and jump straight to cleanup. I think it's probably even fine to have it not worry about the levels of hierarchy when determining where in the cleanup to jump to.

If `skip` is called from within a `beforeAll` it should behave just like `xdescribe` but with the addition of an optional error message. I believe the reporter changes with 3.0 should already have a difference with `excluded` vs. `pending` as different statuses.

**Comment by raketenolli** [comment]
1 and 2 are very useful and if we have
```
it("a test", function() {
  doStuff();
  skip();
  doMoreStuff();
}
```
then `doMoreStuff()` should not be executed, but `doStuff()` should. I don't really have an opinion on whether the test should be marked as "skipped" anyway. Probably should.

Why I came here is because of #1579 and I would like to be able to skip tests from a `beforeEach()` but retain the continue-after-failed-expectation functionality, which is not possible currently.

**Comment by slackersoft** [comment]
@raketenolli I believe your example inside a single `it` should work currently with `pending`. I would want to make sure that also works with a `skip`, but the primary use case for `skip` is to differentiate between a temporary disabling (`pending`) vs a more permanent one (`skip`). The goal of `skip` would in fact be to have it skip tests from a `beforeEach` without needing to turn on the `oneFailurePerSpec` option.

**Comment by codymikol** [comment]
I'm working on a PR for this

**Comment by JaredAAT** [comment]
Is there a reason why this wouldn't be implemented as `describe.skip()` and `it.skip()` like jest and mocha do?

**Comment by slackersoft** [comment]
@JaredAAT because that wouldn't be consistent with any of the other interfaces in Jasmine. I could see having a discussion about changing the interface for `pending` and possibly `xit`/`xdescribe` etc., but matching the exact syntax of other testing frameworks is probably not going to be a good enough reason to make that kind of breaking change.

**Comment by sgravrock** [comment]
I think I sort of accidentally implemented this.

4.0 included two changes that, together, more or less turn `pending` into `skip`:

* `pending` can be called from `beforeEach`
* When a `beforeEach` throws an exception (which `pending` does), subsequent `beforeEach`/`it`/`afterEach` fns are skipped according to the rules outlined in the original proposal.

As far as I can tell, that makes the behavior of `pending` identical to the proposed behavior of variants 1 and 2, which I agree are all we need. I understand that there's still potential value in the semantic difference between `skip` and `pending`. But I don't think that, by itself, is worth the extra complexity in Jasmine and the impact on third party reporters.
