### ISSUE TITLE
Suggestion: officially treat spies on `x#get` and `x#set` as properties

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1714]
I'd like to extend `spyOn` slightly so that these two are equivalent:

```js
spyOn(object, 'thing#get').and.returnValue(42);
spyOnProperty(object, 'thing', 'get').and.returnValue(42);
```

If we make the string `prop#[get|set]` the official way to refer to property spies, we get a couple of benefits:

- The existing `createSpyObj` function gets property spies for free, since `'prop#get'` can jus be included in the string array passed to `createSpyObj`.  This would close PR #1569.

- The upcoming `getSpy` functionality I'd like to add would no longer need a corresponding separate `getSpyOnProperty` method -- you could just do `getSpy(object, 'field#get').and.callThrough()` in order to change the behavior of an existing property spy.

- The current `spyOnProperty` method already exists so we'd keep supporting it.  Maybe we could mark it deprecated for a far-future release to remove in favor of this new syntax.

## Context
The goal here is to make spying on properties both as simple and as _similar_ (to function spies) as possible.  I think this would get us really close and looks, imo, reasonable.

**Comment by slackersoft** [comment]
I think `spyOnProperty` is _far_ more discoverable than the option to tack on a `#get` would be. I'm not inclined to have two different ways to accomplish the same task unless it solves some greater problem.

I would also argue that needing to change the strategy for a spy on a property indicates that you don't really have a property, but should convert it to be a function, and this is just a way for the tests to help you realize this.

**Comment by elliot-nelson** [comment]
OK, that's fair.

Your preference on properties vs functions makes sense to me, but usually I'm not using a spy to mock my _own_ code, I'm mocking a resource I'm using that I didn't write.  So I'm at the mercy of that API, which may be property-happy.

For one-off usage simply saving the spy for reuse works.  That doesn't work for the createSpyObj case, but I guess the original plan (a getSpy-type function) might work.

I wonder if you'd consider adding a way to respy on a property one-off, rather than allowing respy across the board. If I can do either of these:

    respyOnProperty(foo, 'bar', 'get').and.stub();
    spyOnProperty(foo, 'bar', 'get', true /* respy */).and.stub();

Then you don't need a getSpy, as a getSpy is really just a spyOn for existing spies.

**Comment by slackersoft** [comment]
If I had to pick one, I would lean toward options to the existing `spyOn` and `spyOnProperty` functions instead of adding new functions to Jasmine's top level interface. This interface would also jive well with the discussion in #953 around what the interface for "respying" would look like.

**Comment by elliot-nelson** [comment]
OK.  Having a final optional boolean (e.g. `spyOn(foo, 'bar', true)` and `spyOnProperty(foo, 'bar', 'get', true)`) would work for me.

It's worth asking, is it possibly time to change the _default_ to allow respy -- or, even, completely remove the concept of erroring on respying?  Every time I have run into this error, my only reaction is to change `spyOn(foo, 'bar').and` to `foo.bar.and` -- because the goal is to provide different behavior for the spy.

I understand the goal is probably to alert users to a _potential_ mistake, but things like defining duplicate test names, calling `expect` without a matcher, defining `describe` blocks with no function, etc., are all also potential mistakes, and we rely on third party linters for those.  Is there any reason not to completely remove this error, simplifying the whole concept of spying, and assuming that if people need "protection from respy" they'll create a linting rule to provide it?

**Comment by slackersoft** [comment]
I would argue that using `spyOn` over a function is _most likely_ a mistake since it demonstrates that the function is not currently expected to be a spy in this context. If something is a spy when not expected, it is likely that your tests aren't testing the things you think they are. Making this option explicit gives you a way to look at the one line of code where the change to the spy strategy is being made and know that the spy was originally installed elsewhere. I think for the time being we'll leave the default as is.

**Comment by elliot-nelson** [comment]
Closing this suggestion, we'll just call it covered by https://github.com/jasmine/jasmine/pull/1719.
