### ISSUE TITLE
Feature suggestion: Add toHaveBeenCalledOnceWith matcher

### ISSUE THREAD

**Issue by Maximaximum** [jasmine/jasmine#1717]
It would be extremely useful to have a `toHaveBeenCalledOnceWith()` matcher combining both `toHaveBeenCalledTimes(1)` and `toHaveBeenCalledWith()` matchers.

About 70% of my unit test expectations about functions look like this:
```typescript
expect(backendService.get).toHaveBeenCalledTimes(1);
expect(backendService.get).toHaveBeenCalledWith('SomeArgument', someSecondArgument);
```

It would be really much, much more readable if we could have a single matcher that combines both matchers:
```typescript
expect(backendService.get).toHaveBeenCalledOnceWith('SomeArgument', someSecondArgument);
```

**Comment by 14nrv** [comment]
@Maximaximum 

there is `toHaveBeenNthCalledWith` on [jest-extended](https://github.com/jest-community/jest-extended/issues/138)

```
const mock = jest.fn()
expect(mock).toHaveBeenNthCalledWith(1, 'foo')
```

**Comment by Maximaximum** [comment]
@14nrv 
1. As far as I see, it's only a suggestion there, not yet supported.
2. It's toHaveBeenNthCalledWith, which is quite different from what I suggest. My suggestion ensures that the function has been called exactly n times (specifically, 1 time).
3. I'm not using Jest and, as far as I see, it cannot be used as an extension to jasmine, but rather as a replacement, which is not what I would like to do

**Comment by slackersoft** [comment]
I think that probably makes sense as a nice way to simplify your assertions in your specs. I'd be happy to review a pull request to add the new matcher. Ultimately, the spy matchers probably need to be re-worked a bit to allow a more fluent use of call count and argument assertions in a single `expect` call, but that might be a bit further out in the future.

**Comment by Maximaximum** [comment]
@slackersoft Thank you.

I've created a PR for this feature, it's now awaiting for your review :)
