### ISSUE TITLE
custom reporter for disabled tests

### ISSUE THREAD

**Issue by vasiliyb** [jasmine/jasmine#1727]
Folks, we have a need to report on tests which are disabled using a custom reporter.  Is this something that is easily implementable in https://github.com/jasmine/jasmine/blob/066162d6bceefa8c59b5080ef9d32571e56e9b39/lib/jasmine-core/jasmine.js#L1374-L1442 

i.e. `specDisabled` and `suiteDisabled` ?

Thanks!

**Comment by slackersoft** [comment]
Take a look at the [Reporter](https://jasmine.github.io/api/edge/Reporter.html) interface for Jasmine and you can see what kind of data you get back for the various reporter callbacks. We also have a [tutorial for writing a custom reporter](https://jasmine.github.io/tutorials/custom_reporter).

Hope this helps. Thanks for using Jasmine!
