### ISSUE TITLE
subscribe is deprecated: Use an observer instead of a complete callback

### ISSUE THREAD

**Issue by andrey-nastasyev** [jasmine/jasmine#1729]
I wrote test and wrote following expect
expect(closedSubscription.subscribe).toHaveBeenCalledTimes(2);

but i received following issue

> subscribe is deprecated: Use an observer instead of a complete callback

How to fix it?

**Comment by slackersoft** [comment]
It looks like your code under test is using some external code that has deprecated that function. Jasmine doesn't include any subscription management, so I don't think this is related to Jasmine itself.

Hope this helps. Thanks for using Jasmine!
