### ISSUE TITLE
Mark suite as pending?

### ISSUE THREAD

**Issue by janpio** [jasmine/jasmine#1730]
I tried to use a contidional `pending()` (should only apply when the test suite is run in a specific CI enviroinment) in the context of `describe` instead of `it` and didn't have the result I expected:

```
Suite error: SUITENAME
  Message:
    => marked PendingPENDINGREASON
  Stack:
```

The whole suite was counted as 1 failure.

---

Upon checking the documentation I noticed of course that `pending` is indeed documented as to work for specs only:

> Mark a spec as pending, expectation results will be ignored.

https://jasmine.github.io/api/3.4/global.html#pending

---

I also know `.pend()` exists for both `it` and `describe`, but that can not be conditional as far as I know - when I use that the suite is always pending.

---

Is there any other way to conditionally disable (make pending) a whole suite of tests?

**Comment by janpio** [comment]
Looking at the source of both Spec and Suite, it also shouldn't be too hard to just enable `pending()` to work in the context of a suite as it just throws an exception that has to be handled in the suite [similar to how it is for specs](https://github.com/jasmine/jasmine/blob/066162d6bceefa8c59b5080ef9d32571e56e9b39/src/core/Spec.js#L134-L138). Would you be interested in a PR for that?

**Comment by slackersoft** [comment]
You should be able to call `pending` from within a `beforeEach` (maybe even `beforeAll`) to get the ability to specify a message when marking a group of specs as pending. Note that this will mark each individual spec as pending and not necessarily the suite itself. (If `beforeAll` works, it might get you the pending status at the suite level, but I'm not sure).

Hope this helps. Thanks for using Jasmine!

**Comment by janpio** [comment]
Thanks!
