### ISSUE TITLE
Feature Request: Ability to configure 'spec has no expectations' as error

### ISSUE THREAD

**Issue by Evangelinexx** [jasmine/jasmine#1740]
## Feature Request
Some of our repos have hundreds upon hundreds of tests, and seeing which ones are incorrectly implemented as they have no expectations can be difficult. I understand that by default most people would want to keep the current functionality with tests with no expectations being warnings, but I would like the option to flag these as errors.

## Possible Solution
As far as I can find, and documentation on configuring jasmine is hard to find, it would be as simple as having another configuration variable in the jasmine.json, then failing tests which come across that error if the variable is true.

eg.
```
specHasNoExpectationsIsError: true
```

### Notes
I can see that this has been referenced before, but all of the relevant issues are closed, and none of them went in the direction of making this configurable. The closest I could find was #1467, which simply suggests we just fail tests with no expectations. Someone in the thread suggested making it configurable but that went nowhere.

**Comment by krawetko** [comment]
Agree, this would be very useful especially now when Mono-Repos are so widely used. In our mono-repo we have enormous amount of unit tests and ensuring they are correctly implemented has become a struggle. Having opportunity to fail the test when there are no expectations would be a nice improvement.
