### ISSUE TITLE
jasmine.anything() => is not a function

### ISSUE THREAD

**Issue by Raycoms** [jasmine/jasmine#1744]
I am using Node.js to test my class.

I got jasmine setup nicely:
```
import { jasmine } from "../jasmine.mjs";

const { describe, it, expect, spyOn } = jasmine.env;
```

```
describe( "handleTest", () => {

  beforeAll(function() {
    spyOn(service, "sendTransfer").and.callFake(() => '');
    spyOn(service, "sendMemo").and.callFake(() => '');
  });


  it( "No refund", async () => {
    await service.handleTest(notEnoughMsg);

    expect(service.sendTransfer).toHaveBeenCalledWith('ray', '0.001', 'sth', "text", jasmine.anything());
  } );
} );
```

But when I execute this I get:

TypeError: jasmine.anything is not a function

(Same for any)

**Comment by Raycoms** [comment]
Seems I have to do jasmine.jasmine.any

**Comment by slackersoft** [comment]
How are you installing Jasmine? Jasmine out of the box doesn't really allow a way (right now) to import specific portions into a single file. It just installs itself and everything onto the `global` object (`window` in a browser). It looks like whatever shim you're using to allow that `import` is causing some extra wrapping to happen.
