### ISSUE TITLE
question: how to update spec script tag and re-run with standalone jasmine

### ISSUE THREAD

**Issue by cjbd** [jasmine/jasmine#1748]
hello, apologies if i posted in the wrong place, i didn't see repo for standalone jasmine in browser

i'm using standalone jasmine in browser, i added my spec.js after the jasmine js files like this:

```html
<script src="https://cdn.jsdelivr.net/npm/jasmine-core@3.1.0/lib/jasmine-core/jasmine.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jasmine-core@3.1.0/lib/jasmine-core/jasmine-html.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jasmine-core@3.1.0/lib/jasmine-core/boot.js"></script>
<script id="myspec" type="module" src="spec.mjs"></script>
```
i'm trying to use jquery to update my spec file, and then re-run the test, the jquery part is easy
but after changing the last script tag, it won't run any test
```js
$('#myspec').remove();
var script = document.createElement('script');
script.setAttribute('type', 'module');
script.setAttribute('src', 'newspec.mjs');
document.body.appendChild(script);
```
is there any jasmine api that i can use to re-execute the test cases again?
thanks!

**Comment by slackersoft** [comment]
Jasmine doesn't really expect to be run that way. A Jasmine Environment object (`Env`) only expects to be `execute`d once after loading all of the available specs. If you want to perform multiple runs inside a single browser window without reloading the page, you'll nee to implement your own custom jasmine boot logic (https://jasmine.github.io/tutorials/custom_boot) and wrap your create and load script inside something create a _new_ `jasmine.Env` then load your script, and once the script is fully loaded call `execute` on the new `Env`. This _should_ allow you to run a new Jasmine with the completely changed out list of specs.

Hope this helps. Thanks for using Jasmine!

**Comment by cjbd** [comment]
@slackersoft , thank you for the reply, custom boot looks complicated to me, i'm thinking refreshing iframe with html string, that looks simpler
