### ISSUE TITLE
Feature Request : Dynamic Test Cases which run on Condition after Suite has ran should be supported

### ISSUE THREAD

**Issue by EnZWebAppZ** [jasmine/jasmine#1749]
Assuming a use case where I need TestCases A,B,C to run if an element is present on browser,
and TestCases D,E,F to run if element is **not** present on browser.

As of now this is not possible on jasmine because it is not possible to modify specs after jasmine suite is ran. 

As a result, the test would need to run A.B,C,D,E,F and have conditions in all tests to determine if element is present before deciding to do assert or not.

1) Tedious and messy as **EVERY SINGLE** test needs to test if element is present before doing actual test.
2) 3 Test cases are guaranteed to be **redundant** in either condition.

Related issue : 
https://github.com/jasmine/jasmine/issues/754

**Comment by tymfear** [comment]
This is going to end up as a bunch of a leaky tests. You should design you test logic in a way, that you know exactly, what there should be on the screen. Conditional tests shows that you do not control your test flow. 

And if you need to test something according to what is on a screen, just split specs into different suits with preconditions that ensure test flow. And then just execute the suit that you need.

**Comment by EnZWebAppZ** [comment]
In the context of the use case described, pretty sure the test flow is decided by a single and simple condition to where an element is present, so not quite why control is lost here.

I understand the portion about splitting suites with preconditions, but what if there is no way to determine the precondition before the test is even run?

Back to the context of my use case, if the element is decided by a flag value from an external source which I have no access to,  then wouldn't I be entirely dependant on the UI for the status of the element? 

Please suggest a solution in regards to my use case.
Even if I split A B C and D E F into 2 different flows, 1 of the flow will always fail because the element cannot be present and not present at the same time. Or if there is a possibility to run the suite and determine which test cases to run at run-time.

**Comment by slackersoft** [comment]
The problem with making whole portions of your test suite conditionally run is that it makes it potentially impossible to tell whether a passing suite ran all of the specs that it was meant to. If you are explicit about your setup and configure the code under test into the situation it needs to be in for the tests, you can just run all of the tests and let the setup and tear-down do their work.

From your example it sounds like you're trying to test 2 separate systems in conjunction with each other. You might want to look at splitting some tests out that can test the flows in isolation from whatever backend system is configuring which elements on the page, and then maybe a more holistic test in a special environment where you can programmatically control whatever configuration is necessary to get a consistant setup.

The thing that can happen with conditional tests, is that both conditions you're checking for could be false and then you wouldn't run any tests at all. So Jasmine leans away from making an incorrectly green test suite too easy.

Hope this helps. Thanks for using Jasmine!

**Comment by EnZWebAppZ** [comment]
1) Once again, the only way I would know if the element exists is **ONLY** at runtime after the browser has been fired up. Absolutely no access to backend value populating the element whatsoever.

2) Please refer to my use case. The element cannot be present and missing at the same time. My flow is controlled in a sense it is GUARANTEED to either run 
A) TEST A B C when element is present
B) TEST D E F G H when element is not present

It really seems appalling to me when dynamic test cases (a simple straightforward requirement) cannot be supported by jasmine, and the practical solution is to work around the problem by using if-else statements WITHIN it blocks and trying to give expect statements the most appropriate description.

what i ended up doing in my scenario: 

it("cannot support dynamic test case so : "){
  if(elem.present())
  {
    expect(a).toEquals(c, " because element is present and a has to equal c");
  }
  else
  {
   expect(b).toEquals(d, " because element is not present and b has to equal d");
  }
}


And the downside is u will never know which condition ran successfully because apparently jasmine doesn't support successful expect statements either.

PS : I'm daft and will not fully understand your ornamental concepts unless you give me examples to illustrate your point, Please advise what I can do given my use case posted here and above.

PS2 : Im using Protractor if it helps
