### ISSUE TITLE
Error: TypeError: Reflect.hasOwnMetadata is not a function using inversify-express with jasmine

### ISSUE THREAD

**Issue by dedreira** [jasmine/jasmine#1757]
Hi all,
I have a very simple nodeJS api built with typescript, inversify and inversify-express-utils, and for testing I want to use jasmine.

the repo is here:  https://github.com/dedreira/typescript-webapi-inversify

When I try to run the tests suite this error appears:

C:\Users\dedreira\source\GitHub\typescript-webapi-inversify\node_modules\inversify\lib\annotation\decorator_utils.js:22
    if (Reflect.hasOwnMetadata(metadataKey, annotationTarget)) {
                ^
**TypeError: Reflect.hasOwnMetadata is not a function**
    at _tagParameterOrProperty (..\GitHub\typescript-webapi-inversify\node_modules\inversify\lib\annotation\decorator_utils.js:22:17)
    at Object.tagProperty (..\GitHub\typescript-webapi-inversify\node_modules\inversify\lib\annotation\decorator_utils.js:12:5)
    at ..\GitHub\typescript-webapi-inversify\node_modules\inversify\lib\annotation\inject.js:27:31
    at __decorate (..\GitHub\typescript-webapi-inversify\node_modules\inversify-express-utils\lib\base_http_controller.js:5:110)
    at ..\GitHub\typescript-webapi-inversify\node_modules\inversify-express-utils\lib\base_http_controller.js:54:5
    at Object.<anonymous> (..\GitHub\typescript-webapi-inversify\node_modules\inversify-express-utils\lib\base_http_controller.js:62:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

I know that the problem is with the echo-controller (that uses inversify-express) because if I comment this class the other tests run ok.

I don't know how to fix it, but I think it might be a misconfiguration error . . . anybody have any idea? of course, if I transpile the code and run it it executes perfectly :)

Thanks!

**Comment by slackersoft** [comment]
Based on the stacktrace you provided. It looks like this is likely an issue with Inversify or possibly with your babel/typescript/etc configuration when running tests. I would recommend asking in a more Inversify specific forum, or if you believe it is a Jasmine + Inversify configuration thing, you can try the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using Jasmine!

**Comment by dedreira** [comment]
I think it's related to jasmine because I'm able to compile it using tsc and run the resulted javascript with no errors, but when I run jasmine it crashes. 

I'm pretty sure this is something related with configuration, but I'm a little bit lost. I don't know if I can specify jasmine which tsconfig.json file should use to transpile my typescript before running the tests . . .

**Comment by slackersoft** [comment]
Jasmine doesn't actually do any TypeScript (or other) transpiling, so you would have to setup and configure that yourself. Depending on the rest of your setup, you can either run your tests and production code through the compiler and the point Jasmine at those files, or follow some of the relevant steps from our [React tutorial](https://jasmine.github.io/tutorials/react_with_npm), specifically the `@babel/register` and TypeScript setup.

Hope this helps.

**Comment by dedreira** [comment]
Ok, thanks for your help, I'll try the solution you gave me. Now I found a workaround by testing the controller code through an e2e tests and this way the tests don't crash.
