### ISSUE TITLE
Uncaught exception: TypeError: Cannot set property 'jasmineMessage' of undefined

### ISSUE THREAD

**Issue by maxbilbow** [jasmine/jasmine#1759]
Error occurs on this line when `error` is undefined.: https://github.com/jasmine/jasmine/blob/ef3f127d270ccbbd6dde3fe161e0e85474f19369/lib/jasmine-core/jasmine.js#L3805

The error displayed isn't too helpful:
![image](https://user-images.githubusercontent.com/11065417/67304195-6164d200-f4eb-11e9-87b1-6291ded208e8.png)

Seems to be caused by an unhandled promise rejection but does not occur within any specific test.

Could it be to do with the use of `async`?

**Comment by chrisdeely** [comment]
what version of node are you using? are you able to generate a test for reproduction?
It seems likely that the cause is ultimately an error being thrown from within an `async` method, but I'm not sure why the `error` object would be `undefined` in that case

**Comment by horyd** [comment]
I was receiving this error because I had a `Promise.reject()` somewhere

**Comment by slackersoft** [comment]
I would be happy to review a pull request that can detect this kind of issue at the point where Jasmine is trying to combine up the error messages to _at least_ not clobber any existing error with an error entirely within Jasmine.

**Comment by bennycode** [comment]
For me "`Uncaught exception: TypeError: Cannot set property 'jasmineMessage' of undefined`" popped up when using:

```ts
const createSession = spyOn<LoginAPI>(apiClient.rest.login, 'createSession').and.rejectWith();
```

My problem was, that my code was calling `void apiClient.rest.login.createSession`. So I was calling the Promise without awaiting it and my test passed but the Promise failed silently in the background and caused the above error message.

I could solve it by awaiting the Promise. Another possibility would be to not let it fail:

```ts
const createSession = spyOn<LoginAPI>(apiClient.rest.login, 'createSession').and.callFake(() => {});
```
