### ISSUE TITLE
How to create instance of a factory in jasmine?

### ISSUE THREAD

**Issue by raj-chaurasia** [jasmine/jasmine#1769]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by raj-chaurasia** [comment]
I have a factory and I want to test its functions using jasmine. I want to understand how do I create the instance of factory? My code is as below.

**factory**:
angular.module('app.core').factory('sampleService', sampleService);

    function sampleService() {
        var service = {
			getItem: getItem
        };

        return service;

        function getItem(keyName) {

            if (keyName == null) {
                return null;
            }

            // retrieve the data from storage and parse it using JSON.parse if data is not null or undefined.
            var data = sessionStorage.getItem(keyName);
            if (data === null || typeof data === 'undefined' || data === "undefined") {
                return null;
            }
            return JSON.parse(data);
        }
    };

**Unit Test**
describe('sampleService', function () {
    var sampleServiceObj: any;

    beforeEach(function () {
        angular.module('app.core');
    });

    it('should return value 1', () => {

        //Arrange            
        sampleServiceObj = // How to create the instance???

        // Act
        var response = storageServiceObj.getItem('Id');

        //Assert
        expect(response).toEqual(10);
    });
});

**Comment by chrisdeely** [comment]
this is not a bug in jasmine, and would be better served as a question on [StackOverflow](https://stackoverflow.com/questions/tagged/jasmine). 
If you define your Angular modules in individual files, you can export the `sampleService` module and then import just that factory into your tests as needed. The Angular framework doesn't necessarily need to be used in your test suite at all.
