### ISSUE TITLE
New feature request: expectPromise

### ISSUE THREAD

**Issue by spck-test** [jasmine/jasmine#1770]
This is not really a bug, but hoping to not be ignored.

I appreciate how easy it is to test things with jasmine. I wrote some utilities to jasmine that really helps simplify my testing, one of them being an expectPromise proxy. It would be really great to add this to the library as it would help a lot of people out when testing promises. (I implemented this using a Proxy object, I could post the source code if anyone's interested.)

This is some sample code of how I use it:

```javascript
it('should do some stuff', done => {
    expectPromise(self.asyncMethod1()).toBe('result')
        .then(() => expectPromise(self.asyncMethod2()).toEqual('result2'))
        .then(() => expectPromise(self.asyncMethod3()).toEqual('result3'))
        .then(done, done.fail)
})
```

**Comment by elliot-nelson** [comment]
I think this helper might be confusing because it has a lot of overlap with the existing `expectAsync`.

If I rewrote your example as-is:

```javascript
it('should do some stuff', done => {
    expectAsync(self.asyncMethod1()).toResolvedTo('result')
        .then(() => expectAsync(self.asyncMethod2()).toBeResolvedTo('result2'))
        .then(() => expectAsync(self.asyncMethod3()).toBeResolvedTo('result3'))
        .then(done, done.fail)
})
```

If you add in the `await/async` keywords, it's a little cleaner than that:

```javascript
it('should do some stuff', async () => {
    await expectAsync(self.asyncMethod1()).toResolvedTo('result');
    await expectAsync(self.asyncMethod2()).toBeResolvedTo('result2');
    await expectAsync(self.asyncMethod3()).toBeResolvedTo('result3');
})
```

A third alternative, if you are using `await/async` and are not testing rejections, is to just await and then expect:

```javascript
it('should do some stuff', async () => {
    expect(await self.asyncMethod1()).toEqual('result');
    expect(await self.asyncMethod2()).toEqual('result2');
    expect(await self.asyncMethod3()).toEqual('result3');
})
```

Given these existing patterns to choose from, it might be overkill to add a fourth, competing style.

**Comment by sgravrock** [comment]
I'm going to go ahead and close this since we haven't heard anything in some time, and I expect that the examples provided by @elliot-nelson probably meet your needs. Feel free to open a new issue with more information if none of those approaches work for you.
