### ISSUE TITLE
Extracting error message in extractMessage() only works if stack trace starts with "Error .."

### ISSUE THREAD

**Issue by hermava** [jasmine/jasmine#1771]
In extractMessage() the error message cannot be extracted if the stack trace starts with something else then "Error". For example the message for "TypeError" won't be extracted because function messagePrefixLength() in extractMessage() returns 0, because there is no match for "match(/^Error/)".
 
https://github.com/jasmine/jasmine/blob/ef3f127d270ccbbd6dde3fe161e0e85474f19369/lib/jasmine-core/jasmine.js#L7789 
In the end that leads to an issue in function filterJasmine(). 

## Expected Behavior
messagePrefixLength() should consider error messages like "TypeError" or "ReferenceError", too

## Current Behavior
messagePrefixLength() just considers error messages which start with "Error" 

## Possible Solution
In https://github.com/jasmine/jasmine/blob/ef3f127d270ccbbd6dde3fe161e0e85474f19369/lib/jasmine-core/jasmine.js#L7789 change messagePrefixLength()
`if (!stackLines[0].match(/^Error/))` 
to 
`if (!stackLines[0].match(/^\w*Error/))`

**Comment by slackersoft** [comment]
That sounds pretty reasonable. The first effort here was just to get the stack trace filtering pulled up into `jasmine-core` so everyone could make use of it. I'd be happy to review a pull request to allow some sort of wildcarded error names like you've suggested here.

Thanks for using Jasmine!
