### ISSUE TITLE
Browsers: UnhandledRejection errors in specs not forwarded to onerror

### ISSUE THREAD

**Issue by johnjbarton** [jasmine/jasmine#1777]
## Expected Behavior

When this test is run in a browser
```js
describe('bla bla', () => {
  it('should fail', async () => {
    new Promise(() => {
      throw new Error('Foo bar');
    });
    await new Promise((resolve) => {
      setTimeout(resolve, 100);
    });
  });
});
```
I except window.onerror to report "Error: Foo bar"

## Current Behavior
Test passes :-(

## Possible Solution
In the `else` branch of `install()`,
```
        global.addEventListener('unhandledRejection', function (event) {
          onerror("UnhandledRejection: " + event.reason);
        });
```
https://github.com/jasmine/jasmine/blob/b4cbe9850fbe192eaffeae450669f96e79a574ed/src/core/GlobalErrors.js#L63

I started a PR but the tests runner integration test do not define global.process on the jasmineUnderTest. Rather than make guesses I thought it better to ask if there is some better way to implement or to test this feature.

## Suite that reproduces the behavior (for bugs)

```javascript
```js
describe('bla bla', () => {
  it('should fail', async () => {
    new Promise(() => {
      throw new Error('Foo bar');
    });
    await new Promise((resolve) => {
      setTimeout(resolve, 100);
    });
  });
});
```
```
## Your Environment
We already support this in nodejs, but the code for listeners is different in browsers.

**Comment by johnjbarton** [comment]
I verified that this issue would be fixed with the addition of the browser handler (when the event is spelled `unhandledrejection`.

So I believe the only issue is the test (and the possible issue that ancient browsers don't support addEventListener).

**Comment by sgravrock** [comment]
A test like this might work for both browsers and Node:

```
  it('fails the spec when an unhandled rejection occurs', function(done) {
    jasmine.getEnv().requirePromises();
    
    env.it('should fail', function() {
      new Promise(function() {
          throw new Error('Foo bar');
      });

      return new Promise(function(resolve){
        setTimeout(resolve, 0);
      });
    });

    var specExpectations = function(result) {
      expect(result.status).toEqual('failed');
      // ... also assert that the failure message is what was expected
    };

    env.addReporter({ specDone: specExpectations, jasmineDone: done });
    env.execute();
  });
```

There are also a number of tests in `GlobalErrorsSpec.js` that use mocks to test interactions with `onerror`, e.g.:

```
  it('calls previous handlers when one is removed', function() {
    var fakeGlobal = { onerror: null },
      handler1 = jasmine.createSpy('errorHandler1'),
      handler2 = jasmine.createSpy('errorHandler2'),
      errors = new jasmineUnderTest.GlobalErrors(fakeGlobal);

    errors.install();
    errors.pushListener(handler1);
    errors.pushListener(handler2);

    errors.popListener();

    fakeGlobal.onerror('foo');

    expect(handler1).toHaveBeenCalledWith('foo');
    expect(handler2).not.toHaveBeenCalled();
  });
```

Some of those interactions are difficult to verify with integration tests. It would make sense for those tests to also verify that Jasmine does the right thing with the `unhandledrejection` event.

I'm pretty sure that we no longer support any browsers that lack `addEventListener`, so that should be fair game.

**Comment by johnjbarton** [comment]
> Some of those interactions are difficult to verify with integration tests.

Sorry I was not clear. The problem I have is the *existing* integration tests fail because they are designed for nodejs *but* they do not mock the global test env to provide `global.process.listeners`.  Then when my modified `GlobalErrors.install()` runs, it takes the browser branch always.  I guess that causes no current issues, but when I add my `global.addEventListener()` call, all those tests fall over.

Having said that it seems clear that the existing behavior of accidental success is not desirable. I will look for a solution.
