### ISSUE TITLE
When test is fail - features

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1779]
When is used expect and this steps is as failed, in console log is this message only on the and in summary.

example:
it('some example', async () => {
        console.log('some log1');
        console.log('some log2');
        await expect(true).toBe(false, 'some message');
        console.log('some log3');
    });

in the console now will be:
some log1
some log2
some log3

and on the end will be:
**************************************************
*                    Failures                    *
**************************************************

1) some example
  - Expected true to be false, 'some message'.

When somebody read very long test log, it is not possible find moment, when is step fail.

It will be nice, see in console when is expect start. Something as:
some log1
some log2
expect true to be false, 'some message'.
some log3

**Comment by rebajz** [comment]
maybe in config do setting for enable/disable show expect in console.log.

**Comment by slackersoft** [comment]
Most of the things in Jasmine's configuration are intended for settings you might leave on full-time in a project. Since this functionality would not be something you would want on all the time, I'm not sure it needs to be in a configuration file. Aside from that, this type of debugging is usually short term enough, that simply doing a `console.log` for the particular values that are of interest to you is probably more intuitive than finding the correct setting in Jasmine to cause failed expectations to be printed out.

I'm happy to have some more discussion, but this doesn't seem to cross the line into needed functionality in Jasmine at this time.

**Comment by rebajz** [comment]
I understand. For now i do this...

```
public static async doAssert(methodName: string, currentValue: any, expectedValue: any, message: string, negative: boolean = false, precision: number = 0): Promise<void> {
        let screenshotPath = await desktop.takeDesktopScreenShot('assert-' + methodName);
        let pathArray;
        if (negative === false) {
            if (methodName === 'toBeCloseTo') {
                console.log(colors.yellow('Expect'), currentValue, _.startCase(methodName), expectedValue + ' (Precision: ' + precision + ')', colors.yellow(message));
                await (expect(currentValue))[methodName](expectedValue, precision, message);
            } else {
                console.log(colors.yellow('Expect'), currentValue, _.startCase(methodName), expectedValue, colors.yellow(message));
                await (expect(currentValue))[methodName](expectedValue, message);
            }
        } else {
            if (methodName === 'toBeCloseTo') {
                console.log(colors.yellow('Expect'), currentValue, 'Not ' + _.startCase(methodName), expectedValue + ' (Precision: ' + precision + ')', colors.yellow(message));
                await expect(currentValue).not[methodName](expectedValue, precision, message);
            } else {
                console.log(colors.yellow('Expect'), currentValue, 'Not ' + _.startCase(methodName), expectedValue, colors.yellow(message));
                await expect(currentValue).not[methodName](expectedValue, message);
            }
        }
        pathArray = screenshotPath.split('/');
        screenshotPath = pathArray.join('\\') ;
        console.log('Screenshot:', screenshotPath);
    };
```
