### ISSUE TITLE
Jasmine fails if node_modules is junction/symbolic link (Windows)

### ISSUE THREAD

**Issue by greenmooseSE** [jasmine/jasmine#1780]
## Expected Behavior
When calling ```.\node_modules\.bin\jasmine``` it should not fail with error, but work in same way as if node_modules folder is not a junction.

## Current Behavior
When node_modules is junctioned, jasmine will not run and fail with error below:
```
>.\node_modules\.bin\jasmine
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'glob'
Require stack:
- E:\TEMP\junctionTest\jasmine\lib\jasmine.js
- E:\TEMP\junctionTest\jasmine\bin\jasmine.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\TEMP\junctionTest\jasmine\lib\jasmine.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\TEMP\\junctionTest\\jasmine\\lib\\jasmine.js',
    'E:\\TEMP\\junctionTest\\jasmine\\bin\\jasmine.js'
  ]
}
```

## Suite that reproduces the behavior (for bugs)
On Windows (using PowerShell Core and yarn, when using npm the node_modules junction will be removed though):
1. Start in an empty directory
2. Initialize it with yarn ```yarn init```
3. Add jasmine ```yarn add jasmine --dev```
4. Verify jasmine works as expected
``` 
>.\node_modules\.bin\jasmine
Randomized with seed 85289
Started

No specs found
Finished in 0.008 seconds
Incomplete: No specs found
``` 
5. Remove nod_modules and junction it somewher:
```
del .\node_modules\ -Recurse -Force
mkdir e:\temp\junctionTest
New-Item -ItemType Junction -name node_modules -Target E:\TEMP\junctionTest
```
6. Verify dir is junctioned
```
>(get-item .\node_modules\).LinkType
Junction
```
7. Re-install modules 
```
>yarn install
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.47s.
```
8. Try run jasmine again, notice it now throws error:
```
>.\node_modules\.bin\jasmine
internal/modules/cjs/loader.js:969
    throw err;
    ^
...
```

## Context
Avoid GDrive-syncing folders (bin/obj/nuget/node_modules etc.) by junctioning them to a non-synced folder.

## Your Environment
* Version used: Jasmine 3.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js v13.5.0, yarn v1.21.1
* Operating System and version (desktop or mobile): Windows 10

**Comment by slackersoft** [comment]
When you do this move where you do a Junction on windows, do other npm packages work correctly when executed in this way? The [line in lib/jasmine.js](https://github.com/jasmine/jasmine-npm/blob/v3.5.0/lib/jasmine.js#L3) that is throwing an error is just the first time that Jasmine attempts to `require` one of its dependencies that isn't part of the system Node.js libraries. It looks, from the rest of your stacktrace, that it is actually Node.js being unable to load the module from that Junction, and I would expect other libraries to have similar issues.

**Comment by greenmooseSE** [comment]
Thanks, you are right; I observe same behavior with Mocha. Thus closing this.

FWIW, the solution for me was to use ```yarn install --modules-folder `"<junction-target>"```, and then junction node_modules targeting that path.
Then Jasmine works (although Mocha doesn't).
