### ISSUE TITLE
Cannot find module "watch"

### ISSUE THREAD

**Issue by inf3rno** [jasmine/jasmine#1784]
I installed jasmine, but it does not run.

```
> jasmine "**/test/**/test*.js"

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'watch'
Require stack:
- xxx\node_modules\@cnakazawa\watch\test\test_monitorRootDirectory.js
- xxx\node_modules\jasmine\lib\jasmine.js
- xxx\node_modules\jasmine\bin\jasmine.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1040:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (xxx\node_modules\←[4m@cnakazawa←[24m\watch\test\test_monitorRootDirectory.js:3:18)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1151:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1040:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'xxx\\node_modules\\@cnakazawa\\watch\\test\\test_monitorRootDirectory.js'←[39m,
    ←[32m'xxx\\node_modules\\jasmine\\lib\\jasmine.js'←[39m,
    ←[32m'xxx\\node_modules\\jasmine\\bin\\jasmine.js'←[39m
  ]
}
```

I use node 13 with ESM. Jest does not support it, that's why I decided to try jasmine.

**Comment by sgravrock** [comment]
I haven't been able to reproduce this. Do you have a sample project I could run that demonstrates the problem?

**Comment by inf3rno** [comment]
> 
> 
> I haven't been able to reproduce this. Do you have a sample project I could run that demonstrates the problem?

I can make one and upload. Can it depend on the operating system? It is win7 x64.

**Comment by sgravrock** [comment]
That's probably fine. I have Windows 10 but that's probably close enough. Thanks.

**Comment by inf3rno** [comment]
@sgravrock 
Based on the error message it looks like some lib has the dependency `@cnakazawa/watch` but tries to require `watch`.

**Comment by inf3rno** [comment]
Or it tries to load `@cnakazawa/watch` but did not install it as dependency. It should be jasmine.js, but I found no such code in the entire project. :S

**Comment by inf3rno** [comment]
sane, exec-sh, minimist install that package

**Comment by inf3rno** [comment]
Nope, it looks like `@cnakazawa\watch` itself contains `require("watch")`.

**Comment by inf3rno** [comment]
https://github.com/mikeal/watch/blob/master/test/test_monitorRootDirectory.js#L3

**Comment by inf3rno** [comment]
Looks like this cnakazawa guy forked the watch lib from the mikeal repo, published it as 1.0.3 on npm under his name, so npm no longer recognizes that lib as watch, but as "@cnakazawa\watch" and since the lib tries to load itself via npm not via relative path, it throws an error.

**Comment by inf3rno** [comment]
I wrote a letter to the guy. Christoph Nakazawa @cpojer

**Comment by inf3rno** [comment]
I wonder why ppl fork unmaintained projects. I mean in github we don't get separate issues for the fork and it will never be pulled to the original repo.

**Comment by inf3rno** [comment]
Ohh I see now, when I give the `jasmine "**/test/**/test*.js"` param, it matches `xxx\node_modules\@cnakazawa\watch\test\test_monitorRootDirectory.js` too, not just `xxx\test\**\*.js`.

**Comment by cpojer** [comment]
I published 1.0.4 of this package which does not include test files. See https://github.com/cpojer/watch/commit/330f85e813b494b88fe7e0528b6ebfd5c1125459

Your initial command ran tests in node_modules, which is never a good idea – at the same time node_modules shouldn't publish test files. Sorry about that!

**Comment by inf3rno** [comment]
@cpojer Okay, thanks!

**Comment by inf3rno** [comment]
Turned out it works with `./test`.

**Comment by 3anhaha** [comment]
Don’t help him he has put so many license on my Xbox, that’s why it say win 7 he was breaking into my house. Thought he was a friend, he just a thief he can’t rob me of anything so he’s just been invading my privacy. I moved away and he’s been looking for a house to rent by me.. his name is Jamie Joseph Hansen . I’ll show you proof. He has my hole house hooked up to his phone or laptop that he stole from me.  He has had so many people in here help him to try to steal my Xbox account, he has taking all my social media, emails, I’ve been thur at least 7 phones trying to figure out what was going on. He used my driver license to become developer on Apple and he’s been erasing my phone everyday, I’m in a state where I have two family members. He’s been here his whole life. What’s so funny is that he uses my contacts as gamer tags when he’s trying to leave reviews on games. He’s has suckered so many people in GitHub, the best one I need help cloning my phone. That makes no sense, but people so thirty to help he got in my phone and is still in there a year later.. I’ve made police reports.. please don’t not help this guy.
