### ISSUE TITLE
Jasmine error when using jasmine-trx-reporter

### ISSUE THREAD

**Issue by mohammedakbarali** [jasmine/jasmine#1789]
## Context
Im using **jasmine-trx-reporter** for generating report with screenshots in trx format. Problem is Jasmine is throwing file not found error when there are multiple suites with multiple specs and if a spec in first suite fails. When generating result for second suite, Jasmine is trying to look for a screenshot file which was created for the failed spec in the first suite. Screenshot attached.

## Expected Behavior
No error and report should generate fine

## Current Behavior
Jasmine error is causing the Spec to fail and result is marked fail even though Spec is passed

## Suite that reproduces the behavior (for bugs)
Create any two suites with multiple specs and fail the first spec purposely.

## Your Environment
* Version used: 3.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome80, Node.js 10.15.3
* Operating System and version (desktop or mobile): Windows10

![Error Screenshot](https://user-images.githubusercontent.com/45233132/75430170-f469b900-5970-11ea-9a26-9974451b3954.PNG)

**Comment by sgravrock** [comment]
It looks like the error is coming from jasmine-trx-reporter, not Jasmine. (Jasmine itself doesn't have anything to do with screenshots.) I suggest opening an issue with the folks who maintain jasmine-trx-reporter.
