### ISSUE TITLE
Feature request: Add a matcher which tests if a Promise is pending

### ISSUE THREAD

**Issue by DCtheTall** [jasmine/jasmine#1803]
## Expected Behavior

There should be a matcher for when a Promise is pending, e.g.

```javascript
let resolve;
const promise = new Promise((fn) => {
  resolve = fn;
});
await expectAsync(promise).toBePending();
resolve();
await expectAsync(promise).not.toBePending();
```

## Current Behavior

There is no matcher that does this.

## Possible Solution

I would be happy to supply a PR that uses Promise.race() to detect a pending promise, toy example below:

```javascript
function toBePending() {
  return {
    compare(actual) {
      // Type check it is a promise...
      const want = {};
      return Promise.race([actual, Promise.resolve(want)]).then(
        function (got) { return {pass: got === want}; }
      );
    },
  };
}
```

Since Promise.race() is not defined in IE or ES5, we could monkey patch something based on Bluebird's implementation into this matcher if you'd like.

## Suite that reproduces the behavior (for bugs)

See above example.

## Context

I use Jasmine at work and we have to implement this ourselves using assertions, which is not the "Jasmine way" imo.

## Your Environment

* Version used: 3.5.0 (I think)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 80
* Operating System and version (desktop or mobile): Desktop
* Link to your project: N/A

**Comment by sgravrock** [comment]
That seems reasonable. I wouldn't monkey-patch `Promise.race` though. Partly because of the risk of affecting the behavior of user code, and partly because it shouldn't be necessary. I'm pretty sure that we don't support any platforms that have promises but not `Promise.race`.
