### ISSUE TITLE
Jasmine doesn't evaluate expectations inside observable subscribe method

### ISSUE THREAD

**Issue by arquadrado** [jasmine/jasmine#1804]
## Summary
I am using jasmine to test my angular 8 app and I am having trouble to test a method that returns an observable chain that is composed of two service methods that return observables. 

## Expected Behavior
I would like to be able to subscribe the method being tested and expect that both services were called. I have tried multiple approaches and nothing has worked so far.

## Current Behavior
The test runs and finishes ignoring all the expectations

## Suite that reproduces the behavior (for bugs)

```javascript
describe("AppComponent", () => {
  let fixture;
  let component;

  beforeEach(async(() => {
    const patoSpy = jasmine.createSpyObj("serviceA", {
      doSomething: of()
    });

    const ursoSpy = jasmine.createSpyObj("serviceB", {
      doSomethingElse: of()
    });

    TestBed.configureTestingModule({
      imports: [FormsModule],
      declarations: [AppComponent],
      providers: [
        { provide: UrsoService, useValue: ursoSpy },
        { provide: PatoService, useValue: patoSpy }
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });


  // test passes since all expectations are ignored
  fit("should call both services", () => {
    component.methodToTest().subscribe(() => {
      expect(component.serviceA.doSomething).toHaveBeenCalledTimes(1);
      expect(component.serviceB.doSomethingElse).toHaveBeenCalledTimes(1);
      expect(true).toBeFalsy();
    });
  });
  
// test fails since done is never called and timeout exception is thrown
  fit("should call both services", (done) => {
    component.methodToTest().subscribe(() => {
      expect(component.serviceA.doSomething).toHaveBeenCalledTimes(1);
      expect(component.serviceB.doSomethingElse).toHaveBeenCalledTimes(1);
      expect(true).toBeFalsy();
      done();
    });
  });


  // I saw this approach somewhere in the web as the way to do it in 2.8+ version but
  // test fails since it seems that the promise is resolved before the completion
  // of the observable and the second expectation fails
  fit("should call both services", async () => {
    await component.methodToTest().toPromise();
    expect(component.serviceA.doSomething).toHaveBeenCalledTimes(1);
    expect(component.serviceB.doSomethingElse).toHaveBeenCalledTimes(1);
  });
});
```

`app.component.ts` method:

```javascript
public methodToTest(): Observable<string> {
    return this.serviceA.doSomething().pipe(
      mergeMap(() => {
        return this.serviceB.doSomethingElse();
      })
    );
  }
```
## Context
I have a method that calls a service to save a document and then calls another service to log the action. I want to make sure that whenever I call this method the service to save document is called as well as the service to log.

## Your Environment

* Version used: Jasmine 3.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 80, node 12.8.1
* Operating System and version (desktop or mobile): Ubuntu 18.04.4 LTS

**Comment by sgravrock** [comment]
The fact that the second test (the one that uses a `done` callback) times out strongly suggests that the subscriptions never actually fire. There's a lot going on here, but I think the root of the problem is that both of the mock service methods return observables that never emit any values:

```
    const patoSpy = jasmine.createSpyObj("serviceA", {
      doSomething: of()
    });

    const ursoSpy = jasmine.createSpyObj("serviceB", {
      doSomethingElse: of()
    });
```

Instead of `of()`, try something like `of('some value that makes sense for your application')`. I suspect that all of the tests will then start behaving in ways that make more sense.

The first of the three tests that you showed is a synchronous test. As you've discovered, synchronous tests for callback-based code can be unreliable. If the callback containing the assertions is never called or is called after the test finishes, the test will incorrectly pass. For that reason I recommend going with either the second or third version.

**Comment by sgravrock** [comment]
I'm going to go ahead and close this since it doesn't appear to be a bug in Jasmine and we haven't heard anything new in some time. Feel free to open a new issue with more information if you still think there's a problem with Jasmine here.

**Comment by Jonathan-Ironman** [comment]
I managed to solve it like this

```
// Method
getUnit(unitId: Unit['id']): Observable<Unit> {
  const localUnit = LocalStorageService.getUnit(unitId);

  if (localUnit) {
    return of(localUnit);
  }

  return this.databaseService
    .getUnit(unitId)
    .pipe(tap((unit) => LocalStorageService.cacheUnit(unit)));
}

// Test
it('should cache a unit locally when retrieving it from the DB', () => {
  spyOn(MockDatabaseService.prototype, 'getUnit').and.callThrough();
  spyOn(LocalStorageService, 'cacheUnit');

  const unitObs = structureService.getUnit('x');

  expect(MockDatabaseService.prototype.getUnit).toHaveBeenCalledTimes(1);
  unitObs.subscribe(() => {
    expect(LocalStorageService.cacheUnit).toHaveBeenCalledTimes(1); // Correctly evaluated
  });
});
```
