### ISSUE TITLE
Error: Type 'AsymmetricMatcher<any>' is not assignable to type 'string'.ts(2322)

### ISSUE THREAD

**Issue by jethas-bennettjones** [jasmine/jasmine#1805]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Expected Behavior
`expect.toHaveBeenCalledWith` method produces a no linting errors when using the `jasmine.any` matchers.

## Current Behavior
`expect.toHaveBeenCalledWith` method produces a linting error when using the `jasmine.any` matchers.

## Suite that reproduces the behavior (for bugs)

```javascript
class MyClass {
  myMethod(inputVariable: InputVariable) {
    return true;
  }
}

interface InputVariable {
  tester: string
}

describe('linting eror', () => {
  it('should pass the linter without issue', () => {
    var myClassMock = jasmine.createSpyObj<MyClass>('MyClass',['myMethod']);
    var inputVariable = {tester: 'test'};
    myClassMock.myMethod(inputVariable);
    expect(myClassMock.myMethod).toHaveBeenCalledWith({
      tester: jasmine.any(String)
    })
  })
});
```
## Context
Running this in VS Code should produce the expected error.

## Your Environment
VS Code: 1.43.2
TypeScript: 3.8.3
OS: Windows 10 (18363.720)
Node: v13.11.0

**Comment by sgravrock** [comment]
The TypeScript type definitions for Jasmine are part of the [DefinitelyTyped project](https://github.com/definitelytyped/definitelytyped). Please open an issue (or better yet, submit a PR) there if updating to the latest version doesn't fix the problem. Thanks.
