### ISSUE TITLE
Test in error although result and expectation are equals

### ISSUE THREAD

**Issue by Lempkin** [jasmine/jasmine#1809]
## Expected Behavior
Test should be ok or error should show some differences between expectation and result

## Current Behavior
Test gives an error although result and expectation are exactly the same

## Possible Solution
?

## Suite that reproduces the behavior (for bugs)
Here my tests :
```j
describe('InterventionService', () => {

const fakeHttpClient = jasmine.createSpyObj('HttpClient', ['get']);
fakeHttpClient.get.and.returnValue(of({}));

it('should call WS with queryParams', () => {
    const queryParams: Params = {
      'page': '1',
      'pageSize': '100',
      'sortOrder': -1,
      'sortProperty': 'type',
      'interventionRef': 'test'
    };
    service.findAllPaginatedAndSorted(queryParams);
    let expectedParams = new HttpParams();
    expectedParams = expectedParams.append('page', '1');
    expectedParams = expectedParams.append('pageSize', '100');
    expectedParams = expectedParams.append('sortOrder', '-1');
    expectedParams = expectedParams.append('sortProperty', 'type');
    expectedParams = expectedParams.append('InterventionRef', 'test');

    expect(fakeHttpClient.get).toHaveBeenCalledWith(
      'testURL/api/intervention',
      { observe: 'response', params: expectedParams });
  });
```

I get this error : 

>  Error: Expected spy HttpClient.get to have been called with [ 'testURL/api/intervention', Object({ observe: 'response', params: page=1&pageSize=100&sortOrder=-1&sortProperty=type&InterventionRef=test }) ] but actual calls were [ 'testURL/api/intervention', Object({ observe: 'response', params: page=1&pageSize=100&sortOrder=-1&sortProperty=type&InterventionRef=test }) ].

## Your Environment
* Version used:
jasmine-core 3.4.0
angular 8.1.3

**Comment by sgravrock** [comment]
It's hard to tell exactly what's wrong from what's here (in particular, the definitions of `service.findAllPaginatedAndSorted` and `HttpParams` might be important). But in general, this sort of thing happens when an object has a `toString` method that doesn't include all the object's properties, so that two objects that aren't actually equal return the same value from `toString`.

I suggest upgrading jasmine-core. Beginning with 3.5.0, the `toHaveBeenCalledWith` failure message contains more detail that might help you track down the root of the problem.

**Comment by chrisdeely** [comment]
I believe `toHaveBeenCalledWith` is using a strict equality test, and the objects being compared and not literally the same object, they just have similar properties. I would recommend wrapping the expected result object in the jasmine `objectContaining()` utility which will look for equal properties between the expected and actual objects. 

```
expect(fakeHttpClient.get).toHaveBeenCalledWith(
      'testURL/api/intervention',
    jasmine.objectContaining(  { observe: 'response', params: expectedParams }));
  });
```

**Comment by slackersoft** [comment]
The `toHaveBeenCalledWith` matcher uses Jasmines deep equality functionality to compare arguments. One of the things that is compared, in addition to all of the properties, is the constructor used to create the object. Based on the output, it doesn't look like that's what is causing your issue (this is why Jasmine prints out the constructor for pretty-print).

I think the place to look might be in `HttpParams`. I'd start by looking into a `toString()` function and see if there are properties on the object that aren't represented in that function.

**Comment by sgravrock** [comment]
I'm going to close this issue due to prolonged inactivity. Feel free to open a new issue with more information (particularly an updated failure message) if you're still having problems and the tips in this thread didn't help.
