### ISSUE TITLE
are there typescript types for jasmine-core?

### ISSUE THREAD

**Issue by wolverineks** [jasmine/jasmine#1810]
im trying to use jasmine-core in react-native (not node)

ive gotten jasmine-core to work pretty much.
ive hacked up some of the types from [definitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasmine) but they dont seem to line up all that well

so, are there types specifically for jasmine-core? 
if not, i could use some pointers on how jasmine types might line up with jasmine-core

thanks

**Comment by elliot-nelson** [comment]
Hi there, the latest @types/jasmine should be completely up-to-date with jasmine v3.5.

When you say they don't "line up well", are there specific methods that are causing unexpected typescript errors?  (The typings for jasmine aren't maintained by the jasmine team, but I might be able to help you troubleshoot.)

**Comment by wolverineks** [comment]
i figured you didnt maintain them, but i wasnt sure how to contact whoever does...
i have no doubt that that `@types/jasmine` line up with `jasmine v3.5`, but i'm using `jasmine-core` directly, which mean no automatic types

essentially, 
```typescript
import jasmineModule from 'jasmine-core/lib/jasmine-core/jasmine';

const jasmineCore = jasmineModule.core(jasmineModule)
const jasmineEnv = jasmineCore.getEnv()
const jasmineInterface = jasmineModule.interface(jasmineCore, jasmineEnv)
```

when i import this
```typescript
import jasmineModule from 'jasmine-core/lib/jasmine-core/jasmine';
```

i get something with an interface of this
```
interface jasmineModule {
  Any: Function;
  Anything: Function;
  ArrayContaining: Function;
  ArrayWithExactContents: Function;
  base: Function;
  buildExpectationResult: Function;
  CallTracker: Function;
  clearStack: Function;
  Clock: Function;
  core: Function;
  DelayedFunctionScheduler: Function;
  DiffBuilder: Function;
  Empty: Function;
  Env: Function;
  errors: Function;
  ExceptionFormatter: Function;
  Expectation: Function;
  ExpectationFilterChain: Function;
  Expector: Function;
  Falsy: Function;
  formatErrorMsg: Function;
  GlobalErrors: Function;
  interface: Function;
  JsApiReporter: Function;
  MapContaining: Function;
  matchersUtil: Function;
  MockDate: Function;
  noopTimer: Function;
  NotEmpty: Function;
  nothing: Function;
  NullDiffBuilder: Function;
  ObjectContaining: Function;
  ObjectPath: Function;
  Order: Function;
  pp: Function;
  QueueRunner: Function;
  ReportDispatcher: Function;
  requireAsyncMatchers: Function;
  requireMatchers: Function;
  SetContaining: Function;
  Spec: Function;
  Spy: Function;
  SpyFactory: Function;
  SpyRegistry: Function;
  SpyStrategy: Function;
  StackTrace: Function;
  StringMatching: Function;
  Suite: Function;
  Timer: Function;
  toBe: Function;
  toBeCloseTo: Function;
  toBeDefined: Function;
  toBeFalse: Function;
  toBeFalsy: Function;
  toBeGreaterThan: Function;
  toBeGreaterThanOrEqual: Function;
  toBeInstanceOf: Function;
  toBeLessThan: Function;
  toBeLessThanOrEqual: Function;
  toBeNaN: Function;
  toBeNegativeInfinity: Function;
  toBeNull: Function;
  toBePositiveInfinity: Function;
  toBeRejected: Function;
  toBeRejectedWith: Function;
  toBeRejectedWithError: Function;
  toBeResolved: Function;
  toBeResolvedTo: Function;
  toBeTrue: Function;
  toBeTruthy: Function;
  toBeUndefined: Function;
  toContain: Function;
  toEqual: Function;
  toHaveBeenCalled: Function;
  toHaveBeenCalledBefore: Function;
  toHaveBeenCalledTimes: Function;
  toHaveBeenCalledWith: Function;
  toHaveClass: Function;
  toMatch: Function;
  toThrow: Function;
  toThrowError: Function;
  toThrowMatching: Function;
  TreeProcessor: Function;
  Truthy: Function;
  UserContext: Function;
  util: Function;
  version: Function;
}
```

i dont see any types that line up with this interface
is this a combination of interfaces?
even then i dont see anything in the types for UserContext, or ExceptionFormatter, among others

**Comment by elliot-nelson** [comment]
Hmm... yes, you are importing the internal implementation directly, so there wouldn't be types for any of that stuff - and I doubt there ever will be, as it's not really a supported use case.

I'm not sure what your best bet would be here.  If you import @types/jasmine you might be able to take your custom-made interface and just cast it to the right interface in @types, getting the rest of the type tree for free.  If that doesn't work you might be stuck copying the type definitions into your project and changing the names to match your imports (or `any` 😆 ).

**Comment by wolverineks** [comment]
yah, that was the plan, but im not sure which types to combine to get whatever this thing is
they have properties that i cant find on any of the types

**Comment by selangley-wa** [comment]
Somewhat related to this, I wonder if the Jasmine developers would consider updating the typescript types for Jasmine on a regular basis, i.e., when they release a new version of Jasmine?

[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasmine](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasmine)

Do the Jasmine developers not regularly use Typescript?

Thanks.

**Comment by sgravrock** [comment]
> Somewhat related to this, I wonder if the Jasmine developers would consider updating the typescript types for Jasmine on a regular basis, i.e., when they release a new version of Jasmine?

Do we consider updating the TypeScript types? Yes. Do we have time to get to it before someone else does? Not so far, and it’s not looking good for 3.6 either. It’s on my to-do list but it isn’t at the top.

Please keep in mind that Jasmine is run on a volunteer basis. That means that there’s a small and largely fixed amount of maintainer time available. Taking on new work like updating the TypeScript types at release time means doing less of something else like responding to issues and PRs, updating documentation, fixing CI/infrastructure bit rot, core architectural work, adding features that we’re personally interested in, etc. Either that or it means taking more time from our lives outside the computer.

So the question isn’t really “do we want to do this additional thing”. It’s “is there something we should stop doing to make room for the extra work”. So far the answer to that question has been no. The thing about TypeScript support is that a lot of people are willing and able to contribute to it. (And I’m very grateful for that.) That makes it a relatively poor use of maintainer time compared to work that others either can’t or won’t do.

I recognize that the current situation isn’t ideal, and I’m open to suggestions for making it better. So far everything I’ve come up with makes maintainers more of a bottleneck than we already are, makes it harder to contribute to Jasmine, or both.

**Comment by coyoteecd** [comment]
@selangley-wa For what is worth, I agree with @sgravrock above that given limited maintainer time, they should let others update the types. I submitted PRs to DefinitelyTyped and they typically go through in less than a week.

**Comment by sgravrock** [comment]
I just took another look at the OP's first follow-up and noticed something that I'd missed the first time around: Most of the things they were expecting to see in the type definitions were actually not part of the [public API ](https://jasmine.github.io/api/edge/global). That, plus the fact that the types for `jasmine` and `jasmine-core` are both in `@types/jasmine`, could explain a lot of the problem.

For what it's worth, this  compiles using jasmine-core 3.9.0, typescript 4.4.2, and @types/jasmine 3.9.0:

```
// @ts-ignore
import jasmineModule from 'jasmine-core';

const jasmineCore = jasmineModule.core(jasmineModule)
const jasmineEnv: jasmine.Env = jasmineCore.getEnv();

describe('a suite', function() {
	it('a spec', function() {
		expect(['foo', 'bar']).toEqual(jasmine.arrayContaining('foo'));
	});
});
```

Type-checking works: If I change the argument to `arrayContaining` to something other than a string, it doesn't compile. Note that some IDEs, notably VS Code, might need an extra `import {} from 'jasmine';` before autocomplete and other IDE hints work. That works even if only jasmine-core is installed and doesn't affect code generation.
