### ISSUE TITLE
Tests in Subdirectories Not Run

### ISSUE THREAD

**Issue by jcald1** [jasmine/jasmine#1816]
Using Jasmine 2

Files:
spec/unit/indexSpec.js
spec/unit/fileStorage/fileStorageSpec.js

spec/support/jasmine.js
```
{
  "spec_dir": "spec",
  "spec_files": ["**/*[sS]pec.js"]
}
```

`jasmine ./spec/unit/**/*.js`
runs only the specs in spec/unit/fileStorage/fileStorageSpec.js

`jasmine` tries to run everything including the `node_modules` directory

**Comment by sgravrock** [comment]
Jasmine 2 is quite out of date and hasn't been supported in years. Please upgrade to the latest 3.x.

**Comment by jcald1** [comment]
@sgravrock , updated to version 3.5.0 and still having the same issue.

**Comment by sgravrock** [comment]
I haven't been able to reproduce this. Can you please provide a complete, minimal test suite that demonstrates the problem?

**Comment by sgravrock** [comment]
I'm going to go ahead and close this issue since we haven't heard anything in some time. If you're still having problems, please feel free to open a new issue with more information.
