### ISSUE TITLE
MatchersUtil.prototype.eq_ Spec: Add Test for Different Types

### ISSUE THREAD

**Issue by tobiasschweizer** [jasmine/jasmine#1821]
I was trying to find out about the difference between `toBe` and `toEqual` and understood that for *primitive* types they are interchangeable (https://stackoverflow.com/questions/22413009/jasmine-javascript-testing-tobe-vs-toequal).
In my understanding, with both `toBe` and `toEqual` comparing `1` to `'1'` would make the test fail because the types are different.

In the case of `toBe`, `===` checks for both the value equivalence and the type.
In the case of `toEqual`, a type check is provided:

https://github.com/jasmine/jasmine/blob/8a731e17a7e4d97c73ba8428911c4f6d3a004c23/src/core/matchers/matchersUtil.js#L192-L196

## Expected Behavior

`toBe` and `toEqual` already behave as expected for primitive types. I just did not find an explicit test for `toEqual` involving different types for a numeric value (Number and String).

## Possible Solution

I found the following tests for `Number`:

https://github.com/jasmine/jasmine/blob/8a731e17a7e4d97c73ba8428911c4f6d3a004c23/spec/core/matchers/matchersUtilSpec.js#L102-L110

I suggest to add an additional `it` like the following:

```javascript
it("fails for a Number and a String that have equivalent values", function() {
      var matchersUtil = new jasmineUnderTest.MatchersUtil();
      expect(matchersUtil.equals(123, "123")).toBe(false);
    });
```

## Context

`toBe` clearly behaves like `===` which made me think if `toEqual` behaves like `==`.

**Comment by tobiasschweizer** [comment]
If you agree, I could submit a PR adding the suggested `it`.

**Comment by sgravrock** [comment]
I'd be happy to see a PR that adds more tests to cover cases that we're currently missing. Thanks.

**Comment by tobiasschweizer** [comment]
@sgravrock Ok, will do! I will fork this repo and send you a PR.

Just out of curiosity: When you test your test framework, how or to which degree can you apply your test framework's own methods to do that?

In the example above, the additional test for `equals` uses `toBe`. Wouldn't it be more robust to use `===` instead?

I understand that this is a bit like writing a compiler. At some point, you use your own programming language to write the compiler.

**Comment by tobiasschweizer** [comment]
I have submitted https://github.com/jasmine/jasmine/pull/1829.
