### ISSUE TITLE
404 on website https://jasmine.github.io

### ISSUE THREAD

**Issue by trusktr** [jasmine/jasmine#1830]
Not sure if it is GitHub's fault or not, but I get 404 on the Jasmine website.

Also https://twitter.com/EricLiprandi/status/1276657954310066176

**Comment by guyroyse** [comment]
This is probably because the default branch was changed from master to main. GitHub Pages (as of yesterday at least) will only look at master. I tried the same change on part of my personal website and broke it in the same way.

**Comment by sgravrock** [comment]
Fixed by changing the default branch back to master. Thanks for the heads up.
