### ISSUE TITLE
Device - touch event specific testcases are failed

### ISSUE THREAD

**Issue by pandiyarajm93** [jasmine/jasmine#1832]
## Are you creating an issue in the correct repository? Yes

Device touch event-specific test cases are getting failed in touch supported laptops

## Expected Behavior

While trigger a mouseup event programmatically it should trigger touchend handler

## Current Behavior

Currently, When trigger a mouseup event programmatically it not trigger a touched handler

## Possible Solution

Need  to detect touch screen support in the current test environment.

In before it works properly in my application. (Last two years)

## Suite that reproduces the behavior (for bugs)

- Bind touchend event to element

- Trigger mouseup event programmatically using dispatchEvent

- Now check handler never invoke without dispatchEvent without touchend event

## Context

- Getting testcase failure in my local machine not in remote Jenkins automation

## Your Environment

* Version used: jasmine@2.8.0

* Environment name and version  Chrome 83, node.js 8.15.0):

* Operating System and version (desktop or mobile): windows 10

**Comment by sgravrock** [comment]
Jasmine doesn't provide any way to trigger events. My guess is that you're probably using some other library to trigger events. Your best bet might be to ask for help through whatever support channels are offered for that library.

**Comment by pandiyarajm93** [comment]
Thanks for your guidelines and update.
