### ISSUE TITLE
Spy.withArgs ignores custom equality testers

### ISSUE THREAD

**Issue by linnando** [jasmine/jasmine#1836]
## Expected Behavior

If a custom equality matcher is defined and a different but equal argument is passed to a spy, this should be considered as a call matching the configured spy strategy.

## Current Behavior

If a different but equal argument is passed to a spy, the test fails with "Error: Spy 'spy' received a call with arguments [ ... ] but all configured strategies specify other arguments".

On the other hand, toHaveBeenCalledWith() respects the custom equality testers.

## Suite that reproduces the behavior (for bugs)

```typescript
describe("providing different but equal arguments", () => {
  it('works with withArgs', () => {
    jasmine.addCustomEqualityTester((a, b) => true);
    const spy = jasmine.createSpy('spy');
    spy.withArgs(5).and.returnValue(1);

    const value = spy(2 * 2);

    expect(value).toEqual(1);
  });

  it('works with toHaveBeenCalledWith', () => {
    jasmine.addCustomEqualityTester((a, b) => true);
    const spy = jasmine.createSpy('spy');
    spy.and.returnValue(1);

    const value = spy(2 * 2);

    expect(value).toEqual(1);
    expect(spy).toHaveBeenCalledWith(5);
  });
});
```
Currently, the second test passes, but the first one fails.

## Context

We use protocol buffers (https://developers.google.com/protocol-buffers/) to keep and pass complex sets of data. Protocol buffers are complex objects, whose internal state may sometimes differ even if the data are the same. Therefore, in tests, we rely on custom equality testers, which compare the actual data in protocol buffers and not their internal states.

Since protocol buffers are also used as arguments of mocked methods, it is important to check that these methods are called with appropriate arguments. I generally prefer configuring a spy strategy for particular arguments (using withArgs) over checking the actual arguments in expectations (using toHaveBeenCalledWith). The former method allows defining a spy as a black box (with input and output defined in one statement) and not intermix expectations about the output of the actual method under test with expectations about how this method uses the mock. Therefore, even though withArgs and toHaveBeenCalledWith are to some extent interchangeable, it would be nice if their behaviour with respect to custom equality testers were the same.

## Your Environment
* Version used: 3.5.0
* Environment name and version: Chrome 83
* Operating System and version: Linux

**Comment by slackersoft** [comment]
This sounds like a nice addition to Jasmine. I'm not quite sure what the lift will be to get the equality testers to where they need to be. I think some of the work that @sgravrock put in for 3.6 might either make this easier or have just gotten it working already.

I'd be happy to review a pull request to add this functionality if it isn't working as of 3.6.

**Comment by sgravrock** [comment]
I don't think it'll work in 3.6, but it shouldn't be too hard to fix. Currently, all spies and related objects share a single `MatchersUtil` that doesn't have any custom object formatters or other spec-specific state. The fix would be to give spies (and more specifically `SpyStrategyDispatcher`) access to a `MatchersUtil` that's created for the current spec, sort of like how expectations work. See e.g. uses of `makeMatchersUtil` in [Env.js](https://github.com/jasmine/jasmine/blob/main/src/core/Env.js).
