### ISSUE TITLE
Spy object properties are created as not enumerable

### ISSUE THREAD

**Issue by linnando** [jasmine/jasmine#1837]
## Expected Behavior

If a spy object is copied, the copy is expected to behave the same as the original object. In particular, the properties defined on the object should exist on its copy as well.

## Current Behavior

The properties of a spy object are created as not enumerable (as default in JS). As a result, a copy of a spy miss these properties.

## Possible Solution

It seems that the descriptor created at https://github.com/jasmine/jasmine/blob/6f3e85f755554c4b52b2449a6d2d66bb1327ac4e/src/core/SpyFactory.js#L40 should contain also "enumerable: true".

## Suite that reproduces the behavior (for bugs)

```typescript
describe('spy object property', () => {
  it('exists on the object itself', () => {
    const spy = jasmine.createSpyObj('spy', [], {property: 1});

    expect(spy.property).toEqual(1);
  });

  it('exists on the object\'s copy', () => {
    const spy = jasmine.createSpyObj('spy', [], {property: 1});
    const spyCopy = Object.assign({}, spy);

    expect(spyCopy.property).toEqual(1);
  });
});
```

Currently, only the first test passes.

## Context

Of course, normally, spy objects are used directly and not copied. However, I encountered this issue when injected mocked objects in Angular components. It seems that Angular DI uses a copy of the provided value instead of the object itself (I do not know exactly why and where this copying is performed).

## Your Environment
* Version used: 3.5.0
* Environment name and version: Chrome 83
* Operating System and version: Linux

**Comment by slackersoft** [comment]
This sounds reasonable. I can't think of a situation where someone might be depending on the property spies _not_ be `enumerable`, so it seems like a fairly safe thing to change.

We'd be happy to review a pull request to change this functionality.

**Comment by DCtheTall** [comment]
@slackersoft I'd be happy to write a PR for this if the issue is still available!
