### ISSUE TITLE
Test function body in a reporter

### ISSUE THREAD

**Issue by iliakan** [jasmine/jasmine#1842]
In Mocha, another test framework, reporters get the test body - function code.

That's the part of the result. As the spec is created, `fn.toString()` is also stored in it, and then passed to the reporter.

It's very handy - to get the test code in the report. So that if something goes wrong, HTML reporter shows the failed test code on click.

Can Jasmine be tuned to do the same, without much hacking?

**Comment by iliakan** [comment]
P.S. This is what I've done (approximately), is it ok? 
```js
let Spec = jasmineRequire.Spec;
jasmineRequire.Spec = function(j$) {
  let SpecOriginal = Spec(j$);
  return class Spec extends SpecOriginal {
    constructor(attrs) {
      super(attrs);
      this.result.body = (attrs.queueableFn && attrs.queueableFn.fn || '').toString(); 
    }
  }
}
```

**Comment by slackersoft** [comment]
This is an interesting concept. I'm not sure I understand the circumstances in which it would be useful for debugging a test failure though. I'm especially thinking of situations around transpilers (e.g. TypeScript, babel, etc.) and what output would be useful here.

If the original spec is written in TypeScript, Jasmine won't have any way to get the "real" source of the function, just what the compiler output as base JavaScript. I'm not sure how useful that would be; unless of course that is the actual goal here, to be able to see what the code actually running looks like.

If this is added to Jasmine, we would also need to figure out whether (and how) that content would be exposed in the current reporters (both HTML and console), or if we just want to expose the functionality to 3rd party reporters.

**Comment by iliakan** [comment]
If a test fails, HTML reporter becomes able to show the test code. 

Reporters in another framework, Mocha, have access to function body, so I just ported the functionality to Jasmine, with the code above.

**Comment by sgravrock** [comment]
I see a few significant challenges here:

* As mentioned above, the popularity of transpiled languages like TypeScript limit the usefulness of this feature. Unless we got Jasmine into the business of controlling transpiliation of user code (something I'm emphatically not open to), it would be quite difficult to show the actual source code to transpiler users.
* Performance could be a concern. I'd not want this feature to slow down Jasmine for people who don't want it.
* There is the question of how the reporter should display large function bodies. Show the whole thing? Just show a section around where the first assertion failure occurred?

None of that is insurmountable, but it all suggests to me that this feature would likely be expensive to implement and need a fair bit of care and feeding after it's shipped. Given that it's gone over four years with no expression of interest from anyone but the original requester, I don't think it's worthwhile.
