### ISSUE TITLE
Testing unhandled exception handling in jasmine@v3.6.0

### ISSUE THREAD

**Issue by rankida** [jasmine/jasmine#1843]
Firstly, thank you for this great project and all the efforts that has gone into it.

## Behavior
We have a suit of tests that test our error handling component. Specifically it tests that on an unhandled rejection and unhandled exception the info is caught and sent to the server.
In jasmine@v3.5.0 this passes. In jasmine@v3.6.0 it fails due to the new feature _Route unhandled promise rejections to onerror_ from https://github.com/jasmine/jasmine/pull/1778.

## Possible Solution

Ideally there would be a way to tell jasmine that this test will be testing such handling and not fail.

I admit I hacked around the code for a while and was unable to come up with a great solution, but I am happy to try again if you could provide direction.

## Example
The specifics are probably not important, as it works in jamsine@3.5.0 and the PR is clear https://github.com/jasmine/jasmine/pull/1778. But in case they are then:

**`error-log.jsx`**
Component under test
```jsx
  onUnhandledRejectionWindow(e) {

    const error = errorize(e.reason);
    console.error('UNHANDLED REJECTION', error);

    this.onError({ error, message: error.message }, true);

    return false;
  }

  componentDidMount() {
    window.addEventListener('error', bind(this, 'onError'));
    window.onunhandledrejection = bind(this, 'onUnhandledRejectionWindow'); // addEventListener is not supported when core-js Promise shim is used
  }

 // handlers removed in later part of code
```

**`error-log.test.jsx`**
The test which now fails
```js
  it('logs unhandled promise rejections', (done) => {

    spyOn(console, 'error');
    const spy = jasmine.createSpy('log');
    TestUtils.renderIntoDocument(<ErrorLog logError={spy} />);

    const error = new Error('I am unhandled');
    Promise.reject(error);

    setTimeout(() => {

      expect(spy).toHaveBeenCalledWith(jasmine.objectContaining({
        message: 'I am unhandled',
        unhandledRejection: true
      }));

      expect(console.error).toHaveBeenCalledWith('UNHANDLED REJECTION', error); // eslint-disable-line no-console

      done();
    });
  });
```

It is worth pointing out that the components handlers are still executed but jasmine's new handler is also called and that fails the test.

## Your Environment
* Version used: v3.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 84.0.4147.105 (Official Build) (64-bit), Node v12.14.0, karma@5.1.1 
* Operating System and version (desktop or mobile): MacOS Catalina

**Comment by sgravrock** [comment]
> I admit I hacked around the code for a while and was unable to come up with a great solution, but I am happy to try again if you could provide direction.

That's about where I am. I haven't yet come up with an approach that has a good API and doesn't run into weird interleaving issues with Jasmine's existing error handling code. But we have had a few requests for this sort of thing as well as issues that it would help with (e.g. #1453) and I can see how 3.6.0 amplifies the need. So I'm hoping to take another look soon.

I think we'd ideally want something with all these characteristics:
* Prevents Jasmine's default error handler from failing the spec
* Encourages or at least allows spec authors to assert that exactly the expected set of errors happened
* Reliably puts the default error handler back, no matter how the spec terminates
* Works for both sync and async specs (albeit, the latter might need a separate API)

Although I'm hoping to find time to work on this soonish, that shouldn't discourage anyone else from trying. I'd be happy to review a pull request that solves the problem.

**Comment by sgravrock** [comment]
I just merged #1860 which, as a stopgap, allows you to bypass Jasmine's global error handling by setting the global `onerror` handler. That might help with your situation. Be sure to put Jasmine's `onerror` handler back at the end of any spec that overwrites it.

**Comment by top-master** [comment]
@sgravrock Good temporary workaround.

But it would be nice automatically set `onError` back to default, I mean, each time `describe(...)` returns.

**Comment by sgravrock** [comment]
> But it would be nice to automatically set onError back to default, I mean, each time describe(...) returns.
> 
> Once that's done, it's a permanent solution (not just workaround).

That would stop Jasmine from reporting unhandled exceptions in async specs. I'm not willing to do that. We need something more like the solution I outlined in my comment above because Jasmine has no way of distinguishing between an expected unhandled exception that should be ignored and an unexpected unhandled exception that should be treated as a failure.

**Comment by top-master** [comment]
Sorry, I thought `describe(...)` waits for async things, or at least
terminates them, before allowing next `describe(...)` to run.

But if they run Parallel, it makes sense (else I don't know what you mean).
