### ISSUE TITLE
What is the best way to mock a File object? (with custom content)

### ISSUE THREAD

**Issue by AdrianRamzes** [jasmine/jasmine#1844]
I have a simple angular app that allows user to choose, open and view CSV file locally - before uploading it to the server.
I have a class `Parser` with single method  
`parse(file: File): MyObject[]`.

How can I mock File object with my own content?

*xxxParser.spec.ts:*
```typescript
describe("ING Luxembourg CSV parser", () => {

    let parser: xxxParser;
    let csvFile: File;

    beforeAll(() => {
        let content = require("../../../assets/test-data/test-data.js");
        csvFile = new File([content], 'export_123', { type: 'text/csv' });
    })

    beforeEach(() => {
        parser = new xxxParser();
    })

    it(..., (done) => {});

});
``` 

*test-data.js:*
```javascript
module.exports = 

`col1,col2
val1,val2

`;
```

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
