### ISSUE TITLE
Async matchers should fail with a meaningful error message, not a timeout, when the promise is pending.

### ISSUE THREAD

**Issue by sgravrock** [jasmine/jasmine#1845]
The following spec fails with a timeout but should fail with a message that explains that a promise was expected to be resolved:

```
  it('should fail with something other than a timeout', function() {
    var p = new Promise(function() {});
    return expectAsync(p).toBeResolved();
  });
```

Most of the async matchers have this problem, with the notable exception of `toBePending`.

**Comment by aashigupta19** [comment]
Heyy, I would like to work on this issue. May you please assign me this?
Also, can you please give me the initial details and how to start it off? @sgravrock @cfya

**Comment by sgravrock** [comment]
Thank you! I think a good starting point would be to look at the implementation of the `toBePending` matcher in [src/core/matchers/async/toBePending.js](https://github.com/jasmine/jasmine/blob/main/src/core/matchers/async/toBePending.js). Notice how it uses `Promise.race` to determine whether the promise is still pending. I think a similar approach would work for the other async matchers, except that the logic would be different: fail if the promise is still pending, otherwise follow the existing logic in the matcher. For each of the affected async matchers, we should have a test that verifies that the matcher fails if the promise is pending. The tests for `toBePending`, in [spec/core/matchers/async/toBePendingSpec.js](https://github.com/jasmine/jasmine/blob/main/spec/core/matchers/async/toBePendingSpec.js), might be worth a look.
