### ISSUE TITLE
Can't use js generator functions in callFake

### ISSUE THREAD

**Issue by Sascha1251** [jasmine/jasmine#1848]
I have a use case where I would like to use js generator functions [1] inside the callFake, however, I get the following error:
Error: Argument passed to callFake should be a function, got function*() { return []}

I just used the jasmine example spec with the version 3.6.0 and created a generator function for the callFake (in this case, it could also be a normal function, however, in my case it's not that easy). Please have a look at the following example:
```javascript
it("callFake with generator Function", function() {
        spyOn(player, "play").and.callFake(function*() { return []});
        expect(true).toBeTruthy();
});
```

## Expected Behavior
I would expect that a generator function can be provided to the callFake function.

## Current Behavior
It throws an error:
Error: Argument passed to callFake should be a function, got function*() { return []}

## Possible Solution
I've checked where the issue is coming from and in the jasmine/src/core/SpyStrategy.js we have at line 170 the implementation for the callFake and in line 171 is a check whether the provided value is a function or an async function. Due to the way how it's checked if it's a function/ async function (by using `Object.prototype.toString.apply(value)`), the result is false and an error is thrown. It would be possible to just add generator functions as an additional possibility and everything should be fine.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*

Thank you very much for your work

**Comment by sgravrock** [comment]
Thanks for the suggestion.
