### ISSUE TITLE
Error: toEqual with arrayContaining not working (Jasmine 3.6.1)

### ISSUE THREAD

**Issue by NoZjs** [jasmine/jasmine#1849]
I just updated from version 3.5.0 to 3.6.1 and my tests using "toEqual" with "arrayContaining" are not working anymore.

## Expected Behavior
From the exemple in the documentation, The test should be passing.
https://jasmine.github.io/2.6/introduction#section-Partial_Array_Matching_with_%3Ccode%3Ejasmine.arrayContaining%3C/code%3E
https://jasmine.github.io/tutorials/your_first_suite#section-33

## Current Behavior
I get an error that the result are not equal.
![image](https://user-images.githubusercontent.com/35924027/91597276-0c77c080-e933-11ea-926a-d1f054bd4087.png)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
     fit('test', () => { expect(['a', 'c', 'b']).toEqual(jasmine.arrayContaining(['c', 'b', 'a'])); });
});
```

## Your Environment
* Version used: 3.6.1
* Package.json: 
_(nothing in dependencies)_
"devDependencies": {
      "@babel/cli": "^7.10.5",
      "@babel/core": "^7.11.4",
      "@babel/plugin-transform-runtime": "^7.11.0",
      "@babel/preset-env": "^7.11.0",
      "@babel/runtime-corejs3": "^7.11.2",
      "es6-plato": "^1.2.3",
      "istanbul-instrumenter-loader": "^3.0.1",
      "jasmine": "^3.6.0",
      "jasmine-promises": "^0.4.1",
      "karma": "^5.1.1",
      "karma-chrome-launcher": "^3.1.0",
      "karma-coverage-istanbul-reporter": "^3.0.3",
      "karma-jasmine": "^4.0.1",
      "karma-junit-reporter": "^2.0.1",
      "karma-sourcemap-loader": "^0.3.8",
      "karma-webpack": "^4.0.2",
      "puppeteer": "^5.2.1",
      "regenerator-runtime": "^0.13.7",
      "webpack": "^4.44.1"
   },
* Environment name and version: 
Chrome 84.0.4147.135 (Windows 10)
npm: 6.13.4
node: v12.16.1

**Comment by sgravrock** [comment]
I wasn't able to reproduce the problem. When I create a new, empty Jasmine setup and add the example suite you provided, it passes:

```
$ npm install jasmine
[...]
+ jasmine@3.6.1
[...]
$ ./node_modules/.bin/jasmine init
$ cat - > spec/aSpec.js
describe("sample", function() {
     fit('test', () => { expect(['a', 'c', 'b']).toEqual(jasmine.arrayContaining(['c', 'b', 'a'])); });
});
$ ./node_modules/.bin/jasmine 
Randomized with seed 08182
Started
.


1 spec, 0 failures
Finished in 0.005 seconds
Incomplete: fit() or fdescribe() was found
Randomized with seed 08182 (jasmine --random=true --seed=08182)
```

I'm guessing that there's another piece that's necessary to reproduce this besides Jasmine 3.6 and the suite you provided. Do you have any custom equality testers? If so, they might be a factor. I'd also suggest removing `jasmine-promises`. It was written to monkey patch a version of Jasmine that's now almost five years out of date, and the functionality it adds has been in Jasmine core since 2.7. It might not be the cause of the problem, but removing it shouldn't cost you anything and it's the first thing I'd try to rule out.

**Comment by NoZjs** [comment]
First of all thank you sgravrock for looking into it.

In my project, we added a custom extension for Array to check for "contains" (to be honest, we didn't need it...)

```
(function () {
   Object.defineProperty(Array.prototype, 'contains',
   {
      enumerable: false,
      value: function(item) {
          [...]
      }
   });
})();
```


Jasmine use the constains of matcherUtil inside "ArrayContaining".

```
getJasmineRequireObj().ArrayContaining = function(j$) {
  function ArrayContaining(sample) {
    this.sample = sample;
  }
  ArrayContaining.prototype.asymmetricMatch = function(other, matchersUtil) {
    if (!j$.isArray_(this.sample)) {
      throw new Error('You must provide an array to arrayContaining, not ' + j$.pp(this.sample) + '.');
    }
    // If the actual parameter is not an array, we can fail immediately, since it couldn't
    // possibly be an "array containing" anything. However, we also want an empty sample
    // array to match anything, so we need to double-check we aren't in that case
    if (!j$.isArray_(other) && this.sample.length > 0) {
      return false;
    }
    for (var i = 0; i < this.sample.length; i++) {
      var item = this.sample[i];
      if (!matchersUtil.contains(other, item)) {  ← !!! HERE !!!
        return false;
      }
    }
    return true;
  };
```

What's new in the version 3.6.0 is the new prototype "contains" on the matcherUtil.
```
  MatchersUtil.prototype.contains = function(haystack, needle, customTesters) {
    if (j$.isSet(haystack)) {
      return haystack.has(needle);
    }

    if ((Object.prototype.toString.apply(haystack) === '[object Array]') ||
      (!!haystack && !haystack.indexOf))
    {
      for (var i = 0; i < haystack.length; i++) {
        if (this.equals(haystack[i], needle, customTesters)) {
          return true;
        }
      }
      return false;
    }

    return !!haystack && haystack.indexOf(needle) >= 0;
  };
```

When I was running test, Jasmine called the wrong contains. Resulting in a fail test instead of a success. 

Thank you for your time ! I appreciate

**Comment by sgravrock** [comment]
Thanks for the clarification. While we can't 100% guarantee that Jasmine will behave correctly in the face of changes to the built-in JS objects, we try to prevent that kind of problem. Looks like I missed a spot.
