### ISSUE TITLE
Access to Suite's properties in a specDone callback

### ISSUE THREAD

**Issue by antonsarov** [jasmine/jasmine#1863]
When creating a custom jasmine reporter, the `specDone` callback gives information about the current spec properties (which were previously set with https://jasmine.github.io/api/3.6/Env.html#setSpecProperty

Is there a way to also access (within this callback method) the suite's properties which were set with https://jasmine.github.io/api/edge/Env.html#setSuiteProperty

**Comment by slackersoft** [comment]
Any custom properties for a Suite will be reported in the relevant `suiteDone` callback on a reporter.

**Comment by slackersoft** [comment]
We haven't heard anything on this in a while, so I'm going to close it. If there are still questions feel free to comment here or open a new issue.
