### ISSUE TITLE
Node 15 Support

### ISSUE THREAD

**Issue by BboyAkers** [jasmine/jasmine#1868]
## Expected Behavior
Successfully install **jasmine** via `npm install jasmine` in our developer environment.

## Current Behavior
When doing `npm install jasmine` the error we're getting is 
```
npm WARN EBADENGINE Unsupported engine {​​
npm WARN EBADENGINE package: 'jasmine@3.6.3',
npm WARN EBADENGINE required: {​​ node: '^10 || ^12 || ^14' }​​,
npm WARN EBADENGINE current: {​​ node: 'v15.2.0', npm: '7.0.8' }​​
npm WARN EBADENGINE }​​
```

## Possible Solution
1.) Use `npm outdated` to see outdated versions. 
2.) Update the outdated versions
3.) Test locally via `npm link` in developer using node `15.x.x` environment to test if changes are fixed.

## Context
Upgraded a project environment to node `15.2.0`. Everything else is working but the test suites, we are using jasmine. The error above is happening when doing an npm install.

Not sure what the process is for you all to do upgrades for this package but I'd be happy to pair with someone to make node 15 support possible! 🙂 

## Your Environment
* Version used: 3.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Any environment running node `15.2.0`
* Operating System and version (desktop or mobile): 
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.19042 Build 19042

**Comment by ismaproco** [comment]
My solution until there is a proper release for it is to manually set the jasmine reference in the package.json to a fork with the updated version dependency.

For example I have a fork with the latest master version of the npm package
https://github.com/ismaproco/jasmine-npm

and I did the following commit

https://github.com/ismaproco/jasmine-npm/commit/321f1b1b726abdb4a8425ddd49ab6a176f941a1e

and then on the package.json I just added the reference to my fork.
```
    "jasmine": "git+https://github.com/ismaproco/jasmine-npm.git",
```
![image](https://user-images.githubusercontent.com/180197/101189921-4dabfa80-361d-11eb-8bcc-8e7ea69462b3.png)

**This is obviously a workaround and should not be used in anything closer to production, or ci environmnet.**

**Comment by sgravrock** [comment]
I've removed the `engines` specification in jasmine-npm 3.6.4, so users of odd-numbered Node releases will no longer get warnings or errors.

Supported Node versions are listed at <https://jasmine.github.io/setup/nodejs.html>. Jasmine works with odd-numbered releases like 15, and is highly likely to still work with them in the future. But because they are so short-lived, we can't promise future compatibility.
