### ISSUE TITLE
Issue running single specs

### ISSUE THREAD

**Issue by edge33** [jasmine/jasmine#1873]
## Expected Behavior
running `ng test` it is possibile to re-run single specs from the browser only when debug mode is used eg. `http://localhost:9877/debug.html?` . I expect the same behavior when not in debug mode.

## Current Behavior
all the tests are re-run

## Suite that reproduces the behavior (for bugs)
bootstrap an Angular project with `ng new sample-app`

## Your Environment
```
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular/cli": "~10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.4",
    "prettier": "^2.1.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"

```

please refer also to: [This issue](https://github.com/karma-runner/karma/issues/3581)

**Comment by sgravrock** [comment]
Sorry, but this isn't the right place to ask for help with the Angular toolchain. We're not involved in developing it, and I only use it on a very occasional basis. Your best bet might be to reach out to the karma-jasmine-html-reporter maintainers, if you haven't already done so.
