### ISSUE TITLE
saveArgumentsByValue() saves Date arguments as Object({ })

### ISSUE THREAD

**Issue by coyoteecd** [jasmine/jasmine#1885]
This is a follow-up of #1403. For some reason, that issue only fixes boolean/string/regexp/number primitives and not Date objects, even though it has been mentioned [in the discussion](https://github.com/jasmine/jasmine/issues/1403#issuecomment-319472003).

## Expected Behavior
When using saveArgumentsByValue, I expect that args of type Date are copied by value.

## Current Behavior
Using `expect(spy).toHaveBeenCalledWith(myDate);` fails with expectation error:
Expected $[0] = Object({  }) to equal Date(Tue Feb 16 2021 21:18:40 GMT)

## Possible Solution
We could add a case for Date objects in the `cloneArgs` [implementation](https://github.com/jasmine/jasmine/blob/cd1131354bea551ef11478e313fe66fb11721cf4/src/core/util.js#L64-L69).

I tried the following:
```js
      if (!argsAsArray[i] || str.match(primitives)) {
        clonedArgs.push(argsAsArray[i]);
      } else if (str === '[object Date]') {
        clonedArgs.push(new Date(argsAsArray[i].valueOf()));
      } else {
        clonedArgs.push(j$.util.clone(argsAsArray[i]));
      }
```
and it solves my problem, so if it looks good enough I could submit it as a PR.

## Your Environment
* Version used: 3.6.4
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS v12.14
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by slackersoft** [comment]
We would be happy to review a pull request to ensure dates are cloned correctly.
