### ISSUE TITLE
It seems v3.7.0 presents itself as 3.6.0

### ISSUE THREAD

**Issue by pzygielo** [jasmine/jasmine#1888]
https://github.com/jasmine/jasmine/blob/5c17456925398f89c4f0123b270ba3081d79874c/lib/jasmine-core/jasmine.js#L9472

**Comment by sgravrock** [comment]
Thanks for letting us know. I've released 3.7.1, which reports its version number correctly.

**Comment by pzygielo** [comment]
Thanks for checking and for the new release.
Will jasmine/jasmine-npm follow?

**Comment by sgravrock** [comment]
It shouldn't be necessary. The dependency range on -npm is set up to be compatible with core 3.7.*, so anyone who updates their dependency should automatically get core 3.7.1.

**Comment by pzygielo** [comment]
> It shouldn't be necessary. The dependency range on -npm is set up to be compatible with core 3.7.*, so anyone who updates their dependency should automatically get core 3.7.1.

I always forget to force updates in `mvn` call. 3.7.1 was picked indeed - thank you.
