### ISSUE TITLE
jasmine.util.htmlEscape method missing.

### ISSUE THREAD

**Issue by ipixel4** [jasmine/jasmine#1889]
I have multiple tests that use the htmlEscape method in the util library.
A couple of days ago I noticed that the method is marked as undefined.
Looked around and noticed it's been removed in 3.7.0 but not mentioned in the release notes.

## Expected Behavior
To have the method and not throw undefined exceptions.

## Current Behavior
Missing the method altogether

## Possible Solution
Revert the removal of the method from the util library

Thank you :)

**Comment by sgravrock** [comment]
I'm sorry that the removal of `htmlEscape` impacted you. It was an internal helper function that was never part of Jasmine's [public interface](https://jasmine.github.io/api/3.7/global). We generally don't document all the changes to internals. (If we did, the release notes would essentially be a git diff.)

One of the reasons I removed `htmlEscape` is that it wasn't particularly safe. It did a more limited and specific job than what its name implies, and using it in other contexts could lead to problems. All it did was replace `&`, `<`, and `>` with the corresponding HTML entities. If that's what you really need, it's not too hard to write your own equivalent. But it's safer to set `textContent` on a DOM node instead, and that's the approach I recommend if it works in your context.

**Comment by ipixel4** [comment]
Thank you for the response.
I considered the option of writing it for myself, but due to time constraints, the faster fix was to revert to a lower version.

Will probably just write it in a project's utilities class somewhere.

Keep up the good work.
