### ISSUE TITLE
WIki page for Spidermonkey is outdated

### ISSUE THREAD

**Issue by ajvincent** [jasmine/jasmine#1890]
## Expected Behavior
https://github.com/jasmine/jasmine/wiki/Spider-monkey

## Current Behavior
The steps say as a first step, "downloaded a Env.js".  Sadly, the link goes to a domain which is for sale, and doesn't have anything remotely useful anymore...

That said, maybe https://github.com/bterlson/eshost and its friends is a more flexible option, exposing many more engines.  It's probably well worth some time to investigate.

**Comment by sgravrock** [comment]
Sorry about that. The wiki hasn't been maintained for close to a decade and is only kept around for  historical interest. It looks like we'd added a deprecation notice to the home page, but not to the other pages. I've fixed that.

The current documentation is at https://jasmine.github.io/ but you won't find anything about Spider Monkey there. Unfortunately I don't have any current information about how to use Jasmine with Spider Monkey.

**Comment by ajvincent** [comment]
OK, we can probably close this issue since the wiki page has been updated with the deprecation notice.  But just because I'm a mad scientist kind of software engineer, I'm taking a look into what it would take to make a multi-engine jasmine work:

- eshost supports running a single file against multiple engines.
- To combine the spec and source files into one loadable file, I could use [rollup](https://rollupjs.org/guide/en/) to generate a temporary file, with a sourcemap.  I've had good first impressions of it so far.
- For the output, eshost supports a single print() command, writing to stdout.  I'd probably have to adapt the nodejs reporter or the JsApi reporter for that case.
- We may want to launch eshost as a child process in nodejs to force the stdout to be unbuffered, and to combine the reporter's output (preferably JSON) of test failures with the generated source map to produce useful errors as tests run.

Obviously this is a fair bit of work with serious dependencies, and there's no way this project should accept such a complicated piece into its main repository.  But a separate repository?  I could see that.

**Comment by sgravrock** [comment]
That sounds like an interesting project. You might want to look at [jasmine-npm](https://github.com/jasmine/jasmine-npm) if you haven't already. It solves similar problems (set up a Jasmine environment, load specs, hook in a suitable reporter, etc) albeit in a Node-specific way and you might find some useful ideas there.

Good luck!
