### ISSUE TITLE
Migration form node-sass

### ISSUE THREAD

**Issue by mvodicka01** [jasmine/jasmine#1894]
Hi, I was wondering if the library can migrate from node-sass in next versions as the node-sass library is deprecated. Are there any dependencies which block this action?

`'node-sass' usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour and start using 'sass' uninstall 'node-sass'.`

**Comment by slackersoft** [comment]
There is probably a larger effort due around just how Jasmine combines and minifies its files, but the sass portion should be doable without having to change everything. This should also be a development only issue as Jasmine doesn't have any runtime dependencies, so this hasn't been super high priority for us.

That said, we would be happy to review a pull request to convert to a supported tool.

**Comment by mvodicka01** [comment]
I updated it locally following your steps for contributors, but I can't push my changes with `Permission to jasmine/jasmine.git denied`. I did all steps from [here](https://github.com/jasmine/jasmine/blob/main/.github/CONTRIBUTING.md), but I can't push changes on my feature branch.

**Comment by coyoteecd** [comment]
@mvodicka01 It sounds like you're trying to push changes directly to jasmine/jasmine repo, that only works for maintainers. You should fork the jasmine repo in your own Github account, push your changes in a branch there, and submit a pull request referencing this issue.
