### ISSUE TITLE
spyOnAllFunctions does not create any spies for class instance methods

### ISSUE THREAD

**Issue by Dari-K** [jasmine/jasmine#1897]
The specific case is when using classes in Typescript, and passing a class instance to `spyOnAllFunctions`.
Not sure what the expected behaviour is for private vs public methods of class instances, but in this case neither are getting spies created for them.

## Expected Behavior
spyOnAllFunctions creates a spy for each function in the object given.

## Current Behavior
No spies are created.

## Possible Solution
This seems to happen because when compiling to ES5 the generated JS would use functions and prototypes, but when compiling to a later target it just uses javascript classes. With the old prototype style the class methods would end up being enumerable properties, but with the new class style they are not enumerable, which means the `for (prop in obj)` https://github.com/jasmine/jasmine/blob/2fc5182ddcdd67456b89c92c2eedbc2443c928c6/src/core/SpyRegistry.js#L179
does not find anything because it loops over enumerable properties only. Using `Object.getOwnPropertyNames` would get all the properties, though this would include the constructor, callee, caller, arguments, etc, which would not have been included before as they are not enumerable.

**Comment by slackersoft** [comment]
We would be happy to review a pull request to add the ability spy on things with this configuration as long as it doesn't break the current functionality. (It probably also shouldn't accidentally spy on the constructor itself).

**Comment by Dari-K** [comment]
What would be an acceptable way to skip the constructor, is it good enough just to skip functions that are called constructor (is there anything else we can check)? Should this be a separate function something like a toggle `includeUnenumerable` which defaults to false?
