### ISSUE TITLE
Add Spy.calls.thisFor(index), similar to Spy.calls.argsFor(index)?

### ISSUE THREAD

**Issue by ajvincent** [jasmine/jasmine#1902]
## Expected Behavior

```javascript
const thisArg = {};
const mySpy = jasmine.createSpy("mySpy");
const map = new Map([["foo", "bar"]]);
map.forEach(mySpy, thisArg);

expect(mySpy.calls.thisFor(0)).toBe(thisArg);
```

## Current Behavior

There is no direct access to the `this` object for a Spy invocation, except through `.all()` if your invocation was neither the `first()` nor the `mostRecent()`.

I'm really hoping this is a low-hanging fruit idea, easy to do and not something that's been previously rejected.

## Context

I'm implementing some composite collections (think two-key maps, maps of sets, etc.) through code generation.  Similar to the above, one of my methods provides a forEach() method which should use the passed-in `this` argument.  That said, Jasmine's documented API does not provide a direct way to get at the `this` object for an invocation.

## Your Environment

NodeJS 14+ in npm, Jasmine 3.7.0, at https://github.com/ajvincent/composite-collection/blob/main/spec/CodeGenerator/SoloStrongMap.mjs#L159-L163.  Operating system agnostic: I've run this on both MacOS 11.2.3 and Fedora 33.

**Comment by ajvincent** [comment]
:-( Of course, this runs afoul of the first rule about successful pull requests:  "Do not change the public interface."

I successfully generated a [branch](https://github.com/ajvincent/jasmine/tree/spy-calls-thisFor) with this functionality and a test in about 20 minutes.  Before I break that rule, I'd like sign-off from the Jasmine owners that this is okay.

**Comment by sgravrock** [comment]
That seems like a nice addition. I took a quick peek at your branch and the only thing that jumped out at me is that (for completion) it would be nice to have a test for the case where the spy is called without a `this`. I'd be happy to review it further if you submit a PR.

The rule about changing the public interface is really about changing existing things. Adding new things that don't break existing user code is 100% fine and normal. Thanks for reading the contributor's guide.
