### ISSUE TITLE
addAsyncMatchers test for "not" incorrectly has pass: true for the compare() path?

### ISSUE THREAD

**Issue by ajvincent** [jasmine/jasmine#1905]
## Summary
https://github.com/jasmine/jasmine/blob/5f9315731e299ed728c1f4a8cef91a6d867236c7/spec/core/integration/CustomAsyncMatchersSpec.js#L45-L52

As written, the test isn't really telling you which is correct behavior.  Both the `compare()` and the `negativeCompare()` paths say `return Promise.resolve({ pass: true });`.  So you don't know that you're actually running the negativeCompare as the test description says.

## Possible Solution
I see two possible solutions:

1. Change the compare() path to a Promise.reject().
2. Change the compare() path to resolve to `{pass: false}`.

Unfortunately I don't know which one is the correct solution.

## Related issues

I ran into this while searching for documentation on how to implement a custom async matcher.  Surprisingly, the tutorials page on custom matchers didn't include an example.  Good tests are a nice backup plan for documentation, though. 😄

**Comment by ajvincent** [comment]
Eh, on second thought I'm not sure anymore... after all, a `.not()` is supposed to negate the result of a _positive_ test.

**Comment by slackersoft** [comment]
I agree that test does end up looking a bit confusing, but you are correct in your [second comment](https://github.com/jasmine/jasmine/issues/1905#issuecomment-820125843) that the negating of the positive assertion would cause the test to fail if we didn't use the negative comparison. You can see this for yourself by going to [Expectation](https://github.com/jasmine/jasmine/blob/140225e7c3771a90e03bcde2756695691e69b39c/src/core/Expectation.js#L191) and removing the `matcher.negativeCompare ||` part and you will see the test fail.
