### ISSUE TITLE
HTML Reporter for angular (karma) always runs all specs 

### ISSUE THREAD

**Issue by jlpstolwijk** [jasmine/jasmine#1906]
## Expected Behavior
When clicking a spec in the html report, only that spec should be run. 
(Using karma-jasmine-html-reporter, but issue should be fixed in jasmine itself, see below).

## Current Behavior
When clicking a spec in the html report, the full page reloads, running all specs again. Both in regular report and in debug mode.

This seems to be caused by the combination of 2 things:

1. the href of the specs have only a query string, without url path, e.g. `<a title="should be created" href="?spec=ConfirmService%20should%20be%20created">should be created</a>`
2. both the context.html and the debug.html page have `<base href="/">` in the header. The angular team apparently added this in response to [this issue](https://github.com/angular/angular-cli/issues/19116).

See also [this issue, filed on karma repo](https://github.com/karma-runner/karma/issues/3581) (also not picked up there, because it belongs to jasmine), and [this one on karma-jasmine repo](https://github.com/karma-runner/karma-jasmine/issues/282).

## Possible Solution
I'm working on a PR, which I will link to this issue. This involves adding the url pathname + query string to the href of the spec, instead of only adding the query string.
This solution was inspired by [this issue + PR on karma-jasmine-html-reporter](https://github.com/dfederm/karma-jasmine-html-reporter/issues/44), which was rejected because that repo basically copies its code from jasmine. I hope the current PR can be incorporated in jasmine and then copied to karma-jasmine-html-reporter.

## Suite that reproduces the behavior (for bugs)
```
npm install -g @angular/cli
ng new test-app
cd test-app
ng test
```
Then click on a single spec
=> notice that page reloads, and all specs are run again.
Same issue happens in debug mode.

## Your Environment
* Environment name and version: Chrome 90.0.4430.72 (Official Build) (64-bit), Node: 14.16.1
* Operating System and version (desktop or mobile): Windows 10 desktop, x64
* Packages:
 ```
    "@angular-devkit/build-angular": "^0.1102.9",
    "@angular/cli": "^11.2.9",
    "@angular/compiler-cli": "^11.2.10",
    "jasmine-core": "^3.7.1",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.3.2",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-jasmine": "^4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",

```

**Comment by sgravrock** [comment]
@jlpstolwijk Sorry, but I reverted your fix for this because it breaks the functionality of the options checkboxes (accessed via the options button in the top right corner). If you'd like to submit another fix for the Karma issue that doesn't break existing functionality, I'd be happy to review it.

**Comment by jlpstolwijk** [comment]
ah too bad, sorry about that! I'll have a look

**Comment by jlpstolwijk** [comment]
I've create a new PR that doesn't break existing functionality, as far as I can see
