### ISSUE TITLE
afterEach method is missing from jasmine namespace getEnv Method

### ISSUE THREAD

**Issue by Arghh** [jasmine/jasmine#1914]
Hi,

after updating to     "@types/jasmine": "~3.7.0"  the afterEach method seems to be missing in the jasmine.Env namespace.

How can I call this method after the update? Was there a change?

`jasmine.getEnv().afterEach(() => {});`

Thank you for your help!

**Comment by Arghh** [comment]
So in 3.7.0 afterEach along with other methods got moved out of Env namespace and into Globals.

the call in `test.ts` should be now:

`afterEach(() => {});`

that's it. 

the issue can be closed.

**Comment by slackersoft** [comment]
`afterEach` has always been available on the global namespace, along with `it`, `describe`, etc. What happened recently is the typings for Jasmine got updated to more obviously indicate where you should be calling those functions from.
