### ISSUE TITLE
Async timeout firing before custom set timeout

### ISSUE THREAD

**Issue by appy-one** [jasmine/jasmine#1916]
I'm running an async test with custom timeout of `Number.MAX_SAFE_INTEGER`, and after a random amount of time (0 - aprox 10 seconds)  it stops with error ` Error: Timeout - Async function did not complete within 9007199254740991ms (custom timeout)`

Jasmine v3.7.0, core v3.7.1

**Comment by sgravrock** [comment]
When I run a spec like the one you described, I get this diagnostic:

```
(node:4189) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

Try using 2147483647ms (about 24.9 days), or better yet the longest amount of time you're actually willing to wait for the spec to complete.

**Comment by appy-one** [comment]
In my case, I am stress-testing an [AceBase ](https://github.com/appy-one/acebase) database by performing many, fast pseudo-random read and write operations to the data for a long time to test data integrity and deadlock prevention. Being able to let such tests running for days (or weeks) is desirable. Would it be easy for you to disable the timeout entirely if 0 or -1 is passed as parameter?

**Comment by sgravrock** [comment]
> Would it be easy for you to disable the timeout entirely if 0 or -1 is passed as parameter?

The necessary code change is straightforward, but it sits right in the middle of the most bug-prone and difficult to debug part of Jasmine. The bar for adding even small amounts of complexity there is pretty high. And I suspect that you’re the only one who’s going to use the proposed feature.

I hate to tell anyone to maintain a local fork of Jasmine, but that might be the best path forward if you really need a spec to run for longer than 24 days. Here’s the most likely touch point: https://github.com/jasmine/jasmine/blob/68db3f6fcf17426148edffb165c12517bdb84f9b/src/core/QueueRunner.js#L138-L150
