### ISSUE TITLE
jasmine.stringMatching doesn't work well with a raw string passed in containing ?

### ISSUE THREAD

**Issue by chivesrs** [jasmine/jasmine#1923]
## Expected Behavior
The test case passes, and ? isn't treated as the regex char

## Current Behavior
The raw ? gets treated as a regex char instead of a literal ?

## Possible Solution

Some sort of regex escaper?

## Suite that reproduces the behavior (for bugs)

```
describe('identity', () => {
  it('returns the same value', () => {
    const s = jasmine.createSpy();
    s('join? bob');
    expect(s).toHaveBeenCalledWith(jasmine.stringMatching('join? bob'));
    expect(jasmine.version).toBe('3.8.0');
  });
});
```
## Your Environment

* Version used: 3.8
* Environment name and version (e.g. Chrome 39, node.js 5.4): This is a stackblitz so I don't know any of this, but Chrome 91.0.4472.164
* Operating System and version (desktop or mobile): Linux Desktop 5.10.40
* Link to your project: N/A

**Comment by SLaks** [comment]
This is by design; `stringMatching()` creates a regex.

Use `expect(s).toHaveBeenCalledWith('join? bob')`

**Comment by sgravrock** [comment]
For more complex uses, like inside of `objectContaining`, I could the benefit of having a `stringContaining` asymmetric equality tester:

```
const something = {
   ...aBunchMoreProperties,
   foo: 'a string that contains join? bob somewhere'
};
expect(something).toEqual(jasmine.objectContaining({
   foo: jasmine.stringContaining('join? bob')
});
```

I'd be happy to review a PR that adds that.
