### ISSUE TITLE
Unable to run on IOS

### ISSUE THREAD

**Issue by shreyash-sharma** [jasmine/jasmine#1927]
I have tests integrated using Karma and Jasmine for backend testing. I've been using local environments until now but now using browserstack I'm trying to integrate it with iOS.

Everything else works Windows Chrome Mac Safari Android Chrome

Only iPhone safari doesn't work.

The tests run on a server and we are automating the backend. We were using Chrome headless integrated using Karma with the testing framework being Jasmine.

All the tests work with

Chrome Mac

Safari Mac

Chrome Windows

Firefox Windows

And even

Chrome Android

But I get Async error with timeout exception when running the same stuff on iPhone Safari.

So just wanted to know if this is even supported, like if Jasmine is even supported on iPhone to run tests.

Everything is based on JS

**Comment by sgravrock** [comment]
Mobile Safari is not supported but should work in practice, albeit very slowly. I just ran Jasmine's own test suite in mobile Safari and it passed both on a phone and in the simulator. However, the device was 15x slower than desktop Firefox and the simulator was 40x slower.

Jasmine doesn't produce the error message "Async error with timeout", so if that's literally the message you got then it's coming from something other than Jasmine. But if it was actually something like "Timeout - Async function did not complete within <some number>ms", that means that you have an asynchronous spec or before/after function that isn't finishing within the time limit. That could mean that you have a bug in your code that only shows up in mobile Safari. But I think it's more likely that you just need to increase the time limit to account for poor performance in that browser.

**Comment by shreyash-sharma** [comment]
Thanks for your reply! Is there any official page stating the platforms that are supported?

**Comment by sgravrock** [comment]
Yes, it's near the bottom of the [readme](https://github.com/jasmine/jasmine).

**Comment by shreyash-sharma** [comment]
Thanks again!

**Comment by sgravrock** [comment]
You're welcome.
