### ISSUE TITLE
afterEach happens in the middle of an async test

### ISSUE THREAD

**Issue by trusktr** [jasmine/jasmine#1930]
## Expected Behavior

I expect `beforeEach` and `afterEach` procedures to execute before or after tests, never in the middle of a test.

## Current Behavior

`afterEach` fires in the middle of an `async` test.

## Suite that reproduces the behavior (for bugs)

For example, suppose I have a test like this:

```js
describe('foo', () => {
  beforeEach(() => console.log('before'))
  afterEach(() => console.log('after'))

  it('a', async () => {
    console.log('a1')
    await new Promise(r => setTimeout(r, 10))
    console.log('a2')
  })

  it('b', async () => {
    console.log('b1')
    await new Promise(r => setTimeout(r, 10))
    console.log('b2')
  })
})
```

The output will contain this:

```
b1
after
b2
```

This does not make sense, this does not match with expectations people have when they write synchronous tests: `beforeEach` and `afterEach` will never run in the middle of a synchronous test.

## Context

I was spending hours thinking something is wrong with my code, then I realized that the cleanup code in my `afterEach` is the culprit because it is destroying things that should be in place for the expectations that remain for the last half of a test.

## Your Environment

* Version used: 3.9.0
* Environment name and version: Electron 12 via Karma 6
* Operating System and version: Manjaro Linux
* Link to your project: ...

**Comment by trusktr** [comment]
I tried to use `done` instead of `async`/`await`,

```js
describe('foo', () => {
  beforeEach(() => console.log('before'))
  afterEach(() => console.log('after'))

  it('a', done => {
    console.log('a1')
    new Promise(r => setTimeout(r, 10)).then(() => {
      console.log('a2')
      done()
    })
  })

  it('b', done => {
    console.log('b1')
    new Promise(r => setTimeout(r, 10)).then(() => {
      console.log('b2')
      done()
    })
  })
})
```

but the some problem persists.

**Comment by trusktr** [comment]
Upon further investigation, _sometimes_ the `afterEach` runs after a particular test in question, _sometimes_ in the middle of it; it is inconsistent.

**Comment by sgravrock** [comment]
The symptoms you describe usually indicate that an asynchronous spec has told Jasmine that it's done before it actually is. (See <https://jasmine.github.io/pages/faq.html#005-parallel> and <https://jasmine.github.io/tutorials/async>.)

That said, I can't reproduce the problem. When I run the example suites above, I get this output:

```
Randomized with seed 27808
Started
before
b1
b2
after
.before
a1
a2
after
.before
b1
b2
after
.before
a1
a2
after
.


4 specs, 0 failures
Finished in 0.055 seconds
Randomized with seed 27808 (jasmine --random=true --seed=27808)
```

**Comment by trusktr** [comment]
It turns out that `jasmine.DEFAULT_TIMEOUT_INTERVAL`, which defaults to `5000` ms, times out while I'm stepping through tests, causing before or after hooks to fire while a test has not finished (the action of stepping through code takes longer than 5 seconds until the next `await` point at which the Jasmine timeout can run before/after hooks).

With this new knowledge, I tried setting `jasmine.DEFAULT_TIMEOUT_INTERVAL` to 2,856 centuries (`Number.MAX_SAFE_INTEGER`), however now I see a bunch of errors that don't make sense:

```
Error: Timeout - Async function did not complete within 9007199254740991ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
```

I don't have a time machine yet. :smile:

**Comment by sgravrock** [comment]
Jasmine's async timeouts are implemented with `setTimeout`. Most (all?) implementations of `setTimeout` can't handle values as large as `Number.MAX_SAFE_INTEGER`. My guess is that you're running on a JS runtime whose `setTimeout` handles such large values by immediately calling the callback. Try sticking to values that fit in a 32 bit signed integer, which ought to be safe everywhere, or check your JS runtime's documentation for the actual limit.

**Comment by trusktr** [comment]
> Most (all?) implementations of `setTimeout` can't handle values as large as `Number.MAX_SAFE_INTEGER`.

I tested `setTimeout(() => console.log('hello'), Infinity)` in Chrome, and it never logs.

However even if I set the timeout to something like a month in Jasmine, I still get similar `Async function did not complete within 2628000000ms` errors.

I switched my tests to mocha+chai just now, using the [`chai-jasmine`](https://github.com/crysalead-js/chai-jasmine) adapter so that the `expect()` syntax stays the same as with Jasmine, and I am not having the async timeout issue with the same month-long value.

**Comment by trusktr** [comment]
Hmm, interesting. :thinking: I reduced the number to 1 week (`1210000000`) and now I don't have the issue with Jasmine (and Mocha still works as it did even with a bigger value which presumably overflowed to a smaller but still large value).

Or in other words, I can confirm that with a timeout that doesn't fit in an `i32`, like `2628000000`, Jasmine has the async timeout errors and will fire before/after hook in middle of my tests, but Mocha still works and waits for me to finish stepping through tests.

I'm not sure what the difference is between jasmine and mocha, but that's what I'm seeing.

**Comment by trusktr** [comment]
Pull request to clarify in the docs: 

https://github.com/jasmine/jasmine/pull/1931

**Comment by sgravrock** [comment]
> EDIT: does this mean Mocha has special handling, or something?

As far as I can tell, not in browsers, which I understand that you were using. I haven't been able to reproduce what you saw: If I breakpoint inside an async Mocha spec and stay stopped long enough for timeouts to fire, the `afterEach` fn runs as soon as the spec awaits after I un-pause execution.

Mocha *does* disable timeouts when run with debugger support in Node. That's useful but it's also led to a handful of bug reports from people who didn't understand why timeouts weren't working. That makes me a little reluctant to add such a feature even in environments where we can detect the presence of a debugger.

Given that, and the fact that we haven't heard any similar bug reports since your docs PR and my change to reject out-of-range timeout values, I don't think there's anything more to do here.

**Comment by caarmen** [comment]
I'm also having `afterEach()` being called too soon, as soon as I add `async` to one of my tests 🤔 

Not having timeout issues or debugging code in my case.

Will post here later when I find more.
