### ISSUE TITLE
Clock clashes with Zone.js

### ISSUE THREAD

**Issue by krzysztof-grzybek** [jasmine/jasmine#1944]
## Expected Behavior
I would like to have the possibility to run jasmine with [Zone.js](https://github.com/angular/angular/tree/master/packages/zone.js) without any inconveniences. I would have to possibility to load Zone.js after jasmine is bootstrapped.

## Current Behavior
If Zone.js is loaded before jasmine, it works ok. But if jasmine is loaded before Zone.js, when calling `jasmine.clock().install()`, I'm getting error `Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?`

## Possible Solution
It occurs because Zone.js overrides global functions like `setTimeout`, so this is what's happening.
1. Jasmine is bootstrapped, clock gathers `realTimingFunctions` ([here](https://github.com/jasmine/jasmine/blob/main/src/core/Clock.js#L18))
2. Zone.js is bootstrapped, it overrides global functions (not sure if all, `setTimeout` for sure).
3. I call `jasmine.clock().install()` from the spec code.
4. Jasmine checks if the clock wasn't installed already by comparison with `realTimingFunctions` ([here](https://github.com/jasmine/jasmine/blob/main/src/core/Clock.js#L144). Because those were overridden by Zone.js , it throws an error.

Possible solution:

If the only reason for this check is to check if `clock` was already installed, we can just compare the global functions with our local ones, e.g. `!global.setTimeout === self.setTimeout`. To make `uninstall` work properely, we can gather `realTimingFunctions` directly in the `install` function. So it would something like:

```js

function originalTimingFunctionsIntact() {
      return (
         !(global.setTimeout === self.setTimeout) &&
          !(global.clearTimeout === self.clearTimeout) &&
          !(global.setInterval === self.setInterval) &&
          !(global.clearInterval === self.clearInterval)
      );
}

self.install = function() {
      realTimingFunctions = {
          setTimeout: global.setTimeout,
          clearTimeout: global.clearTimeout,
          setInterval: global.setInterval,
          clearInterval: global.clearInterval
      },

     if (!originalTimingFunctionsIntact()) {
          throw new Error(
              'Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?'
          );
     }
...
}
```

## Suite that reproduces the behavior (for bugs)

Load jasmine before Zone.js and use clock
```javascript
describe("sample", function() {
jasmine.clock().install();
});
```
## Context
I'm using angular setup with nx. With default configuration, it works for `apps`, but not for `libs`.

## Your Environment

* Version used: 3.5.0
* Environment name and version Chrome 95
* Operating System and version (desktop or mobile): desktop
* Link to your project:

**Comment by sgravrock** [comment]
On the one hand, we don't support configurations where Jasmine itself or the JS runtime has been monkey-patched. And as far as I know the Angular folks have generally seen these kinds of conflicts as theirs to solve. That appears to include this specific case. See [angular/angular-cli/#14432](https://github.com/angular/angular-cli/issues/14432) which has some workarounds that look pretty easy, and [angular/angular-cli#11626](https://github.com/angular/angular-cli/issues/11626) for some related history.

On the other hand, it looks like there are a huge number of Angular users already using Jasmine alongside zone.js, with few problems. (I'm slightly surprised by that -- I'd have expected use of the mock clock to break any part of Angular that depends on zone.js's patches.)

I think it would be reasonable to have an off-by-default configuration setting that allows the mock clock to be installed over other monkey patches, provided that it also emits a warning that the configuration is unsupported. I'd be happy to review a PR that adds that functionality.

**Comment by krzysztof-grzybek** [comment]
Thanks for the quick response! I will try to raise a PR later this week.

**Comment by sgravrock** [comment]
It's been over two years with no signs of interest in this issue from other users, and it appears to have been fixed on the Angular side. Closing.
