### ISSUE TITLE
Can we have a way to hide excluded tests from test result summary in HTMLReporter?

### ISSUE THREAD

**Issue by Jamie5** [jasmine/jasmine#1946]
## Are you creating an issue in the correct repository?

Yes

## Expected Behavior
It would be nice to have an option to not print out test results for excluded tests (including non-forced tests).

## Current Behavior
There appears to be no easy way to do this

## Possible Solution
In https://github.com/jasmine/jasmine/blob/main/lib/jasmine-core/jasmine-html.js , have another condition in `if (filterSpecs && !hasActiveSpec(resultNode)) {` which would be a flag we set in the config.

## Suite that reproduces the behavior (for bugs)
N/A

## Context
With thousands of tests, when you're running a few tests it seems pointless to list all those other tests that you intentionally didn't `fdescribe`/`fit` on.

## Your Environment
N/A

**Comment by sgravrock** [comment]
Is this something that you'd want to leave on all the time, or would you just turn it on in certain situations? I'm wondering if some UI like a link to hide skipped specs might work better than a configuration setting.

Either way, we'd want to make sure that there's enough information displayed for users to know that not all their specs were run and how to see which ones were skipped.

**Comment by Jamie5** [comment]
I would want it on by default, because 99% of time running tests locally we're `fit` or `fdescribe`ing something and know there's thousands of unrun tests. And needing to explicitly click on a link seems like undesired friction.

**Comment by sgravrock** [comment]
Understood. My main concern with anything like this is that people sometimes forget that they're running focused. I don't want to add any risk of people thinking that their suite is green when it isn't. 

I think your proposal of a configuration property that's read by the HTML reporter is a reasonable way to balance everyone's needs. The reporter would need to continue to display the existing "Incomplete: fit() or fdescribe() was found" message and also show something that tells the user that non-focused specs were omitted, and why. The actual filtering would have to happen in the reporter itself, as you suggested. If jasmine-core were to stop emitting events for skipped suites/specs, that would break third party reporters.

I'd be happy to review a PR that adds that functionality.

**Comment by sgravrock** [comment]
I'm closing this feature request because it's gone almost two years with no PR and no sign of interest from anyone other than the original requester. Anyone who wants this feature enough to submit a PR should still feel free to do so, but I don't think it's worth keeping the issue open.

**Comment by Sobobornraised** [comment]
Y
