### ISSUE TITLE
Add support for arrayContainingExact

### ISSUE THREAD

**Issue by trevor-gullstad** [jasmine/jasmine#1950]
`expect(receivedArray).toEqual(jasmine.arrayContaining(expectedArray))` checks if the received array contains the expected elements, but does not require an exact match. I'd like a method to check if the two arrays have the exact same elements.

Current State:
```
expect([ 0, 1 ]).toEqual(jasmine.arrayContaining([ 0, 1 ]));     // pass
expect([ 0, 1 ]).toEqual(jasmine.arrayContaining([ 0, 1, 2 ]));  // fail
expect([ 0, 1 ]).toEqual(jasmine.arrayContaining([ 0 ]));        // pass
```

Desired State:
```
expect([ 0, 1 ]).toEqual(jasmine.arrayContainingExact([ 0, 1 ]));     // pass
expect([ 0, 1 ]).toEqual(jasmine.arrayContainingExact([ 0, 1, 2 ]));  // fail
expect([ 0, 1 ]).toEqual(jasmine.arrayContainingExact([ 0 ]));        // fail
```

**Comment by slackersoft** [comment]
Good catch. Upon re-reading this, I think we can close it.

It looks like the original request is actually to make an in-order all elements comparison of an array. This should be the default case for:

```javascript
expect([0, 1]).toEqual([0, 1])
```

If you want an out of order all elements comparison, you should be able to use:

```javascript
expect([0, 1]).toEqual(jasmine.arrayWithExactContents([1, 0])
```

If you want partial comparison in any order you can use either of:

```javascript
expect([0, 1]).toContain(1)
expect([0, 1, 2]).toEqual(jasmine.arrayContaining([2, 1])
```

A multi-element partial match that cares about order seems of limited enough value that we probably don't need a matcher included in Jasmine for that.
