### ISSUE TITLE
DEPRECATION warning without any done() calls in tests

### ISSUE THREAD

**Issue by matthjes** [jasmine/jasmine#1956]
## Expected Behavior
The following messages should not appear in tests that do not use `done()`.
```
DEPRECATION: An asynchronous function called its 'done' callback more than once. This is a bug in the spec, beforeAll, beforeEach, afterAll, or afterEach function in question. This will be treated as an error in a future version. See<https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#deprecations-due-to-calling-done-multiple-times> for more information
(in spec: TestreportSelectionComponent should init component correctly)
```
## Current Behavior
The message appears in tests that do not use `done()`.

## Possible Solution
Don't know.

## Context
We've switched from Jasmine 2.6.4 to 4.0.0 and now getting these messages when running tests. These tests, however, do not use the `done()` function at all, in fact, the entire file does not import the function.

This is one of those tests:
```
  it('should init component correctly', () => {
    // given
    const referenzA: string[] = ['A', 'B'];
    const referenzB: string = 'B';
    spyOn(service1, 'fetchAllA').and.returnValue(of(referenzA));
    spyOn(service2, 'fetchCurrentB').and.returnValue(of(referenzB));

    // when
    component.ngOnInit();
    component.ngOnChanges();

    expect(service1.fetchAllA).toHaveBeenCalledTimes(1);
    expect(service2.fetchCurrentB).toHaveBeenCalledTimes(1)
  });
```
When this one is executed, the warning appears at the end

## Your Environment
* Version used: 4.0.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 97.0.4692.99
* Operating System and version (desktop or mobile): Desktop

**Comment by slackersoft** [comment]
It is also worth noting here that the very nature of calling the `done` callback more than once means that Jasmine will have moved on in execution to the next spec in the execution order. Unfortunately, this means that the spec that is calling done more than once is quite unlikely to be the spec where the error is associated. Previously, Jasmine just silently ignored duplicate calls, but this was changed to an error because it indicates that code from that previous test is _still running_ during the execution of other tests, possibly causing various types of pollution.

**Comment by matthjes** [comment]
Hi,

Thanks for the quick response. Unfortunately, I think I cannot provide a minimal example as this is quite a big project and I'm not sure how to extract the relevant parts and still be able to reproduce the problem.

Your last comment is interesting, as I'm seeing this problem when I just execute a single spec / test case. So maybe I have look at the initialization / tear down process, although I think there is nothing special in beforeEach, it just initializes the TestBed, create the components, etc. But I'll have a look.

**Comment by coyoteecd** [comment]
@sgravrock @slackersoft for what is worth, I am also seeing this when attempting to upgrade to jasmine v4.
The key info (I think) is that it's an Angular project - I upgraded some TypeScript-only projects and did not see the issue, whereas both my Angular projects show hundreds of "done called twice" errors.

I am not using done anywhere, I suspect that some other package - karma or angular (?) is doing things behind the scenes, and whatever it does, it does it twice.

**Comment by sgravrock** [comment]
> I am not using done anywhere, I suspect that some other package - karma or angular (?) is doing things behind the scenes, and whatever it does, it does it twice.

That seems likely.

I haven't been able to reproduce this so far, but I also don't have any non-toy Angular test suites handy. It would help if one of you who are affected affected could do one or both of the following:

* Put together a complete, minimal, runnable example that we can try out
* Patch jasmine.js as follows, and let us know what the stack trace that gets logged to the browser console looks like.

```
--- jasmine.js.before	2022-02-07 15:09:01.000000000 -0800
+++ jasmine.js	2022-02-07 18:06:04.000000000 -0800
@@ -1484,6 +1484,7 @@
     };
 
     function recordLateError(error) {
+      console.error(error);
       const result = expectationResultFactory({
         error,
         passed: false,
```

**Comment by sgravrock** [comment]
It looks like 3.99 produces a usable stack trace in this scenario, unlike 4.0. So downgrading to 3.99 and then checking the stack trace might be another way to track down the code that's calling `done` twice..

**Comment by coyoteecd** [comment]
Okay, so I've managed to reproduce it, in a empty application.
Here's the relevant code (a modified copy of app.component.spec, as generated by the `ng new` Angular CLI command):

```ts
import { TestBed, waitForAsync } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
import { ExampleService } from './example.service';

describe('AppComponent', () => {
  let svc: ExampleService;

  beforeEach(waitForAsync(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        ExampleService
      ]
    }).compileComponents();

    svc = TestBed.inject(ExampleService);
  }));

  it('should create the app', waitForAsync(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  }));
});
```

What's killing it is the combination of two waitForAsync, one in `beforeEach` and one in the actual test spec, combined with extracting the `ExampleService` (just an empty service) out of the injector, in the same `beforeEach` as the testbed initialization.

Doing **any of the following resolves the issue**:

1. move the TestBed.inject line in its own beforeEach that does not use waitForAsync wrapper (but in the case, the issue reappears if I add an additional empty beforeEach that does use the waitForAsync wrapper:
```ts
describe('AppComponent', () => {
  let svc: ExampleService;

  beforeEach(waitForAsync(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        ExampleService
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    svc = TestBed.inject(ExampleService);
  });

  // uncommenting this will break the test
  // beforeEach(waitForAsync(() => {}));

  it('should create the app', waitForAsync(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  }));
});
```

2. removing the waitForAsync from the beforeEach that sets up the TestBed (and - same as before - adding another one with waitForAsync breaks it again):

```ts
describe('AppComponent', () => {
  let svc: ExampleService;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        ExampleService
      ]
    }).compileComponents();

    svc = TestBed.inject(ExampleService);
  });

  // uncommenting this will break the test
  // beforeEach(waitForAsync(() => {}));

  it('should create the app', waitForAsync(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  }));
});
```

3. removing the waitForAsync from the spec itself.

```ts
describe('AppComponent', () => {
  let svc: ExampleService;

  beforeEach(waitForAsync(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        ExampleService
      ]
    }).compileComponents();

    svc = TestBed.inject(ExampleService);
  }));

  beforeEach(waitForAsync(() => {}));

  // putting waitForAsync here will again break the test
  it('should create the app', (() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  }));
});
```

**Comment by matthjes** [comment]
Ist the `async` inside `waitForAsync` correct (in `beforeEach`)? Just curious, never saw this before.

**Comment by coyoteecd** [comment]
@matthjes the waitForAsync is not necessary, in our case we actually do not have it, also no await on compileComponents. Older versions of Angular generated the specs without any async/waitForAsync in the initial beforeEach. The problem occurs with or without it.

In our project we use `waitForAsync` basically everywhere, because it sucks to debug a test suite that fails randomly due to missing service mocks. jasmine was (probably still is) reporting the error much later, and good luck finding what test is broken. So that's why we hit the issue.

**Comment by matthjes** [comment]
@coyoteecd 
We're using
```
 beforeEach(async(() => {
    await TestBed.configureTestingModule({
 ...
```
or, instead of `async()` now `waitForAsync()`, but I've never seen both `waitForAsync(async ()`. Maybe we are using this wrong.

**Comment by matthjes** [comment]
> Related issue in the Angular repo: [angular/angular#45025](https://github.com/angular/angular/pull/45025)

Ok, then it's going to be handled on the Angular side and should be resolved with one of the next updates.

**Comment by coyoteecd** [comment]
> @coyoteecd We're using
> 
> ```
>  beforeEach(async(() => {
>     await TestBed.configureTestingModule({
>  ...
> ```
> 
> or, instead of `async()` now `waitForAsync()`, but I've never seen both `waitForAsync(async ()`. Maybe we are using this wrong.

@matthjes that code would not compile, you cannot use await without an async (the keyword, not the Angular async()/waitForAsync() function wrapper). Maybe what you have is this:
```ts
beforeEach(async(() => {
  TestBed.configureTestingModule(..)
    .compileComponents();
}));
```
i.e. using the deprecated async wrapper and no await. It is entirely possible to mix waitForAsync with async functions, you do it anywhere where you want to await, including awaiting on fixture.whenStable(). At any rate, this is going offtopic, let's not spam the jasmine repo with Angular stuff.

**Comment by matthjes** [comment]
Thanks for clarifying this! Yes, I've overlooked the `await`, we're using the Version you posted.

I'll close this ticket as the issue is handled on the Angular side.

**Comment by sgravrock** [comment]
Thanks, everyone. I appreciate all the work you've done to pin this down, and the quick action on the Angular side. I also think there's probably more that Jasmine can do to pinpoint the source of this error, and I'll be looking into that.

**Comment by sgravrock** [comment]
On further investigation, I don't see anything that Jasmine can do to improve the situation. I had hoped to show a stack trace that points at the problematic `done` call. But it looks like zone.js is wrapping the `done` callback in something async, with the result that the calling code is no longer on the stack by the time that Jasmine is called:

```
Error: 
    at eval (eval at Deprecator.addDeprecationWarning (jasmine.js:1:1), <anonymous>:1:1)
    at Deprecator.addDeprecationWarning (jasmine.js:4299:5)
    at Spec.Env.deprecated (jasmine.js:1947:18)
    at ZoneQueueRunner.onMultipleDone (jasmine.js:932:14)
    at jasmine.js:8610:20
    at jasmine.js:8473:11       <-- this is the actual done function
    at _karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1299:1
    at ZoneDelegate.invoke (zone.js:372:1)
    at ProxyZoneSpec.onInvoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
    at ZoneDelegate.invoke (zone.js:371:1)
```

Notice that there's nothing but zone.js internals on the stack below the done function.

Additionally, `karma-jasmine-html-reporter` packages a slightly older version of Jasmine's HTML reporter that doesn't show stack traces on deprecation warnings.

I also noticed that karma-jasmine depends on `"jasmine-core": "^3.6.0"`. As a result, you'll still end up running a 3.x version even if you've explicitly installed 4.0.0. That explains the handful of issues I've seen, including this one, where people say they're running 4.0.0 but report error messages that only occur in 3.99. You'll probably have to wait for karma-jasmine to update before you can actually use Jasmine 4.
