### ISSUE TITLE
"Argument passed to a done callback..." deprecation warning when returning a Promise

### ISSUE THREAD

**Issue by provegard** [jasmine/jasmine#1958]
## Are you creating an issue in the correct repository?

I think so, yes. I'm trying to upgrade to Jasmine 4, and I'm getting _a lot_ of these:

> DEPRECATION: Any argument passed to a done callback will be treated as an error in a future release. Call the done callback without arguments if you don't want to trigger a spec failure.

However, the tests being referred to don't call a `done` callback. Instead they have `beforeEach` returning a `Promise`, e.g.

```
describe("some context", () =>{
    beforeEach(() => somePromiseReturningSetupFunction())

    it("works", () => {
        // ...
    })
})
```

Now, some of these setup functions are fixable so that they return `Promise<void>`. However, sometimes the function comes from a third-party lib, e.g. `beforeEach(() => component.setProps(...))`, where `setProps` belongs to Vue-test-utils. Changing to async/await is a lot of work since the test suite is very big.

## Expected Behavior

When a `beforeEach` (or an `it` for that matter) returns a `Promise`, I should never get a warning about `done` being called with a value.

## Current Behavior

When a `beforeEach` returns a `Promise`, I often get a warning about `done` being called with a value.

## Possible Solution

Suggestion: Detect when a `Promise` is returned and ignore any value without giving a deprecation warning.

## Suite that reproduces the behavior (for bugs)

See above for some pseudo code.

## Context

As noted, I'm trying to upgrade to Jasmine 4, but I will hold it off for now. Fixing all the deprecation warnings is just too much work.

## Your Environment

```
"jasmine": "4.0.2",
"jasmine-core": "4.0.0",
```

**Comment by sgravrock** [comment]
Thanks for the report. I suspect that this will be a relatively common problem, and I'm surprised that it's taken this long for anyone to run into it.

Your suggested fix is what I would have done in 3.99/4.0 if I'd realized that the problem existed. I think we can still *mostly* still do that, but we probably still ought to treat the special case of a promise that resolves to an `Error` or `Error`-like object as a failure.

**Comment by provegard** [comment]
> [...] but we probably still ought to treat the special case of a promise that resolves to an `Error` or `Error`-like object as a failure.

Yeah, that makes sense.

**Comment by sgravrock** [comment]
This is fixed in 3.99.1 and 4.0.1.

**Comment by robations** [comment]
@sgravrock I just spotted that 3.99.1 isn't published yet for https://www.npmjs.com/package/jasmine

**Comment by sgravrock** [comment]
@robations The package that lives in this repo and was updated to 3.99.1 is jasmine-core, not jasmine. See <https://jasmine.github.io/pages/faq.html#versions>.
