### ISSUE TITLE
createSpyObj should pass instanceof checks

### ISSUE THREAD

**Issue by TheSlimvReal** [jasmine/jasmine#1960]
## Expected Behavior
When using the `createSpyObj` function it should be possible to define what kind of class the spy should have.
This would allow the spy to pass `x instanceof y ` checks.

## Current Behavior
This option is not present

## Possible Solution
Following [this article](https://coderwall.com/p/kvsmrw/how-to-trick-instanceof) it is possible to overwrite the prototype of a object.
What could happen inside jasmine could look like this.
```javascript
function assignClass(obj, class) {
  obj.__proto__ = class.prototype
}
```

## Possible use case

I want the following code to return `true`. As far as I know, this is currently not possible with only using jasmine.
```javascript
const spyObj = jasmime.createSpyObj(["myClassFunc"]);

if (spyObj instanceof MyClass) {
   // How do I get here?
   return true;
} else {
   return false;
}
```
## Context
I am using dependency injection in Angular and I would like to check whether a dependency is instance of a specific (sub-)class.
With jasmine I am creating spy objects that are then provided by the dependency injection process.
Now I would like to be able to easily specify of which subclass a given dependency is by providing this subclass to the `jasmine.createSpyObj` function;

**Comment by sgravrock** [comment]
It sounds like you want a "partial mock", i.e. an  actual instance of `MyClass` that has some of its methods replaced with spies. You can do that like this:

```
const spyObj = new MyClass();
spyOn(spyObj, "myClassFunc");
```

**Comment by TheSlimvReal** [comment]
@sgravrock This works in some cases but its not always that easy or wanted to create a new instance and it looses the functionality that `createSpyObj` gives compared to `spyOn` e.g. replacing a getter function with a mocked-property.

**Comment by sgravrock** [comment]
If I understand correctly, you want to create a test double that both is and isn't an instance of `MyClass`: It needs to pass an `instanceof` check, but it needs to be created without calling the `MyClass` constructor. That's a sign that something is wrong with the design. The code under test is too tightly coupled to a dependency that's hard or impossible to use in tests. Dependency injection (DI) is the usual solution to that problem. But by requiring the dependency to be an instance of `MyClass`, you've reintroduced the very coupling that DI is meant to remove.

If I were in your place, I'd look for ways to remove the requirement that the dependency be an instance of `MyClass`. You didn't say why you're doing that, but if you're using it to figure out which dependency is which, you might want to take a look at how Angular DI does that while still allowing the use of tools like `createSpyObj`.


If you really want to stick with the design you've got, there are a few options:

* Use `createSpyObj` and set the prototype using the code you showed above. I won't guarantee that a future version of Jasmine won't break that by providing its own prototype, but it should work for now.
* Manually create a test double with the right prototype and with spies for the methods and property getters/setters you want to override.
* Implement your own version of `createSpyOb` within your codebase, and have it set the prototype the way you want.

I realize that none of those options are as convenient as you'd like. But that's the price of tight coupling.

**Comment by TheSlimvReal** [comment]
@sgravrock Thank you for the very detailed comment.
You are right in the assumption that it is definitely not a good design in my case.
There are workarounds to the problem e.g. instantiating `MyClass` and only spying on the relevant functions or using the `__proto__`  *hack* which I proposed above.

My question was more whether this might be a possible extension to the jasmine API to make these cases **easier** to handle. 
As you are saying it seems like these cases are generally not desirable in terms of software design and jasmine should therefore creating some barriers to not design systems that need this kind of functionality, then I can understand this reasoning. 
If this is the case feel free to close this issue.
