### ISSUE TITLE
Suggestion:  SpyStrategy.prototype.notify(anotherSpy: Spy): Spy

### ISSUE THREAD

**Issue by ajvincent** [jasmine/jasmine#1964]
I've been thinking a long while about how to create a way to _observe_ multiple spies in a richer way than `expect(spy).toHaveBeenCalledBefore(otherSpy)`.  That latter could be problematic, if we call spy A, then spy B, then spy A again.

That said, coming up with a simple API to do this is the real challenge.

Suppose there was a tracking spy which other spies reported to.  That spy would collect the _ordering_ in its calls property of the various calls.  Forwarding would be through each starting spy calling `spy.and.notify(trackingSpy, context).and.callFake()`.

## Expected Behavior
`.notify()` would register the current (sending) spy to forward its calls to another spy, like a tee.  The receiving spy would _not_ be permitted to interfere in the operations of the sending spy.  The return value of the call to `.notify()` would be the sending spy, to allow trapping other behavior.

## Current Behavior
Such a capability is not available in Jasmine right now.

## Possible Solution
Storing a `Map<trackingSpy, context>` to iterate over as a privately accessible property of the call tracker would suffice.  .notify() adds the receiving spy to the Set.  The call tracker calls each receiving spy with the context as a prepended additional argument.  Exceptions thrown from receiving spies are treated as spec failures but not allowed to break the notification or remaining spy operations.

**Comment by sgravrock** [comment]
> That said, coming up with a simple API to do this is the real challenge.

Yes, but I think it's the more important part to pin down. We're better off having the API drive the implementation rather than the other way around. So, what would you want the expectation to look like? Something like this, maybe?

```
expect([spy, otherSpy]).toHaveBeenCalledInOrder();
```

One limitation of that syntax is that it doesn't handle cases where e.g. `spy` was called mulitple times and you want to ensure that a specific call happened before `otherSpy`. But maybe that's good enough.

There's discussion of a similar but not identical feature in #1694.

**Comment by ajvincent** [comment]
I think checking the order of spy calls is a general problem for which I foresee no clean solution.  The context argument I'm suggesting gives a clue as to which starting spy caught the argument, but it doesn't really solve that problem.

This proposal is about forwarding from several starting spies to a tracking spy.  If I were to explicitly try to solve the "make sure this call happened before that call" problem, I'd go down a couple of paths:

- Maybe we require the context be a string, so we can append a counter to it.  "appleContext:1" will never match "appleContext:2".
- Ultimately, a "ensure this was before that" would have to extract a positioned argument from each call's `args` property:
```javascript
// in CallTracker.js
this.argForAllCalls = function(position) {
  return this.allArgs().map(args => args[position]);
}

// in src/core/matchers/toHaveInOrder.js
getJasmineRequireObj().toHaveInOrder = function() {
  function toHaveInOrder(matchersUtil) {
    return {
      compare: function(actual, expected) {
        if (!Array.isArray(actual) || !Array.isArray(expected))
          return { pass: false };
        const order = expected.map(item => actual.indexOf(item));
        if (order.includes(-1))
          return { pass: false; }
        return {
          pass: order.every((element, index) => {
            return index === 0 || element > order[index - 1];
          });
        };
      }
    };
  }

  return toHaveInOrder;
};

// in the spec code
const contexts = trackingSpy.calls.argForAllCalls(0);
expect(contexts).toHaveInOrder("appleContext:0", "orangeContext:0", "appleContext:1");
```

**Comment by sgravrock** [comment]
I think having spies also track the calls from other spies is likely to be confusing to users. I'm also not wild about it from an architectural standpoint.

Besides, we already track enough information to determine call order between two different spies:

```
it('calls in the right order', function() {
  const one = jasmine.createSpy('one');
  const two = jasmine.createSpy('two');
  const three = jasmine.createSpy('three');

  one('foo');
  two();
  three();
  one('bar');

  const expectedCallOrder = [
    one.calls.all()[0],
    two.calls.all()[0],
    three.calls.all()[0],
    one.calls.all()[1],
  ];

  expect(expectedCallOrder[0].args).toEqual(['foo']);
  expect(expectedCallOrder[3].args).toEqual(['bar']);

  const actualCallSeq = expectedCallOrder.map(c => c.invocationOrder);

  for (let i = 1; i < actualCallSeq.length; i++) {
    expect(actualCallSeq[i]).toBeGreaterThan(actualCallSeq[i - 1]);
  }
});
```

To be clear, I don't think that spec is good. I don't like the way it reads, I don't like the failure messages, and it's not what I'd write. But it does show that the order-tracking capability is there. Here's how I'd actually solve the problem with Jasmine's current feature set:

```
it('calls in the right order', function() {
  const calls = [];
  const one = arg => calls.push('one:' + arg);
  const two = () => calls.push('two');
  const three = () => calls.push('three');
  /* Or like this, if spy functionality is needed:

     const one = jasmine.createSpy('one')
       .and.callFake(arg => calls.push('one:' + arg));
  */

  one('foo');
  two();
  three();
  one('bar');

  expect(calls).toEqual(['one:foo', 'two', 'three', 'one:bar']);
});
```


Is it perfect? No. But I think it's reasonably clear, and when the calls are out of order it fails in a way that's easy to understand. That's the bar that any built-in feature needs to clear.

**Comment by ajvincent** [comment]
Sounds like this issue is DOA...
