### ISSUE TITLE
Issues with Symbol key comparisons in `toEqual` in Jasmine 4.1.0

### ISSUE THREAD

**Issue by ystros** [jasmine/jasmine#1966]
We (myself and @aramprice) ran into a couple issues with the changes to the `toEqual` matcher from https://github.com/jasmine/jasmine/pull/1879. That PR updated `toEqual` to start considering `Symbol` keys when comparing two objects.

This introduces:
* Confusing error messages when objects differ by just a `Symbol` key. The failure message does not include the `Symbol` keys, making the two printed objects look identical.
* When there is a Symbol key added to an array object, this causes an exception within the [MatcherUtil.keys](https://github.com/jasmine/jasmine/blob/694375e4eaeb86c535aacb5c8cdbe91abcea2d59/src/core/matchers/matchersUtil.js#L549) method, because it attempts to run a regular expression on a symbol instead of a string.

We encountered this because we use `mobx`, which inserts `Symbol` keys into our objects. Because the error messages were not clear, it led to a lot of investigation into both how `mobx` works and how Jasmine is doing comparisons.

## Expected Behavior
It fails with a clear error message, e.g.:
```
1) test case behaves differently for arrays with symbol keys in 3.99.0 and 4.1
  Message:
    Expected [] with Symbol(obj) to equal [].

2) test case behaves differently for objects with symbol keys in 3.99.0 and 4.1
  Message:
    Expected Object({ value: 1, [Symbol(obj)]: 'obj' }) to equal Object({ value: 1 }).
```

## Current Behavior
It fails with error messages that do not mention `Symbol` keys.
```
1) test case behaves differently for arrays with symbol keys in 3.99.0 and 4.1
  Message:
    TypeError: Cannot convert a Symbol value to a string

2) test case behaves differently for objects with symbol keys in 3.99.0 and 4.1
  Message:
    Expected Object({ value: 1 }) to equal Object({ value: 1 }).
```

## Possible Solution
Print error messages closer to those described in "Expected Behavior."

## Suite that reproduces the behavior (for bugs)
```javascript
describe('test case', () => {
    it('behaves differently for arrays with symbol keys in 3.99.0 and 4.1', () => {
        const obj = [];
        obj[Symbol('obj')] = 'obj';

        expect(obj).toEqual([]);
    })

    it('behaves differently for objects with symbol keys in 3.99.0 and 4.1', () => {
        const obj = {
            value: 1,
            [Symbol('obj')]: 'obj'
        }
        expect(obj).toEqual({ value: 1 });
    })
})
```
## Context
We use `mobx` in our code base and many tests started to fail after upgrading from Jasmine 3.99.0 to 4.1.0.

## Your Environment

* Version used: 4.1.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 16.13.2
* Operating System and version (desktop or mobile): Mac OS

**Comment by sgravrock** [comment]
Thanks for the report. Would you mind testing the fix against your actual codebase before I release it? You should be able to `npm install --save-dev github:jasmine/jasmine` and run your tests as usual.

**Comment by aramprice** [comment]
This give a more scrutable error when `Symbol(...)` differs. Thanks for the quick turn around.

**Comment by sgravrock** [comment]
Thanks. I've released this and one other Symbol property bugfix in 4.1.1 just now.

**Comment by aramprice** [comment]
Thanks for the update. We'll get to slogging through the `Symbol` related errors in our `mobx` comparisons 😞

**Comment by sgravrock** [comment]
Do you consider those errors to be correct failures? To put it in different terms, does it make sense to think of the Symbol properties as part of the object's value? Or are they irrelevant noise from the perspective of your specs?

The more I look into how Symbol properties are being used, the more I suspect that there might not be one right answer to whether or not they should be included in equality comparisons.

**Comment by aramprice** [comment]
The error messages with https://github.com/jasmine/jasmine/commit/9a27407d35c0d66389fbe4a86d83eeca54ed5303 were still fairly undecipherable though I suspect that this has more to do with MOBX.

Example Error Output 
```javascript
// spec snippet
      expect(product.stagedDependsOn).toEqual([]);
```

```
11) Product .fromPendingChanges returns a product which looks like the staged product
  Message:
    Expected object not to have properties
        Symbol(mobx administration): ObservableArrayAdministration({ owned: false, values: [ Symbol(mobx administration): <circular reference: Object> ], proxy: [ Symbol(mobx administration): <circular reference: Object> ], lastKnownLength: 0, atom: Product@4280.stagedDependsOn, enhancer: Function })
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:55485/__spec__/webpack:/react-ui/ui/spec/app/models/product_spec.js:657:1)
        at <Jasmine>
  Message:
    Expected object not to have properties
        Symbol(mobx administration): ObservableArrayAdministration({ owned: false, values: [ Symbol(mobx administration): <circular reference: Object> ], proxy: [ Symbol(mobx administration): <circular reference: Object> ], lastKnownLength: 0, atom: Product@4280.deployedDependsOn, enhancer: Function })
```

It may also be worth noting that in our code base with the commit https://github.com/jasmine/jasmine/commit/9a27407d35c0d66389fbe4a86d83eeca54ed5303 I still saw `TypeError: Cannot convert a Symbol value to a string`

```javascript
//spec snippet
      expect(productCollection.filter(byOs).products).toEqual([productA, productB]);
```
```
19) ProductCollection filter returns a ProductCollection filtered according to a predicate function
  Message:
    TypeError: Cannot convert a Symbol value to a string
  Stack:
        at RegExp.test (<anonymous>)
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:55365/__spec__/webpack:/react-ui/ui/spec/app/models/product_collection_spec.js:290:1)
        at <Jasmine>
```

At the same commit sha as above there were also cases where the output of `toEqual()` appeared to lack info about what was actually different as in this example

```javascript
//spec snippet
      expect(stemcellStatus.selectedStemcells).toEqual([
        {
          version: '1234.2',
          os: 'ubuntu-trusty',
        },
      ]);
```

```
17) StemcellStatus properities has the required properties
  Message:
    Expected [ Object({ version: <getter>, os: <getter> }) ] to equal [ Object({ version: '1234.2', os: 'ubuntu-trusty' }) ].
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:55365/__spec__/webpack:/react-ui/ui/spec/app/models/stemcell_status_spec.js:52:1)
        at <Jasmine>
```

Here are the `package.json` deps at the point I saw the errors above:
```
{
  "dependencies": {
    "babel-loader": "^8.2.4",
    "buffer": "^6.0.3",
    "mobx": "^5.15.7",
    "mobx-react": "^5.4.3",
    "node-polyglot": "^2.3.0",
    "path-browserify": "^1.0.1",
    "pluralize": "^8.0.0",
    "qs": "^6.9.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-hot-loader": "^4.12.11",
    "react-router-dom": "^4.3.1",
    "source-map-support": "^0.5.21"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.17.2",
    "@babel/plugin-syntax-flow": "^7.14.5",
    "@babel/plugin-transform-react-inline-elements": "^7.16.0",
    "@babel/plugin-transform-react-jsx": "^7.14.9",
    "@babel/plugin-transform-runtime": "^7.17.0",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-flow": "^7.16.7",
    "@babel/preset-react": "^7.16.7",
    "@babel/register": "^7.17.0",
    "babel-plugin-react-css-modules": "^5.2.6",
    "babel-polyfill": "^6.26.0",
    "buffer": "^6.0.3",
    "child-process-promise": "^2.2.1",
    "classnames": "^2.2.6",
    "compression-webpack-plugin": "^9.2.0",
    "css-loader": "^3.2.0",
    "del": "^6.0.0",
    "empty": "^0.10.1",
    "eslint": "^8.12.0",
    "eslint-config-prettier": "^8.4.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-filenames": "^1.2.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-jasmine": "^4.1.3",
    "eslint-plugin-json": "^3.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-you-dont-need-lodash-underscore": "^6.12.0",
    "event-source-polyfill": "^1.0.25",
    "favicons": "^6.2.2",
    "favicons-webpack-plugin": "^5.0.2",
    "file-loader": "^6.2.0",
    "flow-bin": "^0.152.0",
    "flow-typed": "^2.4.0",
    "html-webpack-plugin": "^5.5.0",
    "ignore-styles": "^5.0.1",
    "iso-morphic-style-loader": "^2.0.1",
    "jasmine": "^4.1.0",
    "jasmine-browser-runner": "^1.0.0",
    "jasmine_dom_matchers": "^1.4.0",
    "jquery": "^3.2.1",
    "mini-css-extract-plugin": "^2.5.3",
    "minimist": "^1.2.6",
    "node-sass": "^6.0.1",
    "pivotal-ui": "^17.2.3",
    "portastic": "^1.0.1",
    "postcss": "^8.3.3",
    "postcss-scss": "^4.0.3",
    "prettier": "^2.6.1",
    "puppeteer": "^13.5.2",
    "require-dir": "^1.2.0",
    "run-sequence": "^2.2.0",
    "sass-loader": "^12.6.0",
    "svg-url-loader": "^7.1.1",
    "webpack": "^5.71.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4",
    "webpack-manifest-plugin": "^5.0.0",
    "webpack-stream": "^7.0.0",
    "whatwg-fetch": "^3.0.0"
  },
  "resolutions": {
    "jasmine-core": "github:jasmine/jasmine#9a27407"
  }
}
```

**Comment by aramprice** [comment]
Fortunately (I think?) with the changes from https://github.com/jasmine/jasmine/pull/1963 being pulled into 4.1.1 the new-to-our-codebase errors with `toEqual()` appear to be gone.

¯\_(ツ)_/¯

**Comment by sgravrock** [comment]
If I understand correctly, it sounds like mobx marks the Symbol properties in question as non-enumerable. I'm hoping and mostly expecting that that will be the case for most libraries, in which case #1963 (thanks @suke) should largely solve the problem of Symbol properties being relevant only some of the time.

> ```
> 
> It may also be worth noting that in our code base with the commit [9a27407](https://github.com/jasmine/jasmine/commit/9a27407d35c0d66389fbe4a86d83eeca54ed5303) I still saw `TypeError: Cannot convert a Symbol value to a string`
> 
> ```js
> //spec snippet
>       expect(productCollection.filter(byOs).products).toEqual([productA, productB]);
> ```
> 
> ```
> 19) ProductCollection filter returns a ProductCollection filtered according to a predicate function
>   Message:
>     TypeError: Cannot convert a Symbol value to a string
>   Stack:
>         at RegExp.test (<anonymous>)
>         at <Jasmine>
>         at UserContext.<anonymous> (http://localhost:55365/__spec__/webpack:/react-ui/ui/spec/app/models/product_collection_spec.js:290:1)
>         at <Jasmine>
> ```

I'm not sure how to reproduce that. Any chance you could put together a minimal repro for that and log a new issue? Failing that, could you provide an updated stack trace after breaking Jasmine's stack trace filtering as follows?

```
diff --git a/lib/jasmine-core/jasmine.js b/lib/jasmine-core/jasmine.js
index 18d6eb56..b40d76e7 100644
--- a/lib/jasmine-core/jasmine.js
+++ b/lib/jasmine-core/jasmine.js
@@ -3895,11 +3895,7 @@ getJasmineRequireObj().ExceptionFormatter = function(j$) {
           stackTrace.style === 'webkit' ? '<Jasmine>' : '    at <Jasmine>';
 
       stackTrace.frames.forEach(function(frame) {
-        if (frame.file !== jasmineFile) {
           result.push(frame.raw);
-        } else if (result[result.length - 1] !== jasmineMarker) {
-          result.push(jasmineMarker);
-        }
       });
 
       return result;
```


> 
> At the same commit sha as above there were also cases where the output of `toEqual()` appeared to lack info about what was actually different as in this example
> 
> ```js
> //spec snippet
>       expect(stemcellStatus.selectedStemcells).toEqual([
>         {
>           version: '1234.2',
>           os: 'ubuntu-trusty',
>         },
>       ]);
> ```
> 
> ```
> 17) StemcellStatus properities has the required properties
>   Message:
>     Expected [ Object({ version: <getter>, os: <getter> }) ] to equal [ Object({ version: '1234.2', os: 'ubuntu-trusty' }) ].
>   Stack:
>         at <Jasmine>
>         at UserContext.<anonymous> (http://localhost:55365/__spec__/webpack:/react-ui/ui/spec/app/models/stemcell_status_spec.js:52:1)
>         at <Jasmine>
> ```

Do you have any [custom equality testers](https://jasmine.github.io/tutorials/custom_equality) that apply to either side of the comparison? That's the only reason I can think of why Jasmine would pretty-print both sides in their entirety rather than showing a diff.

The `<getter>` output is IMO a bug, albeit quite a venerable one, dating all the way back to version 0.10.1. But you wouldn't be hitting that in the first place if the objects were being diffed.

**Comment by aramprice** [comment]
🤔 Welp, I think that my set of local `node_modules/` may have been in an unexpected / no-longer-reproducible state. I'm not able to reproduce the `TypeError: Cannot convert a Symbol value to a string`. My apologies, I was hoping I could assemble something for you all to chew on.


I was able to get the following spec to fail in _our_ react app's setup:
```javascript
import {decorate, observable, runInAction} from 'mobx';

class ThingCollection {
    @observable thingsAnnotated;
    thingsNonAnnotated;

    constructor(annotatedThings, nonAnnotatedThings) {
        runInAction(() => {
            this.thingsAnnotated = annotatedThings;
            this.thingsNonAnnotated = nonAnnotatedThings;
        });
    }
}
decorate(ThingCollection, {
    thingsNonAnnotated: observable,
});

describe('ThingCollection', () => {
    let thingOne, thingTwo, thingCollection;

    beforeEach(() => {
        thingOne = {title: 'First Thing'};
        thingTwo = {title: 'Second Thing'};
        thingCollection = new ThingCollection([thingOne, thingTwo], [thingTwo, thingOne]);
    });

    it('fails comparing an ANNOTATED mobx attribute', () => {
        expect(thingCollection.thingsAnnotated).toEqual([thingOne, thingTwo]);
    });

    it('fails comparing a NON-ANNOTATED mobx attribute', () => {
        expect(thingCollection.thingsNonAnnotated).toEqual([thingTwo, thingOne]);
    });
});
```

These fail with the following output:
```
jasmine-browser-runner runSpecs --config=spec/support/jasmine-browser.json
Jasmine server is running here: http://localhost:55290
Jasmine tests are here:         ./webpack_assets
Source files are here:          ./app
Running tests in the browser...
Randomized with seed 87663
Started
FF

Failures:
1) ThingCollection fails comparing a NON-ANNOTATED mobx attribute
  Message:
    Expected $[0] not to have properties
        Symbol(mobx administration): ObservableObjectAdministration({ target: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), values: Map( [ 'title', ThingCollection@50.thingsNonAnnotated[..].title[Second Thing] ] ), name: 'ThingCollection@50.thingsNonAnnotated[..]', defaultEnhancer: Function, keysAtom: ThingCollection@50.thingsNonAnnotated[..].keys, proxy: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), pendingKeys: Map( [ 'asymmetricMatch', ThingCollection@50.thingsNonAnnotated[..].asymmetricMatch?[false] ], [ Symbol(Symbol.toStringTag), ThingCollection@50.thingsNonAnnotated[..].Symbol(Symbol.toStringTag)?[false] ], [ 'jasmineToString', ThingCollection@50.thingsNonAnnotated[..].jasmineToString?[false] ], [ 'and', ThingCollection@50.thingsNonAnnotated[..].and?[false] ], [ 'toString', ThingCollection@50.thingsNonAnnotated[..].toString?[false] ], [ '__lookupGetter__', ThingCollection@50.thingsNonAnnotated[..].__lookupGetter__?[false] ] ) })
    Expected $[1] not to have properties
        Symbol(mobx administration): ObservableObjectAdministration({ target: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), values: Map( [ 'title', ThingCollection@50.thingsNonAnnotated[..].title[First Thing] ] ), name: 'ThingCollection@50.thingsNonAnnotated[..]', defaultEnhancer: Function, keysAtom: ThingCollection@50.thingsNonAnnotated[..].keys, proxy: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), pendingKeys: Map( [ 'asymmetricMatch', ThingCollection@50.thingsNonAnnotated[..].asymmetricMatch?[false] ], [ Symbol(Symbol.toStringTag), ThingCollection@50.thingsNonAnnotated[..].Symbol(Symbol.toStringTag)?[false] ], [ 'jasmineToString', ThingCollection@50.thingsNonAnnotated[..].jasmineToString?[false] ], [ 'and', ThingCollection@50.thingsNonAnnotated[..].and?[false] ], [ 'toString', ThingCollection@50.thingsNonAnnotated[..].toString?[false] ], [ '__lookupGetter__', ThingCollection@50.thingsNonAnnotated[..].__lookupGetter__?[false] ] ) })
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:55290/__spec__/webpack:/react-ui/spec/reproduction_spec.js:32:1)
        at <Jasmine>

2) ThingCollection fails comparing an ANNOTATED mobx attribute
  Message:
    Expected $[0] not to have properties
        Symbol(mobx administration): ObservableObjectAdministration({ target: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), values: Map( [ 'title', ThingCollection@51.thingsAnnotated[..].title[First Thing] ] ), name: 'ThingCollection@51.thingsAnnotated[..]', defaultEnhancer: Function, keysAtom: ThingCollection@51.thingsAnnotated[..].keys, proxy: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), pendingKeys: Map( [ 'asymmetricMatch', ThingCollection@51.thingsAnnotated[..].asymmetricMatch?[false] ], [ Symbol(Symbol.toStringTag), ThingCollection@51.thingsAnnotated[..].Symbol(Symbol.toStringTag)?[false] ], [ 'jasmineToString', ThingCollection@51.thingsAnnotated[..].jasmineToString?[false] ], [ 'and', ThingCollection@51.thingsAnnotated[..].and?[false] ], [ 'toString', ThingCollection@51.thingsAnnotated[..].toString?[false] ], [ '__lookupGetter__', ThingCollection@51.thingsAnnotated[..].__lookupGetter__?[false] ] ) })
    Expected $[1] not to have properties
        Symbol(mobx administration): ObservableObjectAdministration({ target: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), values: Map( [ 'title', ThingCollection@51.thingsAnnotated[..].title[Second Thing] ] ), name: 'ThingCollection@51.thingsAnnotated[..]', defaultEnhancer: Function, keysAtom: ThingCollection@51.thingsAnnotated[..].keys, proxy: Object({ title: <getter>, Symbol(mobx administration): <circular reference: Object> }), pendingKeys: Map( [ 'asymmetricMatch', ThingCollection@51.thingsAnnotated[..].asymmetricMatch?[false] ], [ Symbol(Symbol.toStringTag), ThingCollection@51.thingsAnnotated[..].Symbol(Symbol.toStringTag)?[false] ], [ 'jasmineToString', ThingCollection@51.thingsAnnotated[..].jasmineToString?[false] ], [ 'and', ThingCollection@51.thingsAnnotated[..].and?[false] ], [ 'toString', ThingCollection@51.thingsAnnotated[..].toString?[false] ], [ '__lookupGetter__', ThingCollection@51.thingsAnnotated[..].__lookupGetter__?[false] ] ) })
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:55290/__spec__/webpack:/react-ui/spec/reproduction_spec.js:28:1)
        at <Jasmine>

Ran 2 of 722 specs
2 specs, 2 failures
Finished in 1.277 seconds
Randomized with seed 87663 (jasmine-browser-runner runSpecs --seed=87663)
```

Our setup is uses `jasmine-browser-runner`, and the app and specs are assembled via `webpack`, all of which I'm fairly new to, so I'm not certain how to construct a "plain jasmine" test case.

When I tried running via `npm` using a stripped down `package.json` I ran into a bunch of errors with the annotation-style `mobx` integration, and then when I used the `mobx` non-annotation style (e.g. `decorate(ThingCollection, ...)`) the non-annotated test passed, though both fail in our existing setup.

Not sure this is worth pursuing further, though I'd be happy to provide more details if you want to keep digging.

**Comment by aramprice** [comment]
Maybe we can convince @ragaskar to come back and fix the `<getter>` output issue?

**Comment by sgravrock** [comment]
Thanks for the reduced mobx repro. I think that's enough for me to go on.

I'll probably just go ahead and remove the `<getter>` stuff. Not calling getters was a reasonable call back in 2009, but we've been calling them for ages now in the equality and diff-building code and nobody's complained.

**Comment by sgravrock** [comment]
@aramprice I was able to get that last example running. But it fails with no useful output on 4.1.0 and passes on 4.1.1. The only ways I've been able to reproduce your failure output are by using an intermediate commit like 9a27407 or making the property enumerable.

Could you check whether the symbol property is enumerable, e.g.:

```
const o = thingCollection.thingsAnnotated[0];

for (const sym of Object.getOwnPropertySymbols(o)) {
    expect(Object.getOwnPropertyDescriptor(o, sym).enumerable).withContext(sym.toString()).toBeFalse();
}
```
