### ISSUE TITLE
spyOn failing to stub method invocation

### ISSUE THREAD

**Issue by MikepdXRider** [jasmine/jasmine#1967]
## Expected Behavior
- Failing tests to pass in repro codepen.

## Current Behavior
- Synchronous call test fails. 
- spyOn does not stub/catch invoked methods calls within nested anonymous functions. 

## Possible Solution
- N/A: Hoping for a solution here. 

## Suite that reproduces the behavior (for bugs)
- Methods invoked nested in anonymous functions: https://codepen.io/mikepdxrider/pen/JjpGpKv

## Your Environment

* Version used: 2.0 - 3^.6.X
* Link to your project: https://codepen.io/mikepdxrider/pen/JjpGpKv

**Comment by sgravrock** [comment]
One of those codepen links is 404, but I see from the other one that you're trying to run an async/await spec on a version of Jasmine that's far too old for that (2.0, released in 2013). In effect, you intend that the spec is async but the antique Jasmine version you're using thinks it's synchronous. That would cause Jasmine to tear down the spies and move on to the next spec before the callback runs.

Try upgrading to 4.1.0. There's a good chance that that'll fix the problem. If it doesn't, there's likely some other reason why the spec is signalling completion before the callback runs. See [the async testing tutorial](https://jasmine.github.io/tutorials/async) and the async section of [the FAQ](https://jasmine.github.io/pages/faq.html), particularly [this question](https://jasmine.github.io/pages/faq.html#callback-assertions) which deals with reliably testing callbacks.

**Comment by MikepdXRider** [comment]
Hey @sgravrock! Thanks for responding! Sorry about the broken link. The version you were able to access actually wasn't functional. The updated link offers a code example that operates as expected, and highlights the issue test behavior. 

The methods are not declared using async/await. Nor do they explicitly return a promise. We also don't explicitly call these methods asynchronously. We actually expect the synchronous test to pass in this case, is that an invalid expectation? The issue is also occurring in a 3.8.x version of jasmine.

**Comment by sgravrock** [comment]
Yes, it's an invalid expectation. You need to use an asynchronous spec to test asynchronous behavior. And even though you've tried to mock out some of the async aspects of your code, the use of promises makes it inherently asynchronous. Based on a quick skim, it looks like you've got a  number of other async bugs, but the general complexity of it and the multiple layers of spies calling other spies makes it hard to tell what's actually relevant.

You should debug your code to verify that everything is working the way you expect, you aren't getting any un-intended errors, and especially that the code that calls the spy is actually running before the code that expects the spy to have been called.

Also please upgrade to Jasmine 4.1.0. We don't generally support older versions, and by sticking with older versions you're missing out on async-related bugfixes and featues that help diagnose buggy async specs.
