### ISSUE TITLE
Uncaught (in promise) Type Error: Cannot read properties of null (reading 'jasmineMessage')

### ISSUE THREAD

**Issue by plarner30** [jasmine/jasmine#1974]
Jasmine: v4.2.0

Apologies for cross posting I am also asking about this in karma-jasmine but I still have no clue where this problem originates from.
https://github.com/karma-runner/karma-jasmine/issues/323

For some reason any async handling in beforeEach is completely broken on my setup.

Ive narrowed this down to any use of the line `beforeEach(async () => {})`,

`beforeEach(() => {})` is just fine, 

Incidentally `it('test', async () => {});` and returning a promise explicitly also triggers the error.

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'jasmineMessage')
at next (jasmine.js:8036:62)
at jasmine.js:7941:9

The relevant lines from jasmine in the call stack above are
https://github.com/jasmine/jasmine/blob/68eaa64c31d44cd9daf7c991857ff8d36818f25c/lib/jasmine-core/jasmine.js#L8036
https://github.com/jasmine/jasmine/blob/68eaa64c31d44cd9daf7c991857ff8d36818f25c/lib/jasmine-core/jasmine.js#L7941

I have found changing this line

https://github.com/jasmine/jasmine/blob/68eaa64c31d44cd9daf7c991857ff8d36818f25c/lib/jasmine-core/jasmine.js#L8035

to 

`if (typeof err !== 'undefined' && err !== null) {`

seems to fix the problem and all my tests seem to run normally

**Comment by sgravrock** [comment]
> For some reason any async handling in beforeEach is completely broken on my setup.

[...]

> Incidentally it('test', async () => {}); and returning a promise explicitly also triggers the error.

Both of those things work in general, so there's probably something about your code or your setup that's important to reproducing the problem. If you can provide a repo with a complete, self-contained, running test suite that reproduces the problem, I can investigate further.

**Comment by sgravrock** [comment]
I get a couple of `Cannot find module 'jest-jasmine2/build/jasmineAsyncInstall.js'` errors, which isn't what you reported but I think it does show the root cause. You're trying to use both Jest and Jasmine in the same test suite. That won't work. The error you saw could be the result of pieces of Jest and Jasmine trying to call each other. 

You'll need to choose which testing framework you want to use, and then remove either all of the Jest packages or all of the Jasmine packages.

**Comment by plarner30** [comment]
Thanks @sgravrock , removing all jest related dependencies and the jasmineAsyncInstall, plus installing jasmine types did the trick (strangely that jasmineAsyncInstall was available on my local)
