### ISSUE TITLE
Report is not scrollable when you have lots of (failed) Tests

### ISSUE THREAD

**Issue by M6Ka7** [jasmine/jasmine#1978]
## Are you creating an issue in the correct repository?

Im setting up Karma / Jasmin to my project and I'm getting failed specs to be fixed as expected.
But the list (Failures and Summary) is not scrollable.
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/97874931/179162733-2c07d050-4817-4d32-9cc1-8f15ce310ab5.png">

Tried to push the fix to a new Branch but failed due to missing rights :-)

## Expected Behavior
Should be scrollable

## Current Behavior
Is not scrollable

## Possible Solution
Added those lines 
```
.jasmine-failures {
  overflow: scroll;
  height: 80vw;
}
.jasmine-summary {
  overflow: scroll;
  height: 80vw;
}
```
to `lib\jasmine-core\jasmine.css` after line `#245`

After adding those lines the yellow scrollbar apears as expected

## Your Environment
* Version used: 4.2.0
* Environment name and version : Chrome 103

**Comment by sgravrock** [comment]
The whole page is supposed to be scrollable, not just certain regions of it. I can't reproduce this based on the information you've provided. But my guess is that something in your CSS (or less likely in some specific Karma component you're using) is preventing the page from scrolling e.g. by setting `overflow: hidden` on the body element.

**Comment by M6Ka7** [comment]
Maybe it is because jasmin is included as iframe of karma. Or (a combination) of 4K - Screen and virtual monitors. Yes, there is a scrollbar, but I can only scroll two or three isues wide ...

**Comment by sgravrock** [comment]
There's not enough information here for me to reproduce the problem. If you set up a repo with a [minimal, complete, working example](https://stackoverflow.com/help/minimal-reproducible-example) I can take another look. Otherwise you're probably on your own.
