### ISSUE TITLE
How to unit test a Custom Matcher failure message in jasmine v4?

### ISSUE THREAD

**Issue by greyepoxy** [jasmine/jasmine#1980]
## Suite that reproduces the behavior

Say we have a customer matcher like the one below (this is a toy example in TypeScript, not our real code).

```
function toBeCoolFactory(util: jasmine.MatchersUtil): jasmine.CustomMatcher {
  return {
    compare: (actual: { cool?: boolean }) => {

      if (actual.cool === undefined || actual.cool === false) {
        return { pass: false, message: `Expected '${util.pp(actual)}' to be cool` };
      }

      return { pass: true };
    }
  };
}
```

In Jasmine v2 / v3 we would unit test the matcher by creating the custom matcher using the static `jasmine.matchersUtil` (which we learned how to do from this old issue https://github.com/jasmine/jasmine/issues/1024).

```
describe(`test if cool matcher`, () => {
  it(`should return a error message saying the object is not cool`, () => {
    const matcher = toBeCoolFactory(jasmine.matchersUtil);
    const { pass, message } = matcher.compare({});

    expect(pass).toBe(false);
    expect(message).toBe(`Expected 'Object({  })' to be cool`);
  });
});
```

## Current Behavior

Running this test in jasmine v3.99.0 we get the following deprecation warning
```
DEPRECATION: jasmine.matchersUtil is deprecated and will be removed in a future release. Use the instance passed to the matcher factory or the asymmetric equality tester's `asymmetricMatch` method instead. See <https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#static-utils> for details. (in spec: JasmineMatchers test if cool matcher should return a error message saying the object is not cool)
    at <Jasmine>
    at UserContext.<anonymous> (\JasmineMatchers.test.js)
    at <Jasmine>
Note: This message will be shown only once. Set the verboseDeprecations config property to true to see every occurrence.
```

Running in jasmine v4.4.0 results in a runtime error
```
Failures:
1) JasmineMatchers test if cool matcher should return a error message saying the object is not cool
  Message:
    TypeError: Cannot read properties of undefined (reading 'pp')
```

## Context

With the static `jasmine.matchersUtil.pp` function being deprecated I am looking for guidance on how to write tests for custom matchers where we want to assert on the actual error message like above. We have 100s of such tests for a variety of custom matchers in my company. 

I looked at how the core matchers tests were written (for example [toEqualSpec.js](https://github.com/jasmine/jasmine/blob/main/spec/core/matchers/toEqualSpec.js)) and they appear to be creating a `new MatchersUtil` which the documentation says not to do [here](https://jasmine.github.io/api/4.4/MatchersUtil.html). 

> Class: MatchersUtil
> MatchersUtil
> Utilities for use in implementing matchers.
> Note: Do not construct this directly. Jasmine will construct one and pass it to matchers and asymmetric equality testers.

The core matchers tests are also using a method to create the pretty print method that is not exposed `jasmineUnderTest.makePrettyPrinter()`.

## Environment

* Version used: Jasmine v3.99.0 and v4.4.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs v16.16.0
* Operating System and version (desktop or mobile): Windows 10 Enterprise 20H2 19042.1889
* Link to your project: n/a

**Comment by sgravrock** [comment]
The short answer is that there isn't currently a good way to test a custom matcher in integration with MatchersUtil and pp. If you're trying to unblock a migration to 4.x as it exists today, I think your best option is to use a mock object in place of `MatchersUtil`.

The reason there's no longer a static `MatchersUtil` or `pp` is that both of them now carry per-spec state. So they're only available as injected dependencies, which solves a couple of nasty problems but leaves no good way to test that a custom matcher integrates with them correctly.

I'm open to suggestions for a new API that would facilitate that kind of test. I think we'd want something that allows users to verify that their matchers work with things like custom equality testers and custom object formatters without having to know the details of how those things get provided to `MatchersUtil` and `pp`.

**Comment by greyepoxy** [comment]
Thanks for replying @sgravrock! I was able to unblock my companies upgrade to jasmine v4 with the mocking approach you mentioned. Not ideal, but it worked.

I sadly don't have a ton of time to dig into this but one idea I had based around what I have seen looking around online. I see some folks write code like below to test custom matchers error messages.

```
it(`should return a error message saying the object is not cool`, () => {
  expect(() => {
    expect({}).toBeCool();
  }).toThrowError(`Expected 'Object({  })' to be cool`);
});
```

This works if you update the Custom Matcher to throw an error instead of returning an error message object (which it appears like some people do today to work around this problem). 

Not sure if it is actually feasible to do this but I think ideally like you said not having to worry about the `MatchersUtil` at all would be ideal. Well unless I am testing something specific with how a custom matcher behaves with a custom equality tester.

**Comment by sgravrock** [comment]
The one gotcha with matchers that throw exceptions when they fail is that they don't work with `.not` unless they have a `negativeCompare` method. `.not` inverts returned matcher results but not thrown exceptions, since Jasmine has no way of knowing whether a thrown exception indicates a matcher failure or something else.
