### ISSUE TITLE
How to spy on environment file?

### ISSUE THREAD

**Issue by Shradhanjalisahu** [jasmine/jasmine#1984]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- If you have an issue with TypeScript typings, start a discussion at
  [DefinitelyTpyed](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/new?category=issues-with-a-types-package)
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine browser runner](https://github.com/jasmine/jasmine-browser/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sgravrock** [comment]
Your question is unclear. What behavior do you want to test? If you're trying to verify that `prepareHeader` returns the expected value when the object is in a particular state, then:

1. Create an instance of `IframeService`.
2. Call `prepareHeader`.
3. Assert that the return value is what you expected. If you don't know how to do that, see <https://jasmine.github.io/tutorials/your_first_suite>.

If you're trying to test that `prepareHeader` interacts with Angular or your other Angular objects in a particular way, then your question is really about Angular. You should ask it in an Angular forum. There's a list of those at <https://angular.io/>, in the footer under "help".

**Comment by sgravrock** [comment]
Please read [my comment](https://github.com/jasmine/jasmine/issues/1985#issuecomment-1295906216) on your other issue.
