### ISSUE TITLE
I need help how to test   prepareHeader() 

### ISSUE THREAD

**Issue by Shradhanjalisahu** [jasmine/jasmine#1985]
I want to test Service in angular using Jasmin.In below i attached my service code.

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
@Injectable()
export class IframeService {
    locale!: string;
    constructor(private http: HttpClient) { }

    exchanges?: any[];
    exchangeNames?: any = {};

    // Exchange States
    selectedExchange: any = {};
    enableAuthWindow = false;
    tracking = false;
    completed = false;
    exchangeAccounts: any[] = [];

    connected = false;
    selectedExchangeAccount: any;
    authorizing = false;
    processing = false;
    resend = false;
    twoFactorAuth: string = '';
    trackingId: string = '';

    error: any;

    prepareHeader() {
        if (!this.locale) {
            this.locale  = 'en';
        }
        const header = {
            'x-api-key': environment.api.key,
            'client-id': environment.api.clientId,
            'locale': this.locale,
            'Content-type': 'application/json'
        };
        return header;
    }

    generatePaymentAddress(transactionId: string, currency: string): Observable<any> {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/currencies/${currency}`;
        const header = this.prepareHeader();
        return this.http.post(url, null, {headers: header});
    }

    confirmPayment(transactionId: string): Observable<any> {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/statuses/CONFIRMED`;
        const header = this.prepareHeader();
        return this.http.put(url, null, {headers: header});
    }
    

    getCurrencies() {
        const url = `${environment.api.basePayment}/v1/currencies?type=CRYPTO`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header})
    }

    getExchanges() {
        const url = `${environment.api.basePayment}/v1/exchanges`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header})       
    }

    getPaymentInfo(transactionId: string) {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/short`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header})      
    }

    getTranslations(prefix: string) {
        const url = `${environment.api.baseTranslation}/v1/translations/prefixes/${prefix}`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header});
    }

    getPaymentStatus(transactionId: string) {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/status`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header});
    }

    sendPayment(transactionId: string, exchange: string, account: string, currency: string, trackingId?: string, twoFactorAuth?: string) {
        const data: any = {};
        if (twoFactorAuth) {
            data['twoFactorAuth'] = twoFactorAuth;
            if (trackingId) {
                data['trackingId'] = trackingId;
            }
        }
       
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/exchanges/${exchange}/accounts/${account}/currencies/${currency}`;
        const header = this.prepareHeader();
        return this.http.post(url, data, {headers: header});
    }

    processAuth(transactionId: string, exchange: string, authCode: string) {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/exchanges/${exchange}/authcodes/${authCode}`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header});
    }

    getUserExchangeAccounts(transactionId: string, exchange: string) {
        const url = `${environment.api.basePayment}/v1/payments/${transactionId}/exchanges/${exchange}/accounts`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header});
    }

    getExchangeRate(exchange: string, fromCurrency: string, toCurrency: string) {
        const url = `${environment.api.basePayment}/v1/exchanges/${exchange}/rates/${fromCurrency}/${toCurrency}`;
        const header = this.prepareHeader();
        return this.http.get(url, {headers: header});
    }
}

**Comment by sgravrock** [comment]
Your question is unclear. What behavior do you want to test? If you're trying to verify that `prepareHeader` returns the expected value when the object is in a particular state, then:

1. Create an instance of `IframeService`.
2. Call `prepareHeader`.
3. Assert that the return value is what you expected. If you don't know how to do that, see <https://jasmine.github.io/tutorials/your_first_suite>.

If you're trying to test that `prepareHeader` interacts with Angular or your other Angular objects in a particular way, then your question is really about Angular. You should ask it in an Angular forum. There's a list of those at <https://angular.io/>, in the footer under "help".

**Comment by sgravrock** [comment]
You've logged two very vague issues in a row. In both cases you didn't fill out the issue template. Please stop doing that. It's OK to ask strangers on the Internet to spend their free time helping you. But you need to do your part by answering the questions in the issue template and clearly describing your problem.

If you create any more issues in the future, please:

* Fill out the issue template. Don't delete it like you did here or leave it blank like in your previous issue.
* Explain your problem in enough detail that someone who doesn't know anything about your project can understand it. Be specific about what you're trying to do. Don't assume that the reader will know anything about your codebase. For instance, don't assume that anyone knows what you mean by "environment file".
* Include a code sample that contains enough information to show the problem. Remove any unnecessary code. Remove libraries if at all possible, especially Angular. (If you can't remove Angular, your question is probably about Angular and should be asked in an Angular forum.) See <https://stackoverflow.com/help/minimal-reproducible-example> for more information.
