### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by gerardcarbo** [jasmine/jasmine#1988]
When testing angular with karma and setting jasmine seed in karma.config.js:

```
...
client:{
      jasmine: {
        seed: 4321,
        ...
      }
```

When tests are finished it throws 'Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node''
This happens because you are trying to add the port number to the report '...randomized with seed [4321]'

It could be fixed adding to jasmine-core/lib/jasmine-html.js 797:

```
    else if (typeof child === 'number') {
      el.appendChild(createTextNode(+child));
    }
```

**Comment by sgravrock** [comment]
This was fixed in jasmine-core 4.5.0.
