### ISSUE TITLE
Can I use Jasmine expect in cucumber project ?

### ISSUE THREAD

**Issue by rajivnw** [jasmine/jasmine#1989]
### Your question

I would like to use Jasmine expect in cucumber project. Reason is, I created test using webdriverio and cucumber project. WebDriverIo have its own expect but that stop the test execution once it fail (hard-assert). I would like to run all the steps and fail at the end (soft-assert).

I would like to override or would like to use Jasmine 
instead of WebDriverIO assert https://webdriver.io/docs/assertion 

### Example code that demonstrates the problem

```JavaScript
something Like
Jasmine.expect("").toBe("")
```

### jasmine-core version

latest

### Does the problem occur with the latest version of jasmine-core?

No

### Node.js or browser version

18

### Operating System

MAC

**Comment by sgravrock** [comment]
I don't think that's possible without major changes to both Jasmine and Cucumber. On the Jasmine side of things many aspects of matchers involve the currently executing spec. So the matcher system needs Jasmine to be not just present but actually running. On the other side, Cucumber would need a way for matchers to tell it about failures other than by throwing exceptions, and it would need to be able to report multiple expectation failures per test. I don't know for a fact that Cucumber doesn't have those features, but I've only ever seen them in testing frameworks that come with a built-in matcher system that supports multiple failures per test.
