### ISSUE TITLE
spyOnGlobalErrorsAsync has incorrect type signature

### ISSUE THREAD

**Issue by nbilyk** [jasmine/jasmine#1993]
### Steps to Reproduce

spyOnGlobalErrorsAsync

### Expected Behavior

The type definition for spyOnGlobalErrorsAsync should be:

```
function spyOnGlobalErrorsAsync(fn?: (globalErrorSpy: Spy<(error:Error)=>void>) => Promise<void>): Promise<void>

```

### Actual Behavior

```
function spyOnGlobalErrorsAsync(fn?: (globalErrorSpy: Error) => Promise<void>): Promise<void>
```

### Example code that reproduces the problem

```JavaScript
await jasmine.spyOnGlobalErrorsAsync(async (globalErrorSpy) => {
  // globalErrorSpy has incorrect type
}
```

### jasmine-core version

4.4.0

### Does the problem occur with the latest version of jasmine-core?

Yes

### Node.js or browser version

14.x

### Operating System

MacOS

**Comment by sgravrock** [comment]
As the [new issues page](https://github.com/jasmine/jasmine/issues/new/choose) says, please report problems with type definitions (or better yet, submit a PR) at DefinitelyTyped.
