### ISSUE TITLE
Is Web Browser Jasmine Exposing a Require Function?

### ISSUE THREAD

**Issue by leonardjaviniar** [jasmine/jasmine#1995]
### Your question

In the sample code below directly taken from the page [Using Jasmine in the browser](https://jasmine.github.io/setup/browser.html#using-jasmine-in-the-browser), I am wondering if this means that when available in the browser or as part of the app, there would be a global function `require` available in the browser:

### Example code that demonstrates the problem

```JavaScript
const path = require('path');
const jasmineBrowser = require('jasmine-browser-runner');

const config = require(path.resolve('spec/support/jasmine-browser.json'));
config.projectBaseDir = path.resolve('some/path');

jasmineBrowser.startServer(config, { port: 4321 });
```

### jasmine-core version

4.5.0

### Does the problem occur with the latest version of jasmine-core?

I haven't tried

### Node.js or browser version

node 16.2.0

### Operating System

Windows 10

**Comment by sgravrock** [comment]
No, Jasmine doesn't add a `require` function. The code that you quoted runs in Node.js. It starts the server that hosts the page, scripts, etc. that will run in the browser.

**Comment by leonardjaviniar** [comment]
I see, thanks for answering my question!
