### ISSUE TITLE
Uncaught Exception occurs for test that simulates error while using Stream class (Node v18 + Stream class)

### ISSUE THREAD

**Issue by qtphan734** [jasmine/jasmine#1996]
### Steps to Reproduce

While writing a test that simulates write stream error, jasmine reports an uncaught exception when it shouldn't have because the error was caught within the test. Test environment is `Node 18` and can only be reproduce in conjunction with using Node's `Stream` class.

Steps: 
1. Run the below example code while using Node 18.12.1

### Expected Behavior

1. Test to pass

### Actual Behavior

1. Test throws uncaught exception even though error got caught within test

### Example code that reproduces the problem

```JavaScript
fit('expect write() to fail writing', (done) => {
    const { Duplex } = require('stream');
    class TestStream extends Duplex {
        _write(chunk, encoding, callback) {
		try {
			throw new Error('Error');  // Mocking write throwing error
		} catch (error) {
			if (callback) {
				callback(error);
			}
		}
        }
    }
    const testStream = new TestStream();
    const writeAsync = async (data) => new Promise((resolve, reject) => {
	testStream.write(data, null, (err) => {
		if (err) {
			return reject(err);
		}
		return resolve();
	});
    });
    writeAsync(Buffer.from([0x00, 0x01, 0x02, 0x03])).catch((err) => {
	console.log('ERROR CAUGHT', err);
	expect(err).toEqual(new Error('Error'));
	done();
    });
});
```

### jasmine-core version

4.5.0

### Does the problem occur with the latest version of jasmine-core?

Yes

### Node.js or browser version

Node > 12 (Tested aginst Node 14, 18.12.1)

### Operating System

Windows 11, OSX, Linux

**Comment by sgravrock** [comment]
Jasmine only prepends the "Uncaught exception" message in response to Node's uncaughtException event. So that message is a reliable indication that *something* threw an uncaught exception, even if your code doesn't. In this case it looks like the Node stream is re-throwing the error. If I subscribe an error handler (e.g. `testStream.on('error', () => {});`) before the call to `writeAsync`, the failure goes away.
