### ISSUE TITLE
`toHaveBeenCalledWith()` on spy causes TypeScript error using `HTMLElement`'s `scrollTo` method

### ISSUE THREAD

**Issue by json-derulo** [jasmine/jasmine#2004]
### Steps to Reproduce

Stackblitz: https://stackblitz.com/edit/jasmine-testing-pqiumw?file=src%2Fscroll.spec.ts
Please note that the test is running and succeeding, but Intellisense shows an error. In a real world scenario, this results in a compile error.

### Expected Behavior

There is no TypeScript error

### Actual Behavior

There is a TypeScript error on the `toHaveBeenCalledWith()` function:

```
Expected 2 arguments, but got 1.
```

My IDE shows the following type for the `toHaveBeenCalledWith()` function:

```
jasmine.FunctionMatchers<{ (options?: ScrollToOptions | undefined): void; (x: number, y: number): void; } & { (options?: ScrollToOptions | undefined): void; (x: number, y: number): void; }>.toHaveBeenCalledWith(
  x: jasmine.Expected<number>,
  y: jasmine.Expected<number>): void
```

It seems to only pick up the index signature with the two numbers, and not the object notation.

### Example code that reproduces the problem

```JavaScript
// code
export function scroll(): void {
  window.scrollTo({ top: 0 });
}

// spec
describe('scroll', () => {
  it('should call the window scrollTo function', () => {
    const spy = spyOn(window, 'scrollTo');
    scroll();

    expect(spy).toHaveBeenCalledWith({ top: 0 });
  });
});
```

### Context

I want to test whether the `scrollTo` method of a DOM element is called with the right parameters.

See also: https://stackoverflow.com/q/65103183/5470544

### jasmine-core version

4.6.0

### Versions of other relevant packages

typescript 5.0.0

### Node.js or browser version

Node 18

### Operating System

Mac / Linux

**Comment by sgravrock** [comment]
It looks like you're running into https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42455 .

The TypeScript type definitions are maintained at DefinitelyTyped, by a different group of people. Please raise issues related to them [there](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions).
