### ISSUE TITLE
Problem with using formArrayName in test cases

### ISSUE THREAD

**Issue by Jonas-Knebel** [jasmine/jasmine#2014]
### Steps to Reproduce

Try to test a form that contains a formArrayName without an *ngFor Loop.
```JavaScript
<form [formGroup]="form">
  <ng-container formArrayName="formArrayName">
     ...
  </ng-container>
 </form>
 ```
In our Project we have a child component that just access the index of a formArray. This works completly fine with ng serve, but for some reason doesn't work for ng test.

### Expected Behavior

Work the same way ng serve does and not throw an error.

### Actual Behavior

Error: NG01054: formArrayName must be used with a parent formGroup directive.  You'll want to add a formGroup
      directive and pass it an existing FormGroup instance (you can create one in your class).

### Example code that reproduces the problem

```JavaScript

<form [formGroup]="form">
  <ng-container formArrayName="customArrayName">
     ...
  </ng-container>
 </form>
```
with the form being something like this:
```JavaScript
fb = inject(Formbuilder);
form = this.fb.group({
customArrayName: this.fb.array({...});
});
```

### jasmine-core version

5.0.0

### Versions of other relevant packages

"@angular-devkit/build-angular": "^16.0.5",
"@angular/cli": "^16.0.5",
"@angular/compiler-cli": "^16.0.5",
"@types/jasmine": "~4.3.2",
"autoprefixer": "^10.4.14",
"jasmine-core": "~5.0.0",
"karma": "6.4.2",
"karma-chrome-launcher": "3.2.0",
"karma-coverage": "2.2.0",
"karma-jasmine": "5.1.0",
"karma-jasmine-html-reporter": "2.1.0",
"karma-junit-reporter": "~2.0.1",
"ng-mocks": "^14.11.0",

### Node.js or browser version

node 18.16.0

### Operating System

Windows 11

**Comment by sgravrock** [comment]
You're more likely to find people who know how to answer this and other "how do I test this Angular code" questions if you ask in an Angular forum.
