### ISSUE TITLE
Add a matcher for `x === undefined || x === null` and/or `x !== undefined || x !== null`

### ISSUE THREAD

**Issue by DanKaplanSES** [jasmine/jasmine#2018]
### Feature Proposal

I often need a matcher that checks `x === undefined || x === null` and/or `x !== undefined || x !== null`.

### Context

I incorrectly assumed `toBeDefined` did `x === undefined || x === null`. My incorrect assumption introduced a false positive. This was my mistake, but I was surprised there wasn't a built-in matcher that did what I wanted. At least, I wasn't able to find one in [the matcher documentation](https://jasmine.github.io/api/edge/matchers.html). 

### Example

```JavaScript
const undef = undefined;
const nul = null;
const foo = "bar";
const zero = 0;
const nonZero = 1;

expect(undef).toHaveValue(); // fail
expect(nul).toHaveValue(); // fail
expect(foo).toHaveValue(); // pass
expect(zero).toHaveValue(); // pass
expect(nonZero).toHaveValue(); // pass

expect(undef).toNotHaveValue(); // pass
expect(nul).toNotHaveValue(); // pass
expect(foo).toNotHaveValue(); // fail
expect(zero).toNotHaveValue(); // fail
expect(nonZero).toNotHaveValue(); // fail
```

### Other Information

I'm not tied to this matcher name. I'm sure a better one exists.

I just noticed you can do `expect(x).toEqual(jasmine.anything());`. Even though this does what I was looking for, I believe a `toBeAnything` and `toNotBeAnything` matcher is worthwhile syntactic sugar for `.toEqual(jasmine.anything());`. 

PS: Let me know if you would consider a PR for this and I'll submit one.

**Comment by sgravrock** [comment]
`toBeDefined` is an unfortunate relic of the very early (pre-1.3) days, when there was no `.not` and the only way to negate a matcher was to write a second one that did the opposite. All the other negated matchers were removed in 2.0, with only the `toBeDefined`/`toBeUndefined` pair retained. I think that if there was no `toBeDefined` and you'd had to write `.not.toBeUndefined()` instead, you probably wouldn't have been surprised by its behavior.

I think the proposed matcher is relatively niche. Normally I'd reach for a more specific assertion like `toEqual(someExpectedValue)`, `toEqual(jasmine.any(String))`, or even `toBeTruthy()`. But I can see how it would be useful in some cases, and there's precedent in `jasmine.anything()`, so I don't mind having it as long as it's not going to confuse people.

The `toBeAnything` name is consistent with `jasmine.anything`, but I think it's vague enough to cause the same kind of problem that you ran into with `toBeDefined`. What about something like `toBeNullOrUndefined`? So in the normal case where you want to assert that you got some sort of non-nothing value back, you'd write `expect(something).not.toBeNullOrUndefined()`. A bit more verbose, but I think the explicitness is good in this case.

**Comment by ewinslow** [comment]
Standard terminology for this in JS seems to be "nullish" as in "nullish coalescing operator" (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing).

So I'd vote `toBeNullish()` if this gets accepted.
