### ISSUE TITLE
Error using throwUnless: ReferenceError: throwUnless is not defined

### ISSUE THREAD

**Issue by apazureck** [jasmine/jasmine#2020]
### Your question

Hi,

I am (hopefully) using the latest jasmine together with karma for angular testing (Version 15) in VSCode.

I am also using testing-library/angular to write tests and wante to use the waitFor to wait for an update on my DOM.

I read in your documentation, that I cannot use expect, as it sets the test state to failed, instead I should use throwUnless.

It seems a quite recent addition, so I updated jasmine in my package json:
```json
"jasmine": "^5.1.0",
"karma-jasmine": "~5.1.0",
"jasmine-core": "^5.1.1",
"@testing-library/angular": "^14.3.0",

```
The TS Compiler is happy and I can use throwUnless. All of my test runners (wallaby.js, ng test, karma directly) fail with the message: throwUnless is not defined.

![grafik](https://github.com/jasmine/jasmine/assets/14858596/1ab7ccbd-4310-4a12-a1be-9c824ea51bf9)

So may be you can help me out. Do I need to do another import? Why is it not found, when the rest was found? Can this be a conflict with an older karma-jasmine adapter?

Let me know, if I need to provide something else.

Thank you & cheers

### Example code that demonstrates the problem

```JavaScript
describe('throwUnless', () => {
  it('should not fail', async () => {
    const testvalue = 'test';

    await waitFor(() => {
      throwUnless(testvalue).toBe('test');
    });
  });
});
```

### jasmine-core version

5.1.1

### Versions of other relevant packages

jasmine: 5.1.0,
karma-jasmine: 5.1.0,
jasmine-core: 5.1.1,
@testing-library/angular: 14.3.0

### Node.js or browser version

v 20.5.0

### Operating System

Windows 11

**Comment by sgravrock** [comment]
karma-jasmine is tied to jasmine-core 4.x. Unless you've [set up an NPM override](https://jasmine.github.io/pages/faq.html#001-karma), Karma will use jasmine-core 4.x even if you also have 5.x installed.

**Comment by apazureck** [comment]
Hi,

Thanks for the quick reply.

Sadly the override did not work. I tried multiple variants.

```
"overrides": {
    "jasmine-core": "5.1.1"
  }
```

```
  "overrides": {
    "karma-jasmine": {
      "jasmine-core": "^4.1.0 || ^5.0.0"
    }
  }
```

with multiple variants specifying the version.

But as karma is deprecated I think this is the right time to have a look at another test runner... THanks anyway
