### ISSUE TITLE
Unhandled Promise rejections are not logged

### ISSUE THREAD

**Issue by DanKaplanSES** [jasmine/jasmine#2021]
### Steps to Reproduce

1. Write `Promise.reject("unhandled");` somewhere in your test/production code. Ignore the return value.
2. Run the test

You can find a working repository here: https://github.com/DanKaplanSES/boilerplate-jasmine-typescript/tree/jasmine-unhandled-errors

### Expected Behavior

A log message or a test failure due to unhandled promise rejections. Similar output to running `node -p 'Promise.reject()'` on the command line.

### Actual Behavior

The test runs without mentioning any unhandled promises.

### Example code that reproduces the problem

```JavaScript
import "jasmine";

describe("Example", () => {
  it("passes test", () => {
    expect(true).toBeTruthy();
  });

  it("logs unhandled promise rejections?", () => {
    Promise.reject("unhandled");
  });

  it("logs unhandled promise rejections in async functions?", async () => {
    Promise.reject("unhandled");
  });

  it("logs unhandled promises that throw errors?", () => {
    new Promise(() => {
      throw new Error("unhandled");
    });
  });
});
```

### Context

I'm not sure how this has affected me. I recently learned of this behavior. Maybe I have unhandled promise rejections in my code that I'm unaware of because of this. Maybe it's been more challenging than necessary to write asynchronous code because I don't always get feedback when there is a programmer error.

### jasmine-core version

5.1.1

### Versions of other relevant packages

```json
  "devDependencies": {
    "@types/jasmine": "^5.1.1",
    "@types/node": "^20.8.10",
    "jasmine": "^5.1.0",
    "jasmine-console-reporter": "^3.1.0",
    "nyc": "^15.1.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
```

### Node.js or browser version

node v18.17.1

### Operating System

Windows 10

**Comment by sgravrock** [comment]
As with your other issue, thanks for including a working repro.

Unfortunately, I think this is another case where there isn't much that Jasmine can do to help. The problem is that Node reports unhandled promise rejections asynchronously. I don't know that the exact details of the scheduling are documented, but in general the event fires later than anyone who's trying to debug async specs wants it to. In a simple case like this, it doesn't fire at all because Jasmine exits first. You can see that with this change:

```diff
diff --git a/jasmine.json b/jasmine.json
index 55d0cf0..a540b02 100644
--- a/jasmine.json
+++ b/jasmine.json
@@ -3,5 +3,5 @@
   "spec_files": ["**/*.spec.ts"],
   "helpers": ["../node_modules/ts-node/register/type-check.js"],
   "stopSpecOnExpectationFailure": false,
-  "random": true
+  "random": false
 }
diff --git a/src/example.spec.ts b/src/example.spec.ts
index 414d120..1022420 100644
--- a/src/example.spec.ts
+++ b/src/example.spec.ts
@@ -18,4 +18,9 @@ describe("Example", () => {
       throw new Error("unhandled");
     });
   });
+
+  it("delays long enough for rejections to be reported", function(done) {
+    setTimeout(done);
+  });
 });
```

When I run that using Node 18, I get this output:

```
Failures:
1) Example delays long enough for rejections to be reported
  Message:
    Error: Unhandled promise rejection: unhandled
    (Tip: to get a useful stack trace, use Promise.reject(new Error(...)) instead of Promise.reject(...).)
  Stack:
        at <Jasmine>
        at process.emit (node:events:527:28)
        at process.emit (node:domain:475:12)
        at process.emit.sharedData.processEmitHook.installedValue [as emit] (boilerplate-jasmine-typescript/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at processTicksAndRejections (node:internal/process/task_queues:96:32)
  Message:
    Error: Unhandled promise rejection: unhandled
    (Tip: to get a useful stack trace, use Promise.reject(new Error(...)) instead of Promise.reject(...).)
  Stack:
        at <Jasmine>
        at process.emit (node:events:527:28)
        at process.emit (node:domain:475:12)
        at process.emit.sharedData.processEmitHook.installedValue [as emit] (boilerplate-jasmine-typescript/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at processTicksAndRejections (node:internal/process/task_queues:96:32)
  Message:
    Unhandled promise rejection: Error: unhandled
  Stack:
        at boilerplate-jasmine-typescript/src/example.spec.ts:19:13
        at new Promise (<anonymous>)
        at UserContext.<anonymous> (boilerplate-jasmine-typescript/src/example.spec.ts:18:5)
        at <Jasmine>
```

Now they're reported, because the process kept running long enough for the event to fire. But the best Jasmine can do is report them as failures of the spec that's running at the time. This is partly becuse there isn't enough information to allow Jasmine to reliably associate the rejection with the offending spec, and partly because Jasmine already reported a success for the offending spec before Node reported the unhandled rejection.
