### ISSUE TITLE
`throwUnlessAsync` is actually `throwUnless`

### ISSUE THREAD

**Issue by ej612** [jasmine/jasmine#2026]
### Steps to Reproduce

Go to [this file](https://github.com/jasmine/jasmine/blob/main/lib/jasmine-core/jasmine.js), line 8311:
```
throwUnlessAsync: function(actual) {
    return env.throwUnless(actual);
},
```
Notice how `throwUnlessAsync` calls `env.throwUnless`.

### Expected Behavior

`throwUnlessAsync` should provide the async matchers `toBeResolved` etc.

### Actual Behavior

`throwUnlessAsync` provides the sync matchers `toBe` etc.

### Example code that reproduces the problem

```JavaScript
N/A
```

### jasmine-core version

5.1.1

### Node.js or browser version

N/A

### Operating System

N/A

**Comment by sgravrock** [comment]
Yes. I'll do a release the next time I have a chance, likely within the next week.

**Comment by sgravrock** [comment]
https://github.com/jasmine/jasmine/releases/tag/v5.1.2

**Comment by Tangee69** [comment]
**__**
