### ISSUE TITLE
Custom metadata for tests

### ISSUE THREAD

**Issue by JurajJakubov** [jasmine/jasmine#2027]
### Your question

In today world all tests need some metadata often defined by company/team etc...
I cant find any way how to add this metadata to test. Is it any way to do it?

### Example code that demonstrates the problem
Lets say I have this test.
```JavaScript
it('Should do something, () => {
    // Given
    // When
    // Then
});
```
Is it possible to add metadata for example something like this?
```JavaScript
[E2E]
[TeamXYZ]
[SomeOtherStuff]
it('Should do something, () => {
    // Given
    // When
    // Then
});
```

### jasmine-core version

4.3.5

### Node.js or browser version

16.17

### Operating System

windows 10

**Comment by sgravrock** [comment]
You could add the metadata by calling [setSpecProperty or setSuiteProperty](https://jasmine.github.io/api/5.1/global.html#setSpecProperty) and then write it to whatever destination you have in mind with a custom reporter.
