### ISSUE TITLE
Structured data in Error.cause results in TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by aedart** [jasmine/jasmine#2028]
### Steps to Reproduce

1: Throw new Error with structured data as the Error's [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause), e.g. inside a test

### Expected Behavior

Given test should fail displaying the thrown error's message and evt. cause (_structured data_) if `cause` is not `undefined`.

### Actual Behavior

The following (_or similar_) message is shown in the console:

```
Unhandled promise rejection: TypeError: Cannot read properties of undefined (reading 'split')
    at <Jasmine>
     Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
    at <Jasmine>

```

### Example code that reproduces the problem

```JavaScript
describe('Error', () => {
    it('fails...', () => {
        
        throw new Error('Oh my...', {
            cause: { foo: 'bar' }
        });
        
    });
});
```

### Possible Solution

It seems that this behaviour was introduced in #2013? In any cause, according to Mozilla's documentation (_see [Providing structured data as the error cause](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause)_), an Error `cause` can contain arbitrary data.

When viewing the TypeScript definition of an Error, it defines it in the following way:
```
interface ErrorOptions {
    cause?: unknown;
}

interface Error {
    cause?: unknown;
}

interface ErrorConstructor {
    new (message?: string, options?: ErrorOptions): Error;
    (message?: string, options?: ErrorOptions): Error;
}

// Source from: `lib.es2022.error.d.ts` (TypeScript lib)
```

### jasmine-core version

5.1.2

### Node.js or browser version

node 20.11.0

### Operating System

Ubuntu 22.04

**Comment by sgravrock** [comment]
I can't reproduce the problem. When I run your example spec using jasmine 5.1.0 and jasmine-core 5.1.2, I get this output:


```
Randomized with seed 62419
Started
F

Failures:
1) Error fails...
  Message:
    Error: Oh my...
  Stack:
        at UserContext.<anonymous> ([...]/spec/aSpec.js:4:15)
        at <Jasmine>
```

**Comment by aedart** [comment]
Hmmm... can't seem to get around this. I forgot to mention that I'm running jasmine via Karma, Webpack and babel, in Firefox and Chrome (_the setup is fairly cumbersome to write out here_). Basically, whenever I add a `ErrorOptions` to my Error, I get strange behaviour. However, when I do not include any error options (`cause`), then everything works as expected.

Any ideas on what this could be caused by?

**Comment by sgravrock** [comment]
Most likely Karma is loading jasmine-core 4.x even though you also have 5.1.2 installed. That's *extremely* common -- I'd bet that a huge majority of Karma users who think they're running 5.x are actually on 4.x. See https://jasmine.github.io/pages/faq.html#001-karma .

**Comment by aedart** [comment]
Omg... I feel so silly right now! Huge thanks @sgravrock, you were right. Karma did use jasmine-core 4.x and I never noticed this.
After I corrected this via npm's "overwrite", exceptions containing error options work as intended in my tests.
