### ISSUE TITLE
How to ask Ai to write a unit testcase

### ISSUE THREAD

**Issue by cullsin** [jasmine/jasmine#2032]
### Feature Proposal

Hi, 

I need to use AI to write unit tests for our UI projects. Please suggest what aspects of it would be a great fit. By writing an automated Unit test, I want to write code, too, in the direction of AI.

Thanks,
Raja K

### Context

I need to use AI to write unit tests for our UI projects. Please suggest what aspects of it would be a great fit. By writing an automated Unit test, I want to write code, too, in the direction of AI.

**Comment by sgravrock** [comment]
I'm skeptical about automated test generation. Past approaches have tended to produce poor quality tests, and I don't see any reason to think that AI is any different. Even if I thought it was a good idea, it would make more sense as a standalone product than a feature of a testing framework, particularly a testing framework that's designed to be relatively simple and lightweight. There are already a lot of such products out there, and it's possible that some of them work with Jasmine.
