### ISSUE TITLE
spyOn doesn't work properly on Safari 17.5

### ISSUE THREAD

**Issue by DavoOMG** [jasmine/jasmine#2036]
### Steps to Reproduce

Example steps: 1. Paste the example code below into 'mySpec.js'. 2. Run 'npx jasmine@<some
version> mySpec.js '

### Expected Behavior

On chromium based browsers (I tested it on Safari and a Chromium based browser) it runs as expected: console logs an empty array that was generated by localStorage.getItem('cart') with spyOn - [] (the console.log)

### Actual Behavior

On safari instead of using the mocked localStorage it uses the real localStorage and console logs the real localStorage.getItem('cart') - it doesn't console log an empty array, instead it console logs the real 'cart' that was stored in the real localStorage

### Example code that reproduces the problem

```JavaScript
let cart = [{
            productId: "e43638ce-6aa0-4b85-b27f-e1d07eb678c6",
            quantity: 2,
            deliveryOptionId: '1'
        }, {
            productId: "15b6fc6f-327a-4ec4-896f-486349e85a3d",
            quantity: 1,
            deliveryOptionId: '2'
        }];

localStorage.setItem(`cart`, JSON.stringify(cart));

describe("test suit - addToCart", () => {
    it("adds new product to the cart", () => {
        spyOn(localStorage, "getItem").and.callFake(() => {
            return JSON.stringify([]);
        });
        console.log(localStorage.getItem("cart"));
    })
})
```

### Context

I currently learning JavaScript and was doing a test project: an e-commerce website

### jasmine-core version

5.1.1

### Node.js or browser version

Safari 17.5

### Operating System

MacOS 14.5

**Comment by sgravrock** [comment]
Looks like Safari no longer allows localStorage methods to be overwritten, so it's not possible to spy on them. See https://github.com/jasmine/jasmine/issues/2007 for further discussion and some alternatives. (That thread is about Firefox, but the issue is the same.)
