### ISSUE TITLE
Improve error message when "toBeRejectedWithError" is called on a non-promise

### ISSUE THREAD

**Issue by DanKaplanSES** [jasmine/jasmine#2037]
### Feature Proposal

https://github.com/jasmine/jasmine/blob/7a63c06a65bf96fc3d6af72702e93b1de3c3643b/spec/core/matchers/async/toBeRejectedWithErrorSpec.js#L221-L237

This error message would help troubleshooting if it said the type that was passed in and where the wrong type was given. I think this would be a better way to word the error message: 'toBeRejectedWithError expected a promise to be passed to expectAsync but a ... was passed instead.'

### Context

I spent a lot of time trying to figure out what this "Expected toBeRejectedWithError to be called on a promise" meant. I even had working examples I could compare to, but I still couldn't spot the mistake I was making. I found [this StackOverflow post](https://stackoverflow.com/a/64583165/61624) with the same mistake so I know I'm not alone in this confusion. 

I'm using typescript and the type info lets you pass anything you want into `expectAsync`, so it did not help me troubleshoot.

**Comment by sgravrock** [comment]
That seems like a nice improvement. I'd be happy to review a pull request that adds that to `toBeRejectedWithError` and the other built-in async matchers.

**Comment by sgravrock** [comment]
Fixed via #2049
