### ISSUE TITLE
toHaveBeenCalledWith works not with multiple calls

### ISSUE THREAD

**Issue by Sequoia** [jasmine/jasmine#228]
`expect($.fn.get).toHaveBeenCalledWith(0,0);`
Expected spy get to have been called with [ 0, 0 ] but was called with [ [ 0 ], [ 0 ] ]
`expect($.fn.get).toHaveBeenCalledWith([0],[0]);`
Expected spy get to have been called with [ [ 0 ], [ 0 ] ] but was called with [ [ 0 ], [ 0 ] ]
`expect($.fn.get).toHaveBeenCalledWith([ [0],[0] ]);`
Expected spy get to have been called with [ [ [ 0 ], [ 0 ] ] ] but was called with [ [ 0 ], [ 0 ] ]

How do I work this?  Am I missing something?
`$(selector).get(0);` is called twice in the function I'm testing.  I know I can check the args directly with argsForCall but I think toHaveBeenCalledWith reads better and is  more appropriate.

**Comment by poliu2s** [comment]
I was fustrated that this wasn't working and I found out that you can use the obj.method.calls.allArgs() for this to work

**Comment by AndrewEastwood** [comment]
i dunno how to

**Comment by AndrewEastwood** [comment]
foo(1);foo(2);....foo(10);

I suppose that we should have smth like this toHaveBeenCalledWith([1], [2], ...[10])

but it does not work. And why @ragaskar you said that it's unclear? It's pretty much clear when jasmine will start collecting args in the order how they were invoked.

**Comment by slackersoft** [comment]
If you want to check the arguments for multiple calls to your spy, you should use `toHaveBeenCalledWith` multiple times. Jasmine doesn't currently have a way to verify order of calls, and `toHaveBeenCalledWith` will probably never be modified to verify multiple spy invocations in the same matcher call.

Hope this helps. Thanks for using Jasmine!

**Comment by dabalyan** [comment]
I might be just too late, but why not use 

`expect($.fn.get.calls.allArgs()).toEqual([[], [1, 3], ['yo', 'ho']])`

for three calls like
```
$.fn.get();

$.fn.get(1, 3);

$.fn.get('yo', 'ho');
```
I assume it was not an option 4 years ago. Hope it helps :)

**Comment by burdiuz** [comment]
Had same issue and wrote an expectation to test if function ever called with specified arguments
```javascript
export function toBeCalledOnceWith(spiedFunc, ...args) {
    const received = spiedFunc.mock.calls;
    try {
        expect(received).toContainEqual(args);
    } catch (error) {
        return {
            message: `Expected mock function to have been called with:
${this.utils.printExpected(args)}
But it was called with:
${this.utils.printReceived(received)}\n`,
            pass: false,
        };
    }
    return {
        message: `Expected mock function to not have been called with:
${this.utils.printExpected(args)}
But it was called with:
${this.utils.printReceived(received)}\n`,
        pass: true,
    };
}
```
for now works fine

**Comment by deresegetachew** [comment]
how about using spy.args
i used something like this expect(this.spy.args).to.be.eql([[1],[2],[3],[1],[4]]);    

where the nested array values are the arguments passed to the function

**Comment by slackersoft** [comment]
@deresegetachew `spy.calls.allArgs()` is part of the public interface of a spy in Jasmine, whereas `spy.args` is part of the internal implementation of a spy, and not intended for external use.

**Comment by d3vl1m3** [comment]
Is `mockImplementationOnce` not a suitable solution here?

```
const mockOne = jest.fn(() => null);
const mockTwo = jest.fn(() => null);

const mockFunctionToCall = jest.spyOn(ModuleToMock, 'default')
  .mockImplementationOnce(mockOne)
  .mockImplementationOnce(mockTwo);

it('should trigger twice with diff params', () => {
   expect(mockOne).toHaveBeenCalledWith('Foo');
   expect(mockTwo).toHaveBeenCalledWith('Bar');
});
```
