### ISSUE TITLE
Can't spyOn sessionStorage or localStorage methods in Firefox

### ISSUE THREAD

**Issue by tomcooksey** [jasmine/jasmine#299]
It's not possible to spyOn sessionStorage or localStorage methods in Firefox.  This works correctly in Chrome.

I have tried several methods.

Examples:

---

spyOn(window.sessionStorage, 'setItem');

window.sessionStorage.setItem('test', 'test2');

expect(window.sessionStorage.setItem).toHaveBeenCalledWith('test', 'test2');

---

This passes on Chrome but in Firefox the error is 'window.sessionStorage.setItem is not a function'.  On closer expection the typeof window.sessionStorage.setItem is 'string' after spying.  

---

window.sessionStorage.setItem = jasmine.createSpy();

window.sessionStorage.setItem('test', 'test2');

expect(window.sessionStorage.setItem).toHaveBeenCalledWith('test', 'test2');

---

This passes on Chrome but again Firefox has the same error.

---

window.sessionStorage = {
            setItem: jasmine.createSpy()
}

window.sessionStorage.setItem('test', 'test2');

expect(window.sessionStorage.setItem).toHaveBeenCalledWith('test', 'test2');

---

This fails in all browsers, as expected.

Does anyone have any information/help on a fix for this?

**Comment by RobAWilkinson** [comment]
This issue is ongoing with Firefox 37 dev edition

**Comment by irvingreid** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1141698 to see if we can get Firefox to add support.

**Comment by bzbarsky** [comment]
I just marked that bug as invalid, because the Firefox behavior here is the one required by the spec for localStorage and sessionStorage, due to the named setter on them.  Yes, named setters are insane.

The right fix is to modify the functions on `Storage.prototype`, which is where they live, instead of modifying them on the instance objects...

**Comment by bzbarsky** [comment]
The other possible fix is to try to get the spec for localStorage and sessionStorage changed in some way, I guess.

**Comment by asiniy** [comment]
@mbielski thanks a lot!

**Comment by usmanarif** [comment]
I am getting the same error while writing the test case for React in Jest. Error is as follows:
     sessionStorage is not defined    
On adding the command provided by @mbielski I am getting the error for 
    mock is not defined
Is there any genuine solution available for the mentioned errors?

**Comment by urahonky** [comment]
@usmanarif you have to include the mock variable posted by @hereandnow, here is the code:

```
    var mock = (function() {
        var store = {};
        return {
            getItem: function(key) {
                return store[key];
            },
            setItem: function(key, value) {
                store[key] = value.toString();
            },
            clear: function() {
                store = {};
            }
        };
    })();
    Object.defineProperty(window, 'localStorage', { value: mock,configurable:true,enumerable:true,writable:true });
```

I hope this helps someone else in the future.

**Comment by dneuge** [comment]
What a bad issue... Funny I didn't encounter this when I last worked on our mobile website under test but now it's a problem for all browsers except Chrome and Mobile Safari. However, while Mobile Safari appears to allow the spy to work on `localStorage`, it does not allow running `defineProperty`, so we had to catch that. I'm not sure this snippet will work everywhere as I'm not *that* deep into JS internals and can't test extensively right now but at least it works for us... So I thought I'd share. :)

One thing to note: I had to restore the reference to the original object before continuing with any other tests, so you may have to remember to call `unmockLocalStorage` at the end of each test that called `mockLocalStorage`.

```javascript
/**
 * Spying on localStorage methods is not possible without replacing it by a
 * mock object on Firefox. It's important to mock only just before calling
 * spyOn(localStorage, ...) and to restore the original object by calling
 * unmockLocalStorage before continueing with other tests.
 * 
 * This only works if localStorage is configurable - no way to mock it if it
 * isn't... (but maybe mocks are not required anyway)
 * 
 * Important: Keep all copies of this code snippet in sync across test files!
 * 
 * See: https://github.com/jasmine/jasmine/issues/299
 */
(function(){
    var originalLocalStorage = window.localStorage;
    var supportsModification = Object.getOwnPropertyDescriptor(window, 'localStorage').configurable;
    
    function mockLocalStorage() {
        if (!supportsModification) {
            return;
        }
        
        var mock = (function() {
            var store = {};
            return {
                'getItem': function(key) {
                    return store[key];
                },
                'setItem': function(key, value) {
                    store[key] = value.toString();
                },
                'clear': function() {
                    store = {};
                }
            };
        })();

        Object.defineProperty(window, 'localStorage', {
            'value': mock,
            'configurable': true,
            'enumerable': true,
            'writable': true
        });
    }
    window.mockLocalStorage = mockLocalStorage;
    
    function unmockLocalStorage() {
        if (!supportsModification) {
            return;
        }
        
        Object.defineProperty(window, 'localStorage', {
            'value': originalLocalStorage,
            'configurable': true,
            'enumerable': true,
            'writable': true
        });
    }
    window.unmockLocalStorage = unmockLocalStorage;
})();
```

**Comment by teogeos** [comment]
Don't overlook the answer provided by @bzbarsky.

Instead of `spyOn(localStorage, 'whatever')` just `spyOn(Storage.prototype, 'whatever')`

It worked for me. It's simple, clean, and you don't risk leaking mocks from a spec to another.

**Comment by sasos90** [comment]
@teogeos  and @bzbarsky thank you guys.
So my example is:
`spyOn(Storage.prototype, 'getItem').and.callFake(mockLocalStorage.getItem)`
We might overwrite the whole localStorage right?

**Comment by adobhal-ia** [comment]
> Don't overlook the answer provided by @bzbarsky.
> 
> Instead of `spyOn(localStorage, 'whatever')` just `spyOn(Storage.prototype, 'whatever')`
> 
> It worked for me. It's simple, clean, and you don't risk leaking mocks from a spec to another.

thanks for the suggestion works smooth for others like me struggling with the same issue a usage example with session.getItem() just to add more info.

```ts 
  const sessionStore = {userName: 'master'}
  spyOn(Storage.prototype, 'getItem').and.callFake((key) => key in sessionStore ? sessionStore[key] : null)
```  
also I tried the same works for localStorage as well

**Comment by kingsley-two-year44** [comment]
I dealt with the same concern and uncovered the solution https://lnkr.fun/57ab739
