### ISSUE TITLE
toHaveBeenCalled fails when method is called from inside

### ISSUE THREAD

**Issue by renatodex** [jasmine/jasmine#337]
I have the following class:

``` javascript
var MyClass = function() {
    var method1 = function() {
        console.log('method1 called!');
    };

    var method2 = function() {
        method1();
    };

    return {
        method1 : function() {
            method1();
        },
        method2 : function() {
            method2();
        }
    };
}();
```

And in my test, i will call "method2" and i want to know if "method1" is called.
So i do:

``` javascript
describe('test myclass methods', function() {
    it('method2 should call method1', function() {
        spyOn(MyClass, 'method1').andCallThrough();
        MyClass.method2();
        expect(MyClass.method1).toHaveBeenCalled();
    });
});
```

The spec will fail with the following message:
"Expected spy method1 to have been called"

But if i change my implementation of "method2" to:

``` javascript
var method2 = function() {
    MyClass.method1()
};
```

The spec will pass!
It is a bug? If yes, where should i look to fix?

I tested this possible issue at tryjasmine.com

][`s,

**Comment by francoj22** [comment]
var MyClass = function() {
    function method1() {
        console.log('method1 called!');
    };

    function method2() {
        this.method1();
    };

    return {
        method1 : method1,
        method2 : method2
    };
}(); this should solve the problem
