### ISSUE TITLE
toHaveBeenCalledWith fails with multiple arguments

### ISSUE THREAD

**Issue by jamesarosen** [jasmine/jasmine#35]
### First attempt:

```
spyOn(Foo, 'bar');
Foo.bar('baz', 'qux');
expect(Foo.bar).toHaveBeenCalledWith('baz', 'qux');
```

Expected spy to have been called with `[ [ 'baz', 'qux' ] ]` but was called with `[ 'baz', 'qux' ]`.
### Second attempt:

```
spyOn(Foo, 'bar');
Foo.bar('baz', 'qux');
expect(Foo.bar).toHaveBeenCalledWith(['baz', 'qux']);
```

Expected spy to have been called with `[ [ 'baz', 'qux' ] ]` but was called with `[ [ 'baz', 'qux' ] ]`.

I believe the problem is that Jasmine is using a simple `==` or `===` comparison, rather than comparing the elements of `arguments` individually.

**Comment by poliu2s** [comment]
@jamesarosen What was the formatting issue? I seem to be having the same problem

**Comment by poliu2s** [comment]
Actually, I found out that you can use the obj.method.calls.allArgs() for this to work
