### ISSUE TITLE
toContain should work with DOMTokenList

### ISSUE THREAD

**Issue by vin** [jasmine/jasmine#406]
Many of our specs verify expectations of CSS class names being present or absent on DOM elements. It would be nice to be able to just say `expect(element.classList).toContain('myExpectedClassName')`, but that doesn't work with the current `toContains` implementation that checks for Array types.

Our workaround is expect(element.className.split(' ')).toContain(...), which is OK, but somewhat clumsier than it ought to be.

**Comment by slackersoft** [comment]
This should work now as of da6813ef0d8c37053161445412b8ea4e013838b2
