### ISSUE TITLE
Bail on first failure

### ISSUE THREAD

**Issue by hurrymaplelad** [jasmine/jasmine#414]
Put together an [extension](https://github.com/goodeggs/jasmine-bail-fast) to add bail after first failure behavior after [someone else had the same request](http://stackoverflow.com/questions/11562817/does-jasmine-node-offer-any-type-of-fail-fast-option), and I [didn't hear of existing work from the community](https://groups.google.com/forum/#!topic/jasmine-js-dev/M6yx0hHyQdA).

I'd love to see this behavior (`jasmine.Env.prototype.bailFast()`) added to jasmine core before I suggest a flag for [jasmine-node](https://github.com/mhevery/jasmine-node).

I'm happy to put together a PR if folks think this would be useful and agree it belongs in jasmine core.

**Comment by slackersoft** [comment]
I think terminating the suite once a single spec has failed is something that would be good for jasmine to support. I'd be happy to review a pull request for that if anyone has time.

Discussion on stopping a single spec once an expectation has failed should move over to #577 as that is a different issue than what is being discussed here.

**Comment by slackersoft** [comment]
Tracker story here: https://www.pivotaltracker.com/story/show/85966014

**Comment by domio** [comment]
+1

**Comment by avukonke** [comment]
+1

**Comment by ymkjp** [comment]
+1 for `--fail-fast` option

**Comment by erkangur** [comment]
+1, ```--fail-fast```

**Comment by erkangur** [comment]
+1, ```--fail-fast```

**Comment by dwelle** [comment]
+1

**Comment by kriscs** [comment]
+1

**Comment by dnoliver** [comment]
+1

**Comment by mtyeh411** [comment]
+1

**Comment by StephanBijzitter** [comment]
+1

**Comment by mikeverbeck** [comment]
+1

**Comment by andreibondarev** [comment]
:+1:

**Comment by bernabas** [comment]
+1

**Comment by americos** [comment]
+1

**Comment by mgwidmann** [comment]
+1

**Comment by kimx** [comment]
+1

**Comment by pavelKozlov** [comment]
+1

**Comment by pmowrer** [comment]
For the time being, we created this workaround to alleviate the pain: https://github.com/Updater/jasmine-fail-fast

**Comment by StephanBijzitter** [comment]
@pmowrer Would this work with https://github.com/gruntjs/grunt-contrib-jasmine ?

**Comment by pmowrer** [comment]
@StephanBijzitter Sure, it shouldn't matter what Jasmine wrapper you use. I added some usage examples to the [README](https://github.com/Updater/jasmine-fail-fast/blob/master/README.md#grunt-contrib-jasmine). Hopefully that helps.

**Comment by kestelle** [comment]
+1

**Comment by NelsonScott** [comment]
+1

**Comment by amanzyuk** [comment]
+1

**Comment by kcampion** [comment]
+1

**Comment by killercentury** [comment]
+1

**Comment by drewprice** [comment]
+1

**Comment by gabrielhpugliese** [comment]
+1

**Comment by Byron** [comment]
+1

**Comment by SteffiPeTaffy** [comment]
+1

**Comment by runk** [comment]
+1

**Comment by zxxc** [comment]
+1

**Comment by brandenbyers** [comment]
Thanks @pmowrer for the workaround solution. Works great with Protractor.

**Comment by reecehudson** [comment]
+1

**Comment by howdyjessie** [comment]
+ 1

**Comment by Codier** [comment]
+1000,000,000

**Comment by JanPietrzyk** [comment]
+1

**Comment by velo** [comment]
++

**Comment by Codier** [comment]
+1

**Comment by exbuddha** [comment]
+1

**Comment by basvdijk** [comment]
+1

**Comment by F1LT3R** [comment]
+1

**Comment by exbuddha** [comment]
I'm kind of new to this whole Jasmine/Protractor thing, which by the way, I think is one of the most elegant test frameworks I've seen, but maybe another way to think about this feature is to extend the expect() function grammar to allow writing chains like this:

**expect(condition).verb(something).or.stop();**
expect(element(by.id('my-element')).isPresent()).toBe(true).or.stop();

**Comment by aCarpenter** [comment]
+1

**Comment by pmowrer** [comment]
So much +1 spam invading my emails. Try https://github.com/Updater/jasmine-fail-fast. Self promotion, but honestly solves the problem, at least for the Protractor use case.

**Comment by exbuddha** [comment]
Sorry!

-1

And, thank you for the link.

**Comment by F1LT3R** [comment]
Found myself doing the same thing @pmowrer :)

https://github.com/F1LT3R/protractor-jasmine2-fail-whale

Designed for Jasmine2, but I suspect it may work with earlier versions too.

**Comment by marktyers** [comment]
Yes please

**Comment by rcbop** [comment]
+1

**Comment by voltrevo** [comment]
+1

**Comment by Izhaki** [comment]
+1

**Comment by skyshore2001** [comment]
I use jasmine 2.5.2 to test my back-end web APIs via ajax sync call in each "it" block. 
I'm looking for such logic:

- Developer is able to mark some case as "critical case". And the first case in a suite can be auto marked as "critical case". If such case fails, the other cases ("it" blocks) are skipped to execute and marked as "pending". 

- If the first suite fails, stop the tests.

First I write code in such callbacks as reporter.suiteStarted/specStarted to implement such logic, but unfortunately I find it does not really skip a case if fail()/pending() is called in beforeEach function, the ajax call in "it" block still execute. (see https://github.com/jasmine/jasmine/issues/577) 

Now I'm considering a flexible mechanism that the core lib expose some more interfaces that allows developers to program the logic.

**Comment by zhong-edward** [comment]
As I know hiddenElement.click() can stop case if the element does not present.
but if a file flag not exist, how can stop case flow? code like this:
fs.stat(filepath, function(err, stat) {
    if(err ) {
        //break case and continue next spec.
   }
});
//other case step

**Comment by al-the-x** [comment]
Any progress on this? I see no PR linked...

**Comment by bennyn** [comment]
I came here because this issue is referenced in the [Jasmine Core 3.0 Release Notes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md#breaking-changes). Unfortunately, I don't know what has been changed because I see a lot of `+1` comments here but no demo code.

Does anyone have an example of how "proper fail fast with error reporting" looks like?

**Comment by slackersoft** [comment]
@bennyn it really depends on how you're running your Jasmine suite.

If you're using Jasmine's provided HTML runner, there is an option in menu at the top right to Stop on spec failure.

If you're using the Jasmine ruby gem or python wheel, there is an option `stop_on_spec_failure` in the jasmine.yml file.

If you're using the Jasmine npm package, you can either pass `--fail-fast` on the command line or by setting the `stopOnSpecFailure` option in your jasmine.json file.

If you're using Karma, Protractor or something else, you'll have to talk to those teams about supporting the new option in Jasmine 3.0.

Hope this helps. Thanks for using Jasmine!

**Comment by dfederm** [comment]
@slackersoft Is it as easy as just replacing:
```
var catchingExceptions = queryString.getParam("catch");
env.catchExceptions(typeof catchingExceptions === "undefined" ? true : catchingExceptions);
```
with
```
var stoppingOnSpecFailure = queryString.getParam("failFast");
env.stopOnSpecFailure(typeof stoppingOnSpecFailure === "undefined" ? true : stoppingOnSpecFailure);
```
