### ISSUE TITLE
expect({}).toBe({}) Fails.

### ISSUE THREAD

**Issue by winrid** [jasmine/jasmine#416]
For some reason empty objects/arrays aren't expected to be empty objects or arrays.

**Comment by harshjulka** [comment]
@sheelc 
it("demonstrates empty object behavior", function() {
  var x = {}; 
  expect(x).toBe(x);
  expect(x).toEqual(x);
  expect(x).toEqual({});
});

.toBe() is not working for me
however .toEqual() works in above case

**Comment by ragaskar** [comment]
Hi @harshjulka 

Can you be more specific about which assertion is failing? I would expect `expect(x).toBe(x)` to pass, but would *not* expect `expect(x).toBe({})` to pass.

**Comment by priiduneemre** [comment]
I would say that in most cases, it would make more sense to use `expect(x).toEqual({})` instead, anyway.

**Comment by russelyang** [comment]
@harshjulka it may be late. I run into the same issue. I assume toBe is using reference check like ===. toEqual check two objects if they have same things.
