### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aminjam** [jasmine/jasmine#418]
I am trying to use Karma to setup my Jasmine tests, and I get the following error when running "karma run"

RangeError: Maximum call stack size exceeded. at C:/Users/myName/angular/node_modules/karma-jasmine/lib/jasmine.js:1811
Chrome 29.0.1547 (Windows 7): Executed 0 of 1 ERROR (0.244 secs / 0 secs)
PhantomJS 1.9.1 (Windows 7): Executed 0 of 1 ERROR (0.237 secs / 0 secs)

grunt Package.json:
Here is my Package.json:
{
"name": "App",
"description": "App engine",
"version": "0.1.0",
"readme": "Read Me...",
"readmeFilename": "README.md",
"repository": {
"type": "svn",
"url": "http://v8.googlecode.com/svn/trunk/"
},
"devDependencies": {
"grunt": "~0.4.1",
"grunt-contrib-copy": "~0.4.1",
"grunt-contrib-concat": "~0.3.0",
"grunt-contrib-coffee": "~0.7.0",
"grunt-contrib-uglify": "~0.2.0",
"grunt-contrib-compass": "~0.3.0",
"grunt-contrib-jshint": "~0.6.0",
"grunt-contrib-cssmin": "~0.6.0",
"grunt-contrib-connect": "~0.3.0",
"grunt-contrib-clean": "~0.4.1",
"grunt-contrib-htmlmin": "~0.1.3",
"grunt-contrib-imagemin": "~0.1.4",
"grunt-contrib-watch": "~0.5.1",
"grunt-usemin": "~0.1.11",
"grunt-rev": "~0.1.0",
"grunt-karma": "~0.6.2",
"grunt-open": "~0.2.0",
"grunt-concurrent": "~0.3.0",
"matchdep": "~0.1.2",
"connect-livereload": "~0.2.0",
"grunt-google-cdn": "~0.2.0",
"grunt-ngmin": "~0.0.2",
"karma-phantomjs-launcher": "~0.1.0",
"karma-jasmine": "~0.1.3",
"karma": "~0.10.2"
}
}

System Info:

NodeJS: v0.10.17
Karma: v0.10.2
Phantomjs: version: 1.9.1-8

I have already loaded:
Angular 1.0.7
jQuery 2.0.3
bootstrap 3
jasmine 

Any idea what's missing or what I am doing wrong?

**Comment by SimenB** [comment]
@brettcannon @aminjam 
Hi, I realize this is ages ago, but I'm having the same problem. I'm using RequireJS and Jasmine 1.3. I need a reference to jasmine in the requirejs-config, but I'm not able to. If I exclude either mine or karma's jasmine, it can't be found. If I leave them in, I get the error reported here.
Do you guys by any chance have any idea how I can get it to run?

**Comment by bnjasim** [comment]
@brettcannon Your comment was very helpful. Thanks.
