### ISSUE TITLE
Comparing complex Object to toEqual(jasmine.any(Array)) cause Browser to hang

### ISSUE THREAD

**Issue by thomb** [jasmine/jasmine#424]
I have a really complex javascript object - containing two Backbone views, to be specific - and when I compare that object using toEqual(jasmine.any(Array)) it causes the browser to hang hard.

Tested on Firefox 22 and Chrome 27.

**Comment by jesperronn** [comment]
:+1: for Pivotal's focus on recent releases only. Getting stuff to work in backwards compatible ways can be a real time-consumer. Nice to focus on progress in new releases instead of old releases. Thanks project collaborators
