### ISSUE TITLE
How to use ConsoleReporter with 1.3.1 Jasmine version from a zip download?

### ISSUE THREAD

**Issue by op1ekun** [jasmine/jasmine#430]
Firstly. Jasmine is great :) Tests make more sense for everyone when written in specification way. However I run into a small issue. It's not stopping me from work, yet it's pretty irritating :)

I downloaded my version of Jasmine from here: https://github.com/pivotal/jasmine/downloads

There is no ConsoleReporter bundled with this one. So I decided to download it directly from github. Normally I wouldn't work this way, but I'm still pretty new t Jasmine and wanted to play around a little bit.

Unfortunately I can't get it work with my version of Jasmine. After inspecting the code I tried this one in my Runner: 
`var reporter = new getJasmineRequireObj().ConsoleReporter({
        print : console.log
});`.

There are no error and no output in the console :(

If it doesn't make sense I will just clone repository and I will use master branch.

Thanks!

**Comment by Revlin** [comment]
@mustafa0x In that case I would go with what op1ekun recommended and use Larry Myers' [jasmine-reporter](https://github.com/larrymyers/jasmine-reporters):
```
<script type="text/javascript" src="jasmine-reporters/src/tap_reporter.js"></script>
```
... with the TapReporter module:
```
    var tapReporter = new jasmineReporters.TapReporter({});
    jasmine.getEnv().addReporter(tapReporter);
```
