### ISSUE TITLE
a click on a pending spec should run it 

### ISSUE THREAD

**Issue by mighdoll** [jasmine/jasmine#461]
I was surprised that clicking on a xit() spec from the html runner didn't run the pending test.  

The current UI is confusing - it's hard to tell what happened when you click on a pending test from the html runner.  It could be made more clear that no were run...  But I think it would be less confusing and a handy feature to just run a pending test if it is selected explicitly.  

The use I had in mind was creating some specs that were of the form 'create interactive debug environment'.  i.e. debugging versions of tests with extended timeouts, noisy logging, etc.   These tests would be normally disabled, but could be clicked or bookmarked to run as needed.

What do y'all think?

**Comment by chris-orchard** [comment]
Although I don't agree with the reasoning of the original post (I believe this change would make the UI more confusing not less) I do feel it would be beneficial to have a way to re-test `pending` specs without having to physically take the marker off in the code.

I've raised #1517 with a more detail on why I think this would be useful.
