### ISSUE TITLE
Jasmine for ExtendScript

### ISSUE THREAD

**Issue by madevelopers** [jasmine/jasmine#493]
I've tried to port Jasmine for ExtendScript using the standalone zip file. I have already fixed the errors on that environment which is basically the `window` object changed to `$.global`. However I can't get the output displayed on the console. The file console.js doesn't seem to be used. Was this the one responsible for printing the results?

Also, is there already an implementation for ExtendScript?

**Comment by tmaslen** [comment]
I made a port of Jasmine 2.2.0 for ExtendScript.  Help yourselves:

https://github.com/tmaslen/jasminejsx

/t
