### ISSUE TITLE
Objects with null prototype cause exceptions when pretty-printing

### ISSUE THREAD

**Issue by jpolitz** [jasmine/jasmine#500]
This test:

```
describe("objects", function() {
  it("should print results for null protos", function() {
    var o = Object.create(null);
    var o2 = Object.create(null);
    expect(o).toBe(o2);
  });
});
```

Will fail while reporting the test faillure with:

```
1) objects should print results for null protos.
  TypeError: Object [object Object] has no method 'hasOwnProperty'
    at PrettyPrinter.iterateObject (<...>lib/jasmine/lib/jasmine-core/jasmine.js:1350:16)
```

I think a fix would be to have https://github.com/pivotal/jasmine/blob/2670bb40a7d0135553a688f0102ee6e0d8500dc1/lib/jasmine-core/jasmine.js#L1393 use `Object.prototype.hasOwnProperty.call` rather than relying on the object itself having the field, but I'm not familiar enough with the internals to know what else that change could affect, so it's just a guess.

**Comment by emorikawa** [comment]
Yeah, fun story from the 1.3 branch: Node in this pull request: https://github.com/nodejs/node/pull/6092/files gave `EventEmitter` an object with a null prototype. This means that if you attempt to prettyprint any object that contains a Node `EventEmitter`, it'll fail.
