### ISSUE TITLE
Feature Request: Stub a variable (vs spyOn a function)

### ISSUE THREAD

**Issue by tommyh** [jasmine/jasmine#502]
Hi,

I often find myself needing a feature where I can stub a variable (either a global variable, or an object's member variable) with a fake value or dummy implementation.  Note: I am not referring to `spyOn`-ing on a function call.

example:

```
window.foo = 7;

window.bar = Backbone.View.Extend({
   initialize: function(){
     // complex behavior with alot of setup required or side-effects kicked off
     throw("side effects....");
   }
});
```

Then I have a "baz" module, which I want to test and isolate the tests to just "baz" functionality, so I'd like todo this:

```
jasmine.stub(window, "foo", 42);
jasmine.stub(window, "bar", fakeSimpleBackboneView);
```

Note: I could just do `window.foo = 42` in my "baz" test, but jasmine.stub would perform the cleanup after the test, just like `spyOn` does.

If you guys think this is a good idea, I will work on a pull request to jasmine.  If not, that's cool too and I will release a seperate module which people can pull into their projects.  I just want to ask upfront to avoid double work.  (I would predict higher usage if it's in jasmine core).  What are your guys thoughts?  @infews?

Thanks,
Tom

**Comment by sparkeplug** [comment]
Hi @tommyh / @infews 

Is the stubbing of variable functionality in place.... ?

If not any idea how i can stub the variables for my tests in jasmine.........?
