### ISSUE TITLE
Request: Supply filename and line numbers for specs

### ISSUE THREAD

**Issue by DanTup** [jasmine/jasmine#537]
I've created a [Visual Studio Test Adapter for Jasmine](http://visualstudiogallery.msdn.microsoft.com/102979e0-61ba-4c6f-a18c-ca64cc7bd2c6); but I've had to put a massive hack in it to discover tests and get filenames/line numbers.

When "discovering" tests I previously used the filter so that none would run; but I couldn't provide VS with file/line number to allow the user to double-click to jump to a test.

So, I implemented [a horrendous bodge](https://github.com/DanTup/TestAdapters/issues/3), where when discovering tests, the it function is rigged to explode, and I can parse the stack trace.

This is nasty; it would be nicer if Jasmine provided file/line info for a spec in the information; and then I can go back to using the filter to simply disable execution when discovering.

**Comment by agirorn** [comment]
I have managed to get at the file and line number of a each running spec in [jasmine-slow-reporter](https://github.com/agirorn/jasmine-slow-reporter/blob/master/lib/jasmine-slow-reporter.js#L6) by overwriting the `ìt` function. Jasmine could offer more data via hooks or in the reporter api to simplify plugin creation.
