### ISSUE TITLE
Support adding describe() and it() calls at runtime

### ISSUE THREAD

**Issue by SyntaxColoring** [jasmine/jasmine#559]
This feature request is a follow-up to issues #555 and #412.

It would be nice to support adding `describe` and `it` calls after Jasmine is loaded.  This would permit asynchronously loading and running test suites.  (This is necessary, for example, to run CoffeeScript test suites through [`coffee-script.js`](http://coffeescript.org/#scripts).)

I admit that this seems like a pain to implement, but it might be worth considering for future major releases.

**Comment by finspin** [comment]
The status of the feature request is not publicly available, has there been any progress on this?

Here is a use case:

This fails with TypeError: Cannot read property 'forEach' of undefined

    describe('Async car test', function () {

        var cars;

        beforeAll(function (done) {
            // getCars() is a promise which resolves to ['audi', 'bmw']
            getCars().then(function (data) {
                cars = data;
                console.log(cars) // ['audi', 'bmw']
                done();
            });
        });

        cars.forEach(function (car) {
            it('car ' + car, function () {
                expect(car).toBe(car);
            });
        });
    });

This works fine

    describe('Car test', function () {

        var cars = ['audi', 'bmw'];

        cars.forEach(function (car) {
            it('car ' + car, function () {
                expect(car).toBe(car);
            });
        });
    });

**Comment by slackersoft** [comment]
Our preferred way to solve this problem is for a user to wait to actually `execute` the suite until all of the specs that should be run have been loaded.

Changing jasmine so specs could be added after the suite started execution would be a large change to how jasmine works internally. You should be able to get the same kind of effect by writing a [custom `boot.js`](http://jasmine.github.io/edge/custom_boot.html) that waits for your specs to be defined.

**Comment by jwbeech** [comment]
Hi @infews I see you added a feature request for this, I can't seem to access your link, is there any progress on this topic?

**Comment by slackersoft** [comment]
Adding specs after the suite has started execution is not something that we are looking to add to Jasmine.

If you have a static list that you can loop through synchronously to add specs, you can still do that, but if you want to add specs in a more asynchronous manner, you'll probably need to define a [custom boot](https://jasmine.github.io/2.5/custom_boot.html) that waits until you have defined all of your specs before calling `execute` on the Jasmine `Env`
