### ISSUE TITLE
Manually fail a test with fail() method

### ISSUE THREAD

**Issue by dasois** [jasmine/jasmine#563]
Is there still a fail() function on the it object in 2.0?

**Comment by juako4** [comment]
+1

**Comment by kylezeeuwen** [comment]
+1

**Comment by pkalkman** [comment]
+1

**Comment by slackersoft** [comment]
Given that we've implemented this already, I'm not sure what the +1s mean here? @JoaquinFernandez @kylezeeuwen @pkalkman

**Comment by pkalkman** [comment]
Sorry my bad. I should have read the documentation beter.

**Comment by kylezeeuwen** [comment]
Me too, I am stuck using jasmine 1.x via protractor and jasmine-node, but I
think there is a beta version of both that uses jasmine 2 I just haven't
upgraded yet . thanks for all the code !

**Comment by slackersoft** [comment]
I believe that the newer versions or protractor use jasmine 2.x now, and we have release a [jasmine package on npm](https://npmjs.org/package/jasmine) that supports 2.x as well.

**Comment by mpm** [comment]
+1

**Comment by nevcos** [comment]
+1

**Comment by BenjaminVanRyseghem** [comment]
I know this thread it old, but now that there is a `fail` why not also having a `pass`?

As everyone else here, I am dealing with callback, and I would love to be able to write

```js
my.function
    .onSuccess(pass)
    .onError(fail)
```

or something similar, instead on using `expect(true).toBeTruthy()`

Or am I missing something?

**Comment by siminino** [comment]
@BenjaminVanRyseghem  +1

**Comment by casmith** [comment]
@BenjaminVanRyseghem Specs pass implicitly if they do not fail, so there's not really a need to call pass() . If you want to check that a callback was called, usually you would install a spy on it and verify it via the spy.

**Comment by BenjaminVanRyseghem** [comment]
of course I could use a spy, but it's still a bit of boiler plate :smile:

**Comment by luchillo17** [comment]
@BenjaminVanRyseghem also if you have an async test (which to be honest will happen more often than not) you'll just call `done()` whenever the test pass, that way you tell jasmine that the test has ended without trouble.

**Comment by jadekler** [comment]
+1 would love a `.fail()`

**Comment by slackersoft** [comment]
@jadekler as [I mentioned 2 years ago in this thread](https://github.com/jasmine/jasmine/issues/563#issuecomment-94551905), `done.fail` already exists in Jasmine. Not sure what your +1 means here.

**Comment by yavin5** [comment]
I must be missing something, and I suspect others above are as well..

@slackersoft : I'm using Jasmine 2.6.0.  I have tried invoking all of the fail() functions mentioned so far in this issue.. they're all undefined.  I read through the source and grepped through the source, and I am not seeing any definition of a fail function.  Should I be seeing one?  If so, where specifically should I be seeing it in version 2.6.0?

Thanks.

**Comment by slackersoft** [comment]
@yavin5 how are you including/running Jasmine in your project? (Karma, gulp, ruby gem, python, something else). If the mechanism you're using utilizes the default Jasmine spec runner html, you should be able to see the version at the top of the page, like this:

<img width="170" alt="screen shot 2017-07-24 at 5 18 06 pm" src="https://user-images.githubusercontent.com/512724/28550220-48f28e66-7094-11e7-94b9-023afa0800b2.png">

The `fail` functions should be included in any jasmine-core version after 2.1.0

**Comment by yavin5** [comment]
@slackersoft I'm including Jasmine by doing the following:

In package.json, added these as devDependencies:

```
  "devDependencies": {
    "jasmine": "^2.6.0",
    "jasmine-core": "^2.6.0",
    "jasmine-node": "^1.14.5"
  }
```

I initialized Jasmine's configuration file:

```
$ ./node_modules/.bin/jasmine init
```

Then, also in package.json, I added a "test" script:

```
  "scripts": {
    "prestart": "npm install",
    "start": "node ./index.js",
    "pretest": "npm install",
    "test": "./node_modules/jasmine-node/bin/jasmine-node ."
  },
```

And then I run "npm test" on the command line (it also runs from my WebStorm IDE and the results are the same).

Incidentally, I did try to use the "jasmine" command line script instead, at first, like this:

```
  "scripts": {
    "test": "./node_modules/.bin/jasmine",
  },
```

And that worked all except: my socket.io client code stopped working correctly when I ran my spec tests with this test runner!  A request sent from the client is not received by the server, silently.  I didn't have time to investigate that, so I next tried the jasmine-node test runner, which runs my tests fine.  I don't think fail() works in either case.

I see now that node_modules/jasmine-core/lib/jasmine-core/jasmine.js does have a fail() function defined.. it would sure be nice if that was usable somehow.  Placing fail('something'); inside a test, at the top, just gives me:

```
F

Failures:

  1) the test should fail properly
   Message:
     ReferenceError: fail is not defined
   Stacktrace:
     ReferenceError: fail is not defined
    at .<anonymous> (/Users/yavin5/projects/mything/spec/server.spec.js:100:9)
    at .<anonymous> (/Users/yavin5/projects/mything/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

Finished in 0.046 seconds
1 test, 1 assertion, 1 failure, 0 skipped
```

**Comment by luchillo17** [comment]
@yavin5 Mine works with just `fail()`, but just in case could you try the async way with `done.fail()`?

**Comment by yavin5** [comment]
I did indeed try all of the ways of referencing it.. none of those work.

**Comment by slackersoft** [comment]
If you're using jasmine-node, it only support Jasmine 1.3.x and not the 2.x feature set. You probably want your `npm test` script to use the `jasmine` command line tool to get whatever version of jasmine-core you have available.

**Comment by yavin5** [comment]
Interesting.  Okay, yep, I re-tried the jasmine command line test runner tool, and fail('ugh') now works!  And, my other bug that was preventing me from using the jasmine test runner is apparently not happening now (I don't know which change made it stop happening -- I've been actively developing the code).

**ONE SOLUTION: For everyone using the "jasmine-node" test runner instead of the "jasmine" one, fail() won't work because jasmine-node silently exposes an older API version of Jasmine.  :(**

Thank you!

**Comment by t2gaurav** [comment]
Use - expect(true).toEqual(false);
