### ISSUE TITLE
Allow done() to take an optional error.

### ISSUE THREAD

**Issue by nikku** [jasmine/jasmine#567]
It is a popular pattern to pass an error object to a `done()` callback in NodeJS.
We should support that in Jasmine 2.0, too so that users can properly unit test asynchronous code.
#### Example

```
describe('async with error', function() {

  it('should fail on done(err)', function(done) {

    setTimeout(function() {
      done(new Error('async fail'));
    }, 100);
  });
});
```

should fail with 

```
error: 'async fail'
```

instead of succeeding which is the case as of `v2.0.0`.

**Comment by vincentlaucy** [comment]
I'm using this work around 

```expect(err.stack).toBeNull();```

**Comment by martinleopold** [comment]
noob question: is there any difference in using (the global) ```fail``` and ```done.fail```?

**Comment by slackersoft** [comment]
`done.fail` is only available in asynchronous specs where you already have `done` and will also cause the spec to finish and move to the next thing in the queue. The global `fail` will only add an explicit failing expectation and in an asynchronous spec the spec will still wait and timeout.

**Comment by straker** [comment]
Could we get this feature of `done.fail` in the jasmine docs? I spent the last hour trying to google how to not have Jasmine timeout when an async assertion fails, and finally stumbled upon this issue.

**Comment by Gerg** [comment]
There is an issue for adding docs for `done.fail` in the docs repo here: https://github.com/jasmine/jasmine.github.io/issues/26

**Comment by timaschew** [comment]
Why not supporting done(err) as well? 
This is the nodejs way, __forcing__ users to use something different makes absolutely no sense!

**Comment by slackersoft** [comment]
@timaschew please read the discussion above for the reasons why we don't want `done` itself to fail the spec when it receives an argument.

**Comment by johnw42** [comment]
How about another variant that implements the node.js convention? It could be called something like done.node or done.expectNull.

**Comment by jehon** [comment]
Hello

I didn't see that in the documentation... While it is soo goood to have that.

Did i miss something?

Thanks
