### ISSUE TITLE
-0 should equal 0

### ISSUE THREAD

**Issue by jonatr35** [jasmine/jasmine#579]
I've written a unit test for a function were I expect my returned value to be rounded to 0 (example -0.4 should return 0). I've written my unit test as expect(result).toEqual(0) and it is failing. 

When attempting to debug I eventually found out that it was failing because it thought that -0 did not equal 0. It did however pass when using expect(result).toBe(0), however I should still be able to use expect(-0).toEqual(0).

**Comment by KthProg** [comment]
Yeah they should really be equal please update this.
