### ISSUE TITLE
Execute specs in random order

### ISSUE THREAD

**Issue by demisx** [jasmine/jasmine#583]
Hi. Is it possible to force specs execute in random order, similar to RSpec? That would help to detect interdependencies between the specs early.

Thanks.

**Comment by sdemjanenko** [comment]
Has any progress been made on this front?

**Comment by slackersoft** [comment]
The current way to run your specs in a random order is to call `Env.execute` and pass in a list of spec or suite ids in the order you want the specs to run. When we first started implementing `beforeAll` and `afterAll` we consciously broke this functionality until we could figure out how we wanted to handle arbitrary ordering with the `All`s. We made sure not to release Jasmine in a state where passing an order to `execute` didn't work, but doing so made `All`s behave like `Each`s. This has been changed on master, and they should behave as expected going forward.

**Comment by sdemjanenko** [comment]
Couldn't modifying the [TreeProcessor](https://github.com/meraki/jasmine/commit/94b92be05528225607f091f8170dabff3c3797f2) achieve this?

**Comment by myitcv** [comment]
Would be a big fan :+1: 

Has there been any progress on this front?

@slackersoft - did you have any thoughts on @sdemjanenko's suggestion?

**Comment by myitcv** [comment]
Just seen https://github.com/jasmine/jasmine/pull/927
