### ISSUE TITLE
how to use toEqual to skip undefined?

### ISSUE THREAD

**Issue by atian25** [jasmine/jasmine#592]
`expect({key1:'value1', key2:undefined}).toEqual({key1:'value1'})`

**Comment by alex-okrushko** [comment]
That's not the solution - that's a workaround.

**Comment by slackersoft** [comment]
@alex-okrushko It doesn't make sense for Jasmine to think that `{foo: undefined}` is equal to `{}` which is what would have to happen to make this work, so this isn't something that Jasmine is looking to change.

**Comment by adwiens** [comment]
@slackersoft, very true, nonetheless I am looking for a solution to this as I have a tool that generates tests but for some reason omits the undefined fields. OP's solution is what I need, thus am happy they shared it

**Comment by luchillo17** [comment]
I'm having a jasmine test pass with an undefined property in karma, i think maybe the karma config this project has is replacing jasmine `toEqual` for a lax one that ignores undefined properties, has anyone faced this before?
