### ISSUE TITLE
API reference missing?

### ISSUE THREAD

**Issue by op1ekun** [jasmine/jasmine#596]
Hi guys,

I have been using Jasmine for some time, but I still don't know everything about it. There are still some things that I need to check before writing my tests. While "Introduction" page is great for understanding all the basics it's not helping if you want to find something quickly (I know how to use Ctrl + F, but it is not the best solution). I would really appreciate API reference page so I can quickly find what I'm looking for instead of going through "Introduction" page or googling it.

Thanks!

**Comment by TorstenRobitzki** [comment]
"Jasmine has a rich set of matchers included". I was just searching the documentation for the right matcher for an empty array. As far as I get the current documentation there is no such function (toEqual([] would be the closest). 

I agree with op1ekun that a reference that simply states which functions are available would be very helpful.

One approach to keep API and documentation in synch could be to have examples for every API function and to have something that executes this examples.

**Comment by Digicrat** [comment]
I agree that the documentation for this project could be improved (coming from a user that's evaluating this framework for the first time).  

Have you considered using a library such as JSDuck or JSDoc?  These work similarly to JavaDoc or Doxygen in that you use special comment syntax that combines with smart code parsing to automatically generate API documentation.  Admittedly though the JS tools are not as well developed as those for other languages and may require some experimentation with explicit helper tags to get things detected the way you want.

**Comment by maskedcoder** [comment]
+1

It's very tedious to search through or skim a bunch of code. The main thing missing is a list of available functions, as mentioned by others. Even if it only linked to current examples, it would be a huge improvement. The current documentation is almost useless if I want to quickly find a function.

**Comment by qx** [comment]
+1
Terrible experience! 
eg. toExist method is not list anywhere,except stackoverflow! pleas show us api doc!

**Comment by op1ekun** [comment]
@qx It's sad really... 
I've switched to mocha recently mocha. 
Much easier to get you head around: https://mochajs.org/#assertions

**Comment by Gerg** [comment]
@qx I agree that API-style reference documentation would be useful for Jasmine, especially for matchers. It is work noting, however, that `toExist` is not a core jasmine matcher: https://github.com/jasmine/jasmine/tree/master/src/core/matchers. You must be getting that matcher from another library.
