### ISSUE TITLE
.toEqual fails for objects with the same members but of different types

### ISSUE THREAD

**Issue by adrianton3** [jasmine/jasmine#598]
```
it("should tell me what's the difference between these 2", function () {
  function A() { this.a = 10; }
  function B() { this.a = 10; }
  expect(new A()).toEqual(new B());
});
```

fails, but it does not say why - it only states: `Expected { a : 10 } to equal { a : 10 }.` which is instead true.

**Comment by peterflynn** [comment]
Is there any way to compare the properties of an object and ignore differences in constructor function?  I.e. something like `deepEqual()` in Chai or `_.isEqual()` in Underscore/Lodash, which is how I assumed `toEqual()` would work from reading its docs...

When using JS-style "duck typing" you often don't care about the specific constructor, just which properties the object has after it's created.

**Comment by slackersoft** [comment]
Jasmine does not have a built-in way to do a full deep equality that ignores constructors. This appears to be the same way that Underscore behaves (http://underscorejs.org/docs/underscore.html#section-124).

You could implement a custom equality tester that did this, but it would probably be fairly complicated. Alternatively, you could look at `objectContaining` which does ignore constructors, but will also allow properties.

Thanks for using Jasmine!

**Comment by abramovdmitrii** [comment]
@slackersoft can adding an `expect(obj).toDeepEqual(expected)` matcher to Jasmine be considered at all?
seems like a common use case for `expect(someFunction()).toDeepEqual({a: b})` kind of things, where constructor of the returned object does not matter

**Comment by slackersoft** [comment]
I agree that it would be useful to have some way to deeply compare two objects that doesn't check their constructors (or maybe not any constructors). I'm not sure the best way to get that into Jasmine right now or what exactly to call it.

Because the existing `toEqual` does a deep compare, I think another matcher called `toDeepEqual` would be confusing. It would also probably be nice to be able to use some of the rest of the deep compare code that is already in effect there.

I'm open to other ideas/names/PRs for something like this.

**Comment by glebec** [comment]
`to.mostlyEqual`?

Only half-joking.

**Comment by xfg** [comment]
has this feature been created?

**Comment by dinvlad** [comment]
````
expect(Object.assign({}, objOfTypeA)).toEqual(
  jasmine.objectContaining(Object.assign({}, objOfTypeB))
);
```
Ugly, but it works.

**Comment by slackersoft** [comment]
@dinvlad `objectContaining` doesn't look at constructors when comparing, so the `Object.assign` calls shouldn't do anything. I think the initial request was to do an exact property match which would look more like:

```javascript
expect(Object.assign({}, objOfTypeA)).toEqual(Object.assign({}, objOfTypeB));
```

Which makes me think what we might want is something like a `jasmine.objectWithProperties` asymmetric matcher which explicitly ignores constructors.

**Comment by dinvlad** [comment]
@slackersoft I used `objectContaining` in TypeScript, and there it complains about comparing objects of incompatible types unless I do `Object.assign`. Agreed that we need `jasmine.objectWithProperties`.

**Comment by MattiLehtinen** [comment]
At least in TypeScript spread operator can be also used to instead of `Object.assign` for cleaner syntax:
`expect({...objOfTypeA}).toEqual({...objOfTypeB});`

**Comment by jonyeezs** [comment]
@MattiLehtinen @dinvlad I'm experiencing the exact same thing. Any idea why is it the case TS doesn't seem to take the instance as a POJO?

**Comment by johachi** [comment]
@slackersoft, @dinvlad

This worked perfectly, thank you!

`expect(Object.assign({}, objOfTypeA)).toEqual(Object.assign({}, objOfTypeB));`

**Comment by RudiVuuren** [comment]
You can make use of [jasmine-equal-value](https://www.npmjs.com/package/jasmine-equal-value)

**Comment by DanKing123** [comment]
Just wondering why this has been closed?

Does Jasmine now have a solution for this?

I think the `Object.assign()` solution above is just going to run into the same problem once you start getting into deep comparisons?
