### ISSUE TITLE
Downloading the standalone distribution is pretty unintuitive

### ISSUE THREAD

**Issue by Trevoke** [jasmine/jasmine#603]
I've only found two ways to do it:
1. git clone the jasmine repo, take the zip file out
2. Use the 'Downloads' button to download the jasmine repo, unzip, take the zip file out.

I'd honestly expect something less onerous, like ... Click and download.

**Comment by Protoneer** [comment]
@infews the link you provided to the distribution zip is not working anymore(404). Where else can I find it?

**Comment by Protoneer** [comment]
Never mind I, found it... https://github.com/jasmine/jasmine/releases  (A big download button would make it more obvious though :)

**Comment by Trevoke** [comment]
This was originally why I opened the issue: requiring knowledge of Github to download Jasmine is poor UX.
