### ISSUE TITLE
Adding because descriptions to expect failures

### ISSUE THREAD

**Issue by aleksihakli** [jasmine/jasmine#641]
[In the past](https://groups.google.com/forum/#!topic/jasmine-js/1dG11nfnsu8/discussion) and [elsewhere](https://github.com/adobe/brackets/issues/2752) there has been discussion of adding `.because` property to `expect` chain for [clearer failure classification](http://youtu.be/wdoGVgj1MtY?t=1m30s). The proposed syntax was:

```
expect(true).toEqual(false).because('yes it is')
```

Is there a possibility that this feature could be introduced, a reason it has not been introduced and has the team ever estimated how much work the feature would be to implement? In select cases this could greatly improve the speed of resolving causes for breaks, especially if you're trying to find the cause of failures from a CI log etc.

**Comment by davidemannone** [comment]
So I did it for my own for jasmine 2.0 and the related definitely-typed and I've posted it here: https://github.com/davidemannone/jasmine2.0-explained
Here is how to use it: expect(SOMETHING).toEqual(WHAT-EXPECTED).byFailReport("YOUR-CUSTOM-REPORT!");
and this reports only in case of the match fails this: "Expected SOMETHING to be WHAT-EXPECTED. >YOUR-CUSTOM-REPORT!<
For more details read the Readme.Me file.

**Comment by hartatovich** [comment]
+1 for the "because" !!!!!!!

**Comment by davidemannone** [comment]
Thank you very much!

“Because” or other form is not important (I can change my function name
immediately), but I hope they will introduce something like that officially.

**Comment by michaelhogg** [comment]
+1 for the proposed `.because()` syntax.

+1 to @avrelian for his nice library!

**Comment by ronanamsterdam** [comment]
+1 for because()

**Comment by matthewjh** [comment]
+1

Would be useful to make stuff like this:

````
    expect(this.formElement.isPresent()).toBe(true);
    expect(this.usernameInputElement.isPresent()).toBe(true);
    expect(this.passwordInputElement.isPresent()).toBe(true);
    expect(this.submitButtonElement.isPresent()).toBe(true);
````

more meaningful in the test/ci logs.

**Comment by slackersoft** [comment]
@matthewjh I think what you want for that situation is just a `toBePresent` custom matcher. This will give you a default message of "Expected <element description> to be present". You would also have the ability to specify a custom message if desired. See the docs here: http://jasmine.github.io/edge/custom_matcher.html

**Comment by guy-mograbi-at-gigaspaces** [comment]
@slackersoft - how is your solution better than just having the feature implemented?

**Comment by fpirsch** [comment]
@guy-mograbi-at-gigaspaces :+1: 
@matthewjh Having this feature implemented would be much more versatile than having to code a custom matcher for every single use case.

**Comment by matthewjh** [comment]
Indeed. Writing a custom matcher for the sole purpose of more descriptive messages doesn't seem like a brilliant idea, and, more to the point, *every* time you want a custom message, especially when a more general solution has been proposed. 

Being able to write custom messages inline in tests will also improve readability of the tests.

`jasmine-custom-message` works well, but why can't we implement this in jasmine?

**Comment by slackersoft** [comment]
In general jasmine prefers to have a small but extensible external interface. This allows jasmine's codebase to easier for us to maintain and add features that can only be added in core.

**Comment by pwojnowski** [comment]
Hi. Is this feature going to be implemented?

**Comment by chadjaros** [comment]
+1 for `.because()`

How is this not a thing yet? srsly.

**Comment by matanh-tzmedical** [comment]
+1

**Comment by pidupuis** [comment]
+1

**Comment by gyandeeps** [comment]
Actually felt the need for this feature as in my case I usually have 3-4 expect statements inside test case. So during failure its very difficult to tell which expect is failing.

**Comment by donaldpipowitch** [comment]
It would be so nice to have `.because()`. The output of `expect(myObj.someProp).toEqual(3, 'this means foo');` is suboptimal and I'd never have expected this to work... and it is not really documented, right?

**Comment by keithdtyler** [comment]
I feel the resistance to this feature is based on a cultural difference between unit-testing developers, who are ideally dealing with low-level, simple in / simple out functions to test, and functional test engineers, who are commonly dealing with user-flow scenarios in which simple acts or operational sequences can result in complex outcomes that need to be evaluated in full.

Say for example I write a UI test that looks  up an item and expects certain values of that item to be returned, as well as other conditionals. So when I do A, B, and then C, I expect to see D, E, and F. So I need three expects, for example:

    expect(element(by.xpath("tr/td[1]"))).toEqual('Bob');
    expect(element(by.xpath("tr/td[2]"))).toEqual('true');
    expect(element(by.xpath("tr/td[3]"))).toEqual('true');

If either of the latter two asserts fail, all I will see in the output is:
    Failed
        Expected false to be true.

But this doesn't help me identify which of the assertions failed. I then need to run back to the code to examine which assertion failed. This is pretty inconvenient in a CI environment, where the person reviewing the CI report doesn't have ready access to the code, or which might not include the lines reflecting failed line in a summary view.

But if I could write my asserts like:

    expect(element(by.xpath("tr/td[1]"))).toEqual('Bob').because('Bob's name is Bob');
    expect(element(by.xpath("tr/td[2]"))).toEqual('true').because('Bob is a supervisor so the supervisor    column should say "true"');
    expect(element(by.xpath("tr/td[3]"))).toEqual('true').because('Bob is full time so the full-time column should say "true"');

Now if the second assert fails, I will see something like:
    Failed
        Expected false to be true (because: Bob is full time so the full-time column should say "true")

and I can clearly and unambiguously see what the problem was without having to grab a shovel and go digging.

**Comment by aarongreenwald** [comment]
It feels heavy to create a custom matcher when all you really want is a custom message to make debugging easier. The purpose of tests is to make our workflow more smooth and more reliable, so the ability to quickly write expressive tests that output clear messages is very valuable.

n-thing this request.

**Comment by carlin-q-scott** [comment]
Is this the only assertion library that doesn't provide custom failure messages? I've used many and this is the only one I've come across. It seems unreasonable to not implement such a useful feature that requires such a small amount of code.

**Comment by GabrielShaad** [comment]
+1

**Comment by jaapz** [comment]
If I find myself in a situation where I have multiple asserts in one test where I really want to be clear as to what assert failed and why, I split my test up into multiple tests an wrap them in their own describe block with a beforeEach for their shared data.

For example, this:

```javascript
describe('returnWhateverIsGiven', function() {
    it('should return whatever is given', function() {
        let someobject = new SomeObject();
        expect(someObject.returnWhateverIsGiven(true)).toBe(true);
        expect(someObject.returnWhateverIsGiven(false)).toBe(false);
    });
});
```

would become

```javascript

describe('returnWhateverIsGiven', function() {
    beforeEach(function() {
        this.someobject = new SomeObject();
    });
    it('should return true when given true', function() {
        expect(this.someObject.returnWhateverIsGiven(true)).toBe(true);
    });
    it('should return false when given false', function() {
        expect(this.someObject.returnWhateverIsGiven(false)).toBe(false);
    });
});
```

This way it's clear when a specific assertion fails, because each assertion has their own test name.

**Comment by chadjaros** [comment]
@jaapz This is a workaround and requires writing _more_ code (and more complex code) than would be otherwise required if this feature were implemented.

**Comment by fpirsch** [comment]
@jaapz more code, nested tests... This is exactly what new test frameworks like AVA try to avoid:
> If you think you need nested tests or groups, you're probably better off splitting it up into multiple files (and get the benefit of parallelism) or simplifying your tests.
https://github.com/avajs/ava/issues/222

**Comment by keithdtyler** [comment]
@jaapz That's great for unit tests, not great for functional tests, especially UI flow tests. Especially when you're hoping for functional test results in a CI situation within a certain period of time (whether or not this is a good idea is not usually up to the test developer), you need to keep your tests short, not exhaustive. Thus, multiple asserts in a single flow test is precisely what the doctor ordered - and it's no good if the doctor can't identify the symptoms.

**Comment by PaulL1** [comment]
I think one of the comments earlier was pretty clear that this actually works, it's just undocumented.  You can write

    describe('returnWhateverIsGiven', function() {
        it('should return whatever is given', function() {
            let someobject = new SomeObject();
            expect(someObject.returnWhateverIsGiven(true)).toBe(true, 'should return true when given true');
            expect(someObject.returnWhateverIsGiven(false)).toBe(false, 'should return false when given false');
        });
    });

And it just works because if it fails it prints out all the parameters given to the matcher, even though one of those parameters was superfluous.

**Comment by keithdtyler** [comment]
@PaulL1 Agreed, it works rather well.

**Comment by ronanamsterdam** [comment]
@PaulL1 , @keithdtyler it works, it's undocumented, it can be deprecated at any given point. There should be official API support for this, coz obviously the demand is here. 
Also confused why this discussion is still going. C'mon guys)

**Comment by assertquality** [comment]
+1

**Comment by MatthewHerbst** [comment]
@slackersoft any chance this is still on the radar of the project? As far as I can tell the undocumented version above doesn't work (not that anyone should be relying on it), and @avrelian's [`jasmine2-custom-message`](https://github.com/avrelian/jasmine2-custom-message) seems to be not maintained anymore.

**Comment by avrelian** [comment]
@MatthewHerbst (re [jasmine2-custom-message](https://github.com/avrelian/jasmine2-custom-message)) since it works there no need of fixing

**Comment by jfrioux** [comment]
I use:
`expect(something).toBe(likeThis, "because that's how it should be.")`

And it fits my need and solve this problem for me.

**Comment by MatthewHerbst** [comment]
@jfrioux unfortunately I'm not willing to commit my entire company's code-base to an undocumented feature than could be removed at any time (and as noted above, doesn't seem to work for me anyways).

**Comment by keithdtyler** [comment]
@MatthewHerbst  I suspect not all expects work that way, especially any of the custom expects introduced by Jest.

I don't at all disagree with the points about it being undocumented and potentially unsupported later. I would want to both support and encourage this undocumented feature to be made official and a part of all expects. It actually should perhaps be enhanced to allow you to include custom messages and optionally the failed assertion explanation as well, or even sprintf-style placeholders of the expected and actual values.

**Comment by johnhight** [comment]
Having just stepped into this issue, I still see no solution that works with Typescript. What am I missing?

**Comment by ValentinHruzinski** [comment]
But it don't work with typescript 2.4.* (in my case 2.4.2). May be somebody deside this problem?

**Comment by ErgoSoftUK** [comment]
.toBe(expected, output) seems to work OK, however .toEqual(expected, output) does not.

**Comment by slackersoft** [comment]
Please see [earlier in this thread](https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801) for more discussion on this. Neither case is officially supported by Jasmine.

**Comment by RobertDiPaolo** [comment]
Wow, this is the first test framework I've used (and I've used many in many different languages) that doesn't have support for custom error messages for asserts / exceptions. This is a basic requirement for any test framework and should be available out the box IMHO, it shouldn't require custom code or third party libraries, etc.

**Comment by resah** [comment]
Please reconsider to add `.because `!

We are also running integration tests with protractor and jasmine, which run on complete scenarios. Itis painful to search for the actual cause when a scenario fails and we have to check **all** assertions.

**Comment by Scharnvirk** [comment]
> .toBe(expected, output) seems to work OK, however .toEqual(expected, output) does not.

Thanks. I have the same issue, but I think I can live with toBe - series expects... I have digged a bit into jasmine's code but I can't really see any reason for which toEqual wouldn't work. 



> Please see [earlier in this thread](https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801) for more discussion on this. Neither case is officially supported by Jasmine.

Please reconsider supporting this feature. It is really mandatory for complex test cases.

**Comment by slackersoft** [comment]
I do hear the need for some way to tell Jasmine some sort of description of the value being checked, but I don't think it will be as an additional argument to the matcher itself. I'm leaning more toward something like what is suggested here, but I think `because` might be the wrong word for it. I would prefer something that will work for all matchers without them having to build in support for it in customizing their failure messages further.

**Comment by abdulrahman-khankan** [comment]
Since Jasmine 3.3, there's a way to do it through `withContext`

Example: `expect(someValue).withContext('expected someValue to be true...').toBe(true)`

Source: https://github.com/jasmine/jasmine/issues/1457#issuecomment-435465924

**Comment by ViniciusRio** [comment]
> You can use my library - [jasmine-custom-message](https://github.com/avrelian/jasmine-custom-message).

Update your repository for 3.5, man. Proposal its nice.

**Comment by avrelian** [comment]
@ViniciusRio I suppose `withContext` made `jasmine-custom-message` obsolete.
