### ISSUE TITLE
toHaveBeenCalledWith fails to match parameter object methods

### ISSUE THREAD

**Issue by vs0562** [jasmine/jasmine#652]
Actual code: 
scope.toggle({ getAttribute: function (attName) { return PRIMARY; } });
Unit Test code:
spyOn(scope, "toggle");
expect(scope.toggle).toHaveBeenCalledWith({ getAttribute: function (attName) { return PRIMARY; } });
Fails with the message:
"Expected spy toggle to have been called with [ { getAttribute: Function } ] but actual calls were [ { getAttribute: Function } ]."

**Comment by bennyn** [comment]
I know that this issue is a few "days" old but is there any way to use `toHaveBeenCalledWith` which ignores the method check of objects or uses at least the same approach to combine to methods of an object?

**Comment by slackersoft** [comment]
The `toHaveBeenCalledWith` matcher uses jasmine's equality functionality to determine if the parameters are a match. So you should be able to either setup a [custom equality tester](http://jasmine.github.io/edge/custom_equality.html) or use an [asymmetric equality tester](http://jasmine.github.io/edge/introduction.html#section-Custom_asymmetric_equality_tester) for the particular instance you're checking.

**Comment by dm123455** [comment]
We used to use Teaspoon 0.9.1 and 'toHaveBeenCalledWith' worked perfectly then, but after upgrading to teaspoon-jasmine 2.3.4, all our tests having 'toHaveBeenCalledWith' started failing with the same error as stated above. 
Example:
Expected spy toggleButtonText to have been called with [ ({ context: HTMLNode, selector: '#view-providers' }), 'organization', false ] but actual calls were [ ({ context: HTMLNode, selector: '#view-providers' }), 'organization', false ]
Any idea why?
@infews  @slackersoft 
Thanks in advance for the help!

**Comment by slackersoft** [comment]
Unfortunately, I don't have any insight into Teaspoon and what else might have changed in its versions.
