### ISSUE TITLE
Error: 'null' is not an object (evaluating 'currentSpec.expect')

### ISSUE THREAD

**Issue by hon2a** [jasmine/jasmine#665]
This issue has already been posted on [karma-jasmine page](https://github.com/karma-runner/karma-jasmine/issues/37), but it is a `jasmine` issue.

As my test suites grew large (over 1100 specs), I started getting the following error: `'null' is not an object (evaluating 'currentSpec.expect')` during test execution (using _grunt_ + _karma_ + _karma-jasmine_ and testing an app written using _AngularJS_). The error would stop the test execution somewhere around spec #700 and report no details. It would consistently trigger during the subsequent executions. It would only disappear after I removed or disabled a spec (any spec, not necessarilly the previously added one). It seems the problem is simply with the suite being too large.

@Mironor created a [fix candidate](https://github.com/karma-runner/karma-jasmine/commit/5304205d4e5de0cbd1c22a68fc8fdbd2722cfc06) which fixed this problem for me. If you could include it in the next 2.x version of Jasmine or fix this total blocker in some other way, I'd be much obliged.

**Comment by editedredx** [comment]
Anyone still having trouble:
The problem for me was that I had an expect after the async done call, it resulted in the same error.
It basically broke almost all tests after the broken one making it a hard debug.

**Comment by MWalid** [comment]
@editedredx  that was my issue too ...

**Comment by worldspawn** [comment]
I got this error with some code that created a promise and rejected it (although rejecting it didn't seem to matter) and then returning it AFTER calling done(), the calling code would call .then on the result.

I think the key is to do absolutely nothing after calling `done()`

**Comment by slackersoft** [comment]
When you call `done()` you are explicitly telling Jasmine that this step has completed and it is ok to move on to the next thing in the queue.
