### ISSUE TITLE
Feature request: Format long JSON failures nicely

### ISSUE THREAD

**Issue by elanakoren** [jasmine/jasmine#668]
When you're comparing a big JSON object to an expectation, the result is long, unwieldy, and hard to read. (See screenshot below.) Could Jasmine format/pretty-print these?

Thanks! 

![screen shot 2014-09-12 at 4 15 16 pm](https://cloud.githubusercontent.com/assets/3656487/4258436/aa3c1d18-3ad2-11e4-901c-dd1c5362bdc8.png)

**Comment by slackersoft** [comment]
I'm going to close this as a duplicate of #675. Please take further discussion there.

Thanks for using jasmine!
