### ISSUE TITLE
Feature request: Harmony/Generators support

### ISSUE THREAD

**Issue by xpepermint** [jasmine/jasmine#670]
I don't know where to post this feature request https://github.com/mhevery/jasmine-node/issues/349 so I'll do again:

As I speak with nodejs developers the majority love `--harmony` features (generators, yields) and they often complain about slow adoption that new cool features. That includes me ;). Well, once you start with e.g. `koajs` you can not go back to the old tracks. The code simply becomes sexy and clean. 
My proposal is to make `jasmine` the first framework that support generators. This would become a `must-have` framework for me and many others who love beautiful code.

``` js
it('should support generators', function*() {
   var d = yield do('here we go')
   expect(d).toBe('awesome')
})
```

**Comment by hyzhak** [comment]
```it('should support generators', co(function*() {
   var d = yield do('here we go')
   expect(d).toBe('awesome')
});

**Comment by sebastienbarre** [comment]
Has there been any development on this one? I'm having a tough time testing ES6 generators with Jasmine (and [suspend](https://github.com/jmar777/suspend)), did someone find a sure way to make it work? Thank you

**Comment by briandipalma** [comment]
@sebastienbarre I used Mocha in the end.

**Comment by sebastienbarre** [comment]
@briandipalma thanks. Would you happen to have a gist or a file on Github I could look at, for inspiration?

**Comment by briandipalma** [comment]
Maybe [this will help](https://github.com/briandipalma/br-analyzer/blob/master/spec/aspect-spec.js)?

**Comment by sebastienbarre** [comment]
@briandipalma Thanks! I think it will.

**Comment by bloveridge** [comment]
Sorry to revive an old topic, but I was looking for something similar and so just wrote it myself. https://github.com/gradecam/jasmine-co

It allows you to write specs like:

```js
var userId = 'abc123';
it('should track books that are listed for sale', function*() {
    var book = yield bookService.getBooksForUser(userId)[0];
    yield book.listForSale(3.99);
    var forSale = yield bookService.getBooksListedForSaleByUser(userId);
    expect(forSale[0].isbn).toEqual(book.isbn);
});
```

As the name suggests, it uses `co` under the covers and allows you to write specs in a more functional / synchronous style.
