### ISSUE TITLE
Publish to CDN

### ISSUE THREAD

**Issue by mwisnicki** [jasmine/jasmine#676]
Publishing to CDN or providing other means of using jasmine in jsfiddle would be very useful.

**Comment by rohit** [comment]
I think Google folks select which libraries get hosted on GoogleCDN. Maybe there is a way to get in touch with them? An alternative I've found with a little searching is https://cdnjs.com. Already versions `2.0.0` and `1.3.1` are available there. They have started using some kind of automated git setup discussed here: https://github.com/cdnjs/cdnjs/issues/3638 Also check the repo Readme for more information: https://github.com/cdnjs/cdnjs

I guess if you really want this you can make the necessary requests/PR over at cdnjs and things should work. This issue can be closed? /cc @slackersoft

**Comment by slackersoft** [comment]
Sent in a pull request for cdnjs to auto update jasmine to get new versions https://github.com/cdnjs/cdnjs/pull/4205

Closing this.
