### ISSUE TITLE
 TypeError: 'null' is not an object (evaluating 'currentSpec.$injector') + Phantom JS and Jasmine on grunt

### ISSUE THREAD

**Issue by DavidAsish** [jasmine/jasmine#677]
[4mRunning "jasmine:src" (jasmine) task[24m
Testing jasmine specs via PhantomJS

 Cards controllers
   cardsListController
     - should return 2 cards......×
       TypeError: 'null' is not an object (evaluating 'currentSpec.$injector') in file:///D:angular-mocks.js (line 2015) (1)
       TypeError: 'null' is not an object (evaluating 'currentSpec.$injector') in file:///D:angular-mocks.js (line 2015) (2)
       TypeError: 'null' is not an object (evaluating 'currentSpec.$modules') in file:///D:angular-mocks.js (line 2138) (3)

1 spec in 0.002s.
[31m>> [39m1 failures
[33mWarning: Task "jasmine:src" failed. Use --force to continue.[39m

[31mAborted due to warnings.[39m

**Comment by amejiarosario** [comment]
I have the same issue! It's weird I only see this error when I run the whole suite, if I run the single test by itself it show

```
	TypeError: 'null' is not an object (evaluating 'currentSpec.$injector')
	    at /Users/admejiar/workspace/eos/client/bower_components/angular-mocks/angular-mocks.js:2267
	    at processQueue (/Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:13292)
	    at /Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:13308
	    at /Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:14547
	    at /Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:14363
	    at /Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:14652
	    at done (/Users/admejiar/workspace/eos/client/bower_components/angular/angular.js:9734)
	    at handleResponse (/Users/admejiar/workspace/eos/client/bower_components/angular-mocks/angular-mocks.js:1216)
	    at /Users/admejiar/workspace/eos/client/bower_components/angular-mocks/angular-mocks.js:1572
```

**Comment by slackersoft** [comment]
The internals of Jasmine were heavily rewritten for the 2.0 release and angular mocks designed for older versions may not work in the new version. Additionally, `currentSpec.$injector` is not provided by jasmine itself, but by angular-mocks, so I would take your issue up with them first.

**Comment by himdel** [comment]
The bug is probably caused by PhatomJS not having `Function#bind` implemented. You may need to provide a shim..

**Comment by josencv** [comment]
Had the same problem. Never found the root cause, but reinstalling local npm and bower components solved it for me.

**Comment by asim-qb** [comment]
```
TypeError: 'null' is not an object (evaluating 'currentSpec.$injector')
at /home/user/Development/project/bower_components/angular-mocks/angular-mocks.js:2310
PhantomJS 1.9.8 (Linux 0.0.0): Executed 956 of 1214 (4 FAILED) (4.798 secs / NaN secs)

```

I too had the issue. Rerunning the test solved the issue though.
