### ISSUE TITLE
Allow test to return Promise as an alternative to the done callback

### ISSUE THREAD

**Issue by analog-nico** [jasmine/jasmine#681]
As proposed in issue #567 Jasmine should allow a test to return a Promise as an alternative to using the `done` callback for async testing.

A test would not specify the `done` callback as its parameter and would return a Promise:

``` js
it('should pass', function () {
  return new Promise(function (resolve, reject) {
    resolve('value');
  });
});

it('should fail', function () {
  return new Promise(function (resolve, reject) {
    reject(new Error('reason'));
  });
});
```

**Comment by mjackson** [comment]
It would be really, really awesome if this worked. :(

**Comment by OliverJAsh** [comment]
IMO this is enough reason to use Mocha instead of Jasmine. :+1: to this change.

**Comment by piuccio** [comment]
@OliverJAsh agree

**Comment by wmadden** [comment]
It'd really be great to see support for Promise return values in Jasmine. Using Promises would mean that Jasmine can internally take advantage of the advances entering the language in ES6, like the `async` function.

**Comment by slackersoft** [comment]
Given that jasmine still supports IE8, we won't be able to actually use any of the other new features that aren't supported by the older browsers we still want to work with.

**Comment by wmadden** [comment]
@slackersoft: you don't need any explicit dependency on a Promise implementation to add this behavior.

@bilalq provided sample code that would work. In browsers with no implementation of Promises it'd simply not return a "thenable" and have no effect.

**Comment by wmadden** [comment]
Sorry, I think I misunderstood your last comment. You're right, you won't be able to take advantage of the new JS features in the output code, but you'd still be able to use them with a compiler like Babel.

At any rate the biggest advantage would be to the users of Jasmine, rather than the authors.

**Comment by joezimjs** [comment]
http://www.sitepoint.com/promises-in-javascript-unit-tests-the-definitive-guide/
This seems a lot nicer than using `done` and `done.fail`. The reasoning that I saw for not supporting this sounds like you are just too lazy to add it, though I guess some sort of plugin or library that can handle this and is compatible with Jasmine would work just fine as well.

**Comment by joezimjs** [comment]
Anyone who wants some better Promise compatibility:
https://www.npmjs.com/package/jasmine-promise-matchers

This is something like the [chai-as-promised](https://github.com/domenic/chai-as-promised/) as mentioned in the article that I linked in my previous comment. This still isn't quite as nice as being able to return a promise, but it's a step in the right direction.

**Comment by matthewjh** [comment]
I needed this and wrote a small module to handle returning Promises from jasmine test fns.

https://www.npmjs.com/package/jasmine-promises

````javascript
describe('my fancy thing', function () {
    beforeEach(function () {
        return doSomePreparatoryTaskThatIsAsync();
    });
 
    it('should be extra fancy', function () {
        return fancyAsync().then(function (thing) {
            expect(thing).toBeFancy();
        });
    });
});
````

Might be useful for some of you guys.

**Comment by joezimjs** [comment]
DARN YOU @matthewjh!!! I was in the middle of creating the very same thing! Of course, mine is "better" ;)

**Comment by ewinslow** [comment]
I really think the position of the Jasmine team here should be reconsidered. Another reason to support Promise-returning functions: `async/await`:

```js
it('has some async behavior', async function() {
  var result = await someAsyncTask();  
  expect(result.value).toBe(expectedValue);
});
```

It's just annoying boilerplate to make this work with done/done.fail:

```js
it('has some async behavior', async function(done) {
  try {
    var result = await someAsyncTask();  
  } catch (e) {
    done.fail();
  }

  expect(result.value).toBe(expectedValue);
  done();
});
```

**Comment by joezimjs** [comment]
I agree with @ewinslow 
A plugin is great, but I've never liked the idea of trying to make sure all our plugins are being kept up-to-date with the main library, especially when you may need multiple plugins. If the plugins were maintained by the team that maintained the main libray (e.g. Jasmine team made a Promise-compatible plugin and maintained it with Jasmine), then I'm ok with the plugin because updates are more likely to occur at the same time.

In any case, async/await is coming, and in fact already exists with tools like Babel, so this really should be something that Jasmine supports.

**Comment by dcleao** [comment]
I need this feature badly. Mocha moved on from done/done.fail. You should too.
http://tobyho.com/2015/12/16/mocha-with-promises/

**Comment by joezimjs** [comment]
@dcleao You can get this feature using this plugin for now: https://www.npmjs.com/package/jasmine-promises.
Still, it'd be nice to see this "officially" supported.

**Comment by connor4312** [comment]
It would be great if we could get this feature in. Moreso than they were in 2014, Promises have become standard and ubiquitous. The ES7 proposals and inclusion in core browser APIs such as Fetch indicate that this trajectory is unlikely to change. Mocha has also had promise support for about two years.

This would be a fairly small change in the codebase and may be implemented without any backwards-incompatible behaviour. It'd be a huge quality of life improvement for many developers, including myself! :)

**Comment by monkpit** [comment]
https://github.com/jasmine/jasmine/pull/1356 seems to have added this?

**Comment by sgravrock** [comment]
@monkpit Yes.

**Comment by ibrahimbensalah** [comment]
I would like to share my solution / hack which is in my opinion could very well be built-in, with no additional complexity to existing code. Evidence is given by this code:

I am running jasmine from jspm command line:
> npx jspm run spec/runner

then in my file spec/runner.ts I have first, the jasmine import and configuration for who ever is looking for a complete working example, followed by an override of the <code>it</code> function from the jasmine core, and finally the bootstrapping of the jasmine runner <code>jasmine.execute()</code>.

```
import Jasmine = require("jasmine")
jasmine.config({
    "spec_dir": "spec",
    "spec_files": [
        "**/*[sS]pec.js"
    ],
    "helpers": [
        "helpers/**/*.js"
    ],
    "stopSpecOnExpectationFailure": false,
    "random": true
});
let assertAsync = (assertion?: (done?: DoneFn) => void | { then: Function }) => {
    return (done?: DoneFn) => {
        let result = assertion(done);
        if (result && typeof result.then === "function")
            result.then(done, done.fail);
        else
            done();
    }
};

global['it'] =
(jasmineIt => (expectation: string, assertion?: (done: DoneFn) => void, timeout?: number) => jasmineIt(expectation,
    assertAsync(assertion),
    timeout))(it);

// require statements will be resolved by jspm / systemjs. refer to jspm.io to find more info
require("./specs/myAsyncSpec");

jasmine.execute();

```

**Comment by BenoitZugmeyer** [comment]
@ibrahimbensalah Jasmine supports promises since [v2.7.0](https://github.com/jasmine/jasmine/blob/master/release_notes/2.7.0.md) (more than a year ago).
