### ISSUE TITLE
beforeAll is not defined

### ISSUE THREAD

**Issue by enricorotundo** [jasmine/jasmine#704]
I'm using Protractor 1.4.0 that should include jasmine but doing this:

``` javascript
describe('Create album', function() {
  beforeAll(function () {
    ...
  });
});
```

Give me this error: `ReferenceError: beforeAll is not defined` but the [jasmine doc](http://jasmine.github.io/edge/introduction.html#section-Setup_and_Teardown) refer it.

**Comment by sandy-adi** [comment]
@slackersoft I'm using protractor 1.6.1 which I see is dependent on jasmine 2.1.1, but when I run my tests using the protractor command I get the error ReferenceError: beforeAll is not defined

**Comment by amavisca** [comment]
@sandy-adi Are you actually specifying jasmine2 in your protractor config file? The default jasmine is 1.3.x in protractor.

**Comment by sandy-adi** [comment]
@amavisca are you saying that even though protractor 1.6.1 is dependent on jasmine 2.1.1 it still uses jasmine 1.3.x? Could you please tell me how to enforce protractor to use jasmine2?

**Comment by Pyo25** [comment]
I'm in front of the same problem using karma and the module karma-jasmine.
My package.json specifies:
 - "jasmine-core": "^2.2.0",
 - "karma": "~0.12.9",
 - "karma-jasmine": "^0.2.2",

And the methods `beforeAll` and `afterAll`are undefined.

**Comment by slackersoft** [comment]
From what I can tell from the karma-jasmine release notes, it looks like they started relying on the jasmine-core package around v0.3.0 (possibly also v.0.2.3). So you might need to update your karma-jasmine version to be able to use jasmine-core with `beforeAll`

**Comment by Pyo25** [comment]
Upgrading to karma-jasmine v0.3.5 solved the problem !

Thank you @slackersoft

**Comment by sandy-adi** [comment]
@amavisca sorry for the delayed response. I was out on a long vacation and just catching up on my messages. The problem was with the config file as you pointed out. Changed the conf value to jasmine 2 and it works now. Thank you.
