### ISSUE TITLE
Done handling still isn't quite right

### ISSUE THREAD

**Issue by JonnyRa** [jasmine/jasmine#709]
I'm on version 2.0.2 

Think there were some pretty big changes to this from 2.0 and it's made it loads better but I'm getting the following problem:

if you have a setup like this:

```
beforeEach(function(done){
    console.log('start');
    doSomethingThatWillCall(done);
    doSomeOtherStuff();
    console.log('end of beforeEach');
});

it('is a test', function(){
    console.log('in test');
});
```

If doSomethingThatWillCall calls done immediately (rather than in an asynchronous manner) then you end up dropping into the test before the subsequent call is done.  Eg you'd get the following in the console:

'start'
'in test'
'end of beforeEach'

Im not sure where the fix would go in the jasmine code but I'd suggest you could do something like this when the before each is run

```
function functionThatSortsItOut(beforeEachFunction, existingDoneFunction) {
    var endReached = false;
    var triedToCallDoneEarly = false;

    var patchedDone = function () {
        triedToCallDoneEarly = true;

        if(!endReached)
            return;

        existingDoneFunction();
    };

    beforeEachFunction(patchedDone);
    endReached = true;

    if(triedToCallDoneEarly)
        existingDoneFunction();
}
```

It sort of feels like that could be simpler but it's nearly home time and i'm tired!

That way it calls done only if the end of the function has already been hit - either when it gets run or later when done gets called asynchronously.

---

As a bit of an aside nice one with including beforeAll and afterAll... although I've not tried them out yet (I've patched in my own version of beforeAll already).  I really like this library - in particular nesting suites is a really great feature - lets you save repeating setup code and bits of test names + something that puts it ahead of similar frameworks in other languages.

**Comment by JonnyRa** [comment]
So the fix turned out to be extremely simple.

I just pasted my function into jasmine.js and then modified attemptAsync like this:

    @@ -1671,7 +1671,7 @@
           }
     
           try {
    -        fn.call(self.userContext, next);
    +        functionThatSortsItOut(fn.bind(self.userContext), next);
           } catch (e) {
             handleException(e);
         next();

**Comment by allan-bonadio** [comment]
I think the solution in the initial post is the way to go.  You could simplify it by making a function, that counts how many times it's been called, and on the second call, from whatever upper code, it calls done().

**Comment by slackersoft** [comment]
This situation should be much improved in recent versions of Jasmine (2.7 I think?). Basically what happens now is we force asyncness in the case that `done` is called in a synchronous manner in order to ensure the suite is in a known good state.

Hope this helps. Thanks for using Jasmine!
