### ISSUE TITLE
Support multiple createSpyObj in one call

### ISSUE THREAD

**Issue by VWoeltjen** [jasmine/jasmine#713]
I use a lot of constructor-style dependency injection and like to use spy objects in place of those dependencies in my tests. As a consequence, my suites tend to start with a lot of `jasmine.createSpyObj` calls (one for each injected dependency, plus one for any secondary object I need/want to spy on as a return value from one of those dependencies)

It would save me some typing and improve readability if I could reduce that to one call, something like (note the pluralization of createSpyObjs):

```
var deps = jasmine.createSpyObjs({
    something: [ "someMethod", "someOtherMethod" ],
    somethingElse: [ "yetAnotherMethod" ],
    // and so on...
});
```

...and get back one object which contains all the mocks I need. (The keys above would be the names of the spy object, and the values would be the names of the spies in those mocks.)

For purposes of illustration, a trivial (and non-robust) implementation of this would look like:

```
function createSpyObjs(interfaces) {
    var result = {};
    Object.keys(interfaces).forEach(function (k) {
        result[k] = jasmine.createSpyObj(k, interfaces[k]);
    });
    return result;
}
```

It's easy enough to add that as a helper function to achieve the above, but it would be nicer still if it came free in the box with Jasmine.

Any chance of getting this built into a future version of Jasmine? I'd be happy to handle the implementation (along with appropriate input-checking and "you're using it wrong" warnings), if this is something that project maintainers feel is appropriate to include.

**Comment by slackersoft** [comment]
We haven't heard any other feedback from the community on this issue, and the next version of jasmine should include the ability to `createSpyObj` without naming the object, so my second example could just be:

````javascript
var something = jasmine.createSpyObj(['one', 'two']);
var another = jasmine.createSpyObj(['three', 'four']);

callTheThing(something, another);
````

Closing this. Thanks for using jasmine.
