### ISSUE TITLE
jasmine.any() method for matching only simple objects

### ISSUE THREAD

**Issue by bostrom** [jasmine/jasmine#715]
I ran into the issue of jasmine.any(Object) returning true for all types of objects including, but not limited to, Arrays. This is of course natural since Javascript Arrays are also Objects, but what if I want to assert that an object is, in fact, a simple object and not an array. 

Example:
```
var foo = {a: 2};
var bar = ['a', 2];
expect(foo).toEqual(jasmine.any(Object)); // -> ok!
expect(bar).toEqual(jasmine.any(Object)); // -> also ok! I'd like it to fail here.
```

I'm not proposing a change to the jasmine.any(Object) function, but is there a way to extend the behaviour of jasmine.any() to support checking that an object is a simple object and not, for example, an array?

More specifically, what I want to achieve is something like this
```
var data = {
  name: 'Foo',
  props: {},
  props2: []
};
expect(data).toEqual(jasmine.objectContaining({
  name: jasmine.any(String),         // ok!
  props: jasmine.any(Object),        // should be ok
  props2: jasmine.any(Object)        // should fail here, since props2 is an array
}));
```
Any ideas how to achieve this without modifying the behaviour of jasmine.any(Object)?

**Comment by slackersoft** [comment]
As of 2ab22951a13267dd078d4181ca2cdc21ff510b22 we should have a nicer way to accomplish this. If you have an object that has an `asymmetricMatch` function, that function will be invoked by jasmine when testing equality and passed the object being compared. `asymmetricMatch` should return `true` or `false`. I'm working on getting some docs up for this functionality as well.

**Comment by slackersoft** [comment]
Docs for how to create your own asymmetric matcher are here: http://jasmine.github.io/2.2/introduction.html#section-Custom_asymmetric_equality_tester

I'm not sure if this is something we need in core, as the use case seems pretty specific, so I'm going to close this issue given we've made it possible to provide your own matcher.

Thanks for using jasmine!

**Comment by fpoljak** [comment]
You can workaround this with something like this:

    expect(data).toEqual(jasmine.objectContaining({
      name: jasmine.any(String),
      props: jasmine.any(Object),
    }));
    expect(typeof(data.props2)).toEqual('Object');
    expect(data.props instanceOf Array).toBeFalsy(); // should fail
