### ISSUE TITLE
Adding a window.onload handler hangs jasmine

### ISSUE THREAD

**Issue by venustus** [jasmine/jasmine#727]
I've a source script which has an assignment statement to window.onload. Whenever I run the test using phantomjs, it just hangs without any output and browser does not exit. To narrow down the problem, I just downloaded fresh copy of jasmine-standalone-2.1.3.zip, unzipped and opened SpecRunner.html in my browser and it worked fine.

I edited SpecRunner.html with the following:

``` html
 <script src="lib/jasmine-2.1.3/boot.js"></script>

  <script type="text/javascript">
    window.onload = function() { alert("onload"); };
  </script>
  <!-- include source files here... -->
  <script src="src/Player.js"></script>
  <script src="src/Song.js"></script>
```

After this if I open SpecRunner.html, it displays nothing. I'm getting the alert though. But jasmine seems to have crashed/hanged.

I'm using Chrome on MAC OS X 10.10.

Can you please help?

**Comment by mattixpet** [comment]
if you are the one which overwrote `window.onload`, you can do instead `window.addEventListener('load', function(){}, false)` to not mess with jasmine.
