### ISSUE TITLE
beforeAll/afterAll don't work with focused specs

### ISSUE THREAD

**Issue by hankduan** [jasmine/jasmine#732]
`beforeAll` and `afterAll` will run once per spec (like `beforeEach` and `afterEach`) when you use focused specs:

```
describe('focused spec', function() {
  var passed;

  beforeAll(function() {
    console.log('beforeAll')
    passed = 0;
  });

  afterAll(function() {
    console.log('afterAll')
    expect(passed).toEqual(2);
  });

  iit('should pass1', function() {
    ++passed;
  });

  iit('should pass3', function() {
    ++passed;
  });
});
```

The output is: 
```
beforeAll
afterAll
FbeforeAll
afterAll
F

Failures: 
1) focused spec should pass1
1.1) Expected 1 to equal 2.
    Error: Expected 1 to equal 2.
        at Object.<anonymous> (/workspace/minijasminenode/spec/focused_spec.js:11:20)

2) focused spec should pass3
2.1) Expected 1 to equal 2.
    Error: Expected 1 to equal 2.
        at Object.<anonymous> (/workspace/minijasminenode/spec/focused_spec.js:11:20)

2 specs, 2 failures
Finished in 0.007 seconds
```

**Comment by slackersoft** [comment]
It sounds like this is resolved now, so I'm going to close this issue. Please re-open if you feel it hasn't been fully resolved.

**Comment by juliemr** [comment]
FYI -this behavior is causing some confusion for Protractor users - see https://github.com/angular/protractor/issues/1743.

It would be great if it could be addressed in a future version, or if there were a good place to point to for documentation on how `fit` or `fdescribe` will affect your test run.

**Comment by dtabuenc** [comment]
Not only does it run once for each it, but it seems to run additional times as well. Please see here:

http://jsfiddle.net/openspectrum/wzAyL/

**Comment by Gerg** [comment]
I pushed a fix for the additional `beforeAll` runs.

We agree that the interaction between `beforeAll`/`afterAll` and `fit`/`fdescribe` is confusing. We would like to change this in a future release.

**Comment by PaddyMann** [comment]
Wondering why this was closed - is there a separate location we can track progress on this being fixed? (i.e. beforeAll / afterAll only being called once with a focused describe block)

**Comment by slackersoft** [comment]
As of Jasmine 2.3, `beforeAll` and `afterAll` should behave the same with focused suites as without. I.e. they should only run once, instead of before each spec.

**Comment by pooja10404** [comment]
I'd like to execute some code when a particular suite fails. I'd imagine that there there a place, a hook or callback of some kind which can be invoked if there is a failure in a suite.

Can you add an example of this to one of the suites and point me to it?
