### ISSUE TITLE
Double-nested xdescribe breaks entire spec

### ISSUE THREAD

**Issue by chge** [jasmine/jasmine#733]
This spec doesn't work with default `SpecRunner.html` on `2.1.3`:

```javascript
describe('1st', function() {
	describe('2nd', function() {
		xdescribe('3rd', function() {
			it('works', function() {
				expect(true).toBe(true);
			});
		});
	});

	it('works', function() {
		expect(true).toBe(true);
	});
});
```

When I change `xdescribe` to `describe` it works fine.

**Comment by rohit** [comment]
Just tried this on master and the output:

![jasmine-issue-733](https://cloud.githubusercontent.com/assets/14514/5716375/6b2b8f4a-9b13-11e4-9a0e-1755e5d7130c.png)

**Comment by slackersoft** [comment]
Sounds good. Closing.
