### ISSUE TITLE
Possibly confusing failure message by toThrow and toThrowError matchers

### ISSUE THREAD

**Issue by rohit** [jasmine/jasmine#735]
```
1) Hamming throws error when strands are not equal length
  Message:
    Expected function to throw Error: DNA strands must be of equal length., but it threw Error: DNA strands must be of equal length.
```

The above failure message is confusing because the two error strings look alike. The actually thrown error is missing a full stop: "DNA strands must be of equal length". This is while running jasmine via CLI in node.

IMHO this should give a non confusing error message but I don't know what should be done. On the one hand the full stop could be removed from the error message but then the message is different in style from the others. I think the following output would be better:

```
1) Hamming throws error when strands are not equal length
  Message:
    Expected function to throw
      Error: DNA strands must be of equal length.
    but it threw
      Error: DNA strands must be of equal length
```

By splitting the message over multiple lines I think we can remove the full stop from the error message.

Another option, as suggested by @joshuacc, is to surround the error text with quotations.

```
1) Hamming throws error when strands are not equal length
  Message:
    Expected function to throw "Error: DNA strands must be of equal length.", but it threw "Error: DNA strands must be of equal length"
```

This might be the simplest although splitting onto multiple lines does look nice IMHO. :grin:

_EDIT ~5 mins: Added suggestion to surround by quotes_

**Comment by joshuacc** [comment]
Simply putting quotation marks around the error text would remove the ambiguity as well.

**Comment by rohit** [comment]
@slackersoft I'd be happy to make a PR for this if it's desirable to fix. If yes then any preference on how to fix?

**Comment by slackersoft** [comment]
Quoting the error message is probably the nicest solution for now. We haven't fully solved pretty printing messages for `console` (node) and html.

**Comment by rohit** [comment]
Hmm one problem is it's not necessary to throw a string you could throw a number for e.g. There is already some quoting in the specs of `toThrow` and `toThrowError` so I don't think wrapping everything thrown with quotes is a good idea.

Separating the expected and actual on different lines would be useful IMHO but if pretty printing is still being discussed/thought-about then I guess this issue should be closed.

**Comment by slackersoft** [comment]
`toThrow` and `toThrowError` both use the jasmine `PrettyPrinter` to display the message being thrown, so strings should be being wrapped in quotes.

I'd be interested to see an example spec where you were seeing this now.

**Comment by slackersoft** [comment]
If you expect the function to throw an actual `Error` object you should probably use `toThrowError` which will properly quote the message when displaying a failure message. If you use `toThrow`, jasmine's pretty printer ends up falling back to calling `toString()` on the `Error` objects and that is what generates the message you see.

Given this, I'm going to close this issue.

Thanks for using jasmine!
