### ISSUE TITLE
SpyRegistry clearSpies() puts inherited methods onto target prototype

### ISSUE THREAD

**Issue by coderagebbc** [jasmine/jasmine#737]
One of the issues we're having migrating tests from JSTestDriver with sinon to with Jasmine is that we cannot run our tests in a randomised order.

This is rooted in the use of inheritance and the way in which Jasmine returns spied on function back to their original values (I don't want to get into a debate on composition over inheritance at this stage, I probably agree with you).

What happens is when we have a function on the prototype that comes from a superclass n levels up (we're currently using a variant of resig's Class()), jasmine takes a copy of the original based on it as being a member of the subclass. https://github.com/jasmine/jasmine/blob/master/src/core/base.js#L60

In clearSpies() it returns the value back onto the subclass - 
https://github.com/jasmine/jasmine/blob/master/src/core/SpyRegistry.js#L43

This unfortunately hides the superclass behaviour which is breaking our other tests when not run in specific orders.

There are three possible solutions to this.
1. Check for hasOwnProperty when creating the spy and throw an exception when the property does not exist.
2. return the function back to the superclass only
3. do nothing.

I have potential solutions for 1 and 2 and wonder what the community thinks is the best approach before I put in a PR.

option 3 suggests this is not really a problem - and I'd be interested in hearing arguments as to whyu this is the case. Genuinely,

Rich

**Comment by slackersoft** [comment]
I'm not totally sure I understand what exactly is happening. It sounds like you're getting a function from the parent prototype put into the child prototype, but that doesn't seem like it would cause an issue.

**Comment by coderagebbc** [comment]
I'll put together some code within the next day or so, and screenshot some console, that might explain it better.

**Comment by coderagebbc** [comment]
I guess I could go as far to say that is exactly the case, and that does cause spying problems for us whilst we are migrating our approach to test to jasmine (which is awesome btw). I'm also not sure that it should behave this we since it's isn't properly returning objects to their correct former state on teardown.

**Comment by slackersoft** [comment]
I think I better understand the issue now. We'd be happy to review a pull request that detected an original method that was from up the prototype chain and deleted the spy property from the object instead of putting the original method in its place upon cleanup.

**Comment by ryanswood** [comment]
This bit us too. We automatically assert that no global properties were added, which we implement by checking `_(window).keys()` before and after each example. In our case, we spy on window.print, which adds the `print` method directly to `window` causing our test to fail.
