### ISSUE TITLE
toMatch("url(./a.png)") is no match

### ISSUE THREAD

**Issue by 59naga** [jasmine/jasmine#738]
hi.
```js
css="url(./a.png)"
expect(css).toMatch("url(./a.png)")
// > Expected 'url(./a.png)' to match 'url(./a.png)'.
```
This behavior is expected?

replaced
```js
expect(css.indexOf("url(./a.png)")).toBeTruthy() // passed
```

**Comment by slackersoft** [comment]
`toMatch` is intended for regular expression matching. As such, a string passed in will be passed to the `RegExp` constructor and any RegExp special characters in your string (e.g. `(`, `.`, `)`) will be treated differently.

Possibly you want to use `toContain` for partial string match or `toEqual` for full string match.

**Comment by 59naga** [comment]
`throw new myself` ok, understood.
