### ISSUE TITLE
Multi-line error messages are rendered in a weird order

### ISSUE THREAD

**Issue by mzgol** [jasmine/jasmine#742]
The following test:
```js
it('test title', function () {
    jasmine.addMatchers({
        toAAA: function () {
            return {
                compare: function () {
                    return {
                        pass: false,
                        message: 'a\nb\nc\nd',
                    };
                },
            };
        },
    });
    expect(true).toAAA();
});
```
gives the following output:
```
Chrome 39.0.2171 (Mac OS X 10.10.1)  test title FAILED
	b
	c
	d
	Error: a
	    at Object.<anonymous> (/PATH:column:row)
Chrome 39.0.2171 (Mac OS X 10.10.1): Executed 1 of 1 (1 FAILED) ERROR (0 secs / 0.038 secs)
```
i.e. lines from the second to the last one are printed first, then `Error: ` and the first line of the message. This reads weirdly, especially if the second line is a continuation to the first. I'd expect the following:
```
Chrome 39.0.2171 (Mac OS X 10.10.1)  test title FAILED
	Error: a
	b
	c
	d
	    at Object.<anonymous> (/PATH:column:row)
Chrome 39.0.2171 (Mac OS X 10.10.1): Executed 1 of 1 (1 FAILED) ERROR (0 secs / 0.038 secs)
```
I couldn't find any documentation about this behavior at http://jasmine.github.io/2.1/custom_matcher.html

OS X 10.10.1, native Terminal.app, Jasmine 2.1.3 fired via [karma](https://github.com/karma-runner/karma) 0.12.31 and [karma-jasmine](https://github.com/karma-runner/karma-jasmine) 0.3.4, Node 0.10.35 and 0.11.14.

**Comment by slackersoft** [comment]
I'm not seeing this same behavior with just bare jasmine-core. The `HtmlReporter` seems to be reporting roughly as expected:

![screen shot 2015-01-12 at 4 23 02 pm](https://cloud.githubusercontent.com/assets/512724/5713962/4ed84a64-9a77-11e4-9c6a-99f38aff2b11.png)

It's possible this is a karma issue in some way that they are transposing the error message.

**Comment by slackersoft** [comment]
It looks like jasmine itself is reporting the error as you would expect, so it seems like this isn't an issue with jasmine, but rather how karma is reporting errors from jasmine.

I'm going to close it, but let us know if you can isolate it something more jasmine specific.

Thanks for using jasmine!
