### ISSUE TITLE
toThrow fails on PhantomJS but works good on Chrome and Firefox

### ISSUE THREAD

**Issue by Maks3w** [jasmine/jasmine#748]
OS: Windows 8.1 x64
Browsers:
* Chrome 39.0.2171 (Windows 8.1)
* Firefox 35.0.0 (Windows 8.1)
* PhantomJS 1.9.8 (Windows 8)

Stack:
* node: 0.10.33 (x64)
* karma: 0.12.31
* karma-jasmine: 0.3.4
* jasmine: 2.1.1

The error message:

> Error: Expected function to throw { code: 500, name: 'generic error', message: 'error message' }, but it threw { code: 500, name: 'generic error', message: 'error message', line: 9, sourceId: 84165968, sourceURL: 'c:/***/ApiRequest.js', stack: '[object Object]

Expected: SUCCESS

Spec:
```js
      var expectedError = new API.Ws.Errors.ValidationError(
        500,
        "generic error",
        "error message"
      );
      expect(function () {
        ApiRequest.testForLogicalError(response)
      }).toThrow(expectedError);
```

SUS:
```js
// API.Ws.Errors.ApiLogicErrror.js
var API;
(function (API) {
    var Ws;
    (function (Ws) {
        var Errors;
        (function (Errors) {
            "use strict";
            var ApiLogicError = (function () {
                function ApiLogicError(code, name, message) {
                    this.code = code;
                    this.name = name;
                    this.message = message;
                }
                return ApiLogicError;
            })();
            Errors.ApiLogicError = ApiLogicError;
        })(Errors = Ws.Errors || (Ws.Errors = {}));
    })(Ws = API.Ws || (API.Ws = {}));
})(API || (API = {}));

// API.Ws.Errors.ValidationErrror.js
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var API;
(function (API) {
    var Ws;
    (function (Ws) {
        var Errors;
        (function (Errors) {
            "use strict";
            var ValidationError = (function (_super) {
                __extends(ValidationError, _super);
                function ValidationError(code, name, message, messages) {
                    _super.call(this, code, name, message);
                    this.messages = messages;
                }
                return ValidationError;
            })(Errors.ApiLogicError);
            Errors.ValidationError = ValidationError;
        })(Errors = Ws.Errors || (Ws.Errors = {}));
    })(Ws = API.Ws || (API.Ws = {}));
})(API || (API = {}));
```

**Comment by slackersoft** [comment]
It looks like when the error is thrown in phantomjs it acquires some extra metadata about where it was thrown from. The `toThrow` matcher uses jasmine's deep compare functionality to check equality of the thing thrown vs the thing expected to be thrown, so this check fails in phantom.

You might be able to use something like `jasmine.objectContaining` to only compare the part of the object you care about to work around this issue.

Thanks for using jasmine!

**Comment by slackersoft** [comment]
This seems like it's an issue with how phantom is treating errors when they get thrown and not necessarily an issue with jasmine itself. I'm going to close it since `objectContaining` seems like it should be a good workaround.

If this doesn't work please let us know.

**Comment by Maks3w** [comment]
With objectContaining the result is worst. All browers fails

> Expected ValidationError({ code: 422, name: 'Unprocessable Entity', message: 'Failed Validation', messages: Object({ input_param: 'generic message', another_param: 'error message' }) }) to equal <jasmine.objectContaining(ValidationError({ code: 422, name: 'Unprocessable Entity', message: 'Failed Validation', messages: Object({ input_param: 'generic message', another_param: 'error message' }) }))>.

**Comment by Maks3w** [comment]
Finally I needed to create a plain object with the properties.

`expect(<ApiLogicError>).toEqual(jasmine.objectContaining(<ApiLogicError>));` works OK
`expect(<ValidationError>).toEqual(jasmine.objectContaining(<ValidationError>));` Fail.
`expect(<ValidationError>).toEqual(jasmine.objectContaining(<ApiLogicError>));` works OK.

Seems to be a problem when an object extend from other (ValidationError extends from ApiLogicError)

**Comment by slackersoft** [comment]
`objectContaining` is designed to work with just a bare javascript object, and not the result of calling a constructor function. It's possible this is failing in a way similar to #769 and `Object.defineProperty`, in which case this might actually work as you expect on master with `objectContaining`.

**Comment by slackersoft** [comment]
Closing this, since it sounds like you've got it working with `objectContaining` and it seems like it's primarily an issue with what different browsers do when an `Error` is thrown.

Thanks for using jasmine!
