### ISSUE TITLE
Testing async features that can't receive a done() callback

### ISSUE THREAD

**Issue by tiagorg** [jasmine/jasmine#749]
I have authored a very simple preCondition instruction for Jasmine 2.0's way of async testing.

I found it necessary for some types of asynchronous features that will complete on their own and won't allow the user to pass a callback where ```done``` would be fired, like rendering Google Maps, images or anything else that can change both the DOM and the CSSOM.

While it is utterly possible to re-implement waitsFor, I believe that Jasmine 2.0 direction is more towards stepping away from this idea and instead taking more advantage of done callbacks, like putting one it block as a pre-condition for another.

I would love to receive some feedback from you guys to see if you agree with this approach. It is available here https://github.com/tiagorg/jasmine-precondition and also on NPM.

And if you ever feel like this idea can evolve towards something getting incorporated into the official Jasmine library, I would love to chip in as well :)

With the preCondition it would be possible to do something like: (I can provide a Google Maps example as well)

    describe('the preCondition instruction', function () {

      var counter1 = 0,
          counter2 = 0,
          interval;

      beforeEach(function(done) {
        interval = setInterval(function(){
          counter1 += 100;
        }, 100);

        preCondition(function() {
          return counter1 >= 500;
        }, done, 100);
      });

      it('should only get executed when counter1 is 500', function (done) {
        expect(counter1).toBe(500);

        preCondition(function() {
          counter2 += 200;
          return counter2 === 1000;
        }, done, 100);
      });

      it('should only get executed when counter2 is 1000', function () {
        expect(counter2).toBe(1000);
      });

      afterEach(function(){
        clearInterval(interval);
      });
    });

**Comment by slackersoft** [comment]
This looks like it could be a useful add-on for jasmine. Since it looks like you didn't have to make any changes to the core of jasmine, I think it makes sense for you to publish it and see how much traction it gets.

Thanks for contributing to the jasmine ecosystem.

Closing.

**Comment by tiagorg** [comment]
Outstanding! Thanks Gregg! :)

**Comment by gregor-w** [comment]
Looks very helpful to me.... :+1:

**Comment by mmzoo** [comment]
Pretty useful, thank you @tiagorg 

I needed this to see if a partial is loaded via ajax (in my fixtures). I had no trigger other than waiting :)

```coffeescript
it 'loads the header', (done) ->
  preCondition (-> $('#header_partial').length > 0), done
```

**Comment by tiagorg** [comment]
Awesome! You're welcome @mmzoo !
