### ISSUE TITLE
SpiderMonkey 24 compatibility

### ISSUE THREAD

**Issue by ptomato** [jasmine/jasmine#751]
I'm working on a [Jasmine runner](https://github.com/ptomato/jasmine-gjs) for the GJS interpreter (whose engine is SpiderMonkey 24) and when it loads the Jasmine core it complains about a few things:

```
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 481]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 638]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 742]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 995]: function Clock does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1109]: function DelayedFunctionScheduler does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1387]: function buildExpectationResult does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1474]: function FakeDate does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1437]: function MockDate does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1686]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 1764]: function ReportDispatcher does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 2280]: function asymmetricMatch does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 2299]: function eq does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 2223]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 2760]: function toThrowError does not always return a value
Gjs-Message: JS WARNING: [/Users/fliep/gtk/inst/share/jasmine-gjs/jasmine.js 72]: assignment to undeclared variable getJasmineRequireObj
```

At several places in Jasmine there's a `return` statement followed by more code, which is mainly what it's complaining about. The code following the `return` seems to be just functions, so it's harmless, but it would be nice to get rid of the complaints.

The final line is complaining about a variable that isn't declared with `var` in `requireCore.js`.

In addition, Jasmine's timers don't work as expected because `jasmineGlobal` doesn't get set properly in `getJasmineRequireObj()`. I think for SpiderMonkey the code should check for the existence of `window` just like it does for `global` in node.js.

I'll prepare a pull request for both of these compatibility problems.

**Comment by slackersoft** [comment]
The offending `return` statements are intended to be before some of the supporting functions to more easily delineate those supporting functions from the overall algorithm.

For the global object, I think we prefer to get it by passing in the implicit `this` to the function instead of looking for `window` specifically. If this isn't working in SpiderMonkey, I think I'd rather see a fallback to `window` if we couldn't find a global to always setting the global to `window` if `window` is defined.

**Comment by ptomato** [comment]
In that case, would you consider moving the supporting functions to come before the algorithm? I think what SpiderMonkey is complaining about is that there is code after an unconditional `return`.

For the global object, the problem is that `this` is set to the module object rather than the global object when you import the Jasmine module. So Jasmine thinks it gets a global object, but it's not _the_ global object. (This is probably actually the fault of GJS's import machinery, rather than SpiderMonkey.)

**Comment by infews** [comment]
The style of private functions is a conscious choice and we want to keep it. 

We're happy to take a pull request that helps  us truly get the global object in a case for SpiderMonkey.

**Comment by ptomato** [comment]
Thanks for the feedback. I've split the pull request into two pull requests:

- #752 fixes two of the SpiderMonkey linting complaints - I believe that these two at least can be fixed without interfering with Jasmine's coding style. (I'll be patching jasmine.js in my Jasmine for GJS runner to silence the warnings anyway, but I'd prefer to diverge as little as possible from upstream Jasmine.)

- On reflection I think the global object problem is specific to the GJS interpreter and not its SpiderMonkey engine. #757 sets the global object to `window` in a special case which I'm pretty sure is GJS-specific.

**Comment by slackersoft** [comment]
Given that these pull requests have been merged, can we close this issue?

**Comment by ptomato** [comment]
Thanks! I think it's fixed for me.
