### ISSUE TITLE
Is it possible to use 'beforeEach(module('app'))' code on separated external file?

### ISSUE THREAD

**Issue by joowh85** [jasmine/jasmine#756]
For example:
Testing AngularJS code with the Jasmine.

app_helper.js
```
   beforeEach(module('adminApp'));
```

app_test_controller_spec.js.coffee
```
describe 'TestController', ->
	scope = $location = controller = undefined
	beforeEach inject ($rootScope, $controller, _$location_) ->
		$location = _$location_
		scope = $rootScope.$new()
		controller = $controller 'TestController', {
			'$scope': scope
		}

	it 'should success', ->
		expect(2).toEqual(3)
```

Currently this code not works.

Is another way to use 'beforeEach(module('app'))' code on separated external file?

**Comment by slackersoft** [comment]
This looks like more of a "how to test?" question than an issue with jasmine itself. Please ask the group at jasmine-js@googlegroups.com.

Closing.
