### ISSUE TITLE
Update to Jasmine Test Framework (JasmineTest) NuGet package

### ISSUE THREAD

**Issue by abulhasanlakhani** [jasmine/jasmine#759]
Currently Nuget only shows JasmineTest version 2.0.0 whereas the Jasmine Github shows 2.1.3 released on December 4th 2014. Please update the NuGet version of JasmineTest to the latest version along with its TypeDefinitions (https://github.com/borisyankov/DefinitelyTyped/issues/3522).

Thanks

**Comment by slackersoft** [comment]
The jasmine core team doesn't maintain a NuGet package for jasmine. You'll want to find out who has released that package and ask them to release a new version.

Closing this. Thanks for using jasmine.
