### ISSUE TITLE
Run `afterAll` and `afterEach` even after spec failure

### ISSUE THREAD

**Issue by gyandeeps** [jasmine/jasmine#760]
I think the `afterAll` and `afterEach` should run even if the `spec` fails. Sometimes its needed to because we might be doing some clean up work inside `after` and `afterEach` functions.

Example would be:
Let say I am testing a module which copies a directory recursively into a different directory. Now after the test is over I want to delete the newly created a directory as a cleanup.

Its like in the `database` world, when you test you manipulate the data inside the tables but when your test finishes you always `rollback` the changes regardless of failure or success.

**Comment by slackersoft** [comment]
This should be the current functionality. What version of jasmine are you using? How are you running jasmine? Do you have an example spec/suite that demonstrates the problem?

**Comment by gyandeeps** [comment]
Not able to reproduce now. Will reopen the issue if see that happening again.
Sorry about that.
