### ISSUE TITLE
why this project named jasmine?

### ISSUE THREAD

**Issue by kimmking** [jasmine/jasmine#762]
why this project named jasmine?

**Comment by slackersoft** [comment]
@infews did a bit of explanation in his [blog post about the 2.0 release](http://pivotallabs.com/jasmine-2-release/).

In general we like to keep github issues as actual issues with jasmine itself and not questions about the framework. In the future please take questions like this or about how to test something to the jasmine-js@googlegroups.com mailing list.

Thanks for using jasmine. Closing.
