### ISSUE TITLE
Pretty Printer should be updated to reflect changes in Array comparison.

### ISSUE THREAD

**Issue by jamestalmage** [jasmine/jasmine#766]
While `toEqual()` has been updated to compare custom properties on arrays. Pretty printer is only [looping from 0 to length](https://github.com/jasmine/jasmine/blob/v2.2.1/src/core/PrettyPrinter.js#L80), this is bound to cause confusion, as you can have unequal values display exactly the same.

**Comment by jwngr** [comment]
Here is an example of this:

```
it('repro', function() {
  var a = [1,2,3];
  var b = [1,2,3];
  a.$id = 'foo';
  expect(a).toEqual(b);
});
```

The test passed in Jasmine 2.1.3 but now fails in Jasmine 2.2.0 with this confusing error message:

```
repro
  Expected [ 1, 2, 3 ] to equal [ 1, 2, 3 ].
```

From the 2.2.0 changelog, it appears the change from passing to failing for this test was intentional. However, the error message should be improved to reduce confusion.

**Comment by slackersoft** [comment]
I agree that the message isn't clear. How would you expect array properties to be pretty printed?

**Comment by jamestalmage** [comment]
`console.log()` in Chrome prints it like this:
```
[ 1, 2, 3, 4, '$id': 'foo' ]
```
I think that is a good choice.

**Comment by slackersoft** [comment]
Sounds good. We've made a story for it here: https://www.pivotaltracker.com/story/show/87644044

**Comment by jwngr** [comment]
Awesome, thanks for the super quick turnaround here!

**Comment by danilanna** [comment]
Cool!! Thanks for the help!
