### ISSUE TITLE
v2.2 jasmine.objectContaining doesn't work with Object.defineProperty

### ISSUE THREAD

**Issue by logankd** [jasmine/jasmine#769]
I'm using TypeScript to create classes. The properties are added with Object.defineProperty. When I update from Jasmine 2.0 to 2.2 my test started failing. This same test passes in v2.0.

Here's my test:
```javascript
var myObject = (function () {
			function myObject(id){
				this.a = ['a','b','c'];
				this.empty = [];
				this._id = id;
				this.update = function(differentT){
					// pretend this is a real function to spyOn
					
				}
			};
			return myObject;
		 })();
		Object.defineProperty(myObject.prototype, "id", {
            get: function () {
                return this._id;
            },
            enumerable: true,
            configurable: true
        });
describe("Object containing and toHaveBeenCalledWith", function() {
		
	it('objectContains matcher with property', function(){
		var t2 = new myObject(444);
		spyOn(test, 'update');
		test.update(t2);
		expect(test.update).toHaveBeenCalledWith(jasmine.objectContaining({ id: 444 }));
	});
});
```
Is there a workaround or can the equality be improved?

```Object.prototype.hasOwnProperty.call(other, property)``` is false in the expect above

Extra Note: I had about 7 broken tests (of 900) after updating.
* expect(myObject.array).toEqual([]) from Knockout observable arrays using the ES5 plugin. had to be changed to myObject.array.length).toBe(0)
*  or comparing arrays values to splitting it to:
expect(acceptedTypes[0]).toBe(accepts[0]);			
expect(acceptedTypes[1]).toBe(accepts[1]);			
expect(acceptedTypes[2]).toBe(accepts[2]);

I'm not sure how I feel about those changes breaking my tests.

**Comment by Gerg** [comment]
It appears that this test is now failing because the property is defined on the object's prototype. Either way, they should probably still match, so we will work on a fix. 

For the array equality expectations, do the arrays have properties defined on them? Jasmine 2.2 compares array properties when checking equality. There was an [issue](https://github.com/jasmine/jasmine/issues/766) with printing array equality failure messages in 2.2, which should be fixed on master. 

It might make sense for there to be a matcher that only compares indexed array values, though I'm not sure exactly what that would look like. Would you find this useful?

**Comment by logankd** [comment]
Here is more information and some tests to duplicate the array issues I'm seeing.
The Chrome debugger shows it as Array[0] with a lot of extra functions. model.saleList instanceof Array is true.
![jasminearray](https://cloud.githubusercontent.com/assets/1636977/6063143/af943ea2-ad1a-11e4-9df3-384bce2b5538.png).

TS example: 
```javascript
class Model {
  public saleList: Sale[];
  constructor(saleList: Sale[] = []){
   this.saleList = saleList;
   ko.track(this, ['saleList']);
  }
}
// output JS
var Slot = (function () {
        function Slot(saleList) {
            var _this = this;
            if (saleList === void 0) { saleList = []; }
            this.saleList = saleList;
            ko.track(this, [
                'saleList',
            ]);
....
```

Heres some examples of the equality for arrays I ran into with Knockout. You'll need Jasmine 2.2, Knockout 3.2.0 and Knockout ES-5
```javascript
var myObject = (function () {
	function myObject(id, list){
		this.a = ['a','b','c'];
		this.empty = [];
		this._id = id;
		this.update = function(differentT){
			// pretend this is a real function to spyOn
			
		}
		if(list === void 0) { list = [] };
		this.list = list;
		ko.track(this, ['list']);
	};
	return myObject;
 })();
Object.defineProperty(myObject.prototype, "id", {
	get: function () {
		return this._id;
	},
	enumerable: true,
	configurable: true
});
describe("Equals", function() {
	describe('toEqual and toBe', function() {
		 var test;
		 beforeEach(function(){			
			var l = [1,2,3];
			test = new myObject(133, l);
		 });
		 /*
		it('passes if arrays are equal', function() {
			var arr = [1, 2, 3];
			expect(arr).toEqual([1, 2, 3]);
		});
		
		it('passes if arrays are equal 2', function() {
			var arr = ['a', 'b', 'c'];
			var exp = ['a', 'b', 'c'];
			expect(arr).toEqual(exp);
		});
		
		it('passes if array from object is same', function() {
			var exp = ['a', 'b', 'c'];
			expect(test.a).toEqual(exp);
		});
		
		it('empty array not toEqual', function() {
			expect(test.empty).toEqual([]);
		});
		it('empty array toBe', function() {
			expect(test.empty).not.toBe([]);
		});
		it('[] toEqual', function() {
			expect([]).toEqual([]);
		});
		it('[] not toBe', function() {
			expect([]).not.toBe([]);
		});
		
		it('[] not toBe', function() {
			expect([]).not.toBe([]);
		});*/
		
		it('objectContains matcher with property', function(){
			var t2 = new myObject(444);
			spyOn(test, 'update');
			test.update(t2);
			expect(test.update).toHaveBeenCalledWith(jasmine.objectContaining({ id: 444 }));
		});
		
		it('ES5 Knockout array should still be equal []', function(){
			expect(test.list).toBe([1,2,3]);
		});
		
		it('ES5 Knockout array empty is [] fails', function(){
			// this passed in v2.0
			test = new myObject(133);
			expect(test.list).toEqual([]);
		});
		it('ES5 Knockout array now with 2.2 we have test if initialized to []', function(){
			test = new myObject(133);
			expect(test.list.length).toBe(0);
		});
	});
});
```

Thanks!

**Comment by Gerg** [comment]
I just pushed a fix for the prototype properties.

The array tests are failing because they have additional properties. For example 
```js
it('ES5 Knockout array should still be equal []', function(){
  expect(test.list).toBe([1,2,3]);
});
```
now fails with the message `Expected [ 1, 2, 3, pop: Function, push: Function, reverse: Function, shift: Function, sort: Function, splice: Function, unshift: Function ] to be [ 1, 2, 3 ].`

It seem that some Jasmine users care about non-numerical array properties and other don't. I think it makes sense to cater to both groups, but I'm not sure exactly what the matchers would look like. Definitely open to suggestions.

**Comment by logankd** [comment]
Thanks for the quick responses and code fix. I like the message that comes out now.

http://stackoverflow.com/questions/15717844/jasmine-js-comparing-arrays has a custom matcher to compare the values inside of the array. I don't like the name, tried out toBeSameArrayValues (there's probably a better name). I think the toEqual and toBe would stay the same as you have it and to have a custom matcher in the core for array comparison.

something like (modified from the SO answer):
```javascript
toBeSameArrayValues: function(array) {
		  this.message = function() {
			return "Expected " + JSON.stringify(this.actual) + " to be array " + JSON.stringify(array) + ".";
		  };
		  var arraysAreSame = function(x, y) {
			debugger;
			var arraysAreSame = true;
			if(!x){ return false; }
			for(var i; i < x.length; i++)
			{
				if(x[i] !== y[i])
				{
				   arraysAreSame = false;
				}
			}
			 return arraysAreSame;
		  };
		  return arraysAreSame(this.actual, array);
		}
	});
it('ES5 Knockout array now with 2.2 we have test if initialized to []', function(){
	expect(test.list).toBeSameArrayValues([1,2,3]);
});```

I wasn't able to get the matcher attached, this was the window, so I didn't test this a whole lot.

**Comment by logankd** [comment]
Just checking in again... We're using the version with the change set and it's working well. I would like to see an array value matcher in there. Did you get a chance to look at it and have some ideas?

**Comment by slackersoft** [comment]
Glad to hear its working!

`toBeSameArrayValues` sounds ok, but I think I might prefer something like `toMatchArray` for the name.

We'd be happy to review a pull request that added a matcher that matched either all of the items in an array in any order or only in a specific order.

Thanks for using jasmine!

**Comment by logankd** [comment]
Since I figured out pull requests, I'll try and get toBeSameArrayValues  added in at some point (hopefully by the end of June)
