### ISSUE TITLE
Spy on non–property functions

### ISSUE THREAD

**Issue by mightyiam** [jasmine/jasmine#771]
Is there a way to spy on a function which is not a property of an object? I'm thinking something like

``` javascript
var foo = function() {
  // awesomize something
}
var spy = spyOn(foo).and.callThrough()
```

**Comment by gyandeeps** [comment]
I also want to know the answer to this question.
There is a way to do this in sinonJs.
http://sinonjs.org/docs/#spies

**Comment by joshuacc** [comment]
@mightyiam @gyandeeps Are you looking for [jasmine.createSpy](http://jasmine.github.io/2.2/introduction.html#section-Spies:_%3Ccode%3EcreateSpy%3C/code%3E)?

**Comment by mightyiam** [comment]
@joshuacc Thank you. I don't think so because it has no implementation behind it.

I'm looking to wrap my existing function. `jasmine.createSpy` can't seem to do that.

**Comment by joshuacc** [comment]
@mightyiam Ah. I see. You can do this with `and.callFake` like so:

```js
var spy = jasmine.createSpy().and.callFake(function () {
  console.log("I'm being called!");
});

spy();
// => "I'm being called!"
```

**Comment by gyandeeps** [comment]
Lets say I am trying to test `add` function in this code:

```.js
function add(a, b){
    var result = 0;
    
    if(validParameters(a, b)){
        return a + b;
    }
    else{
        return null;
    }
}

function validParameters(x, y){
    //do something
}
```

So when I am testing `add` function, how want to fake `validParameters` function and return different values to test my `add` function behavior.

I think that's what @mightyiam wants to know.

**Comment by joshuacc** [comment]
@gyandeeps Hmm. You can do that if `validParameters` is in the global scope.

```js
spyOn(window, "validParameters").and.callThrough()
```

However, if `validParameters` is in a local scope, that is impossible. JS doesn't provide a way to access local scopes from the outside.

**Comment by gyandeeps** [comment]
hmm... I was also thinking about the same.

**Comment by mightyiam** [comment]
I would like to create a spy by providing an existing function and having a wrapper spy returned.

So I think that
``` javascript
var myFunc = function(myArg) {
  myArg++
}
var spiedOnMyFunc = jasmine.createSpy().and.callFake(myFunc)
var i = 0
spiedOnMyFunc(i)
expect(spiedOnMyFunc).toHaveBeenCalled()
expect(i).toEqual(1)
```
Will work, right?

Thank you, @joshuacc and @gyandeeps.

**Comment by gyandeeps** [comment]
The value would be `passed by value` so `expect(i).toEqual(1)` would fail.

**Comment by mightyiam** [comment]
Oh, excuse me.
``` javascript
var i = 0
var myFunc = function(myArg) {
  i = myArg
}
var spiedOnMyFunc = jasmine.createSpy().and.callFake(myFunc)
spiedOnMyFunc(1)
expect(spiedOnMyFunc).toHaveBeenCalled()
expect(i).toEqual(1)
```
Updated the fiddle.
