### ISSUE TITLE
Specs inside xdescribe are not reported at all

### ISSUE THREAD

**Issue by Derbeth** [jasmine/jasmine#774]
See http://jasmine.github.io/2.2/introduction.html: xdescribe "A spec" contains a spec "is just a function, so it can contain any code". This nested spec is completely ignored in Jasmine results:

1. nested "it" is counted in the total number of tests, but appears neither in executed nor in skipped tests, so the numbers don't sum up and cause confusion ("Ran 80 of 81 specs - run all / 80 specs, 0 failures, 3 pending specs" - so, are there 80 or 81 specs?)
2. you cannot find the "it" text nowhere in the report, only the text of "xdescribe" can be seen

**Comment by slackersoft** [comment]
I think it probably makes sense that `it`s in an `xdescribe` should be reported the same as if they were all `xit`s. We'd be happy to review a pull request that implemented this.
