### ISSUE TITLE
jasmine.clock().install() doesn't throw errors when called multiple times

### ISSUE THREAD

**Issue by mik01aj** [jasmine/jasmine#782]
I believe it should, because when I have 2 tests like this:

```
it('a', function (done) {
    jasmine.clock.install(); 
    // ... some async code, calling done() when it's finished ...
    jasmine.clock.tick(100); // this runs the async code
    jasmine.clock.uninstall(); // and this doesn't get called (this is a bug in my test)
}

it('b', function () {
    jasmine.clock.install(); 
    // ... init theThing - it will be ready in 2 ticks ...
    jasmine.clock.tick(1);
    expect(theThing.isReady).toBe(false); // normally this would be ok, nut now will fail because of unnecessary ticks (because of bug in the test a)
    jasmine.clock.tick(1);
    expect(theThing.isReady).toBe(true);
    jasmine.clock.uninstall();
}
```

What happens here? The test `a` succeeds and `b` fails. But `b` fails only because `a` didn't clean up after itself! This introduces subtle dependencies between tests and makes tests using Jasmine clock a nightmare to debug in big projects.

I know that I should call `jasmine.clock.install()` from `beforeEach`, and so on, i.e. I know this isn't a good test. But I would expect the testing framework to do some sanity checks like these for me. And I would expect the test framework to do its best to make each test case independent of each other.

I'm using jasmine `2.2.0`.

**Comment by infews** [comment]
Your example isn't clear. Can you provide a full suite (`describe`, etc.) that shows the problem?

**Comment by mik01aj** [comment]
Damn... I wasn't able to reproduce this on a simple example. So I'll just paste a few pieces of my code.

Here's the test case that breaks stuff:
```
var ModelStore = require('../ModelStore');
var Promise = require('es6-promise').Promise;

// mocking the module using rewireify
ModelStore.__set__('axios', {
    get: function () {
        console.log('A ha!');
        return new Promise(function(fullfill, reject) {
            fullfill({
                status: 200,
                data: {
                    things: [
                        {hello: 'world'},
                    ],
                },
            });
        });
    },
});

describe('ModelStore', function () {
    it('aaaa', function (done) {
        jasmine.clock().install();
        var s = new ModelStore('http://example.com/things', 'things');
        s.get(123).then(function (thing) {
            console.log('asdfasdf');
            expect(thing).toEqual({hello: 'world'});
            done();
        });
        jasmine.clock().tick(100);
        jasmine.clock().uninstall();
      });
});
```

And this is the test being broken:

```
var Promise = require('es6-promise').Promise;

describe('PromiseWrapper', function () {
    var promise, fulfill;

    beforeEach(function () {
        jasmine.clock().install();
        promise = new Promise(function (_fullfill) {
            fulfill = _fullfill; // saving the callback
        });
        expect(fulfill).toEqual(jasmine.any(Function));
    });

    afterEach(function () {
        jasmine.clock().uninstall();
    });

    it('should use a predictable promise implementation', function () {
        var promiseFulfilled = false;
        promise.then(function() {
            promiseFulfilled = true;
        });
        expect(promiseFulfilled).toBe(false);
        fulfill();
        expect(promiseFulfilled).toBe(false);
        jasmine.clock().tick(1); // Waiting for the callbacks
        expect(promiseFulfilled).toBe(true);
    });
});
```

**Comment by slackersoft** [comment]
It sounds like this might be related to #792  which has been fixed, but not released. Can you try it again on master and see if the problem is fixed?

Thanks.

**Comment by mik01aj** [comment]
Still the same behaviour.

Btw, this might be related to https://github.com/jasmine/jasmine/issues/790.

**Comment by mik01aj** [comment]
Btw, the documentation says:

> A spy only exists in the describe or it block it is defined, and will be removed after each spec.

I think it's a great idea. But why doesn't it work the same for clocks? This would be just great and doesn't seem hard to implement. After a spec using `jasmine.clock().install()` is finished, Jasmine could:

a) check if the clock was uninstalled and throw an error if it wasn't, OR
b) uninstall the clock silently to prevent test pollution.

What do you think?

**Comment by slackersoft** [comment]
The clock actually used to automatically uninstall itself at the end of a spec it had been installed in. The functionality changed in 2.0, due to some of the refactoring that was done around how all the functions for a spec are run.

In 1.x it was possible to append an `afterEach` while the spec was running, but this functionality was removed in 2.0. This meant that external plugins that used to do this (like jasmine-ajax) had to be converted to need an explicit uninstall step in an `afterEach`. We decided it made sense for the clock to not have special behavior, that other plugins couldn't replicate, so this kind of behavior would be consistent.

**Comment by mik01aj** [comment]
I see. But how do the spies do it then?

**Comment by slackersoft** [comment]
Spies are cleaned up at the end of the scope they are declared in because when spying, you can set up arbitrary functionality for an external function. But with the clock, you put it into a specific (mocked) state until you uninstall it.

We'd be happy to review a pull request that made the clock throw an error if it was told to install on top of timing functions that weren't the real ones from the global object. This would also cause the clock to throw if installed over itself.

**Comment by mik01aj** [comment]
Btw... I got another idea: what if you would mock the timer using `spyOn(window, 'setTimeout').and.callFake(...);`? This would unbind the timer when the test is finished.

**Comment by longmatthewh** [comment]
I'm using grunt-contrib-jasmine, which recently pulled in jasmine-core 2.0.3, and it appears this change is now breaking my specs with the new exception. I'm using jasmine.clock().install() in the beforeEach() and  jasmine.clock().uninstall() in the afterEach(), and still getting the exception.

**Comment by longmatthewh** [comment]
I found a spot where I was using install/uninstall in a spec (per documentation this allowed) and moved them to the beforeEach/afterEach and received the exception several more times.

**Comment by longmatthewh** [comment]
Figured it out...not sure if what we were doing was bad. We were using jasmine.clock().install() and jasmine.clock().uninstall() appropriately. In the spec, we were also spying on window.clearInterval, which through off the new check that was added.
