### ISSUE TITLE
expect().toEqual() with arrays fails (sometimes)

### ISSUE THREAD

**Issue by Sventric** [jasmine/jasmine#786]
When i got a failed test with the message "`Expected [ 1, undefined ] to equal [ 1, undefined ].`" i almost started to doubt myself.

This is easy reproducable with the following code.

```javascript
var t1 = [1];
t1.length = 2;
expect(t1).toEqual([1, undefined]);
```
(used jasmine 2.2.0)

**Comment by Gerg** [comment]
It looks like this is probably the pretty printer issue from #766.

**Comment by Sventric** [comment]
If that is the case what is the difference between `arr1` and `arr2`?

```javascript
var arr1 = [1];
arr1.length = 2;

var arr2 = [1, undefined];
```

Yes, `arr1` was internally only 1 long, but what does an internally (and 'hidden'?) state have to do with equality.
Both objects are `Array`s and both arrays have a length of 2 and both have a value on the first index and both have undefined on the second index.

After playing around a little it maybe is a question what do we call equal. Same behavior or identical structure. For the previous sample the difference is 'easy' detectable with code below or via a for-in loop.

```javascript
var arr1_is_fully_explicit = arr1.hasOwnProperty(1); // -> false
var arr2_is_fully_explicit = arr2.hasOwnProperty(1); // -> true
```

**Comment by Gerg** [comment]
It is currently failing because
```js
Object.keys(arr1); // -> ["0"]
Object.keys(arr2); // -> ["0", "1"]
```
It appears that Underscore's toEqual (on which Jasmine's equality is based) does still say the two arrays are equal. 

As you have identified, defining equality is a tricky problem. For now, if this behavior is important to you, I would recommend creating a [custom equality tester](http://jasmine.github.io/2.2/custom_equality.html).

**Comment by wim82** [comment]
i might have the same issue, where comparing arrays gives me a not equal, even though they are (or should be) the same.

    error: - Expected [ 'a', 'b' ] to equal [ 'a', 'b' ]

for code:

       element(by.className('search-summary')).all(by.className('keyword')).getText().then(function(summary) {
            console.log(summary);
            console.log(expectedSummary);

            expect(summary).toEqual(expectedSummary);

when doing a console.log i get the exact same result. Or console.log is hiding something i can't see.

**Comment by slackersoft** [comment]
@wim82 what version of jasmine are you using? The pretty printer should be printing out all properties for an array as of version 2.3.0 to match with the comparison logic.

**Comment by molehillrocker** [comment]
We are facing a similar issue with Jasmine 2.4.1. The test case to reproduce is:

```
it('should prepend elements to array', function() {
  var array = [];
  array.length = 2;

  var originalArray = ['yes', 'no', 'maybe'];
  var expectedArray = [undefined, undefined, 'yes', 'no', 'maybe'];

  expect(array.concat(originalArray)).toEqual(expectedArray);
});
```

The error message is ``Expected [ undefined, undefined, 'yes', 'no', 'maybe' ] to equal [ undefined, undefined, 'yes', 'no', 'maybe' ].``

Our current workaround is to convert the arrays to a JSON string and compare those.

```
it('should prepend elements to array', function() {
  var array = [];
  array.length = 2;

  var originalArray = ['yes', 'no', 'maybe'];
  var expectedArray = [undefined, undefined, 'yes', 'no', 'maybe'];

  var actualJSON = JSON.stringify(array.concat(originalArray));
  var expectedJSON = JSON.stringify(expectedArray);

  expect(actualJSON).toEqual(expectedJSON);
});
```

**Comment by JamieCorkhill** [comment]
I can confirm the same anomaly. In my case, I wasn't comparing to arrays, but rather two objects.

I have an object, which I send to MongoDB. I then query the database for that same document, get it back, and confirm the response is the same as the object I originally sent.

I receive the following in the console: 

```
Expected value to equal:
{"_id": "abc123", "author": {"firstName": "John","lastName": "Doe"}
Recieved:
{"_id": "abc123", "author": {"firstName": "John","lastName": "Doe"}

Compared values serialize to the same structure. 
Printing internal object structure without calling `toJSON` instead.
```
I can confirm that wrapping both objects in `expect()` an `toEqual()` in `JSON.stringify()` solves this issue.

**Comment by slackersoft** [comment]
@JamieCorkhill what version of Jasmine are you using? That looks like a older error message from `toEqual`. Newer Jasmine versions should include more details about differences (constructor possibly) and breakdowns of which fields are missing or different.

**Comment by JamieCorkhill** [comment]
@slackersoft I have just realized I have posted this to Jasmine and not Expect/Jest. I'm not using Jasmine, I'm using Expect, and it's 23.6.0. I apologize for the mixup.

**Comment by Codgereight-hour** [comment]
https://openjs.space/questions/combine-elements-from-an-array-into-a-single-string I sourced the answer
