### ISSUE TITLE
Not toHaveBeenCalledWith should test against all object properties

### ISSUE THREAD

**Issue by bensampaio** [jasmine/jasmine#793]
Hello,

I have the following test:

```js
it("tests if method was executed or not with a certain object argument", function() {
	var fooSpy = jasmine.createSpy('foo');
	var expectedArg = { any : jasmine.any(String), foo : 'fuu' };

	// Passes as expected
	fooSpy({ any : 'lulz', foo : 'fuu'});
	expect(fooSpy).toHaveBeenCalledWith(expectedArg);

	// Fails as not expected
	fooSpy({ any : 'lulz', foo : 'foo'});
	expect(fooSpy).not.toHaveBeenCalledWith(expectedArg);
});
```

Shouldn't the second `expect` pass? The value of `any` is correct but `foo` isn't. I would expect `toHaveBeenCalledWith` to test against all properties in the object. Am I wrong? Is there a better way to do this?

**Comment by Gerg** [comment]
`toHaveBeenCalledWith` looks at all the spy's calls. If you only care about the most recent call, you want something like this:

```js
expect(fooSpy.calls.mostRecent()).not.toEqual(expectedArg);
```

Does this answer your question?

**Comment by bensampaio** [comment]
Thank you for your fast reply!

Well that works, but I think what I want is this:

```js
expect(fooSpy.calls.mostRecent().args[0]).not.toEqual(expectedArg);
```

Because from what I understood the `mostRecent()` function returns an object with more data besides the passed arguments. Anyway, it works but I must say it doesn't look very nice compared to most *expectations* I have been writing. I believe it would look much nicer like this:

```js
expect(fooSpy.calls.mostRecent()).not.toHaveBeenCalledWith(expectedArg);
```

That is a suggestion for future releases ;)

**Comment by slackersoft** [comment]
You should also be able to call `fooSpy.calls.reset()` to clear out the currently tracked calls in between if you want. This would let you use the `toHaveBeenCalledWith` matcher.

Given that, I think we're unlikely to change this behavior.

**Comment by bensampaio** [comment]
Ok, that is also a solution. Thanks!
