### ISSUE TITLE
Why can't you stub a variable.

### ISSUE THREAD

**Issue by vsakaria** [jasmine/jasmine#795]
I want to be able to stub a variable with Jasmine, to control the state of the test for different scenario's    

For example 

var foo = false;

if(foo)
console.log('Hey')

stub(window, 'foo').andReturn(true);

**Comment by infews** [comment]
JavaScript makes this hard or impossible depending on how backwards-compatible one is.

Have you looked at dependency injection as a technique? This can accomplish what you want without polluting your implementation.

Closing.
