### ISSUE TITLE
Ugly error messages from `toHaveBeenCalledWith` when using `jasmine.any`

### ISSUE THREAD

**Issue by mik01aj** [jasmine/jasmine#796]
Try this test case:

```
it('aaa', function () {
    var spy = jasmine.createSpy();
    spy('a', {});
    expect(spy).toHaveBeenCalledWith('b', jasmine.any(Object));
});
```

Result:

```
FAILED TESTS:
  ✖ aaa
    PhantomJS 1.9.8 (Mac OS X)
      [native code]
  })> ] but actual calls were [ 'a', Object({  }) ].
  Error: Expected spy unknown to have been called with [ 'b', <jasmine.any(function Object() {
      at (...)
```

Using Jasmine  `2.2.1`.

**Comment by mik01aj** [comment]
PS. When I try to check stuff like `expect(...).toEqual(jasmine.any(Promise));` the error message is even worse:

```
    ✖ should work woth object
      PhantomJS 1.9.8 (Mac OS X)
          this._id = $$es6$promise$promise$$counter++;
          this._state = undefined;
          this._result = undefined;
          this._subscribers = [];
          if ($$$internal$$noop !== resolver) {
            if (!$$utils$$isFunction(resolver)) {
              $$es6$promise$promise$$needsResolver();
            }
            if (!(this instanceof $$es6$promise$promise$$Promise)) {
              $$es6$promise$promise$$needsNew();
            }
            $$$internal$$initializePromise(this, resolver);
          }
        })>.
    Error: Expected undefined to equal <jasmine.any(function $$es6$promise$promise$$Promise(resolver) {
        at (...)/__tests__/stuff.js:120:0
```

**Comment by slackersoft** [comment]
The only line of those errors that jasmine is actually in control of is:

    Error: Expected spy unknown to have been called with [ 'b', <jasmine.any(function Object() {
and

    Error: Expected undefined to equal <jasmine.any(function $$es6$promise$promise$$Promise(resolver) {

and then only up to the point where the actual name of the expected comes in. I don't know where all the lines above that error line are coming from, but to me that seems like the part that is hard to read. What part of those error messages concerns you?

**Comment by mik01aj** [comment]
To me it looks like Jasmine is doing some simple parsing on the errors. In the first example, I would expect to see something like this:

```
FAILED TESTS:
  ✖ aaa
    PhantomJS 1.9.8 (Mac OS X)
      [native code]
  Error: Expected spy unknown to have been called with [ 'b', <jasmine.any(function Object() { })> ] but actual calls were [ 'a', Object({  }) ].
      at (...)
```

Note that this is exactly what Jasmine outputs now, just in different order.

And in the second example, I would expect to see an error message like `Expected spy unknown to have been called with [ 'b', any $$es6$promise$promise$$Promise ]`. Constructors are functions, and it doesn't make sense to put the whole function in the error report - name would be enough (this affects only `jasmine.any`, I believe.)

**Comment by mik01aj** [comment]
It works, thanks! :)
