### ISSUE TITLE
Documentation for async tests using done

### ISSUE THREAD

**Issue by MarkPaxton** [jasmine/jasmine#799]
Hello,

I am having trouble understanding the way to test async calls using jasmine 2.2.

Please could you clarify the execution order if tests when using "done" calls:

In this case:

beforeEach(done) {
 done();[1]
}

it("spec 1", function(done) {
 expect something;
});

it("spec 2", function() {
  expect something;
});

Will it be the case that spec 1 and spec 2 will be executed in arbitrary order after done() [1] is called?

And in the next case will it be that spec 4 will not be executed until done()[2] is called?

beforeEach(done) {
 done();[1]
}

it("spec 3", function(done) {
 expect something;
  done();[2]
});

it("spec 4", function() {
  expect something;
});

Thanks

**Comment by slackersoft** [comment]
Having asynchronous specs does not affect the order in which they are run. For more documentation on async see our docs [here](http://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support)

If you have more questions about how to test something please ask at jasmine-js@googlegroups.com instead of opening an issue. If you feel that jasmine is not behaving properly, or you'd like to suggest a new feature to be implemented, that's what the github issues are for.

Thanks for using jasmine!

**Comment by MarkPaxton** [comment]
Hello,

Thanks for the reply, I did actually read the documentation however it was not clear how to test the same behaviour that from the runs / waitsFor methods did prior to 2.x, so I would suggest that this is an 'issue' with the documentation.

I would propose a modification of the examples such as:

it("is completed after 9000ms", function(done) {
     doSomething() // This will be completed within 9000ms 
     setTimeout(function() {
        expect(something).toBe(completed);
        done();
      }, 9000);
    });

I think this would make the usage of done() in it() blocks much clearer. There could also be an example using 'setInterval' and 'clearInterval' to show how it is possible to periodically check for the 'complete' condition and call done to end the spec sooner than 9 seconds. This is basically to support async cases where there is no callback for completion.

Thanks - hope that's helpful.

**Comment by Gerg** [comment]
You can find documentation for upgrading from 1.x to 2.x [here](http://jasmine.github.io/2.2/upgrading.html). The change from `runs` / `waitsFor` to `done` requires thinking about asynchronous specs a bit differently.

I would caution against using setTimeouts/setIntervals in your specs. 
* If you want to test setTimeouts in your implementation, I would suggest using synchronous tests with the Jasmine [mock clock](http://jasmine.github.io/2.2/introduction.html#section-Jasmine_Clock)
* If you are testing other asynchronous code, the function under test should have a callback/ event on completion with which to call `done`.

**Comment by MarkPaxton** [comment]
Hello,

Thanks again for the reply - the main problem is when there is no 'done'
callback in the async method being testing and you are just waiting for a
condition to be satisfied. That's the case which is so far not documented.

Thanks,
Mark

**Comment by slackersoft** [comment]
If you'd like to suggest a specific change to the docs, they're on github [here](https://github.com/jasmine/jasmine.github.io). We'd love to review a pull request.
