### ISSUE TITLE
expect().toBe­Gre­ate­rTh­an() SyntaxError: illegal character

### ISSUE THREAD

**Issue by MichaelThompson32214** [jasmine/jasmine#800]
SyntaxError: illegal character
expect(homework_03.gl.viewportWidth).toBe­Gre­ate­rTh­an(1);

The arrow points to the "G' in toBe­Gre­ate­rTh­an

**Comment by slackersoft** [comment]
Looks like there are some strange characters/encoding in your call to `toBeGreaterThan`. When I copy from your post and paste into an editor (I tried vim and textmate) I see `toBe-Gre-ate-rTh-an` instead, which could be what's causing your issue.

**Comment by slackersoft** [comment]
Closing, since this seems to be an issue with the text in the spec file and not with jasmine itself.

Thanks for using jasmine!
