### ISSUE TITLE
CLI Improvements for Node.js

### ISSUE THREAD

**Issue by jimbol** [jasmine/jasmine#803]
*Couple ideas*:
- `--configure <FILE NAME>` - Specify the config json (`jasmine.json`) from command line (also allow cson)
- `--coffee` - Runs coffee files

**Comment by slackersoft** [comment]
Setting the config file to use for jasmine-npm is done with the `JASMINE_CONFIG_PATH` environment variable, though the documentation for this isn't very good.

We've made some changes on master as well that should allow you to just have a helper file that requires the coffeescript patch to `require` so the rest of your coffeescript files will get loaded properly. This should be in the next release.

We're working on some other enhancements to the CLI, see [jasmine/jasmine-npm#19](https://github.com/jasmine/jasmine-npm/issues/19) and the corresponding [tracker story](https://www.pivotaltracker.com/story/show/87856068)

In the future please open issues for the jasmine npm package on [its github page](https://github.com/jasmine/jasmine-npm)

Closing. Thanks for using jasmine!
