### ISSUE TITLE
toHaveBeenCalledWith() failing, although values are the same

### ISSUE THREAD

**Issue by alexhoneygosky** [jasmine/jasmine#805]
I'm trying to verify that a function has been called with specific values.  Unfortunately, although the values are the same, I'm still getting the error:

```
Expected spy dailyRepeat to have been called with [ 0, 100000, Date(Sat Mar 16 2115 00:00:00 GMT-0400 (Eastern Daylight Time)), Date(Mon Mar 16 2015 00:00:00 GMT-0400 (Eastern Daylight Time)) ] but actual calls were [ 0, 100000, Date(Sat Mar 16 2115 00:00:00 GMT-0400 (Eastern Daylight Time)), Date(Mon Mar 16 2015 00:00:00 GMT-0400 (Eastern Daylight Time)) ].
```

I mocked out the time, cast it to a `Number`, and they were both the exact same number.  I also verified that all of the parameter `typeof`s were equivalent.

- Running on Windows 7
- Jasmine ~2.1.0
- PhantomJS 1.9.8

**Comment by mik01aj** [comment]
I tried this:

            var dailyRepeat = jasmine.createSpy('dailyRepeat');
            dailyRepeat(
            0, 100000, new Date('Sat Mar 16 2115 00:00:00 GMT-0400 (Eastern Daylight Time)'), new Date('Mon Mar 16 2015 00:00:00 GMT-0400 (Eastern Daylight Time)')
            );
            expect(dailyRepeat).toHaveBeenCalledWith(
            0, 100000, new Date('Sat Mar 16 2115 00:00:00 GMT-0400 (Eastern Daylight Time)'), new Date('Mon Mar 16 2015 00:00:00 GMT-0400 (Eastern Daylight Time)')
            );


In the current jasmine and it doesn't throw an error. Could you provide more details about the issue?

**Comment by slackersoft** [comment]
We haven't heard anything else from the community on this issue, and have not been able to reproduce it. I'm going to close the issue for now, but if you have more details, please re-open or create a new issue.

Thanks for using jasmine!
