### ISSUE TITLE
Discussion: shouldn't timer mocking be discouraged?

### ISSUE THREAD

**Issue by mik01aj** [jasmine/jasmine#808]
I wrote many tests for async code with promises, and I ran into test pollution issues a few times (and those are hard to debug). Now I'm refactoring my tests to use the `done()` callback whenever possible, and this turns out to be a much more reliable method. Mocking `setTimeout` may break because:

* some library might store its own reference to `setTimeout` (which will not be mocked),
* setTimeout is not the only mechanism of asynchronous scheduling (from [es6-promise](https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/asap.js): there are: `BrowserMutationObserver` and `MessageChannel` in browser and `process.nextTick` in Node)
* JavaScript is a language where threads are never interrupted, and calling `tick()`is like interrupting the current thread. Imho this can lead to very frustrating problems with tests.

Shouldn't the documentation warn about this?

**Comment by slackersoft** [comment]
Native promises don't go through the native `setTimeout` directly and are thus hard to write specs around with a mocked clock, and you might find that a true async spec with a `done` callback works better for you.

For other use cases, say if you have a long timeout passed to `setTimeout`, using the mock clock is going to allow you to not only run your spec synchronously, but the test also won't have to actually wait for the long timeout to elapse.

The documentation is also [on github](https://github.com/jasmine/jasmine.github.io) and we accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) and [issues](https://github.com/jasmine/jasmine.github.io/issues) if you'd like to contribute.

**Comment by mik01aj** [comment]
Thanks for the answer. I think that what you just wrote is a valuable information for the doc, too :) I forked  jasmine.github.io and I'll send a PR when I have some time for this.

**Comment by slackersoft** [comment]
Cool, closing this in favor of updating the docs.
