### ISSUE TITLE
A very strange issue with jasmine clock (which can be worked around by empty describe or it blocks)

### ISSUE THREAD

**Issue by mik01aj** [jasmine/jasmine#809]
I have a test suite with around 60 tests. Recently I started refactoring them to use the `done` callback instead of the jasmine mocked clock, and after I changed some of the tests to use `done`, the next ones that were still using the timer, started to fail. So I got 6 failing tests. Then I started some experimenting, and I found out that if I put this at the beginning of my test suite:

```
describe('x', function () {
    it('a', function () {});
    it('b', function () {});
    it('c', function () {});
    it('d', function () {});
    it('e', function () {});
});
```

...the tests pass. What is more, when I remove just one `it`, one of those timer-based tests fails again. And so on. It's like one empty `it` fixes one broken timer-based test.

Btw, I found that the same is true for `describe`:

```
describe('a', function () {});
describe('b', function () {});
describe('c', function () {});
describe('d', function () {});
describe('e', function () {});
describe('f', function () {});
```

...is also enough.

I can't share my code right now, but I'm saving the current state in Git so I'll be able to reproduce it in the future.

**Comment by slackersoft** [comment]
You probably want to make sure you're correctly uninstalling the clock after each spec as well and not installing it when you're using the `done` callback. There have also been a few fixes to the clock on master and I'd be curious if it worked better for you there.

**Comment by mik01aj** [comment]
FYI: my code got published: https://github.com/mik01aj/flying-squirrel/tree/master/src/__tests__

**Comment by slackersoft** [comment]
@mik01aj are you still seeing this issue? Have you been able to upgrade to a more recent release? The fixes I mentioned earlier should be in a release now as well.

**Comment by slackersoft** [comment]
Closing this as we haven't heard anything else from the community on this issue and haven't been able to reproduce it.

Thanks for using jasmine!
