### ISSUE TITLE
Print failure summary on specDone

### ISSUE THREAD

**Issue by enotha** [jasmine/jasmine#812]
Jasmine prints the result on jasmineDone, in case of a failure, need to wait until all the specs finish execution to see the failure summary.

It would be better, if we can find the failure trace on SpecDone. Depends on the failure message, can terminate the test manually and fix the problem instead of waiting for long time to see the output.

**Comment by slackersoft** [comment]
The `HtmlReporter` used to print out the full failure messages as the specs finished, but we found that it was causing a log of reflows on the page and was actually slowing down the time it took to run the suite.

It shouldn't be too hard to write your own reporter that updates the page as the specs run. This isn't something we're going to pull into jasmine itself for now, so I'm going to close this issue.

Thanks for using jasmine!
