### ISSUE TITLE
Add support for spec suite dependencies

### ISSUE THREAD

**Issue by drewzh** [jasmine/jasmine#814]
Would it be possible to add a feature whereby you can specify dependencies for each suite of tests. This would allow the ability to test a specific test suite without knowing what prerequisite tests need to come before it.

for e.g,

You'd be able to run a single spec file "supportSpec.js" and have it's dependencies run before it.

supportSpec.js
```javascripts
describe("customer support should work", ['login'], function(){
  // Tests to go here
});
```

loginSpec.js
```javascripts
describe("login should work", ['registration'], function(){
  // Tests to go here
});
```

registrationSpec.js
```javascripts
describe("registration should work", function(){
  // Tests to go here
});
```

I understand this might require some significant changes.  Is this in any way a proposed or even thought-about feature? I couldn't find any reference to such a feature on the issue trackers.

**Comment by Gerg** [comment]
Your tests should be able to function independent of each other. Any setup that you need should be handled in a `beforeEach` function.

If you are looking for a way to do common setup, I suggest making some test helper functions. For example:

```js
describe("customer support should work", function() {
  beforeEach(function() {
    testHelper.loginUser();
  });

  // Tests to go here
});
```
Thanks for using Jasmine.

**Comment by slackersoft** [comment]
A test or set of tests should not have any dependencies on any other tests in your suite, so this isn't something we're going to bring into jasmine itself. Maybe you can get it to work as a plugin to jasmine.

Closing.
