### ISSUE TITLE
beforeEach does not wait on beforeAll

### ISSUE THREAD

**Issue by jdenekat** [jasmine/jasmine#816]
In our pages, we use ```<ng-controller="ctrlName as vm">``` and then use the pattern
```ng-model="vm.something"```.  We use services to communicate between controllers
so nothing is dependent on the state of $scope.

When unit testing controllers we therefore need a reference not to scope
but the controller itself so we would like to do this:
```
describe('When users does something', function() {
	var ctrl;

	beforeAll(function() {
		module['theModule'];
		inject(function($controller) {
			ctrl = $controller('theController', { $scope: {} });
		});
	});

	beforeEach(function() {
		ctrl.state = whatever;	//setup specific actions for specific test case
	});

	it('check the result', function() {
		expect(ctrl.value).toBe('something');
	});
});
```
While we would like to do that we can't.  The issue appears to be that ```beforeEach```
is called prior to resolution of ```beforeAll``` (in``` beforeEach```, ctrl is null).

Instead we find that we have to do this pattern:
```
...
	beforeEach(function() {
		module['theModule'];
		inject(function($controller) {
			ctrl = $controller('theController', { $scope: {} });
		});
		//Can't use ctrl here, it is null.
	});

	it('check the result', function() {
		ctrl.state = whatever;	// This doesn't belong here.
		expect(ctrl.value).toBe('something');

		describe('', function() {
			beforeEach(function() {
				ctrl.state = theNextThing;		//Works fine down here
			}
			it('check the next result', function() {
				expect(ctrl.value).toBe('better');
			});
		}
	});
...
```
So we're both taking the action and checking the result in the same place on the
first level of test but in nested tests we can follow the desired pattern.

Should we care?  Are we doing something wrong with ```beforeAll()```?  Is there a 
way to wait asynchronously on the creation of ctrl in ```beforeEach``` 
(or for that matter, ```beforeAll```) and then take the action there?

Thank you.

angular: 1.3.15
jasmine: 2.2.1
karma: 0.12.31
karma-cli: 0.0.4

**Comment by slackersoft** [comment]
It sounds to me like the `inject` call is asynchronous and is returning before it has called your callback. You should be able to use the `done` callback in your `beforeAll` (and `beforeEach`, etc) to tell jasmine that the function will be asynchronous and will call the `done` callback when it has completed its work. In your case this would probably be inside your `inject` callback after you've set the value of `ctrl`. Hope this helps.

**Comment by jdenekat** [comment]
Thanks, this worked just fine when doing everything in ```beforeEach```.  But when we tried to move the ```done``` callback to ```beforeAll``` and create the controller there the result was the same -- ```beforeAll``` does not appear to care about ```done```.

**Comment by jdenekat** [comment]
This is what is happening now and we think it is a deficiency (if not a defect) with ```beforeAll```:

```
describe('When users does something', function() {
    var ctrl;

    //Chaining beforeEach...beforeEach works, but beforeAll...beforeEach does not:
    beforeEach(function() {
        module['theModule'];
        inject(function($controller) {
            ctrl = $controller('theController', { $scope: {} });
        });
    });

    beforeEach(function() {
        ctrl.state = whatever;  //ctrl is available in chained beforeEach
    });

    it('check the result', function() {
        expect(ctrl.value).toBe('something');
    });
});
```

Chaining together ```beforeEach``` and ```beforeEach``` gives us a valid controller.  If the first ```beforeEach``` is turned into ```beforeAll``` then the controller will be null in the ```beforeEach```.

**Comment by slackersoft** [comment]
Can you provide a full simple example with a spec and implementation that displays this issue? I am unable to make something simple that makes your specs work even with `beforeEach` only.

**Comment by jdenekat** [comment]
Thanks for your attention to this issue.  Here is a [GIST](https://gist.github.com/jdenekat/0ee735193134bc844520).

I don't actually need beforeAll in this simple test, but when I switch between beforeEach and beforeAll on line 6 of commentUnit.js I can observe the issue.

**Comment by slackersoft** [comment]
I think this is actually a quirk with angular-mocks now that jasmine supports `beforeAll`. Angular-mocks attempts to determine whether or not a spec is currently running when you call `module`, `inject`, etc. and the functions behave differently if no spec is running. Basically, it's expecting the difference between:

````javascript
beforeEach(module('foo'));
````

and

````javascript
beforeEach(function() {
  // some stuff
  module('foo');
});
````

And when you run the `inject` and `module` calls from within the `beforeAll` no spec is running yet and you get the behavior as if you'd called it in the first example. This should mean that you can do something like this and it should work with `beforeAll`:

````javascript
beforeAll(module('comments');

beforeAll(inject(function ($controller) {
  ctrl = $controller('commentController', { $scope: {} });
}));
````

**Comment by jdenekat** [comment]
When trying the proposed change I get this:
```
TypeError: Cannot read property '$injector' of null at Object.workFn (D:/.../angular-mocks.js:2287:22)
TypeError: Cannot read property '$modules' of null at Object.workFn (D:/.../angular-mocks.js:2411:32)
```
Apparently it still doesn't know that a spec is running.

We plan to adopt this pattern:
```
var initialized = false;
beforeEach(function() {
    if (!initialized) {
        ...
        initialized = true;
    }
});
```
That has the effect we're looking for and doesn't get bogged down in quirky behavior of ```beforeAll```.

**Comment by slackersoft** [comment]
I would take this issue to the angular/angular-mocks folks and see what they have to say about the issue. `beforeAll` is still pretty new to jasmine, so it's possible they haven't noticed this issue yet.

Since this doesn't appear to be an issue with jasmine itself, I'm going to close it. Let us know if you have any other issues.

Thanks for using jasmine!
