### ISSUE TITLE
toThrowError doesn't consider inheritance

### ISSUE THREAD

**Issue by chge** [jasmine/jasmine#819]
`toThrowError` is very useful, but I think it works incorrectly with custom error classes.

```javascript
function PirateError(message) {
	this.message = 'Arrggghhhh! ' + message;
}
PirateError.prototype = new Error();

describe('custom try/catch', function() {
	it('works fine in tests', function() {
		try {
			throw new PirateError();
		} catch (error) {
			expect(error).toEqual(jasmine.any(Error));
			expect(error).toEqual(jasmine.any(PirateError));
			expect(error instanceof Error).toBeTruthy();
			expect(error instanceof PirateError).toBeTruthy();
		}
	});
});

describe('toThrowError', function() {
	it('considers error inheritance', function() {
		expect(function() {
			throw new PirateError('Blow me down!');
		}).toThrowError(PirateError);
	});
});
```

Result:
```
Expected function to throw PirateError, but it threw Error.
```

**Comment by slackersoft** [comment]
Jasmine uses the `constructor` attribute to determine whether the thrown error is of the desired type. When you assign the prototype of your `PirateError` to be a `new Error()` it changes the constructor to the `Error` function instead. If you add:

````javascript
PirateError.prototype.constructor = PirateError;
````

after you assign the prototype your example should work.

We'd be open to a way to do this checking that didn't require re-assigning the constructor after setting the prototype, but none has come up yet.

**Comment by chge** [comment]
But, for example, `jasmine.any` uses `instanceof` for matching. Why shouldn't `toThrowError` use `instanceof` instead of direct constructor comparison?
