### ISSUE TITLE
How to use jasmine with official node.js debugger?

### ISSUE THREAD

**Issue by rusikf** [jasmine/jasmine#820]
Hello all javascript hackers!
Just create sample rake app and run
``jasmine:install``
``jasmine:examples``
``jasmine:ci``
5 test are successfull
After it, adding ```debugger;``` in to spec file PlayerSpec.js like this
```javascript
describe("Player", function() {
  var player;
  var song;

  beforeEach(function() {
    player = new Player();
    song = new Song();
  });

  it("should be able to play a Song", function() {
    debugger;
    player.play(song);
    expect(player.currentlyPlayingSong).toEqual(song);

    //demonstrates use of custom matcher
    expect(player).toBePlaying(song);
  });

  describe("when song has been paused", function() {
    beforeEach(function() {
      player.play(song);
      player.pause();
    });

    it("should indicate that the song is currently paused", function() {
      expect(player.isPlaying).toBeFalsy();

      // demonstrates use of 'not' with a custom matcher
      expect(player).not.toBePlaying(song);
    });

    it("should be possible to resume", function() {
      player.resume();
      expect(player.isPlaying).toBeTruthy();
      expect(player.currentlyPlayingSong).toEqual(song);
    });
  });

  // demonstrates use of spies to intercept and test method calls
  it("tells the current song if the user has made it a favorite", function() {
    spyOn(song, 'persistFavoriteStatus');

    player.play(song);
    player.makeFavorite();

    expect(song.persistFavoriteStatus).toHaveBeenCalledWith(true);
  });

  //demonstrates use of expected exceptions
  describe("#resume", function() {
    it("should throw an exception if song is already playing", function() {
      player.play(song);

      expect(function() {
        player.resume();
      }).toThrowError("song is already playing");
    });
  });
});

```

, run ``jasmine:ci``
All sucessfull, but debugger is not running, why? 
It looks, that in [usual case](https://nodejs.org/api/debugger.html), we must use something like this:
``$ node debug file.js``
But how to use it with jasmine ?
With the best regards, Ruslan.

**Comment by slackersoft** [comment]
It sounds like you're using the jasmine ruby gem to run the specs, which is designed for running javascript specs in a browser, not in nodejs. If you want to debug the specs, you'll want to run the `rake jasmine` task and load the page in a browser to debug.

If your intent is to test nodejs code, you should look at the [jasmine-npm](https://github.com/jasmine/jasmine-npm).

You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using jasmine!
