### ISSUE TITLE
add a global "custom matcher registration"-method

### ISSUE THREAD

**Issue by GFriedrich** [jasmine/jasmine#821]
I've seen that this was already request in #721 and it was denied to implement it.
But as I'm quite sure that there are several people having the same issue, I'm asking again to implement a method to register a new matcher globally.

"Why?" you're may asking: The reason is simple. It's really painful to add a matcher over and over again, if you want to use it in several beforeAll methods - it simply adds more boilerplate code.

Why not add the possiblity to add matchers to a global list like the default matchers are?

And even more horrible: If I want to use the "jasmine-matchers" library, there is no way to access and register the matchers at all from the outside.

So please: Think again about adding a global matcher registration method.

Thank you. :)

**Comment by slackersoft** [comment]
After a bit of testing it looks like the cascading of a custom matcher should work from a `beforeAll` that is inside a `describe` but not a global one. There are a couple of other issues around global `beforeAll`s and `afterAll`s that are related to this. See #811 

Instead of adding a new thing to jasmine's interface, I'd prefer to make a global `beforeAll` work more like one inside a `describe`.

Closing this in favor of #811 

Thanks for using jasmine!

**Comment by 77ganesh** [comment]
You can add global matchers using this

`jasmine.Expectation.addCoreMatchers(matchers)`

**Comment by slackersoft** [comment]
The `addCoreMatchers` method is an internal implementation detail and not part of Jasmine's public interface. As such, it is susceptible to breaking changes without notice. If you want to add matchers to all of your specs, you should either register it in a global `beforeEach` or possibly now a `beforeAll`.

**Comment by 77ganesh** [comment]
Ohh! Sorry I didn't know that..  I use jasmine with protractor and I need custom matchers like toBePresent() toBeDisplayed() throughout the entire test suites. Will there be a possibility for such method in the future?

**Comment by slackersoft** [comment]
A matcher registered in a `beforeEach` is available to all specs within the `describe` where it is called. If the `beforeEach` is declared outside of any `describe`, any matchers in it will be available to all specs.
