### ISSUE TITLE
toThrowError does not handle a function call with an argument ...

### ISSUE THREAD

**Issue by lokeb** [jasmine/jasmine#823]
... which is odd. Write now the function has to be wrapped inside another function for it to work. Will there be a fix in the near future?

**Comment by slackersoft** [comment]
I'm not sure how you would pass the argument to the function, given that you don't want it to execute at declaration time, but wait until the spec is running.

**Comment by lokeb** [comment]
There is another problem. When calling in this manner, the context of the call is Window, which is going to create problems when the function expects to be called in the context of the object it is contained in, i.e., it refers to this, and expects the expected.

**Comment by pivotal-vanguard** [comment]
If you're able to use it (support in IE9+), you could use Function.prototype.bind.

**Comment by amavisca** [comment]
If you're able to use [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind), that would let you pass the `this` and the arguments.

**Comment by jaapz** [comment]
Building on this, I think

    expect(MyMathLib.add, [1, 'two']).toThrow(NotAnIntegerError);

Looks nicer than

    var plsThrow = function () {
        MyMathLib.add(1, 'two');
    };

    expect(plsThrow).toThrow(NotAnIntegerError);

The first version cuts out the need of an intermediate wrapping function. In my tests I have quite a few of these things that could be cleaned up this way.

**Comment by nertzy** [comment]
Would be interesting to add a `calledWith` matcher that could support something like the following:

```js
expect(MyMathLib.add).calledWith(1, 'two').toThrow(NotAnIntegerError);
```

**Comment by slackersoft** [comment]
Neither of the proposed solutions from @jaapz and @nertzy solve the problem of specifying what the `this` should be when the function is executed. If we're not going to solve that problem, I don't think we want to try to only address arguments to the function. Additionally, the interface for specifying the context for execution becomes clunky (`expect(foo).calledWith(1).calledOn(4).toThrow`) or possibly confusing (`expect(foo, [1], 4).toThrow`).

Both of the solutions also require a lot of code to write and maintain from jasmines point of view, just to make it so you don't have to wrap your call in an anonymous function. Additionally, it seems to me that the anonymous function is a lot more clear about what exactly is happening (the `toThrow` or `toThrowError` matcher is going to invoke the function and expect something to be thrown).

I don't think this is something we're going to implement in jasmine itself, but I'd be happy to link to a plugin that is able to accomplish this.

Thanks for using jasmine!

Closing.
