### ISSUE TITLE
feature request: toHaveBeenCalledWith and call count

### ISSUE THREAD

**Issue by lukeapage** [jasmine/jasmine#825]
In situations where I want to test spy's I'm finding the existing assertions a bit awkward.

firstly, toHaveBeenCalledWith is ambiguous as to whether it means "has been called once and it was called with" or "it was last called with" or "it was called at some point with".

I had expected the first as the most useful for testing, then the 2nd as a little useful and closer to the english but was surprised by the last. I guess it makes sense because of the `toHaveBeenCalled` matcher. Maybe that confusion was just me..

When would you want to check something had been called with x at some point? I'm using reset, but then I might be fooled into thinking I had a good enough test with
```
spy.reset();
test();
expect(spy).toHaveBeenCalledWith("");
```

where as ideally I want to test that the call count is 1. Would you ever not care how many times a function had been called? So I think that the majority of people using this function probably want to do...

```
spy.reset();
test();
expect(spy).toHaveBeenCalledWith("");
expect(spy.calls.count()).toEqual(1);
```

Furthermore, if what I am testing tests twice I am left with assertions that don't look great

```
// I care about ordering
spy.reset();
test();
expect(spy.calls.count()).toEqual(2);
expect(spy.calls.argsFor(0)).toEqual(["1"]);
expect(spy.calls.argsFor(1)).toEqual(["2"]);

// I don't care about ordering
expect(spy.calls.count()).toEqual(2);
expect(spy).toHaveBeenCalledWith("1");
expect(spy).toHaveBeenCalledWith("2");
```

So, I'm wondering about better syntax, something like the below ?

```
expect(spy).toHaveBeenCalled.once.with("1")
expect(spy).toHaveBeenCalled.first.with("1");
expect(spy).toHaveBeenCalled.second.with("1");
```

or

```
expect(spy.calls.first()).toHaveBeenCalledWith("1")
expect(spy.calls.second()).toHaveBeenCalledWith("2")
```

so what do you think? the main thing is I am finding in the wild quite messy assertions in some instances and lovely clean ones in others. Thanks.

**Comment by lukeapage** [comment]
After implementing custom matchers for this, I think the benefit is probably small. Other than changing things in a bigger way - I'm not sure what to do. Maybe its just documentation, maybe its just me. Feel free to close if you can't see anything of benefit here.

**Comment by ulrichb** [comment]
I would also like to have this feature. But: In 90% of these cases I want to assert "exactly once" bahavior.

So what about `expect(mySpy).toHaveBeenCalledOnceWith('argA', 'argB', 'argC')`?

**Comment by bebepeng** [comment]
Or something like expect(mySpy).toHaveBeenCalledWith('argA', 'argB', 'argC').times(1)

**Comment by tkane2000** [comment]
Here's a quick fix (there should be a slicker way to do this):
// count how many times commit is called with first arg of 'foo'
`const count = storeStub.commit.mock.calls.reduce((accum, mockCall) => {
        accum += (mockCall[0] === 'foo'); // where foo is name of arg
        return accum;
}, 0);`
