### ISSUE TITLE
Async timeouts while writing sync specs

### ISSUE THREAD

**Issue by mspanc** [jasmine/jasmine#829]
Hello,

I get error `Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out` while I am writing synchronous specs and 100% sychronous code.

Log:

```
Failures:
1) RadioKit.Data.Interface #getQuery if one argument is passed and it is valid but there's no such query encountered a declaration exception
1.1) Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out
```

I am using jasmine 2.2.1 and gulp to compile coffeescript to JS prior to execution. 

```
  describe "#hasQuery", ->
    instance = null

    beforeEach ->
      instance = new RadioKit.Data.Interface({ authUserName: "123", authPassword: "123" })

    describe "if no argument is passed", ->
      it "throws an error", ->
        expect ->
          instance.hasQuery()
        .toThrow()

    describe "if one argument is passed", ->
      describe "but it is invalid", ->
        describe "because it contains something different than a string", ->
          it "throws an error", ->
            expect ->
              instance.hasQuery(123)
            .toThrow()

      describe "and it is valid", ->
        describe "but there's no such query", ->
          it "returns false", ->
            expect(instance.hasQuery("myQuery")).toBe(false)

        describe "and there's such query", ->
          beforeEach ->
            instance.addQuery("myQuery", "Track")

          it "returns true", ->
            expect(instance.hasQuery("myQuery")).toBe(true)
```

**Comment by slackersoft** [comment]
Are you able to find a subset of your specs (possibly one) that has this problem, or are you only seeing it when you run the full suite? I tried taking your example here and compiling to javascript and I didn't see any issues.

**Comment by casertap** [comment]
Same error here. Did you find a solution to this problem?

**Comment by casertap** [comment]
My grunt task was defining:
````
frameworks: ['mocha', 'jasmine']
````
I just removed the mocha framework and it worked.

**Comment by jescacena** [comment]
it worked for me :+1:  Thanks!

**Comment by slackersoft** [comment]
It sounds like this is coming up due to misconfiguration within karma,and not directly because of Jasmine itself. I'm going to close this for now, but please reopen if you can narrow it down to something Jasmine is doing.

**Comment by maxime1992** [comment]
@casertap thanks, i was lost !
Even ```expect(true).toBe(true);``` was not working and i was loosing time for nothing :+1:
