### ISSUE TITLE
tobeUndefined() runs out of memory

### ISSUE THREAD

**Issue by nishakchaudhari** [jasmine/jasmine#831]
If I use tobeUndefined() for some element on webpage , it runs out of memory and crashes.
Following is my test:

it('test for undefined element',function(){
        browser.get("https://builtwith.angularjs.org/");
        expect(element(by.className('myname'))).toBeUndefined();
});

And when I run it , it takes a few minutes and gives me the following:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)

ALSO
test passes if I use the following 
it('test for undefined element',function(){
        browser.get("https://builtwith.angularjs.org/");
        expect(element(by.className('myname'))).toBeDefined();
});

**Comment by slackersoft** [comment]
What browser are you seeing exhibit this behavior? `toBeDefined` and `toBeUndefined` both just check `===` or `!==` with `void 0` since 2.0. It was `undefined` previously. There isn't really any complicated processing happening there.

Do you maybe have something that has installed a custom `toBeUndefined` matcher that clobbers the built-in one?

**Comment by nishakchaudhari** [comment]
So it might be a protractor bug?
I see this in Chrome. I am not using any custom toBeUndefined matcher
But my jasmine version is less than 2.0. will that make difference?

**Comment by slackersoft** [comment]
Pre-2.0 still just did a `=== undefined` so I'm not sure what could be causing much in the way of memory usage.

**Comment by nishakchaudhari** [comment]
so this would be a protractor bug?

**Comment by slackersoft** [comment]
I don't think it is necessarily a bug with protractor, as I don't think it defines its own `toBeUndefined` or `toBeDefined` matchers either.

One of the things you mentioned in your original post was that it only broke when the expectation failed, but worked fine when successful. We've seen issues with serializing certain types of objects (usually out from a browser or phantomjs (see #640 and #690)). HTML nodes are the most likely to have problems, and it looks like that's what you are checking. It seems likely then, that it is not the expectation itself that is breaking, but the reporting of the failure that it attempting to serialize the DOM node that wasn't supposed to be found.

Hope this helps. Thanks for using jasmine!

**Comment by nishakchaudhari** [comment]
works with version > 2. Thanks . closing the issue.
