### ISSUE TITLE
Missing SpecRunner.html file 

### ISSUE THREAD

**Issue by punit11** [jasmine/jasmine#833]
Hi, I have recently started learning Jasmine. Most tutorials advise to edit "SpecRunner.html" file run the tests. But I am unable to find this file in root folder or anywhere else ? Where can I found this file ? Thanks

**Comment by Gerg** [comment]
If you download one of the [standalone releases](https://github.com/jasmine/jasmine/releases), SpecRunner should be in the root directory.

Note 2.2.1 is missing a standalone version, because the release only affected the bower distribution.

**Comment by ssmahesh** [comment]
Hi, I have recently started learning jasmine.I am not able to edit the specRunner.html file.I dowloaded Standalone 2.0.0 version and also Standalone 2.3.4 version,In the root directory specRunner.html file is there,if i try to open that file it will move to chrome,but i can't edit the file.how to edit that file

**Comment by slackersoft** [comment]
specRunner.html is just a normal `html` file, so you can edit the same way you edit any other html file you work with.

**Comment by slackersoft** [comment]
We haven't heard anything else from the community on this in a while, so I'm going to close it for now.

**Comment by amit-kumar88** [comment]
Hi.
Hi, I have recently started learning Jasmine and downloaded standalone 2.5.1. Most tutorials advise to edit "SpecRunner.html" file run the tests. But I am unable to find this file in root folder or anywhere else ? Where can I found this file ? 
Thanks

**Comment by slackersoft** [comment]
The 2.5.1 standalone zip from the [releases page](https://github.com/jasmine/jasmine/releases) definitely includes the `SpecRunner.html` file, I just checked. Where did you get the standalone package from?

**Comment by bryanjebyrd** [comment]
@slackersoft I'm guessing this is a common theme when you download jasmine from NPM. I am in the same boat but I'm going to head to that releases page you attached and go from there.
