### ISSUE TITLE
Why does jasmine.HtmlReporter() need the user to define each function??

### ISSUE THREAD

**Issue by dopatraman** [jasmine/jasmine#835]
I'm talking about this:
```
var env = options.env || {},
      getContainer = options.getContainer,
      createElement = options.createElement,
      createTextNode = options.createTextNode,
      onRaiseExceptionsClick = options.onRaiseExceptionsClick || function() {},
      onThrowExpectationsClick = options.onThrowExpectationsClick || function() {},
      addToExistingQueryString = options.addToExistingQueryString || defaultQueryString,
      timer = options.timer || noopTimer,
      results = [],
      specsExecuted = 0,
      failureCount = 0,
      pendingSpecCount = 0,
      htmlReporterMain,
      symbols,
      failedSuites = [];
```
Why is the user supposed to pass all these in??

**Comment by Gerg** [comment]
Jasmine uses dependency injection to increase modularity and testability. For most cases, users should use `boot.js` instead of constructing `HtmlReporter` directly.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). If you have questions about developing for jasmine you can use the [jasmine-js-dev group](https://groups.google.com/group/jasmine-js-dev) We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using jasmine! Closing.
