### ISSUE TITLE
Testing a function that has a callback and a return value

### ISSUE THREAD

**Issue by lokeb** [jasmine/jasmine#838]
How do I test a function that has a callback and an immediate return value? Using 'done', ignores the test for the return value, and only considers the tests in the callback function.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
