### ISSUE TITLE
The jasmine page cannot be scrolled in Safari and Chrome on OS X 10.10

### ISSUE THREAD

**Issue by cheunghy** [jasmine/jasmine#839]
I'm using jasmine 2.3, the previous version seems doesn't have this issue.
After clicking on a specific test, sometimes the page can be scrolled.

**Comment by slackersoft** [comment]
I just checked on a Yosemite machine against jasmine's own test suite (about 550 specs) and I don't have any problem scrolling the page in either browser.

Is there maybe something still happening in the background (a custom reporter or something) that could be pre-empting the browsers scrolling?

**Comment by cheunghy** [comment]
The causing may be this test suite, the tested function uses `setTimeOut` internally.
``` coffeescript
describe "Dispatch After", ->
  a = 20
  time = new Date().getTime()
  beforeEach (done) ->
    CB.DispatchAfter (-> a = 30; done()), 2000

  it "should perform after some time", ->
    later = new Date().getTime()
    expect(a).toBe(30)
    expect(later - time).toBeGreaterThan(2000)
    expect(later - time).not.toBeGreaterThan(2200)
```

**Comment by slackersoft** [comment]
As long as the `done` callback is invoked after all async work has completed, there shouldn't be anything else running in the background.

I'm going to close this issue as it doesn't seem like an issue with jasmine itself, but rather something in your test suite that is causing problems. You can also try asking a question on the [jasmine-js group](https://groups.google.com/group/jasmine-js).
