### ISSUE TITLE
Specs with xit or no function are no longer reported as pending

### ISSUE THREAD

**Issue by benjaminjosephw** [jasmine/jasmine#840]
The docs say that [`xit`](http://jasmine.github.io/2.3/introduction.html#section-15) and [functionless specs](http://jasmine.github.io/2.3/introduction.html#section-16) will be marked as pending which is currently not the case. It seems both of these are disabled and not reported on. The docs currently suggest that [`xit` specs and `xdescribe` suites will not be reported on at all](http://jasmine.github.io/2.3/introduction.html#section-Disabling_Suites). 

Should the docs be updated to clarify that only specs with a call to `pending` are actually reported as pending and others are hidden?

My view is that functionless specs should still be reported as pending since they have not be explicitly disabled and represent an unfinished (i.e. pending) test rather than one that is purposely hidden.

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by mikepack** [comment]
This is holding up support for Jasmine 2.3 in https://github.com/modeset/teaspoon

**Comment by slackersoft** [comment]
The docs should probably be updated so they no longer incorrectly say that specs declared with `xit` are `pending`, they should always have been `disabled` as they are now.

Functionless `it`s should be `pending` and are currently not as of 2.3. This was an unintended change and we'll need to work on a fix.

**Comment by slackersoft** [comment]
Upon further inspection, an `xit` spec will actually be marked `pending` but and not `disabled`, but a spec that is a child of an `xdescribe` will be `disabled`.

I think I have a fix for the functionless specs being reported incorrectly, and will work to get that out soon.
