### ISSUE TITLE
Attributes set on the "this" keyword inside root beforeAll can no longer be accessed inside describe block

### ISSUE THREAD

**Issue by joswhite** [jasmine/jasmine#846]
<p>Hey, thank you guys so much for maintaining this project! It has helped me out so much! I love Jasmine's "this" keyword. While doing some tests and upgrading from Jasmine version 2.2.1 to 2.3.0, I noticed my tests no longer passed because of a change that was made in the way the "this" keyword can be used. I want to understand why this change was made, and if the Jasmine team as well as people using Jasmine would support reverting this change. Take for example the following code:</p>
<pre><code>beforeAll(function() {
	this.attr = 1;
})

describe('Testing root beforeAll', function() {
	it('should be able to access "attr"', function() {
		expect(this.attr).toEqual(1);
	});
});</code></pre>
<p>Note that in the test we are setting an attribute on the "this" keyword inside a <code>beforeAll</code> function that executes on the root level. Executing this test in version 2.2.1 (both the standalone and npm versions) shows the test as passing. However, in version 2.3.0 the test fails.</p>
<p>Let me explain my argument for why this should be changed to work in the latest version of Jasmine. In Jasmine versions 2.2.1 and 2.3.0 I've noticed that inside any <code>describe</code> block you can access attributes on the "this" keyword that were set in the <code>beforeAll</code> function of that <code>describe</code> block, regardless of the nesting level inside the block from which you attempt to access those attributes. It only seems logical that the same rules would apply to <code>beforeAll</code> functions on the root level that set attributes on the "this" keyword.</p>
<p>Why is this a big deal? Normally you could just use global variables, or put the <code>beforeAll</code> function inside your <code>describe</code> block, and then you could access the attribute just fine. This doesn't work for me though because I chose to use helper files to avoid redundancy in my code. Inside the helper file a <code>beforeAll</code> on the root level initializes attributes on the "this" keyword so they can be accessed by the tests. Since the <code>beforeAll</code> no longer works this way, my only alternative (while still allowing me to keep the same testing framework) is using the <code>beforeEach</code>, which will run before every single <code>it</code> block. Considering that there will be over 100 <code>it</code> blocks in my code, the <code>beforeEach</code> will be run dozens of times, making my test code more inefficient. As such, this appears to be a poor solution. So I'm hoping we could get the previous functionality back. :)</p>
<p>Thank you to all who have read my post. Please comment and let me know what you think.</p>

**Comment by trsrm** [comment]
+1

**Comment by flashbag** [comment]
+1

**Comment by slackersoft** [comment]
Sorry about this. This was definitely not intended functionality as part of 2.3. I'm not entirely sure what happened to cause it, but I should have some time tomorrow to take a look and try to fix it, unless someone has time to submit a pull request before then.

**Comment by flashbag** [comment]
I wrote basic explanation of problem. Now we definitely know that it exists and difference in those two versions clear. Working in - 2.2.1, not working in - 2.3.0.

See terminal video about this: https://asciinema.org/a/19871
Or commited files for proof of working: https://github.com/flashbag/jasmine/commit/0ba1de0d547c81b67187745e57b471bea5e96a0a

**Comment by slackersoft** [comment]
This should be fixed and released in version 2.3.3

**Comment by joswhite** [comment]
Thank you so much! I appreciate that. Thanks for getting back to me so quickly as well. I'll try it as soon as version 2.3.3 is released on npm. I assume that will be sometime later this week.

**Comment by slackersoft** [comment]
Version 2.3.3 of jasmine-core should be available already on npm and rubygems. Pypi should will be coming soon.

**Comment by joswhite** [comment]
I'm actually using the CLI version that works with Node. So the package name is "jasmine" rather than "jasmine-core"

**Comment by slackersoft** [comment]
The jasmine package doesn't need to be bumped for this fix, it has a dependency on the jasmine-core package which should allow upgrades of minor and patch version.

**Comment by joswhite** [comment]
Yes, you are right! I didn't realize that until now. I installed the package again, and it works with my tests just fine. There are no more problems with the <code>this</code> object. Thanks for your good work!
