### ISSUE TITLE
feature request: toHaveBeenCalledOnce

### ISSUE THREAD

**Issue by logankd** [jasmine/jasmine#853]
I find myself doing: expect(searchModel.clearSearchCallback.calls.count()).toEqual(1); a lot to make sure a method has been called, but only one time.

It'd be great if there was a toHaveBeenCalledOnce method.

Thanks!

**Comment by slackersoft** [comment]
I think we would prefer to have the matcher be able to take a parameter for the call count instead of only having it hard-coded to the singular case. Something like `toHaveBeenCalledTimes(4)` possibly.

I'd be happy to review a pull request for that.
