### ISSUE TITLE
Error: Spies must be created in a before function or a spec

### ISSUE THREAD

**Issue by nottinhill** [jasmine/jasmine#859]
1) tracks that the spy was called
    A spy
    Error: Spies must be created in a before function or a spec
    at http://localhost:9126/base/node_modules/jasmine-core/lib/jasmine-    
    core/jasmine.js?578a1e5ff14db21b04e2d6db7fd0eda37042440c:687

My Test code should be ok, so I am out of knowledge where the root cause for this error could be. I already re-installed karma-jasmine.

    describe 'A spy', ->
      foo = undefined
      bar = null
      beforeEach ->
        foo = setBar: (value) ->
          bar = value
          return
        spyOn foo, 'setBar'
        foo.setBar 123
        foo.setBar 456, 'another param'
        return
      it 'tracks that the spy was called', ->
        expect(foo.setBar).toHaveBeenCalled()

This is from the *devDependencies* section of my `package.json`:

    ..
    "jasmine": "^2.3.1",
    "jasmine-core": "^2.3.4",
    "karma": "^0.12.32",
    "karma-chai": "^0.1.0",
    "karma-chai-plugins": "^0.5.0",
    "karma-chrome-launcher": "^0.1.12",
    "karma-coffee-preprocessor": "^0.2.1",
    "karma-firefox-launcher": "^0.1.4",
    "karma-html2js-preprocessor": "^0.1.0",
    "karma-jade-preprocessor": "0.0.11",
    "karma-jasmine": "^0.3.5",
    "karma-mocha": "^0.1.10",
    "karma-ng-html2js-preprocessor": "~0.1.0",
    "karma-ng-jade2js-preprocessor": "^0.1.2",
    "karma-ng-scenario": "~0.1.0",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-requirejs": "~0.2.1",
    "karma-script-launcher": "~0.1.0",
    "karma-spec-reporter": "0.0.19",
    ..

**Comment by slackersoft** [comment]
I just set up a tester app with your spec and it is working fine, both with just the `jasmine` command and through karma. The only direct npm dependencies I installed were:

````
coffee-script
jasmine
jasmine-core
karma
karma-chrome-launcher
karma-coffee-preprocessor
karma-jasmine
````

Is it possible one of your other dependencies is messing something up?

**Comment by nottinhill** [comment]
Yes, it was Mocha which interferred. Removing it from karma.conf.js
solved the issue.

**Comment by slackersoft** [comment]
Awesome. Closing this then.
