### ISSUE TITLE
is it possible to run only one file by command? 

### ISSUE THREAD

**Issue by shoyer2010** [jasmine/jasmine#861]
for example: 
i have several files, but in developing, i may just run one of them by jasmine, as so far, it seems jasmine will run all the files.  i want to know if there is a way to run a file by format like this: jasmine aFileSpec.js

**Comment by Gerg** [comment]
If you have a top level `describe` for each file, you can use `fdescribe` to focus the file.

**Comment by shoyer2010** [comment]
@Gerg thks.
