### ISSUE TITLE
"Template.leaderboard.players() is not a function" in leaderboard-jasmine 

### ISSUE THREAD

**Issue by totorokk** [jasmine/jasmine#862]
Dear All,

I'm trying to figure out client unit testing on template helper functions. After I cloned and ran the [leaderboard-jasmine](https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-jasmine) code (unchanged), I got this error:
> Template.leaderboard.players() is not a function 

which comes from 
```javascript
// velocity-examples/leaderboard-jasmine/tests/jasmine/client/integration/LeaderboardSpec.js
var players = Template.leaderboard.players().fetch();
```
After digging a bit here, I changed above line to below:
```javascript
// velocity-examples/leaderboard-jasmine/tests/jasmine/client/integration/LeaderboardSpec.js
spyOn(Template.leaderboard.__helpers, 'players')
```
which resulted in another error: 
> players() method does not exist

I have seen the 2nd usage in the [Telescope repo](https://github.com/TelescopeJS/Telescope/blob/master/tests/jasmine/client/unit/commentItemSpec.js), so it should have worked. Does anyone have had similar experience and sorted it out?

**Comment by slackersoft** [comment]
This sounds like an issue with leaderboard-jasmine and not jasmine itself. Nothing in your examples would be code from within jasmine itself, so you should probably open an issue with leaderboard-jasmine.

Closing this unless you can narrow it down to an issue with jasmine itself. Thanks for using jasmine!
