### ISSUE TITLE
Issue with angular.mock.inject method

### ISSUE THREAD

**Issue by mal90** [jasmine/jasmine#863]
I am using karma/jasmine and i have the following jasmine test case .

    'use strict';

    describe('companyService', function() {

    var $httpBackend, companyService;

    beforeEach(angular.mock.module('myApp'));

    beforeEach(angular.mock.inject(function($httpBackend , companyService ) {
        $httpBackend = $httpBackend;
        companyService = companyService;
    }));

    it('should return a promise for getCompany function', function() {
        expect(typeof companyService.getCompany('foobar').then).toBe('function');
    }); 

    });

for some reason the execution doesn't enter the **angular.mock.inject(function(_$httpBackend_ , _companyService_ ) {**  code block . Because of this i am getting the following error when i try to access getCompany() method .

        minErr/<@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/bower_components/angular/angular.js:63:12
        loadModules/<@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/bower_components/angular/angular.js:4138:15
        forEach@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/bower_components/angular/angular.js:323:11
        loadModules@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/bower_components/angular/angular.js:4099:5
        createInjector@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/bower_components/angular/angular.js:4025:11
        workFn@C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/node_modules/angular-mocks/angular-mocks.js:2425:44
        TypeError: companyService is undefined in C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/test/company/Compa
    nyServiceSpec.js (line 15)
        @C:/Users/userone/Documents/myAppPkg/myApp/WebApiRole/test/company/CompanyServiceSpec.js:15:16

if this got something to do with a missing of a dependency , how do i test (isolate) the missing dependency . The only error i get is the undefined error which is not exactly helping me to find the rootcause . I have used **karma start --log-level debug** but it doesn't tell you much about the issue . If anyone can help me to pinpoint the issue rootcause it would be much appreciated .

**Comment by slackersoft** [comment]
Are you sure the function passed to `inject` is not actually invoked? A `console.log` or a `debugger` should help you confirm that. But, from the code you pasted it looks like you just have a variable scoping issue.

Inside the function passed to `inject` your parameter names `$httpBackend` and `companyService` end up shadowing the variables with the same name declared directly in the `describe`, and thus you can't assign anything to the outer variables.

Your options are basically:
* rename the outer variables to the don't get shadowed
* rename the parameters (I think you can surround with `_` for just such an occasion, so you would have `_$httpBackend_` etc)

Hope this helps. Thanks for using jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else from the community about this issue, so I'm going to close it.

**Comment by angel3509268** [comment]
I have a  similar problem

**Comment by Thorocaine** [comment]
I have this issue.

I have tried

    beforeEach(() => angular.mock.inject(($q: any) => {
        console.log('injecting');
    }));

I have tried

    beforeEach(angular.mock.inject(($q: any) => {
        console.log('injecting');
    }));

instead of $q I have tried $rootScope, $http, and _myOwnService_
I have tried :any, and :ng.IWhatEverService.

It is never running, the `console.log` never writes (I can see other console logs from `describe` etc writing to the terminal.

After the console output from my `it` I get an error

    Firefox 57.0.0 (Windows 10 0.0.0) App should work FAILED
        minErr/<@App/testSpecs.js:464:12
        loadModules/<@App/testSpecs.js:5305:15
        forEach@App/testSpecs.js:758:11
        loadModules@App/testSpecs.js:5265:5
        createInjector@App/testSpecs.js:5187:19
        WorkFn@App/testSpecs.js:37414:44
        angular.mock.inject@App/testSpecs.js:37394:35
        @App/testSpecs.js:271:37
        ContextKarma/this.loaded@http://localhost:9876/context.js:162:7

I have read everything I could find, comparing what I am trying to every example I could get my hands on, and nothing seems wrong.

Any ideas on what else I could try?

**Comment by Thorocaine** [comment]
I only get this error when I try `angular.mock.inject`. I also have an `angular.mock.module` which works.
If I remove the inject, but keep the module, and run an `it expect true to be true` sort of thing works fine.

**Comment by Thorocaine** [comment]
Okay, if I comment out `beforeEach(angular.mock.module('App'));` then injection works, but then it doesn't let me inject my own services.
So when then have I done wrong with `angular.mock.module`.

**Comment by Thorocaine** [comment]
also, `console.log("AG -> " + angular.module('App').name);` provides the expected output, so my angular module is loaded.

**Comment by slackersoft** [comment]
@Thorocaine If the errors you're seeing are with the different `angular.mock` functions, it might make more sense to bring this issue to an angular forum as those functions aren't provided by Jasmine.

Hope this helps. Thanks for using Jasmine!

**Comment by Thorocaine** [comment]
It turned out to be DI.
I found changing the browser from Firefox to Chrome gave better information, and told me what dependancy what not being resolved.

Thank you for your response.
