### ISSUE TITLE
Add setImmediate support to jasmine.clock

### ISSUE THREAD

**Issue by Aaronius** [jasmine/jasmine#866]
The code I am testing is leveraging `setImmediate()` to defer a function call. It would be nice to use Jasmine's clock to fast-forward over the delay similar to how I would use it to fast-forward over a `setTimeout(fn, 0)` call.

**Comment by slackersoft** [comment]
As `setImmediate` is only implemented in IE 10 and doesn't look like it will become a standard any time soon (if ever), I don't think it is something jasmine is going to support as part of it's mock clock implementation. 

Closing. Thanks for using jasmine!

**Comment by Aaronius** [comment]
Understandable. Thanks.

**Comment by bvaughn** [comment]
Adding support would still be nice for [React users](https://facebook.github.io/react-native/docs/timers.html) or those using [the setImmediate polyfill](https://www.npmjs.com/package/setimmediate).

**Comment by slackersoft** [comment]
In general, jasmine tries to stay away from implementing things based on polyfills, so this isn't something we're likely to put into jasmine. That said, you should be able to provide your own `setImmediate` that simply calls `setTimeout(..., 0)` only in jasmine that would allow jasmine's existing mock clock to work as you expect.

**Comment by agirorn** [comment]
Now I think it is time to add support for [setImmediate](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args) sine node.js seem to have a stable version of it.

**Comment by slackersoft** [comment]
Jasmine is not solely a testing framework for node.js code, it also needs to work in all of the browsers that we currently support (IE8 and up, Chrome, Firefox, Safari 6 and up). Not all web projects will be using a polyfill for `setImmediate` in those environments, so we don't want the clock to provide a mock version of a function that doesn't actually exist.

This still isn't high up on the list, but we'd be willing to review a pull request that provided a mock `setImmediate` _only_ when there is one already present on the `global` object.

**Comment by sgravrock** [comment]
I'm closing this due to prolonged inactivity, but anyone who wants the proposed change enough to implement it should still feel free to submit a PR.
