### ISSUE TITLE
toHaveBeenCalledWith Can't Match

### ISSUE THREAD

**Issue by johnnyshankman** [jasmine/jasmine#867]
For some reason toHaveBeenCalledWith is unable to match some calls to my spy in one oddball test even though the calls and expectations are identical. I'm making two calls to the same method with different parameters and then in the test I check to see if that same method was called two separate times with the two different sets of parameters. The first expectation passes and the second expectation fails every time.

The test in question:
```
it('removes the transform on feed and globalMenuWrap', function() {
      expect(utility.setPrefixedStyle).toHaveBeenCalledWith($m('#feed, .globalMenuWrap'), 'transform', '');
      expect(utility.setPrefixedStyle).toHaveBeenCalledWith($m('.sideNav'), 'transform', '');
});
```

The code that is most definitely getting executed:
```
global.requestAnimationFrame(function(){
      $m(document.body).removeClass("showSideNav");
      utility.setPrefixedStyle($m('#feed, .globalMenuWrap'), 'transform', '');
      utility.setPrefixedStyle($m('.sideNav'), 'transform', '');
});
```

The resulting failure log which makes no sense:
```
Expected spy setPrefixedStyle to have been called with
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ] 

but actual calls were

[ ({ 0: HTMLNode, 1: HTMLNode, length: 2, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '#feed, .globalMenuWrap' }), 'transform', '' ], 
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ].
```

As you can see from the above print out, the calls are actually identical and toHaveBeenCalledWith seems to be unable to match anything past the first call made to the spy.

As a workaround, I also tried using argsFor(1) but this also failed in even more bewildering way. Here is what that test looks like:
```
it('removes the transform on sideNav', function() {
      expect(utility.setPrefixedStyle.calls.argsFor(1)).toEqual([$m('.sideNav'), 'transform', '']);
});
```
And here is the bewildering failure log:
```
Expected 
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ] 
to equal 
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ].
```

**Comment by Gerg** [comment]
Is this definitely because it is the second call? If you remove the first call to `setPrefixedStyle` and the first expectation, does the test pass?

**Comment by johnnyshankman** [comment]
I commented out the first call and the first expectation and surprisingly it still fails. I apologize for assuming it was due to there being multiple calls.

Here is the new code, test, and failure log:
```
global.requestAnimationFrame(function(){
      $m(document.body).removeClass("showSideNav");
      //utility.setPrefixedStyle($m('#feed, .globalMenuWrap'), 'transform', '');
      utility.setPrefixedStyle($m('.sideNav'), 'transform', '');
});
```
```
it('removes the transform on feed and globalMenuWrap', function() {
      //expect(utility.setPrefixedStyle).toHaveBeenCalledWith($m('#feed, .globalMenuWrap'), 'transform', '');
      expect(utility.setPrefixedStyle).toHaveBeenCalledWith($m('.sideNav'), 'transform', '');
});
```
```
Expected spy setPrefixedStyle to have been called with 
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ] 
but actual calls were 
[ ({ length: 0, prevObject: ({ 0: HTMLNode, context: HTMLNode, length: 1 }), context: HTMLNode, selector: '.sideNav' }), 'transform', '' ].
```

**Comment by Gerg** [comment]
Jasmine's equality test sometimes takes into consideration some factors that are not represented by the pretty printer (see #786, #598). We would love to update the pretty printer to include more information, but without having access to your code, it is difficult to tell what is causing the inequality.

If you want to explore yourself, Jasmine's equality check lives here: https://github.com/jasmine/jasmine/blob/4be20794827a63ca5295848c58ffc478624ee4dc/src/core/matchers/matchersUtil.js#L77

If you can get more information about why the equality match is failing or reproduce this in a standalone example, I would be happy to look into it.

**Comment by slackersoft** [comment]
We haven't heard anything else from the community on this in a while, so I'm going to close it for now.

**Comment by johnnyshankman** [comment]
@Gerg Is there anyway to get an ugly printout so that I can see deep into the object and find the difference manually?

**Comment by slackersoft** [comment]
@johnnyshankman The pretty printer has been updated so it should now print out all the things that are used when doing an equality comparison. You can also define a `jasmineToString` (or just `toString` if you're working out of HEAD) to print out whatever you want about the object.

**Comment by johnnyshankman** [comment]
@slackersoft Thank you a ton. I'll update so that I can get that pretty printer. :+1:
