### ISSUE TITLE
Jasmine + .swf (jasmine.yml?)

### ISSUE THREAD

**Issue by NavyAnt24** [jasmine/jasmine#868]
Rails 4, Backbone + Marionette, Jasmine 2.1.3

I have added the DataTables TableTools plugin to our Rails app, and am trying to test that a certain callback gets called when the user attempts to export a PDF and Excel file. However, the TableTools plugins relies of Flash (a .swf file) for this functionality.

I am able to successful check that the event in question gets called when the user `prints` using the plugin, which does need the Flash functionality. However, when running the tests, the event does not get called when I try to export a PDF of Excel file.

I imagine the problem could be because I need to add the `assets/copy_csv_xls_pdf.swf` to `jasmine.yml`, but I don't know if this is the right approach.

Is what I am trying to do even possible using Jasmine?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

As far as your tests go though, you probably want to just test that you call into the library correctly, with a mock and not worry about testing the library itself.

Thanks for using jasmine! Closing.
