### ISSUE TITLE
Jasmine using anonymous instead of Object

### ISSUE THREAD

**Issue by alxdg** [jasmine/jasmine#870]
Hello All,

I have a test that it is checking that the content of two objects is equal, this test used to work in jasmine 1.3 but it doesn't work in Jasmine 2.x, I don't understand what "anonymous" means, this is the first time that I have encounter this issue with the framework, any help is greatly appreciated 

Expected [ anonymous({ request: '321455' }) ] to equal [ Object({ request: '321455' }) ]

**Comment by slackersoft** [comment]
Jasmine now includes the constructor when checking for equality of two objects, and the name of the constructor is what is being printed out before the `()`. The string `anonymous` appears to be the actual name of the constructor for the actual object passed to the expectation, as jasmine's pretty printer does not attempt to clean up a constructor without a name.

Hopefully this helps. If not, can you share a bit more of your spec itself?

Thanks.

**Comment by slackersoft** [comment]
We haven't heard anything else from the community on this issue in a while, so I'm going to close this.
