### ISSUE TITLE
.toHaveBeenCalledWith and modified objects

### ISSUE THREAD

**Issue by shamansir** [jasmine/jasmine#872]
The actual problem happens thanks to object references—I realize it's not a bug, but it really looks like that from the first sight. Probably you have a solution or some advice for that.

```javascript
describe('spy issue', function() {
    var foo = {};
    function injectAndCall(prop, val, cb) {
        foo[prop] = val;
        console.log(foo);
        cb(foo);
    };

    it('spy issue', function() {
        var mySpy = jasmine.createSpy('test');

        injectAndCall('a', 0, mySpy);
        injectAndCall('b', 1, mySpy);

        expect(mySpy).toHaveBeenCalledWith({ a: 0 });
        expect(mySpy).toHaveBeenCalledWith({ a: 0, b: 1 });
    });
});
```

The response is: 

`Expected spy test to have been called with [ Object({ a: 0 }) ] but actual calls were [ Object({ a: 0, b: 1 }) ], [ Object({ a: 0, b: 1 }) ].`

If you check the console, however, you'll get:

```
{ a: 0 }
{ a: 0, b: 1 }
```

May be this could be solved with deep-cloning arguments for spies?

This example is quite easy, but this also could happen when `foo` has a reference to another object inside, and the latter in its turn is a subject to modifications.

**Comment by shamansir** [comment]
...or could there be a special matcher like `.toHaveBeenCalledWith(jasmine.identicalTo({ a: 0 }))`?

**Comment by shamansir** [comment]
I've looked up for a possible reason in source and I discovered that indeed there's a deep-check there, but of course for this case object in this line: https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js#L159 is already modified. So the case in the example is easily solved with: 

```javascript
to_test('a', 0, mySpy);
expect(mySpy).toHaveBeenCalledWith({ a: 0 });
to_test('b', 1, mySpy);
expect(mySpy).toHaveBeenCalledWith({ a: 0, b: 1 });
```

Could not be as easy in complex cases when one have no ability to put an expectation between the calls, though.

**Comment by shamansir** [comment]
In my code I solved it with:

```javascript
mySpy.and.callFake(function() {
    if (mySpy.calls.count() === 1) {
        expect(mySpy).toHaveBeenCalledWith({ 'a': 0 }, jasmine.anything());
    } else if (processSpy.calls.count() === 2) {
        expect(mySpy).toHaveBeenCalledWith({ 'a': 0, 'b': 1 }, jasmine.anything());
    }
});

// code which emits mySpy:
injectAndCall('a', 0, mySpy);
injectAndCall('b', 1, mySpy);
```

**Comment by slackersoft** [comment]
I would be happy to review a pull request that allowed the `callTracker` for a spy to alternatively save arguments by value. This could be used something like:

````javascript
jasmine.createSpy().calls.saveArgumentsByValue()
````

**Comment by a-r-d** [comment]
@slackersoft hey did anyone ever do some work on this? If not I am interested in adding this feature.
