### ISSUE TITLE
beforeAll called before beforeEach from the parent describe

### ISSUE THREAD

**Issue by ondrejhanslik** [jasmine/jasmine#873]
I have just encountered something which I think is an issue. Let's have the following simple test:

```javascript
describe('level 1', function () {
    beforeEach(function () {
        console.log('Level 1 beforeEach');
    });
  
    describe('level 2', function () {
        beforeAll(function () {
            console.log('Level 2 beforeAll');
        });
    
        it('test 1', function () {
            console.log('Test 1');
        });
    
        it('test 2', function () {
            console.log('Test 2');
        });
    });
});
```

I would expect that console output would be:

```
Level 1 beforeEach
Level 2 beforeAll
Test 1
Level 1 beforeEach
Test 2
```

However, the actual output is:

```
Level 2 beforeAll
Level 1 beforeEach
Test 1
Level 1 beforeEach
Test 2
```

I am not sure if this behavior is expected but it strikes me as not obvious and it is definitely not documented.

**Comment by slackersoft** [comment]
This is exactly what is supposed to happen. The `beforeAll` and `afterAll` functions wrap the specs where the `beforeEach` and `afterEach` functions wrap an individual spec.

If jasmine ran in the order you are expecting, then the `beforeEach` for the first spec would execute before the `beforeAll`, but the second spec's `beforeEach` would execute after it, and thus have a different setup. Since the `beforeEach` is declared at the `describe` level, a user should be able to expect that it should be at the same state for each spec that it is run for.

Closing.

**Comment by PaddyMann** [comment]
I'm with @ondrejhanslik - this is an unfortunate constraint!

As an example use case, I have a page with an Excel file uploader that I'm testing in Protractor. I expected to be able to:

```
describe('My page', function () {
  beforeAll(function () {
    // Call the API and set-up some users
    // Login
  });

  beforeEach(function () {
    // Open the page I'm testing
  });

  describe('Header', function () {
    it('should be called \'My Excel file uploader\'', function () {
      // expect...
    });
  });

  describe('Excel file uploader', function () {
    beforeAll(function () {
      // Upload an Excel file
    });

    it('should require A1 to be filled in', function () {
      // expect...;
    });

    it('should require A2 to be filled in', function () {
      // expect...;
    });
});
```

I would expect it to run:

- beforeAll1
- beforeEach1
- spec1
- beforeEach1
- beforeAll2
- spec2
- beforeEach1 
- spec3
- beforeEach1
- spec4

Essentially, I expect beforeAll to act the same a beforeEach (note order of beforeEach1 > beforeAll2 > spec3) with the exception that it is doesn't get called more than once.

I'm not clear on your reasoning @slackersoft - I see this as a valuable addition and not overly complex to implement?

**Comment by ondrejhanslik** [comment]
Don't let me wrong. After diving into using `beforeAll`, I completely understand the reasoning and I prefer the current order of execution. However, the problem is that when you first start using it, you expect it to be different. The ordering should be mentioned in the documentation.

**Comment by PaddyMann** [comment]
With the current implementation (if I understand correctly), it only really makes sense to have a single `beforeAll`, and this should either be outside of any `describe` block, or at the top of the outermost `describe` block.

i.e. It would make no sense for my 2nd `beforeAll` to be located where it is.

So I would see adding support for what I'm after as an extension of what's possible, rather than something that goes against your current desired behaviour.

**Comment by PaddyMann** [comment]
My workaround is:

```
describe('My page', function () {
  beforeAll(function () {
    // Call the API and set-up some users
    // Login
  });

  beforeEach(function () {
    // Open the page I'm testing
  });

  describe('Header', function () {
    it('should be called \'My Excel file uploader\'', function () {
      // expect...
    });
  });

  describe('Excel file uploader', function () {
    it('should validate A1', function () {
      // upload
      // expect1
      // expect2
      // expect3
    });

    it('should validate A2', function () {
      // upload
      // expect1
      // expect2
      // expect3
    });
});
```

Now that's sucky - I'm having to duplicate the upload code (which is abstracted in a page object, so at least it's only a one liner), and then put multiple expectations in each spec (bleugh).

If there's a better workaround or if I'm fundamentally getting things wrong, I'd love to hear suggestions :)

**Comment by slackersoft** [comment]
@PaddyMann You should be able to use `beforeAll` and `beforeEach` wherever you want in your spec hierarchy. If you don't want the code duplication in your tests, you should be able to use a `beforeEach` in your inner `describe` to perform the upload.

All `beforeAll`s need to be run before the `beforeEach` because that is how we can guarantee that all the specs in the given `describe` have their setup run in the same order. If it ran [as you proposed](https://github.com/jasmine/jasmine/issues/873#issuecomment-115234432) your actual order of operations would have been:

1. Call the API and do setup - beforeAll1
1. Login
1. Open the page - beforeEach1
1. expectations - spec 1
1. Open the page - beforeEach1
1. Perform the Upload - beforeAll2
1. expectations - spec 2
1. Open the page - beforeEach1
1. expectations - spec 3
1. Open the page - beforeEach1
1. expectations - spec 4

This would make any expectations in specs 3 and 4 be in a state where they had just loaded the page with the form and the upload would not have happened yet.

**Comment by PaddyMann** [comment]
I see how my example confuses - actually in steps 8 and 10, the URL is the same and my test doesn't refresh the page if it's already loaded. 

I understand the point around tests in the same describe block having the same apparent state, but still lament the lack of the flexibility. Never mind - thanks for taking the time to explain (again)

**Comment by klinki** [comment]
Isn't there any way how to modify execution order of beforeEach/beforeAll? 
I need to execute it on on hierarchy level. (I need basically exactly the same thing as others in this thread). 


```
describe('Root describe', function() {
     beforeAll(function() { });
     beforeEach(function() {}); 
     afterEach(function() {});
     afterAll(function(){}); 
     
    it(function() {});

   describe('Nested describe', function() {
     beforeAll(function() { });
     beforeEach(function() {}); 
     afterEach(function() {});
     afterAll(function(){}); 
    
     it(function() {});
  });
});
```

And order would be 

1. Root describe beforeAll
2. Root describe beforeEach
3. Root describe it
4. Root describe afterEach
5. Root describe beforeEach
6. Nested describe beforeAll
7. Nested describe beforeEach
8. Nested describe it
9. Nested describe afterEach
10. Nested describe afterAll
11. Root describe afterEach
12. Root describe afterAll


Idea is basically to handle the describe block in similar way as the it block.

**Comment by chaoran** [comment]
I agree that the beforeAlls should execute in the order of their hierarchical position. I really don't see the point of the constraint to running all beforeAlls before every beforeEach. This makes the beforeAll only makes sense when using at the outermost scope. With this constraint, what's the point of using a beforeAll in a child scope?

**Comment by songokudbz** [comment]
I also find this nonsense. I would suggest making a Before All for each individual 'describe' ....

**Comment by keithdtyler** [comment]
I don't agree with anyone who thinks beforeAll should run after beforeEach. It doesn't make any sense from an organizational perspective. beforeEach runs before each test. beforeAll runs before the whole describe. The beforeEach is tied to the tests and the beforeAll is tied to the describe. Doing the beforeAll after the beforeEach would break that boxing. This is pretty standard stuff in test engines. 

    beforeAll -------
    |   beforeEach -------
    |   |   test1 --------
    |   beforeEach -------
    |   |   test2 -------
    ...

**Comment by PaddyMann** [comment]
Very happy for beforeAlls to always run before any beforeEachs @keithdtyler. Only problem is that currently beforeAlls attached to sub-describes are hoisted to the top and shouldn't be.

**Comment by Gerg** [comment]
@PaddyMann 

Jasmine's ordering of `beforeAll`s and `beforeEach`s is consistent with other BDD frameworks.

For example this RSpec suite:
```ruby
RSpec.describe 'foo' do
  before(:each) do
    puts 'each 0'
  end

  before(:all) do
    puts 'all 0'
  end

  it 'spec' do
    puts 'spec 0.0'
  end

  it 'another spec' do
    puts 'spec 0.1'
  end

  describe 'suite' do
    before(:each) do
      puts 'each 1'
    end

    before(:all) do
      puts 'all 1'
    end

    it 'spec' do
      puts 'spec 1.0'
    end

    it 'another spec' do
      puts 'spec 1.1'
    end
  end
end

```

and the corresponding jasmine suite:

```javascript
describe("foo", function() {
    beforeEach(function() {
        console.log('each 0');
    });
    
    beforeAll(function() {
        console.log('all 0');
    });

    it('spec', function() {
        console.log('spec 0.0');
        expect(true).toBe(true);
    });
    
    it('another spec', function() {
        console.log('spec 0.1');
        expect(true).toBe(true);
    });

    describe('suite', function() {
        beforeEach(function() {
            console.log('each 1');
        });
        
        beforeAll(function() {
            console.log('all 1');
        });

        it('spec', function() {
            console.log('spec 1.0');
            expect(true).toBe(true);
        });
    
        it('another spec', function() {
            console.log('spec 1.1');
            expect(true).toBe(true);
        });
    });
});
```

Here is the Rspec output:

```
all 0
each 0
spec 0.0
each 0
spec 0.1
all 1
each 0
each 1
spec 1.0
each 0
each 1
spec 1.1
```

and the Jasmine output:

```
all 0
each 0
spec 0.0
each 0
spec 0.1
all 1
each 0
each 1
spec 1.0
each 0
each 1
spec 1.1
```

**Comment by keithdtyler** [comment]
Didn't know the "outer" each fired for all the tests for the inner describe in addition to the "inner" each, but it's nice to know. 

@PaddyMann It doesn't look to me like a nested describe's beforeEach "bubbles to the top" at all, as long as the "inner" beforeEach is defined inside the nested describe block.

**Comment by PaddyMann** [comment]
@keithdtyler the beforeEachs do not, but the beforeAlls did I believe. I'm on holiday and can't double check this, but this is what I remember the issue to have been. Apologies for any inaccuracy.

**Comment by kevinkuebler** [comment]
I agree with @PaddyMann and find the ordering with regards to nested contexts to be unintuitive. My expectation is that nested `describe` contexts are treated as one spec with respect to the `beforeAll` and `beforeEach` setups of their parent. So given the example from @Gerg I would expect the following output:

```
all 0
each 0
spec 0.0
each 0
spec 0.1
each 0     <-- this not happening here is what surprised me
all 1
each 1
spec 1.0
each 1
spec 1.1
```
It other words, I expect the parent `beforeEach` to be run once _before_ the nested context, instead of being treated as another `beforeEach` _within_ the nested context. Obviously, changing to this ordering would be a pretty major breaking change. It might be nice to have a way to configure the framework for this mode though.

**Comment by JoshCheek** [comment]
Surprising that this has so much attention. It's a totally reasonable decision. Paddy's is reasonable too, it basically amounts to "before all of *these* tests". For the other perspectives, I suspect the confusion is due to the structure of the syntax causing it to feel like tree traversal or something, it'll probably make sense if you think about the meaning of the method names as human words. Anyway, cheers to the maintainers for fighting the good fight 🍻

**Comment by masaeedu** [comment]
@JoshCheek All of that is well and good, but how am I supposed to actually do sequencing of `beforeAll`s? Everyone keeps pointing to other frameworks and their feelings about the issue, but there is a use case that is unserved by the existing feature set. If it needs to be called `beforeThisIsTotallyNotAllThisIsSomethingElse`, and then be sequenced hierarchically, that's fine, but we still need a way to do:

```
do some setup
run 20 general tests
do some more setup
run 10 special tests
teardown special test setup
teardown general setup
```

As @PaddyMann said, the duplication he settled for is a workaround. This is not an acceptable workaround in all scenarios. I'm doing integration tests, and it takes on the order of minutes to do setup. I really don't want to saddle every one of my sub-second tests with a minute long setup phase.

**Comment by slackersoft** [comment]
@masaeedu that's exactly what `beforeAll` and `afterAll` are for. Possibly the confusion comes from the fact that they are scoped within the `describe` that they are within. This means that the specs in a child `describe` will also run in between the parents `beforeAll` and `afterAll`.

Something like this seems like it would solve your problem:

```javascript
describe('global', function() {
  beforeAll(function() { /* general setup */ });

  it('is not special', function() {});

  describe('special', function() {
    beforeAll(function() { /* special setup */ });
    it('is special', function() {});
    afterAll(function() { /* teardown special setup */ });
  });

  afterAll(function() { /* teardown general setup */ });
});
```

I've moved the `afterAll`s out to where the actually run to make it more clear, but you would probably group them with the `beforeAll`s in a real suite.

**Comment by jeme** [comment]
Ok so this issue had me highly confused, after doing some poking around so just wanted to share some observations.

Given this spec:
```javascript
var log = console.log;
describe('spec', function() {
    beforeAll(function() { log('spec.beforeAll'); });
    beforeEach(function() { log('spec.beforeEach'); });

    describe('nested_01', function() {
        beforeAll(function() { log('spec.nested_01.beforeAll'); });
        beforeEach(function() { log('spec.nested_01.beforeEach'); });
        it('it_001', function() { log('spec.nested_01.it_001'); });
        it('it_002', function() { log('spec.nested_01.it_002'); });
        afterEach(function() { log('spec.nested_01.afterEach'); });
        afterAll(function() { log('spec.nested_01.afterAll'); });
    });

    describe('nested_02', function() {
        beforeAll(function() { log('spec.nested_02.beforeAll'); });
        beforeEach(function() { log('spec.nested_02.beforeEach'); });
        it('it_001', function() { log('spec.nested_02.it_001'); });
        it('it_002', function() { log('spec.nested_02.it_002'); });
        afterEach(function() { log('spec.nested_02.afterEach'); });
        afterAll(function() { log('spec.nested_02.afterAll'); });
    });

    afterEach(function() { log('spec.afterEach'); });
    afterAll(function() { log('spec.afterAll'); });
});
```

We get:
```
spec.beforeAll
spec.nested_01.beforeAll
spec.beforeEach
spec.nested_01.beforeEach
spec.nested_01.it_001
spec.nested_01.afterEach
spec.afterEach
spec.beforeEach
spec.nested_01.beforeEach
spec.nested_01.it_002
spec.nested_01.afterEach
spec.afterEach
spec.nested_01.afterAll
spec.nested_02.beforeAll
spec.beforeEach
spec.nested_02.beforeEach
spec.nested_02.it_001
spec.nested_02.afterEach
spec.afterEach
spec.beforeEach
spec.nested_02.beforeEach
spec.nested_02.it_002
spec.nested_02.afterEach
spec.afterEach
spec.nested_02.afterAll
spec.afterAll
```

Which seems perfectly reasonable to me, but lets dig deeper.

> beforeAll/afterAll bubbles to the top most scope.

Thats incorrect if we examine the output above, `spec.beforeAll`, `spec.nested_01.beforeAll` and `spec.nested_02.beforeAll` would all be at the top of the output if that was the case, but `spec.nested_02.beforeAll` clearly comes later...

> outer scoped beforeEach/afterEach runs for each test in inner scope.

This may be counter-intuitive, but either way that it would run would give some feature that wasn't there, so it being defined like this is just fine...
I am not a fan of beforeEach/afterEach anyways so it's of little consequence to me.

**Comment by psxvoid** [comment]
The current execution order should be written in **RED** at the top of the documentation because I stumble upon this issue multiple times for almost 5 years. And it hurts each time.

Shouldn't it be at least configurable? Will a pull request be acceptable for such a feature?
