### ISSUE TITLE
Is there a way to get a handle of the spec name in the AfterEach block ?

### ISSUE THREAD

**Issue by raghavan85** [jasmine/jasmine#875]
Hi Team,

We can perform jasmine.getEnv().currentSpec.description to get the name of the test in the AfterEach block in Jasmine 1 version for protractor but doesn't work when switching to jasmine2 framework in Protractor.

I see a closed story here: https://github.com/jasmine/jasmine/issues/611.

The scenario specifically where I would use is to capture screenshot with file name containing the spec name. 

Is it possible to bring back the deprecated feature or provide a different mechanism that I can include in every spec file in the afterEach block to capture screenshots with the filename containing the spec name.

**Comment by raghavan85** [comment]
Found protractor-jasmine2-html reporter which does the job.

**Comment by hjhart** [comment]
For those who stumble upon this: https://github.com/Kenzitron/protractor-jasmine2-html-reporter
