### ISSUE TITLE
Is there a standard for object method tests in Jasmine?

### ISSUE THREAD

**Issue by bingomanatee** [jasmine/jasmine#876]
i.e., testing new List()).add(), FooCollection.index (static methods)

is `it('List#add"...)`

or 

`it("List.add"...)`

preferred?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Jasmine does not enforce any kind of naming of your `it`s or `describe`s. Closing.
