### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by alex-dow** [jasmine/jasmine#878]
introduction.html contains almost the entirety of the Jasmine documentation with no form of navigation.

It would be very very useful to have at minimum a table of contents so that it is easy to jump to specific sections of the documentation when needed.

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing this.
