### ISSUE TITLE
Expectations in async function are not asserted

### ISSUE THREAD

**Issue by jeroenvekemans** [jasmine/jasmine#882]
# Context
Expects declared in asynchronous function are not asserted.

# Environment
Protractor 1.6.1 (which packs Jasmine 2.1.1)
Request 2.53.0

# Example
```javascript
    var request = require('request');
    describe('async test', function() {
        it('should verify after done', function(done) {
                var options = {
                        url: 'http://www.google.com',
                        method: 'GET',
                        json : {},
                        headers: {
                            'Accept':'*'
                        }
                };

                request(options, function(error, message, body) {
                    expect(true).toEqual(false);

                    done();
                });
        });
    });
```

The outcome of this test is successful (but it clearly should fail). But when I replace the done invocation with setTimeout(done, 1000), it fails.

**Comment by ljwall** [comment]
I just tried to replicate this and got the expectation failing as it should, using both Jasmine 2.1.1 directly and Protractor 1.6.1.

**Comment by jeroenvekemans** [comment]
@ljwall Thank you for the response, it seems that I did not provide the intended example. The example below does succeed using protractor 1.6.1, but fails correctly when using the latest version of protractor. Executing the test with jasmine also shows correct behaviour, so I guess it was a problem with protractor/jasminewd in older versions.

```javascript
var request = require('request');

describe('async test', function() {
    it('should fail because of afterEach', function() {
          // verify nothing
    });
});

afterEach(function(done) {
  var options = {
          url: 'http://www.google.com',
          method: 'GET',
          json : {},
          headers: {
              'Accept':'*'
          }
  };

  request(options, function(error, message, body) {
      expect(true).toEqual(false);

      done();
  });
});
```
