### ISSUE TITLE
runnableLookupTable is added to, but never used - causes memory increase for no reason

### ISSUE THREAD

**Issue by lostthetrail** [jasmine/jasmine#884]
The 'runnableLookupTable' is created and added to, but never used. This causes un-required memory increases.

Is there any reason I shouldn't put in a PR to remove this?

**Comment by slackersoft** [comment]
It should be fine to remove the `runnableLookupTable`, I believe it is vestigial from how subsets of specs were run before. It looks like it is just holding onto the `topSuite` which is going to be held onto by other things as well, so I don't know what you'll see much memory improvement from removing it.

**Comment by slackersoft** [comment]
We haven't seen anything else from the community on this issue so I'm going to close it. I'd still be willing to review a pull request that gets rid of the `runnableLookupTable` if it truly isn't used.
