### ISSUE TITLE
Spies and promises

### ISSUE THREAD

**Issue by asvetliakov** [jasmine/jasmine#886]
They don't work from promises callbacks for some reason:
```javascript
    validateToken: function () {
        var options = {
            url: this.appOptions.exAuthUrl,
            data: {
                method: 'validateToken',
                token: this.get('token')
            }
        };
        return Promise.resolve($.get(options)).then(function (obj) {
            if (obj.status === "OK") {
                return true;
            } else {
                throw new Error("Invalid token");
            }
        });
    }

       describe("when calling validateToken", function () {
            var successMock, errorMock;
            beforeEach(function () {
                model.set('token', 'testtoken');

                successMock = jasmine.createSpy('success');
                errorMock = jasmine.createSpy();
            });

            it("Should resolve promise if response is correct and status OK", function (done) {

                model.validateToken().then(function (data) {
                    console.log('success');
                    successMock();
                }).catch(function () {
                    console.log('err');
                }).finally(function () {
                    console.log('don');
                    done();
                });

                jasmine.Ajax.requests.mostRecent().respondWith({
                    status: 200,
                    responseText: '{"status": "OK", "response": "text"}'
                });


                expect(successMock).toHaveBeenCalled();
            });
      });
```
Gives me following:
'success'
'don'
Expected spy success to have been called.

Jasmine 2.3.4

**Comment by slackersoft** [comment]
Some promise libraries (and the native ones too, I think) will invoke their callbacks in a `setTimeout(0)` or something similar. This would cause your expectation to be run before the callbacks are actually invoked.

To confirm if this is the case, can you make your spec async (receive the `done` callback) and change your expectation to be in its own `setTimeout`? e.g

````javascript
setTimeout(function() {
  expect(successMock).toHaveBeenCalled();
  done();
}, 50);
````

If this fixes the spec, it should just be a timing issue in the promise library.

**Comment by ljwall** [comment]
slackersoft is right - indeed it is part of the the promise spec that `then` should execute asynchronously.  (See https://promisesaplus.com 2.2.4 and 3.1.)

However, rather than use a timeout to coordinate, you should either move the `expect` into the `finally` block, or you could drop the spy and the expect altogether and just use:
```javascript
model.validateToken()
  .then(done)
  .catch(done.fail);
```

**Comment by ljwall** [comment]
Sorry, just changing my mind. You shouldn't use timeout like this in application code, but here, where you know the promise should resolve promptly, slackersoft's suggestion will give a more descriptive failure message if the promise rejects or pends for too long.

**Comment by asvetliakov** [comment]
Yes, that makes sense. My original thought was that expect() will be called after done() (may be it can be a feature request?), but looks like it's wasn't so. I was slightly confused.

**Comment by slackersoft** [comment]
In an async spec (or `beforeEach`, etc) when you invoke the `done` callback you are informing jasmine that *all* work in that function is complete and it should move on to the next thing in the suite. Nothing should be happening after `done` is called.

If you need that, you can put the async portion in a `beforeEach` and your expectations in the `it`.

**Comment by slackersoft** [comment]
It sounds like you have a solution to this issue, and it hasn't seen any activity in a while, so I'm going to close it.
