### ISSUE TITLE
Add before and after hooks

### ISSUE THREAD

**Issue by lvaldovinos** [jasmine/jasmine#887]
Hi, 

Any possibility of adding before/after hooks? i do understand there's a beforeEach/afterEach that runs before/after executing every spec, but what i'm looking for is a hook that's executed before/after all the specs.

Regards.

**Comment by r4j4h** [comment]
Hmmm, just incase you weren't aware, they work in `describe`'s which run before/after the specs therein respectively, I'm not sure if there is a global or higher level version than that though.

**Comment by slackersoft** [comment]
`beforeAll` has been in Jasmine since version 2.1. This should be exactly what you're looking for. 

Closing.

**Comment by lvaldovinos** [comment]
thanks @slackersoft  for info, i was looking at the wrong documentation :(
