### ISSUE TITLE
Bug in timeouts, jasmine 2.3.1, protractor 2.1.0

### ISSUE THREAD

**Issue by nishakchaudhari** [jasmine/jasmine#890]
When I have a few test cases and one of the test fails because of timeout , all the subsequent tests fail because of timeout. If I increase the timeout for the failing test and make that test case pass, no subsequent test case fails. All work fine. Why subsequent test cases use timeout specified for previous test case?
Below is my spec file:
 'use strict';

describe('page', function() {
    beforeEach(function() {
        console.log('------- in before each');
    });
    afterEach(function() {
        console.log('------- in after each');
    });
    it('test 1',function() {
        return browser.get('https://docs.angularjs.org/api');
    });
    it('test 2',function() {
        return browser.get('https://angularjs.org/');
    },100);
    it('test 3',function() {
        return browser.get('https://docs.angularjs.org/tutorial');
    });
    it('test 4',function() {
        return browser.get('https://docs.angularjs.org/misc/contribute');
    });
});

below is my conf file:
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['todo-spec.js'],
    capabilities: {
        'browserName': 'firefox',
    },
    framework: 'jasmine2',
};

So test 2 fails and test 3 and test 4 also fail.
If test 2 passes then test 3 and test 4 pass .
Also I observed that this problem occurs if using afterEach in suite. If we are not using afterEach , everything works fine.
@slackersoft

**Comment by slackersoft** [comment]
I don't see a `done` callback being received by your `test 2` so jasmine is unable to know that you expect it to be an asynchronous spec. This means it will continue running further specs immediately after it returns.

**Comment by nishakchaudhari** [comment]
Above thing works fine with jasmine1.3 but doesn't work with jasmine 2.
even after using done callback , it fails with timeout error on subsequent tests.

**Comment by slackersoft** [comment]
Have you checked with the Protractor team? Jasmine, itself, doesn't do anything with a return value from an `it`, so I wonder if something changed with how Protractor handled those after the switch to jasmine 2.0.

**Comment by slackersoft** [comment]
We haven't heard anything else from the community on this, and it sounds like it could be an issue with protractor, so I'm going to close this for now. Please open an issue if it looks like you can pinpoint an issue in jasmine itself.
