### ISSUE TITLE
No tests displayed in spec window

### ISSUE THREAD

**Issue by DennisNerush** [jasmine/jasmine#893]
Hi,
I've added Jasmine 2.2.0 via Nuget to my project angular project which is hosted in Visual Studio. When I run the SpecRunner I don't see the specs list but only the title. If I inspect the page I can see that all the specs are there but not displayed. Can you please help?
![capture](https://cloud.githubusercontent.com/assets/2686088/8758053/5fd266d4-2ce8-11e5-87d3-ac40ee537ee2.PNG)

![capture](https://cloud.githubusercontent.com/assets/2686088/8758069/88f06872-2ce8-11e5-90b8-0db0e3e341d7.PNG)

**Comment by slackersoft** [comment]
I don't know much about the NuGet jasmine package, but looking at the html you've posted, I would guess that angular might be messing with jasmine because you've included it before jasmine loads. Jasmine expects to be loaded on the page before any libraries or code under test.

**Comment by DennisNerush** [comment]
Tried without angular. Just the samples. Still nothing. no error or anything..blank page. works in explorer and edge...

**Comment by slackersoft** [comment]
If I'm reading this correctly, it sounds like the specs are working fine in Internet Explorer (and other browsers) but not running correctly in the built-in Visual Studio browser. Jasmine 2.x only supports Internet Explorer version 8 and up, so if the Visual Studio browser is based on IE 7 it may not work properly.

Hope this helps. Thanks for using jasmine!

**Comment by DennisNerush** [comment]
It works on IE and not running on chrome

**Comment by slackersoft** [comment]
Are you seeing any errors in Chrome's javascript console? Are you able to get even a simple `expect(true).toEqual(true);` to work in Chrome?

**Comment by DennisNerush** [comment]
No..I see the page header (the green jasmine line at the top) but no specs

**Comment by slackersoft** [comment]
Sorry we haven't been able to be much help.

It looks like you're seeing the icons for passed and failed specs still. Does it look like the symbols are correct for the specs that are running?

Also, just to confirm when you inspect the html, does it look like the spec results and failures lists are there but not displayed? That could be a CSS issue. If there doesn't appear to even be any html in the page, it could be something else.

Have you talked to the maintainers of the NuGet package? It might be something that package is doing.

**Comment by DennisNerush** [comment]
It started to work. I guess it has to do with the chrome version.

**Comment by slackersoft** [comment]
Awesome. I'm going to close this issue then. Please let us know if you have any other issues.
