### ISSUE TITLE
Only show output for exclusively run test

### ISSUE THREAD

**Issue by OliverJAsh** [jasmine/jasmine#894]
When I run a test exclusively using `fit` or `fdescribe`, the reporter will log all of my tests alongside the exclusively ran test. Is it possible to only show the output for the exclusively ran test? This would be useful for debugging when the user has lots of tests.

**Comment by slackersoft** [comment]
What version of jasmine are you using? What library are you using to run your specs (ruby gem, npm, etc)?

The core of jasmine reports every spec that is defined to whatever reporters are listening. When specs are focused with `fit` and `fdescribe` all other specs should have a status of `disabled` and not be reported to the user.

**Comment by OliverJAsh** [comment]
jasmie-core 2.3.2 which Karma 0.12.31. I guess this is a bug with Karma's reporter then?

**Comment by slackersoft** [comment]
I would certainly investigate this with the Karma maintainers. Closing this for now, since it doesn't seem like it is related to the core of jasmine itself. If it looks like there is something in jasmine that is causing this, please comment again or open a new issue.

Thanks for using jasmine.
