### ISSUE TITLE
Log object without "..." in properties

### ISSUE THREAD

**Issue by davidlmiller21** [jasmine/jasmine#897]
I'm trying to debug the location of a property in my object, which has a nested structure. When I log it in the test, I get the object, but most of the property values are "..." instead of their actual values. How can I log the full object with all its values so that I can properly debug?

**Comment by slackersoft** [comment]
What are you using to log the object. Jasmine does not currently have any way to do logging (other than failed expectations).

**Comment by davidlmiller21** [comment]
I am just using console.log

**Comment by slackersoft** [comment]
`console.log` is provided by the browser (or whatever execution environment you're in), and not by jasmine. If you're not getting the output you like, jasmine can't help you there.

Sorry. Closing.
