### ISSUE TITLE
Specs are executed before async beforeAll completes

### ISSUE THREAD

**Issue by mocsharp** [jasmine/jasmine#898]
We're using nested describe with beforeAll that does async calls, e.g.
```javascript
describe('test suite', function(){
   beforeAll(function(done) {
       // login.... 
      // then wait for url  ...
      .then(function(){
          done();
       });
   }, 20000);

   describe('verify bla', function() {
          it('should bla....', function() {

         });
   });
});
```

From the sample code above, the it spec gets executed before beforeAll calls done.  

We are using jasmine v2.3.4.
Thanks.

**Comment by ljwall** [comment]
Do you have a complete example.  I've just tried this with jasmine v2.3.4:

```javascript
var Promise = require('bluebird');
describe('test suite', function(){
  beforeAll(function(done) {
    (new Promise(function (resolve) {
      setTimeout(resolve.bind(null, 'foo'), 1000);
    }))
    .then(function(){
      console.log('Calling done');
      done();
    });
  }, 20000);

   describe('verify bla', function() {
          it('should bla....', function() {
                console.log('in it');
         });
   });
});
```

and got the expected response
```
Started
Calling done
in it
.
1 spec, 0 failures
Finished in 1.01 seconds
```

**Comment by mocsharp** [comment]
Your example works fine.  I think the reason mine's failing is that the login logic redirects the page to Windows Azure, does login and redirects the user back to the app.  The "it" would kick off while browser is on the Azure page and it would failed with "Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window""

This used to work in protractor 1.x and jasmine 1.x.

**Comment by ljwall** [comment]
It sounds like this is a support issue for protractor rather than a bug in jasmine?  Suggest to close this issue and try the support channels for protractor.

(Note that if your `beforeAll` fails then it will report the specs as failed.  This does _not_ mean that the `it` has been executed.  I'm not a protractor expert, but what springs to mind is that protractor could be looking for angular on the Azure page and failing when it does not find it.)

**Comment by mocsharp** [comment]
Thanks @ljwall.  I have opened a bug on protractor https://github.com/angular/protractor/issues/2378.
