### ISSUE TITLE
Parameterized tests in Jasmine

### ISSUE THREAD

**Issue by ctapobep** [jasmine/jasmine#900]
Is it possible to add this extremely useful feature to Jasmine? Something like in [neckbeard](http://htmlpreview.github.io/?https://raw.github.com/desirable-objects/neckbeard.js/master/website/index.html), but native:
```
var Ʊ = require('neckbeard-node.js');						
describe('spec which loops', function() {
  describe('Here is some functionality', function() {
    Ʊ.iterate('first', 'second', 'sum')
     .where(   3,       3,        6,
               10,      4,        14,
               7,       1,        8
     );
     Ʊ.loop('#first plus #second is #sum', function(first, second, sum) {
       expect(first+second).toEqual(sum);
     });
  });
});
```

**Comment by slackersoft** [comment]
We think functionality like this is better suited to an add-on than as an addition to core. (See #741, #527, and #480). The original poster also made a [plugin](https://github.com/gburghardt/jasmine-data_driven_tests) as well.

Closing this.

**Comment by j-funk** [comment]
+1 to add this to core.

**Comment by rajjaiswalsaumya** [comment]
+1 to add this to core

**Comment by sgravrock** [comment]
In plain old JS:

```
const cases = [
  [3, 3, 6],
  [10, 4, 14],
  [7, 1, 8]
];

for (const [first, second, sum] of cases) {
  it(`${first} plus ${second} is ${sum}`, function() {
    expect(first+second).toEqual(sum);
  });
}
```

Or if you prefer named rather than positional parameters:

```
const cases = [
  {first: 3, second: 3, sum: 6},
  {first: 10, second: 4, sum: 14},
  {first: 7, second: 1, sum: 8}
];

for (const {first, second, sum} of cases) {
  it(`${first} plus ${second} is ${sum}`, function() {
    expect(first+second).toEqual(sum);
  });
}
```

JS is expressive enough that there's not really anything to be gained by adding a feature like this to Jasmine. Particularly now that the language has features like string interpolation and destructuring.

**Comment by jneuhaus20** [comment]
> JS is expressive enough
Absolutely agree!  They key is that tests are enumerated at run time in jasmine (which is not always the case,) so calling `it` or `describe` in a loop and using string interpolation is 100% valid and works beautifully.

IMO the real crime is that this isn't right up front in the docs, and there's 5 closed issues whose conclusion is "this should be a plugin," so it looks like data-driven testing is not natively supported, when it absolutely is.
