### ISSUE TITLE
 SpyOn getterTypeError: setting a property that has only a getter 

### ISSUE THREAD

**Issue by lovedota** [jasmine/jasmine#901]
Hi friends
i am using es6 with babeljs

*Store.js*
```
var _allPackages = [];

class Store() {
   get allPackages() {
        return _allPackages;
    }
}

export default new Store();
```
*View.js*
```
import Store from './store';

class View() {
   convertPackages() {
       Store.allPackages.forEach() {}
   }
}

export default new Store();
```

In unit test
```
import Store from './store';
import View from './store';

describe('View')
spyOn(Store, 'allPackages').and.returnValue([]);
```

it causes an issue ** TypeError: setting a property that has only a getter**

How can i use sponOn in this case. Thnaks !

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using jasmine! Closing.
