### ISSUE TITLE
RequireJS Shim doesn't seem to be working correctly when loaded into Jasmine

### ISSUE THREAD

**Issue by isuftin** [jasmine/jasmine#903]
https://jsfiddle.net/so2z3gvy/5/

The issue here is that the shim for "olLayerSwitcher" doesn't seem to be working when ran through Jasmine.

This is a distilled implementation of a project I am trying to write using RequireJR and Jasmine. 

The OpenLayers3 library is AMD-capable. I am able to load the library through require and it tests out fine in Jasmine as being defined. However, the olLayerSwitcher OpenLayers3 plugin is not AMD so I am using a shim to load it. It requires that "ol" be a variable that it then updates with functionality.

While this works when loading the application itself in a browser in the same configuration I'm using in this fiddle, it doesn't seem like it works properly using Jasmine. 

The Spec runner here is a hybrid of what the Jasmine-maven plugin creates (my project is a java project and I test on build) and what I was able to cobble together to get Jasmine to load in jsfiddle properly.

So the question here is: Why is it that this works outside of Jasmine? It seems like Jasmine is not allowing RequireJS shimming to work properly.

**Comment by slackersoft** [comment]
Jasmine shouldn't be doing anything to cause RequireJS not to work. We're pretty sure it works in a generic RequireJS context (and definitely in nodejs). It is possible that the `boot.js` file is not being a good citizen and just clobbering any existing `window.onload` that the `olLayerSwitcher` may be installing. But jasmine mostly expects to be loaded in place before anything else is loaded, so this shouldn't really cause problems.
