### ISSUE TITLE
Configuration option pointing to location of jasmine.json

### ISSUE THREAD

**Issue by aleksey-bykov** [jasmine/jasmine#904]
As far as our build process it is inconvenient to depend on the standard location of the jasmine.js file. Global environment variable doesn't work well either because it is global and we have more than one project that needs testing. So can you add an option to specify where jasmine.js is via a command line argument? Thank you.

**Comment by slackersoft** [comment]
Assuming that you're using the [jasmine-npm](https://github.com/jasmine/jasmine-npm) package, you should be able to set the environment variable only for the duration of the command execution. Something like:

````sh
JASMINE_CONFIG_PATH=foo/jasmine.json jasmine
````

**Comment by slackersoft** [comment]
Closing this, as the solution provided should work and we haven't heard anything else.

Thanks for using jasmine!
