### ISSUE TITLE
with my custom reporter,when run first,jasmine can find the files i will test,but when run second,null file found?how can i solve this problem?

### ISSUE THREAD

**Issue by byrhuwei** [jasmine/jasmine#907]
var jasmine = new Jasmine();
                        console.log("aaaaa",jasmine);
                        try {
                            jasmine.loadConfig({
                                "spec_dir": "/opt/app/cafbot.yunos.com/test",
                                "spec_files": [
                                    "**/ui/*.js",
                                    "**/ui/transform/*.js",
                                    "**/animation/*.js",
                                    "**/layout/*.js"
                                ],
                                "helpers": [
                                    "helpers/**/*.js"
                                ]
                            });
                            console.log("bbbbb");
                        } catch (e) {
                            console.log(e);
                        }

                        var myCustomReporter = {
                            jasmineStarted: function(suiteInfo) {
                                passedCount = 0;
                                failedCount = 0;

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using jasmine! Closing.
