### ISSUE TITLE
Create a spy once for all functions of same class

### ISSUE THREAD

**Issue by rstm** [jasmine/jasmine#909]
To create two spies on functions of same class i do this:

    spyOn(mockFooService, 'function1');
    spyOn(mockFooService, 'function2');

Can i do something like this?

     spyOn(mockFooService, [
            'function1',
            'function2'
        ]);

Or maybe create spy on all functions of class like this:

    spyOn(mockFooService)

**Comment by slackersoft** [comment]
Take a look at `createSpyObj` (docs here: `http://jasmine.github.io/edge/introduction.html#section-Spies:_<code>createSpyObj</code>`). This should let you replace the `mockFooService` with an object that has all of its methods as spies. Jasmine does not have a mechanism to make a partial mock of an object spying on multiple methods at once.

**Comment by slackersoft** [comment]
Closing this, since we haven't heard anything else from the community on it.

Thanks for using jasmine!
