### ISSUE TITLE
jasmine.any() should warn on incorrect use

### ISSUE THREAD

**Issue by JDaance** [jasmine/jasmine#910]
Hello, I'm about average stupid and I accidentally did
`expect(spy).toHaveBeenCalledWith(jasmine.any())`

This gives a cryptic error `Cannot read property 'name' of undefined` and then jasmine hides the line numbers and just references the expect line in the test.

Anyway after 30 minutes of debugging I ended up in the code for jasmine.any() and realized it crashes like that if not given an argument. I figured out I should use `jasmine.anything()` but maybe someone else could be spared the headache :) Thanks for a great framework.

**Comment by slackersoft** [comment]
Looks like this is fixed on master with #854, but hasn't been released yet, so I'm going to close this.

Thanks for using jasmine.
