### ISSUE TITLE
Error: "Cannot read property 'appendChild' of undefined" (2.3.4)

### ISSUE THREAD

**Issue by danielalexiuc** [jasmine/jasmine#917]
This happens occasionally (about once every three test runs), and only seems to affect Chrome browser. 

I have traced the problem down to this line in jasmine-html.js (line 114, version 2.3.4):

symbols.appendChild(createDom('li', {

'symbols' is null at this point - it seems like the html report page has not been initialised yet. It seems to happen when there are nested "describes" in my test, and they each have a "beforeEach()", but I'm not sure if this is related.

![jasmine](https://cloud.githubusercontent.com/assets/139083/9594747/77693efc-50a2-11e5-81e6-d21ce60771f7.PNG)

If I let the debugger go, the test output looks like this:

![jasmine2](https://cloud.githubusercontent.com/assets/139083/9594768/d892ec5a-50a2-11e5-80fe-e052f857017b.PNG)

**Comment by CharlieHess** [comment]
+1, also hitting this quite frequently.
