### ISSUE TITLE
Jasmine fails tests when their afterEaches fail

### ISSUE THREAD

**Issue by voltrevo** [jasmine/jasmine#922]
I'm all for jasmine failing the suite when an afterEach fails, and probably even failing the test is appropriate, but no indication is given that the error was really in the afterEach, and this is very confusing.

http://jsfiddle.net/6k7a5v34/2/

Input:
``` javascript
describe('foo', function() {
    afterEach(function() {
        expect(true).toBe(false);
    });
    
    it('bar', function() {
        expect(true).toBe(true);
    });
});
```

Output: Jasmine reports an issue with foo bar
Desired output: Jasmine reports an issue with foo bar's afterEach

**Comment by slackersoft** [comment]
The error should contain information about what line number in your suite the failure was on, which should lead you to the proper expectation. This way jasmine doesn't have to worry about which function in the queue had a failed expectation, but you should still have a pointer to anywhere up the stack of `describe`s that a `beforeEach` or `afterEach` could be coming from.

If you're not seeing the line numbers in the error report, that would be a bug that we need to fix. Also, see #801 for more discussion on cleaning up the trace that is presented to make it easier to find the actual code in your suite that is causing the problem.

**Comment by slackersoft** [comment]
Closing, as this is the desired functionality. If you're seeing issues with the error reporting not properly including stacktrace information, please open a new issue.

Thanks for using jasmine!
