### ISSUE TITLE
jasmineToString

### ISSUE THREAD

**Issue by myitcv** [jasmine/jasmine#928]
I notice [this discussion](https://groups.google.com/forum/#!topic/jasmine-js-dev/Fohd0x0bZEg) in the Google Group forum. 

In particular I agree with André's comment:

> shouldn't their custom toString be preferred over the recursive pretty print?

I have expectations like the following:

```typescript
expect(res).not.toBeDefined();
```

where `res` is expected to be undefined but if this fails then it will be an instance of [`immutable-js` `List`](https://facebook.github.io/immutable-js/docs/#/List). 

Is the expectation here that `immutable-js` should define `jasmineToString()` functions for all their types?

**Comment by myitcv** [comment]
**Method 2** in [this SO answer](http://stackoverflow.com/a/26324116/2097883) provides a cleaner means of overriding this behaviour. Still I would argue falling back to `toString()` is sensible behaviour.

**Comment by slackersoft** [comment]
The `jasmineToString` method was introduced specifically to make overriding existing methods in the pretty printer unnecessary.

I would be happy to review a pull request that allows a custom `toString` to take precedence over just the fallback recursion. I would like it to be pretty sure that it is actually custom and will print something more useful than just `[object Object]` or similar.

**Comment by myitcv** [comment]
@slackersoft just created #929. Thoughts/feedback welcomed there
