### ISSUE TITLE
Email Jasmine test reports.

### ISSUE THREAD

**Issue by udayas8451** [jasmine/jasmine#934]
Hi,

I was wondering if there is a module or a tutorial that would actually send email notifications after the test has been executed. If possible, it would be great to send the exact report as an email.

Please let me know.

Thanks,
Uday

**Comment by slackersoft** [comment]
Jasmine does not have (or really want) a built-in way to send emails of the results of a suite. Sending emails is usually very environment specific and as such, this seems like it would be a good candidate for a custom reporter. There might even be something like this already available in the jasmine custom reporters project.

Closing this.
