### ISSUE TITLE
[Feature Request] Allow an async spec to be marked as pending

### ISSUE THREAD

**Issue by juliemr** [jasmine/jasmine#937]
It would be great to allow an asynchronous spec to be marked as pending, in the same way that it can be marked as failed with `done.fail` e.g.

``` js
it('takes a while but is pending', function(done) {
  setTimeout(function() {
    done.pend();
  }, 100);
}
```

Specifically, this is coming up here: https://github.com/angular/jasminewd/issues/27#issuecomment-144882283.

**Comment by slackersoft** [comment]
This sounds reasonable. We'll have to figure out the right way to pipe all the necessary stuff through to the `QueueRunner`, but I'd be happy to review a pull request that adds this feature.

**Comment by slackersoft** [comment]
If the global `onerror` handler proposed in #529 is hooked up correctly, simply calling `pending` even in async code should properly pend the right spec and move on as it does for synchronous specs.

**Comment by christian-bromann** [comment]
@juliemr check out my commit above for the [wdio-jasmine-framework](https://github.com/webdriverio/wdio-jasmine-framework). I am pretty sure you guys can pull this off in Protractor too.

**Comment by guilhermevrs** [comment]
Hi
I have a specific scenario where, according to other circustances, I have to mark an async it as pending.
I have tried to use the ``pending()``, but unfortunately I get the ``UnhandledPromiseRejectionWarning: Unhandled promise rejection`` with the pending reason ex:

``UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): => marked PendingInvalid mock error: TypeError: Cannot read property 'mocks' of undefined``

@slackersoft I didn't get it how the ``onerror`` will have to be implemented here. Do you have a clear example?

Thanks in advance

**Comment by slackersoft** [comment]
@guilhermevrs I've made a new issue (#1450) for the pending promises. Please take a look there and add anything you think I might have missed.

Thanks for using Jasmine!

**Comment by nitin-kapoor** [comment]
Still facing this issue **"Allow an async spec to be marked as pending"**

Please help!!

Tried below but getting "Property 'pend' does not exist on type **'DoneFn'"**

it('takes a while but is pending', function(done) {
  setTimeout(function() {
    done.pend();
  }, 100);
}

**Comment by slackersoft** [comment]
You should be just calling the existing `pending()` function and passing an optional message.

**Comment by nitin-kapoor** [comment]
I am using pending function like below but its marking as **failed**
Even the spec report treating pending function as failed.

![image](https://user-images.githubusercontent.com/34282001/85224998-b5fa7d00-b3eb-11ea-8374-92eb6eb0b5f3.png)

![image](https://user-images.githubusercontent.com/34282001/85224976-821f5780-b3eb-11ea-8825-4b97afeaf5a1.png)

**Comment by slackersoft** [comment]
That console output doesn't come from Jasmine itself, so this might be an issue with the particular runner/reporter that you're using. You might want to check with Protractor or the Protractor-beautiful-reporter to make sure it handles all of the the status' that Jasmine has for specs
