### ISSUE TITLE
Help spread adoption by providing guides how to integrate with node.

### ISSUE THREAD

**Issue by stefek99** [jasmine/jasmine#938]
The top result for "jasmine node" is https://github.com/mhevery/jasmine-node

Which is more than 1 year old and defaults to 1.x version of Jasmine.

Shall I use https://github.com/jasmine/jasmine-npm then?

Either way - some notes / some clarification would be helpful.

---

In fact I hate making decisions (I hate thinking) and it is easier to use ___ instead.

(not being fussy, just offering some feedback from top of my head)

**Comment by slackersoft** [comment]
Jasmine-npm is the official jasmine team supported release for use of jasmine in a node context. Given that the readme for this repository also lists jasmine-npm, what other kinds of changes would you like to see for clarification?

**Comment by stefek99** [comment]
@slackersoft my suggestion: communicate with owners of the other repo...

![image](https://cloud.githubusercontent.com/assets/249703/10406185/14535dbe-6ed6-11e5-81d5-08de7a0267bc.png)

...and update their readme :)

---

Shouldn't be that hard as @mhevery is probably busy with @angular and stuff.

**Comment by slackersoft** [comment]
The jasmine team doesn't want to be in the business of telling maintainers of other repos that support jasmine to mark their work as deprecated.

As the suggested changes don't seem to be related to any of the jasmine repos, I'm going to close this. Thanks for using jasmine!

**Comment by stefek99** [comment]
> Thanks for using jasmine!

Actually I'm not using Jasmine because of the confusion.

If the top search result for ```jasmine node js``` links to an outdated repo - that's a signal that something is not right.

Minimal effort from the side of maintainers should be enough to provide trusted and reliable info (update the readme, ask them to provide links to the official repo).

*(but I guess that's not my business - back to work)*

PEACE
