### ISSUE TITLE
No way to use a before() statement? Any plugin available?

### ISSUE THREAD

**Issue by bitliner** [jasmine/jasmine#940]
I would need a before() method.

Imagine a login that is done only at the startup.

I found a way to do it, but I would prefer to have a method `before()`.

**Comment by slackersoft** [comment]
Check out the [setup and teardown section](http://jasmine.github.io/edge/introduction.html#section-Setup_and_Teardown) of the docs. Jasmine uses the function `beforeEach` for this.

**Comment by bitliner** [comment]
I know, that is why I am asking for a `before()` method.

**Comment by slackersoft** [comment]
We use `beforeEach` to help clarify the difference between it and `beforeAll`. A function simply named `before` can be easily confused as to when it is intended to run.

If you really can't use `beforeEach`, you can [customize your boot.js](http://jasmine.github.io/edge/custom_boot.html) to alias the existing `beforeEach` to also be `before`.

This isn't functionality we're going to put into the core of jasmine. Closing this issue.

Thanks for using jasmine!

**Comment by bitliner** [comment]
`beforeAll` was what I was looking for, thanks!
