### ISSUE TITLE
Implement spies for get/set functions on accessor properties

### ISSUE THREAD

**Issue by apsillers** [jasmine/jasmine#943]
I think it would be useful to extend `spyOn` (or add another method, like `spyOnGetter`) to spy on the getter or setter function of an accessor property. Currently there is no way to spy on the following `get` functions, because Jasmine currently can only spy on functions that are properties, and not on functions that are `set`/`get` accessor functions of a property:

```
Object.defineProperty(obj, "dynamicFoo", {
    configurable: true,
    get: function() {
        return Math.random();
    }
});

var obj = {
    get dyanmicBar() { return Math.random(); }
}
```

It seems like the core functionality could be implemented using `defineProperty` to rewrite the property with a spy for its `get` or `set` method.

The current code is

```
this.spyOn = function(obj, methodName) {
    ...
    var spy = j$.createSpy(methodName, obj[methodName]);
    obj[methodName] = spy;
}
```

The code could handle accessor functions with a third argument (either `"get"` or `"set"`) like so:

```
this.spyOn = function(obj, methodName, accessType) {
    ...
    var desc = Object.getPropertyDescriptor(obj, methodName);
    if(desc[accessType]) { // "get" or "set" exists on the property
        var spy = j$.createSpy(methodName, desc[accessType]);  

        desc[accessType] = spy;

        Object.defineProperty(obj, methodName, desc);
    }
}
```

However, I'm not sure how this would break existing assumptions. For example, in my sample code above, `createSpy` is given the _property name_, but the property is not being spied on; rather, one of the property's accessor functions is being spied on. This change would require eliminating the assumption that a function being spied on is a property of an object, and instead writing logic that admits the possibility that a spied function could be a `get` or `set` function within an object property.

**Comment by StanleyGoldman** [comment]
+1

**Comment by slackersoft** [comment]
I can see that being useful. I don't think we want to add that complexity to the existing `spyOn` implementation, but I would be happy to review a pull request to add something like `spyOnProperty` or something.

**Comment by mgilliganrca** [comment]
+1

**Comment by isadovskiy** [comment]
+1

**Comment by jamesbrobb** [comment]
+1

**Comment by apaatsio** [comment]
+1

**Comment by mharris7190** [comment]
+1

**Comment by cervenyprofiq** [comment]
+1

**Comment by salickc** [comment]
+1

**Comment by yhari** [comment]
+1

**Comment by nicbou** [comment]
+1

**Comment by Anjmao** [comment]
+1

**Comment by FunkeyFlo** [comment]
+1

**Comment by benediktarnold** [comment]
+1

**Comment by chrisatanasian** [comment]
+1

**Comment by ptomato** [comment]
I think at this point the +1s are crowding out any actual discussion that might happen here; please show your enthusiasm by subscribing yourself to the issue or adding a :+1: reaction with GitHub's new "reaction" feature so that everybody doesn't continue to get notifications for each new +1.

Or, better yet, attach a pull request :smile:

**Comment by henrahmagix** [comment]
@ptomato #1008 is a pull-request that fulfills this issue, already attached

**Comment by Gigitsu** [comment]
+1

**Comment by henrahmagix** [comment]
@slackersoft We now have #1008 and #1203 able to be merged. Is there a timeline for this feature?

**Comment by elwynelwyn** [comment]
Any guidance on when this will make it into a release?

**Comment by joshfermin** [comment]
+1

**Comment by fimius23** [comment]
+1

**Comment by henrahmagix** [comment]
@elwynelwyn @joshfermin @fimius23 I know this is late so you may know already, but this is available in 2.6 (https://github.com/jasmine/jasmine/pull/1203#issuecomment-300644219) with docs at https://jasmine.github.io/api/edge/global.html#spyOnProperty

**Comment by pauljeffreys** [comment]
I realise I am late to the game here, but does anybody know of a similar function call for jest? Wanting to test a getter in that also, but this addition is just jasmine..

**Comment by slackersoft** [comment]
@pauljeffreys you should probable ask the Jest folks. (https://github.com/facebook/jest) I'm not totally sure it's even still built on top of Jasmine in a way that would allow them to incorporate the work done here.

**Comment by phra** [comment]
@pauljeffreys @slackersoft see my PR at https://github.com/facebook/jest/pull/5107
