### ISSUE TITLE
Spying on a function that is defined using a getter causes PhantomJS to crash

### ISSUE THREAD

**Issue by StephanBijzitter** [jasmine/jasmine#948]
`TypeError: setting a property that has only a getter`.

Now you might think that this is an issue for PhantomJS to resolve, but it is not. Your own tests run on Node, which in this case has the same issue but fails silently instead.

In the end, it means that you cannot spy on a function or constant that has been declared using only a getter. Depending on the environment, it either fails silently (possibly providing false test results) or fails by hanging the process.

**Comment by amilligan** [comment]
This is no doubt the correct behavior for Jasmine spies.  However, it breaks tests that are currently functioning properly.  

PhantomJS will return `{ writable: false, enumerable: false, configurable: false }` for properties like window.history.pushState, and yet spying on that function would still work.  In fact, just overwriting that property works just fine in PhantomJS; again, no doubt an incorrect behavior in PhantomJS, but one that some indeterminate number of spec suites probably depends on.

Jasmine should make this change, but a deprecation warning, or a major version change, would be appropriate.
