### ISSUE TITLE
Specifications generator

### ISSUE THREAD

**Issue by sveinburne** [jasmine/jasmine#950]
Hi! I'm new to jasmine and I love it! 
Was wondering if it was possible to generate some auto-generated markdown (or any format) specifications? Each `describe` block would be a new dummy entry like : 

```markdown
## Some instance .

- shall handle some specific case ...
- shall handle some generic case ...
- shall throw an error when ...
```

Thanks for your help!

**Comment by slackersoft** [comment]
This sounds like a [custom reporter](http://jasmine.github.io/edge/custom_reporter.html). There are also some existing custom reporters out there (the jasmine-reporters project for example) that may have something like this already built.

In the future you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself. I'm going to close this.

Thanks for using jasmine
