### ISSUE TITLE
--watch option for fast iteration during TDD?

### ISSUE THREAD

**Issue by thom-nic** [jasmine/jasmine#952]
First, apologies if this has been asked before but a search for 'watch' in github and google don't turn up anything relevant.

Mocha has a `--watch` mode that re-runs tests when something changes.  Karma also does something similar, in fact Karma's default mode is to stay in a watch mode unless you specify 'single run.'  This makes TDD easy as you can write your tests first, see them fail, then as you save code tests start passing.

I can approximate this functionality with [chokidar](https://github.com/paulmillr/chokidar) and gulp/grunt, but was surprised this doesn't seem to be built-in.

**Comment by slackersoft** [comment]
I think you're probably looking for jasmine/jasmine-npm#5. This repository doesn't contain any code to run the suite in a way that would be watchable.

Closing this as a duplicate. Thanks for using jasmine!

**Comment by thom-nic** [comment]
Ah, gotcha.  Thanks!
