### ISSUE TITLE
Testing the property of an undefined object

### ISSUE THREAD

**Issue by Tetraib** [jasmine/jasmine#959]
In the process of testing a REST API with the following code :
 
    describe('GET /', function() {
        it('should respond with 200', function(done) {
            request(options, function(error, response, body) {
                expect(response.statusCode).toBe(200);
                done();
             });
         });
    });

If the webservice is down, or the requested address is wrong, the response is not defined, all tests are skipped and jasmine fail with :
  TypeError: Cannot read property 'statusCode' of undefined

If this situation I would expect jasmine to just report :
  Expected undefined to be 200.
Is jasmine failing this way by design ? And then how can I best prevent jasmine to completely fails in this situation ?
Or
Shouldn't jasmine just report "expected undefined <some matcher> something" in case we are reading the property of an undefined object ?

**Comment by slackersoft** [comment]
It's actually the underlying javascript interpreter that is throwing that error and not jasmine itself. If just the `statusCode` was `undefined` you would get the error you want. You could also do a precursor check, something like:

```javascript
expect(response).not.toBeUndefined();
```

There isn't much jasmine can do by itself in this situation, so I'm going to close this. Thanks for using jasmine!

**Comment by Tetraib** [comment]
Yes I was doing the precursor check, but It doesn't help because it is not even showed on the console if I test for

    expect(response.statusCode).toBe(200);
in the same spec.

May be I can go for a custom matcher that tests the existence of the object before testing it's property ?
