### ISSUE TITLE
Feature to retry failed tests

### ISSUE THREAD

**Issue by hankduan** [jasmine/jasmine#960]
Is there the possibility for Jasmine to add an option to retry failed tests to de-flake?

i.e. if my test suite has 3 tests: A, B and C.
If B failed, but A and C passed, Jasmine will rerun B to see if it passes (it will retry only the failed tests up to a specified number of times). 

This would help with Protractor tremendously. (i.e. https://github.com/angular/protractor/issues/1190). I would be willing to create a PR for this if owners think this feature fit within jasmine.

**Comment by joao10falcao** [comment]
+1

**Comment by slackersoft** [comment]
I think this is functionality we'd like to keep out of jasmine itself. I _think_ you should be able to build something that can do this with the existing [custom reporter](http://jasmine.github.io/edge/custom_reporter.html) and `filter` function. If this isn't possible, I'd be happy to review an issue or pull request about what makes it hard.

**Comment by juliemr** [comment]
There's been a *lot* of requests for this from Protractor users, so I think it's worth at least putting together an initial design to see if it could be done outside of the Jasmine project itself, as a custom reporter. I imagine other users may find it helpful as well. @hankduan can you do a quick prototype?

**Comment by bruindav** [comment]
+1000

**Comment by willgm** [comment]
+1

**Comment by vishal-modi** [comment]
+1

**Comment by premkh9** [comment]
That will be very helpful

**Comment by d3ming** [comment]
👍

**Comment by sul4bh** [comment]
This would surely be very useful. @juliemr @hankduan do you guys have any update on this?

**Comment by slackersoft** [comment]
It sounds like the primary use case for this feature (Protractor) has been solved with the [protractor-flake](https://www.npmjs.com/package/protractor-flake) library. I'm going to close this issue in favor of that solution for now. I would be happy to review a pull request or discuss enhancements to Jasmine that would make this kind of thing easier to put together for Jasmine.

Thanks for using Jasmine!

**Comment by wmhilton** [comment]
Hi, I have no idea what Protractor is - I'm using Jasmine on SauceLabs on Karma on Travis-CI to run tests on a bunch of different browsers, and the tests are just flaky enough that my Travis-CI build almost never passes on the first try. Having a retry function built into Jasmine would be ideal because it is the lowest level of granularity. Rerunning one test (out of a thousand) would be the fastest and most reliable, since it doesn't run the risk of a test that previously passed now failing. Having a Karma plugin to re-run Jasmine is the next level of granularity, followed by re-running Karma, followed by re-running Travis. I've been re-running Travis, and am about to try using `travis_retry` to rerun Karma, but that is still less likely to succeed than rerunning the individual Jasmine tests.

Looking at the custom reporter spec, I don't see how it could be used to re-run a failed spec. I'd need to remove the failed test and append a new test, or somehow "wrap" each test in a retrying function before the test executes. Could someone explain how I could implement such a reporter?

**Comment by slackersoft** [comment]
The custom reporter isn't the full solution, but the part that allows recording of which specs failed for a later retry. You should be able to take that info and input it into a second execution of Jasmine to just run those specs that failed. I'm not sure what all Karma will let you do with to pass all of that through, and how the reporter would work there either.

Hope this helps. Thanks for using Jasmine!

**Comment by wmhilton** [comment]
Ah! That makes sense now. I'll see what I can figure out.

**Comment by kevinlbatchelor** [comment]
+1

**Comment by joeyparrish** [comment]
If anyone comes here still looking for a standalone option to retry tests in Jasmine, here is a shim that seems to be working for me: https://gist.github.com/joeyparrish/c8b020a33095ea7cf191c06f4339a4dc

**Comment by ScottLNorvell** [comment]
@joeyparrish thanks for posting the gist! I was able to get it working with a few tweaks. (I think we are on an older version of jasmine 😄)

**Comment by milesstewart88** [comment]
@joeyparrish @ScottLNorvell Hey guys, would you be kind enough to give me a pointer on how I could use this. Much appreciated

**Comment by joeyparrish** [comment]
@milesstewart88, copy this function into a file that loads after jasmine itself: https://gist.github.com/joeyparrish/c8b020a33095ea7cf191c06f4339a4dc

Then call it at load-time, e.g.:

```js
retryFailedTests(3 /* retries */, 1000 /* millisecondsBetweenRetries */, window.setTimeout);
```

**Comment by milesstewart88** [comment]
That is great, I appreciate it.  Thank you

**Comment by arjun1607** [comment]
@joeyparrish where should i use this retryFailedTests function? in test.ts file or karma.conf.js
I new to angular please tell me.

**Comment by joeyparrish** [comment]
In karma.conf.js, you can set the specific files that are loaded and their order.  They will be loaded and executed in that order.

Make sure you load the gist above after Jasmine (either loaded explicitly or by a plugin).  In that file, add a call to retryFailedTests().  After that, load the actual tests.  Then any calls to jasmine.Spec made by defining tests will get the shimmed version that does retries.

Does this help?

**Comment by joeyparrish** [comment]
I posted that gist 3 years ago and haven't exactly maintained it.  Feel free to tinker and modify it, though.  I came up with a lot of those details by spelunking in jasmine source, so there is probably a way to do what you want if you are willing to dig.

Sorry I don't have a good answer for you!
