### ISSUE TITLE
Cannot call createSpyObj with only name, not list of methods

### ISSUE THREAD

**Issue by danfinnie** [jasmine/jasmine#961]
jasmine.createSpyObj throws if you don't pass it any method names: https://github.com/jasmine/jasmine/blob/375a6f9fda57fdd896acce9abba7aca2e02b310a/src/core/base.js#L113

Why was this behavior added? My use case is that I'd like to ensure that a specific parameter was passed through to another function.  For instance:

```js
function iCallThings(a, b) {
  a(b);
}

a = jasmine.createSpy('a');
b = jasmine.createSpyObj('b', []);

iCallThings(a, b);
expect(a).toHaveBeenCalledWith(b);
```

AFAIK, this test would work if it weren't for Jasmine checking the length of the array passed as the second argument to `createSpyObj`.  A solution right now is to do something like `b = {'b': true}`, but I'd prefer to use createSpyObj.  I'm fine with having to pass an empty array but I'd like to not have to pass a non-empty array.

I can send out a PR for this if you agree that it'd be a positive change.

**Comment by slackersoft** [comment]
We're throwing an error in this case under the assumption that you've probably mistakenly called `createSpyObj`. The line you have

```javascript
b = jasmine.createSpyObj('b', []);
```

ends up being exactly equivalent to:

```javascript
b = {};
```

because if you don't pass in any method names, no spies are actually created on the object. Given this, this isn't functionality we're likely to change.

**Comment by danfinnie** [comment]
Hmmm that does seem to be the case.

I was hoping that by creating spy objects I would get more descriptive error messages based on their names.  For instance, "Expected spy a to have been called with [ spy object 'b' ] but actual calls were [ spy object 'c' ]".  This doesn't seem to be the case though, the name you pass into jasmine.createSpyObj is just used to name the spies it creates.  This functionality exists for normal spies but not spy objects, is there a reason for that?

**Comment by slackersoft** [comment]
A spy object is just an object with a bunch of spies on it, the intention is to make it easier to inject a collaborator object in and see which functions get called on it.

The functionality you're looking for can be accomplished very easily with plain javascript (`var b = {"object": "b"};` or `var b = "object b";`), so this isn't something we're looking to change in jasmine itself.

Thanks for using jasmine! Closing.

**Comment by gestj** [comment]
If you want to create an empty spy/mock in typescript for testing:

`let x: T = <T>{};`

_(just ran into this by myself)_

**Comment by Enteee** [comment]
Thank you, @gestj: In your solution you still need to do a bit of import management to get the type `T` in your tests. What I sometimes use use, if I don't even care about the type is:

`let x = {} as any`

sledgehammer style :smile:
