### ISSUE TITLE
Is jasmine really BDD?

### ISSUE THREAD

**Issue by inf3rno** [jasmine/jasmine#962]
> Jasmine is a Behavior Driven Development testing framework for JavaScript.

Is this really true? 

As far as I know BDD means the usage of a feature description language, for example [gherkin](https://github.com/cucumber/gherkin3) which we can use to describe features in a human readable form. These descriptions have very high abstraction level, use words from ubiquitous language (DDD), for example:

```cucumber
Scenario: Wilson posts to his own blog
  Given I am logged in as Wilson
  When I try to post to "Expensive Therapy"
  Then I should see "Your article was published."
```
As you can see they don't contain any (javascript) code, so the implementation is independent from the feature description. You can do it on any programming language using any programming style.
By running the tests we translate the feature descriptions into running tests by the usage of step definitions. These step definitions are reusable and contain low level code like fixtures, assertions, etc. and they are reusable. So I can say that 
```cucumber
Scenario: Gabriel tries to post to Wilson's blog
  Given I am logged in as Gabriel
  When I try to post to "Expensive Therapy"
  Then I should see "You don't have the permissions to post here"
```
And I can reuse the step definition of the `When I try to post to "Expensive Therapy"` part. 

A clean separation of these 2 abstraction levels is important not just because the reusability, but because the human readability and the ensurance of  loose coupling between the feature descriptions and the code. So we don't have to touch the feature descriptions if only the implementations changes, but the supported features remain the same.

Ofc. jasmine could be used for writing these step definitions, just as any unit testing framework.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using jasmine!

**Comment by inf3rno** [comment]
@slackersoft I think this is a documentation bug. I should have put ?! to the end of the title.

**Comment by slackersoft** [comment]
BDD is a way to approach testing, not a tool that you use. The question of whether the format of the tests you are writing is or is not BDD is off topic for github issues.

**Comment by inf3rno** [comment]
@slackersoft Can you add some references about why jasmine is BDD? I haven't found anything here: https://en.wikipedia.org/wiki/Behavior-driven_development or any BDD related video and article I checked, and I checked a lot in the past year.
