### ISSUE TITLE
Jasmine cannot work in Atom Electron environment

### ISSUE THREAD

**Issue by skupr** [jasmine/jasmine#964]
When I try to run Jasmine under Electron, it fails with error:
*jasmine.js:28 Uncaught ReferenceError: exports is not defined*
Looking at source code, I can suppose that the problem is in mixed node.js/browser environment.

**How to reproduce:**
```bash
set -e
git clone https://github.com/atom/electron-quick-start
cd electron-quick-start
wget https://github.com/jasmine/jasmine/releases/download/v2.3.4/jasmine-standalone-2.3.4.zip
unzip jasmine-standalone-2.3.4.zip
cp SpecRunner.html index.html
npm install
npm start
```
And then look at developer console by pressing Ctrl-Shift-I

**Comment by slackersoft** [comment]
Yeah, it looks like we've got some bad assumptions/bugs in a couple places that are causing issues.

I would be happy to review a pull request that fixes this issue.

**Comment by denisgursky** [comment]
@slackersoft , Is it possible publish a new version to npm with this fix?

**Comment by slackersoft** [comment]
New version 2.5.x is released and should have the fix for this in it.
