### ISSUE TITLE
Add dddescribe, iiit for suites, specs that should always run

### ISSUE THREAD

**Issue by F1LT3R** [jasmine/jasmine#966]
While I am isolating a test using `ddescribe` in `scenario-change-username.js` I also have to use it in `scenario-login.js` so that the user is logged in.

It would be nice to use something like `dddescribe` in the login file, (for want of better nomenclature).

``dddescribe` would be immutable, and this case, the login test would always run, even when other `ddescribes` are used.

**Comment by slackersoft** [comment]
Any given test in your suite shouldn't have dependencies on other tests. If you need common setup, jasmine provides `beforeEach` and `beforeAll` for this purpose.

This isn't a feature we want to have in jasmine itself.

Thanks for using jasmine! Closing.
