### ISSUE TITLE
Way to export spec tree?

### ISSUE THREAD

**Issue by gavD** [jasmine/jasmine#967]
Hi,

I would like to export a tree of the Jasmine specs, is this possible?

When I use `karma-spec-reporter` I can output the specs as they run, making a tree like:

```
MyModule
  someFunction()
    when foo == bar
      returns 'true'
    when foo == baz
      returns 'false'
```

This is really useful and I would like to use this information to describe my modules outside of running the tests. Is there any way I can simply parse the specs in Jasmine and somehow get at that information? I assume that Jasmine creates some kind of tree somewhere of what it has to run.

Thanks,
- Gavin

**Comment by slackersoft** [comment]
You should be able to write your own [custom reporter](http://jasmine.github.io/edge/custom_reporter.html) to accomplish this as part of your test run. Outside of this, jasmine doesn't provide any way to get your spec tree. You could probably also write a runner that defined `describe` and `it` and built up a tree as they were called.

This isn't a feature we're looking to have in jasmine itself, so I'm going to close this. Thanks for using jasmine!

**Comment by gavD** [comment]
Thanks, that's great :-)
