### ISSUE TITLE
Feature: mock timezone in fake clock

### ISSUE THREAD

**Issue by lukeapage** [jasmine/jasmine#969]
It would be useful to be able to mock the timezone in the mock clock in a similiar way to https://github.com/Jimbly/timezone-mock or https://github.com/plaa/TimeShift-js

We already use the jasmine clock everywhere and now we will have one test that is using a different mocking framework so we can mock timezones.

**Comment by slackersoft** [comment]
That sounds like an interesting feature. I would be happy to review a pull request that implements this.

**Comment by mkprajeen** [comment]
I am looking for this feature. It will be very use full feature. 
-Prajeen

**Comment by renaldas-kerpe-arria** [comment]
+1

**Comment by imben1109** [comment]
@lukeapage do you have any idea if i want to use in angular test?

**Comment by sgravrock** [comment]
I'm closing this due to prolonged inactivity, but anyone who wants the proposed change enough to implement it should still feel free to submit a PR.
