### ISSUE TITLE
Is there a possibility in jasmine not to override messages from passed expects?

### ISSUE THREAD

**Issue by lynchblue** [jasmine/jasmine#971]
I am using in my project protractor for my e2e tests with jasmine2 as framework. I am using as well the libraries [jasmine2-custom-message](https://github.com/avrelian/jasmine2-custom-message) and [protractor-jasmine2-html-reporter](https://github.com/Kenzitron/protractor-jasmine2-html-reporter). 

I have realised that the message from passed expects would be overridden with the word: Passed.

After a little research I realised that the file that is actually overridden this message is the following:
node_modules/protractor/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js

Specifically the function:
```javascript
getJasmineRequireObj().buildExpectationResult = function () {
    function buildExpectationResult(options) {
        var messageFormatter = options.messageFormatter || function () {
                },
            stackFormatter = options.stackFormatter || function () {
                };

        var result = {
            matcherName: options.matcherName,
            message: message(),
            stack: stack(),
            passed: options.passed
        };

        if (!result.passed) {
            result.expected = options.expected;
            result.actual = options.actual;
        }

        return result;

        function message() {
            if (options.passed) {
                return 'Passed.';
            } else if (options.message) {
                return options.message;
            } else if (options.error) {
                return messageFormatter(options.error);
            }
            return '';
        }

        function stack() {
            if (options.passed) {
                return '';
            }

            var error = options.error;
            if (!error) {
                try {
                    throw new Error(message());
                } catch (e) {
                    error = e;
                }
            }
            return stackFormatter(error);
        }
    }

    return buildExpectationResult;
};
```

I wonder if there is a way to override this function (buildExpectationResult), for example in protractor config file. I have already tried that by adding in protractor config file the following.
```javascript
onPrepare: function () {
    jasmine.buildExpectationResult = function () {
        function buildExpectationResult(options) {
            var messageFormatter = options.messageFormatter || function () {
                    },
                stackFormatter = options.stackFormatter || function () {
                    };

            return {
                matcherName: options.matcherName,
                expected: options.expected,
                actual: options.actual,
                message: message(),
                stack: stack(),
                passed: options.passed
            };

            function message() {
                if (options.passed && !options.message) {
                    return 'Passed.';
                } else if (options.message) {
                    return options.message;
                } else if (options.error) {
                    return messageFormatter(options.error);
                }
                return "";
            }

            function stack() {
                if (options.passed) {
                    return "";
                }

                var error = options.error;
                if (!error) {
                    try {
                        throw new Error(message());
                    } catch (e) {
                        error = e;
                    }
                }
                return stackFormatter(error);
            }
        }

        return buildExpectationResult;
    };
}
````
But that is not working. 

Is there any other way of overriding jasmine functions?

**Comment by lynchblue** [comment]
I have created a pull request modifying the logic of populating expectation messages. What I do it's very simple, if the expectation has a message we populate this message regardless of the expectation failed or passed. 

I find it very useful for using it in reports in combination with meaningful expectation messages provided for example by [jasmine2-custom-message](https://github.com/avrelian/jasmine2-custom-message) .

The pull request can be found in the following link:
https://github.com/jasmine/jasmine/pull/972

**Comment by slackersoft** [comment]
A matcher doesn't know whether or not it has been called in conjunction with `.not`, so it always needs to provide a failure message. The message will assume that the current state is in correct, because that is when messages are shown to the user. If we were to change this behavior the message for:

```javascript
expect(1).toEqual(1);
```

would be: "Expected 1 not to equal 1" which is not what is actually in the expectation. In order to reduce confusion, the message is changed to "Passed".

This is not functionality we'd really be interested in changing, as the use case for showing passing expectations seems dubious at best.

Thanks for using jasmine! Closing.
