### ISSUE TITLE
Add command line option to run only a subset of the tests

### ISSUE THREAD

**Issue by ggarber** [jasmine/jasmine#974]
It could be useful to have options to filter the tests to be run.  Something like these flags supported by mocha:

 -g, --grep <pattern>                    only run tests matching <pattern>
 -f, --fgrep <string>                    only run tests containing <string>

**Comment by slackersoft** [comment]
Are you using [node](https://github.com/jasmine/jasmine-npm), [ruby](https://github.com/jasmine/jasmine-gem), [python](https://github.com/jasmine/jasmine-py), or something else to run the tests? The core of jasmine doesn't provide a command line interface, so this issue probably belongs in a different repo.

That said, jasmine-npm does provide a `--filter=` option for specifying which tests to run.

Thanks for using jasmine! Closing.
