### ISSUE TITLE
Fail a test if no expectations were made

### ISSUE THREAD

**Issue by alecxe** [jasmine/jasmine#977]
Is there anything built-in to jasmine to fail a test if no expectations were made in it?

If not, would it make sense to request such a feature? Thanks.

**Comment by slackersoft** [comment]
Jasmine does not have a way to fail a given test if no expectations are made during its run. The number of expectations (passed and failed) are [sent to reporters](http://jasmine.github.io/edge/custom_reporter.html#section-specDone) for use in reporting.

This isn't something we're looking to have as there are legitimate reasons why a spec without expectations might be desired.

Thanks for using jasmine! Closing.

**Comment by foklepoint** [comment]
Just curious @slackersoft, under what scenario would it make sense for a test without any expectations to be pass, be useful? Also maybe instead of failing, maybe it makes more sense to emit a warning?
