### ISSUE TITLE
Passing parameters from Spec to Reporter

### ISSUE THREAD

**Issue by paranoid-android** [jasmine/jasmine#978]
Hello,

I've been working on a custom reporter that I use from Node. I need the reporter to display more details than are returned in the `specResult` object from a spec. For example, my spec looks like this:

**spec**
```
it("should return parameter values", function(done) {
    expect(true).toBe(true);
    this.parameter2 = 'anotherValue';
    done();
}, { parameter1:'paramValue' });
```

**reporter**
```
this.specDone = function(result) {
  var parameter1 = null; // how do I get result.parameter1
  var parameter2 = null; // how do I get result.parameter2

  ...
}
```

I cannot figure out how to pass additional information from a spec to a reporter. In addition to the properties that are currently returned with `result` (i.e. `description`, `fullName`, `passedExpectations`, `failedExpectations`, and `status`), I'd like add two other properties: `properties` and `result`. I'm not having any luck in accomplishing this though.

Thank you to the community for any assistance that can be provided. I personally have the opinion that this would be a valuable addition to the Jasmine in general.

**Comment by slackersoft** [comment]
There is no way to pass arbitrary meta data from a spec to reporters. This doesn't sound like something that we're looking to add to the core of jasmine either, so I'm going to close this. Thanks for using jasmine!
