### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by adambuczynski** [jasmine/jasmine#979]
The documentation example specifies an onComplete callback, however, when you do that and run the tests, jasmine complains that it's been deprecated. Docs should probably be updated to reflect new API?

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing. Thanks for using jasmine!
