### ISSUE TITLE
Documentation should reflect that toContain can do substring matching

### ISSUE THREAD

**Issue by ryanwilsonperkin** [jasmine/jasmine#981]
The [documentation](http://jasmine.github.io/2.0/introduction.html) for Jasmine states
> The 'toContain' matcher is for finding an item in an Array

In practice it also works for matching substrings. (ie. `expect('qwerty').toContain('we')`) as mentioned by @slackersoft in #738 . If this is an intended feature, I would recommend that it be included in the documentation. Alternatively, if it's not intended and may go away in a future release I would recommend adding a caveat to the docs reflecting that.

Let me know which way the collaborators lean on this and I'd be happy to submit a PR.

**Comment by slackersoft** [comment]
According to [the specs for contains](https://github.com/jasmine/jasmine/blob/master/spec/core/matchers/matchersUtilSpec.js#L312) substring matching is expected to work.

I would be happy to review a pull request over at the [jasmine documentation github repository](https://github.com/jasmine/jasmine.github.io).

I'm going to close this issue as it relates to the documentation and not jasmine itself. Thanks for using jasmine!

**Comment by ryanwilsonperkin** [comment]
@slackersoft after finding an old email pointing to this thread, I finally got around to adding this support.
