### ISSUE TITLE
Link "this list" does not work on wiki

### ISSUE THREAD

**Issue by Ziemowit** [jasmine/jasmine#982]
On site:

https://github.com/jasmine/jasmine/wiki/A-simple-project

link does not work.
404 error is returned.

**Comment by Ziemowit** [comment]
Linkt "downloads page". also does not work on this site => http://pivotal.github.io/jasmine/#section-Downloads

**Comment by slackersoft** [comment]
Thanks for the head up. I've update the download links I could find in the wiki. The wiki is deprecated and falling out of date, so I wouldn't rely on it too heavily.
