### ISSUE TITLE
Call Done twice? Docs on async inconclusive

### ISSUE THREAD

**Issue by uncleoptimus** [jasmine/jasmine#988]
Hi all! 
Udacity front-end program student here and a bunch of us have been confused by the role of the *done* function.
Specifically, say we use *done* in a *beforeEach*. If the accompanying *it* block doesn't have any async action, do we still need to call it within that *it* block for a spec to be considered complete? 

Several of us have noticed a spec still works if we don't pass in the *done* function (in the case that *it* block has no async).

However the documentation language and example seems to indicate that we **do** need to call *done* twice in this circumstance. [link](http://jasmine.github.io/2.4/introduction.html#section-Asynchronous_Support)

**Comment by slackersoft** [comment]
The `done` function is used to make a specific function (`beforeEach`, `afterEach`, `it`, `beforeAll`, `afterAll`) in your suite complete asynchronously. The purpose of this is to keep the knowledge of the async logic contained in that function, so others can execute synchronously as usual. So even if a `beforeEach` receives a `done` callback, an `it` in the same context should only need to if it is async as well.

The documentation is specifically trying to show an example of each type of function being async to show the possibilities. The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing this. Thanks for using jasmine!

**Comment by uncleoptimus** [comment]
Thank you @slackersoft , thats super clear!
