### ISSUE TITLE
How to setup a basic Javascript test using Jasmine 2.4.1 (standalone)?

### ISSUE THREAD

**Issue by adrian-moisa** [jasmine/jasmine#989]
This is the first time I'm trying to write tests. I have installed jasmine 2.4.1 inside my project using bower:

`bower install jasmine --save`

![2015-12-09_203216](https://cloud.githubusercontent.com/assets/11160141/11698674/936cbc36-9ec8-11e5-9c74-5ee0434baf70.png)

I just can't figure out what to do next in order to setup `specRunner.html`. All the tutorials I found online are focused on previous versions of jasmine, which seem to have the `specRunner.html` file and a slightly different package structure. The install instructions I found on github are outdated, dating back to version 2.0.0. Also no luck on finding useful info on the github page. Sorry for posting such a basic question, but I just can't find a clear answer after so many hours of searching.

What am I suposed to do next to get the most basic of tests running?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using jasmine!

**Comment by adrian-moisa** [comment]
Finally found the solution (hooray, six hours lost). I was supposed to change `jasmine-2.0.0` to `jasmine-core`. Ok, no problem with that, but at least this could have been mentioned inside README.md somewhere. Not to say that there's no clue where to put the specs scripts and sources. It may be obvious for anyone who used jasmine previously, but not to a newcomer. You know, usually when you open a library, the documentation has clear cut steps on how to proceed.

	<!doctype html>
	<html>
		<head>
			<title>Jasmine Spec Runner</title>
			<link rel="stylesheet" href="../libs/jasmine/lib/jasmine-core/jasmine.css">
		</head>
		<body>
			<script src="../libs/jasmine/lib/jasmine-core/jasmine.js"></script>
			<script src="../libs/jasmine/lib/jasmine-core/jasmine-html.js"></script>
			<script src="../libs/jasmine/lib/jasmine-core/boot.js"></script>
	 
			
			<script src="src.js"></script>
	 
			
			<script src="test.js"></script>
		</body>
	</html>
