### ISSUE TITLE
Jasmine spies do not preserve function arity

### ISSUE THREAD

**Issue by glebec** [jasmine/jasmine#991]
Whether using `spyOn` to replace an object property whose value is a function, or using `.and.callFake` to delegate to a supplied function, the resulting spy always has arity (`.length`) of zero — even if the original function has arity of 1, 4, whatever.

This is irrelevant much of the time but becomes critical when testing libraries that check function arity. Two well-known examples:

* libraries which check to see if a `done` param is defined, in order to determine whether to execute asynchronously. Jasmine itself does this, ironically.
* libraries like Express which register "error-handling middleware" as being functions with arity 4 (as opposed to the usual 3 or less), and which execute those functions if a truthy value has been passed into a previously-supplied `next` function (or if an error was thrown during the execution of "normal" middleware).

The best spies which substitute for existing functions do so transparently, so that the library is not able to determine the difference between a spy and an original. Jasmine spies would be improved by matching the arity of their originals, reducing the possibility of the framework being tested exhibiting different behavior.

**Comment by slackersoft** [comment]
I'm not sure how to create a function with a dynamic arity, but I would be happy to review a pull request that creates a spy with the arity of the original function passed in.

**Comment by kapke** [comment]
Creating a function with desired arity is possible in two ways:
  - use `Function` constructor which takes array of argument names and function body in string (generic but using function constructor is more or less like call to `eval`)
  - in ES6 `length` property is configurable so it is possible in modern browsers and newer versions of node.js to use `Object.defineProperty` (checked on Firefox, Chrome, Edge and node.js 5.5, sadly IE 11 doesn't support that)

I have an idea for solution. Probably I will open a pull request in few days.
