### ISSUE TITLE
new warnings in bluebird 3.0 and jasmine

### ISSUE THREAD

**Issue by marneborn** [jasmine/jasmine#992]
First, this isn't really jasmine's fault, so I understand if you don't think it should be fixed here.
This does seem to be the simplest place to fix it, and bluebird promises are popular...
I can make a pull request for it, but don't want to go through the effort if it's likely to be rejected.

Bluebird has, in 3.0, added a warning flagging cases where a promise is created in a promise handler, but none is returned.
There's a more detailed explanation [here](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it) .

This warning is triggered whenever promises are handled like this:
```javascript
it("should check the promises result", function (done) {
    returnsAPromise()
    .then(function (res) {
        expect(res).toBe(expectedResult);
    })
    .then(done, done.fail);
});
```

The warning is easy to turn off, but I like the intent behind it so would like to keep it enabled.
But that means that I need to wrap done and done.fail in a function that returns null everywhere instead of ```.then(done, done.fail)```

```javascript
.then(function () {
    done();
    return null;
}, function (err) {
    done.fail(err);
    return null;
})
```

Alternatively, change jasmine so that the done and done.fail functions created in the QueueRunner always return null.

```javascript
  function once(fn) {
    var called = false;
    return function() {
      if (!called) {
        called = true;
        fn();
      }
      return null;
    };
  }
```

```javascript
      next.fail = function() {
        self.fail.apply(null, arguments);
        return next();
      };
```

**Comment by duzun** [comment]
Isn't it better (and easy) to add support for Promises to Jasmine?
I found this library that works great: https://github.com/matthewjh/jasmine-promises
But I don't see any reason for not supoorting Promises dirrectly by Jasmine.

**Comment by slackersoft** [comment]
My inclination is that `done` and `done.fail` are intended to not have a return value, so explicitly returning `null` feels weird. However, since one of the primary use cases for `done` is promises, I don't think it would fundamentally change how they work to have an explicit return that indicates that nothing further should happen.

I'd be happy to review a pull request that causes both functions to return `null`.

Thanks for using Jasmine!

**Comment by JoshKaufman** [comment]
@marneborn We are not creating a promise inside of the `done` function so I don't see why bluebird would show the warning. 

I got a simple test running it doesn't show the warning

```javascript
it('no bluebird warning', function(done) {
  (new Promise(function(resolve, reject){
    resolve('test')
  })).then(function(value){
    expect(value).toBe('test')
  })
  .then(done, done.fail);
});
```

When I create a nested promise and don't return anything I get the warning

```javascript
it('bluebird warning', function(done) {
  Promise.resolve('test')
  .then(function(value){
    var nestedPromise = new Promise(function(resolve, reject){
      resolve(true);
   });
    expect(value).toBe('test');
  })
  .then(done, done.fail);
});
```


I tried returning `null` from the done function as you suggested but it didn't change anything.

maybe I'm missing something simple here.

**Comment by marneborn** [comment]
@JoshKaufman,  this is all a bit convoluted, I'll try to explain it better. Bluebird complains if a promise is created within the context of a handler (.then(fullfillmentHandler, rejectionHandler)) and that handler returns ```undefined```.

Here's an example that shows what Bluebird is trying to flag.
There is a promise create within the context of fn0 (in fn3) but the return value is ```undefined``` because I "forgot" the return in fn2. This is an easy bug to introduce and hard to track down.
```javascript
BPromise.resolve(1)
    .then(fn0);

function fn0 (val) {
    return fn1(2);
}

function fn1 (val) {
    return fn2(val);
}

function fn2 (val) {
    fn3(val);
}

function fn3 (val) {
    return BPromise.resolve(val);
}
```

This all means that you need more than one thing that uses a promise in the jasmine Queue to see the problem.
Here's a simple example.

```javascript
describe('suite for bluebird warnings', function() {
    beforeEach(function (done) {
        BPromise.resolve()
            .finally(done, done.fail);
    });

    it("create a promise test", function (done) {
        BPromise.resolve()
            .finally(done, done.fail);
    });
});
```

The promise in the test is created within the context of the ```done``` from the beforeEach, so the beforeEach's ```done``` needs to return null;

As an example to hopefully clarify that point, bluebird doesn't complain in this example.
```javascript
describe('suite for bluebird warnings', function() {
    beforeEach(function (done) {
        BPromise.resolve()
            .finally(
                function () { done(); return null; },
                function () { done.fail(); return null; }
            );
    });

    it("create a promise test", function (done) {
        BPromise.resolve()
            .finally(done, done.fail);
    });
```

The failure mechanism is a message being written to console.warn. This message has a stack trace so can get long. The test itself is OK, it's just that all of my console reporter output scrolls off the screen because of of the console.warn's from bluebird.

This is how I'm testing in the pull request I created.
```
  describe("a promise was created in a handler but none were returned from it", function () {
    // http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

    it("shouldn't complain about non-returned promises", function (outerDone) {
      spyOn(console, 'warn');

      env.describe('suite for bluebird warnings', function() {
        env.it("create a promise test", function (done) {
          BPromise.resolve()
            .then(function () {})
            .finally(done, done.fail);
        });
        env.it("create another promise test", function (done) {
          BPromise.resolve()
            .then(function () {})
            .finally(done, done.fail);
        });
        env.it("check if console.log was called", function () {
          expect(console.warn).not.toHaveBeenCalled();
          outerDone();
        });
      });
      env.execute();
    });
  });
```
