### ISSUE TITLE
spyOn report error: `Expected a spy, but got Function`

### ISSUE THREAD

**Issue by creeperyang** [jasmine/jasmine#996]
**code:**

```js
    let methods = {
        reportError() {},
        reportOk(which) {}
    };

    beforeAll((done) => {
        spyOn(methods, 'reportError').and.callThrough();
        smartSprite(options.source, options.output, options.retina).then((data) => {
            methods.reportOk('sprite');
            return generateStyle(options.output, options.stylePath, data[0], true, {
                retina: options.retina
            });
        }, (err) => {
            methods.reportError();
            done(err);
        }).then((data) => {
            methods.reportOk('style');
            done();
        }, (err) => {
            methods.reportError();
            done(err);
        });
    });
    
    it('should generate sprite successfully.', function() {
        expect(methods.reportError).not.toHaveBeenCalled();
        expect(methods.reportOk).toHaveBeenCalledWith('sprite');
    });
```

 `jasmine`'s version is 'v2.4.1'. And error info is `Error: Expected a spy, but got Function.`

**Comment by creeperyang** [comment]
After minutes, I found I miss `spyOn(methods, 'reportOk').and.callThrough();` :joy:

**Comment by reddynr** [comment]
I am writing karma test case to used spy.. getting below error
Expected spy offerCancelled to have been called.

here is my code.
var spy;
beforeEach(function () {
spy=spyOn($scope,'offerCancelled');
 $scope.offerCancelled=function(){

            };
 it('ModelCtrl Verification..', function (done) {
        console.log(compiledElement);
              expect($scope.offerCancelled).toHaveBeenCalled();
}

**Comment by slackersoft** [comment]
You'll see the error message that "Expected a spy, but got Function" when you use one of the matchers that expects to be used with a spy (like `toHaveBeenCalled()`), but the object you pass in isn't actually a spy.

In your case, it looks like you're overwriting the spy with another function immediately after you add it. Next time, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
