### ISSUE TITLE
jasmine.json docs

### ISSUE THREAD

**Issue by IngwiePhoenix** [jasmine/jasmine#997]
I am trying to wrap jasmine into my project. The project consists of many backends and parts, so it needs to have a rather specific folder structure.

```
test/
  - php/
    - ... PHP Testing stuff ...
  - node/
    - jasmine.json
    - tests/
```

Can I use `jasmine.json` to tell it:
- Where my tests are?
- How I want them reported?
- That I use ES2015/Babel?

Kind regards, Ingwie

**Comment by IngwiePhoenix** [comment]
Found it. I need to RTFM more...

**Comment by urish** [comment]
You can find the code that parses `jasmine.json` here:

https://github.com/jasmine/jasmine-npm/blob/793b7bb4f3ba4f420c7183b825ec477ebcf6eb52/lib/jasmine.js#L87
