### ISSUE TITLE
How can I pass multiple capabilities via cmdline?

### ISSUE THREAD

**Issue by allspat** [jasmine/jasmine#998]
I am trying something like -

--capabilities[{browserName=chrome,chrome.chdomeOptions.mobileEmulation.deviceName='Apple iPhone 6'}]

at the same time, I want my tests/methods to read the deviceName at runtime alike browser.params.browserName

**Comment by slackersoft** [comment]
I'm fairly certain this issue belongs on a different portion of your testing environment. No part of Jasmine even accepts a `capabilities` argument. Is this maybe a protractor feature?

Thanks for using Jasmine. Closing
